### ISSUE TITLE
getting users by customData filter

### ISSUE THREAD

**Issue by RubenBenBen** [QuickBlox/quickblox-ios-sdk#1003]
Hi, I added a ```NSDictionary``` to ```customData``` in ```QBUUser```s, and want to request users by filtering key values from customData. I've seen the filtering example filtering by ```last_request_at```:
```
NSMutableDictionary *filters = [NSMutableDictionary dictionary];
filters[@"filter[]"] = @"date last_request_at gt 2012-03-20T08:47:34Z";
 
[QBRequest usersWithExtendedRequest:filters page:[QBGeneralResponsePage responsePageWithCurrentPage:1 perPage:100] successBlock:^(QBResponse *response, QBGeneralResponsePage *page, NSArray *users) {
     // Request succeeded   
} errorBlock:^(QBResponse *response) {
     // Handle error  
}];
``` 

Is there a way to do this with ```customData```? or if no, maybe is there a way to add some custom properties to users? For example, my custom data is ```@"status:1"``` or ```@"status:0"```, I want to get users with ```@"status:1"```.

**Comment by pro100andrey** [comment]
> Is there a way to do this with `customData`?

NO, this is all params, operators, Allowed Field for filtering:

Param | Operator | Allowed types | Allowed fields | Value Example | Description
-- | -- | -- | -- | -- | --
filter[] | gt | number,string,date | id,full_name,email,login,phone,website,created_at,updated_at,last_request_at,external_user_id,twitter_id,facebook_id | number+id+gt+3 | Will return users withs IDs greater than 3
filter[] | lt | number,string,date | id,full_name,email,login,phone,website,created_at,updated_at,last_request_at,external_user_id,twitter_id,facebook_id | number+id+lt+34 | Will return users withs IDs less than 34
filter[] | ge | number,string,date | id,full_name,email,login,phone,website,created_at,updated_at,last_request_at,external_user_id,twitter_id,facebook_id | number+id+ge+445 | Will return users withs IDs greater than or equal to 445
filter[] | le | number,string,date | id,full_name,email,login,phone,website,created_at,updated_at,last_request_at,external_user_id,twitter_id,facebook_id | number+id+le+2241 | Will return users withs IDs less than or equal 2241
filter[] | eq | number,string,date | id,full_name,email,login,phone,website,created_at,updated_at,last_request_at,external_user_id,twitter_id,facebook_id | number+id+eq+3 | Will return a user withs ID equal to 3
filter[] | ne | number,string,date | id,full_name,email,login,phone,website,created_at,updated_at,last_request_at,external_user_id,twitter_id,facebook_id | number+id+ne+3 | Will return users withs IDs not equal to 3
filter[] | between | number,string,date | id,full_name,email,login,phone,website,created_at,updated_at,last_request_at,external_user_id,twitter_id,facebook_id | number+id+between+3,2241 | Will return users withs IDs between 3 and 2241
filter[] | in | number,string,date | id,full_name,email,login,phone,website,created_at,updated_at,last_request_at,external_user_id,twitter_id,facebook_id | number+id+in+3,45,2241 | Will return users withs IDs 3,45,2241

> For example, my custom data is @"status:1" or @"status:0", I want to get users with @"status:1".

Use tags or [custom objects](https://quickblox.com/developers/SimpleSample-customObjects-ios#With_filters), for example:

- Get users with tag - status 0
```objc
[QBRequest usersWithTags:@[@"status_0"] page:[QBGeneralResponsePage responsePageWithCurrentPage:1 perPage:100]
            successBlock:^(QBResponse *response, QBGeneralResponsePage *page, NSArray *users) {
                      // Successful response with page information and users array
} errorBlock:^(QBResponse *response) {
                      // Handle error
}];
```

- Get Custom objects with status 0

```objc
//Get custom object with status
[QBRequest objectsWithClassName:@"YourCustomObjectClass"
                extendedRequest:@{@"status" : @"0"}.mutableCopy
                   successBlock:^(QBResponse *response, NSArray<QBCOCustomObject *> *objects, QBResponsePage *page) {
                       QBCOCustomObject *obj = objects.firstObject;
                       //Get users with ids
                       [QBRequest usersWithIDs:@[@(obj.userID).stringValue]
                                          page:nil
                                  successBlock:^(QBResponse *response, QBGeneralResponsePage *page, NSArray<QBUUser *> *users) {
                                      
                                  } errorBlock:^(QBResponse * _Nonnull response) {
                                      
                                  }]
                       
                   } errorBlock:^(QBResponse *  response) {
                       
                   }];

```

Thanks

**Comment by pro100andrey** [comment]
Hi @RubenBenBen, any updates?

**Comment by RubenBenBen** [comment]
@pro100andrey thanks, I'll use these then.
