### ISSUE TITLE
Chat Accept/Reject at first time

### ISSUE THREAD

**Issue by vineeshtp** [QuickBlox/quickblox-ios-sdk#1004]
I have implemented QuickBlox chat for iOS.
IS there any provision for chat accept/reject at first time for the user.
Let me know any API available for the same

 - [ ] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [ ] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    | e.g. 8.0                                    |                                          
Quickblox iOS SDK version      | e.g. 2.7.6                                  |
QuickbloxWebRTC SDK version    | e.g. 2.2.1                                  |                               
Xcode Version                  | e.g. Xcode 8.1                              |
Repro with our demo sample     | e.g. does it happen with our demo sample?   |

**Did this work before?**

**Expected behavior**

**Actual behavior**

**Logs**

*Please use the following template for logs:*

To enable full logs use the following code:
```objc
[QBSettings setLogLevel:QBLogLevelDebug];
[QBSettings enableXMPPLogging];
```

<details>
<summary>Title for logs </summary>

```logos

// Your logs here

```

</details>

**Steps to reproduce the behavior**

**Any others comments**

**Comment by pro100andrey** [comment]
Hi @vineeshtp 

> IS there any provision for chat accept/reject at first time for the user.

What do you mean?

**Comment by pro100andrey** [comment]
if you mean ContactList Accept / Reject functionality use methods bellow:

```ojbc
// Accept
[[QBChat instance] confirmAddContactRequest:5645 completion:^(NSError * _Nullable error) {
 
}];
```
Reject
```objc
[[QBChat instance] rejectAddContactRequest:6555 completion:^(NSError * _Nullable error) {
 
}];
```
For more details check our documentation : [Chat Contact list](https://quickblox.com/developers/SimpleSample-chat_users-ios#Contact_list)

**Comment by vineeshtp** [comment]
I want to show an accept/rejecte button when a new chat request
received(first time only).

**Comment by Raikerian** [comment]
Hi,

This is a client-side feature, if you want help on how to do it, you can check our Q-muinicate app source code here: https://github.com/QuickBlox/q-municate-ios

Show UI notification whenever you are receiving contact request message.

**Comment by pro100andrey** [comment]
@vineeshtp  if you will have any other problems or questions please let us know by creating a separate issue.

Thanks
