### ISSUE TITLE
Incoming call with user name

### ISSUE THREAD

**Issue by vineeshtp** [QuickBlox/quickblox-ios-sdk#1005]
I have implemeted QuickBlox audio/video  call.
I have an issue, When a incoming call received it shows a number and appname.
Please find the attached image.
1. Showing the number
2. Appname + audio/video

How to replace this with call user name.

![img_0031](https://user-images.githubusercontent.com/2011379/39077600-e40b390a-4520-11e8-9d7f-10f3f1884954.png)

 - [ ] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [ ] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    | e.g. 8.0                                    |                                          
Quickblox iOS SDK version      | e.g. 2.7.6                                  |
QuickbloxWebRTC SDK version    | e.g. 2.2.1                                  |                               
Xcode Version                  | e.g. Xcode 8.1                              |
Repro with our demo sample     | e.g. does it happen with our demo sample?   |

**Did this work before?**

**Expected behavior**

**Actual behavior**

**Logs**

*Please use the following template for logs:*

To enable full logs use the following code:
```objc
[QBSettings setLogLevel:QBLogLevelDebug];
[QBSettings enableXMPPLogging];
```

<details>
<summary>Title for logs </summary>

```logos

// Your logs here

```

</details>

**Steps to reproduce the behavior**

**Any others comments**

**Comment by vineeshtp** [comment]
Any updates

**Comment by vineeshtp** [comment]
Please update.

**Comment by pro100andrey** [comment]
Hi @vineeshtp, Check https://developer.apple.com/documentation/callkit
