### ISSUE TITLE
Mute Opponent user voice in Video call

### ISSUE THREAD

**Issue by vineeshtp** [QuickBlox/quickblox-ios-sdk#1006]
How do I mute opponent Voice while video chat.
I could turn off video and audio together but, couldn't the mute voice.
The the documentation it self it not mentioned separate ,
https://quickblox.com/developers/Sample-webrtc-ios#Getting_Started_with_Video_Calling_API

Please let me know the property to be execute for mute voice while video call.

 - [ ] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [ ] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    | e.g. 8.0                                    |                                          
Quickblox iOS SDK version      | e.g. 2.7.6                                  |
QuickbloxWebRTC SDK version    | e.g. 2.2.1                                  |                               
Xcode Version                  | e.g. Xcode 8.1                              |
Repro with our demo sample     | e.g. does it happen with our demo sample?   |

**Did this work before?**

**Expected behavior**

**Actual behavior**

**Logs**

*Please use the following template for logs:*

To enable full logs use the following code:
```objc
[QBSettings setLogLevel:QBLogLevelDebug];
[QBSettings enableXMPPLogging];
```

<details>
<summary>Title for logs </summary>

```logos

// Your logs here

```

</details>

**Steps to reproduce the behavior**

**Any others comments**

**Comment by pro100andrey** [comment]
Hi @vineeshtp, Check or documentation again

https://quickblox.com/developers/Sample-webrtc-ios#Getting_Started_with_Video_Calling_API

```from 
//Called in case when receive remote audio track from opponent
- (void)session:(QBRTCSession *)session receivedRemoteAudioTrack:(QBRTCAudioTrack *)audioTrack fromUser:(NSNumber *)userID {
 
    // mute specific user audio track here (for example)
    // you can also always do it later by using '[QBRTCSession remoteAudioTrackWithUserID:]' method
    audioTrack.enabled = NO;
}
```
