### ISSUE TITLE
Video call receiver automatically in loudspeaker

### ISSUE THREAD

**Issue by vineeshtp** [QuickBlox/quickblox-ios-sdk#1007]
I have implemented video and voice chat. Both working but, in video call the receiver automatically change the voice to loudspeaker.

I tried to change forcefully to receiver by using the below lines of code but, not working.

- (void)session:(QBRTCSession *)session receivedRemoteVideoTrack:(QBRTCVideoTrack *)videoTrack fromUser:(NSNumber *)userID {
    
    if (session == self.session) {
        
        dispatch_async(dispatch_get_main_queue(), ^{
            
           QBRTCAudioDevice device = [QBRTCAudioSession instance].currentAudioDevice;
            
            if ( device == QBRTCAudioDeviceSpeaker) {
              
                [QBRTCAudioSession instance].useManualAudio = true;
                [QBRTCAudioSession instance].currentAudioDevice = QBRTCAudioDeviceReceiver;
            }
            
        });     
    }
}

 - [ ] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [ ] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    | e.g. 8.0                                    |                                          
Quickblox iOS SDK version      | e.g. 2.7.6                                  |
QuickbloxWebRTC SDK version    | e.g. 2.2.1                                  |                               
Xcode Version                  | e.g. Xcode 8.1                              |
Repro with our demo sample     | e.g. does it happen with our demo sample?   |

**Did this work before?**

**Expected behavior**

**Actual behavior**

**Logs**

*Please use the following template for logs:*

To enable full logs use the following code:
```objc
[QBSettings setLogLevel:QBLogLevelDebug];
[QBSettings enableXMPPLogging];
```

<details>
<summary>Title for logs </summary>

```logos

// Your logs here

```

</details>

**Steps to reproduce the behavior**

**Any others comments**

**Comment by pro100andrey** [comment]
> I have implemented video and voice chat. Both working but, in video call the receiver automatically change the voice to loudspeaker.

Yes,  this is the default behavior for video (Check any app). 

You can change this with:

```objc
//Set headphone or phone receiver
[QBRTCAudioSession instance].currentAudioDevice = QBRTCAudioDeviceReceiver;
```

**Comment by vineeshtp** [comment]
for the receiver it is not working. I could able to switch the speaker/receiver in  call intitiaor  side.

**Comment by Raikerian** [comment]
Hi,

Please show us code how you are initializing QBRTCAudioSession using initialize method.

**Comment by pro100andrey** [comment]
HI @vineeshtp, any updates?

**Comment by vineeshtp** [comment]
Thank you for the support.
