### ISSUE TITLE
App crashes while handling remote notification

### ISSUE THREAD

**Issue by dipendrapulse** [QuickBlox/quickblox-ios-sdk#1008]
**New Issue Checklist**

 - [ ] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [ ] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    | e.g. 11.3                                    |                                          
Quickblox iOS SDK version      | e.g. 2.16                                  |
QuickbloxWebRTC SDK version    | e.g. 2.2.1                                  |                               
Xcode Version                  | e.g. Xcode 9.3                              |
Repro with our demo sample     | e.g. does it happen with our demo sample?   |

**Did this work before?**
Not tested

**Expected behavior**
The chat should load

**Actual behavior**
App crashes

**Logs**

 [QBCore]: Response[1]:
headers: {
    "Access-Control-Allow-Origin" = "*";
    "Cache-Control" = "max-age=0, private, must-revalidate";
    Connection = "keep-alive";
    "Content-Length" = 124;
    "Content-Type" = "application/json; charset=utf-8";
    Date = "Tue, 24 Apr 2018 15:17:27 GMT";
    Duration = "1.836968";
    Etag = "W/\"12b620a10f866885151843e6321c8f86\"";
    "QuickBlox-REST-API-Version" = "0.1.1";
    Server = "nginx/1.8.1";
    "Set-Cookie" = "_mkra_ctxt=46d830e85811f83b30c318692511d72b--200; path=/; max-age=5; HttpOnly; secure";
    Status = "304 Not Modified";
    "Strict-Transport-Security" = "max-age=31536000, max-age=15768000;";
    "X-Content-Type-Options" = nosniff;
    "X-Frame-Options" = SAMEORIGIN;
    "X-Request-Id" = "179daeb9-e0eb-43f3-8293-311f0b800132";
    "X-Runtime" = "0.006734";
    "X-XSS-Protection" = "1; mode=block";
}
object: {
    "api_endpoint" = "https://api.quickblox.com";
    "chat_endpoint" = "chat.quickblox.com";
    "turnserver_endpoint" = "turn.quickblox.com";
}
2018-04-24 20:47:27.890946+0530 Leafpon[9841:4022148] [Core]: Account Settings: 
 apiEndpoint: https://api.quickblox.com
 chatEndpoint: chat.quickblox.com, 
 lastCheckDate: 2018-04-24 15:17:27 +0000
2018-04-24 20:47:27.891085+0530 Leafpon[9841:4022148] [QBCore]: Request[2]:
POST URL:https://api.quickblox.com/login.json
headers: {
    "Accept-Language" = "en-IN;q=1";
    "Content-Type" = "application/x-www-form-urlencoded";
    "QB-OS" = "iOS 11.3";
    "QB-SDK" = "iOS 2.16";
    "QB-Token" = 384798509c5810e16d0f5f58f952d5efac0109ea;
    "QuickBlox-REST-API-Version" = "0.1.1";
    "User-Agent" = "Leafpon/1.0 (iPhone; iOS 11.3; Scale/2.00)";
}
parameters: {
    email = "*****";
    password = *****;
}
2018-04-24 20:47:27.891203+0530 Leafpon[9841:4022148] [QBCore]: Request[3]:
POST URL:https://api.quickblox.com/subscriptions.json
headers: {
    "Accept-Language" = "en-IN;q=1";
    "Content-Type" = "application/x-www-form-urlencoded";
    "QB-OS" = "iOS 11.3";
    "QB-SDK" = "iOS 2.16";
    "QB-Token" = 384798509c5810e16d0f5f58f952d5efac0109ea;
    "QuickBlox-REST-API-Version" = "0.1.1";
    "User-Agent" = "Leafpon/1.0 (iPhone; iOS 11.3; Scale/2.00)";
}
parameters: {
    device =     {
        platform = ios;
        udid = "14FBC827-BB7A-4647-93A5-656EAFF1D436";
    };
    "notification_channels" = apns;
    "push_token" =     {
        "bundle_identifier" = "com.leafponapp.leafponapp";
        "client_identification_sequence" = 4f9d2bc1f4394947e59bafa390adc923166666db7569660f70a0e5b6253ee964;
        environment = development;
    };
}
2018-04-24 20:47:29.830569+0530 Leafpon[9841:4022145] [QBCore]: Response[2]:
headers: {
    "Access-Control-Allow-Origin" = "*";
    "Cache-Control" = "no-cache";
    Connection = "keep-alive";
    "Content-Length" = 419;
    "Content-Type" = "application/json; charset=utf-8";
    Date = "Tue, 24 Apr 2018 15:17:29 GMT";
    Duration = "1.938594";
    "QB-Token-ExpirationDate" = "2018-04-24 17:10:34 +0000";
    "QuickBlox-REST-API-Version" = "0.1.1";
    Server = "nginx/1.8.1";
    "Set-Cookie" = "_mkra_ctxt=bf35d45d91a0e3aad43981cff184539f--202; path=/; max-age=5; HttpOnly; secure";
    Status = "202 Accepted";
    "Strict-Transport-Security" = "max-age=31536000";
    "X-Content-Type-Options" = nosniff;
    "X-Frame-Options" = SAMEORIGIN;
    "X-Request-Id" = "596ba54b-4333-4d18-9621-b2990a388a8e";
    "X-Runtime" = "0.039771";
    "X-XSS-Protection" = "1; mode=block";
}
object: {
    user =     {
        "blob_id" = "<null>";
        "created_at" = "2018-02-19T10:18:52Z";
        "custom_data" = "";
        email = "****";
        "external_user_id" = "<null>";
        "facebook_id" = "<null>";
        "full_name" = "Dipendra Dubey";
        id = 43670289;
        "last_request_at" = "2018-04-24T15:17:29Z";
        login = "dipendra.dubey";
        "owner_id" = 49462;
        phone = 123456;
        "twitter_digits_id" = "<null>";
        "twitter_id" = "<null>";
        "updated_at" = "2018-04-24T15:10:10Z";
        "user_tags" = "<null>";
        website = "<null>";
    };
}
2018-04-24 20:47:29.915553+0530 Leafpon[9841:4022148] [ChatService]: Connecting with JID: 43670289-68074@chat.quickblox.com/14FBC827-BB7A-4647-93A5-656EAFF1D436
2018-04-24 20:47:30:332 Leafpon[9841:4803] SEND: <?xml version='1.0'?>
2018-04-24 20:47:30:333 Leafpon[9841:4803] SEND: <stream:stream xmlns='jabber:client' xmlns:stream='http://etherx.jabber.org/streams' version='1.0' to='chat.quickblox.com' from='43670289-68074@chat.quickblox.com'>
2018-04-24 20:47:30.945633+0530 Leafpon[9841:4022145] [QBCore]: Response[3]:
headers: {
    "Access-Control-Allow-Origin" = "*";
    "Cache-Control" = "max-age=0, private, must-revalidate";
    Connection = "keep-alive";
    "Content-Length" = 304;
    "Content-Type" = "application/json; charset=utf-8";
    Date = "Tue, 24 Apr 2018 15:17:30 GMT";
    Duration = "3.057674";
    Etag = "W/\"3cedcfb52382b6fbd8fde5c2cf63f086\"";
    "QB-Token-ExpirationDate" = "2018-04-24 17:17:29 +0000";
    "QuickBlox-REST-API-Version" = "0.1.1";
    Server = "nginx/1.8.1";
    "Set-Cookie" = "_mkra_ctxt=76eb0b30ac3cf0c41499ad8b61c29e58--201; path=/; max-age=5; HttpOnly; secure";
    Status = "201 Created";
    "Strict-Transport-Security" = "max-age=31536000, max-age=15768000;";
    "X-Content-Type-Options" = nosniff;
    "X-Frame-Options" = SAMEORIGIN;
    "X-Request-Id" = "9984640e-5b67-4b9a-8c4c-6cc92ca67b10";
    "X-Runtime" = "0.027275";
    "X-XSS-Protection" = "1; mode=block";
}
object: (
        {
        subscription =         {
            device =             {
                "bundle_identifier" = "com.leafponapp.leafponapp";
                "client_identification_sequence" = 4f9d2bc1f4394947e59bafa390adc923166666db7569660f70a0e5b6253ee964;
                platform =                 {
                    name = ios;
                };
                udid = "14FBC827-BB7A-4647-93A5-656EAFF1D436";
            };
            id = 43877944;
            "notification_channel" =             {
                name = apns;
            };
        };
    }
)

**Steps to reproduce the behavior**
i)The app is not running
ii)The device receive push notification
iii)On tapping push notification alert the app crashes
iv)I also have attached crashalytics screenshot

![image](https://user-images.githubusercontent.com/18593012/39197836-2e18352c-4803-11e8-8c06-14dcad8c6a99.png)

**Any others comments**

**Comment by pro100andrey** [comment]
@dipendrapulse,  if you will have any other problems or questions please let us know by creating a separate issue.
