### ISSUE TITLE
QBRequestGetBuilder - where array is NOT empty

### ISSUE THREAD

**Issue by prographo** [QuickBlox/quickblox-ios-sdk#1009]
How do I specify that a field should not be null, i.e. an array must have at least one member. I have read the documentation, but I could not see this.

**Comment by prographo** [comment]
This object allows you to specify criteria (fields, filters) when fetching custom objects or dialogs from the QuickBlox server. You can learn about it here: https://docsdev.quickblox.com/android/Chat/Dialogs.html

**Comment by prographo** [comment]
Ah, I posted in iOS, should have been in android.

**Comment by VitaliyGuru** [comment]
@prographo, yes, that's why we closed this issue.
