### ISSUE TITLE
How to start voice message recorder ?

### ISSUE THREAD

**Issue by Dharmikios** [QuickBlox/quickblox-ios-sdk#1011]
I was trying to send voice record message in demo but it is not working. It is just showing recording view but it not start recording. Can you please provide suggestion on this and let me know why it is not working.

I am working with swift and did this but same result. It is only showing record view but nothing is happening, no recording and no time increment.
Let me know if i am doing anything wrong and please provide steps for this in swift.

let recorderview = QMAudioRecordView()
func messagesInputToolbarAudioRecordingStart(_ toolbar: QMInputToolbar!) {
print("record start")
recorderviewaudioRecordingStarted()
}

**Comment by pro100andrey** [comment]
Duplicate https://github.com/QuickBlox/q-municate-ios/issues/335
