### ISSUE TITLE
How maintain media cell with play/push video or audio in swift ?

### ISSUE THREAD

**Issue by Dharmikios** [QuickBlox/quickblox-ios-sdk#1015]
I am working with swift and i reviewed demo app(https://github.com/QuickBlox/q-municate-ios) and find that for any media(video/audio) type message, for maintain their play/push you are using 

 [self.mediaController configureView:(id<QMMediaViewDelegate>)cell
                                withMessage:message];

Please help me on this how can i do this in swift. I already tried with conversion of methods but didn't get any result. Please provide me proper way to using this in swift.

I need to play audio and video messages by click on that.

**Comment by pro100andrey** [comment]
Hi @Dharmikios,

>I already tried with conversion of methods but didn't get any result.

Could you provide project example?

Thanks
