### ISSUE TITLE
QuickBlox : Error while trying to login into QBChat in iOS 9

### ISSUE THREAD

**Issue by hagile** [QuickBlox/quickblox-ios-sdk#102]
I'm trying to login into QuickBlox Chat (QBChat) but couldn't login into iOS9 (running via XCode7 beta). It was working great in iOS 7 and 8. An error logs the following in debug console:

2015-07-06 17:56:47.464 MyApp[25156:251907] xmppStreamDidConnect
2015-07-06 17:56:47.464 MyApp[25156:251907] -[QBChat xmppStreamDidConnect:] -> Trying TLS...
2015-07-06 17:56:47.910 MyApp[25156:251916] -[QBChat xmppStreamDidDisconnect:withError:] -> error: 
Error Domain=kCFStreamErrorDomainSSL Code=-9850 "The operation couldn’t be completed.
(kCFStreamErrorDomainSSL error -9850.)" UserInfo=0x7f9dd962e430 
{NSLocalizedRecoverySuggestion=Error code definition can be found in Apple's 
SecureTransport.h}
Today, I've updated my QuickBlox iOS SDK from 2.2 to 2.3. So I've setup everything as per they want.

Note, I'm able to create session but couldn't able to login into QBChat.

Here's my sample code:

    QBSessionParameters *parameters = [QBSessionParameters new];
    parameters.userLogin = ...;
    parameters.userPassword = ...;
    
    [QBRequest createSessionWithExtendedParameters:parameters successBlock:^(QBResponse *response, QBASession *session) {
        DLog(@"Success");
        
        QBUUser *user = [QBUUser user];        
        user.ID = ...;
        user.password = ...;

        [[QBChat instance] addDelegate:self];
        
        [[QBChat instance] setAutoReconnectEnabled:YES];
        
        BOOL requestQBChatLogin = [[QBChat instance] loginWithUser:user];
        if(!requestQBChatLogin) {
            //This will never prints in logs
            DLog(@"Something went wrong while sending request for QBChatLogin.");
        }
        
    } errorBlock:^(QBResponse *response) {
        DLog(@"Error: %@", response.error);
    }];

    -(void) chatDidLogin{
        //This will never call
        DLog(@"You have successfully signed in to QuickBlox Chat!");
    }
    
    - (void) chatDidNotLogin {
        //This will never call
        DLog(@"You have not signed in to QuickBlox Chat!");
    }

Please make sure that – I've added proper values for userName or ID or password as and when require.

**Comment by soulfly** [comment]
Thanks for reporting this

We will check this on iOS9 and let you know

**Comment by hagile** [comment]
@soulfly, any updates? Too long week! :(

**Comment by soulfly** [comment]
You can temporary disable Chat TLS for now

[QBSettings useTLSForChat:NO];

This fix will be released in a next iOS SDK release

**Comment by AndreyMoskvin** [comment]
Just checked QB SDK 2.3.0.1 on iOS 9 (device and simulator) - I'm able to login to chat.
