### ISSUE TITLE
DeviceTokenNotForTopic when sending VoIP Push

### ISSUE THREAD

**Issue by jlubeck** [QuickBlox/quickblox-ios-sdk#1020]
I'm having issues getting the VoIP to work when my app is in the background.
After going through a few issues here on github, I was able to find the queue of messages inside my app. I see that they show up as sent, but failed. And here is an example of one:

```json
{
    "notification": {
        "id": 343,
        "badge": null,
        "device_token": "797720f384513ee0c77151638fd4ffb2b80c41d76ff54fa71b87a3527f097161",
        "sound": null,
        "alert": "name is calling you.",
        "data": {
            "VOIPCall": "1",
            "headers": {
                "apns-topic": "com.realstir.app.voip"
            }
        },
        "expiry": 86400,
        "delivered": false,
        "delivered_at": null,
        "failed": true,
        "failed_at": "2018-05-07T05:15:00+00:00",
        "fail_after": "2018-05-07T06:14:59+00:00",
        "retries": 0,
        "error_code": 400,
        "error_description": "DeviceTokenNotForTopic",
        "deliver_after": null,
        "alert_is_json": null,
        "app_id": 10,
        "collapse_key": null,
        "delay_while_idle": null,
        "registration_ids": null,
        "uri": null,
        "priority": null,
        "url_args": null,
        "category": null,
        "content_available": false,
        "mutable_content": false,
        "notification": null,
        "type": "Rpush::Client::Redis::Apns::Notification",
        "event_id": 242,
        "event_date": "2018-05-07T05:14:58+00:00"
    },
    "log": [{
        "device_token": "797720f384513ee0c77151638fd4ffb2b80c41d76ff54fa71b87a3527f097161",
        "delivered_at": null,
        "failed_at": "2018-05-07T05:15:00+00:00",
        "error_code": 400,
        "error_description": "DeviceTokenNotForTopic"
    }]
}
```

What does that DeviceTokenNotForTopic mean? and where is that com.realstir.app.voip coming from? I'm not seeing that bundle id anywhere inside my app... Maybe that's got something to do with this... The bundle ID on my app (and on the certificate that I uploaded to the admin portal) is just com.realstir.app . 

Oh, I DO see a valid APNS VOIP subscription on the Subscriptions tab. So that seems to be working fine...

And regular push notifications from the chat service work fine as well on the same device

Thank you

**Comment by pro100andrey** [comment]
Hi @jlubeck 

This error is returned from the Apple Push Notification service (APNs) when the presented push notifications token attributes does not match the topic specified at the time of sending. In the context of Quickblox Platform this means the token was issued to an app with a given Apple App ID but the server push SSL certificate is configured for another Apple App ID. When the service is sending the push notifications to APNs they determine the topic (usually this is the App ID) and know how to address the notification to the particular device. In this case the topic does not match on the device, hence the error.

Solution:

Ensure that the Apple App ID of the provisioning profile with which the application is deployed to a device is matching the Apple App ID for which the server push SSL certificate is configured. For example, you have deployed the app with the provisioning profile for com.realstir.app.voip but on the server you have uploaded a push certificate for com.realstir.app.voip.

**Comment by pro100andrey** [comment]
@jlubeck, how many certificates are you using?

**Comment by Raikerian** [comment]
@jlubeck you can check certificates in your admin panel: Push Notifications -> Settings.
Tell us how many certificates are there and what their types are. Or rather make a screenshot of that page so we can see ourselves.

**Comment by pro100andrey** [comment]
Hi @jlubeck,

For fixing your issue with DeviceTokenNotForTopic you should:

1) Remove all certificates from your admin panel
2) Upload the Universal (sandbox & production & voip) certificate with `com.realstir.app` bundle.

Thanks.

**Comment by jlubeck** [comment]
Yup! That fixed it! I still see `com.realstir.app.voip` on the logs, but now it's working. 
Thanks!

**Comment by prohoney** [comment]
I had 3 issues where all needed to be fixed
- wrong cert. It belonged to a different bundleID
- wrong bundleID
- wrong build, that is we didn't have a sandbox environment to send notifications for our debug builds or something I guess. Solution to that problem was to send notifications to a release build, not debug builds...

**Comment by ibmmt** [comment]
From the documentation you linked to:

voip:

If you set this push type, the apns-topic header field must use your app’s bundle ID with .voip appended to the end.

Therefore you must specify apns-topic as ao.medicare.app.voip

https://stackoverflow.com/a/76184904/3244767
