### ISSUE TITLE
CustomObject UIImage not updating

### ISSUE THREAD

**Issue by RubenBenBen** [QuickBlox/quickblox-ios-sdk#1024]
Hi guys, I was saving an ```UIImage``` to CustomObject as a ```string``` property:
```objc
    QBCOCustomObject *object = [QBCOCustomObject customObject];
    object.className = @"UserInfo"; // your Class name
    object.ID = self.currentUserInfo.ID;
    if (image) {
        [object.fields setObject:[DataHelperMethords imageToNSString:image] forKey:@"image"];
    }
    
    [QBRequest updateObject:object successBlock:^(QBResponse * _Nonnull response, QBCOCustomObject * _Nullable object) {
        self.currentUserInfo = object;
        if (successBlock) {
            successBlock();
        }
    } errorBlock:^(QBResponse * _Nonnull response) {
        if (failBlock) {
            failBlock();
        }
    }];
```
 Everything was ok until today. Now it doesn't update and just returns the previous object in successBlock, I am assuming you added a limitation to the string property characters count?

**Comment by pro100andrey** [comment]
Hi @RubenBenBen, could you provide full logs with gist?

**Comment by RubenBenBen** [comment]
@VitaliyGuru thanks, I've seen this, but is it possible to upload a file in the same request? I want to update everything with 1 request, with ```[QBRequest updateObject:object]``` method by setting object fields ```[object.fields setObject:object]```, is it possible to do the same thing with files also?

**Comment by RubenBenBen** [comment]
@pro100andrey [https://gist.github.com/RubenBenBen/3c73f3c935271d89c27a212b20f0232e](log)
now it actually fails, was getting success with previous object earlier.

**Comment by pro100andrey** [comment]
PUT URL:https://api.quickblox.com/data/UserInfo/(null)

check object.ID = self.currentUserInfo.ID;

is 0

**Comment by RubenBenBen** [comment]
@pro100andrey sry my bad, here is the working [logs](https://gist.github.com/RubenBenBen/59adf88549028f7dfd7ac65bf981b3e3)

**Comment by RubenBenBen** [comment]
@pro100andrey thanks, I've seen this, but is it possible to upload a file in the same request? I want to update everything with 1 request, with [QBRequest updateObject:object] method by setting object fields [object.fields setObject:object], is it possible to do the same thing with files also?

**Comment by RubenBenBen** [comment]
@pro100andrey I've tried uploading image it with file property, but it doesn't seem to work:
```
    QBCOCustomObject *object = [QBCOCustomObject customObject];
    object.className = @"UserInfo"; // your Class name
    object.ID = self.currentUserInfo.ID;

    [object.fields setObject:@(time) forKey:@"time"];
    if (image) {
        QBCOFile *file = [QBCOFile file];
        file.name = @"img";
        file.contentType = @"image/png";
        file.data = UIImagePNGRepresentation(image);
        [object.fields setObject:file forKey:@"image"];
    }
    
    
    [QBRequest updateObject:object successBlock:^(QBResponse * _Nonnull response, QBCOCustomObject * _Nullable object) {
        self.currentUserInfo = object;
        if (successBlock) {
            successBlock();
        }
    } errorBlock:^(QBResponse * _Nonnull response) {
        if (failBlock) {
            failBlock();
        }
    }];
```

and it just returns the object with empty data. Here are the full [logs](https://gist.github.com/RubenBenBen/d3b2073ab79fe2d737329df95a29e681) :

**Comment by pro100andrey** [comment]
@RubenBenBen 

> I've seen this, but is it possible to upload a file in the same request?

- is not possible


From [documentation](https://quickblox.com/developers/SimpleSample-customObjects-ios#Files).
**Files**
Custom Objects module supports the `File` field type. It is created to easily work with content from Custom Objects module. There is an ability to upload, download, update and delete content of file fields.

The max file size is 32 MB.

Uploading/Updating a file

```
QBCOFile *file = [QBCOFile file];
file.name = @"plus";
file.contentType = @"image/png";
file.data = [NSData dataWithContentsOfFile:[[NSBundle mainBundle] pathForResource:@"plus" ofType:@"png"]];
 
[QBRequest uploadFile:file className:@"Movie" objectID:@"5256c265535c128020000182" fileFieldName:@"image" successBlock:^(QBResponse *response) {
    // uploaded
} statusBlock:^(QBRequest *request, QBRequestStatus *status) {
    // handle progress            
} errorBlock:^(QBResponse *response) {
    // error handling
    NSLog(@"Response error: %@", [response.error description]);
}];
```
