### ISSUE TITLE
session hangUp removing video track from another session

### ISSUE THREAD

**Issue by RubenBenBen** [QuickBlox/quickblox-ios-sdk#1026]
Hi guys, I'm trying to handle the case when 2 users call each other simultaneously, so there are 2 sessions created. Here is how I'm handling it in my sessionHandler:
```
- (void)didReceiveNewSession:(QBRTCSession *)session userInfo:(NSDictionary *)userInfo {
    NSLog(@"RECEIVED NEW SESSION");
    if (self.session != nil) {
       ...
        if (self.opponentUser.ID == [session.initiatorID unsignedIntegerValue]) {
            if (Core.currentUser.ID > self.opponentUser.ID) {
                [session rejectCall:@{@"reject" : @"111"}];
                return;
            } else {
                [self.callTimer invalidate];
                self.callTimer = nil;
                [self.session hangUp:@{@"hangup" : @"222" }];
                self.session = nil;
                self.callUUID = nil;
            }
        }
    }

    self.session = session;
    self.session.localMediaStream.videoTrack.videoCapture = self.cameraCapture;
    [self acceptCall];
}
```
So, basically I have two sessions: session1 by user1 and session2 by user2, and I close the session whose creator (user1) has lower ID. The problem is that when the user1 closes his session1 and calls ```[self.session hangUp:@{@"hangup" : @"222" }];```, it removes the videoCapture from video track of the **new** session2 after 1-2 seconds, so user2 doesn't get `remoteVideoTrack` from user1 (but user1 gets track from user2). Here is the [log](https://gist.github.com/RubenBenBen/78c08a32e1a3f80bb0cefc2a1575da4b) (some logs are disabled).

P.S. I'm starting camera capture session **before** any calls.

**Comment by Raikerian** [comment]
Hi,

You must assign self.cameraCapture to localMediaStream videoTracks' videoCapture of your choice. In the code snippet you have provided you are setting it to the self.session's localMediaStream. Make sure that this is the correct session. And also look if there is any other code that might override videoCapture.

**Comment by Raikerian** [comment]
Try setting nil to the old session videoCapture, before assigning it to the new one. When QBRTCSession deallocating it does not stop your videoCapture, but do, in fact, clear old local video track from it (basically just setting nil for you in the old videoTrack). This should not be the problem in your situation, but in case there are some racing conditions occurs, try the suggestion above.

If it won't work, please try the same with the latest 2.7 framework and report back, there were some changes regarding this (as you are using ver. 2.6.3).

**Comment by RubenBenBen** [comment]
@Raikerian thanks, it worked.

**Comment by Raikerian** [comment]
@RubenBenBen if possible, please check your old code (without implementing suggestions above) with latest 2.7 framework. Thanks in advance.

**Comment by RubenBenBen** [comment]
@Raikerian if I comment ` self.session.localMediaStream.videoTrack.videoCapture = nil; ` this line, the bug still exists in v. 2.7.
