### ISSUE TITLE
can't upload file with new framework

### ISSUE THREAD

**Issue by RubenBenBen** [QuickBlox/quickblox-ios-sdk#1027]
Hi again, I just updated my quickblox frameworks to the latest ones and now the file upload returns an 401 error. Here is the code I'm using, it worked fine with v.2.6.3:
```
        QBCOFile *file = [QBCOFile file];
        file.name = @"img";
        file.contentType = @"image/png";
        file.data = UIImagePNGRepresentation(image);
        
        [QBRequest uploadFile:file className:@"UserInfo" objectID:self.currentUserInfo.ID fileFieldName:@"image" successBlock:^(QBResponse * _Nonnull response, QBCOFileUploadInfo * _Nullable info) {

        } statusBlock:^(QBRequest * _Nonnull request, QBRequestStatus * _Nonnull status) {

        } errorBlock:^(QBResponse * _Nonnull response) {
            NSLog(@"%@", response);
        }];
``` 

Here are full [logs](https://gist.github.com/RubenBenBen/b46ed217f542be07db59b9a35ed54b0b)

**Comment by pro100andrey** [comment]
Hi @RubenBenBen, thanks for the report! Tomorrow will be fixed it.

**Comment by pro100andrey** [comment]
Fixed, See [changelog](https://github.com/QuickBlox/quickblox-ios-sdk/releases/tag/2.17.1).

Thanks.
