### ISSUE TITLE
How to Upload audio in message attachment?

### ISSUE THREAD

**Issue by riteshpatel0** [QuickBlox/quickblox-ios-sdk#1028]
Hi,

I am not able to upload audio on Quickblox server? How can I attach my audio in message and upload into Quickblox server.

Thank you.

**Comment by VitaliyGuru** [comment]
@riteshpatel0, Hello.
Just follow the [Quickblox documentation](https://quickblox.com/developers/SimpleSample-chat_users-ios#Send_and_receive_a_message_with_attachment).

**Comment by riteshpatel0** [comment]
Hello @VitaliyGuru ,

How to identify text and audio message type from the all messages.

Thanks.

**Comment by VitaliyGuru** [comment]
When you create an attachment you should provide its type, e.g. `"audio"`.
Then you can check the attachment type in the received message like in the method below:

```
static NSString * const kQMChatAudioMessageTypeName = @"audio";

- (BOOL)isAudioAttachment:(QBChatMessage *)message {
    
    __block BOOL isAudioAttachment = NO;
    
    [message.attachments enumerateObjectsUsingBlock:^(QBChatAttachment * _Nonnull obj, NSUInteger __unused idx, BOOL * _Nonnull stop) {
        
        if ([obj.type isEqualToString:kQMChatAudioMessageTypeName]) {
            isAudioAttachment = YES;
            *stop = YES;
        }
    }];
    
    return isAudioAttachment;
}
```

**Comment by pro100andrey** [comment]
Hi @riteshpatel0, any updates?

**Comment by riteshpatel0** [comment]
Hi @pro100andrey ,

We are doing attachment below way, is it perfect?. can you check below code,

We are upload image using below code,
 
QBRequest.tUploadFile(audioData!, fileName: soundFileName, contentType: "audio/m4a", isPublic: false, successBlock: { (response : QBResponse!, uploadedBlob :QBCBlob!) -> Void inQBRequest.tUploadFile(audioData!, fileName: soundFileName, contentType: "audio/m4a", isPublic: false, successBlock: { (response : QBResponse!, uploadedBlob :QBCBlob!) -> Void in

--------------------------
We are get content id from the above method and we set id as a attachment id, please check below code, is it right way?

                let message = QBChatMessage()
                let attachment = QBChatAttachment()
                attachment.id = String(uploadedBlob.id)
                attachment.attachmentType = .contentTypeAudio
                message.attachments = [attachment]
                message.senderID = UInt(self.senderID)
                message.deliveredIDs = [(NSNumber(value: self.senderID))]
                message.readIDs = [(NSNumber(value: self.senderID))]
                message.markable = true
                message.dateSent = Date()
                message.messageType = .contactRequest
                message.dialogName = (self.dialog?.name)!
                
                let params: NSMutableDictionary = NSMutableDictionary()
                params["save_to_history"] = true
                message.customParameters = params
                self.chatDataSource.add(message)
                self.sendMessage(message: message)

**Comment by riteshpatel0** [comment]
Hello @pro100andrey ,

Is any update ?

Thanks.

**Comment by VitaliyGuru** [comment]
@riteshpatel0, 
As for

> We are get content id from the above method and we set id as a attachment id, please check below code, is it right way?

Yes, this is the right way to handle attachments.

**Comment by VitaliyGuru** [comment]
> We are upload image using below code,

Apparently, you've been mistaken and meant the audio uploading instead of the image uploading
