### ISSUE TITLE
remoteVideoTrack image load callback

### ISSUE THREAD

**Issue by RubenBenBen** [QuickBlox/quickblox-ios-sdk#1029]
Hi guys, in my app when I make a video call to a user, I want to know when his remoteVideoTrack frame is set to my `QBRTCRemoteVideoView` and is visible. I only found two methods:
``` - (void)session:(QBRTCSession *)session receivedRemoteVideoTrack:(QBRTCVideoTrack *)videoTrack fromUser:(NSNumber *)userID ``` and ``` - (void)videoView:(QBRTCRemoteVideoView *)videoView didChangeVideoSize:(CGSize)size ```, but both of them are called before the user's video is visible. Is there a way to observe when the video is visible?

**Comment by RubenBenBen** [comment]
I call `setVideoTrack:` in `receivedRemoteVideoTrack`, but **image** is **visible** when ```- (void)videoView:(QBRTCRemoteVideoView *)videoView didChangeVideoSize:(CGSize)size``` is called, I can track it that way in iOS 9.3. But when running on ios version > 9, it is loaded with delay and the following is logged: 

[CAMetalLayerDrawable texture] should not be called after already presenting this drawable. Get a nextDrawable instead.

**Comment by Raikerian** [comment]
There is no really a way to know when the video will exactly be processed on screen, but you do start receiving frames when you have received video track. Of course, it might take some time to process the first frame on the screen, but that's about it.

How is this feature crucial for you? Give us some use cases. We might take a look if there is a way to get such internal notification.

**Comment by RubenBenBen** [comment]
I have a timer which needs to start exactly when opponent is visible, so it is really important for my app. Actually, I can track it on iOS 9, ```- (void)videoView:(QBRTCRemoteVideoView *)videoView didChangeVideoSize:(CGSize)size``` is called when the first frame is received, so it works in 100% cases. My problem is when I run it on iOS 11 (iPhone 6s) I get a warning " [CAMetalLayerDrawable texture] should not be called after already presenting this drawable. Get a nextDrawable instead" when ```- (void)videoView:(QBRTCRemoteVideoView *)videoView didChangeVideoSize:(CGSize)size``` method is called first time, but the frame is received after 3-4 seconds and the same method is called again 1-2 times.

**Comment by Raikerian** [comment]
The warning has nothing to do with it really. But I can suggest you force OpenGLES drawings instead of Metal, for now, just do this:
`QBRTCRemoteVideoView.preferMetal = NO;`

Let me know if that will achieve something you are looking for.

**Comment by RubenBenBen** [comment]
thanks, will try and update it later today

**Comment by RubenBenBen** [comment]
I tested it on iPhone X too, and actually it was crashing on the same warning. But your suggestion helped, it works perfect now.

**Comment by Raikerian** [comment]
Yeah, we will take a look at the Metal drawings problems in the next release. OpenGLES is the best for now.
Does our sample in this repository also crashes on your iPhone X with Metal drawings, or is this specific to your project? Would be helpful.

**Comment by RubenBenBen** [comment]
I've tested it on my project, but it should crash on the sample project as well, as the only difference is that I start my camera capture session before video calling. I can test it on sample project too when I have access to iPhone X again (I borrowed it yesterday for testing).

**Comment by Raikerian** [comment]
It will be helpful if you can get the case, where it crashes constantly. It is also probably not related to iPhone X, but perhaps to a specific use case of QBRTCRemoteVideoView. If you cannot narrow it down to what causing this then sure, close it.

**Comment by RubenBenBen** [comment]
Ok, it just may take some time, cause I need iPhone X to get the warning about metal, cause my default testing device is iPhone 4.

**Comment by Raikerian** [comment]
Keep in mind that Metal only available with A7 processors or higher.

**Comment by proactive-solutions** [comment]
I am also facing the same issue with `Xcode 10`. Using the sample code from `sample-videochat-webrtc-swift`

**Comment by QB-vladyslav-vyshniak** [comment]
The status of the ticket changed to "Closed" due to inactivity.
If the reported issue is still actual for you - please reopen the ticket.
