### ISSUE TITLE
How to delete group dialog without leave from the group ?

### ISSUE THREAD

**Issue by Dharmikios** [QuickBlox/quickblox-ios-sdk#1030]
I need to clear group dialog conversation without leave group for me only. I need to do same like single user chat "Delete" on right swipe. 
For now group dialog has leave option but i don't want to leave group, i just need to clear group dialog for me. 

I tried with this same method used in single user dialog delete, But it is not working for group dialog. Calling this method for group leads to Leave group instead of delete dialog. Please help me on this how can i do this.

    ServicesManager.instance().chatService.deleteDialog(withID: dialogData.id!)

**Comment by pro100andrey** [comment]
Hi @Dharmikios, try

1) ServicesManager.instance().chatService.dialogsMemoryStorage.deleteChatDialog(withID:...
2) ServicesManager.instance().chatService.messagesMemoryStorage.deleteMessages(withDialogID:...
3) QMChatCache.instance.deleteDialog(WithID:...
4) QMChatCache.instance.deleteMessages(WithDialogID:...
5) Update your UI.

**Comment by Dharmikios** [comment]
Hello @pro100andrey ,
I tried both but it is not working. I also tried this methods in demo code but it is not working. It is always leaving group instead of delete.  Can you please check this same in demo at your side and let me know if i am doing anything wrong.

**Comment by Dharmikios** [comment]
@pro100andrey is there any update ?

**Comment by Dharmikios** [comment]
@pro100andrey is there any update ?

**Comment by QB-vladyslav-vyshniak** [comment]
The status of the ticket changed to "Closed" due to inactivity.
If the reported issue is still actual for you - please reopen the ticket.
