### ISSUE TITLE
I am not able to delete chat dialog.

### ISSUE THREAD

**Issue by riteshpatel0** [QuickBlox/quickblox-ios-sdk#1031]
Hello,

I am getting below error when I am try to delete chat dialog,
"{
    errors =     (
        "You don't have appropriate permissionsError while remove dialogs.
 to perform this operation"
    );
}"

------------------------------------------------------------------------------------------
Below my code for delete chat dialog,

QBRequest.deleteDialogs(withIDs: setDialog, forAllUsers: false, successBlock: { (response, deletedId, notFoundId, wrongPermissionId) in
                self.webServiceCall(Path.ClearChatHistory,parameter: ["user_id":_theUser.userId!]) { (json, error) in
                    self.showTostMessage(json["message"].stringValue,nil)
                }
            }, errorBlock: { (response) in
  
                print("Error while remove dialogs.")
            })

**Comment by pro100andrey** [comment]
Hi @riteshpatel0, could you provide full logs with [gist](gist.github.com)?

**Comment by pro100andrey** [comment]
Hi @riteshpatel0, Could you provide full logs from the start of the application till this issue.
