### ISSUE TITLE
How to accept call from anywhere in iOS? 

### ISSUE THREAD

**Issue by SalmanGhumsani** [QuickBlox/quickblox-ios-sdk#1032]
Basically, I want to accept the call anywhere in my iOS application is there notification fired by the webRTC?

I have 20 UIViewController so how to implement the same functionality to open the CallViewController?

**Comment by Raikerian** [comment]
Hi,

I will assume that currently, you have you call handlers (by that I mean you are handling call notifications) in 1 view controller, while you have 19 others. If that's wrong let me know.
So what you need to do, is basically, move your call handlers to some long living class (maybe you have 1 specific view controller that is always in memory? or you have 1 class that is always in memory like AppDelegate). You can see the example in our app Q-municate. Here we have a call manager class, which is singleton (always in memory), handling all calls for us and opens Call UI whenever it is needed: https://github.com/QuickBlox/q-municate-ios/blob/master/Q-municate/Classes/Core/QMCallManager/QMCallManager.m

**Comment by SalmanGhumsani** [comment]
@Raikerian Thank you very much :)
