### ISSUE TITLE
Persistent User login

### ISSUE THREAD

**Issue by haarj** [QuickBlox/quickblox-ios-sdk#1034]
Question:

Is there a way to persistent a current user login without having to login every time a user needs to connect to the chat?

**Comment by Raikerian** [comment]
Hi,

What login method are using? Email or social provider? I guess you are asking if there is a way to login into QBChat without loggin in with QBRequest, right?

**Comment by haarj** [comment]
Hi @Raikerian,

Yes I am using email and the ServicesManager's authservice object to login every time.

**Comment by Raikerian** [comment]
You can skip QBRequest login before QBChat login. but only if you are using login by email or password. You cannot skip it if you are using social provider login cause you always need to check for token not being expired, as that token used as password to connect to the chat.

**Comment by haarj** [comment]
Great. Thanks!
