### ISSUE TITLE
How can I implement message pagination in chat ?

### ISSUE THREAD

**Issue by gosaitarun** [QuickBlox/quickblox-ios-sdk#1039]
Hello,

I working on the chat application in which I have implemented the chat with QuickBlox.
In chat, I want to implement the pagination but right now they return only 100 messages.

List Response:
{
    items =     (
    );
    limit = 100;
    skip = 0;
}

So, how can I do that?
Thanks!

**Comment by pro100andrey** [comment]
Hi @gosaitarun, check this answer https://github.com/QuickBlox/quickblox-ios-sdk/issues/1037

**Comment by pro100andrey** [comment]
@gosaitarun, any updates?

**Comment by gosaitarun** [comment]
Hello @pro100andrey,

Yes, it's working..!!!

Thanks!
