### ISSUE TITLE
I am integrating quickblox in one of my app, in which i have successfully integrated chat functionality. now as per the requirement i need to display each user thumbnail on chat screen if it is a group. can some one suggest me how to achieve this.

### ISSUE THREAD

**Issue by justashish00** [QuickBlox/quickblox-ios-sdk#1044]
**New Issue Checklist**

 - [x] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [x] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    | e.g. 8.0                                    |                                          
Quickblox iOS SDK version      | e.g. 2.7.6                                  |
QuickbloxWebRTC SDK version    | e.g. 2.2.1                                  |                               
Xcode Version                  | e.g. Xcode 8.1                              |
Repro with our demo sample     | e.g. does it happen with our demo sample?   |

**Did this work before?**

**Expected behavior**

**Actual behavior**

**Logs**

*Please use the following template for logs:*

To enable full logs use the following code:
```objc
[QBSettings setLogLevel:QBLogLevelDebug];
[QBSettings enableXMPPLogging];
```

<details>
<summary>Title for logs </summary>

```logos

// Your logs here

```

</details>

**Steps to reproduce the behavior**

**Any others comments**

**Comment by Raikerian** [comment]
Hi,

This is a very generic question and does not have to do anything with Quickblox.
However, I can suggest you look at our projects, such as:
[sample-chat](https://quickblox.com/developers/SimpleSample-chat_users-ios) - simple sample with basic dialogs and messages representation with users to chat with ([github link](https://github.com/QuickBlox/quickblox-ios-sdk/tree/master/sample-chat))
[Q-municate](https://quickblox.com/developers/Q-municate) - powerful chat application with a wide range of communication features included. All sample features included and many more ([github link](https://github.com/QuickBlox/q-municate-ios)).

I have linked both documentation and github project. Please check out both for your needs.
