### ISSUE TITLE
Getting wrong unread count and last message

### ISSUE THREAD

**Issue by gosaitarun** [QuickBlox/quickblox-ios-sdk#1045]
Hello,

I am working in chat application with QuickBlox,
When I get a list of all dialog sometimes I got the wrong count of the unread message.
This issue special occurs when I am clear all message with using method QBRequest.deleteMessages
so that's a reason they also show me wrong last message.

Thanks!

**Comment by gosaitarun** [comment]
Hello @pro100andrey,

--> I have load all the message with using this method, 

QBRequest.messages(withDialogID: currentDialogID, extendedRequest: ["sort_desc" : "date_sent"], for: resPage, successBlock: {(response: QBResponse, messages: [QBChatMessage]?, responcePage: QBResponsePage?) in

}, errorBlock: {(response: QBResponse!) in
          
 })

but still, they showing me greater than 0 unread counts,

--> I have also tried below method too, but it's not worked

QBRequest.totalUnreadMessageCountForDialogs(withIDs: Set<String>, successBlock: <#T##qb_response_unread_messages_block_t?##qb_response_unread_messages_block_t?##(QBResponse, UInt, [String : Any]) -> Void#>, errorBlock: <#T##qb_response_block_t?##qb_response_block_t?##(QBResponse) -> Void#>)

so, how can I solve that issue is there any other way to get a correct unread count?

Thanks!

**Comment by pro100andrey** [comment]
Hi @gosaitarun, By default `QBRequest.messages(...`  mark messages as read. 

From our [documentation](https://quickblox.com/developers/SimpleSample-chat_users-ios#List_chat_messages):

>By default all messages will be marked as read after this request but you can skip this logic with a filter mark_as_read=0, just pass it into extendedRequest.

Thanks

**Comment by pro100andrey** [comment]
Hi @gosaitarun, any updates?

**Comment by pro100andrey** [comment]
Hi @gosaitarun, any updates?

**Comment by haarj** [comment]
@soulfly I think the reason is because the updateAt properties are the same here.

**Comment by QB-vladyslav-vyshniak** [comment]
The status of the ticket changed to "Closed" due to inactivity.
If the reported issue is still actual for you - please reopen the ticket.
