### ISSUE TITLE
Thread 1: EXC_BAD_ACCESS (code=1, address=0x20) When subView

### ISSUE THREAD

**Issue by vineeshtp** [QuickBlox/quickblox-ios-sdk#1047]
I have implemented the sample application (both chat,video, audio). provided by quickBox.

Now I am facing an issue. I could make audio call success fully.
On Video call, I can get call using VOIP and successfully my custom video calling screen came.
But, after receiving the remote video delegate method,

> receivedRemoteVideoTrack

I can see the remote video for second suddenly get crashed on Appdelegate. error message is shown below,
Thread 1: EXC_BAD_ACCESS (code=1, address=0x20)

I already posted the issue in Stackoverflow with quickBlox tag.

https://stackoverflow.com/questions/50665149/thread-1-exc-bad-access-code-1-address-0x20-when-subview?noredirect=1#comment88340867_50665149

**New Issue Checklist**

 - [ ] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [ ] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    | e.g. 8.0                                    |                                          
Quickblox iOS SDK version      | e.g. 2.7.6                                  |
QuickbloxWebRTC SDK version    | e.g. 2.2.1                                  |                               
Xcode Version                  | e.g. Xcode 8.1                              |
Repro with our demo sample     | e.g. does it happen with our demo sample?   |

**Did this work before?**

**Expected behavior**

**Actual behavior**

**Logs**

*Please use the following template for logs:*

To enable full logs use the following code:
```objc
[QBSettings setLogLevel:QBLogLevelDebug];
[QBSettings enableXMPPLogging];
```

<details>
<summary>Title for logs </summary>

```logos

// Your logs here

```

</details>

**Steps to reproduce the behavior**

**Any others comments**

**Comment by pro100andrey** [comment]
duplicated https://github.com/QuickBlox/quickblox-ios-sdk/issues/1029
