### ISSUE TITLE
Unable to get push notification via messaging or voip manually

### ISSUE THREAD

**Issue by SalmanGhumsani** [QuickBlox/quickblox-ios-sdk#1048]
Hi team,

I have uploaded my APNS certificate on the admin panel setting tab, All messages are coming via admin panel but not coming when I send the message to anyone even the same certificate used in FCM for our backend service it works fine but unable to get the notification in-case of Quickblox messaging.

**Comment by VitaliyGuru** [comment]
@SalmanGhumsani, Hello. Could you please provide full logs.
Could you please enable full logs and send us this information?

```
[QBSettings setLogLevel:QBLogLevelDebug];
[QBSettings enableXMPPLogging];
```

**Comment by QB-vladyslav-vyshniak** [comment]
Hello, dear @SalmanGhumsani 

Could you please confirm that this issue is still relevant for you and we will proceed with the investigation of the reported issue.

If you have any additional questions, please let us know.

**Comment by QB-vladyslav-vyshniak** [comment]
Dear @SalmanGhumsani 

The status of the ticket changed to "Closed" due to the absence of the reply from you.
If you have any additional questions, please let us know.
