### ISSUE TITLE
Hi, I am unable to find QBRTCScreenCapture Class in pods. 

### ISSUE THREAD

**Issue by kmittal97** [QuickBlox/quickblox-ios-sdk#1049]
**New Issue Checklist**

 - [x] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [x] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    |11.o                                    |                                          
Quickblox iOS SDK version      | e.g. 2.7.6                                  |
QuickbloxWebRTC SDK version    | e.g. 2.2.1                                  |                               
Xcode Version                  | 9.0                              |
Repro with our demo sample     | e.g. does it happen with our demo sample?   |

**Did this work before?**

**Expected behavior**

**Actual behavior**

**Logs**

*Please use the following template for logs:*

To enable full logs use the following code:
```objc
[QBSettings setLogLevel:QBLogLevelDebug];
[QBSettings enableXMPPLogging];
```

<details>
<summary>Title for logs </summary>

```logos

// Your logs here

```

</details>

**Steps to reproduce the behavior**

**Any others comments**

**Comment by VitaliyGuru** [comment]
@kmittal97, Hello, please refer to the [Quickblox Video Sample](https://github.com/QuickBlox/quickblox-ios-sdk/blob/62117ced3f044a2b581e4875ab50739edb45c923/sample-videochat-webrtc/sample-videochat-webrtc/ViewControllers/SharingViewController/QBRTCScreenCapture.h).

**Comment by QB-vladyslav-vyshniak** [comment]
Hello, dear @kmittal97  

Could you please confirm that this issue is still relevant for you and we will proceed with the investigation of the reported issue.

If you have any additional questions, please let us know.

**Comment by QB-vladyslav-vyshniak** [comment]
Dear @kmittal97 @kmittal98 

The status of the ticket changed to "Closed" due to the absence of the reply from you.
If you have any additional questions, please let us know.
