### ISSUE TITLE
WebRTC Video Call iOS: Self video view is flipped. 

### ISSUE THREAD

**Issue by madhu014** [QuickBlox/quickblox-ios-sdk#105]
Self video view is flipped. The feed from the my front camera appears on the QBGLVideoView as is, whereas it should appear as if I'm looking into a mirror.  This issue is seen in the sample app as well and q-municate. 

Please let me know if I can do anything in my app side to get round this problem.

**Comment by iSevenDays** [comment]
Hello. You can flip your UIView by 180 degrees.

**Comment by madhu014** [comment]
Yes. Thats the solution I used. It would be better if this can be configured using video track object.
