### ISSUE TITLE
Problem in setting Remote Video View

### ISSUE THREAD

**Issue by kmittal98** [QuickBlox/quickblox-ios-sdk#1052]
Hi, 

I am building video conferencing app using quickblox. As the number of participants is dynamic so I am using collection view to represent the video tracks. 

I am using below code to set video tracks in collectionView
 let videoTrack = videoTracks[effectiveIndex]
   
        print(videoTrack)
        
        

 
    
        
       cell.videoView.setVideoTrack(videoTrack)
        

Im getting following Crash
'NSInternalInconsistencyException', reason: '|renderer| is already attached to this track'

I use various approaches to remove this crash but all go in vein.

Thanks in advance

**Comment by VitaliyGuru** [comment]
@kmittal98, Hello.
it is not allowed to have more than 1 renderer for video track for performance reasons, please try to use only 1 remote video view for 1 video track in the WebRTC.
Please refer to [the video sample](https://github.com/QuickBlox/quickblox-ios-sdk/blob/master/sample-videochat-webrtc/sample-videochat-webrtc/ViewControllers/CallViewController/CallViewController.m#L390-L400) where we are setting the remote view for the cell.

**Comment by VitaliyGuru** [comment]
@kmittal98, Hello. Any updates?

**Comment by kmittal98** [comment]
Hi,

The issue is solved though I have used different Approach. I did following

//1 Subclassed your videoTrack
class KunalVideoTrack: QBRTCVideoTrack {
    
    
    var videoTrack:QBRTCVideoTrack?
    
    init(videoTrack: QBRTCVideoTrack) {
        self.videoTrack = videoTrack
    }
    var attachedVideoTracks = [Int]()
    //The videoView Currently Attached with videoTrack
    var attachVideoView: QBRTCRemoteVideoView?
    //Custom Use
    var name: String = ""
    var designation : String = ""
}

//2
check in cellForItemAt Method whether The View is attached or not
 if let view = videoTrack.attachVideoView {
            videoTrack.videoTrack!.remove(view)
        }
     
 //3 Then Set It       
 cell.videoView.setVideoTrack(videoTrack.videoTrack!)


Let me know if there is any flaws in using this approach

**Comment by QB-vladyslav-vyshniak** [comment]
Hello, dear @kmittal98 

Thank you for the provided solution for this issue.
The status of the ticket changed to "Closed".

If you have any additional questions, please let us know.
