### ISSUE TITLE
Local video view stretching

### ISSUE THREAD

**Issue by Cyangineer** [QuickBlox/quickblox-ios-sdk#1053]
So I'm starting to work with quickblox and my project is in swift. Im working with the local video view and i noticed that the view is stretching and squishing like its trying to fit everything in the screen.

![img_0003](https://user-images.githubusercontent.com/8491681/41176776-bcfd9c92-6b2f-11e8-8ba6-100e233fceba.png)

![img_0005](https://user-images.githubusercontent.com/8491681/41176777-bd0b7bb4-6b2f-11e8-8631-f8cc26f3747e.png)

I have a setup method here:
func setup(){
`

        videoFormat.frameRate = 30
        videoFormat.pixelFormat = QBRTCPixelFormat.format420f
        videoFormat.width = 640
        videoFormat.height = 480

        self.videoCapture = QBRTCCameraCapture.init(videoFormat: videoFormat, position: AVCaptureDevice.Position.front)
        self.videoCapture!.previewLayer.frame = self.localVideoView.bounds
        self.videoCapture!.previewLayer.videoGravity = .resizeAspectFill
        self.videoCapture!.startSession()
        self.localVideoView.layer.insertSublayer(self.videoCapture!.previewLayer, at: 0) `
}

Any solutions in swift on how to fix this?

**Comment by kmittal98** [comment]
Change video gravity to .aspect fit or whatever the you want like (.Center etc)

**Comment by Ndennis** [comment]
But I only have 3 choices for `AVLayerVideoGravity`, `.resize`, `.resizeAspect`, and `.resizeAspectFill` and they all do the same stretching thing. Is there a way i can get use the choices like `.aspectFit` or `.center`?

**Comment by kmittal98** [comment]
try resizeAspect

**Comment by QB-vladyslav-vyshniak** [comment]
Hello, dear @Cyangineer 

Could you please confirm that this issue is still relevant for you and we will proceed with the investigation of the reported issue.

If you have any additional questions, please let us know.

**Comment by QB-vladyslav-vyshniak** [comment]
Dear @Cyangineer 

The status of the ticket changed to "Closed" due to the absence of the reply from you.
If you have any additional questions, please let us know.
