### ISSUE TITLE
unable to connect incoming call to other device say Send voip push - Error

### ISSUE THREAD

**Issue by goutham465** [QuickBlox/quickblox-ios-sdk#1054]
**New Issue Checklist**

 - [ ] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [ ] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    | e.g. 8.0                                    |                                          
Quickblox iOS SDK version      | e.g. 2.7.6                                  |
QuickbloxWebRTC SDK version    | e.g. 2.2.1                                  |                               
Xcode Version                  | e.g. Xcode 8.1                              |
Repro with our demo sample     | e.g. does it happen with our demo sample?   |

**Did this work before?**

**Expected behavior**

**Actual behavior**

**Logs**

*Please use the following template for logs:*

To enable full logs use the following code:
```objc
[QBSettings setLogLevel:QBLogLevelDebug];
[QBSettings enableXMPPLogging];
```

<details>
<summary>Title for logs </summary>

```logos

// Your logs here



2018-06-10 11:31:35.559 rtc::[PCON]<50708897, R:Offer> Did change ice gethering state to COMPLETE
2018-06-10 11:31:35.651120+0530 sample-videochat-webrtc[1152:24264] Send voip push - Error
2018-06-10 11:31:35.651121+0530 sample-videochat-webrtc[1152:24411] [QBCore]: Response[3]
headers: {
    "Access-Control-Allow-Origin" = "*";
    "Cache-Control" = "no-cache";
    Connection = "keep-alive";
    "Content-Length" = 45;
    "Content-Type" = "application/json; charset=utf-8";
    Date = "Sun, 10 Jun 2018 06:01:35 GMT";
    Duration = "0.301801";
    "QB-Token-ExpirationDate" = "2018-06-10 08:01:19 +0000";
    "QuickBlox-REST-API-Version" = "0.1.1";
    Server = "openresty/1.9.15.1";
    "Set-Cookie" = "_mkra_ctxt=c458fd2c650fb64d71d09535095eaf1e--422; path=/; max-age=5; HttpOnly; secure";
    Status = "422 Unprocessable Entity";
    "Strict-Transport-Security" = "max-age=31536000";
    "X-Content-Type-Options" = nosniff;
    "X-Frame-Options" = SAMEORIGIN;
    "X-Request-Id" = "bc64d87d-9600-4bdc-9830-fb1e6da71981";
    "X-Runtime" = "0.039658";
    "X-XSS-Protection" = "1; mode=block";
}
error: Request failed: client error (422)
reasons: {
    errors =     (
        "No one can receive the message"
    );
}


```

</details>

**Steps to reproduce the behavior**

**Any others comments**

**Comment by VitaliyGuru** [comment]
@goutham465, Hello. Please provide the error.

**Comment by QB-vladyslav-vyshniak** [comment]
Hello, dear @goutham465 

The status of the ticket changed to "Closed" due to the absence of the reply from you.

If you have any additional questions, please let us know.
