### ISSUE TITLE
Can iOS Screen can be shared in background mode through quickblox?. If yes then please provide me code.

### ISSUE THREAD

**Issue by kmittal98** [QuickBlox/quickblox-ios-sdk#1056]
**New Issue Checklist**

 - [ ] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [ ] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    | e.g. 8.0                                    |                                          
Quickblox iOS SDK version      | e.g. 2.7.6                                  |
QuickbloxWebRTC SDK version    | e.g. 2.2.1                                  |                               
Xcode Version                  | e.g. Xcode 8.1                              |
Repro with our demo sample     | e.g. does it happen with our demo sample?   |

**Did this work before?**

**Expected behavior**

**Actual behavior**

**Logs**

*Please use the following template for logs:*

To enable full logs use the following code:
```objc
[QBSettings setLogLevel:QBLogLevelDebug];
[QBSettings enableXMPPLogging];
```

<details>
<summary>Title for logs </summary>

```logos

// Your logs here

```

</details>

**Steps to reproduce the behavior**

**Any others comments**

**Comment by QB-vladyslav-vyshniak** [comment]
Hello, dear @kmittal98 

Could you please confirm that this issue is still relevant for you and we will proceed with the investigation of the reported issue.

If you have any additional questions, please let us know.

**Comment by QB-vladyslav-vyshniak** [comment]
Dear @kmittal98

The status of the ticket changed to "Closed" due to the absence of the reply from you.
If you have any additional questions, please let us know.
