### ISSUE TITLE
wake up call issue and can support to ios to  Android phone video call

### ISSUE THREAD

**Issue by goutham465** [QuickBlox/quickblox-ios-sdk#1057]
**New Issue Checklist**

 - [ ] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [ ] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    | e.g. 8.0                                    |                                          
Quickblox iOS SDK version      | e.g. 2.7.6                                  |
QuickbloxWebRTC SDK version    | e.g. 2.2.1                                  |                               
Xcode Version                  | e.g. Xcode 8.1                              |
Repro with our demo sample     | e.g. does it happen with our demo sample?   |

**Did this work before?**

**Expected behavior**

**Actual behavior**

**Logs**

*Please use the following template for logs:*

To enable full logs use the following code:
```objc
[QBSettings setLogLevel:QBLogLevelDebug];
[QBSettings enableXMPPLogging];
```

<details>
<summary>Title for logs </summary>

```logos

// Your logs here



```

</details>

**Steps to reproduce the behavior**

**Any others comments**

is the quick blox supports wake up call option  even if the app is background or not opened please suggest me in any code available

**Comment by VitaliyGuru** [comment]
@goutham465, Hello. Please take a look at our [Q-municate](https://github.com/QuickBlox/q-municate-ios/blob/8b00f2270f970cc32539e4e609433abb2b24a14a/Q-municate/Classes/Core/QMCallManager/QMCallManager.m#L94-L153) application. To implement wake up call option you should configure voip push notifications and send event.
Also, will be helpful [Push notifications documentation](https://quickblox.com/developers/SimpleSample-messages_users-ios#Adding_support_for_VOIP_push_notifications).

**Comment by QB-vladyslav-vyshniak** [comment]
Hello, dear @goutham465 

The status of the ticket changed to "Closed" due to the absence of the reply from you.

If you have any additional questions, please let us know.
