### ISSUE TITLE
Quickblox Notification

### ISSUE THREAD

**Issue by kmittal98** [QuickBlox/quickblox-ios-sdk#1059]
Does Quickblox notification contains the key "mutable-content" key with value 1?

If no then how to add it from both the platform I.e Android and iOS

**Comment by VitaliyGuru** [comment]
@kmittal98, You can enable this feature in the admin panel. Go to the chatAlerts settings and tick the checkbox named "mutable content".
http://joxi.ru/eAOe3bxixpYbnm

**Comment by kmittal98** [comment]
well I'm not asking for chat alerts. I'm asking for the notification that is sent through QBMEvent. It was mentioned on your site that to enable mutable-content in iOS the keyword in "iOS_mutable_content". It is working fine with Android but have issues in iOS.

Also from yesterday, I am not receiving notifications on iPhone. Please look into the matter.

I have checked the following points
1. The certificate contains the same bundle identifier that is am using. It is production SSL Universal certificate.
2. There is subscription on Quickblox for iOS Device.
3. There is no error logs on certificate.


Please let me know if I missing anything.

**Comment by QB-vladyslav-vyshniak** [comment]
Hello, dear @kmittal98 

Could you please confirm that this issue is still relevant for you and we will proceed with the investigation of the reported issue.

If you have any additional questions, please let us know.

**Comment by QB-vladyslav-vyshniak** [comment]
Dear @kmittal98 

The status of the ticket changed to "Closed" due to the absence of the reply from you.
If you have any additional questions, please let us know.
