### ISSUE TITLE
Quickblox Notification iOS Not Working

### ISSUE THREAD

**Issue by kmittal98** [QuickBlox/quickblox-ios-sdk#1060]
Hello guys,

Notification not working in iOS from quickblox(Neither Dashboard nor API)

Some more info attached below

1. Logs of created Push
{"notification":{"id":15426200,"badge":null,"device_token":"99404e36da874a204b867eb38d50bd29b1cd6f7be51a957011186d8ad0b45b81","sound":"default","alert":"hi","data":{"headers":{"apns-topic":"employee.vFrame10"}},"expiry":86400,"delivered":false,"delivered_at":null,"failed":false,"failed_at":null,"fail_after":"2018-07-02T07:13:41+00:00","retries":154,"error_code":null,"error_description":null,"deliver_after":"2018-07-02T06:26:34+00:00","alert_is_json":null,"app_id":23756,"collapse_key":null,"delay_while_idle":null,"registration_ids":null,"uri":null,"priority":null,"url_args":null,"category":null,"content_available":false,"mutable_content":false,"notification":null,"type":"Rpush::Client::Redis::Apns::Notification","event_id":24721297,"event_date":"2018-07-02T06:13:40+00:00"},"log":[{"device_token":"99404e36da874a204b867eb38d50bd29b1cd6f7be51a957011186d8ad0b45b81","delivered_at":null,"failed_at":null,"error_code":null,"error_description":null}]}

2. Logs of certificate
No Errors

3. Certificates are double checked both the certificate are same.

Let me know if anything is missing.

**Comment by algrid** [comment]
I'm having the same issue.
Lots of notifications going with "Delivered: 0, failed: 0".

**Comment by kmittal98** [comment]
Hi algrid,

This issue starts with me from 29 June. Everything working fine before 29 June. Also i tested with one of my build which is on app store. The notification is working fine on that build. 

Is the same case with you?

**Comment by algrid** [comment]
Hi @kmittal98 , 

Yes, it looks like it started June 29 for me too. 
I'm not sure about the older builds. When I try to send a test push to all the users from the admin interface I see in logs "Delivered: 15, failed: 0", but no devices I have access to receive the push. And no mentions for their tokens in logs.

**Comment by KrishnaPatell** [comment]
Hello,
I'm also facing this issue from 29 June 2018 in my two projects.
I'm using 2.16 SDK version.
I've tried to send notification from dashboard, from app and from our server(our own control panel) but not working. It shows that notification successfully send but iOS receiver cannot receive notification anymore. 
On dashboard its always shows me  "Delivered: 0, failed: 0"
On other hand android devices gets notification perfectly.

Please see log that i have found in dashboard : 

{"notification":{"id":15380965,"badge":null,"device_token":"4ff7691f8082fbfb436ce13a2778082f7d95e982bc9447f4d5acfa400930be76","sound":null,"alert":{"title":"Notification from Taxisti","body":"55646456"},"data":{"type":"admin_notification","body":"55646456","title":"Notification from Taxisti","headers":{"apns-topic":"com.yahya.Taxisti"}},"expiry":86400,"delivered":false,"delivered_at":null,"failed":false,"failed_at":null,"fail_after":"2018-06-30T05:08:40+00:00","retries":10,"error_code":null,"error_description":null,"deliver_after":"2018-06-30T04:09:31+00:00","alert_is_json":null,"app_id":22873,"collapse_key":null,"delay_while_idle":null,"registration_ids":null,"uri":null,"priority":null,"url_args":null,"category":null,"content_available":false,"mutable_content":false,"notification":null,"type":"Rpush::Client::Redis::Apns::Notification","event_id":24691718,"event_date":"2018-06-30T04:08:40+00:00"},"log":[{"device_token":"4ff7691f8082fbfb436ce13a2778082f7d95e982bc9447f4d5acfa400930be76","delivered_at":null,"failed_at":null,"error_code":null,"error_description":null}]}

**Comment by kmittal98** [comment]
Hi Krishna Patell,

The similar logs is shown on my side.

**Comment by kmittal98** [comment]
Any updates?

**Comment by kmittal98** [comment]
I have tested the latest production build and it is working fine. 
But development still not receiving the notifications. Please look into the matter

**Comment by kmittal98** [comment]
I got a reply from quickblox that the issue is resolved from their side. but it looks my app is not receiving the notifications in development mode still. 

Is the issue resolved for anyone. If yes then do the reply here please.

**Comment by KrishnaPatell** [comment]
Hi @kmittal98,
I also got reply from Quickblox saying that issue is resolved but my app is still not receiving notification in development mode.

**Comment by Rumesh25** [comment]
Hi there!
I received a notification from the CB that they are closing. We all need to look for alternative platforms.

**Comment by KrishnaPatell** [comment]
Hi @Rumesh25,
Can you please send us a screenshot of what you receive from QB about closing?

**Comment by romansorochak** [comment]
I have same issue too.
do not receive push notifications when send it from the latest ios SDK either when send from quickblox admin panel
I cannot even submit a ticket cuz it asks some strange customer id (account id from quickblox profile settings does not accept)

Quickblox support please help !

**Comment by Rumesh25** [comment]
Guys, I got a message how to resolve the push notifications issue with delivery fails on dev & prod, can share it with you , u can mail me <rumeshtubalor@gmail.com>

**Comment by chiragiOSDev** [comment]
Hi @kmittal98 @algrid @KrishnaPatell @Rumesh25 @romansorochak 

I have the same problem with development mode push is not working. I shared build to a client before 15-20 days with the working condition now push is not working.

Any idea to fix this issue or help would be appreciated.

**Comment by vineeshtp** [comment]
Why they are closing.  This issue still exist.

**Comment by KrishnaPatell** [comment]
Hi @kmittal98,
I just want to know that have you faces delayed in notification at all?

**Comment by Dhananjay22** [comment]
@VitaliyGuru
@andr45
@iSevenDays
@Berk0ld

is there any update on this issue? I am still facing the issue.
is Quickblox team has started fixing this issue?

**Comment by KrishnaPatell** [comment]
Hi @kmittal98 @orlovev88 @RubenBenBen @algrid 
Can you guys please check with your production build for push notification?
I think its not working too.
Please check push notification in production environment.

**Comment by RubenBenBen** [comment]
Hi guys, @KrishnaPatell @kmittal98 @algrid @Dhananjay22 @romansorochak  can you please if notifications are working right now? I can send the notification, but it's not received by the user.
