### ISSUE TITLE
Push notifications (version 2.17.1): Can't create subscription from iOS - "unknown attribute: bundle_identifier"

### ISSUE THREAD

**Issue by tonifirnandes** [QuickBlox/quickblox-ios-sdk#1062]
Dear team,

We are still facing this issue "unknown attribute: bundle_identifier" on version 2.17.1, where it never happened on previously version 2.7.5. We do upgrade the version since we are migrating our code form swift 2 to swift 3 using Xcode 8.3.3

Thanks.

**Comment by YogendraPatel** [comment]
@toni firnandes hi, have you done successfully signup using latest version 2.17.1?

**Comment by QB-vladyslav-vyshniak** [comment]
Dear @tonifirnandes 

The status of the ticket changed to "Closed" due to the absence of the reply from you.
If you have any additional questions, please let us know.
