### ISSUE TITLE
Push notifications do not work at all!

### ISSUE THREAD

**Issue by romansorochak** [QuickBlox/quickblox-ios-sdk#1063]
Push notifications do not work at all.
They do not work from the latest ios SDK and from quickblox admin panel.
I have my certificates up to date.
Here is my account id - 82514
Cannot even submit a ticket into quickblox service.
I see also today was created relevant issue - https://stackoverflow.com/questions/51172685/ios-push-notification-stop-working-in-quick-blox/51190208#51190208.
Is there an issue on quickblox ?

**Comment by KrishnaPatell** [comment]
Hi @romansorochak,

All of the developer around the world facing this issue with development mode. Please check the following issue...
#1061 #1060

**Comment by iOSMahesh** [comment]
@romansorochak 
I tried with Ad-Hoc certificate, but in iOS device push is not received. is there any other step need to perform?

**Comment by Dhananjay22** [comment]
@VitaliyGuru 
is there any update on this issue? I am still facing the issue.
is Quickblox team has started fixing this issue?

**Comment by vineeshtp** [comment]
It is working with production certificate

**Comment by QB-vladyslav-vyshniak** [comment]
Hello, dear @vineeshtp 

Thank you for contacting QuickBlox support.
Take our apologies for the delay in reply. 
Currently, all is working well. You can test it.

If you have any additional questions, please let me know.
