### ISSUE TITLE
QuickBlox "Request failed: client error (404):Couldn't find user" 

### ISSUE THREAD

**Issue by prafulargiddi** [QuickBlox/quickblox-ios-sdk#1065]
GET URL:https://api.quickblox.com/users/by_tags.json?page=1&per_page=100&tags=dev
headers: {
    "Accept-Language" = "en;q=1";
    "QB-OS" = "iOS 11.2";
    "QB-SDK" = "iOS 2.17.1";
    "QB-Token" = 1bc21b092966c148383ecece586f3560dc011a2b;
    "QuickBlox-REST-API-Version" = "0.1.1";
    "User-Agent" = "QuickBloxDemo/1.0 (iPhone; iOS 11.2; Scale/2.00)";
}
parameters: {
    page = 1;
    "per_page" = 100;
    tags = dev;
}
2018-07-11 21:17:49.818454+0530 QuickBloxDemo[59137:2903196] [QBCore]: Response[8]
headers: {
    "Access-Control-Allow-Origin" = "*";
    "Cache-Control" = "no-cache";
    Connection = "keep-alive";
    "Content-Length" = 44;
    "Content-Type" = "application/json; charset=utf-8";
    Date = "Wed, 11 Jul 2018 15:47:46 GMT";
    Duration = "1.150223";
    "QB-Token-ExpirationDate" = "2018-07-11 17:33:09 +0000";
    "QuickBlox-REST-API-Version" = "0.1.1";
    Server = "nginx/1.8.1";
    "Set-Cookie" = "_mkra_ctxt=dbc8691803815f19587a2ab55a594768--404; path=/; max-age=5; HttpOnly; secure";
    Status = "404 Not Found";
    "Strict-Transport-Security" = "max-age=31536000";
    "X-Content-Type-Options" = nosniff;
    "X-Frame-Options" = SAMEORIGIN;
    "X-Request-Id" = "cd5a4bf7-4cc1-47aa-a3e2-413bf96392b7";
    "X-Runtime" = "0.166892";
    "X-XSS-Protection" = "1; mode=block";
}
error: Request failed: not found (404)
reasons: {
    code = "<null>";
    message = "Couldn't find user";
}

**Comment by prafulargiddi** [comment]
please help me above error. I am stuck with this error. I am not able to get User information

**Comment by vineeshtp** [comment]
@prafulargiddi : You may deleted the user.

**Comment by prafulargiddi** [comment]
no. Records are available on tables but I cant able to retrieving user
records for new chat dialogs. Please help me as soon as possible.

**Comment by vineeshtp** [comment]
This error message shows that, "Couldn't find user".
error: Request failed: not found (404)
reasons: {
code = "";
message = "Couldn't find user";
}

**Comment by prafulargiddi** [comment]
yes but I have record on Admin tables

**Comment by prafulargiddi** [comment]
Any Settings are needed on Admin panel?

**Comment by prafulargiddi** [comment]
I have used  tags bellow code
 class var QB_USERS_ENVIROMENT: String {
        
        #if DEBUG
            return "dev"
        #elseif QA
            return "qbqa"
        #else
            assert(false, "Not supported build configuration")
            return ""
        #endif
        
    }

anything changes are needed above codes. please help me I am stuck now. when I am going to run Sample Chat  Credentials such as Authorize key, its I will get User list but my credentials to not working

**Comment by vivekshah-zymr** [comment]
@prafulargiddi , Have you found any solution for this? I am facing the same issue.

**Comment by prafulargiddi** [comment]
Yes i had solution for this issue. there is one field tags in user tables quickblox web side.
you can insert records "dev/qbqa". its will search record matches from tags .
its will working.
if any facing issue let me know with screen short. i will help you 
Regards
Praful Argiddi

**Comment by QB-vladyslav-vyshniak** [comment]
Hello, dear @prafulargiddi

Thank you for the provided solution for the users.
The status of the ticket changed to "Closed", the issue has been resolved.

If you have any additional questions, please let us know.
