### ISSUE TITLE
How do I check chat user blocked status

### ISSUE THREAD

**Issue by vineeshtp** [QuickBlox/quickblox-ios-sdk#1067]
I have Implemented the Block user functionality in iOS by using the below code,

 let item : QBPrivacyItem = QBPrivacyItem(privacyType: QBPrivacyType.userID, userID:UInt(self.dialog.recipientID), allow: false)!
        item.mutualBlock = false
        let list: QBPrivacyList = QBPrivacyList(name: "public", items: [item])
        QBChat.instance.setPrivacyList(list)
        QBChat.instance.setDefaultPrivacyListWithName("public")

**It is working fine,**
**How do I check the blocked user status ?**

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    | e.g. 8.0                                    |                                          
Quickblox iOS SDK version      | e.g. 2.7.6                                  |
QuickbloxWebRTC SDK version    | e.g. 2.2.1                                  |                               
Xcode Version                  | e.g. Xcode 8.1                              |
Repro with our demo sample     | e.g. does it happen with our demo sample?   |

**Did this work before?**

**Expected behavior**

**Actual behavior**

**Logs**

*Please use the following template for logs:*

To enable full logs use the following code:
```objc
[QBSettings setLogLevel:QBLogLevelDebug];
[QBSettings enableXMPPLogging];
```

<details>
<summary>Title for logs </summary>

```logos

// Your logs here

```

</details>

**Steps to reproduce the behavior**

**Any others comments**

**Comment by QB-vladyslav-vyshniak** [comment]
Hello, dear @vineeshtp 

Thank you for contacting QuickBlox support.
Currently, our developers are improving the Privacy Lists feature.
Please, check our blog: https://quickblox.com/blog , there you will find news about the new improvements for this feature as soon as our developers release them.

The status of the ticket changed to "Closed".

If you have any additional questions, please let us know.
