### ISSUE TITLE
Error  code 429

### ISSUE THREAD

**Issue by vineeshtp** [QuickBlox/quickblox-ios-sdk#1073]
I am facing an issue Error code  429 , as per the documentation is clear that **Too Many Requests** per second. Since, it is free.
But, I am able to send too many messages / second in android.
in iOS error notification is coming too many times. How to deactivate the  error notification.

 - [ ] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [ ] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    | e.g. 8.0                                    |                                          
Quickblox iOS SDK version      | e.g. 2.7.6                                  |
QuickbloxWebRTC SDK version    | e.g. 2.2.1                                  |                               
Xcode Version                  | e.g. Xcode 8.1                              |
Repro with our demo sample     | e.g. does it happen with our demo sample?   |

**Did this work before?**

**Expected behavior**

**Actual behavior**

**Logs**

*Please use the following template for logs:*

To enable full logs use the following code:
```objc
[QBSettings setLogLevel:QBLogLevelDebug];
[QBSettings enableXMPPLogging];
```

<details>
<summary>Title for logs </summary>

```logos

// Your logs here

```

</details>

**Steps to reproduce the behavior**

**Any others comments**

**Comment by QB-vladyslav-vyshniak** [comment]
Hello, dear @vineeshtp 

Thank you for contacting QuickBlox support.
Could you please provide me with information about your current QB plan.
This error happened, because your API calls limits were exceeded.
We can't disable this error, but you can upgrade your QB plan to higher. 
https://quickblox.com/developers/Errors

If you have any additional questions, please let me know.
