### ISSUE TITLE
Quickblox Customize push notifications

### ISSUE THREAD

**Issue by katoreRahul** [QuickBlox/quickblox-ios-sdk#1074]
How can we customize Quickblox push notifications as per users requirement in iOS App?
For ex. If user wants to vibrate/silent/alert iPhone, when he received notification from quickblox server(from another QB User.)

**Comment by QB-vladyslav-vyshniak** [comment]
Hello, dear @katoreRahul 

Thank you for contacting QuickBlox support.
You could proceed with customization of push notifications in your admin panel, please, check image in the attachment.

If you have any additional questions, please let me know.

![pushnotifications customization](https://user-images.githubusercontent.com/45996007/51262356-447ef980-19c3-11e9-8804-4300a9dca923.PNG)
