### ISSUE TITLE
Can we encrypt and decrypt message in Quickblox ?

### ISSUE THREAD

**Issue by riteshpatel0** [QuickBlox/quickblox-ios-sdk#1075]
Hello,

Can we send encrypted message to another. and another side can we decrypt those message?

Thanks!

**Comment by riteshpatel0** [comment]
Hello

Any updates?

Thanks!

**Comment by QB-vladyslav-vyshniak** [comment]
Hello, dear @riteshpatel0 

Thank you for contacting QuickBlox.
We don't have any additional encryption feature besides SSL/TLS. 

If you have any additional questions, please let us know.
