### ISSUE TITLE
Retrieving registered user from quickblox getting crash with unknown exception  

### ISSUE THREAD

**Issue by ReusIosDeveloper** [QuickBlox/quickblox-ios-sdk#1077]
Here is my method to retrive register user from quickblox

  QBRequest.registeredUsersFromAddressBook(withUdid: nil, isCompact: false,
                                                 successBlock: { (usersQB) in
                                      

                                
        }) { (response) in
            print("\((response.error?.description)!)")
        }

but it crash with unknown exception

**Comment by QB-vladyslav-vyshniak** [comment]
Hello, dear @ReusIosDeveloper 

Thank you for contacting QuickBlox support.
Could you please confirm that this issue is still relevant for you?

If you have any additional questions, please let us know.

**Comment by QB-vladyslav-vyshniak** [comment]
Dear @ReusIosDeveloper 

The status of the ticket changed to "Closed" due to the absence of the reply from you.
If you have any additional questions, please let us know.
