### ISSUE TITLE
Swift - how to add link preview

### ISSUE THREAD

**Issue by sergiuatodiresei** [QuickBlox/quickblox-ios-sdk#1080]
Please help me with Quickblox link preview implementation in Swift (in chat messages).

For example, in Objective-C i have this

`if (QMCore.instance.openGraphService.memoryStorage[message.ID] != nil) {
return isIncomingMessage ? QMChatIncomingLinkPreviewCell.class :  QMChatOutgoingLinkPreviewCell.class;
            }`

And in Swift, in QMServicesManager.instance(), the method openGraphService doesn't exist.

**Comment by QB-vladyslav-vyshniak** [comment]
Hello, dear @sergiuatodiresei 

Thank you for contacting QuickBlox support.
Could you please confirm that this question is still relevant for you? 

If you have any additional questions, please let us know.

**Comment by QB-vladyslav-vyshniak** [comment]
Dear @sergiuatodiresei 

The status of the ticket changed to "Closed" due to the absence of the reply from you.
If you have any additional questions, please let us know.
