### ISSUE TITLE
QBRequest.signUp Error  422

### ISSUE THREAD

**Issue by vineeshtp** [QuickBlox/quickblox-ios-sdk#1082]
When Sign up Got error 422
Find below code which is used for signp'

QBRequest.signUp(qUser, successBlock: { (response, user) in
            
            
          
            print(user)
            
        }) { (response) in
            if response.status.rawValue == 422{
                //Email ID already taken
                self.loginWithQuickBlox(qUser: qUser)
            }
            print(response)
        }
**Error Log:-**

headers: {
    "Access-Control-Allow-Origin" = "*";
    "Cache-Control" = "no-cache";
    Connection = "keep-alive";
    "Content-Length" = 44;
    "Content-Type" = "application/json; charset=utf-8";
    Date = "Mon, 27 Aug 2018 23:19:45 GMT";
    Duration = "1.664355";
    "QuickBlox-REST-API-Version" = "0.1.1";
    Server = "nginx/1.8.1";
    "Set-Cookie" = "_mkra_ctxt=7a573a99b9d7641043230e3b981f898d--422; path=/; max-age=5; HttpOnly; secure";
    Status = "422 Unprocessable Entity";
    "Strict-Transport-Security" = "max-age=31536000";
    "X-Content-Type-Options" = nosniff;
    "X-Frame-Options" = SAMEORIGIN;
    "X-Request-Id" = "aabb62ef-c8c8-4f4f-867e-79b687251c50";
    "X-Runtime" = "0.006391";
    "X-XSS-Protection" = "1; mode=block";
}
error: Request failed: client error (422)
reasons: {
    errors =     {
        base =         (
            "No application found"
        );
    };
}

 - [ ] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [ ] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    | e.g. 8.0                                    |                                          
Quickblox iOS SDK version      | e.g. 2.7.6                                  |
QuickbloxWebRTC SDK version    | e.g. 2.2.1                                  |                               
Xcode Version                  | e.g. Xcode 8.1                              |
Repro with our demo sample     | e.g. does it happen with our demo sample?   |

**Did this work before?**

**Expected behavior**

**Actual behavior**

**Logs**

*Please use the following template for logs:*

To enable full logs use the following code:
```objc
[QBSettings setLogLevel:QBLogLevelDebug];
[QBSettings enableXMPPLogging];
```

<details>
<summary>Title for logs </summary>

```logos

// Your logs here

```

</details>

**Steps to reproduce the behavior**

**Any others comments**

**Comment by dhara6894** [comment]
I am also facing same issue
![24dc1074-6886-42b5-a3cf-ee9f0f82b32a](https://user-images.githubusercontent.com/25882656/51309195-dfcaaa00-1a69-11e9-8cc7-b2fddd47c23e.jpg)

**Comment by tuna25** [comment]
We had a similar issue in September. After investigation and communication with QuickBlox support we got this:

- Each session token contains info about app it relates. 'No application found' means there is no app for this token
- This is strange and can't be happen, so they asked for more logs, and then more logs again, and finally responded to check our code, it's our issue
- After back n forth they finally confirmed they lost our app during some server DB migration. And also they were not able to restore from backups that is weird. Luckily our app was not in AppStore and we just recreated it. But these guys doing a complete crap..   

Maybe they again lost some DB data

**Comment by QB-vladyslav-vyshniak** [comment]
Hello, dear @vineeshtp @dhara6894 

Thank you for contacting QuickBlox support.
Could you please confirm that this issue is still relevant for you?

**Comment by QB-vladyslav-vyshniak** [comment]
The status of the ticket changed to "Closed" due to the absence of the reply.

**Comment by RahulChona11091991** [comment]
Hi QuickBlox Team, 
I facing this same issue.
[QBResponse], status: 422

Can anyone help in finding the issue?

Thanks
