### ISSUE TITLE
[CAMetalLayerDrawable texture] should not be called - Video call app crash

### ISSUE THREAD

**Issue by vineeshtp** [QuickBlox/quickblox-ios-sdk#1083]
In video call application crashing, Please see the below error message,

> [CAMetalLayerDrawable texture] should not be called after already presenting this drawable. Get a nextDrawable instead

 - [ ] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [ ] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    | e.g. 8.0                                    |                                          
Quickblox iOS SDK version      | e.g. 2.7.6                                  |
QuickbloxWebRTC SDK version    | e.g. 2.2.1                                  |                               
Xcode Version                  | e.g. Xcode 8.1                              |
Repro with our demo sample     | e.g. does it happen with our demo sample?   |

**Did this work before?**

**Expected behavior**

**Actual behavior**

**Logs**

*Please use the following template for logs:*

To enable full logs use the following code:
```objc
[QBSettings setLogLevel:QBLogLevelDebug];
[QBSettings enableXMPPLogging];
```

<details>
<summary>Title for logs </summary>

```logos

// Your logs here

```

</details>

**Steps to reproduce the behavior**

**Any others comments**

**Comment by vineeshtp** [comment]
Do not wait for quickBlox, you will not get any solution from QuickBlox. They only know how to close the issues...!!!

Set the below property.

`QBRTCRemoteVideoView.preferMetal = false`

**Comment by proactive-solutions** [comment]
@vineeshtp thanks for the reply.
`QBRTCRemoteVideoView.preferMetal = false` did the trick for me.
I just wonder why the sample app does not crash.

**Comment by QB-vladyslav-vyshniak** [comment]
Dear @proactive-solutions 

Take our apologies for the delay in reply.
Thank you for the confirmation that the issue has been successfully resolved.

Dear @vineeshtp 
As I know, you are Enterprise member of QuickBlox, please, submit a ticket to QB customer support portal (Enterprise department). We are always glad to help you with the resolution of any raised requests. 

QuickBlox improves all the provided services, if you have any additional questions, please let us know.
