### ISSUE TITLE
Silent Mode - Issue

### ISSUE THREAD

**Issue by alexsdi** [QuickBlox/quickblox-ios-sdk#1084]
Hello Developer,

While Iam using the quickblox for audio call when my phone is silent mode I can't hear the receiver sound.
Below I have mentioned the file name
QMSoundManager

**Comment by QB-vladyslav-vyshniak** [comment]
Hello, dear @alexsdi 

Thank you for contacting QuickBlox.
Could you please confirm that this issue is still relevant for you.

**Comment by QB-vladyslav-vyshniak** [comment]
Dear @alexsdi 

In this case, you could use AVAudioPlayer instead of standard system audio from our sample for dial tone.
This is a single solution which I can propose to you.

If you have any additional questions, please let us know.
