### ISSUE TITLE
Remote video not receiving- ios Swift

### ISSUE THREAD

**Issue by vineeshtp** [QuickBlox/quickblox-ios-sdk#1086]
I have implemented VoIP calls both video and Audio all  VoIP calls are working.
But In video call sometimes I am not able to get the remote user video.

Here I am attaching error log

[https://gist.github.com/vineeshtp/8a32c7c91f5ccd176422f8f32bee1f95](url)
Kindly let me know  how do I solve this issue.

**Note: Do not close the ticket, give me some time to answer.**

 - [ ] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [ ] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    | e.g. 8.0                                    |                                          
Quickblox iOS SDK version      | e.g. 2.7.6                                  |
QuickbloxWebRTC SDK version    | e.g. 2.2.1                                  |                               
Xcode Version                  | e.g. Xcode 8.1                              |
Repro with our demo sample     | e.g. does it happen with our demo sample?   |

**Did this work before?**

**Expected behavior**

**Actual behavior**

**Logs**

*Please use the following template for logs:*

To enable full logs use the following code:
```objc
[QBSettings setLogLevel:QBLogLevelDebug];
[QBSettings enableXMPPLogging];
```

<details>
<summary>Title for logs </summary>

```logos

// Your logs here

```

</details>

**Steps to reproduce the behavior**

**Any others comments**

**Comment by QB-vladyslav-vyshniak** [comment]
Hello, dear @vineeshtp 

Thank you for contacting QuickBlox support.
Could you please confirm that this issue is still relevant for you and we will proceed with the investigation.

**Comment by QB-vladyslav-vyshniak** [comment]
Dear @vineeshtp 

The status of the ticket changed to "Closed" due to the absence of the reply from you.
If you have any additional questions, please let us know.
