### ISSUE TITLE
How to get total unread messages count for all the dialogs?

### ISSUE THREAD

**Issue by kushal211** [QuickBlox/quickblox-ios-sdk#1089]
Hi, 

I wanted to get the **total number of unread messages** count for all the Chat dialogs. I can able to get the unread messages count for the individual dialogs but not for all the dialogs in a single shot.

I have checked [this reported issue](https://github.com/QuickBlox/quickblox-ios-sdk/issues/709) and tried it as well but it is not returning me any count in response.

Please help me with this as I wanted to show the total number of unread messages in the application.

Thanks in advance.

**Comment by kushal211** [comment]
Hi, 

Any update please!

**Comment by QB-vladyslav-vyshniak** [comment]
Hello, dear Kushal.

Thank you for contacting us.
You can implement the following logic:
=>>get values from unread dialogs and count the sum of all messages then display it as total count of unread messages.

Let me know if I can help you more.

**Comment by QB-vladyslav-vyshniak** [comment]
The status of the ticket changed to "Closed" due to the absence of the reply from the user.

**Comment by IamSumitJangid** [comment]
` **QB.chat.message.unreadCount(params, callback);**`

This function will give you the total of all dialogs unread messages count.
All you need to have the latest version of sdk.
