### ISSUE TITLE
When My app is killed or in background, Android to iOS calling is not working(but ios to ios calling is working).

### ISSUE THREAD

**Issue by katoreRahul** [QuickBlox/quickblox-ios-sdk#1090]
1. iOS to iOS calling
      a. when app is in foreground, calling functionality works smoothly.
      b. when app is in background, calling functionality works smoothly.
      c. when app was killed/screen locked, calling functionality works but not smoothly.

2. android to iOS calling
      a. when app is in foreground, calling functionality works smoothly.
      b. when app is in background, calling functionality not working.
      c. when app was killed/screen locked, calling functionality  not working.

So please tell me how can I achieve calling functionality from android to iOS when my app is killed or in background.

**Comment by QB-vladyslav-vyshniak** [comment]
Hello, dear @katoreRahul 

Thank you for contacting QuickBlox support. 
Could you please confirm that this issue is still relevant for you?

**Comment by QB-vladyslav-vyshniak** [comment]
Dear @katoreRahul 

The status of the ticket changed to "Closed" due to the absence of the reply from you.
If you have any additional questions, please let us know.

**Comment by Lavi1561** [comment]
I am also facing same issue

**Comment by silicus-kirankhalkar** [comment]
Hello Team, 
We are facing the same problem. Anyone know that is the cause of this.

**Comment by RashidaBegamShaik** [comment]
unable to get call when the app is killed... we need a solution in flutter to get call when the app is killed ... please help me with the solution

**Comment by harshGD** [comment]
In my case ios to ios call not working please tell me how to connect call when app is in background or terminated

**Comment by IlliaChemolosov** [comment]
@harshGD Hello, 

For iOS, support calls can only be implemented using standard Apple features like [voIP notification](https://developer.apple.com/documentation/pushkit/pkpushtype/voip) and the [CallKit framework](https://github.com/QuickBlox/quickblox-ios-sdk/tree/master/sample-videochat-webrtc-swift) when the application is in an inactive state. You can explore an example demonstrating how we utilize these features to configure calls in an inactive state by visiting the following link: [link](https://github.com/QuickBlox/quickblox-ios-sdk/tree/master/sample-videochat-webrtc-swift)

If you are already using our example, you may need to configure an APNS certificate that supports voIP notifications and upload it to the QuickBlox Dashboard. 
https://docs.quickblox.com/docs/ios-push-notifications#upload-certificate-to-dashboard
