### ISSUE TITLE
Custom object linked with QBChatMessage or QBChatDialog

### ISSUE THREAD

**Issue by mawshd** [QuickBlox/quickblox-ios-sdk#1091]
Hello, 
I want to add likes and dislikes in group chat dialog. 
like i am having 5 members in dialog, 3 of them like my message 2 of them dislike. i want to attach these counter with QBChatMessage. How i can do this?

Can we update QBChatmessage custom params?
If I create custom class for it, than its not linking with QBMessages when retrieval in dialog.?

Can you please guide me?
Thanks

**Comment by mawshd** [comment]
when i am creating new QBchatMessage with custom params, i am adding custom class key in dictionary like
 `
        let QBMsg = QBChatMessage.markable()
        QBMsg.text = textView.text.trim()
        QBMsg.customParameters = ["class_name": "myCustomClass", "likes" : 3, "dislikes" : 2, "save_to_history" : true]
        QBMsg.dialogID = dialog?.id
`

message being sent successfully, and when receive in delegate custom class objet id, parent id is not being received. but likes and dislikes received.  Also i can see there is not entry creating on myCustomClass in my QB dashbord on website. is it working fine according to you or i m making some mistake?

**Comment by mawshd** [comment]
If I could get these id and parent id in QBChatMessage, than i will be able to update the counters by simply using 

`QBRequest.update(custom, successBlock: { (response, customObje) in
            print(custom)
        }) { (response) in
            print(response)
        }
`

**Comment by mawshd** [comment]
Or guide me in better way. if it is possible to achieve this.?

**Comment by QB-vladyslav-vyshniak** [comment]
Dear @mawshd 

Thank you for contacting QuickBlox support.
Could you please confirm that this request is still actual for you?

**Comment by QB-vladyslav-vyshniak** [comment]
Dear @mawshd 

The status of the ticket changed to "Closed" due to the absence of the reply from you.
If you have any additional questions, please let us know.
