### ISSUE TITLE
Code=-1011 "Request failed: internal server error (500)

### ISSUE THREAD

**Issue by prathap2626** [QuickBlox/quickblox-ios-sdk#1096]
Hello, I am getting this error in AFNetworking.  I am using XCode 10
Error Domain=com.alamofire.error.serialization.response Code=-1011 "Request failed: internal server error (500)"

Anyone knows please reply fast...

`-(void)blockAndBook {

//    NSMutableDictionary *aBodyDictionary = [NSMutableDictionary dictionaryWithObject:[BRUtility getAuthToken] forKey:@"Authorization"];

    NSString *anURLString = [NSString stringWithFormat:@"%@%@",kSmartCommuteBaseURL,kBlockAndBook];
    
    AFHTTPSessionManager *manager = [BRUtility getAFHTTPSessionManager];

    [manager POST:anURLString
       parameters:[self prepareRequestBody]
        progress:nil
        success:^(NSURLSessionDataTask * _Nonnull task, id  _Nullable responseObject) {
            NSString *anErrorCode = [responseObject valueForKey:@"errorCode"];
            if(anErrorCode.intValue == 0) {

                NSError *anError = nil;
                self.bikeConfirmationResponse = [MTLJSONAdapter modelOfClass:[BlockAndBookResponse class] fromJSONDictionary:[responseObject valueForKey:@"data"] error:&anError];
                
                self.bikeConfirmationResponse.orderId = [[responseObject valueForKey:@"data"] valueForKey:@"orderId"];

                self.bookingConfirmedOTPLabel.text = [NSString stringWithFormat:@"%@",[[responseObject valueForKey:@"data"] valueForKey:@"otp"]];

            } else {

                  }
              } failure:^(NSURLSessionDataTask * _Nullable task, NSError * _Nonnull error) {
                  [BRUtility dismissLoader:self];
                  [BRUtility showErrorMessageWithTitle:@"Error" message:@" " delegate:self];
        }];
}`

And this is AFHTTPSessionManager

`#pragma mark -  For AFHTTPSessionManager
+ (AFHTTPSessionManager *)getAFHTTPSessionManager {
    AFHTTPSessionManager *manager = [AFHTTPSessionManager manager];
    manager.requestSerializer = [AFJSONRequestSerializer serializer];
    manager.responseSerializer = [AFJSONResponseSerializer serializer];
    [manager.requestSerializer setValue:@"application/json" forHTTPHeaderField:@"Accept"];
    [manager.requestSerializer setValue:@"application/json" forHTTPHeaderField:@"Content-Type"];
    [manager.requestSerializer setValue:[self getAuthToken] forHTTPHeaderField:@"Authorization"];
//    manager.responseSerializer.acceptableContentTypes = [manager.responseSerializer.acceptableContentTypes setByAddingObject:@"text/html"];
//    manager.responseSerializer.acceptableContentTypes = [NSSet setWithObject:@"application/json"];
    return manager;
}`

**Comment by QB-vladyslav-vyshniak** [comment]
Hello, dear prathap2626.

Thank you for contacting QuickBlox.
Could you please confirm that this issue is still relevant for you.

**Comment by QB-vladyslav-vyshniak** [comment]
Dear @prathap2626 

The status of the ticket changed to "Closed" due to the absence of the reply from you.
If you have any additional questions, please let us know.
