### ISSUE TITLE
QuickBlox Voice Call Recording: Can't Hear Opponent Voice [Swift]

### ISSUE THREAD

**Issue by sohilspaceo** [QuickBlox/quickblox-ios-sdk#1097]
**New Issue Checklist**

 - [x] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [x] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    | 12.0                                 |                                          
Quickblox iOS SDK version      | 2.17.1                           |
QuickbloxWebRTC SDK version    | 2.7                                |                               
Xcode Version                  | 10.0                            |
Repro with our demo sample     | No demo sample don't provide recording   | 

**Did this work before?**
haven't tried with earlier verison.

**Expected behavior**

Quickblox should record the Voice call with not only receiver's voice but also with opponent voice.

**Actual behavior**

Using QuickBlox in my app with video and voice calling functionality. Now I want to record a normal One-to-One Voice call. As documented, I am trying to record Voice call but I am not able to hear opponent voice. Code Snippet.

```
func startRecordingCall() {
    //Start Recording on Caller's Screen
    let formatter = DateFormatter()
    formatter.dateFormat = "yyyy-MM-dd_HH.mm.ss"
    let date = formatter.string(from: Date())
    let url = createNewAudioFile("\(idToCall!)_\(date).wav")
    session?.recorder?.delegate = self
    session?.recorder?.startRecord(withFileURL: url)
}
```

As the document says to record .mp4 file extension is must but I have tried with all like .mp3, .mp4, .m4a & .wav but still no luck. Can anyone say what I am missing?

Reference: https://quickblox.com/developers/Sample-webrtc-ios#Recording_audio_and_video_calls

**Comment by QB-vladyslav-vyshniak** [comment]
Hello, dear @sohilspaceo 

Thank you for contacting QuickBlox support.
Could you please confirm that this issue is still relevant for you?

**Comment by sohilspaceo** [comment]
Yes, it still exists!

**Comment by QB-vladyslav-vyshniak** [comment]
Dear @sohilspaceo 

Could you please update your WebRTC version to the latest (2.7.3) and proceed with the testing of this option again.

**Comment by QB-vladyslav-vyshniak** [comment]
Dear @sohilspaceo 

The status of the ticket changed to "Closed" due to the absence of the reply from you.
If you have any additional questions, please let us know.

**Comment by sohilmemon** [comment]
Still the issue exists I tried just today, can you pls check and let me know if anything needed from my side.

**Comment by waqarYasin** [comment]
I have been trying this issue but same response when i start recording it only records my voice but don't record other side voice 
but i am facing this issue in android 10 ..
