### ISSUE TITLE
Can't create a subscription for iOS.

### ISSUE THREAD

**Issue by CookAmir** [QuickBlox/quickblox-ios-sdk#1098]
Hello, I am getting this error in create a subcription for iOS.

let subscription: QBMSubscription! = QBMSubscription()
subscription.notificationChannel = QBMNotificationChannel.APNS
subscription.devicePlatform = "iOS"
subscription.deviceUDID = UIDevice.current.identifierForVendor!.uuidString
subscription.deviceToken = "****firebase token****"
QBRequest.createSubscription(subscription, successBlock: { (response, objects) in
            print("createSubscription success")
 }) { (res) in
            print(res.error?.description)
            print("createSubscription error")
}

It is failed and i got this error.
"Error reasons:{errors:{"client_identification_sequence":"is invalid" )}}"

I upload the apns certificate to the admin panel, also i can get the firebase cloud message from fcm.

Please help me.

**Comment by dgem** [comment]
Hi,
_disclaimer_: I'm not familiar with swift or the ios sdk.
Looking at the API documentation (https://quickblox.com/developers/Messages#Create_subscription_.28subscribes.29) the client_identification_sequence:
>Identifies client device in 3-rd party service like APNS, GCM/FCM, BBPS or MPNS. Initially retrieved from 3-rd service and should be send to QuickBlox to let it send push notifications to the client.
Based on the above, I would have expected you to set it as a property of the subscription, so it can be forwarded as per the docs rest call:
```
curl -X POST \
-H "Content-Type: application/json" \
-H "QuickBlox-REST-API-Version: 0.1.0" \
-H "QB-Token: 17f6a337b0656c9c7e983f9705d79562fc694c0e" \
-d '{"notification_channels": "apns", "push_token": {"environment": "development", "client_identification_sequence": "aa557232bc237245ba67686aa557232bc237245ba67686", "bundle_identifier": "com.quickblox.myawesomeapp"}, "device": {"platform": "ios", "udid": "2343af3433aa3a4fsv"}}' \
https://api.quickblox.com/subscriptions.json
```

**Comment by CookAmir** [comment]
Hi, I need help on Swift.
Thanks for your advice.

**Comment by CookAmir** [comment]
![image](https://user-images.githubusercontent.com/4521435/47381821-791c4580-d733-11e8-9335-12994022dad6.png)

Hi, I am still getting same issue.
Please help me. I need it very much.
Regard.

**Comment by williamtran1988** [comment]
Hi All, 

ARE THERE ANYWAY TO CREATE SUBSCRIPTION WITH "bundle_identifier" on iOS SDK?

QBMSubscription *subscription = [QBMSubscription subscription];
    subscription.notificationChannel = QBMNotificationChannelAPNS;
    subscription.deviceUDID = deviceUDID;
    subscription.deviceToken = deviceTokenData;

    [QBRequest createSubscription:subscription successBlock:^(QBResponse *response, NSA.....

Currently, i don't see where we can define this property?

**Comment by QB-vladyslav-vyshniak** [comment]
Hello, dear @williamtran1988 

I already provided you with the answer in the ticket #1102 
The status of the ticket changed to "Closed" due to duplicate.
