### ISSUE TITLE
Custom parameters with video call

### ISSUE THREAD

**Issue by DrMoriarty** [QuickBlox/quickblox-ios-sdk#11]
When I call 
[QBVideoChatInstance callUser:userID conferenceType:QBVideoChatConferenceTypeAudioAndVideo customParameters:customParameters;

the other side calls the QBChatDelegate method:
-(void) chatDidReceiveCallRequestFromUser:(NSUInteger)userID withSessionID:(NSString*)sessionID conferenceType:(enum QBVideoChatConferenceType)conferenceType;

So custom parameters have not been sent to the other side.

I understand that your enterprise clients may not need this feature, but I ask you to fix this issue, please.

**Comment by mgiraldo** [comment]
I am having a problem where the custom parameters get sent but the `chatCallDidAcceptByUser:customParameters:` delegate does not get fired. If I accept the call with no custom parameters (using `acceptCallWithOpponentID:conferenceType:`), the delegate does get fired (with some other "custom parameters": `callType, sessionID`).

What do I have wrong here?

**Comment by mgiraldo** [comment]
I had to break down the `customParameters` dictionary. I was sending a `CLLocation` and QB didn't like that (the event would not fire). Having separate `lat`, `lon`, `alt` components did fire the delegate event.

**Comment by soulfly** [comment]
Yes, it works with key-value string

**Comment by s612** [comment]
Hi I got

 rtc::<QBRTCClient 0x17024a9b0, delegates[0]> created new <QBRTCSession: 0x1702d5540, ID: 73A32B6D-49BD-469D-B709-166B7CDA2104, initiatorID: 10430785, opponentsIDs: 10430891, conferenceType: video(1), connections: 1>
2016-03-14 15:33:36:110 Test[730:63102] rtc::There is no delegates which responds to didReceiveNewSession:userInfo:

Can you please suggest me which delegate is missing ?
