### ISSUE TITLE
Unable to upload certificate in quickblox admin panel

### ISSUE THREAD

**Issue by jrana0017** [QuickBlox/quickblox-ios-sdk#1100]
Hi,

I'm not able to upload a certificate in quickblox admin panel for push notification. 

Attaching screen shot of an error for the reference. Please take a look and revert.

Thanks,
Jay
![screen shot 2018-10-19 at 6 22 55 pm](https://user-images.githubusercontent.com/44294351/47219290-0e35dc00-d3cc-11e8-8410-7cf00353020d.png)

**Comment by sshaforenkoqb** [comment]
Hi, you need to upload cert in p.12 format. Here is an instruction: https://quickblox.com/developers/APNS_instruction

**Comment by QB-vladyslav-vyshniak** [comment]
Hello, dear Jay.

More about APNS you can see by this link: https://quickblox.com/developers/APNS_instruction
If you have additional question, please let us know.
