### ISSUE TITLE
Could not create subscription with Bundle_identifier - IOS

### ISSUE THREAD

**Issue by williamtran1988** [QuickBlox/quickblox-ios-sdk#1102]
Hi All,

I am working on iOS sdk. Framework version 2.8.0.1 Do you know any way to create a subscription with bundle_identifier? I would like to support multi push notification certificate. I am using this

QBMSubscription *subscription = [QBMSubscription subscription];
    subscription.notificationChannel = QBMNotificationChannelAPNS;
    subscription.deviceUDID = deviceUDID;
    subscription.deviceToken = deviceTokenData;

    [QBRequest createSubscription:subscription successBlock:^(QBResponse *response, NSArray *objects) {
       
    } errorBlock:^(QBResponse *response) {
       
    }];

But i don't see anywhere to define bundle_identifier. 

Many thanks,
Thuong Tran.

**Comment by williamtran1988** [comment]
Hi @sshaforenkoqb 

Can I use QBRequest to make this kind of request? Could you please show me how to do that?

Thanks

**Comment by williamtran1988** [comment]
But the first certificate will be used as default, that's why my application build according to seconds cert will not work. It means that sdk will not takes automatically.

**Comment by williamtran1988** [comment]
Do you have any ideas?

**Comment by williamtran1988** [comment]
On Quickblox instruction:
Please make sure you keep the certificates up to date. We won't be able to send the APNS messages for you once certificates expire. If you have more than 1 push certificate for the same channel and environment and your push notifications subscriptions do not have 'bundle_identifier' value set - then the 1st uploaded certificate will be used. 

So when i tried to send a push message, at first CERT i can see the log:
400/BadDeviceToken

So i think SDK did not take bundle identifier by itself.

**Comment by sshaforenkoqb** [comment]
Here is a log from sample-push-notifications sample:
parameters: {
    device =     {
        platform = ios;
        udid = "57B9D830-90AE-4BD6-9484-7FBA896420BC";
    };
    "notification_channels" = apns;
    "push_token" =     {
        "bundle_identifier" = "com.quickblox.supersample";
        "client_identification_sequence" = 2dde940d87cde14e470b35a5db8eadf8f13a8730b6e03f2ad40e5de6b378e4f1;
        environment = development;
    };
}

As you can see bundle identifier is there.

**Comment by williamtran1988** [comment]
I have check subscriptions on quickblox CMS. the bundle_identifier is empty. It could be a problem on version 2.8.0.1?

**Comment by williamtran1988** [comment]
Anyway, do you know how to make a QBREquest on Objective C? I would like to add it instead of using createSubscription by SDK. Because i could not upgrade to latest version at the moment.

**Comment by QB-vladyslav-vyshniak** [comment]
Hello, dear @williamtran1988 

Take our apologies for the delay.
Could you try to make it in 2.17.1 version? There you will have the possibility to proceed with your request.

If this solution is suitable for you, please, confirm it.
Also, i already closed the ticket https://github.com/QuickBlox/quickblox-ios-sdk/issues/1103 as a duplicate.

**Comment by QB-vladyslav-vyshniak** [comment]
Dear @williamtran1988 

The status of the ticket changed to "Closed" due to the absence of the reply from you.
If you have any additional questions, please let us know.
