### ISSUE TITLE
How to custom QBRequest on IOS with Objective C?

### ISSUE THREAD

**Issue by williamtran1988** [QuickBlox/quickblox-ios-sdk#1103]
Hi All,

I  would like to create a function which can support create a subscription with specify Bundle_Identifier because my application supported multiple APNS certificate.

Could you please tell me how to do that? Can we use QBRequest to make REST API? If true how to do that?

Many thanks.
William Tran.

**Comment by QB-vladyslav-vyshniak** [comment]
Hello, dear @williamtran1988 

Thank you for contacting QuickBlox support.
I closed this ticket as a duplicate, original ticket: https://github.com/QuickBlox/quickblox-ios-sdk/issues/1102
We can continue the discussion there.
