### ISSUE TITLE
Chat messages wrong sorting - Objective-c

### ISSUE THREAD

**Issue by dudinvlad** [QuickBlox/quickblox-ios-sdk#1104]
Hi everyone! After several days I spent to resolve this issue I want to ask about help.
I using Quickblox to create chat, but not inherited from QMChatViewController as it shown in demo project. As a result my chat messages go upside down. I mean the newest message located on the top.
It happened after updating Quickblox and replaced chatSectionManager to chatDataSource.
So, is it possible to make message sorting as usual and not inherited from QMChatViewController?
![2018-11-01 3 05 45](https://user-images.githubusercontent.com/30140914/47853546-bf367080-dde7-11e8-843d-5511b4771c1d.png)

**Comment by QB-vladyslav-vyshniak** [comment]
Hello, dear @dudinvlad 

Thank you for contacting QuickBlox support.
Could you please confirm that this issue is still relevant for you and our developers will investigate the issue.

**Comment by QB-vladyslav-vyshniak** [comment]
The status of the ticket changed to "Closed" due to the absence of the reply from the user.
