### ISSUE TITLE
FaceDetection with AVCaptureVideoDataOutputSampleBufferDelegate or ARSCNViewDelegate

### ISSUE THREAD

**Issue by ValeriiVV** [QuickBlox/quickblox-ios-sdk#1106]
Hello, I have almost the same goal as astanton with his issue #404. I'm trying to detect face and make some manipulations then... Could you tell me please, is there any way to get access to AVCaptureVideoDataOutputSampleBufferDelegate or maybe somehow start ARSCNView's session in order to get access to its ARSCNViewDelegate methods? 

I have already tried to import in project your files from #404 issue: FaceDetectorCamera.h.
That file isn't being build anymore, I think it's out-of-date...

Thank you!

**Comment by QB-vladyslav-vyshniak** [comment]
Hello, dear @ValeriiVV 

Thank you for contacting QuickBlox support.
Could you please confirm that this issue is still relevant for you and our developers will investigate it.

**Comment by ValeriiVV** [comment]
Hello, yes, it is still relevant for me, thank you

**Comment by QB-vladyslav-vyshniak** [comment]
Hello, dear @ValeriiVV 

Due to WebRTC updates, some of the solutions that worked before couldn't be used now.
In this case, as a fast solution, you can use older versions of SDK, where the needed option is available.
