### ISSUE TITLE
QuickBlox Remote Video is freezing for video call Swift.

### ISSUE THREAD

**Issue by MaitriDB** [QuickBlox/quickblox-ios-sdk#1107]
**New Issue Checklist**

 - [ ] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [ ] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    | e.g. 8.0                                    |                                          
Quickblox iOS SDK version      | e.g. 2.7.6                                  |
QuickbloxWebRTC SDK version    | e.g. 2.2.1                                  |                               
Xcode Version                  | e.g. Xcode 8.1                              |
Repro with our demo sample     | e.g. does it happen with our demo sample?   |

**Did this work before?**
No

**Expected behavior**
When trying to do a video call remote video is freezing.
Actually i was trying to change the Video call UI , i want remote video as full screen and local video in corner. Sometimes remote video not updating and  is freezing.

**Actual behavior**
It should not freeze.

**Comment by QB-vladyslav-vyshniak** [comment]
Dear @MaitriDB 

Take our apologies for the delay in reply.
Could you please proceed with the update to the latest WebRTC version 2.7.3, find a link below: |
https://cocoapods.org/pods/Quickblox-WebRTC

Let us know about the result.

**Comment by QB-vladyslav-vyshniak** [comment]
Dear @MaitriDB 

The status of the ticket changed to "Closed" due to the absence of the reply.
