### ISSUE TITLE
QuickbloxWebRTC.framework missing x86_64 architecture

### ISSUE THREAD

**Issue by captainuberawesome** [QuickBlox/quickblox-ios-sdk#1109]
**New Issue Checklist**

 - [x] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [x] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none
(there is a similar issue, but it's old, closed and doesn't help)

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                  | 12.1                                     |
Quickblox iOS SDK version      | 2.17.1                                  |
QuickbloxWebRTC SDK version    | 2.7.2                                  |                               
Xcode Version                  | Xcode 10.1                              |
Repro with our demo sample     |  yes   |

**Did this work before?**
Yes, this error does not appear in QuickbloxWebRTC SDK version 2.7

**Expected behavior**

QuickbloxWebRTC framework should include symbols for architecture x86_64

**Actual behavior**

QuickbloxWebRTC framework is missing symbols for architecture x86_64

**Logs**
<details>
<summary>Xcode build logs</summary>

```logs

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_QBRTCCameraCapture", referenced from:
      objc-class-ref in CallViewController.o
  "_OBJC_CLASS_$_QBRTCVideoFormat", referenced from:
      objc-class-ref in CallViewController.o
  "_OBJC_CLASS_$_QBRTCRemoteVideoView", referenced from:
      objc-class-ref in CallViewController.o
  "_OBJC_METACLASS_$_QBRTCVideoCapture", referenced from:
      _OBJC_METACLASS_$__TtC29sample_videochat_webrtc_swift13ScreenCapture in ScreenCapture.o
  "_OBJC_CLASS_$_QBRTCAudioSession", referenced from:
      objc-class-ref in CallViewController.o
  "_OBJC_CLASS_$_QBRTCClient", referenced from:
      objc-class-ref in CallViewController.o
  "_OBJC_CLASS_$_QBRTCVideoFrame", referenced from:
      objc-class-ref in ScreenShareViewController.o
      objc-class-ref in ScreenCapture.o
  "_OBJC_CLASS_$_QBRTCConfig", referenced from:
      objc-class-ref in CallViewController.o
  "_OBJC_CLASS_$_QBRTCSession", referenced from:
      objc-class-ref in ScreenShareViewController.o
      objc-class-ref in CallViewController.o
  "_OBJC_CLASS_$_QBRTCVideoCapture", referenced from:
      objc-class-ref in ScreenShareViewController.o
      objc-class-ref in ScreenCapture.o
      type metadata for sample_videochat_webrtc_swift.ScreenCapture in ScreenCapture.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

```

</details>

**Steps to reproduce the behavior**
1. Update sample app QuickbloxWebRTC to version 2.7.2
2. Launch sample app in simulator

**Comment by dhavalpanchani** [comment]
I'm getting same error, I've tried a lot but no luck, 

@QuickBlox Team - Please help us asap as app is crashing a lot in the video call feature with multiple device logging in. I've see your past issues too, but not able to fix it. Can anyone help us on this?

**Comment by dhavalpanchani** [comment]
@captainuberawesome : What's the solution to run the app in the simulator? It's very hard to test in the real devices every time, as even other codes are not compiling in the simulator due to this QuickbloxWebRTC.framework.

**Comment by vadimkhmyrovqb** [comment]
@captainuberawesome , @dhavalpanchani QuickbloxWebRTC 2.7.3 has been released. It contains support of architecture x86_64.

**Comment by QB-vladyslav-vyshniak** [comment]
@captainuberawesome @dhavalpanchani 
Could you confirm that we can close this ticket and reply of @vadimkhmyrovqb  is suitable for you?

If you have any additional questions related to this ticket, please let me know.

**Comment by captainuberawesome** [comment]
@QB-vladyslav-vyshniak 

Yes, everything's okay now, thank you.
