### ISSUE TITLE
how to set user image with message in chat screen

### ISSUE THREAD

**Issue by NaveenYadavGithub** [QuickBlox/quickblox-ios-sdk#1110]
**New Issue Checklist**

 - [x] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [x] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    | e.g. 8.0                                    |                                          
Quickblox iOS SDK version      | e.g. 2.7.6                                  |
QuickbloxWebRTC SDK version    | e.g. 2.2.1                                  |                               
Xcode Version                  | e.g. Xcode 8.1                              |
Repro with our demo sample     | e.g. does it happen with our demo sample?   |

**Did this work before?**

**Expected behavior**

**Actual behavior**

**Logs**

*Please use the following template for logs:*

To enable full logs use the following code:
```objc
[QBSettings setLogLevel:QBLogLevelDebug];
[QBSettings enableXMPPLogging];
```

<details>
<summary>Title for logs </summary>

```logos

// Your logs here

```

</details>

**Steps to reproduce the behavior**

**Any others comments**

**Comment by NaveenYadavGithub** [comment]
Please help with your possible answer it's urgent. I'm stuck here

**Comment by QB-vladyslav-vyshniak** [comment]
Hello, dear Naveen.

Thank you for contacting us. 
Hope you are going well.

If you are using QMChatViewController for chat screen, you could use the following repository https://github.com/QuickBlox/QMChatViewController-ios 

Let me know if you have an additional question.

**Comment by QB-vladyslav-vyshniak** [comment]
Dear Naveen.

Could you please confirm that we can close this ticket and my previous reply is suitable for you?

**Comment by NaveenYadavGithub** [comment]
Sorry for late reply
 There is one more query please can you tell me how to download chat videos
from chating view or please give me it's reference link
Thankyou...!

**Comment by QB-vladyslav-vyshniak** [comment]
Dear @NaveenYadavGithub 

Thank you for the feedback.
Could you please try to use this solution: https://quickblox.com/developers/SimpleSample-chat_users-ios#Receive_attachment

**Comment by NaveenYadavGithub** [comment]
thanks

**Comment by QB-vladyslav-vyshniak** [comment]
Dear @NaveenYadavGithub 

Thank you for the feedback.
I change the status of the ticket to "Closed".

If you have any additional questions, please let us know.
