### ISSUE TITLE
Share user current location old API has been deprecated, any idea how to achieve with new API?

### ISSUE THREAD

**Issue by Kiran-Patel** [QuickBlox/quickblox-ios-sdk#1111]
**Does any one have any hint with new [Custom Objects module](https://quickblox.com/developers/Custom_Objects) feature that, how we can share user's current location(not live location) like WhatsApp using QuickBlox?**

_Originally posted by @Kiran-Patel in https://github.com/QuickBlox/quickblox-ios-sdk/issues/499#issuecomment-444765078_

**Comment by QB-vladyslav-vyshniak** [comment]
Hello, dear Kiran-Patel.

Thank you for contacting us.
Could you create the custom object with the fields: latitude, longitude, timestamp and "user_id".
Just update it when the location changes.
If you want to see the location of particular user you can get this custom object by "user_id".

Could you confirm that this is a suitable solution for you?

**Comment by QB-vladyslav-vyshniak** [comment]
Dear @Kiran-Patel 
Could you please check and confirm that my previous reply is suitable for you and I can close this ticket?
