### ISSUE TITLE
QB.instance.sendSystemMessage Crash EXC_BAD_ACCESS KERN_INVALID_ADDRESS

### ISSUE THREAD

**Issue by nyan2x** [QuickBlox/quickblox-ios-sdk#1113]
**New Issue Checklist**

 - [x] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [x] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    | 12.0                                    |                                          
Quickblox iOS SDK version      | 2.17.1                                  |                            
Xcode Version                  | Xcode 9.4.1                              |
Repro with our demo sample     |  intermittently   |

**Expected behavior**
It shouldn't crash

**Actual behavior**
When QB.instance.sendSystemMessage is called,
it Crashes with this error: EXC_BAD_ACCESS KERN_INVALID_ADDRESS

**Logs**
```
QB.instance.sendSystemMessage()
Quickblox | updateProgresForRequest
(Missing) | (Missing)
CoreFoundation | -[__NSDictionaryM setObject:forKeyedSubscript:]
```

**Steps to reproduce the behavior**
no specific steps. it happens intermittently every call of the sendSystemMessage

**Comment by QB-vladyslav-vyshniak** [comment]
Hello, dear Marianne.

Hope you are going well.
Thank you for contacting us.

Could you provide us with information about which fields you fill in QBMessage and detailed crash logs for the successful investigation.

**Comment by QB-vladyslav-vyshniak** [comment]
Dear Marianne.

According to the information from my colleague this ticket has been successfully resolved via ticket in the customer support portal.
I changed the status of the ticket to "Closed".

If you have any additional questions, please let me know.
