### ISSUE TITLE
Socket closed by remote peer

### ISSUE THREAD

**Issue by RahulTBI** [QuickBlox/quickblox-ios-sdk#1114]
Always i get this error "Socket closed by remote peer" while i am unlocking screen.

please help me out.

**Comment by sshaforenkoqb** [comment]
Hi RahulTBI, you can try to close chat connection when going to background.

**Comment by RahulTBI** [comment]
Hi sshaforenkoqb, Thanks for help.

**Comment by QB-vladyslav-vyshniak** [comment]
Hello, dear RahulTBI.

This issue is still relevant for you?
