### ISSUE TITLE
Push notification don't show payload

### ISSUE THREAD

**Issue by sv9988** [QuickBlox/quickblox-ios-sdk#1115]
Sometimes, when I test call on iOS device at production, I receive a push notification with call ID string. This is not correct with payload which I send when start a call.

Somethings, device not show push notification but it show call view from backgound. It's good!
So why sometimes, device receive push notification with call ID. How to fix to show call view?

**Comment by QB-vladyslav-vyshniak** [comment]
Dear Ngô.

Could you confirm that we can close this ticket and my previous reply is suitable for you?

**Comment by sv9988** [comment]
Thanks for your support. It's from backend side.
Please close this ticket.

**Comment by QB-vladyslav-vyshniak** [comment]
Dear Ngô.

Thank you for the feedback.
Always glad to help you.
