### ISSUE TITLE
IOS Swift Video Call UI

### ISSUE THREAD

**Issue by arjunmaniyar** [QuickBlox/quickblox-ios-sdk#1116]
How can we customize the video call UI in IOS swift 4?

**Comment by QB-vladyslav-vyshniak** [comment]
Hello, dear Arjun.

Thank you for contacting QuickBlox.
If you mean call screen, then yes. UI isn't a part of QuickBlox SDK, in this case, you may do anything you want.
If you have an additional question, please let us know.

**Comment by QB-vladyslav-vyshniak** [comment]
Dear Arjun.

Could you confirm that we can close this ticket and my reply is suitable for you?

**Comment by arjunmaniyar** [comment]
Hi,

 

We got the solution from our side.

You can close the ticket.

 

Thanks & Regards,

Arjun M

Skype: arjun.avion

1-646-290-5326

Confidential and Privileged

This communication and any accompanying documents are confidential and may also be legally privileged.  If you have received this transmission in error, you are advised that any disclosure, copying, distribution or the taking of any action in reliance upon this communication is strictly prohibited.  Moreover, any such disclosure shall not compromise or waive the confidentiality or privilege as to this communication or otherwise. If you have received this e-mail in error, please contact the sender immediately at the above email address, and delete the material from all your computers and servers. Thank you.

**Comment by QB-vladyslav-vyshniak** [comment]
Dear Arjun.

Thank you for the feedback.
Always glad to help you.
