### ISSUE TITLE
Can't remove privacy list

### ISSUE THREAD

**Issue by PoojaSachanIOSDeveloper** [QuickBlox/quickblox-ios-sdk#1119]
In My app there is blocked and unblocked user module.
Blocked user is working fine. but unblocked user is not working. 
 [[QBChat instance] removePrivacyListWithName:@"public"] is not working 

Here is my code
- (void)UnblockUserWithQBId:(NSUInteger)qbID{
    
    QBPrivacyItem *item = [[QBPrivacyItem alloc]initWithPrivacyType:QBPrivacyTypeUserID userID:qbID allow:YES];
    item.mutualBlock = NO;
    if (blockPrivacyList) {
        NSMutableArray<QBPrivacyItem *> *mutableItems = [blockPrivacyList.privacyItems mutableCopy];
        
        for (QBPrivacyItem * item in blockPrivacyList.privacyItems) {
            if (item.userID == qbID) {
                [mutableItems removeObject:item];
            }
        }
        
        blockPrivacyList.privacyItems = mutableItems;
        if (blockPrivacyList.privacyItems.count == 0) {
            [[QBChat instance] removePrivacyListWithName:@"public"];
        }
    }else{
        blockPrivacyList = [[QBPrivacyList alloc] initWithName:@"public" items:@[item]];
    }
    
    [[QBChat instance] setPrivacyList:blockPrivacyList];
    [[QBChat instance] setDefaultPrivacyListWithName:@"public"];
}

I am getting error "Can not modify list while being in use by other session"
I am waiting for your positive response

**Comment by QB-vladyslav-vyshniak** [comment]
Hello, dear Pooja.

Thank you for contacting QuickBlox support.
Did you read our documentation about "PrivacyLists" feature on IOS? 
Could you please check it by this link: https://quickblox.com/developers/SimpleSample-chat_users-ios#Privacy_lists

If you have any additional questions, please let me know.
