### ISSUE TITLE
QuickBlox not getting call when the Android App app is closed quickblox onReceiveNewSession not getting invoked,

### ISSUE THREAD

**Issue by vineeshLee** [QuickBlox/quickblox-ios-sdk#1120]
hi iam not getting call when the Android App app is closed quickblox onReceiveNewSession not getting invoked,is there any option to add callKit like IOS in android to solve this problem,please help.

_Originally posted by @vineeshLee in https://github.com/QuickBlox/quickblox-ios-sdk/issues/970#issuecomment-452967854_

**Comment by QB-vladyslav-vyshniak** [comment]
Hello, dear @vineeshLee 

Thank you for contacting QuickBlox support.
Could you please try to use the following documentation: https://quickblox.com/developers/Sample-webrtc-android#Track_session_states_via_QBRTCClientSessionCallbacks_interface
If the provided solution doesn't help, please, provide us with detail logs.

**Comment by vineeshLee** [comment]
Hi this issue is solved by using pushnotification.now iam facing an issue
iOS when calling from android iam getting  user information null in iOS
receiver function
? Please help to resolve this issues.

Thanks and Regards

Vineesh Kumar mk
ph:8547452226,8075136606

**Comment by QB-vladyslav-vyshniak** [comment]
Dear @vineeshLee 

Thank you for the report.
I will investigate the reported issue. 
As soon as I find the solution for you - I will let you know.

**Comment by vadimkhmyrovqb** [comment]
@vineeshLee Have you set user info as per documentation? https://quickblox.com/developers/Sample-webrtc-android#Start_Call

**Comment by QB-vladyslav-vyshniak** [comment]
The status of the ticket changed to "Closed" due to the absence of the reply.
