### ISSUE TITLE
Need audio call with callkit in swift

### ISSUE THREAD

**Issue by RahulTBI** [QuickBlox/quickblox-ios-sdk#1122]
Please help me out if anybody did this

Thanks
RahulTBI

**Comment by QB-vladyslav-vyshniak** [comment]
Hello, dear Rahul.

Thank you for contacting QuickBlox.
In this case, you can use the following resources: 
=>>https://quickblox.com/developers/Sample-webrtc-ios 
=>>https://github.com/QuickBlox/quickblox-ios-sdk/tree/master/sample-videochat-webrtc
=>>https://cocoapods.org/pods/Quickblox-WebRTC

**Comment by RahulTBI** [comment]
Hello, dear vladyslav
Thanks for reply

I already use this resources, audio call work perfectly in foreground, but i want it in kill state as well.
so i implement VoIP push notification, it occur while someone call, but my application was not launch automatically

**Comment by QB-vladyslav-vyshniak** [comment]
Dear @RahulTBI 

Could you please check this one: https://quickblox.com/developers/Sample-webrtc-ios#Calling_offline_users

**Comment by RahulTBI** [comment]
Thanks for your reply

I did same with your mentioned link.
i want VoIP push (silent notification). while it occur application automatically open and root will change to AudioVC controller where i have audio calling features

Thanks
RahulTBI

**Comment by QB-vladyslav-vyshniak** [comment]
Dear @RahulTBI 

Thank you for the feedback.
Please, use the following: https://quickblox.com/developers/Sample-webrtc-ios#Apple_CallKit 
Confirm if this solution is suitable for you.
