### ISSUE TITLE
Notification stop working

### ISSUE THREAD

**Issue by tung238** [QuickBlox/quickblox-ios-sdk#1123]
**New Issue Checklist**

 - [x ] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [ x] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    | 10.3.2, 11.4                                    |                                          
Quickblox iOS SDK version      | 2.17.1                                  |
QuickbloxWebRTC SDK version    | 2.7                                  |                               
Xcode Version                  | 10.1                              |

**Did this work before?**
YES

**Expected behavior**
Notification should show on receiver

**Actual behavior**
Notification not show (send from ios/android, receiver is ios/android)
Quickblox admin's queue show notifications in list with status "Active"

**Logs**
Log in admin console:
`APNS (Apple Push) Delivered: 0, failed: 0 

There were no recipients for this scheduled event. You may need to check 'Subscriber filtering' settings for your event. For example: there are no users with specified tags. `

**Steps to reproduce the behavior**

**Any others comments**
Seem it is stop working from around Jan 15, 2019 9PM
Both on production and develop (different quickblox account)
Certificates are ok (no error)
Receiver having active subscriptions

**Comment by vvdodiya** [comment]
Did you find any solution?

I have the same issue for notification. yesterday it was working fine but today notification can't receive on the receiver side.

it show in quickblox admin panal as Active status.

**Comment by QB-vladyslav-vyshniak** [comment]
Hello, dear @tung238 and @vvdodiya 

Thank you for contacting QuickBlox support.
This issue has been resolved. We had maintenance on our Shared (PROD) instance, but currently, all works as expected.
Could you please check and confirm that all works as expected on your side too.

**Comment by vvdodiya** [comment]
It is working but taking to much time. I receive notification after sometimes. I am implementing call functionality but when the notification arrived, the call is already timeout.

**Comment by tung238** [comment]
Confirm it is working again, thanks @QB-vladyslav-vyshniak!

**Comment by QB-vladyslav-vyshniak** [comment]
Dear @tung238 

Thank you for confirmation.
Glad that all works as expected on your side.

**Comment by QB-vladyslav-vyshniak** [comment]
Dear @vvdodiya 

Our developers are still resolving the issues with push notifications (delays, etc) after the maintenance.
We will resolve all issues as soon as possible.

**Comment by QB-vladyslav-vyshniak** [comment]
Dear @tung238 @vvdodiya 

Our DevOps and backend teams reported that all works as expected.
Could you please check and confirm it.

If you have any additional questions, please let me know.

**Comment by vvdodiya** [comment]
Confirmed it is working fine.. thanks @QB-vladyslav-vyshniak!
