### ISSUE TITLE
Notification still received after disabling for chat.

### ISSUE THREAD

**Issue by haarj** [QuickBlox/quickblox-ios-sdk#1125]
After calling

`+ (QBRequest *)updateNotificationsSettingsForDialogID:(NSString *)dialogID
                                               enable:(BOOL)enable
                                         successBlock:(nullable void(^)(BOOL enabled))successBlock
                                           errorBlock:(nullable qb_response_block_t)errorBlock;`

I'm still receiving push notifications for a specific dialog id with the below app delegate still getting called on background. 

`(void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo fetchCompletionHandler:(void (^)(UIBackgroundFetchResult))completionHandler {`

LOGS:
2019-01-30 06:47:43.143758-0500 level[5425:1416587] [QBCore]: Request[10]:
PUT URL:https://api.quickblox.com/chat/Dialog/5c460f9ea0eb472e4c271774/notifications.json
headers: {
    "Accept-Language" = "en-US;q=1";
    "Content-Type" = "application/x-www-form-urlencoded";
    "QB-OS" = "iOS 12.1.2";
    "QB-SDK" = "iOS 2.17.1";
    "QB-Token" = 5e862eb38b65dc044c920b523945307f0300f5f9;
    "QuickBlox-REST-API-Version" = "0.1.1";
    "User-Agent" = "level/1.1.5 (iPhone; iOS 12.1.2; Scale/3.00)";
}
parameters: {
    enabled = 0;
}
2019-01-30 06:47:43.349148-0500 level[5425:1416587] [QBCore]: Response[10]:
headers: {
    "Access-Control-Allow-Origin" = "*";
    "Cache-Control" = "max-age=0, private, must-revalidate";
    Connection = "keep-alive";
    "Content-Length" = 31;
    "Content-Type" = "application/json; charset=utf-8";
    Date = "Wed, 30 Jan 2019 11:47:43 GMT";
    Duration = "0.206073";
    Etag = "W/\"a1313eb6e1c29ba21056fb350b318ece\"";
    "QB-Token-ExpirationDate" = "2019-01-30 13:39:13 +0000";
    "QuickBlox-REST-API-Version" = "0.1.1";
    Server = "nginx/1.8.1";
    "Set-Cookie" = "_mkra_ctxt=4ab11bcdfb19758a8f6e06f19e27c768--200; path=/; max-age=5; HttpOnly; secure";
    Status = "200 OK";
    "Strict-Transport-Security" = "max-age=31536000, max-age=15768000;";
    "X-Content-Type-Options" = nosniff;
    "X-Frame-Options" = SAMEORIGIN;
    "X-Request-Id" = "dd732f91-549e-4081-a2f7-7b24ced8acee";
    "X-Runtime" = "0.024920";
    "X-XSS-Protection" = "1; mode=block";
}
object: {
    notifications =     {
        enabled = 0;
    };
}

**Comment by haarj** [comment]
Hello @QB-vladyslav-vyshniak,

Any info about this?

Thanks,

Justin

**Comment by QB-vladyslav-vyshniak** [comment]
Hello, dear @haarj 

Thank you for contacting QuickBlox support.
I already sent the reported issue to our developers. 
As soon as they provide me with the solution - i will let you know.

**Comment by haarj** [comment]
Ok. Thanks @QB-vladyslav-vyshniak!

**Comment by QB-vladyslav-vyshniak** [comment]
Dear @haarj 

Did you try this method? - https://quickblox.com/developers/Chat#Update_notifications_settings

**Comment by justinhaar** [comment]
Hey @QB-vladyslav-vyshniak ,

I used the above iOS SDK method in the description.

**Comment by QB-vladyslav-vyshniak** [comment]
Dear @haarj 

Could you please implement this option as you can see in our documentation and check it again.

**Comment by justinhaar** [comment]
@QB-vladyslav-vyshniak 

I want to use `+ (QBRequest *)updateNotificationsSettingsForDialogID:(NSString *)dialogID enable:(BOOL)enable successBlock:(nullable void(^)(BOOL enabled))successBlock errorBlock:(nullable qb_response_block_t)errorBlock;`

, which is calling that api internally. It seems that even if I do use the one you suggested, it still won't work based on the logs I attached. Something seems to be wrong server side.

**Comment by QB-vladyslav-vyshniak** [comment]
Dear @justinhaar 

Thank you for the feedback.
I will check the reported issue with our developers and get back to you soon.

**Comment by QB-vladyslav-vyshniak** [comment]
Hello, dear @haarj @justinhaar 

Our developers detected the reported issue, it will be fixed in the next release.
The status of the ticket changed to "Closed".

**Comment by justinhaar** [comment]
Ok great. Is this an iOS SDK fix? If so, when is the expected release of that?

Thanks!

Justin Haar
201-218-9631

Sent from my iPhone

On Feb 22, 2019, at 9:41 AM, Vladyslav Vyshniak <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #1125<https://github.com/QuickBlox/quickblox-ios-sdk/issues/1125>.

**Comment by QB-vladyslav-vyshniak** [comment]
Dear @justinhaar 

The reported issue is related to the backend side. 
It will be fixed after deploying of new release next week.

If you have any additional questions, please let us know.

**Comment by haarj** [comment]
Great! Thanks for clarifying!

**Comment by haarj** [comment]
@QB-vladyslav-vyshniak, 

This is still not working.

**Comment by QuickBlox-team** [comment]
This email is confirmation that you are now registered at our helpdesk.

Registered email: reply@reply.github.com
Password: lhweje4lpf

You can visit the helpdesk to browse articles and contact us at any time: https://assist.quickblox.com/

Thank you for registering!


QuickBlox

Helpdesk: https://assist.quickblox.com/index.php?

**Comment by haarj** [comment]
Hi. I'm testing this again and it's still not working.
