### ISSUE TITLE
No dial tone playing when phone is on silent

### ISSUE THREAD

**Issue by RahulTBI** [QuickBlox/quickblox-ios-sdk#1126]
Hi everyone,

I need dial tone when my phone is on silent.

Currently when i put my phone on silent, dial tone not played.

Please help me out

Thanks
RahulTBI

**Comment by QB-vladyslav-vyshniak** [comment]
Hello, dear RahulTBI.

Thank you for contacting QuickBlox support.
I sent the reported issue to our developers and they will proceed with the internal investigation.
As soon as they provide me with the result - i will let you know.

**Comment by RahulTBI** [comment]
Thank you for reply

Please help me soon

**Comment by QB-vladyslav-vyshniak** [comment]
Dear @RahulTBI 

In this case, you could use AVAudioPlayer instead of standard system audio from our sample for dial tone. 
This is a single solution which I can propose to you.

If you have any additional questions, please let us know.

**Comment by RahulTBI** [comment]
Thanks for reply,

In AVAudioPlayer sound play in speaker not in ear speaker

**Comment by RahulTBI** [comment]
Hi
any update about my issue

Please help me

**Comment by QB-vladyslav-vyshniak** [comment]
Dear @RahulTBI 

I already sent your report to our developers.
I will let you know as soon as they provide me with any solution.

**Comment by RahulTBI** [comment]
Ok thanks

**Comment by QB-vladyslav-vyshniak** [comment]
Dear @RahulTBI 

In this case, you can try to use the following method: 
`AVAudioSession *audioSession = [AVAudioSession sharedInstance];
[audioSession setCategory:AVAudioSessionCategoryPlayAndRecord error:nil];
[audioSession setActive:YES error:nil];

AVAudioSessionPortDescription *routePort = audioSession.currentRoute.outputs.firstObject;
NSString *portType = routePort.portType;

if ([portType isEqualToString:@"Receiver"])

{ [audioSession overrideOutputAudioPort:AVAudioSessionPortOverrideSpeaker error:nil]; } `
Also, you can investigate this ticket:  https://stackoverflow.com/questions/31692577/how-to-play-audio-through-built-in-earpiece-speaker

If you have any additional questions, please let us know.

**Comment by RahulTBI** [comment]
Yes i already use the AVAudiosession he works fine, but if my phone is on silent mode and i call opponent user then my ring will play in my ear speaker, but not i here in speaker so this is not user friendly.


thanks
RahulTBI

**Comment by RahulTBI** [comment]
Hiii any update?

**Comment by QB-vladyslav-vyshniak** [comment]
Dear @RahulTBI 

In this case, please proceed with the investigation and corrections on your side.
This issue isn't related to our SDK.
