### ISSUE TITLE
User does not have a confirmed email address

### ISSUE THREAD

**Issue by RahulTBI** [QuickBlox/quickblox-ios-sdk#1128]
Hi 
When i try to forgot my password it produces error that "User does not have a confirmed email address"

(Error Domain=api.quickblox.com Code=403 \"Request failed: forbidden (403)\" UserInfo={NSErrorFailingURLKey=https://api.quickblox.com/users/password/reset.json?email=rv@gmail.com, NSLocalizedFailureReason={\n    errors =     (\n        \"User does not have a confirmed email address\"\n    );\n}, NSLocalizedDescription=Request failed: forbidden (403)})")

Please help me out

Thanks
RahulTBI

**Comment by QB-vladyslav-vyshniak** [comment]
Hello, dear @RahulTBI 

Thank you for contacting QuickBlox support.
Could you please send me e-mail address of the user which try to recovery password to vlad.vishnyak@quickblox.com and we will investigate it.

**Comment by RahulTBI** [comment]
I sent mail on mentioned above mail id

**Comment by QB-vladyslav-vyshniak** [comment]
Dear @RahulTBI 

I already provided you with the answer via Gmail. 
The status of the ticket changed to "Closed".

If you have any additional questions, please let us know.

**Comment by RahulTBI** [comment]
I did not get your mail with this information.

**Comment by AmitBhavsarIphone** [comment]
Same issue facing in my app

When i try to reset my password it produces error that "User does not have a confirmed email address"

Can anyone please help regarding this?

In Settings: 

User > Settings > Require email confirmation (for application users) 
This option is already unchecked.

**Comment by QuickBlox-team** [comment]
This email is confirmation that you are now registered at our helpdesk.

Registered email: reply@reply.github.com
Password: rf3lqwe7cv

You can visit the helpdesk to browse articles and contact us at any time: https://assist.quickblox.com/

Thank you for registering!


QuickBlox

Helpdesk: https://assist.quickblox.com/index.php?
