### ISSUE TITLE
Disable notification for some chat dialog

### ISSUE THREAD

**Issue by RahulTBI** [QuickBlox/quickblox-ios-sdk#1129]
Hi everyone,

I would like to disable push notification for some chat dialog. i send push notification while i sent message to user. 

If my group chat type is normal means one-to-one chat, if opposite user disable (mute) notification then this particular user wont get chat notification about messages.

if my group chat type is group means group chat. if any opponent will disable (mute) notification then this particular user wont get chat notification but other participant will get chat notifications message about new messages

how should i implement this?

Thanks
RahulTBI

**Comment by QB-vladyslav-vyshniak** [comment]
Hello, dear @RahulTBI 

Thank you for contacting QuickBlox support.
Here is the solution: https://quickblox.com/developers/Chat#Update_notifications_settings

Could you please confirm that the provided option is suitable for you and we can close the ticket?
Let us know if you have any additional questions.

**Comment by RahulTBI** [comment]
I have not enable push chat alert, i am sending manual push notification while sending a message.
so this is not possible

**Comment by haarj** [comment]
I'd like to just share that I had the same issue with mine below. 

https://github.com/QuickBlox/quickblox-ios-sdk/issues/1125

Thanks

**Comment by QB-vladyslav-vyshniak** [comment]
The status of the ticket changed to "Closed" due to inactivity.
If the reported issue is still actual for you - please reopen the ticket.
