### ISSUE TITLE
Chat Dialog custom data not saved.

### ISSUE THREAD

**Issue by RahulTBI** [QuickBlox/quickblox-ios-sdk#1130]
Hii everyone,

I am trying to save custom data in QBChatDialog, but it is not updated both side means all user that are in group.

I need to set custom data for notification type. if user set active value in custom data of chat dialog, opposite user will send push notification about new message. and if user set deactivate value in custom data then opposite user will not send push notification.

please help me out 

Thanks,
RahulTBI

**Comment by vadimkhmyrovqb** [comment]
@RahulTBI Please share the code sample or request that you try. Please also check this article about dialog's custom data: https://quickblox.com/developers/Chat#Set_custom_parameters

**Comment by RahulTBI** [comment]
Thanks for reply

i used data property for storing custom data in chatdialog

dialog.data = ["notificationActiveStat" : "1", "userId" : CuurentUser.id], here currentUserId means login user id.

thanks
RahulTBI

**Comment by QB-vladyslav-vyshniak** [comment]
The status of the ticket changed to "Closed" due to inactivity.
If the reported issue is still actual for you - please reopen the ticket.
