### ISSUE TITLE
Audio Call Not worked sometimes in Swift

### ISSUE THREAD

**Issue by RahulTBI** [QuickBlox/quickblox-ios-sdk#1131]
Hii everyone,

I need audio call features in my application, it worked perfectly, but sometimes session was not created so opponent can not receive call signal in didReceiveNewSession method.

few call will work fine, but after that it did not work, caller can not here dial tone as well else opponent wont receive call signal. 

didReceiveNewSession not being called sometimes 

please help me out for this problem

Thanks
RahulTBI

**Comment by vadimkhmyrovqb** [comment]
@RahulTBI Did you try it on the samples from our documentation? Is there any kind of error in the logs?

**Comment by RahulTBI** [comment]
Yes, i tried it.
i create session successfully but sometime opponent will not receive call signal in didReceiveNewSession method, so we can not proceed due to mentioned issue.

while i call userA after userA receive call signal and i present audio view controller, whatever action will performed by user i.e., accept or reject or timeout. after userA will call me back at that time i did not receive call signal in delegate method

Thanks
RahulTBI

**Comment by RahulTBI** [comment]
Hello,

When we go through notification at that time opponent user don't receive new call signal in didReceiveNewSession method.
so call will not be connected.

please help me out.

Thanks
RahulTBI

**Comment by RahulTBI** [comment]
Hiiii any update?

**Comment by IgorChernobayQB** [comment]
@RahulTBI,

Unfortunately, we had an issue on our server at that period of time.

Please confirm if your issue still occurs.
If yes, specify which version of the SDK you used and exactly what sample you tried.

**Comment by RahulTBI** [comment]
Alright, will check it soon

Thanks

**Comment by QB-vladyslav-vyshniak** [comment]
The status of the ticket changed to "Closed" due to inactivity.
If the reported issue is still actual for you - please reopen the ticket.
