### ISSUE TITLE
deleteMessages

### ISSUE THREAD

**Issue by HFMohammad** [QuickBlox/quickblox-ios-sdk#1132]
I use below code for delete message
But this code remove message only for sender
I want delele messaeg for sender and receiver

```
QBRequest.deleteMessages(withIDs: Set(arrayLiteral: "..."), forAllUsers: false, successBlock: { (response: QBResponse!) -> Void in
                print("errorCheck2 \(response)")
            }) { (response: QBResponse!) -> Void in
                print("errorCheck1 \(response)")
            }
```

**Comment by HFMohammad** [comment]
I change `forAllUsers: false` to `forAllUsers: true` and fix it

**Comment by QB-vladyslav-vyshniak** [comment]
Hello, dear @HFMohammad 

Thank you for contacting QuickBlox support.
Glad to hear that you successfully fixed the issue and all works as expected on your side.

If you have any additional questions, let us know. 
Also, you can use QB documentation for implementation: https://quickblox.com/developers/QuickBlox_Developers
