### ISSUE TITLE
Audio Call Push Notification not playing ring continuously, it plays & vibrate it in a second

### ISSUE THREAD

**Issue by RahulTBI** [QuickBlox/quickblox-ios-sdk#1133]
Hi everyone

I have audio call feature in my application, when i call to opponent user, and if the user is offline, i sent push notification with custom sound, push notification occur successfully, but sound and vibration is just a single time means it play and vibrate in a second only, i want it to continuously play until i tapped on it or call time out.

Please help me out 

Thanks
RahulTBI

**Comment by RahulTBI** [comment]
Hiii any update?

**Comment by QB-vladyslav-vyshniak** [comment]
Hello, dear @RahulTBI 

Thank you for contacting QuickBlox support.
We don't have the requested option for push notifications, please proceed with the customization from your side.

**Comment by dansinclair25** [comment]
@RahulTBI don't use ordinary push notifications for VOIP calls - you should send VOIP push notifications instead.

Alternatively, play a sound file in the call push notification that is 30 seconds long (which is the max time a sound from a push notification can be played on iOS).
