### ISSUE TITLE
QB_SRWebSocket Thread 1: signal SIGABRT in swift 4.2

### ISSUE THREAD

**Issue by BRLOKESH** [QuickBlox/quickblox-ios-sdk#1134]
i am using you demo project : sample-conference-videochat-swift
QB_SRWebSocket Thread 1: signal SIGABRT in swift 4.2

rtc::[ConferenceClient] Establishing signaling connection.
rtc::[RTCClient] Initializing SSL...
rtc::[Conference] Opening Socket.

Assertion failed: ([scheme isEqualToString:@"ws"] || [scheme isEqualToString:@"http"] || [scheme isEqualToString:@"wss"] || [scheme isEqualToString:@"https"]), function -[QB_SRWebSocket _SR_commonInit], file /Users/vitaliygorbachov/Downloads/QB3rdParty/SocketRocket/SocketRocket/SRWebSocket.m, line 311.

warning: could not execute support code to read Objective-C class data in the process. This may reduce the quality of type information available.

**Comment by QB-vladyslav-vyshniak** [comment]
Hello, dear @BRLOKESH 

Thank you for contacting QuickBlox support.
It seems like some mistake in line 311, please proceed with the investigation of implementation. 

Let us know about the result.

**Comment by DikenOpenxcell** [comment]
Hello,

I am facing the same issue. Have you found any solution for that?

**Comment by QuickBlox-team** [comment]
This email is confirmation that you are now registered at our helpdesk.

Registered email: reply@reply.github.com
Password: mupwe8btup

You can visit the helpdesk to browse articles and contact us at any time: https://assist.quickblox.com/

Thank you for registering!


QuickBlox

Helpdesk: https://assist.quickblox.com/index.php?
