### ISSUE TITLE
Unread message counter updated from dialog screen (Not in chat view controller)

### ISSUE THREAD

**Issue by RahulTBI** [QuickBlox/quickblox-ios-sdk#1135]
Hiii everyone

currently i am facing this issue, when both user are in message list screen (i mean list of dialog screen), at that time any user message unread counter visible with 1 and increment it when another message arrived from same user, but it disappear instantly.

sometimes unread message does not disappear, while i come back from chat view to message list screen

Thanks,
RahulTBI

**Comment by QB-vladyslav-vyshniak** [comment]
Hello, dear @RahulTBI 

Thank you for contacting QuickBlox support.
Do you use your own application or Q-municate?

**Comment by RahulTBI** [comment]
Thanks for reply
I am using my own application not Q-municate

**Comment by QB-vladyslav-vyshniak** [comment]
Dear @RahulTBI 

It seems like a strange behavior on your side (incorrect logic or implementation).
We didn't meet this bug previously, I can suggest to use IOS chat guide by this link:
https://quickblox.com/developers/SimpleSample-chat_users-ios#Guide:_Getting_Started_with_Chat_API
You can find a lot of useful options there and implement it correctly on your side.

**Comment by RahulTBI** [comment]
Hi @QB-vladyslav-vyshniak 

Now i am using Q-municate services, but issue remains same.

**Comment by QB-vladyslav-vyshniak** [comment]
Dear @RahulTBI 

In this case, please provide us with video proof of the issue.
Looking forward to your reply.

**Comment by RahulTBI** [comment]
Yes will provide you video soon
let me reproduce this issue, cause it happen sometimes

**Comment by RahulTBI** [comment]
Dear @QB-vladyslav-vyshniak 

Please check below video link for better understanding
https://drive.google.com/file/d/1gvAvrfpAZjQL9lpInGLq5fNgd76euteU/view?usp=sharing

**Comment by QB-vladyslav-vyshniak** [comment]
Dear @RahulTBI 

Thank you for the provided video proof.
I will send it to developers for the investigation. 

I will let you know as soon as they provide me with the result.

**Comment by RahulTBI** [comment]
Ok thanks @VladimirNybozhinsky

**Comment by nanirocks125** [comment]
I am also facing the same issue mentioned in the video.

**Comment by QB-vladyslav-vyshniak** [comment]
The status of the ticket changed to "Closed" due to inactivity.
If the reported issue is still actual for you - please reopen the ticket.
