### ISSUE TITLE
iPhone X screen sharing issue

### ISSUE THREAD

**Issue by iamfarmankhan** [QuickBlox/quickblox-ios-sdk#1137]
Actually, I am facing an issue with iPhone X screen sharing feature with QuickBlox iOS sdk. Whenever we share screen from iPhone X then it got scaled automatically.

Please refer the screenshot:
![Simulator Screen Shot - iPhone XR - 2019-03-22 at 16 34 01](https://user-images.githubusercontent.com/19756500/54818965-c1df1880-4c57-11e9-81f8-b794ce492a62.png)

**Comment by QB-vladyslav-vyshniak** [comment]
Hello, dear @iamfarmankhan 

Thank you for contacting QuickBlox support.
In the reported case you can proceed with setting up of "UIImage" parameter before making the call.
Screen sharing documentation: https://quickblox.com/developers/Sample-webrtc-ios#Screen_sharing

If you have any additional questions, please let us know.

**Comment by QB-vladyslav-vyshniak** [comment]
The status of the ticket changed to "Closed" due to the absence of the reply.
