### ISSUE TITLE
downloadCurrentEnvironmentUsers give me Request failed: not found (404) error

### ISSUE THREAD

**Issue by RahulTBI** [QuickBlox/quickblox-ios-sdk#1138]
When i fetch user from QuickBlox using downloadCurrentEnviornmentUsers method, but it will giving me below error

 ["NSLocalizedDescription": Request failed: not found (404), "NSErrorFailingURLKey": https://api.quickblox.com/users/by_tags.json?page=1&per_page=100&tags=dev, "NSLocalizedFailureReason": {
    code = "<null>";
    message = "Couldn't find user";
}]

my current user environment is 
```
 #if DEBUG
            return "dev"
        #elseif QA
            return "qbqa"
        #else
            assert(false, "Not supported build configuration")
            return ""
        #endif
```
in admin panel there is one field tags in user tables quickblox web side. I set dev/qbqa tag, but it also not work.

Thanks,
RahulTBI

**Comment by QB-vladyslav-vyshniak** [comment]
Hello, dear @RahulTBI 

Thank you for contacting QuickBlox support.
Please, could you investigate the following information about how to retrieve users by different methods: https://quickblox.com/developers/Users

Let us know about the result after your investigation.

**Comment by QB-vladyslav-vyshniak** [comment]
The status of the ticket changed to "Closed" due to the absence of the reply.
