### ISSUE TITLE
attachment.localFileURL always return nil

### ISSUE THREAD

**Issue by RahulTBI** [QuickBlox/quickblox-ios-sdk#1139]
Hi everyone,

In chat attachement services, when i sent video to opponent user, it sends perfectly, but when i fetch localurl of particular attachment i return it nil.

i need cache management for faster video playing, how local video play directly in chatviewcontroller of QMChatAttachmentOutgoingCell.

Thanks
RahulTBI

**Comment by QB-vladyslav-vyshniak** [comment]
The status of the ticket changed to "Closed" due to inactivity.
If the reported issue is still actual for you - please reopen the ticket.
