### ISSUE TITLE
Display PDF Document attachment with thumbnail

### ISSUE THREAD

**Issue by nanirocks125** [QuickBlox/quickblox-ios-sdk#1142]
How to display thumbnail of document , am able to send documents to my friend.
I tried with PDFView from PDFKit but could not get document.

After downloading data using 
 **QBRequest.downloadFile(withUID: attachmentID, successBlock: { (response, data) in
             guard let page = PDFDocument(data: data)?.page(at: 0) else { return nil }
        }, statusBlock: { (request, requestStatus) in
            print("progress \(requestStatus.percentOfCompletion)")
        }) { (response) in
            print("error in downloading the document")
  }**

In the sample code, PDFDocument(data: data)?.page(at: 0) returning nil

**Comment by QuickBlox-team** [comment]
This email is confirmation that you are now registered at our helpdesk.

Registered email: reply@reply.github.com
Password: cezq3kmbmv

You can visit the helpdesk to browse articles and contact us at any time: https://assist.quickblox.com/

Thank you for registering!


QuickBlox

Helpdesk: https://assist.quickblox.com/index.php?

**Comment by vadimkhmyrovqb** [comment]
@nanirocks125 

Try the following:
```

QBRequest.blob(withID: attachmentID, successBlock: { (response, file) in
	// see https://quickblox.com/developers/SimpleSample-content-ios#Public.2FPrivate_urls
	let url = file.isPublic ? file.publicUrl : file.privateUrl
	// use url to display pdf file (for example in the WebView)
}, errorBlock: { (errorResponse) in
	// handle error
})
```

**Comment by QB-vladyslav-vyshniak** [comment]
The status of the ticket changed to "Closed" due to inactivity.
If the reported issue is still actual for you - please reopen the ticket.
