### ISSUE TITLE
Chat View Controller display Download Button icon centre of the screen

### ISSUE THREAD

**Issue by RahulTBI** [QuickBlox/quickblox-ios-sdk#1143]
Hi, i have face this issue while i implement private chat.
once i navigate to chat view controller there are already display download icon centre of the screen, this image is no longer available in my project.

please see this image for better understanding.

![IMG_0180](https://user-images.githubusercontent.com/44398163/56571190-099beb80-65da-11e9-8780-2239e2e37056.png)
![IMG_0181](https://user-images.githubusercontent.com/44398163/56571191-099beb80-65da-11e9-8724-d8fc9b8a2cc2.png)

Please help me out with this problem

Thanks
Rahul

**Comment by QuickBlox-team** [comment]
This email is confirmation that you are now registered at our helpdesk.

Registered email: reply@reply.github.com
Password: t3qqchp0pe

You can visit the helpdesk to browse articles and contact us at any time: https://assist.quickblox.com/

Thank you for registering!


QuickBlox

Helpdesk: https://assist.quickblox.com/index.php?

**Comment by RahulTBI** [comment]
From where can i enter this credential?

Registered email: reply@reply.github.com
Password: t3qqchp0pe

**Comment by QuickBlox-team** [comment]
This email is confirmation that you are now registered at our helpdesk.

Registered email: reply@reply.github.com
Password: tfqcrhpvn3

You can visit the helpdesk to browse articles and contact us at any time: https://assist.quickblox.com/

Thank you for registering!


QuickBlox

Helpdesk: https://assist.quickblox.com/index.php?

**Comment by RahulTBI** [comment]
i try with mentioned credential, but credential was incorrect

**Comment by QuickBlox-team** [comment]
This email is confirmation that you are now registered at our helpdesk.

Registered email: reply@reply.github.com
Password: w3xf7cuerk

You can visit the helpdesk to browse articles and contact us at any time: https://assist.quickblox.com/

Thank you for registering!


QuickBlox

Helpdesk: https://assist.quickblox.com/index.php?

**Comment by QB-vladyslav-vyshniak** [comment]
Hello, dear @RahulTBI 

Thank you for contacting QuickBlox support.

I have already provided you with the answer in QB support portal, ticket #143330

The status of the ticket changed to "Closed".

Let me know if you have any additional questions.
