### ISSUE TITLE
Thread 1: signal SIGABRT

### ISSUE THREAD

**Issue by abhijeetji24** [QuickBlox/quickblox-ios-sdk#1144]
I have downloaded the code from github and running the sample-conference-videochat-swift demo. When i try to initiate video call it is crashing with the error here:- "session = QBRTCConferenceClient.instance().createSession(withChatDialogID: chatDialog.id!,
                                                                 conferenceType: conferenceType)"
The error says "Thread 1: signal SIGABRT". Please let me know the solution.

**Comment by QuickBlox-team** [comment]
This email is confirmation that you are now registered at our helpdesk.

Registered email: reply@reply.github.com
Password: nrk2cnjty8

You can visit the helpdesk to browse articles and contact us at any time: https://assist.quickblox.com/

Thank you for registering!


QuickBlox

Helpdesk: https://assist.quickblox.com/index.php?

**Comment by dansinclair25** [comment]
@abhijeetji24 did you run this in the simulator? If so, don't. Run it on a real device.

**Comment by QB-vladyslav-vyshniak** [comment]
The status of the ticket changed to "Closed" due to inactivity.
If the reported issue is still actual for you - please reopen the ticket.
