### ISSUE TITLE
push notification issue foir chat 

### ISSUE THREAD

**Issue by suryaween** [QuickBlox/quickblox-ios-sdk#1145]
I have wbeen facing push notification issue win chat. When two individuals chat to each other . the other user doesnot receive messages as notification or notifications when the app is in background mode .

**Comment by QuickBlox-team** [comment]
This email is confirmation that you are now registered at our helpdesk.

Registered email: reply@reply.github.com
Password: 8mgzmkqjze

You can visit the helpdesk to browse articles and contact us at any time: https://assist.quickblox.com/

Thank you for registering!


QuickBlox

Helpdesk: https://assist.quickblox.com/index.php?
