### ISSUE TITLE
User does not have a confirmed email address

### ISSUE THREAD

**Issue by AmitBhavsarIphone** [QuickBlox/quickblox-ios-sdk#1146]
When i try to reset my password it produces error that "User does not have a confirmed email address"

Can anyone please help regarding this?

In Settings:
User > Settings > Require email confirmation (for application users)
This option is already unchecked.

**Comment by QuickBlox-team** [comment]
This email is confirmation that you are now registered at our helpdesk.

Registered email: reply@reply.github.com
Password: ocdr16ph3k

You can visit the helpdesk to browse articles and contact us at any time: https://assist.quickblox.com/

Thank you for registering!


QuickBlox

Helpdesk: https://assist.quickblox.com/index.php?

**Comment by AmitBhavsarIphone** [comment]
I also tried with enable "Require email confirmation (for application users)" option, but at the time of sign up I am getting this error "Unsupported argument type: MailTemplate"

Confirmation mail also not received to email id.

**Comment by QuickBlox-team** [comment]
This email is confirmation that you are now registered at our helpdesk.

Registered email: reply@reply.github.com
Password: ddgogy2y3w

You can visit the helpdesk to browse articles and contact us at any time: https://assist.quickblox.com/

Thank you for registering!


QuickBlox

Helpdesk: https://assist.quickblox.com/index.php?

**Comment by QB-vladyslav-vyshniak** [comment]
Hello, dear @AmitBhavsarIphone 

Thank you for contacting QuickBlox support. 

Unfortunately, API users can reset their password through the contacting of the account owner. 
Currently, that issue is resolving by QB developers.

Let me know if you have any additional questions.

**Comment by QuickBlox-team** [comment]
This email is confirmation that you are now registered at our helpdesk.

Registered email: reply@reply.github.com
Password: diswjh68x4

You can visit the helpdesk to browse articles and contact us at any time: https://assist.quickblox.com/

Thank you for registering!


QuickBlox

Helpdesk: https://assist.quickblox.com/index.php?

**Comment by AmitBhavsarIphone** [comment]
I received 2 or 3 emails of reset password and again it stop receiving.

If I will plan to use custom web-page to reset password, Is below API will work?

PUT https://api.quickblox.com/update_password.json
    - user[reset_password_token]
    - user[password]
    - user[password_confirmation]

As per my testing default reset password page and this API, both are not working properly.

@QB-vladyslav-vyshniak 
I have blocker in my app because of this functionality, can you please try to solve it?

**Comment by QB-vladyslav-vyshniak** [comment]
Dear @AmitBhavsarIphone 

I have provided you with answer in QB support portal, ticket #143474

Let me know if you have any additional questions.

**Comment by haarj** [comment]
Hi @QB-vladyslav-vyshniak,

Can you share that answer here as well?

Thanks!

**Comment by HussainTechGee** [comment]
@QB-vladyslav-vyshniak i'm facing the same issue as quickblox server is not sending a reset password mail to user. I have enabled authenticate user email checkbox in users > setting > Require email confirmation (for application users).

**Comment by sohaibkhaa** [comment]
I'm having the same issue 
"User does not have a confirmed email address"
can anyone help?
