### ISSUE TITLE
Get chat dialogs from specific date

### ISSUE THREAD

**Issue by suryaween** [QuickBlox/quickblox-ios-sdk#1147]
I want to show the chat dialogs from specific date  sending the below as extended request
 dictExtend = @{@"type":@"2",
                       @"updated_at" :"date",
                       @"sort_desc":@"last_message_date_sent",
                       @"data[class_name]" : @"ChatDialogType",
                       @"data[ChatCategory]": strChatType
                       };

I am getting error . Help me regarding this

**Comment by QB-vladyslav-vyshniak** [comment]
Hello, dear @suryaween 

Thank you for contacting QuickBlox support.

Have you tried the following method: https://quickblox.com/developers/SimpleSample-chat_users-ios#Retrieve_list_of_dialogs
If yes, please, provide me with the error that you get when you try to use the reported method.

Looking forward to your reply.
