### ISSUE TITLE
[!] Error installing QuickBlox

### ISSUE THREAD

**Issue by baybomax** [QuickBlox/quickblox-ios-sdk#1150]
Installing QuickBlox (2.17.1)

[!] Error installing QuickBlox
[!] /usr/bin/curl -f -L -o /var/folders/1g/v3bmdtxj5k1djdf_37j302ym0000gn/T/d20190618-3268-biva6k/file.zip https://sdk.quickblox.com/ios/iOS-QuickBlox-SDK-2.17.1.zip --create-dirs --netrc-optional --retry 2

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:01:14 --:--:--     0curl: (7) Failed to connect to sdk.quickblox.com port 443: Operation timed out

**Comment by QB-vladyslav-vyshniak** [comment]
The status of the ticket changed to "Closed" due to inactivity.
If the reported issue is still actual for you - please reopen the ticket.
