### ISSUE TITLE
Taking a call off of speaker on the lock screen doesn't turn the speaker off

### ISSUE THREAD

**Issue by dansinclair25** [QuickBlox/quickblox-ios-sdk#1155]
**New Issue Checklist**

 - [x] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [x] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    | 11.0 - 12.3                                    |                                          
Quickblox iOS SDK version      | 2.17.1                                  |
QuickbloxWebRTC SDK version    | 2.7.3                                  |                               
Xcode Version                  | Xcode 10.2.1                              |
Repro with our demo sample     | Reproducible with video chat swift sample project   |

**Did this work before?**
No

**Expected behavior**
Given a user is on an audio call
And the device is locked
When the user presses the speaker button on the CallKit screen to disable the speaker
Then the audio should be routed to the receiver

**Actual behavior**
When the speaker button is pressed to disable the speaker, the audio is not returned to the receiver but is forced back on through the speaker.

**Logs**

*Please use the following template for logs:*

To enable full logs use the following code:
```objc
[QBSettings setLogLevel:QBLogLevelDebug];
[QBSettings enableXMPPLogging];
```

*No logs available*
However, if you log the type of `QBRTCAudioDevice` in the `func audioSession(_ audioSession: QBRTCAudioSession, didChangeCurrentAudioDevice updatedAudioDevice: QBRTCAudioDevice)` delegate method then you can see that even though it should return "receiver", it actually returns "speaker".

**Steps to reproduce the behavior**
- Run the [sample-videochat-webrtc-swift](https://github.com/QuickBlox/quickblox-ios-sdk/tree/master/sample-videochat-webrtc-swift) demo app on 2 devices. 
- Start an audio call between them.
- Accept the call
- Lock one device. 
- On the device that's locked, press the speaker button to turn on the speaker.
- On the device that's locked, press the speaker button again to turn it off the speaker and return it to the receiver.
- Speaker button will unhighlight temporarily but then turn back on again.

**Any others comments**
N/A

**Comment by QB-vladyslav-vyshniak** [comment]
Hello, dear @dansinclair25 

Thank you for contacting QuickBlox support.

The reported issue has been successfully reproduced by QuickBlox QA team and will be resolved by the developers in one of the upcoming Shared instance releases. 

Thank you for your help in improving of QuickBlox platform.

**Comment by vishalrana-spaceo** [comment]
I am also facing same issue. please let us know when it will be fixed
