### ISSUE TITLE
Update user profile pic with url iOS API

### ISSUE THREAD

**Issue by kalyanpkumar** [QuickBlox/quickblox-ios-sdk#116]
Hi..

We are planning to user QuickBlox API in our iOS app for chatting. So, in our app we have user profile pics uploaded to our server say s3 bucket. So, here we have user profile pic url. So, can we use the same url to upload user profile pic with the QuickBlox. 

I have seen your method of uploading the image to content and then assign the blobid to user and then download the image with that user.blobid and show. But I am looking for something as mentioned above to upload user image url.

As i see, for the group chat dialog you have given the option "Can be an url to any file in Internet", though i didn't check it, the docs say that.. so in the same way do we have any way to upload user image with url with out downloading it...

Please let me know the possibilities.

Thanks
Kalyan

**Comment by soulfly** [comment]
You can use user's website url for this for example
or even better customData field

**Comment by kalyanpkumar** [comment]
Hi Igor..

Thanks for the information….

Can you please tell me how can we use custom parameters to “QBUpdateUserParameters”

And website you mean user.website = “picture link”??

Thanks
Kalyan





Regards
Kalyankumar Parise
Team Lead - iOS Applications Development
M: +91 7396476329 | T: 040 42000654
e-mail : kalyan.p@bravemount.com
skype  : kalyan.parise

**Comment by kalyanpkumar** [comment]
Hi Igor,

We are able to figure out using the custom data for user profile pic… thanks for the suggestions.

We had checked the chat samples and users samples and push notifications API’s and As we are in the final stages of confirming to use your SDK in our app, our client might be buying some plans. But we are stuck with few points that we are still thinking about the improvements and requests.

I have few requests to ask you that are listed below…

PUSH NOTIFICATIONS :

1. We need to send push notifications for the messages. But we see there are only two possibilities to send the notifications like either from App or from admin panel.
2. But as we need to invoke the API call for every message from the code itself.

So, what i request you is that, if there is any possibility to send from your server itself, when we invoke the message send API with the message and as well the dialog id or the recipient id. As you will be having all the details of the users in the dialog and the device ids in your server and so that you can send the notifications from your end itself instead of invoking the notifications from the app.

So, with this we can avoid the number of API calls from the app for every message and even it might help to improve the app performance of the app too.

NOTIFICATIONS TO OFFLINE USERS:

And also, can you let me know how does the notifications to only offline users feature would work..

1. Like does it send the notifications to offline users automatically or do we also need to write some code in the app for this feature too.
2. Or if we enable the notifications to offline users in admin module in chat section in alerts tab, then does it automatically send notifications. So, for this if the QB does anything with in the app or do we need to write some code for this too…

VIDEO ATTACHMENT IN CHAT :

And may i know if we can send the videos in the chat messages in the same way as images, though we are checking the same with the available samples. And does QB provides any video conversion API as the videos recorded in iPhone (it gives .mov format) might not play in Android devices (it supports only mp4 formats) sometimes. So, we are thinking if QB provides any conversion API for the videos to mp4 format.

I request you to provide the details on the above points.. Please your information would be very helpful for us to proceed further with the confirmations of the client….

Thanks
Kalyan




Regards
Kalyankumar Parise
Team Lead - iOS Applications Development
M: +91 7396476329 | T: 040 42000654
e-mail : kalyan.p@bravemount.com <mailto:kalyan.p@bravemount.com>
skype  : kalyan.parise

**Comment by kalyanpkumar** [comment]
Hi Igor,

We are able to figure out using the custom data for user profile pic… thanks for the suggestions.

We had checked the chat samples and users samples and push notifications API’s and As we are in the final stages of confirming to use your SDK in our app, our client might be buying some plans. But we are stuck with few points that we are still thinking about the improvements and requests.

I have few requests to ask you that are listed below…

PUSH NOTIFICATIONS :

1. We need to send push notifications for the messages. But we see there are only two possibilities to send the notifications like either from App or from admin panel.
2. But as we need to invoke the API call for every message from the code itself.

So, what i request you is that, if there is any possibility to send from your server itself, when we invoke the message send API with the message and as well the dialog id or the recipient id. As you will be having all the details of the users in the dialog and the device ids in your server and so that you can send the notifications from your end itself instead of invoking the notifications from the app.

So, with this we can avoid the number of API calls from the app for every message and even it might help to improve the app performance of the app too.

NOTIFICATIONS TO OFFLINE USERS:

And also, can you let me know how does the notifications to only offline users feature would work..

1. Like does it send the notifications to offline users automatically or do we also need to write some code in the app for this feature too.
2. Or if we enable the notifications to offline users in admin module in chat section in alerts tab, then does it automatically send notifications. So, for this if the QB does anything with in the app or do we need to write some code for this too…

VIDEO ATTACHMENT IN CHAT :

And may i know if we can send the videos in the chat messages in the same way as images, though we are checking the same with the available samples. And does QB provides any video conversion API as the videos recorded in iPhone (it gives .mov format) might not play in Android devices (it supports only mp4 formats) sometimes. So, we are thinking if QB provides any conversion API for the videos to mp4 format.

I request you to provide the details on the above points.. Please your information would be very helpful for us to proceed further with the confirmations of the client….

Thanks
Kalyan




Regards
Kalyankumar Parise
Team Lead - iOS Applications Development
M: +91 7396476329 | T: 040 42000654
e-mail : kalyan.p@bravemount.com
skype  : kalyan.parise

**Comment by soulfly** [comment]
Please create a separate issue/issues

**Comment by UpasnaGandhi** [comment]
Hello I have an same issue with profile picture. Please help me if you know that how we upload and get profile picture?
