### ISSUE TITLE
QBRTCRecorder becomes nil after first recording is complete

### ISSUE THREAD

**Issue by aminiz** [QuickBlox/quickblox-ios-sdk#1165]
Is there a restriction of 1 recording per session? Or can we do multiple recordings in a single session? 

Currently, we are seeing that after the first recording is complete, the recorder becomes nil.

**Comment by QB-vladyslav-vyshniak** [comment]
Hello @aminiz 

Thank you for contacting QuickBlox support.

The developers have successfully reproduced the reported bug and currently are fixing it. 
The fix will be contained in the upcoming SDK. 

P.S. You are QuickBlox Enterprise member, so you can use the support portal (https://assist.quickblox.com/) to report us any issue, question, etc. 
Let me know if you need any help with a registration process there.

**Comment by QB-vladyslav-vyshniak** [comment]
The status of the ticket changed to "Closed".

The solution has been provided in QB support portal.
