### ISSUE TITLE
QuickBlox Integrated App-First call after installing Android App is not getting,once restart the app then call functionalities are working fine.

### ISSUE THREAD

**Issue by vineeshLee** [QuickBlox/quickblox-ios-sdk#1166]
**-First call after installing Android App is not getting**

QuickBlox Integrated App-First call after installing Android App is not getting,once restart the app then call functionalities are working fine.

QuickBlox Sdk version 3.8.1

Please help to find a better solution.

**Comment by QB-vladyslav-vyshniak** [comment]
Hello @vineeshLee 

Thank you for contacting QuickBlox support.

Please, create a new ticket in Android section. Here we consider the tickets which are related to IOS platform. 

Proceed with the update to the latest stable Android SDK version, link: https://github.com/QuickBlox/quickblox-android-sdk
