### ISSUE TITLE
I didn't create group chat dialog following documentation. There is a miss match between documentation and sample code. why? 

### ISSUE THREAD

**Issue by Samrat555** [QuickBlox/quickblox-ios-sdk#1168]
I didn't create group chat dialog following documentation. There is a miss match between documentation and sample code. why?

**Comment by QB-vladyslav-vyshniak** [comment]
Hello @Samrat555 

Thank you for contacting QuickBlox support.

Could you clarify what exactly is going wrong on your side while the creation of group dialog? 
Provide me with the detailed logs, steps to reproduce the reported issue and link to our documentation where you have found the miss match.

Looking forward to your reply.

**Comment by QB-vladyslav-vyshniak** [comment]
Hello @Samrat555 

The status of the ticket changed to "Closed", because you haven't provided me with an answer.
You can reopen this ticket, if you would like to continue the discussion of the reported issue.
