### ISSUE TITLE
Hello everyone..I am using quickblox for chatting..My requirement is that i want to update all the status which is read, delivered and sent to one label..The  send and delivered are updating in one label but the read is showing in other label..I am also attaching the screenshot for reference..Can you help me in this?

### ISSUE THREAD

**Issue by HarleenKa** [QuickBlox/quickblox-ios-sdk#1169]
[**New](url
![Simulator Screen Shot - iPhone Xs Max - 2019-09-05 at 16 47 40](https://user-images.githubusercontent.com/48941073/64337381-e445d200-cffc-11e9-82a6-1ba54ee1ad56.png)

**Comment by QB-vladyslav-vyshniak** [comment]
Hello @HarleenKa 

Thank you for contacting QuickBlox support.

Please, be notified that such feature is absent and couldn't be implemented due to the contradiction with QB logic.
So, you can proceed with the implementation and configuration on your side.

**Comment by QB-vladyslav-vyshniak** [comment]
Hello @HarleenKa 

The status of the ticket changed to "Closed".

Please, create a new ticket if you have any additional questions.
