### ISSUE TITLE
Issue still persists with content file upload for new AWS S3 SDK

### ISSUE THREAD

**Issue by waveTeamApp** [QuickBlox/quickblox-ios-sdk#117]
Unfortunately, after updating to v2.3.0.3, the issue with uploading content using the new AWS S3 SDK is still there. Whenever you try to upload data using AWS S3 SDK, AWSTask block returns the operation instantly as completed with no errors, while the data is never uploaded!

Here's the change log from v2.3.0.2 which is believed to have solved this issue a couple of days ago:
v2.3.0.2 — Jul 20, 2015 - Fixed an issue with Content file upload for new AWS S3 SDK

**Comment by soulfly** [comment]
Please provide more details and logs of your query
