### ISSUE TITLE
App  crash

### ISSUE THREAD

**Issue by Bharath2r** [QuickBlox/quickblox-ios-sdk#1174]
**New Issue Checklist**

 - [x] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [ ] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    | e.g. 8.0                                    |                                          
Quickblox iOS SDK version      | e.g. 2.7.6                                  |
QuickbloxWebRTC SDK version    | e.g. 2.2.1                                  |                               
Xcode Version                  | e.g. Xcode 8.1                              |
Repro with our demo sample     | e.g. does it happen with our demo sample?   |

**Did this work before?**

**Expected behavior**

**Actual behavior**

**Logs**
error: Execution was interrupted, reason: EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0).
The process has been returned to the state before expression evaluation.
![Screenshot 2019-09-18 at 2 23 30 PM](https://user-images.githubusercontent.com/23276219/65133423-371d8180-da20-11e9-8d25-5a74ba3dcf45.png)
*Please use the following template for logs:*

To enable full logs use the following code:
```objc
[QBSettings setLogLevel:QBLogLevelDebug];
[QBSettings enableXMPPLogging];
```

<details>
<summary>Title for logs </summary>

```logos

// Your logs here

```

</details>

**Steps to reproduce the behavior**

**Any others comments**

**Comment by vadimkhmyrovqb** [comment]
@Bharath2r please fill the form above, indicating:

iOS Version
Quickblox iOS SDK version
QuickbloxWebRTC SDK version
Xcode Version
Repro with our demo sample - Y/N

**Comment by Bharath2r** [comment]
iOS version 12.3
Quickblox iOS SDK version  2.17.1
Xcode version 10.1
Repro with our demo sample - N

**Comment by vadimkhmyrovqb** [comment]
Please write Steps to reproduce the behavior.

**Comment by Bharath2r** [comment]
Download below link
Go to chatviewcontroller(App is getting crashed at ChatDataSource)
https://github.com/Bharath2r/QuickBloxChatSample

**Comment by vadimkhmyrovqb** [comment]
@Bharath2r we do not offer custom code review.
You mentioned that it works with our sample - please try to compare the problematic code block against your sample.

**Comment by Bharath2r** [comment]
Both files were same.I copied the Sample project code file(problematic file) into our sample Project but no result.

**Comment by vadimkhmyrovqb** [comment]
The main purpose of Simple Samples is to allow quickly test main functionality and to see implementation example. Sample code is not meant to be copied to other projects. To implement main functionality of Quickblox, please use SDK methods documented here: https://quickblox.com/developers/SimpleSample-chat_users-ios#Guide:_Getting_Started_with_Chat_API

**Comment by QB-vladyslav-vyshniak** [comment]
Hello @Bharath2r 

Any luck with the testing on QB clear samples? 

Looking forward to your reply.

**Comment by QB-vladyslav-vyshniak** [comment]
Hello @Bharath2r 

The status of the ticket changed to "Closed", because you haven't provided me with an answer.
You can reopen this ticket, if you would like to continue the discussion of the reported issue.
