### ISSUE TITLE
App crash 

### ISSUE THREAD

**Issue by Bharath2r** [QuickBlox/quickblox-ios-sdk#1175]
**New Issue Checklist**
Error:    Unable to capture view hierarchy.
Details:  Log Title: Data source expression execution failure.
Log Details: error evaluating expression “(id)[[(Class)objc_getClass("DBGTargetHub") sharedHub] performRequestWithRequestInBase64:@"…"]”: error: Execution was interrupted.
The process has been returned to the state before expression evaluation.

Log Method: -[DBGDataSourceConnectionLibViewDebugger _executeLLDBExpression:forRequest:onPotentialThread:iteration:]_block_invoke
Method:   -[DBGViewDebugger _initiateInitialRequestWithDataSourceVersion:]_block_invoke
Environment: Xcode 10.1 (10B61) debugging iPhone X iOS Simulator 12.1 (16B91).
Please file a bug at https://bugreport.apple.com with this warning message and any useful information you can provide.
 - [ ] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [ ] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    | e.g. 8.0                                    |                                          
Quickblox iOS SDK version      | e.g. 2.7.6                                  |
QuickbloxWebRTC SDK version    | e.g. 2.2.1                                  |                               
Xcode Version                  | e.g. Xcode 8.1                              |
Repro with our demo sample     | e.g. does it happen with our demo sample?   |

**Did this work before?**

**Expected behavior**

**Actual behavior**

**Logs**

*Please use the following template for logs:*

To enable full logs use the following code:
```objc
[QBSettings setLogLevel:QBLogLevelDebug];
[QBSettings enableXMPPLogging];
```

<details>
<summary>Title for logs </summary>

```logos

// Your logs here

```

</details>

**Steps to reproduce the behavior**

**Any others comments**

**Comment by QB-vladyslav-vyshniak** [comment]
Hello @Bharath2r 

The status of the ticket changed to "Closed" due to duplicate with https://github.com/QuickBlox/quickblox-ios-sdk/issues/1175

Please, don't create duplicate tickets, their status will be changed to "Closed".
