### ISSUE TITLE
Facing [QBResponse], status: 422 Issue

### ISSUE THREAD

**Issue by RahulChona11091991** [QuickBlox/quickblox-ios-sdk#1179]
**New Issue Checklist**

 - [ ] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [ ] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    | e.g. 8.0                                    |                                          
Quickblox iOS SDK version      | e.g. 2.7.6                                  |
QuickbloxWebRTC SDK version    | e.g. 2.2.1                                  |                               
Xcode Version                  | e.g. Xcode 8.1                              |
Repro with our demo sample     | e.g. does it happen with our demo sample?   |

**Did this work before?**

**Expected behavior**

**Actual behavior**

**Logs**

*Please use the following template for logs:*

To enable full logs use the following code:
```objc
[QBSettings setLogLevel:QBLogLevelDebug];
[QBSettings enableXMPPLogging];
```

<details>
<summary>Title for logs </summary>

```logos

// Your logs here

```

</details>

**Steps to reproduce the behavior**

**Any others comments**

**Comment by QB-vladyslav-vyshniak** [comment]
Hello @RahulChona11091991 

Thank you for contacting QuickBlox support.

Could you provide me with a detailed description of the faced issue? 
Please, be notified that the error 422 it's the customer's side issue, so first of all, double-check the correctness of your request/action.

**Comment by QB-vladyslav-vyshniak** [comment]
Hello @RahulChona11091991 

First of all - proceed with the update of IOS SDK to the latest stable version - 2.17.4 using xCode 10.
Please, don't use xCode 11 to avoid any issues, etc. 

Looking forward to your reply.

**Comment by oskarko** [comment]
in iOS12 works fine login. in iOS13, error 422 :(

**Comment by QB-vladyslav-vyshniak** [comment]
@oskarko 

I have answered you in the ticket #1183

**Comment by QB-vladyslav-vyshniak** [comment]
@RahulChona11091991 

The status of the ticket changed to "Closed", because you haven't provided me with an answer.
You can reopen this ticket, if you would like to continue the discussion of the reported issue.

**Comment by pavanbalu** [comment]
how to access response date value from iOS SDK
