### ISSUE TITLE
Push Notifications from QB API when sending messages

### ISSUE THREAD

**Issue by kalyanpkumar** [QuickBlox/quickblox-ios-sdk#118]
Hi..

We had checked the chat samples and users samples and push notifications API’s and As we are in the final stages of confirming to use your SDK in our app, our client might be buying some plans. But we are stuck with few points that we are still thinking about the improvements and requests.

1. We need to send push notifications for the messages. But we see there are only two possibilities to send the notifications like either from App or from admin panel.
2. But as we need to invoke the API call for every message from the code itself.

Right now, i see i can send push notification to users who ever i want by passing user ids after sending message, but i want this to be done automatically by the syste. when i send a message in a group the system know who is offline or online, so it can send to offline users only as server has everything it require to judge who is offline and send notifications...

So, what i request you is that, if there is any possibility to send from your server itself, when we invoke the message send API with the message and as well the dialog id or the recipient id. As you will be having all the details of the users in the dialog and the device ids in your server and so that you can send the notifications from your end itself instead of invoking the notifications from the app.

So, with this we can avoid the number of API calls from the app for every message and even it might help to improve the app performance of the app too.

Please let us know the details of possibilities.

Thanks
Kalyan

**Comment by AndreyMoskvin** [comment]
We have automatic push notifications feature for chat (server will send push notification when message is received by server - so you will not need to send it from client). It could be enabled in Admin Panel.
