### ISSUE TITLE
Login Error in iOS 13

### ISSUE THREAD

**Issue by saifan95** [QuickBlox/quickblox-ios-sdk#1180]
**New Issue Checklist**

 - [ ] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [ ] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    |  13.0                                    |                                          
Quickblox iOS SDK version      | 2.17.1                                  |                               
Xcode Version                  |  Xcode 11.0                              |
Repro with our demo sample     | https://github.com/QuickBlox/quickblox-ios-sdk/tree/master/sample-chat-swift  |

**Did this work before?**
Working fine in iOS 12

**Expected behavior**
Login / Sign up should be successful with login API 

**Actual behavior**
Getting error "Unexpected signature"

**Logs**

*Please use the following template for logs:*

<details>
<summary>Response of API </summary>
```
POST URL:https://api.quickblox.com/session.json
headers: {
    "Accept-Language" = "en;q=1";
    "Content-Type" = "application/x-www-form-urlencoded";
    "QB-OS" = "iOS 13.0";
    "QB-SDK" = "iOS 2.17.1";
    "QuickBlox-REST-API-Version" = "0.1.1";
    "User-Agent" = "QBNotification/1.0 (iPhone; iOS 13.0; Scale/3.00)";
}
parameters: {
    "application_id" = 78757;
    "auth_key" = "NV-TGg8hQVmG89J";
    nonce = 835;
    signature = "{length=20,bytes=0xa717a42361cdf9c3e67594d1dc418509a1b57a52}";
    timestamp = 1570075476;
    "user[login]" = saifan;
    "user[password]" = quickblox;
}
2019-10-03 09:34:37.278925+0530 QBNotification[1440:12058] [QBCore]: Response[3]
headers: {
    "Access-Control-Allow-Origin" = "*";
    "Cache-Control" = "no-cache";
    "Content-Type" = "application/json; charset=utf-8";
    Date = "Thu, 03 Oct 2019 04:04:37 GMT";
    Duration = "0.322956";
    Server = "nginx/1.14.2";
    "Set-Cookie" = "_mkra_ctxt=3084b59581d65e670ca0bf1639b77f39--422; path=/; max-age=5; HttpOnly; secure";
    Status = "422 Unprocessable Entity";
    "Strict-Transport-Security" = "max-age=31536000";
    "quickblox-rest-api-version" = "0.1.1";
    "x-content-type-options" = nosniff;
    "x-frame-options" = SAMEORIGIN;
    "x-request-id" = "d0ccaee6-8456-4245-aac6-c47e386a988e";
    "x-runtime" = "0.034357";
    "x-xss-protection" = "1; mode=block";
}
error: Request failed: client error (422)
reasons: {
    errors =     {
        base =         (
            "Unexpected signature"
        );
    };
}
```

</details>

**Steps to reproduce the behavior**
```
    let login = "saifan"
    let password = "quickblox"
    QBRequest.logIn(withUserLogin: login,
                    password: password,
                    successBlock: { [weak self] response, user in
                        guard let self = self else {
                            return
                        }

                        Print("Success")

        }, errorBlock: { [weak self] response in
           Print("Error")  
    })
```

**Others comments**
i have checked all the keys and credentials its working fine in iOS 12 only issue with iOS 13 devices

**Comment by koust** [comment]
i get same issue. 

> Error Domain=com.quickblox.chat Code=-1011 "(null)" UserInfo={NSLocalizedRecoverySuggestion=User must have a valid user ID}

**Comment by QB-vladyslav-vyshniak** [comment]
Hello @saifan95 

Thank you for contacting QuickBlox support.

I have already provided you with an answer in the ticket #145300 (QB support portal).
So, please, proceed with the actions that I have mentioned there.

**Comment by QB-vladyslav-vyshniak** [comment]
Hello @koust 

First of all you should proceed with the following instructions: 
Please use Xcode 10 or lower to create the release build for IOS SDKs up to version 2.17.4 (which supports IOS 13).
The main reason is that Xcode 11 still in the Beta version and the issues can occur during it using.

Please notice that the latest version of IOS SDK is 2.17.4.
You can download it here https://github.com/QuickBlox/quickblox-ios-sdk/releases
QuickBlox SDK 2.17.4 Cocoapods: https://cocoapods.org/pods/QuickBlox

Also, proceed with the update of Quickblox-WebRTC 2.7.4 framework: https://github.com/QuickBlox/quickblox-ios-sdk/tree/master/Framework (need unarchive)
Quickblox-WebRTC 2.7.4 Cocoapods: https://cocoapods.org/pods/Quickblox-WebRTC

Let me know about a result after the update to the latest IOS SDK.
