### ISSUE TITLE
Update SDWebImage Dependency. 

### ISSUE THREAD

**Issue by haarj** [QuickBlox/quickblox-ios-sdk#1184]
Currently the QuickBlox SDK supports only SDWebImage 4.4.8. Is is possible to update to the latest, which is 5.10.2?

Thanks!

**Comment by QB-vladyslav-vyshniak** [comment]
Hello @haarj 

Thank you for contacting QuickBlox support.

Could you provide me with the detailed description of the reported issue.

Looking forward to your reply.

**Comment by haarj** [comment]
The SDWebImage Dependency in the QuickBlox iOS framework is out of date. Currently it supports SDWebImage 4.0.0. The Latest is v5.9.5.

Thank you!

**Comment by haarj** [comment]
Hi @QB-vladyslav-vyshniak any news here? Thanks!

**Comment by haarj** [comment]
Hi @QB-vladyslav-vyshniak any update here. Just wondering if and when the latest SDWebImage dependency will be supported in the SDK and the QMChatViewController. Thanks!

https://github.com/SDWebImage/SDWebImage

**Comment by QB-nikolay-zolotarov** [comment]
@haarj 
You can use our [official SDKs](https://docs.quickblox.com/docs) and [samples](https://docs.quickblox.com/docs/code-samples).

You may also be interested in our [UI Kit](https://quickblox.com/ui-kit/).
