### ISSUE TITLE
push notifications with each new version on AppStore

### ISSUE THREAD

**Issue by oskarko** [QuickBlox/quickblox-ios-sdk#1186]
Hi!

iOS push notifications work fine but every time I upload a new version to AppStore I have to remove all subscriptions in admin panel for making them work again. Why is not working with every new live app? on debug works always fine.... so it´s strange.

iOS 12 and 13.

**Comment by QB-vladyslav-vyshniak** [comment]
Hello @oskarko 

Is the issue still relevant for you?

**Comment by QB-vladyslav-vyshniak** [comment]
The status of the ticket changed to "Closed" due to the absence of a reply.
