### ISSUE TITLE
IOS 13 VOIP Background Crash  Issue

### ISSUE THREAD

**Issue by sushantgiri** [QuickBlox/quickblox-ios-sdk#1188]
The error logged while running the application is:

Apps receving VoIP pushes must post an incoming call (via CallKit or IncomingCallNotifications) in the same run loop as   pushRegistry:didReceiveIncomingPushWithPayload:forType:[withCompletionHandler:] without delay.

Please update the sample application code for iOS 13 and onwards.

**Comment by SwiftAmit** [comment]
anybody got any Solution?

**Comment by QB-vladyslav-vyshniak** [comment]
Hello @sushantgiri @SwiftAmit 

Please, be notified, that VOIP functionality has been deprecated by Apple in IOS 13, this is why it doesn't work on your side.
Check the following article about what you should do in this case: https://developer.apple.com/videos/play/wwdc2019/707/

Have a good day!

**Comment by QB-vladyslav-vyshniak** [comment]
@SwiftAmit 

Has the issue solved or still actual for you?

**Comment by QB-vladyslav-vyshniak** [comment]
The status of the ticket changed to "Closed" due to the absence of a reply.
