### ISSUE TITLE
Automatic Notifications to offline users

### ISSUE THREAD

**Issue by kalyanpkumar** [QuickBlox/quickblox-ios-sdk#119]
Hi..

We had checked the chat samples and users samples and push notifications API’s and As we are in the final stages of confirming to use your SDK in our app, our client might be buying some plans. But we are stuck with few points that we are still thinking about the improvements and requests.

can you Please let me know how does the notifications to only offline users feature would work..
1. Like does it send the notifications to offline users automatically or do we also need to write some code in the app for this feature too.
2. Or if we enable the notifications to offline users in admin module in chat section in alerts tab, then does it automatically send notifications. So, for this if the QB does anything with in the app or do we need to write some code for this too…

To be clear

sending push notification to only offline users -- is this feature possible??
Right now, i see i can send push notification to users who ever i want by passing user ids after sending message, but i want this to be done automatically by the system when i send a message in a group
coz the system know who is offline or online, so it can send to offline users only..server has everything it require to judge who is offline and send notifications...

So, please let us know the details..

Thanks
Kalyan

**Comment by tungdx** [comment]
Hello, any answers for this? thanks

**Comment by VitaliyGuru** [comment]
@tungdx , @kalyanpkumar, Hello. 

Quickblox [supports offline notifications](https://quickblox.com/developers/Chat/Push_notifications). 

These Push notification alerts are typically used in:
-1:1 Chat when user is sending IM message/file attachment to other user but the other user went offline
-Group chat / any other social interaction where there has been some activity related to what current user is tracking (own chat message/post, topic of interest etc)

The offline user ('offline' meaning the user has either quit the app or has lost the internet connection) is in such case being sent a push notification alert.

This is a really great way to inform users about activity happening in their absence, improve reaction time for offline users and increase user retention time users spend in your app.

To enable offline notifications you should:
1. Configure environment for Push notifications.(APNS Certificate) [How to](https://quickblox.com/developers/How_to_create_APNS_certificates)
1. Enable chat alerts in the admin panel. [How to](https://quickblox.com/developers/Chat#Alerts).
2. Subscribe for push notifications in your application. [How to](https://quickblox.com/developers/Chat/Push_notifications)

**Comment by Raikerian** [comment]
Please create separate issue if you have any questions.
