### ISSUE TITLE
Dark Mode Support

### ISSUE THREAD

**Issue by haarj** [QuickBlox/quickblox-ios-sdk#1190]
Make QMChatAttachmentIncomingCell & QMChatAttachmentOutgoingCell's progressLabels support dark mode.

**Comment by QB-vladyslav-vyshniak** [comment]
Hello @haarj 

Currently, applying of dark mode for Q-municate is unavailable, such option will be added in the new Q-municate 2.0 

Unfortunately, there is no ETA of release for now.

**Comment by QB-vladyslav-vyshniak** [comment]
The status of the ticket changed to "Closed", the answer has been provided.
