### ISSUE TITLE
Stop Working VOIP Push notification - show Error in Certificate.

### ISSUE THREAD

**Issue by SwiftAmit** [QuickBlox/quickblox-ios-sdk#1191]
In admin panel push certificate show error log in every 2-3 days, when this certificate shows error then VOIP push notification stops working again I have to upload the same certificate **[WITHOUT ANY CHANGES]** and the VOIP push notification start working.

This scenioro is too frequently, i am not able to find the reason behind that why certificate  shows error in admin panel automatically.

Two Certificates are listed in admin panel.
 1- VOIP(Sandbox & Production) SSL certificate
 2 - Development(SandboX) SSL certificate

error is shown always on **Development(SandboX) SSL certificate.**

**Log showing in Error File. -** 

Certificate errors:
**2020-01-25** 12:15:04 UTC: Connection reset by APNS: SSL connection error. Certificate is invalid or outdated. Please upload other certificate.
2020-01-25 12:15:05 UTC: Connection reset by APNS: SSL connection error. Certificate is invalid or outdated. Please upload other certificate.

APNS feedback service (development), last 14 days:

Certificate errors:
**2020-01-29** 14:45:03 UTC: Connection reset by APNS: SSL connection error. Certificate is invalid or outdated. Please upload other certificate.
2020-01-29 14:45:04 UTC: Connection reset by APNS: SSL connection error. Certificate is invalid or outdated. Please upload other certificate.

APNS feedback service (development), last 14 days:

**Comment by QB-vladyslav-vyshniak** [comment]
Hello @SwiftAmit 

Have you tried to generate a new APNS certificate and check how it works with a new one?

**Comment by QB-vladyslav-vyshniak** [comment]
The status of the ticket changed to "Closed" due to the absence of a reply.

**Comment by Rushang007** [comment]
@QB-vladyslav-vyshniak  not working for me i had generate a new APNS certificate and check but not working its Working in iOS 12 but not working in iOS 13 can you please help me?
![WhatsApp Image 2020-04-08 at 7 42 53 PM](https://user-images.githubusercontent.com/16713953/79043650-03a17f00-7c1e-11ea-860b-1e98cb239801.jpeg)
 
Latest version of Quickblox and WebRTC SDK 
Swift 
#1199

**Comment by parthsit** [comment]
@QB-vladyslav-vyshniak Yes I am also facing same issue in iOS 13 can you please help me ?
