### ISSUE TITLE
is typing status is not working properly.

### ISSUE THREAD

**Issue by vishalrana-spaceo** [QuickBlox/quickblox-ios-sdk#1198]
**New Issue Checklist**

 - [yes ] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [ yes] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    |  13.0                                    |                                          
Quickblox iOS SDK version      |  2.17.4                                  |
QuickbloxWebRTC SDK version    |  2.7.4                                  |                               
Xcode Version                  |  Xcode 11.3.1                             |
Repro with our demo sample   

**Did this work before?**
yes

**Expected behavior**
should able to send isTyping chat notifications status and the opposite side should able to receive status under added observers.

**Actual behavior**
observer never called for typing status

**Logs**

*Please use the following template for logs:*

To enable full logs use the following code:
```objc
[QBSettings setLogLevel:QBLogLevelDebug];
[QBSettings enableXMPPLogging];

**Steps to reproduce the behavior**


**Any others comments**

**Comment by QB-maksym-pidhorbunskyi** [comment]
Hello @vishalrana-spaceo,

Thank you for contacting QuickBlox support.

Please make sure that you are following QuickBlox iOS documentation regarding Is Typing Status functionality: https://docs.quickblox.com/docs/ios-chat-advanced#is-typing-status
