### ISSUE TITLE
<Quickblox/Quickblox.h> not found

### ISSUE THREAD

**Issue by glaretechnology** [QuickBlox/quickblox-ios-sdk#12]
I have download sample-chat demo from github. When I tried compile it shows that <Quickblox/Quickblox.h> not found in .pch file 

How to resolve it ???

![12 copy](https://f.cloud.github.com/assets/5313554/1773166/1f954b04-67e1-11e3-9296-68be1b97167f.png)

**Comment by Fisky-Alan** [comment]
**unable to install QMCVDevelopment .** 

- Pre-downloading: `QMCVDevelopment` from `git@github.com:QuickBlox/QMChatViewController-ios.git`, branch `development`
Pre-downloading: `QMServicesDevelopment` from `git@github.com:QuickBlox/q-municate-services-ios.git`, branch `development`
[!] Unable to satisfy the following requirements:

- `QMChatViewController/QMChatLocationSnapshotter` required by `QMCVDevelopment/Categories (0.4.0.1)`

None of your spec sources contain a spec satisfying the dependency: `QMChatViewController/QMChatLocationSnapshotter`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
