### ISSUE TITLE
VIDEO ATTACHMENT IN CHAT 

### ISSUE THREAD

**Issue by kalyanpkumar** [QuickBlox/quickblox-ios-sdk#120]
Hi..

We had checked the chat samples and users samples and push notifications API’s and As we are in the final stages of confirming to use your SDK in our app, our client might be buying some plans. But we are stuck with few points that we are still thinking about the improvements and requests.

May i know if we can send the videos in the chat messages in the same way as images, 

though we are checking the same with the available samples. And does QB provides any video conversion API as the videos recorded in iPhone (it gives .mov format) might not play in Android devices (it supports only mp4 formats) sometimes. So, is there any possiblity that QB have video conversion process in such a way that it is compatible on iOS and Android devices.

Thanks
Kalyan

**Comment by AndreyMoskvin** [comment]
You could use QBChatAttachment API to send videos but appropriate conversion should be implemented by yourself on the client.

**Comment by abhishek33u** [comment]
Hi can you give me any any sample  of video sharing

**Comment by PrincessGitu** [comment]
Hi can you please share me any sample of video attachment sharing

**Comment by VitaliyGuru** [comment]
@PrincessGitu, @abhishek33u  Please create a separate issue.
