### ISSUE TITLE
Calls not working in background in swift but working fine in objective C

### ISSUE THREAD

**Issue by Awais987** [QuickBlox/quickblox-ios-sdk#1206]
**New Issue Checklist**

 - [yes] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [yes] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    | e.g. 13.3.1                                    |                                          
Quickblox iOS SDK version      | e.g. 2.17.4                             |
QuickbloxWebRTC SDK version    | e.g. 2.7.4                                  |                               
Xcode Version                  | e.g. Xcode 11.3.1                             |
Repro with our demo sample     | e.g. does it happen with our demo sample?   |

**Did this work before?**

**Expected behavior**

**Actual behavior**

**Logs**

*Please use the following template for logs:*

To enable full logs use the following code:
```objc
[QBSettings setLogLevel:QBLogLevelDebug];
[QBSettings enableXMPPLogging];
```

<details>
<summary>Title for logs </summary>

```logos

// Your logs here

```

</details>

**Steps to reproduce the behavior**

**Any others comments**

**Comment by VladimirNybozhinsky** [comment]
Please check the latest update Swift-Video-Chat-WEBRTC
https://github.com/QuickBlox/quickblox-ios-sdk/commit/9b70536f44558d7ce004449731a9cfb4e539ea2b

**Comment by Awais987** [comment]
@VladimirNybozhinsky yes it is working fine now there is only 1 issue left when i picked call from terminate state or from lock screen the voice connection is lost and i can't hear other user voice but it is working fine in background or active state

**Comment by Muhammad7861** [comment]
> @VladimirNybozhinsky yes it is working fine now there is only 1 issue left when i picked call from terminate state or from lock screen the voice connection is lost and i can't hear other user voice but it is working fine in background or active state

yes i have same issue which is facing by @Awais987 please look into this we are on ending state we have need to buy startup or enterprise plan

**Comment by Muhammad7861** [comment]
@VladimirNybozhinsky  please update and check thoroughly swift webrtc project we are on stake with our client 4 months effort can be destroyed on this last feature of quickblox 
Please help into this.

**Comment by Navya-ios** [comment]
> @VladimirNybozhinsky yes it is working fine now there is only 1 issue left when i picked call from terminate state or from lock screen the voice connection is lost and i can't hear other user voice but it is working fine in background or active state

Can i know how you implemented background video call in swift ?

**Comment by RuchiMakadia** [comment]
same issue video calling not work in background in swift

**Comment by QB-nikolay-zolotarov** [comment]
@RuchiMakadia Hello,

Please check our new swift sample where the background call functionality is reworked and described in more detail:
[
https://github.com/QuickBlox/quickblox-ios-sdk/tree/master/sample-videochat-webrtc-swift](
https://github.com/QuickBlox/quickblox-ios-sdk/tree/master/sample-videochat-webrtc-swift)
