### ISSUE TITLE
Return MessageID on send

### ISSUE THREAD

**Issue by cloudtenlabs** [QuickBlox/quickblox-ios-sdk#1207]
Can you please return message Id on dialog.send function?
let privateDialog = ...
privateDialog.send(message) { (error) in
    
}

I need to implement the feature to delete the message the users just sent but I cant delete them because they do not have message Id

**Comment by maughray** [comment]
You should firstly create message via `QBRequest.createMessage` and then send it. This method will also attach an identifier for this message
