### ISSUE TITLE
I can't receive any background calls in TestFlight

### ISSUE THREAD

**Issue by GokmenAkar** [QuickBlox/quickblox-ios-sdk#1217]
Hello guys, 

I just can't take any calls in TestFlight, just working in the app. While I'm running the app via Xcode there is no problem. I can take calls in the foreground or background, and locked state. It works as expected. APNS certificates were uploaded successfully, there are subscribers also. But as I said there is a problem with TestFlight(I also tried Firebase distribution). I can take VoIP token in TestFlight, VoIP subscription also succeed. Is there any way to solve this problem? Or won't it even work in production? (**This is crucial**)

Thank you for this awesome SDK, I really like. Probably I'll suggest this for next and other projects too. 

![Screen Shot 2020-05-29 at 17 29 15](https://user-images.githubusercontent.com/16048623/83271326-6224bb80-a1d2-11ea-97ba-d6d8a34a03b5.png)

**New Issue Checklist**

 - [x] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [x] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    | 13.4.1 & 12.4.6                                    |                                          
Quickblox iOS SDK version      | 2.17.4 |
QuickbloxWebRTC SDK version    | 2.7.4                               |                               
Xcode Version                  | 11.4.1                         |
Repro with our demo sample     | no  |

**Expected behavior**
Receive calls while the app in the background in TestFlight

**Actual behavior**
The app is not getting any call in the background in TestFlight

**Logs**

*Please use the following template for logs:*

To enable full logs use the following code:
```objc
[QBSettings setLogLevel:QBLogLevelDebug];
[QBSettings enableXMPPLogging];
```

<details>
<summary>Title for logs </summary>

```logos

// Your logs here

```

</details>

**Steps to reproduce the behavior**
Just download the app in TestFlight or any distribution way but Xcode

**Any others comments**

**Comment by BCSingh** [comment]
Have you managed to get this work on Testflight app? I am facing the same issue now.. Incoming calls works fine in development mode. But the incoming call doesnt come in the testflight app, both in background and killed state.

**Comment by datpham96** [comment]
@BCSingh I have the same opinion with you. In development mode, the voip token spawns normally but on the testflight, it doesn't seem to spawn and function?

**Comment by BCSingh** [comment]
It had to rework on it to get it working.. Check my post [here](https://github.com/QuickBlox/quickblox-ios-sdk/issues/1223#issuecomment-663189506)..  See if any point helps
