### ISSUE TITLE
SDK 2.0.12: Dialog ID is being set to Last Message ID

### ISSUE THREAD

**Issue by waveTeamApp** [QuickBlox/quickblox-ios-sdk#122]
This started occurring after the last system update on (June 28th, 2015).

1- Retrieve a list of dialogs for a certain user:
    NSMutableDictionary *extendedRequest = [NSMutableDictionary new];
    extendedRequest[@"limit"] = @(100);
    [QBChat dialogsWithExtendedRequest:extendedRequest delegate:self];

2- NSLog(@"%@",dialog.id) of any of the resulted dialogs.
 You'll end up getting the last message id instead of the actual dialog id!

**Comment by soulfly** [comment]
returned to prev state, should work now
