### ISSUE TITLE
taking to much time to establish  audio/video call

### ISSUE THREAD

**Issue by kirti301290** [QuickBlox/quickblox-ios-sdk#1227]
iOS Version                    13.5                                 
QuickbloxWebRTC SDK version   2.7.5              
Xcode Version                 Xcode 11.5

Hello 
we facing problem  4-5 sec delay  establish  audio/video call and having good internet connection 
for example  UserA calling to UserB and  UsedB Accepted call but  it taking 4-5 sec to connection
Thanks

**Comment by KiranPatelSpaceo** [comment]
I have same issue

**Comment by maughray** [comment]
I also have the same issue.

**Comment by Navya-ios** [comment]
same issue

**Comment by QB-nikolay-zolotarov** [comment]
The issue is being closed as outdated.

If it is still relevant, feel free to open a new issue.
