### ISSUE TITLE
Network switch during call causing disconnect.

### ISSUE THREAD

**Issue by shoaibhassan1** [QuickBlox/quickblox-ios-sdk#1228]
I have successfully connected to video call, but if i switch network connection during call and if switching takes more than 3,4 seconds, then call gets disconnect, i want to increase this time and want to implement a reconnect feature like whatsapp and others apps do.
Thanks in advance.

**Comment by QB-nikolay-zolotarov** [comment]
@shoaibhassan1 The issue is being closed as outdated.

If it is still relevant, feel free to open a new issue.
