### ISSUE TITLE
How can i Stop Login Every Time?  

### ISSUE THREAD

**Issue by maulikshah09** [QuickBlox/quickblox-ios-sdk#1229]
How can i Stop Login Every Time? any Possible way to store login info in model  and directly connect ? 

1. When I login first time through api then i login into quickblox it's ok understand that but when i remove app from back ground then lunch again it's need to relogin in quickblox it's not understand. can i Store login info in local and reuse to connect client .

**Comment by shoaibHassanAttech** [comment]
I think you shoud Use login and Signup methods when you are logging in your app and save QB user ID innto device.
next time when you launch app and goes to home screen directly, you just need to connnect to chat then you can perform chat and Audio/Video calls.

**Comment by maulikshah09** [comment]
NO i think it's not working..

**Comment by shoaibHassanAttech** [comment]
Well i have implemented that logic mentioned above into my app
and it is working good for audio video calls and iOS and android as well.

**Comment by maulikshah09** [comment]
Can YOU Give me code or example

**Comment by shoaibHassanAttech** [comment]
Here is my code in app Delegate

```
func pushRegistry(_ registry: PKPushRegistry, didReceiveIncomingPushWith payload: PKPushPayload, for type: PKPushType, completion: @escaping () -> Void) {
        
        let payloadDict = payload.dictionaryPayload as? Dictionary<String, Any>
        self.isSavedLog = false
        let isDoctor = UserDefaults.standard.bool(forKey: Constants.k_IS_DOCTOR)
            if let callType = payloadDict!["callType"] as? String
            {
                    
                    let userString = // user id got from user defaults
                    patientID = userString
                    let qbManager = QBManager.getSharedManager()
                    qbManager.connectToChat()
                    qbManager.isVideoCall = callType == "Video"
                    let sessionId = payloadDict!["sessionID"] as? String
                    qbManager.channelIDString = sessionId!
                    self.callSession = sessionId!
                    self.callCenter.showIncomingCall(of: sessionId!)
                    qbManager.shouldShowCallKit = false
                    self.prepareBackgroundTask()
            }
            completion()
        NSLog("incoming voip notification: \(payload.dictionaryPayload)")
    }
```

and here is my helper function in singleton helper

 ```
func connectToChat() {
      
        if QBChat.instance.isConnected {
            return
        }
        let qbUserId = self.getUserIdOfQuickBlox()
        
               print("connecting to chat with QB id...\(qbUserId)")

        QBRTCClient.instance().remove(self)
        QBRTCClient.instance().add(self)
        
        QBChat.instance.connect(withUserID: qbUserId, password: quickBloxPassword, completion:
      { [weak self] error in
        if let error = error
    
        {
            print("Chat not connected")
            self?.isUserLoggedIn = false
            print(error.localizedDescription)
         }
        else
        {
            print("connected to chat")
            self?.isUserLoggedIn = true
            self?.checkForUserSubscriptionNotCreated()
        }
        })
    }
```

and then all delegate get called in that singleton methods for didRecieveNewSession or accept and reject.

**Comment by maulikshah09** [comment]
*I have done the same code IN my app. for quick blox login...IT's everytime login when you remove app from background.*



func connectToChat() {
     
       if QBChat.instance.isConnected {
           return
       }
       let qbUserId = self.getUserIdOfQuickBlox()
       
              print("connecting to chat with QB id...\(qbUserId)")

       QBRTCClient.instance().remove(self)
       QBRTCClient.instance().add(self)
       
       QBChat.instance.connect(withUserID: qbUserId, password: quickBloxPassword, completion:
     { [weak self] error in
       if let error = error
   
       {
           print("Chat not connected")
           self?.isUserLoggedIn = false
           print(error.localizedDescription)
        }
       else
       {
           print("connected to chat")
           self?.isUserLoggedIn = true
           self?.checkForUserSubscriptionNotCreated()
       }
       })
   }

**Comment by shoaibHassanAttech** [comment]
This is not app login, this is connecting to chat server only,
login and signup are different methods of SDK.
You must connect to server to perform any query to SDK.
Not only in Quickblox but any other SDK must initiate a connection with server to proceed.
