### ISSUE TITLE
Android to iOS calling is not working when my app is killed or in background, (but ios to ios calling is working).

### ISSUE THREAD

**Issue by silicus-kirankhalkar** [QuickBlox/quickblox-ios-sdk#1231]
**New Issue Checklist**

 - [ yes] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [ yes] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    | e.g. 13.0                                |                                          
Quickblox iOS SDK version      | e.g. 2.7.6                                  |
QuickbloxWebRTC SDK version    | e.g. 2.2.1                                  |                               
Xcode Version                  | e.g. Xcode 11.6                             |
Repro with our demo sample     | e.g. does it happen with our demo sample?   |

**Did this work before?**

**Expected behavior**
It should work android to iOS and iOS to iOS as well

**Actual behavior**
1.	
a. iOS to iOS calling a. when the app is in the foreground, calling functionality works smoothly. 
b. when app is in the background, calling functionality works smoothly.
 c. when the app was killed/screen locked, calling functionality works but not smoothly. 
2.
a.android to iOS calling a. when the app is in the foreground, calling functionality works smoothly.
 b. when the app is in the background, calling functionality not working. 
c. when the app was killed/screen locked, calling functionality not working. 

**Logs**

*Please use the following template for logs:*

To enable full logs use the following code:
```objc
[QBSettings setLogLevel:QBLogLevelDebug];
[QBSettings enableXMPPLogging];
```

<details>
<summary>Title for logs </summary>

```logos

// Your logs here

```

</details>

**Steps to reproduce the behavior**

**Any others comments**

**Comment by shoaibHassanAttech** [comment]
Check environment type to distribution on android side if you are creating build for adhoc in iOS.

**Comment by silicus-kirankhalkar** [comment]
@shoaibHassanAttech - Thanks for the response. We already did that setup. but not getting a call from the android device when the iOS app has in the background and Terminated state.

**Comment by shoaibHassanAttech** [comment]
Please check in subscription tab in Quickbolx whether VOIP token is registered or not
if it is registered and subscription is created then there is possibility whether android is sending APNS instead of VOIP notification or there is some certificate issue.

**Comment by silicus-kirankhalkar** [comment]
@shoaibHassanAttech - Yes, from iOS sider we successfully subscribed for VOIP along with the token. also crossed check on Quickblox portal.
From the android side, we sent below payload for VOIP calling.

Notification Type - QBMNotificationTypePush
Event type = QBMEventTypeOneShot;

{
  "message": “Jemi is calling you..",
  "ios_voip": "1",
  "VOIPCall": "1",
  "sessionID": "0e6448b5-464b-4f8d-bc47-c63d51c3efb0",
  "opponentsIDs": 72511889,
  "opponentsName": “Nevill”,
  "opponentsURL": "https://finedmet/e98bf1c4-a83a-4b81-97d4-037856b52529_1575537132690.jpg",
  "conferenceType": 2,
  "timestamp": "2020-08-20 14:28:30"
}

**Comment by shoaibHassanAttech** [comment]
Please check in queue what response you got?

**Comment by silicus-kirankhalkar** [comment]
@shoaibHassanAttech -It is showing push sent. Do you have any idea about what changes required from the Android side? while sending push. Do you have any sample payload for Android which will work for iOS and Android as well?

**Comment by shoaibHassanAttech** [comment]
We are using these lines of code from android side and call s working fine in all 3 platforms.

  ```
QBEvent qbEvent = new QBEvent();
    qbEvent.setNotificationType(QBNotificationType.PUSH);
    qbEvent.setEnvironment(QBEnvironment.PRODUCTION);
    //Generic push - will be delivered to all platforms (Android, iOS, WP, Blackberry..)
    JSONObject json = new JSONObject();
    try
    {
        json.put("message", outMessage);
        json.put("ios_voip", "1");
        if(callType)
        {
            json.put("callType", "Video");
        }
        else
        {
            json.put("callType", "Audio");
        }
        json.put("appointmentId", appointmentID);
        json.put("sessionID", sessionID);
        json.put("doctorID", doctorID);
        json.put("VOIPCall", "1");
    }
    catch (JSONException e)
    {
        e.printStackTrace();
    }
    qbEvent.setMessage(json.toString());
    StringifyArrayList<Integer> userIds = new StringifyArrayList<>(recipients);
    qbEvent.setUserIds(userIds);
    QBPushNotifications.createEvent(qbEvent).performAsync(null);
```

**Comment by silicus-kirankhalkar** [comment]
@shoaibHassanAttech - Yes, we also have the same code snippet. but we not received VOIP call from android on below two conditions.

1. when the iOS app is in the background, call not received from Android
2. when their OS app was killed/screen locked, call not received from Android.

As I mentioned, it is working fine on iOS to iOS.

For testing purpose, I have added logfile for VOIP method but doesn't find any logs for the above two conditions.

**Comment by shoaibHassanAttech** [comment]
Maybe you are receiving VOIP notification in background but not handing in didReceiveIncomingPushWith properly,
and app is crashing before callkit get initiated,
please write a text/json file in documents directory in this method with log including payload, then you will get better idea.

**Comment by silicus-kirankhalkar** [comment]
@shoaibHassanAttech, I have already done that, I have written Payload in my text log file but not found any entry.   

 - (void)pushRegistry:(PKPushRegistry *)registry didReceiveIncomingPushWithPayload:(nonnull PKPushPayload *)payload forType:(nonnull PKPushType)type withCompletionHandler:(nonnull void (^)(void))completion {
//Logfile added here..
}

**Comment by kirti301290** [comment]
@silicus-kirankhalkar @shoaibHassanAttech 
i  have similar problem and found problem from android side so need to send environment (production or development )  in push notification payload then ios will  receiver voip notification

**Comment by silicus-kirankhalkar** [comment]
@kirti301290 - Can you please share Android end the sample Payload?

**Comment by kirti301290** [comment]
@silicus-kirankhalkar 
you need to set  one in manifest file and qbevent class like this 
  qbEvent.setEnvironment(QBEnvironment.PRODUCTION);
you are doing in development then need to set development instead of production
may be you are set PRODUCTION mode that why are not getting notification

**Comment by silicus-kirankhalkar** [comment]
@kirti301290 - Thanks for your reply.  Yes, Our Android developer already added this line of code while initiating call "qbEvent.setEnvironment(QBEnvironment.PRODUCTION)". We also tried the "development" environment but it did not work. We will again revisit this point.

**Comment by silicus-kirankhalkar** [comment]
@kirti301290 - have you received a call from Android to iOS when iOS App has in Background or Kill state?. We have done above changes like "qbEvent.setEnvironment(QBEnvironment.DEVELOPMENT)" but it does not work.

**Comment by kirti301290** [comment]
@silicus-kirankhalkar  yes, do you added  same environment in manifest file file 
 opened ticket regarding this problem from quickblox and here is their reply

Check the Admin Panel whether a user has Push Notification subscription for Device(s) or not → Admin panel →App name→Push notifications→Subscriptions→User

Please make sure that devices have subscriptions to all of the push notifications types for Android and iOS: GCM/APNS/VOIP. Please take a look: https://i.imgur.com/B5t4StL.png

Make sure that Push Notifications subscriptions exist for the proper environment(s) (Prod and/or Dev). You can check the details of Push Notification Subscription closely by going to Admin panel→ App name→Push notifications→Queue→Sender→UDID: https://i.imgur.com/OliWpMO.png

Make sure that the Push is sent from the same environment device is subscribed for (QBEnvironment DEVELOPMENT to PRODUCTION or vice versa)
Bundle Identifier (for APNS) in Push Subscription should match Bundle Identifier of APNS Certificate itself: https://i.imgur.com/UVgDgWU.png

Please check the error log next to the APNS cert, click on "View error log" button, download the log and check for possible errors.

**Comment by silicus-kirankhalkar** [comment]
@kirti301290 - Thanks, I just want one confirmation is the point here, I have subscribed only for VOIP, not for an APNS?  is it fine or I need to be a subscription for APNS as well.

**Comment by shoaibHassanAttech** [comment]
if you are subscribed to VOIP, and your subscription is shown in quickblox dashboard, then you should receive VOIP notification, Even if you are not receiving VOIP notification from iOS to iOS with this type of payload in killed/terminated state,then most probably you have some certificates issue.   

```
  let payload = [
            "ios_voip": "1",
            UsersConstant.voipEvent: "1",
            "sessionID": sessionId,
            "conferenceType" : conferenceTypeString,
            "timestamp" : timeStamp,
            "callType" : isVideoCall ? "Video" : "Audio"
        ]
        
        let data = try? JSONSerialization.data(withJSONObject: payload,
                                               options: .prettyPrinted)
        var message = ""
        if let data = data {
            message = String(data: data, encoding: .utf8) ?? ""
        }
        let event = QBMEvent()
        event.notificationType = QBMNotificationType.push
        event.usersIDs = usersIDsString
        event.type = QBMEventType.oneShot
        event.message = message
        QBRequest.createEvent(event, successBlock: { response, events in
            debugPrint("[QBManager] Send voip push - Success")
        }, errorBlock: { response in
           // debugPrint("[QBManager] Send voip push - Error \(String(describing: response.error?.description))")
        })
```

**Comment by silicus-kirankhalkar** [comment]
@shoaibHassanAttech - No, It is working fine for iOS to iOS - I received a call from Application all state (Active,background and Kill). But this is not worked for the below condition- 
Android to iOS issue- 
1. when the app is in the background, calling functionality not working. 
2. when the app was killed/screen locked, calling functionality not working.

**Comment by silicus-kirankhalkar** [comment]
@kirti301290 @shoaibHassanAttech - We have resolved this issue.  Thank you for your inputs and time. 

Managing Background Mode properly is the key. Ensure you manage users' Background mode properly, because automatic Chat Alerts for Offline users require that a recipient is explicitly Offline:
follow the following link:
https://docs.quickblox.com/docs/ios-chat#section-chat-in-background

Note- iOS app needs to Connect Quickblox and disconnect on below method.
// 1
    func applicationWillTerminate(_ application: UIApplication) {
        QBChat.instance.disconnect { (error) in
        }
    }
//2 
    func applicationDidEnterBackground(_ application: UIApplication) {
        QBChat.instance.disconnect { (error) in
        }
    }
//3
    func applicationWillEnterForeground(_ application: UIApplication) {
        QBChat.instance.connect(withUserID: currentUser.ID, password: currentUser.password) { (error) in
        }
    }

iOS end we have not added this line   **QBChat.instance.disconnect { (error) in
        }**  
into the  applicationWillTerminate and  applicationDidEnterBackground method.
