### ISSUE TITLE
Issue with Quickblox WebRTC v1.0.6 error in iOS

### ISSUE THREAD

**Issue by NirmitDagly** [QuickBlox/quickblox-ios-sdk#124]
Hello,
  I am getting error of duplicate symbols for Quickblox WebRTC framework in iOS. I am  using XCode 6.4 and Quicblox WebRTC framework v1.0.6. My deployment target is iOS 8.0. I am getting this error as shown in attached image. It is showing 244 Duplicate symbols error in architecture armv7. Please tell me how can I solve this?
![screen shot 2015-07-31 at 15 58 04](https://cloud.githubusercontent.com/assets/8401881/9005587/ff6b9e54-379c-11e5-8aa9-b1555bac1590.png)

**Comment by Pro100Andrey** [comment]
Hi @NirmitDagly Please check framework search path (in build settings), maybe you have included quickbloxWebRTC framework twice

**Comment by NirmitDagly** [comment]
Have checked it. The framework path is set properly and does't include quickbloxWebRTC framework twice.

**Comment by Pro100Andrey** [comment]
@NirmitDagly This can happen if you accidentally #import a .m file instead of the .h! in your project.

**Comment by Pro100Andrey** [comment]
or provide full build log

**Comment by NirmitDagly** [comment]
Hello Andrey,
  I have not accidentally imported any .m file. So, it is not a matter of issue. Here I am attaching screenshots of Framework Search path as well as debug log. Hope it helps you.

Thanks once again.
![screen shot 2015-07-31 at 16 53 59](https://cloud.githubusercontent.com/assets/8401881/9006469/172929a0-37a5-11e5-860f-e5effb92769d.png)
![screen shot 2015-07-31 at 16 53 35](https://cloud.githubusercontent.com/assets/8401881/9006470/177cd5dc-37a5-11e5-96bd-7638f0c96768.png)

**Comment by Pro100Andrey** [comment]
Solution: remove -all_load  from "other linker flags"
