### ISSUE TITLE
I am getting ' o ' in the one to one chat user name and how to display the username of last user who sent the message

### ISSUE THREAD

**Issue by ajay2c9** [QuickBlox/quickblox-ios-sdk#127]
When i create a single chat  after creating  i check in the dialogVC and for few single chats  it shows the username as ' o ' . how to display the username correctly for single chats. Please give the suggestions for getting the user name who sent the last message in the chat.

Thank you

**Comment by soulfly** [comment]
Can you provide a screenshot?

**Comment by ajay2c9** [comment]
![screen shot 2015-08-07 at 1 14 31 pm](https://cloud.githubusercontent.com/assets/9112899/9131112/62916dce-3d06-11e5-89c1-39b8d754f16b.png)

Hi
 The above is the screen shot  i am just checking the integrating the sample code in another sample app  after creating the  dialog the when checking the 1-1 chat it shows like this.

Thank you

**Comment by ajay2c9** [comment]
Hi
this is the screen shot of the sample provided for  1-1 chat it shows like this.the name ' o ' is showing like this 
![ios simulator screen shot 11-aug-2015 11 44 09 am](https://cloud.githubusercontent.com/assets/9112899/9191395/90295f38-401e-11e5-89dd-5d7ad9238bff.png)

**Comment by soulfly** [comment]
This is fixed already
