### ISSUE TITLE
response [QBResponse], status: 201 after sending message

### ISSUE THREAD

**Issue by aju10** [QuickBlox/quickblox-ios-sdk#1279]
after sending message got this response [QBResponse], status: 201, 
and notification not send to next user
Please help me out to solve this

**Comment by aju10** [comment]
@stephanoparaskeva Thanks, just join the QB Community on slack

**Comment by QB-nikolay-zolotarov** [comment]
@aju10 The issue is being closed as outdated.

If it is still relevant, feel free to open a new issue.
