### ISSUE TITLE
getting error in Login to chat

### ISSUE THREAD

**Issue by NirmitDagly** [QuickBlox/quickblox-ios-sdk#128]
Currently I'm getting error in Login to chat. Following is the snippet of error that I'm getting.
-[QBChat xmppStreamDidDisconnect:withError:] -> error: Error Domain=kCFStreamErrorDomainSSL Code=-9825 "The operation couldn’t be completed. (kCFStreamErrorDomainSSL error -9825.)" UserInfo=0x7ff3b9f1a390 {NSLocalizedRecoverySuggestion=Error code definition can be found in Apple's SecureTransport.h}

Please advice me how to solve this error. Thanks in advance..!!

**Comment by AndreyMoskvin** [comment]
Hello!

We are working on this issue. Will let you know when it will be resolved.

**Comment by NirmitDagly** [comment]
solved by Quickblox team. Thanks.

**Comment by kittu4ios** [comment]
I am getting below error.

[ChatService] Did disconnect with error: Error Domain=kCFStreamErrorDomainSSL Code=-9806 "(null)" UserInfo={NSLocalizedRecoverySuggestion=Error code definition can be found in Apple's SecureTransport.h}

**Comment by Pro100Andrey** [comment]
hi @kittu4ios  please update SDK to last version

**Comment by VitaliyGuru** [comment]
Hello, @kittu4ios, You've already created [issue](https://github.com/QuickBlox/quickblox-ios-sdk/issues/669), so there is no need to add comments here.
