### ISSUE TITLE
QuickBlox community Slack

### ISSUE THREAD

**Issue by stephanoparaskeva** [QuickBlox/quickblox-ios-sdk#1280]
Here is the invite link:
https://join.slack.com/t/quickbloxcommunity/shared_invite/zt-q0s3bx3b-YzacqhEfPeBGbEdgEtFr1g

quickbloxcommunity.community.slack

@muteKey @Forsarion @soulfly

**Comment by haarj** [comment]
Hi @stephanoparaskeva where can we get invite links to the slack channel? Thanks!
