### ISSUE TITLE
Too many occupants for Private Dialog.

### ISSUE THREAD

**Issue by jeetrajput01** [QuickBlox/quickblox-ios-sdk#1281]
ERROR occur while creating private chat dialog 
  Optional(
   Error reasons:{
    errors =     (
        "Too many occupants for Private Dialog."
    );
})
I found this is an error from QBResponse.

**Comment by QB-nikolay-zolotarov** [comment]
@jeetrajput01 The issue is being closed as outdated.

If it is still relevant, feel free to open a new issue.
