### ISSUE TITLE
Could not build Objective-C module 'Quickblox'

### ISSUE THREAD

**Issue by remotelxszk** [QuickBlox/quickblox-ios-sdk#1285]
When I try to import Quickblox inside AppDelegate after installing it with Cocoapods (pod 'Quickblox'), I get this error: 
`'QuickBlox/QBAddressBookContact.h' file not found`
I've tried deleting Derrived Data, Clearing pods cache, deleting all pods and reinstalling it.

**Comment by remotelxszk** [comment]
I fixed it by replacing in every header file 
`#import<QuickBlox` 
with 
`#import<Quickblox`

**Comment by QB-vladyslav-vyshniak** [comment]
Hello Dominik. 

Thank you for contacting QuickBlox Customer Support department. 

Glad that the reported case has been successfully resolved on your side and is no longer relevant. 
The status of the ticket changed to "Closed" for now. 

Have a good day.
