### ISSUE TITLE
Differentiate bw calling and ringing 

### ISSUE THREAD

**Issue by tarikhs** [QuickBlox/quickblox-ios-sdk#1286]
**New Issue Checklist**

 - [x] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [x] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    | ~13.0                                    |                                          
Quickblox iOS SDK version      |  2.17.10                                  |
QuickbloxWebRTC SDK version    | 2.7.6                                  |                               
Xcode Version                  |  Xcode 12                              |
Repro with our demo sample     | YES  |

**Did this work before?**
NO

**Expected behavior**
Once the call is initiated and callee is offline it will receive a VOIP in return his app starts and receive a session. I need to know when the session is received on callee side, so I can update the calling screen stats from CALLING -> RINGING 

**Actual behavior**
No any notification or delegate method to notify

**Steps to reproduce the behavior**
start calling an offline user via VOIP Push app open and session received called but no notification on caller side.

**Any others comments**
There should be some delegate method to notify i.e. didStartRinging()

**Comment by QB-nikolay-zolotarov** [comment]
Hello Tariq,

This is Nikolay from QuickBlox support.

Please check the following method:
onCallListener - A new call session has been received.

Please refer to the Event Listener section in the documentation:
https://docs.quickblox.com/docs/js-video-calling#event-listener

Also, please be notified that the handling of VoIP notifications in the background/non-running state isn't part of QuickBlox SDK's and the implementation of that functionality is up to the client side.

You can check the correct implementation and work of VoIP notifications on the clear QuickBlox iOS WebRTC sample, which you can find by this URL: https://docs.quickblox.com/docs/code-samples#video-calling-samples

We are going to release a new iOS Swift WebRTC sample that will bring more understanding in the implementation of VOIP functionality.
