### ISSUE TITLE
Self video is inverted

### ISSUE THREAD

**Issue by karthiksrinivas** [QuickBlox/quickblox-ios-sdk#129]
Self video is inverted in Qmunicate and sample app. Please suggest.

**Comment by madhu014** [comment]
That's an issue with SDK and probably will be fixed in next versions. I rotated the video view by 180 degrees to get round this problem.

**Comment by soulfly** [comment]
Try our latest WebRTC SDK
http://quickblox.com/developers/Sample-webrtc-android
