### ISSUE TITLE
Swift Package Manager

### ISSUE THREAD

**Issue by OmarNoppe** [QuickBlox/quickblox-ios-sdk#1291]
Are there any plans to support the Swift Package Manager for installing the Quickblox SDK?

**Comment by QB-nikolay-zolotarov** [comment]
Hello Omar,

This is Nikolay from QuickBlox support.

The point with Swift Package Manager support is absent in the roadmap for this year.

You may check [the iOS SDK repository](https://github.com/QuickBlox/quickblox-ios-sdk) for updates.
