### ISSUE TITLE
[BUG] lastMsgText remains even if message is deleted

### ISSUE THREAD

**Issue by maughray** [QuickBlox/quickblox-ios-sdk#1297]
- [x] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [x] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

**Bug description**
If all messages from a dialog are removed (even for all users), _lastMsgText_ property of _**Dialog**_ model contains last message anyway, even if it does not exist anymore.
In QuickBlox admin panel is the same situation - dialog contains "Last message", but there are no messages in that dialog.

**Steps to reproduce the behavior**
1. Create new private dialog with any user
2. Send a message to that user
3. Remove that message for all users

*Expected result*
_lastMsgText_ property of _**Dialog**_ model is null
*Actual result*
_lastMsgText_ property of _**Dialog**_ model contains last message that does not even exist.

**Comment by QB-nikolay-zolotarov** [comment]
@maughray Hello,

This is Nikolay from QuickBlox support.

Please let me know if the issue is reproduced on the latest version of the QuickBlox iOS SDK (2.17.10):
https://github.com/QuickBlox/quickblox-ios-sdk/releases/tag/2.17.10

Also, please provide me with the following information:
- Versions of the iOS platform where the issue is reproduced (e.g. iOS 13).
- iPhone models (e.g. iPhone 12 Pro).

**Comment by maughray** [comment]
> @maughray Hello,
> 
> This is Nikolay from QuickBlox support.
> 
> The issue is being investigated.
> 
> Please let me know if the issue is reproduced on the latest version of the QuickBlox iOS SDK (2.17.10): https://github.com/QuickBlox/quickblox-ios-sdk/releases/tag/2.17.10
> 
> Also, please provide me with the following information, just in case:
> 
> * Versions of the iOS platform where the issue is reproduced (e.g. iOS 13).
> * iPhone models (e.g. iPhone 12 Pro).

This is a server-side issue. I don't think that iOS version or iPhone models matter.
