### ISSUE TITLE
Displaying of the images quickly when  they are posted

### ISSUE THREAD

**Issue by ajay2c9** [QuickBlox/quickblox-ios-sdk#130]
hi,
I want to display the image instantly when the image is posted.Give the suggestions to display the images fastly.

**Comment by AndreyMoskvin** [comment]
Hi,

Which one images? Image that you are sending as an attachment?

**Comment by ajay2c9** [comment]
YES. when the image is selected from gallery,firstly it displayed in the dialog before uploading process is started 

Please give suggestions.

Thank you

**Comment by ajay2c9** [comment]
YES. when the image is selected from gallery,firstly it displayed in the
dialog before uploading process is started.

Please give suggestions or samples.

Thank you

----------------------------
Regards
Ajay

**Comment by AndreyMoskvin** [comment]
Which one branch of samples do you use?

**Comment by ajay2c9** [comment]
sample-content sample is used. 

I designed a single tableview cell like displaying both text and images. by using a string i identified the images and text and setting the frames for images I used the code for displaying the images is   sample-chat project code for fillWithStickerMessage. generating the url using the attachment id  and using SDWebimge image is displaying in the cell.

if is there any wrong with this please give the suggestions I will follow up

**Comment by ajay2c9** [comment]
hi,
I want to display the image fastly. I am getting the while going to the chat screen.i am using the  QBCBlob id for displaying the image. I used below code

 NSString *imgurl1 = [QBCBlob privateUrlForID:[str integerValue]];
  [cell.stickerImage sd_setImageWithURL:[NSURL URLWithString:imgurl] placeholderImage:[UIImage imageNamed:@""]];

is there any fastest way to display the images.


Please give suggestions.

Thank you

**Comment by AndreyMoskvin** [comment]
Hi,

Faster way it is to use smaller images(previews, with smaller width and height).

**Comment by ajay2c9** [comment]
But requirement is to display images in 220*220 . we are using default camera for taking the images.
we uploading the image in the reduce size by using below code.
    imagedata = UIImageJPEGRepresentation(chosenImage, 0.1f);

is there any other way to display the images fastly ?
Please give suggestions.
Thank you

**Comment by ajay2c9** [comment]
Hi,

I implemented your suggestion now its working .thanks you suggestion.
 
In chatting screen we need to display the  profile pics (who sent messages to us). i am using the  the below method in cell for row to display profile pic images.
[QBRequest userWithID:message.senderID successBlock:^

in the success response of the method i get the url using the blobid by using the below code
                 NSString *privateUrl = [QBCBlob privateUrlForID:user.blobID];

 displaying image using the SDWebImage methods.

My problem is when the msg or image is sent or received the profile pics in all tableview cells are flickering . is there any other way to display the profile pics with out flickering.

Please give suggestions.
Thank you

**Comment by AndreyMoskvin** [comment]
Hi,

Could you please ask your question on http://stackoverflow.com.
Unfortunately we can't help you with questions that is not related to Quickblox.

**Comment by ajay2c9** [comment]
ok thanks
