### ISSUE TITLE
NSInternalInconsistencyException', reason: 'Killing app because it never posted an incoming call to the system after receiving a PushKit VoIP push.' terminating with uncaught exception of type NSException

### ISSUE THREAD

**Issue by akshaypatil5634** [QuickBlox/quickblox-ios-sdk#1302]
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Killing app because it never posted an incoming call to the system after receiving a PushKit VoIP push.'

App crashing in pushRegistry(_ registry: PKPushRegistry,
                      didReceiveIncomingPushWith payload: PKPushPayload,
                      for type: PKPushType,
                      completion: @escaping () -> Void)

**Comment by QB-liubov-shmatok** [comment]
Hello Akshay,

Please, be notified, that the handling of VOIP notifications in the background/non-running state isn't part of QuickBlox IOS SDK's and the implementation of that functionality is up to the client-side.

To use Apple CallKit with VOIP notifications please refer to our documentation:
https://docs.quickblox.com/docs/ios-video-calling-advanced#apple-callkit-using-voip-push-notifications

You can check the correct implementation and work of VOIP notifications in the background/non-running state on clear QuickBlox IOS WebRTC samples, that you can find by this URL:
https://docs.quickblox.com/docs/code-samples#video-calling-samples
Here are a few more useful links according to your issue and possible ways of resolving it:

    https://developer.apple.com/videos/play/wwdc2019/707/   
    https://forums.developer.apple.com/thread/117939
    https://developer.apple.com/documentation/pushkit/responding_to_voip_notifications_from_pushkit?language=objc
