### ISSUE TITLE
You have to be connected to Chat in order to use Chat API.

### ISSUE THREAD

**Issue by pradip-thummar-sttl** [QuickBlox/quickblox-ios-sdk#1303]
hi Dear,

we have implement chat functionality but all SDK Api error send "You have to be connected to Chat in order to use Chat API."

please help me for this problem.

**Comment by QB-nikolay-zolotarov** [comment]
@pradip-thummar-sttl Hello,

This is Nikolay from QuickBlox support.

Please double-check our documentation regarding authentication:
[https://docs.quickblox.com/docs/ios-authentication](https://docs.quickblox.com/docs/ios-authentication)

Also, please make sure that the user is connected to chat:
[https://docs.quickblox.com/docs/ios-chat-connection](https://docs.quickblox.com/docs/ios-chat-connection)
