### ISSUE TITLE
QuickBlox not compilable on case-sensitive drives

### ISSUE THREAD

**Issue by Borisss** [QuickBlox/quickblox-ios-sdk#1304]
Due to mismatch of cases in imports and paths in framework directories/files (Quickblox vs QuickBlox on multiple places) pod is not compilable on APFS (case-sensitive) drives.

Experienced in Xcode 12.5.1, iOS 14.0, QuickBlox 2.17.10 but it shouldn't matter. This should probably be fixed as it's a simple rename for all
`#import <QuickBlox/` to `#import<Quickblox/` and is in general a good practice to avoid mismatching cases regardless of filesystem.

**Comment by QB-nikolay-zolotarov** [comment]
@Borisss Hello, This is Nikolay from QuickBlox support.
We have forwarded this information to our developers. Once there is any news, we will let you know.

**Comment by QB-nikolay-zolotarov** [comment]
@Borisss 
Thank you for reporting this.
However, according to our developers, it is a standard. 
This is how #import is written by default when creating a project.
