### ISSUE TITLE
Apple silicon support?

### ISSUE THREAD

**Issue by codingrhythm** [QuickBlox/quickblox-ios-sdk#1307]
**New Issue Checklist**

 - [x] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [x] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    | 15.0                                    |                                          
Quickblox iOS SDK version      | 2.17.10                                  |
QuickbloxWebRTC SDK version    | 2.17.10                                  |                               
Xcode Version                  | Xcode 13.2.1                              |
Repro with our demo sample     | Yes   |

**Did this work before?**
No

**Expected behavior**
Successfully built against iOS simulator with arm64 architecture.

**Actual behavior**
Build failed due to missing symbols for arm64.

**Logs**

```logos
Undefined symbol: _OBJC_CLASS_$_QBChat
Undefined symbol: _OBJC_CLASS_$_QBChatDialog
Undefined symbol: _OBJC_CLASS_$_QBChatMessage
Undefined symbol: _OBJC_CLASS_$_QBGeneralResponsePage
Undefined symbol: _OBJC_CLASS_$_QBRequest
Undefined symbol: _OBJC_CLASS_$_QBResponsePage
Undefined symbol: _OBJC_CLASS_$_QBSession
Undefined symbol: _OBJC_CLASS_$_QBSettings
Undefined symbol: _OBJC_CLASS_$_QBUUser

```

</details>

**Steps to reproduce the behavior**

1. Open Xcode 13 on M1 machine
2. Build the project with the SDK.

**Any others comments**

**Comment by QB-nikolay-zolotarov** [comment]
@codingrhythm Hello,

This is Nikolay from QuickBlox support.

We will refactor the samples in the future.

At this moment to correctly launch samples in the iOS simulator, you need to update the pod file like in the next snippet:
```
post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
end
```

And reinstall the pods.

Podfile example (update pod file for the chat sample swift):
```
platform :ios, "13.0"

use_frameworks!

inhibit_all_warnings!

target 'sample-chat-swift' do
    pod 'QuickBlox', '~> 2.17.10'
    pod 'SVProgressHUD'
    pod 'SDWebImage', '~> 4.4.7'
    pod 'TTTAttributedLabel', '~> 2.0.0'
end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
end
```

**Comment by codingrhythm** [comment]
@QB-nikolay-zolotarov Thanks for your reply. Correct me if I am wrong, this change you suggested was to exclude arm64 from iOS simulator build, but we actually need it for building on M1 machine. What we need is to include the arm64 slice (for simulator) as part of the prebuilt xcframework. Instead of `ios-x86_64-simulator/Quickblox.framework`, we will have `ios-arm64_x86_64-simulator/Quickblox.framework`

**Comment by QB-nikolay-zolotarov** [comment]
@codingrhythm Thank you for your reply. Yes, you are right. We will add support of arm64 in the next release. 
I will update you.

**Comment by codingrhythm** [comment]
@QB-nikolay-zolotarov That's great! Do you know when will the next release be?

**Comment by QB-nikolay-zolotarov** [comment]
@codingrhythm ETA - next week.

**Comment by codingrhythm** [comment]
Hi @QB-nikolay-zolotarov any updates on this? Thanks.

**Comment by QB-nikolay-zolotarov** [comment]
@codingrhythm Hello. Our developers are working on it. However, unfortunately, it was not possible to build our SDK for the required architecture. It will take some more time. I will update you as soon as possible.

**Comment by codingrhythm** [comment]
@QB-nikolay-zolotarov Hi, could you be more specific why it's not possible? Is there any help I can provide? I've been working on M1 support for some of our own mobile libraries(c++, golang) recently on both M1 and Intel based Macbook Pro. Maybe I could provide a bit help?

**Comment by QB-nikolay-zolotarov** [comment]
@codingrhythm Thank you, I will provide you with information from the developers as soon as I have it. If we have any questions, we will let you know.

**Comment by QB-nikolay-zolotarov** [comment]
@codingrhythm We have successfully built a QuickBlox SDK with arm64 simulator support. But we can't build the Quickblox-WebRTC SDK because there is a fail with building a static WebRTC library with simulator support.

We will provide a new Quickblox-WebRTC SDK with arm64 simulator support. ETA - 4 months.

**Comment by codingrhythm** [comment]
BTW, we are not using Quickblox-WebRTC SDK anyway, so arm64 simulator support for QuickBlox SDK should be sufficient at the moment.

**Comment by QB-nikolay-zolotarov** [comment]
@codingrhythm We will try building the SDK. However, it will take time due to the current situation in Ukraine.

**Comment by codingrhythm** [comment]
Thanks @QB-nikolay-zolotarov . Let me know if you have any updates.

**Comment by QB-nikolay-zolotarov** [comment]
@codingrhythm Unfortunately, there are no updates. I will update you if there is any news.

**Comment by QB-nikolay-zolotarov** [comment]
@codingrhythm M1 simulator support added in the new version, please check

**Comment by codingrhythm** [comment]
@QB-nikolay-zolotarov Thanks, we've tested it, works as expected. All the best!
