### ISSUE TITLE
How to delete a message from chat?

### ISSUE THREAD

**Issue by joytomchin** [QuickBlox/quickblox-ios-sdk#1308]
how to delete message from a chat?

**Comment by QB-nikolay-zolotarov** [comment]
@joytomchin Hello, 

This is Nikolay from QuickBlox support.

Please refer to our documentation:
https://docs.quickblox.com/docs/ios-chat-messaging#delete-message

**Comment by joytomchin** [comment]
Thank you @QB-nikolay-zolotarov 

It's my mistake I'm on wrong GitHub repo, actually my question was for **`quickblox-react-native-sdk`**.

Thanks

**Comment by QB-nikolay-zolotarov** [comment]
@joytomchin Unfortunately, the functionality of deleting messages is not described in our React Native SDK.

According to our developers, It is planned for development. However, there is no ETA.

You may refer to the iOS and Android documentation to write it natively:
https://docs.quickblox.com/docs/android-chat-messaging#delete-message
https://docs.quickblox.com/docs/ios-chat-messaging#delete-message
