### ISSUE TITLE
Updating the chatdialog

### ISSUE THREAD

**Issue by ajay2c9** [QuickBlox/quickblox-ios-sdk#131]
Hi,
 I created a chatroom with one user and did some chatting. Now i want to update the chat dialog by adding 2 more users (making private chat toGroup chat).  i implemented updateDialog for updating the group chat it is working fine. is there any solution to update the private chat.

please give suggestions.

Thank you

**Comment by AndreyMoskvin** [comment]
Hi!

Unfortunately - no, there is no way to create group chat from private and add occupants to it. You can use only group chats (even for 2 people) - than you will not have this problem.

**Comment by ajay2c9** [comment]
how can I set the type as group when one user is selected. is the same procedure like creating the group chat? or need to change the some thing else.

 please give suggestions.

Thank you

**Comment by ajay2c9** [comment]
how can I set the type as group when one user is selected. is the same
procedure like creating the group chat? or need to change the some thing
else.

please give suggestions.

Thank you

> ----------------------------
>
Regards
Ajay

**Comment by AndreyMoskvin** [comment]
You can create group chat with one user. It will work. The procedure is the same.

**Comment by ajay2c9** [comment]
ok. I will work and inform you

Thank you

**Comment by ajay2c9** [comment]
Thank you for suggestion its working now

**Comment by ajay2c9** [comment]
HI I create a dialog with three people  after some chatting i added(updated) 3 more people to that chat. for last 3 more people how to show the new messages only.now it showing all the previous messages also.

**Comment by ajay2c9** [comment]
Hi,
 I have to display all the names who are in the Group chatting . my problem is when one of the user is updated the his login name. How to updated his name in the chatroom 

Please give suggestions

Thank you

**Comment by AndreyMoskvin** [comment]
Hi, 
1. Probably you can hide/delete messages that are before the date of the "join-to-dialog" message.
2. You can send system message with updated login to the users of the group and update the login accordingly.

**Comment by ajay2c9** [comment]
I didn't get 2nd point.please explain

**Comment by ajay2c9** [comment]
How to send the  system message please suggest . if we send the system message , username  updated in all chatDialog.name? if not is there any other way

**Comment by AndreyMoskvin** [comment]
You will need to update it manually when you receive this message.

http://quickblox.com/developers/SimpleSample-chat_users-ios#System_notifications
