### ISSUE TITLE
Exporting archive with `gym` fails with the latest version of Quickblox

### ISSUE THREAD

**Issue by corujautx** [QuickBlox/quickblox-ios-sdk#1311]
**New Issue Checklist**

 - [X] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [X] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

**Environment details**

Info|Value|
---|---|
iOS Version|14.0|                                          
Quickblox iOS SDK version|2.17.11|
QuickbloxWebRTC SDK version|N/A|                               
Xcode Version|Xcode 13.2.1|
Repro with our demo sample| e.g. does it happen with our demo sample?   |

**Did this work before?**
Yes

**Expected behavior**
Export to succeed

**Actual behavior**
Export does not succeed

**Logs**

*Please use the following template for logs:*

To enable full logs use the following code:
```objc
[QBSettings setLogLevel:QBLogLevelDebug];
[QBSettings enableXMPPLogging];
```

<details>

This is not a runtime log, rather it's a `gym` output from Fastlane. I think it's related to missing bitcode in the fat frameworks embedded in the `.xcframework`. We do not want to disable bitcode in our app because we want to be able to distribute an slim app.

<summary>Gym logs</summary>

Please check the attached files
[gym.log](https://github.com/QuickBlox/quickblox-ios-sdk/files/8438979/gym.log)

</details>

**Steps to reproduce the behavior**
1. Create a project and link with Quickblox
2. Export an archive using `gym`

Alternatively, try to distribute an archive with Xcode whilst rebuilding with bitcode

![image](https://user-images.githubusercontent.com/4993929/162099788-72f8f91e-b279-4c7d-bbe3-57658a4d9149.png)
![image](https://user-images.githubusercontent.com/4993929/162102916-56ab6929-b181-4555-affd-a61191224ea8.png)

**Any others comments**
N/A

**Comment by QB-nikolay-zolotarov** [comment]
@corujautx Hello, this is Nikolay from QuickBlox support.
We created a new project and installed our new SDK into it using CocoaPods and manually.
Several times we built the project for release under various conditions.
The error did not reproduce.

Please try updating XCode to the latest version.

**Comment by corujautx** [comment]
Do you guys changed anything recently on the CocoaPods phase? We're not integrating it via CocoaPods.

**Comment by corujautx** [comment]
Updating to the latest Xcode version is not possible as well due to the known issue with bitcode and Swift's new concurrency model.

**Comment by JohnCaccavale-Teladoc** [comment]
@QB-nikolay-zolotarov I may be having similar issues. At this time I'm not sure if it is Quickblox or not. I am using the latest version of Xcode version 13.3.1 and installing via CocoaPods QuickBlox (2.17.11).

As you can see from my screenshot below, it does look quite similar to the screenshot @corujautx posted. I am building a Framework that utilizes Quickblox and when integrating my XCFramework into a sample app—when I then try to export the sample with the `Rebuild from Bitcode` checkbox selected, it fails. 

If I run `xcrun bitcode-build-tool` in the terminal against the latest iOS SDK and my framework, I consistently get the following error.

```console
Quickblox not found in dylib search path
```

I'm not doing anything out of the ordinary as far as  I can tell, the Podfile simply lists  `pod 'QuickBlox'` along with many other pod dependencies. 

If I use `otool -L` I see Quickblox in the list as well,

```console
@rpath/Quickblox.framework/Quickblox (compatibility version 1.0.0, current version 1.0.0)
```

Would you have any thoughts on this?

![Screen Shot 2022-04-18 at 4 05 51 PM](https://user-images.githubusercontent.com/84742379/163871227-44805d04-0503-49a0-82ae-af016077b4f8.png)

**Comment by JohnCaccavale-Teladoc** [comment]
Also, I just tested everything by commenting out Quickblox from my podfile and building my Framework without it. By not including Quickblox I was then able "Rebuild from Bitcode" and export everything accordingly.

**Comment by QB-nikolay-zolotarov** [comment]
Thank you, we are reviewing the information
