### ISSUE TITLE
ChatViewController - blank space between inputToolBar and Keyboard/keyboard predictive suggestions

### ISSUE THREAD

**Issue by haarj** [QuickBlox/quickblox-ios-sdk#1318]
I think this is the solution but not 100% 
`var pos = view.frame.size.height - convertedViewPoint.y - self.view.frame.origin.y + 5`

https://github.com/QuickBlox/quickblox-ios-sdk/blob/e3fb2f95a3d05e7eeaa36489da37d5869fd7c0d4/sample-chat-swift/sample-chat-swift/Components/ChatScreen/ChatViewController.swift#L178

Also I think you need to add `observerAdded = false` in these braces somewhere so if a user dismisses the keyboard by an interactive dismiss, the textview's keyboard can be hit again in the `observeValueForKeyPath` method and the calculation to show the toolbar on top of the keyboard runs - https://github.com/QuickBlox/quickblox-ios-sdk/blob/329b633192cd70e79b7488a967094d338149a7d4/sample-chat-swift/sample-chat-swift/Components/ChatScreen/Chat/KVOView.swift#L36

**Comment by haarj** [comment]
Even better - This sticks the input toolbar to the top of the keyboard as a user presents and dismisses the keyboard. 
`var pos = superview.frame.size.height - view.frame.origin.y - self.view.frame.origin.y + 5`
https://github.com/QuickBlox/quickblox-ios-sdk/blob/e3fb2f95a3d05e7eeaa36489da37d5869fd7c0d4/sample-chat-swift/sample-chat-swift/Components/ChatScreen/ChatViewController.swift#L178

**Comment by QB-nikolay-zolotarov** [comment]
@haarj Hello, thank you, I've forwarded your feedback to the developers.

**Comment by haarj** [comment]
This is the best
`var pos = superview.frame.size.height - view.frame.origin.y`

**Comment by QB-nikolay-zolotarov** [comment]
@haarj Thanks for the feedback, we will consider this suggestion in the next release
