### ISSUE TITLE
The very first time I got a call, I got a prompt for Camera. This prompt needs to be disabled. 

### ISSUE THREAD

**Issue by subhangiP** [QuickBlox/quickblox-ios-sdk#1319]
**New Issue Checklist**

 - [x] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [x] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    | 15.0.2                                   |                                          
Quickblox iOS SDK version      | 2.17.10'                              |
QuickbloxWebRTC SDK version    | 2.7.6'                           |                               
Xcode Version                  | e.g. Xcode 13.0                             |

**Project descriptions **

- This is our flutter app which has audio call and chat functionality using quickblox-flutter as well as quickblox-iOS SDK that is 
   working fine.
- For chat, we are using [quickblox flutter SDK](https://github.com/QuickBlox/quickblox-flutter-samples) - working fine
- For audio calls, we are using [quickblox iOS SDK](https://github.com/QuickBlox/quickblox-ios-sdk) using the method channel 
   in native iOS - working fine
- Our app does require camera access to update the profile pic and that permission we are asking to user while adding the profile pic.
- The issue is if user didn’t add profile pic and receives a call the very first time time, there will be prompt for camera permission.
 **Why there is camera permission prompt in audio call is recieve. we have follow same iOS sample project to implement audio call functionality?**  Is it becoz [quickblox flutter SDK](https://github.com/QuickBlox/quickblox-flutter-samples) because it requires all` Camera, Microphone, Storage permissions` to **enable**

**Expected behavior**
This prompt needs to be disabled. 

**Actual behavior**
The camera permission prompt is displaying first time when call notifications is receive.

PFA SS for the same issue.
![camera_popup](https://user-images.githubusercontent.com/40853201/171825626-c7cd6464-2d20-42dc-8b07-ff94642ac256.PNG)

**Comment by QB-nikolay-zolotarov** [comment]
let's continue the conversation here: https://github.com/QuickBlox/quickblox-flutter-samples/issues/14
