### ISSUE TITLE
Clickable links

### ISSUE THREAD

**Issue by ajay2c9** [QuickBlox/quickblox-ios-sdk#132]
Hi 
how to make url links to be selectable and directed to browser when links are posted in Chatting.

Please give suggestions

Thank you

**Comment by AndreyMoskvin** [comment]
This question is not related to Quickblox Samples. Please look at  https://github.com/QuickBlox/QMChatViewController-ios there is a pod called **TTTAttributedLabel** which could be used for link detection.
