### ISSUE TITLE
Any callback / delegate to know the sender delete / update the message?

### ISSUE THREAD

**Issue by vincent0225** [QuickBlox/quickblox-ios-sdk#1325]
I am able to update / delete the message. But if the recipient is opening the chatroom, she is still seeing the original message.
Is there any callback / delegate method for the recipient to update the message list?

Currently, the recipient need to re-enter the chatroom to see the updated message.

**Comment by QB-nikolay-zolotarov** [comment]
@vincent0225 Hello, this is Nikolay from QuickBlox support. 
There is no callback for deleting messages.
As an option, you can send a system message and use the system message listener.
https://docs.quickblox.com/docs/ios-chat-messaging#send-system-messages
