### ISSUE TITLE
iOS - Can not make video call once app in background or terminated state.

### ISSUE THREAD

**Issue by Haribabu-Appit** [QuickBlox/quickblox-ios-sdk#1328]
QuickBlox (2.17.11)
* Quickblox-WebRTC (2.7.6) sdks ios

We've developed admin portal using javascript sdk. from admin portal, we've made a call to mobile apps. If the app is foreground call is coming but when the app in background and terminated state, Calls are not coming. I have uploaded universal certificate in quickblox dashboard.

**Comment by IlliaChemolosov** [comment]
Hello @Haribabu-Appit ,

This is Illia from Quickblox
Please, check the next info:
- [JS QB SDK Send push notifications](https://docs.quickblox.com/docs/js-push-notifications#send-push-notifications) 
- [Using Apple VoIP Push Notifications with QuickBlox SDK](https://quickblox.com/blog/using-apple-voip-push-notifications-with-quickblox-sdk/)
