### ISSUE TITLE
QBRTCSession initWithCurrentUserID:multicastHandler:sessionDescription:peerFactory: crashes app sometimes

### ISSUE THREAD

**Issue by tomkowz** [QuickBlox/quickblox-ios-sdk#133]
Hey guys,

I am using QuickBlox 2.3.0.3 / 2.3.0.4.

I am creating call session by sending array of `NSNumber`s to `QBRTCClient` -`createNewSessionWithOpponents:withConferenceType:` like this:

    self.callSession = [[QBRTCClient instance] createNewSessionWithOpponents:@[userId] withConferenceType:QBConferenceTypeVideo];
    [self.callSession startCall:@{@"newcall" : @"newcall"}];
    self.callSession.audioEnabled = self.publish;
    self.callSession.videoEnabled = self.publish;

I am sure that this `userId` is never nil, otherwise it will crash because `NSArray` cannot keep nils.

I saw the next call is `QBRTCSession` `-initWithCurrentUserId:multicastHandler:sessionDescription:peerFactory:` and first argument is sometimes nil and sometimes is the number I sent. 

>2015-08-25 12:17:09.711 LeeoCam[4709:2222773] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** setObjectForKey: key cannot be nil'
*** First throw call stack:
(0x2409b44b 0x35632dff 0x23fb6479 0x6eb1e9 0x461635 0x459163 0x459085 0x4598a5 0x461c0d 0x2409fe24 0x23fca485 0x23fcdf17 0x623657 0x2409e711 0x23fcde58 0x5e6b47 0x2409fe24 0x23fca485 0x23fcdf17 0x671e1b 0x1683e4f 0x1683e3b 0x1688891 0x2405e175 0x2405c66f 0x23faed89 0x23faeb7d 0x2d181af9 0x281d799d 0x464901 0x35d80873)
libc++abi.dylib: terminating with uncaught exception of type NSException

Is that a known issue?

Thank you in advance for help.

**Comment by tomkowz** [comment]
I missed that those ids are different. I see that current user id is nil so this one I send to `QBChat -loginWithUser`.

**Comment by tomkowz** [comment]
I investigate it a bit and this is why app crashed:

I was logging in using `QBChat -loginWithUser` and when I received `chatDidLogin` I send right away `QBRTCClient -createNewSessionWithOpponents:withConferenceType:` and this call was before presence was send by framework after `chatDidLogin` was received. When I wait to time when presence event is send I can make calls with no crashes.

**Comment by Pro100Andrey** [comment]
Hi @tomkowz!!! You're right, first you need to login to chat before using qbrtcclient.

**Comment by tomkowz** [comment]
Yup, works okay now.
