### ISSUE TITLE
QuickBlox 2.18.0 & QuickBloxWebRTC 2.8.0 can't upload to App Store Connect

### ISSUE THREAD

**Issue by haarj** [QuickBlox/quickblox-ios-sdk#1334]
**New Issue Checklist**

 - [-] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [-] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                   NA                                   
Quickblox iOS SDK version      2.18.0
QuickbloxWebRTC SDK version   2.8.0                              
Xcode Version                 14.0.1
Repro with our demo sample    

**Did this work before?**
Yes

**Expected behavior**
Uploads to AppStore Connect without errors

**Actual behavior**

**Logs**

Asset validation failed
CFBundleIdentifier Collision. There is more than one bundle with the CFBundleIdentifier value 'com.quickblox.Quickblox' under the iOS application 'MyApp.app'. (ID: e5ccb0c3-b715-49ce-b6b1-c301168c8bf0)

Asset validation failed
Invalid Bundle. The bundle at 'MyApp.app/Frameworks/QuickbloxWebRTC.framework' contains disallowed nested bundles. (ID: d47a4bbb-d390-4406-8992-44edaf38671f)

Asset validation failed
Invalid Bundle. The bundle at 'MyApp.app/Frameworks/QuickbloxWebRTC.framework' contains disallowed file 'Frameworks'. (ID: 949c4236-1ec6-4e84-af48-3ca6c748f94c)

*Please use the following template for logs:*

To enable full logs use the following code:
```objc
[QBSettings setLogLevel:QBLogLevelDebug];
[QBSettings enableXMPPLogging];
```

<details>
<summary>Title for logs </summary>

```logos

// Your logs here

```

</details>

**Steps to reproduce the behavior**

Archive and upload to app store connect. 
**Any others comments**

**Comment by sshaforenkoqb** [comment]
Hi haarj,
Thank you for the notification, the team is working on this right now. Once the solution will be verified we will publish a new version.

**Comment by sshaforenkoqb** [comment]
Hi haarj,
New version QuickBloxWebRTC 2.8.1 released, problem solved, please check.
