### ISSUE TITLE
Push notifications are not sent to iOS device after regaining internet connection

### ISSUE THREAD

**Issue by huynguyennang-fruitstreet** [QuickBlox/quickblox-ios-sdk#1336]
**New Issue Checklist**

 - [x] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [x] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    | > 13                                    |                                          
Quickblox iOS SDK version      | 2.17.10                                  |
Xcode Version                  | 13.3.1                          |
Repro with our demo sample     |  https://github.com/QuickBlox/quickblox-ios-sdk/tree/master/sample-push-notifications-swift  |

**Did this work before?**
 No

**Expected behavior**
Also when in airplane mode (to emulate loss of network connectivity), a notification were logged in the QB queue, but even after re-gaining network connectivity, the notification doesn’t appear on my phone. 

**Actual behavior**
Receive Push notifications after regaining internet connection

**Steps to reproduce the behavior**

- Turn on airplane mode: 2-3 mins
- Using dashboard send a push notification, it show in Queue below
![Screen Shot 2022-10-17 at 17 47 39](https://user-images.githubusercontent.com/87348098/196158821-9322362b-3c5d-4aa3-a809-f1e9ed332269.png)

- Waiting for 2-3 mins
- Turn off airplane mode: Wifi and cellular is available 
- Don't get this push notification

**Any others comments**
- I try sent with [iOS SDK](https://docs.quickblox.com/docs/ios-push-notifications#send-apns--push-notifications) and [API](https://docs.quickblox.com/reference/create-event), I got the same issue
- Maybe, we send push notification with set `apns-expiration : 0`, Refer [apns-expiration](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/sending_notification_requests_to_apns?language=objc)

**Comment by IlliaChemolosov** [comment]
This is Illia from Quickblox
This issue fixed by the server side.
