### ISSUE TITLE
Update user issue

### ISSUE THREAD

**Issue by iOSAshvin** [QuickBlox/quickblox-ios-sdk#1339]
Documentation says we need to set null in password if we don't want to change it while "Updating user". But, swift doesn't have null operator. So that, it doesn't work.

**Comment by AnkitGabani** [comment]
Hello @iOSAshvin 
Do have demo for Audio video calling and chat?
i will pay brother
gabani7004@gmail.com

Thanks

**Comment by IlliaChemolosov** [comment]
Hello @iOSAshvin ,
This is Illia from Quickblox

You can use `nil` for a swift in this case.
