### ISSUE TITLE
Feature Request: Each chat user should be able to configure automatic push notifications

### ISSUE THREAD

**Issue by madhu014** [QuickBlox/quickblox-ios-sdk#134]
https://quickblox.com/blog/new-feature-push-notifications-for-offline-participants-in-a-group-dialog/

This feature was introduced last year and its not possible to set whether a single user would like to these automatic push notifications. But it is only configurable for the entire app. 

It'll be helpful if these automatic notifications can be configured instead of unsubscribing to the entire QB push notifications. We use notifications for other functionalities but want the automatic push notifications for offline messages to be configurable.

**Comment by soulfly** [comment]
We are working on a feature where you will be able to configure pushes for particular dialog

Will be released soon
