### ISSUE TITLE
Load message Skip value isn't correct.

### ISSUE THREAD

**Issue by haarj** [QuickBlox/quickblox-ios-sdk#1341]
Not sure if this is right but I think the "return" statements in this property should be switched in order to skip the right amount of non-divider messages. 

What's happening is with the current values, the paging of messages going back in time isn't loading the correct amount of messages and isn't showing older messages, where the paging eventually stops. 
https://github.com/QuickBlox/quickblox-ios-sdk/blob/e1f611ff15ff544bab2051a0ddc8e1b8084f7c5f/sample-chat-swift/sample-chat-swift/Components/ChatScreen/DataSource/ChatDataSource.swift#L47

**Comment by haarj** [comment]
By switching the return values, the paging is now seamless and loads the correct "limit" of messages.

**Comment by IlliaChemolosov** [comment]
Hello @haarj,
This is Illia from Quickblox

We appreciate your attention and will take your comments into account. But the main purpose of the sample is to demonstrate how the SDK works. Therefore, here we expect comments specifically about the SDK, not about the samples.
