### ISSUE TITLE
Support for Rich links using LPLinkView

### ISSUE THREAD

**Issue by haarj** [QuickBlox/quickblox-ios-sdk#1350]
No issue here just seeing if you had any suggestions/help to implement and size correctly rich links using Apple's, [LPLinkView](https://developer.apple.com/documentation/linkpresentation/lplinkview) in chats.

**Comment by sshaforenkoqb** [comment]
Hello @haarj I would suggest using [systemLayoutSizeFitting(_:withHorizontalFittingPriority:verticalFittingPriority:)](https://developer.apple.com/documentation/uikit/uiview/1622623-systemlayoutsizefitting) to obtain the optimal size for a View with [LPLinkView](https://developer.apple.com/documentation/linkpresentation/lplinkview).

**Comment by haarj** [comment]
ok thanks @sshaforenkoqb!
