### ISSUE TITLE
Web to iOS call is not Connecting

### ISSUE THREAD

**Issue by RaviGautam** [QuickBlox/quickblox-ios-sdk#1357]
Hi Team,

I am using the following SDKs for iOS-
 pod 'QuickBlox','2.17.4'
 pod 'Quickblox-WebRTC','2.7.5'

I also tried the following latest iOS versions as well but same issue.
QuickBlox (2.19.0)
Quickblox-WebRTC (2.8.1)

And using the following JS SDK for Web-
https://github.com/QuickBlox/quickblox-javascript-sdk/releases/tag/2.12.6

I am calling from Web to iOS and getting an error to set the answer due to one extra parameter coming from the Web i.e. 

` a=extmap-allow-mixed`

I am successfully able to connect call iOS to iOS and iOS to Web but not the Web to iOS

Here is the complete log of the error when accepting the call from the Web to iOS-

`<sdp>v=0
o=- 7659755522196448755 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0
a=extmap-allow-mixed
a=msid-semantic: WMS 95dd650a-07fb-4b2b-8753-964fad49fa0c
m=audio 53805 UDP/TLS/RTP/SAVPF 111 63 103 9 0 8 105 13 110 113 126
c=IN IP4 206.189.91.108
a=rtcp:9 IN IP4 0.0.0.0
a=candidate:2128419428 1 udp 2122260223 192.168.1.9 50718 typ host generation 0 network-id 1 network-cost 50
a=candidate:3325332814 1 udp 1686052607 180.188.224.206 30442 typ srflx raddr 192.168.1.9 rport 50718 generation 0 network-id 1 network-cost 50
a=candidate:1243388 1 tcp 1518280447 192.168.1.9 9 typ host tcptype active generation 0 network-id 1 network-cost 50
a=candidate:3805370878 1 udp 41885695 206.189.91.108 53805 typ relay raddr 180.188.224.206 rport 30442 generation 0 network-id 1 network-cost 50
a=candidate:2619259750 1 udp 25108223 206.189.91.108 56956 typ relay raddr 180.188.224.206 rport 2563 generation 0 network-id 1 network-cost 50
a=ice-ufrag:hlZ2
a=ice-pwd:2qKOHrENlnQ5zoOCllVrZQKI
a=ice-options:trickle
a=fingerprint:sha-256 00:2B:0A:EA:32:78:DD:BE:F3:E6:00:7A:0D:1C:43:AF:0D:0A:2F:C6:F7:25:51:CB:B2:25:54:DB:1E:E4:65:5D
a=setup:actpass
a=mid:0
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
a=sendrecv
a=msid:95dd650a-07fb-4b2b-8753-964fad49fa0c c4bb4e88-a156-4b26-8d63-35156daad3df
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:63 red/48000/2
a=fmtp:63 111/111
a=rtpmap:103 ISAC/16000
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:113 telephone-event/16000
a=rtpmap:126 telephone-event/8000
a=ssrc:1317064716 cname:c6VKzyZCYztvEfyK
a=ssrc:1317064716 msid:95dd650a-07fb-4b2b-8753-964fad49fa0c c4bb4e88-a156-4b26-8d63-35156daad3df
</sdp><moduleIdentifier>WebRTCVideoChat</moduleIdentifier><signalType>call</signalType><platform>web</platform></extraParams></message>
2023-08-11 15:35:42.582 rtc::[Signaling Processor] - Did receive signal: call from: 138186370
2023-08-11 15:35:42.583 rtc::[PCON]<138186370, R:Answer> Create answer
(webrtcsdp.cc:370): Failed to parse: "a=extmap-allow-mixed". Reason: Expects at least 2 fields.
(RTCLogging.mm:31): (RTCSessionDescription.mm:61 -[RTCSessionDescription nativeDescription]): Failed to create session description: Expects at least 2 fields.
line: a=extmap-allow-mixed
2023-08-11 15:35:42.585 rtc::[PCON]<138186370, R:Answer> Set remote session description
2023-08-11 15:35:42.585 rtc::[Connection] Start answer error: Error Domain=org.webrtc.RTCPeerConnection Code=-1 "SessionDescription is NULL." UserInfo={NSLocalizedDescription=SessionDescription is NULL.}`

Any help would be appreciated.

Thanks

**Comment by RaviGautam** [comment]
Hi @VladimirNybozhinsky ,
Thanks for your reply.
I have provided all the details about the platform, versions, and scenarios.

And you mention that the error has all the related information to fix the issue, but there is no provision to set the session description manually, which is not accessible.
Any help would be appreciated.

Thanks

**Comment by VladimirNybozhinsky** [comment]
@RaviGautam Hi!
Have you tried to reproduce the problem on our samples?
[IOS Videochat](https://github.com/QuickBlox/quickblox-ios-sdk/tree/master/sample-videochat-webrtc-swift) and [JS Videochat](https://github.com/QuickBlox/quickblox-javascript-sdk/tree/gh-pages/samples/webrtc).

**Comment by VladimirNybozhinsky** [comment]
I noticed that you are not using the current version of js sdk. Please update the SDK to the latest version.
https://github.com/QuickBlox/quickblox-javascript-sdk/releases/tag/2.15.5

This should solve your problem.
We have fixed this known issue in the current versions of the SDK, as not all platforms support this option yet.

`/**
 * This is to fix error on legacy WebRTC implementations
 * @param {RTCSessionDescriptionInit} description
 */
function _removeExtmapMixedFromSDP(description) {
    if (description &&
        description.sdp &&
        description.sdp.indexOf('\na=extmap-allow-mixed') !== -1) {
        description.sdp = description.sdp
            .split('\n')
            .filter(function (line) {
                return line.trim() !== 'a=extmap-allow-mixed';
            })
            .join('\n');
    }
    return description;
}`

Best regards, Vladimir

**Comment by RaviGautam** [comment]
Thanks @VladimirNybozhinsky,
Sorry, I did not try the samples.
I am already working to update our JS SDK for Web. I will let you know when its done.
Thanks
