### ISSUE TITLE
Getting the notification in testing mode but not in live mode

### ISSUE THREAD

**Issue by manohar-techahead** [QuickBlox/quickblox-ios-sdk#1359]
Whenever I am sending the messages using admin panel in testing mode, I am getting the push notification but whenever I am trying to send it in live mode I am getting the error - "No recipients. At least one user should be subscribed for 'apns' (through SDK or REST API)". Also please let me know if I will get push notifications automatically in case I am offline or not using the app(connected to internet) if I get any message from other user

**Comment by VladimirNybozhinsky** [comment]
@manohar-techahead Hi
This is Vladimir from QuickBlox.

You can get detailed information about setting up push notifications in the [QuickBlocks documentation](https://docs.quickblox.com/docs/ios-push-notifications).

1. Make sure you are using an Apple Push Notification Service (Sandbox & Production) SSL certificate.
2. When building Archive, use Ad Hoc or App Store Connect as needed, but not Development.

Best regards, Vladimir

https://discord.gg/ZWZ3WpYZ9q

**Comment by manohar-techahead** [comment]
@VladimirNybozhinsky  thanks for reply . Also please let me know if I will get push notifications automatically in case I am offline or not using the app(connected to internet) if I get any message from other user or I have to create the events for this

**Comment by VladimirNybozhinsky** [comment]
@manohar-techahead 

Yes, you will receive push notifications automatically if this mode is set (it is set by default) in your application in the admin panel.

![Screenshot 2023-08-22 at 11 32 26](https://github.com/QuickBlox/quickblox-ios-sdk/assets/43746573/c27de0c3-07ad-46fb-9eff-7593c4a2fe2b)

You can get detailed information about setting up push notifications in the [QuickBlox documentation](https://docs.quickblox.com/docs/ios-push-notifications).

You can get an example of using push notifications in your application in our [IOS Chat Sample](https://github.com/QuickBlox/quickblox-ios-sdk/tree/master/sample-chat-swift)

**Comment by manohar-techahead** [comment]
I want to send dialog id in push notification. I am trying to achieve it using this
let event = QBMEvent()
        event.notificationType = .push
        let ids = (users.filter{"\($0)" != "\(Profiles().ID)"})
            event.usersIDs = ids.map{"\($0)"}.joined(separator: ",")
            event.type = .oneShot
            var pushParameters = [String : String]()
            pushParameters["message"] = message
            pushParameters["ios_badge"] = "1"
            pushParameters["ios_sound"] = "app_sound.wav"
            pushParameters["dialog_id"] = dialogId
  but I am not getting this parameter in user info. I am getting this userinfo
  [AnyHashable("aps"): {
    alert = Fgfg;
    badge = 1;
    sound = "app_sound.wav";
}]

**Comment by manohar-techahead** [comment]
Thanks for your prompt response @VladimirNybozhinsky . Issue is resolved now
