### ISSUE TITLE
Request failed: client error (422) on sendVoipPush 

### ISSUE THREAD

**Issue by Maks273** [QuickBlox/quickblox-ios-sdk#1362]
I'm calling from Ukraine to UK and get next. It's working well when calling in Ukraine. Could you help me to figure about what's wrong pls?

   Error reasons:{
    errors =     {
        base =         (
            "No recipients. At least one user should be subscribed for 'apnsvoip' (through SDK or REST API)"
        );
    };
}

Request failed: client error (422)

**Comment by djmckee** [comment]
Yep I have found this issue in inverse too 👍

**Comment by Maks273** [comment]
I got success here
let deviceIdentifier = UIDevice.current.identifierForVendor?.uuidString
        let subscription = QBMSubscription()
        subscription.notificationChannel = chanel
        subscription.deviceUDID = deviceIdentifier
        subscription.deviceToken = token
        QBRequest.createSubscription(subscription, successBlock: { _, _ in
            completion(true)
        }) { errorResponse in
            Crashlytics.crashlytics().log("ERROR createSubscription = \( errorResponse.error?.error?.localizedDescription ?? "")")
            completion(false)
        }

**Comment by IlliaChemolosov** [comment]
Hello @djmckee!

This error indicates that the user receiving the call does not have a subscription for voip push notifications.

In your case, there could be several reasons for this behavior, most likely due to different environments (test or live). It directly depends on the build (develop or production). So, you may have a situation where "develop to develop" or "prod to prod" calls work, but "develop to prod" does not. First and foremost, I recommend checking if you are using builds signed with different certificates.

**Comment by Maks273** [comment]
Героям Слава!

Так, причина з середовищами є! Але помітив, коли телефонував з dev to prod, то цей аккаунт видає таку саму помилку коли телефоную з dev => dev

Тепер протестував 2 акк на деві і все працює, але на test flight ні :( отримую 422 error

**Comment by Maks273** [comment]
@IlliaChemolosov so the issue is when I testing on test flight. Any tips to check what's causing the issue?

**Comment by IlliaChemolosov** [comment]
Hello @Maks273!
Maybe you're currently using a sandbox certificate. I recommend creating a universal certificate and updating it within the QuickBlox admin panel.

**Comment by Maks273** [comment]
@IlliaChemolosov could you send a link to that article pls?

**Comment by IlliaChemolosov** [comment]
@Maks273 https://docs.quickblox.com/docs/ios-push-notifications#generate-a-certificate-signing-request

**Comment by Maks273** [comment]
@IlliaChemolosov do I need to generate aspn cer or it can be voip one?

**Comment by IlliaChemolosov** [comment]
@IlliaChemolosov It varies based on your app's requirements, especially if you need to receive regular pushes, such as when the app is in the background and notifications arrive. Typically, I create a universal certificate that supports both calls and regular messages. However, you can create individual certificates and add them depending on your requirements, our admin panel supports up to 3 certificates.
