### ISSUE TITLE
Request failed: client error (422) on sendVoipPush for specific users 

### ISSUE THREAD

**Issue by harshgrg5** [QuickBlox/quickblox-ios-sdk#1370]
i am calling from iOS to iOS or Android, but for some users i am getting the error "Request failed: client error (422)" while call

**Comment by VladimirNybozhinsky** [comment]
@harshgrg5 Hi!
This is Vladimir from QuickBlox.
To help us with your case we request the following points:

1. QuickBlox iOS SDK version.
2. When did this problem occur?
3. What are the steps to reproduce on our side?
4. Does this problem occur in your code or in our examples?
5. Please provide us with the complete REST + XMPP logs (from Xcode) as an attachment to this ticket in .txt format. There should be QB SDK logs from application launch to request and "wrong" response (error). You can learn how to collect logs here: [Log Collection Guides - QuickBlox Help Center](https://quickblox.kayako.com/article/368-how-can-i-enable-quickblox-logs)

Try to test the problem on our samples, such [IOS Videochat](https://github.com/QuickBlox/quickblox-ios-sdk/tree/master/sample-videochat-webrtc-swift).

Best regards, Vladimir
