### ISSUE TITLE
Video view auto rotation. 

### ISSUE THREAD

**Issue by madhu014** [QuickBlox/quickblox-ios-sdk#139]
For self video view has auto-rotation property to it, and its not possible for the developer to control it. If AVCaptureVideoPreviewLayer is used internally, it should be made public. So that the developer can set it to not rotate when device orientation changes.

**Comment by AndreyMoskvin** [comment]
@Pro100Andrey Any comments?

**Comment by iSevenDays** [comment]
Hello. We are developing a new SDK which will give you more control over customizations and hardware optimizations. Please wait.
