### ISSUE TITLE
Video flick noticed if the user does a video chat in landscape mode

### ISSUE THREAD

**Issue by sudhirnkamath** [QuickBlox/quickblox-ios-sdk#140]
If the video chat app supports only portrait mode and the user attempts to video chat in landscape what happens is, the video chat window is displayed in landscape mode for a while and then flick back to portrait mode if user change the device orientation when video call is in progress

This defect is minor but worth a look!

**Comment by AndreyMoskvin** [comment]
Hi, thanks for reporting issue. This is fixed in our Quickblox WebRTC SDK v2.0. We are going to release it soon.
