### ISSUE TITLE
Multiple UpLoading images 

### ISSUE THREAD

**Issue by ajay2c9** [QuickBlox/quickblox-ios-sdk#142]
HI,
I want to upload  the multiple images like WhatsApp .display the image while uploading.

 Please give suggestions for uploading multiple images like WhatsApp.

**Comment by soulfly** [comment]
You can do it without any problems 

just upload many images in your code 
http://quickblox.com/developers/SimpleSample-chat_users-ios#Send_and_receive_a_message_with_attachment
