### ISSUE TITLE
Problem with createSessionWithSuccessBlock:errorBlock

### ISSUE THREAD

**Issue by blazejchwiecko** [QuickBlox/quickblox-ios-sdk#143]
hello there, I'm trying to implement simple chat in my app and I decided to use quickblox, but I'm having a huge problem with it. After adding all required staff in app delegate, a cannot create session. My app crashes and here is log: 
+[QBRequest createSessionWithSuccessBlock:errorBlock:]: unrecognized selector sent to class 0x1002bb2c0
2015-09-02 16:55:18.965 unstealth.me[1302:312618] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[QBRequest createSessionWithSuccessBlock:errorBlock:]: unrecognized selector sent to class 0x1002bb2c0'
*** First throw call stack:
(0x18488422c 0x1965500e4 0x18488b1e0 0x1848880a8 0x18478a96c 0x10010a94c 0x189372f78 0x18958a654 0x18958d008 0x18958b578 0x18d0bd3c8 0x18483bfc8 0x18483b0d0 0x1848396f4 0x184764f74 0x18936c224 0x189366d94 0x10010bf1c 0x196bfaa08)
libc++abi.dylib: terminating with uncaught exception of type NSExceptionWhat can it be?

**Comment by AndreyMoskvin** [comment]
Which one Quickblox iOS SDK version are using? 
We are managing session on the SDK side so in latest version of SDK we've removed this method.
