### ISSUE TITLE
Dialog can't store additional data

### ISSUE THREAD

**Issue by realloxer** [QuickBlox/quickblox-ios-sdk#144]
I cannot store additional data for chat dialog, I run this code and it is not working now, created dialog always return nil for data property.
newDialog.data = @{@"class_name": @"dialog_data", @"age": @33};
 Can you help me how to fix it, thanks.

**Comment by AndreyMoskvin** [comment]
Hi,

This link will help you - http://quickblox.com/developers/SimpleSample-chat_users-ios#Custom_parameters

**Comment by kondak3** [comment]
Hi 
am also getting same error, 
chatdialog created, but data reponse getting null;

**Comment by soulfly** [comment]
It should work with 2.4.4

http://quickblox.com/developers/IOS#Framework_changelog:
