### ISSUE TITLE
Custom data added for QBChatDialog is not getting saved

### ISSUE THREAD

**Issue by sourcebits-anand** [QuickBlox/quickblox-ios-sdk#145]
CODE: 
QBChatDialog *chatDialog = [QBChatDialog new];
chatDialog.occupantIDs = @[@(4698202), @(4700193)];
chatDialog.type = QBChatDialogTypePrivate;
chatDialog.data = @{@"isMatchMeChat":@(YES)};
[QBRequest createDialog:chatDialog successBlock:^(QBResponse *response, QBChatDialog *createdDialog) {

} errorBlock:^(QBResponse *response) {

}];

RESPONSE:
ID:55e84a54a0eb47855d00123e                      
    Created At:2015-09-03 13:25:40 +0000                      
    Room JID:(null)                      
    name:(null)                      
    photo:(null)                      
    type:3                      
    lastMessage:(null)                      
    lastMessageDate:(null)                      
    occupantIDs:(
    4698202,
    4700193
)                      
    userID:4698202                      
    data:(null)                      
    unreadMessagesCount:0                      
    lastMessageUserID:0

EXPECTED RESULT:
data to be as @{@"isMatchMeChat":@(YES)}

ACTUAL RESULT:
  data:(null)                      

SDK USED:
  "QB-SDK" = "iOS 2.3.0.1";

**Comment by AndreyMoskvin** [comment]
Hi!

This link will help you - http://quickblox.com/developers/SimpleSample-chat_users-ios#Custom_parameters .

**Comment by sourcebits-anand** [comment]
I have created a custom class in admin portal and added below data for a QBChatDialog and still data is null

Screen shot of portal:
http://cl.ly/image/2G2g0J0D0I3g

QBChatDialog *chatDialog = [QBChatDialog new];
chatDialog.occupantIDs = @[@(4698202), @(4698207)];
chatDialog.type = QBChatDialogTypePrivate;
chatDialog.data = @{@"class_name": @"MatchMe", @"IsMatchMeChat": @(YES)};
[QBRequest createDialog:chatDialog successBlock:^(QBResponse *response, QBChatDialog *createdDialog) {

} errorBlock:^(QBResponse *response) {

}];


Response:
    ID:55cd8498535c1217db001d23                      
    Created At:2015-08-14 06:03:04 +0000                      
    Room JID:(null)                      
    name:(null)                      
    photo:(null)                      
    type:3                      
    lastMessage:dfgdfgdfg                      
    lastMessageDate:2015-09-01 10:28:51 +0000                      
    occupantIDs:(
    4698202,
    4698207
)                      
    userID:4698207                      
    data:(null)                      
    unreadMessagesCount:0                      
    lastMessageUserID:4698207

**Comment by AndreyMoskvin** [comment]
Hi!

You still have incorrect format of keys:

Correct key format:
data[class_name] - should contain CustomObjects class name created above
data[field1]
data[...]
data[fieldN]

**Comment by sourcebits-anand** [comment]
Hi,

Am assuming you are pointing to below piece of code.
chatDialog.data = @{@"class_name": @"MatchMe", @"IsMatchMeChat": @(YES)};

Description:
"MatchMe" : This is the custom class name which i have created.
"IsMatchMeChat" : This is the new field which i have added  for "MatchMe" class

Screen shot:
http://cl.ly/image/2G2g0J0D0I3g

As per documentation am providing proper class name(MatchMe) for  "class_name".Am i missing something here?

**Comment by AndreyMoskvin** [comment]
Hi,

The correct format in your case:
chatDialog.data = @{@"data[class_name]": @"MatchMe", @"data[IsMatchMeChat]": @(YES)};

**Comment by sourcebits-anand** [comment]
Hi,

As per documentation, format which you have specified is used in setting the extended request for "dialogsForPage" API not for "createDialog" API.

Documentation:
http://cl.ly/image/051q3n0g0c1C

Note:
I have tried with format which you have specified above,still data field is null.

**Comment by sourcebits-anand** [comment]
Any updates for this issue? Is this valid bug?

**Comment by AndreyMoskvin** [comment]
This issue is fixed in Quickblox iOS SDK 2.4.4.

**Comment by AleksandrKh** [comment]
I get this issue in 2.7.3

**Comment by Raikerian** [comment]
@AleksandrKh please note that there is a specific use of customData for QBChatDialog: http://quickblox.com/developers/SimpleSample-chat_users-ios#Custom_parameters

If this doesn't help please create a separate issue and describe it with the steps provided upon issue creation.

**Comment by mawshd** [comment]
2.16 is not working for custom data
