### ISSUE TITLE
Unable to use -all_load flag with QuickBlox in workspace

### ISSUE THREAD

**Issue by tomkowz** [QuickBlox/quickblox-ios-sdk#150]
I need to use `-all_load` linker flag in my project with integrated QuickBlox. Unfortunately when I use this flag I get errors related to QuickBlox.

> ld: warning: object file (/Users/tomkowz/Workspace/Leeo/LeeoCam/Pods/Quickblox-WebRTC/QuickbloxWebRTC.framework/QuickbloxWebRTC(QBSoundRouter.o)) was built for newer iOS version (8.1) than being linked (7.0)
  ld: warning: object file (/Users/tomkowz/Workspace/Leeo/LeeoCam/Pods/Quickblox-WebRTC/QuickbloxWebRTC.framework/QuickbloxWebRTC(QBRTCSessionDescription.o)) was built for newer iOS version (8.1) than being linked (7.0)
  ld: warning: object file (/Users/tomkowz/Workspace/Leeo/LeeoCam/Pods/Quickblox-WebRTC/QuickbloxWebRTC.framework/QuickbloxWebRTC(QBBackgroundTimer.o)) was built for newer iOS version (8.1) than being linked (7.0)
  ld: warning: object file (/Users/tomkowz/Workspace/Leeo/LeeoCam/Pods/Quickblox-WebRTC/QuickbloxWebRTC.framework/QuickbloxWebRTC(QBGLVideoView.o)) was built for newer iOS version (8.1) than being linked (7.0)
  ld: warning: object file (/Users/tomkowz/Workspace/Leeo/LeeoCam/Pods/Quickblox-WebRTC/QuickbloxWebRTC.framework/QuickbloxWebRTC(QBRTCUtils.o)) was built for newer iOS version (8.1) than being linked (7.0)
  ld: warning: object file (/Users/tomkowz/Workspace/Leeo/LeeoCam/Pods/Quickblox-WebRTC/QuickbloxWebRTC.framework/QuickbloxWebRTC(QBRTCVideoTrack.o)) was built for newer iOS version (8.1) than being linked (7.0)
  ld: warning: object file (/Users/tomkowz/Workspace/Leeo/LeeoCam/Pods/Quickblox-WebRTC/QuickbloxWebRTC.framework/QuickbloxWebRTC(QBSignalChannel.o)) was built for newer iOS version (8.1) than being linked (7.0)
  ld: warning: object file (/Users/tomkowz/Workspace/Leeo/LeeoCam/Pods/Quickblox-WebRTC/QuickbloxWebRTC.framework/QuickbloxWebRTC(QBDisplayLinkTimer.o)) was built for newer iOS version (8.1) than being linked (7.0)
  ld: warning: object file (/Users/tomkowz/Workspace/Leeo/LeeoCam/Pods/Quickblox-WebRTC/QuickbloxWebRTC.framework/QuickbloxWebRTC(QBSignalingSpec.o)) was built for newer iOS version (8.1) than being linked (7.0)
  ld: warning: object file (/Users/tomkowz/Workspace/Leeo/LeeoCam/Pods/Quickblox-WebRTC/QuickbloxWebRTC.framework/QuickbloxWebRTC(QBRTCSignalProcessor.o)) was built for newer iOS version (8.1) than being linked (7.0)
  ld: warning: object file (/Users/tomkowz/Workspace/Leeo/LeeoCam/Pods/Quickblox-WebRTC/QuickbloxWebRTC.framework/QuickbloxWebRTC(QBRTCClient.o)) was built for newer iOS version (8.1) than being linked (7.0)
  ld: warning: object file (/Users/tomkowz/Workspace/Leeo/LeeoCam/Pods/Quickblox-WebRTC/QuickbloxWebRTC.framework/QuickbloxWebRTC(QBRTCConfig.o)) was built for newer iOS version (8.1) than being linked (7.0)
  ld: warning: object file (/Users/tomkowz/Workspace/Leeo/LeeoCam/Pods/Quickblox-WebRTC/QuickbloxWebRTC.framework/QuickbloxWebRTC(QBRTCSession.o)) was built for newer iOS version (8.1) than being linked (7.0)
  ld: warning: object file (/Users/tomkowz/Workspace/Leeo/LeeoCam/Pods/Quickblox-WebRTC/QuickbloxWebRTC.framework/QuickbloxWebRTC(QBPeerChannel.o)) was built for newer iOS version (8.1) than being linked (7.0)
  ld: warning: object file (/Users/tomkowz/Workspace/Leeo/LeeoCam/Pods/Quickblox-WebRTC/QuickbloxWebRTC.framework/QuickbloxWebRTC(QBICEServer.o)) was built for newer iOS version (8.1) than being linked (7.0)
  ld: warning: object file (/Users/tomkowz/Workspace/Leeo/LeeoCam/Pods/Quickblox-WebRTC/QuickbloxWebRTC.framework/QuickbloxWebRTC(device_vers.o)) was built for newer iOS version (8.1) than being linked (7.0)
  Undefined symbols for architecture armv7:
    "_getauxval", referenced from:
        _OPENSSL_cpuid_setup in QuickbloxWebRTC(boringssl.cpu-arm.o)
        _OPENSSL_cpuid_setup in QuickbloxWebRTC(boringssl.cpu-arm.o)
    "_iconv", referenced from:
        _mem_cd_iconv in Quickblox(striconv.o)
        _str_cd_iconv in Quickblox(striconv.o)
       (maybe you meant: _str_iconv, _mem_cd_iconv , _str_cd_iconv )
    "_iconv_close", referenced from:
        _str_iconv in Quickblox(striconv.o)
    "_iconv_open", referenced from:
        _str_iconv in Quickblox(striconv.o)
  ld: symbol(s) not found for architecture armv7
  clang: error: linker command failed with exit code 1 (use -v to see invocation)

I see `_iconv*` things are from `libiconv` but I don't know what should I import to make `_getauxval` working. Could you help me with this, please?

Thank you in advance!

**Comment by AndreyMoskvin** [comment]
@Pro100Andrey Any comments on this?
