### ISSUE TITLE
"unread_messages_count" is not getting proper values for "QBChatDialogTypePublicGroup" type chatdialogs

### ISSUE THREAD

**Issue by sourcebits-anand** [QuickBlox/quickblox-ios-sdk#152]
Hello,

Event though QBChatDialogTypePublicGroup  type chat dialog is having unread messages, "unread_messages_count" is always "0" (API used : dialogsForPage:successBlock:errorBlock)

Request params for  dialogsForPage:successBlock:errorBlock: API
{
    limit = 10;
    "type[in]" = 1;
}

**Comment by sourcebits-anand** [comment]
Hello,

Its been more than 12 days.Any updates for this issue? 
Please let me know Is this valid bug or am i missing some thing?

**Comment by soulfly** [comment]
The 'unread_messages_count' doesn't work for 'QBChatDialogTypePublicGroup'

only for private chat and private group chat

The reason for this is that in public group chat there is no 'occupants_ids' field

**Comment by sourcebits-anand** [comment]
ok,For my application requirement i need to display unread chat count,which means i need to use QBChatDialogTypeGroup instead of QBChatDialogTypePublicGroup.But is there any restriction on number of occupants for "QBChatDialogTypeGroup" chat dialog?

**Comment by soulfly** [comment]
No limits here, you can add as many as you need
