### ISSUE TITLE
QMServices.h not found

### ISSUE THREAD

**Issue by alvinvarghese** [QuickBlox/quickblox-ios-sdk#157]
Downloaded from GitHub, ran the project. And build failed by this message, and i could see that QMServices.h does not exists, as in it is there but it is not accessible, showing in red color. What i should i do now ?

**Comment by Raikerian** [comment]
Hi,

You need to clone submodules.
This link should help you: https://github.com/QuickBlox/quickblox-ios-sdk#clone-submodules

**Comment by alvinvarghese** [comment]
Thanks for the info, Let me take a look at that.

**Comment by rogerluan** [comment]
Did it and it worked. Cloned using SourceTree.

BUT, why is it that way? When I wanna read the source code of something, and/or download to test the example on device, I like to simply download the zip, and not clone. Cloning takes way longer, and requires more and interactions. But now it only "supports" cloning, and not downloading? :cry:

**Comment by soulfly** [comment]
@rogerluan

we are working on it now, true 'downloading' will be supported in a week

thanks

**Comment by rogerluan** [comment]
Yay thanks @soulfly :D
