### ISSUE TITLE
Deleted 1:1 chatDialog is appearing in "dialogsForPage" response

### ISSUE THREAD

**Issue by sourcebits-anand** [QuickBlox/quickblox-ios-sdk#159]
Hello,

am  trying to delete a 1:1 dialog using below API.

     + (QBRequest *)deleteDialogWithID:(NSString *)dialogID successBlock:(void(^)(QBResponse *responce))successBlock errorBlock:(QBRequestErrorBlock)errorBlock;

And after am trying to get list of all dialogs 1:1 and group chats dialogs
 using below piece of code,But am getting deleted chat dialogs as well here.

    [QBRequest dialogsForPage:pageDialogs extendedRequest:@{@"type[in]":@"2,3"}  successBlock:^(QBResponse *response, NSArray *dialogObjects, NSSet *dialogsUsersIDs,   QBResponsePage *page)
    {
    
    }errorBlock:^(QBResponse *response){
     
    }
   

Expected response:
Deleted 1:1 chat dialogs should not appear in  dialogsForPage response.

Note:
This functionality works fine for group chats.

**Comment by soulfly** [comment]
Hi Anand, 

QA team has confirmed the issue, will roll out the fix soon

thank you
