### ISSUE TITLE
How to delete the users from the Groupchat

### ISSUE THREAD

**Issue by ajay2c9** [QuickBlox/quickblox-ios-sdk#163]
I create a Group chat With 10 users. After Few Chatting, i want to delete the 3 users and their messages. how to delete 3 users from Group Chat and how to delete the messages of deleted users.

**Comment by soulfly** [comment]
Here is how you can do it

http://quickblox.com/developers/SimpleSample-chat_users-ios#Update_group_dialog

use 'pull_all' filter

**Comment by ajay2c9** [comment]
Thank you for giving suggestion. I updated the QuickBlox SDK using pods. For createSessionWithSuccessBlock its shows warning i removed createSessionWithSuccessBlock. After removing  this chat is not working .When I used createSessionWithSuccessBlock chat is working. 

I downloaded  the latest chat sample and run in the simulator its not working for me.

Please give suggestions.
Thank you

**Comment by soulfly** [comment]
Yes, now SDK manages session by itself so you don't need to call it .

Which error do you receive?

**Comment by ajay2c9** [comment]
it shows this message like this -[QBChat(Deprecated) sendChatMessage:toRoom:] -> return. You have to be logged in in order to use Chat API  .I already using this method [[QBChat instance] loginWithUser:user]; for login in the chat.

**Comment by AndreyMoskvin** [comment]
You are not connected in Chat that's why you are not able to send message.
