### ISSUE TITLE
How to identify the user is in the Group chat or not  while chatting.

### ISSUE THREAD

**Issue by ajay2c9** [QuickBlox/quickblox-ios-sdk#170]
Hi,

Some one created a Group Chat having 5 members  in the middle of the Chatting Admin removed One of the user while he is in Chatting . how to identify that the user is in the dialog or not .

Please give suggestions.

**Comment by AndreyMoskvin** [comment]
Send "notification" messages to notify about updates in group chat. This mechanism is implemented is sample-chat and sample-chat-swift.
