### ISSUE TITLE
How to operate the push notification to a every particular Chat dialog?

### ISSUE THREAD

**Issue by ajay2c9** [QuickBlox/quickblox-ios-sdk#172]
Hi,
I have 10 group chat dialogs each have 8 members. I have a situation like particularly 3 users want to stop receiving push notification (but they have to see chatting) for a particular Chat dialog.  and  want to receive for others Chat dialogs. But remaining persons receive the notifications as usually for that chat.

Please Give Suggestions .

Thank you

**Comment by Raikerian** [comment]
Duplicate https://github.com/QuickBlox/quickblox-ios-sdk/issues/177
