### ISSUE TITLE
Issue with Swift Example

### ISSUE THREAD

**Issue by sporelab** [QuickBlox/quickblox-ios-sdk#173]
Photos selection does not show when keyboard is showing. See screenshots attached. I am assuming they are just hidden.

![simulator screen shot oct 4 2015 11 50 22 pm](https://cloud.githubusercontent.com/assets/6438514/10273252/0719464a-6af3-11e5-9083-c248c3ef7e09.png)

![simulator screen shot oct 4 2015 11 50 35 pm](https://cloud.githubusercontent.com/assets/6438514/10273254/0c097e36-6af3-11e5-9c8e-2eb062a81072.png)

**Comment by AndreyMoskvin** [comment]
Fix available on CocoaPods - QMChatViewController 0.2.4
