### ISSUE TITLE
 How to stop receiving push notifications for all chat messages from all 1-1 chat rooms and group chat rooms?

### ISSUE THREAD

**Issue by ajay2c9** [QuickBlox/quickblox-ios-sdk#175]
I had switch for chat notifications in my app .If i turn on the switch i should receive the push notifications for any chat room. If i turn of the switch i shouldn't receive push notifications. How to handle this?
Thank you

**Comment by Raikerian** [comment]
Duplicate https://github.com/QuickBlox/quickblox-ios-sdk/issues/177
