### ISSUE TITLE
How to handle push notifications for 1-1 chat room and Group Chat room?

### ISSUE THREAD

**Issue by ajay2c9** [QuickBlox/quickblox-ios-sdk#177]
How to switch ON and OFF the Push notifications for 1-1 chat room and Group Chat room?
what i mean is 
For Example:
I had a button for every room in my iOS app, if i turn it on, then only i should receive the notifications, it it is turn off, then i shouldn’t receive the notifications for that room.

These scenarios will be possible or not? IF possible , How?

**Comment by AndreyMoskvin** [comment]
Hi,

With the current version of SDK it is not possible, in next version of SDK we are going to add this feature.

**Comment by Raikerian** [comment]
In order to receive updates about Quickblox new features, follow our [blog here](http://quickblox.com/blog/).

We are closing this thread for tracking purposes.
If you have any other questions please create separate issue.
