### ISSUE TITLE
QBRequest.logInWithUserLogin error

### ISSUE THREAD

**Issue by georgi3web** [QuickBlox/quickblox-ios-sdk#179]
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]'

while executing:

QBRequest.logInWithUserLogin(<#login: String!#>, password: <#String!#>, successBlock: <#((QBResponse!, QBUUser!) -> Void)!##(QBResponse!, QBUUser!) -> Void#>, errorBlock: <#QBRequestErrorBlock!##(QBResponse!) -> Void#>)

**Comment by AndreyMoskvin** [comment]
Fixed in 2.5 SDK.

**Comment by KrutarthPatel0825** [comment]
same issue
