### ISSUE TITLE
ConnectionFailedWithUser with SessionDescription is NULL Error in Video Call

### ISSUE THREAD

**Issue by kshitijgaur-kiwi** [QuickBlox/quickblox-ios-sdk#181]
Issue:
After accepting the call following error occurs which terminates the video call.

Error logs:
Renegotiation needed. userID - 6100877
2015-10-14 18:40:25.969 Globechat[312:5603] Error(-1): Error Domain=RTCSDPError Code=-1 "The operation couldn’t be completed. (RTCSDPError error -1.)" UserInfo=0x17066eb00 {error=SessionDescription is NULL.}

Description:
As soon as I accept the call, didReceiveLocalVideoTrack method gets called and then connectionFailedWithUser delegate method gets called and I get "SessionDescription is NULL" error in logs. I am using Quicblox sdk 2.4.5 and Quickblox-WebRTC 1.0.6 .

**Comment by AndreyMoskvin** [comment]
@iSevenDays @Pro100Andrey Any comments?

**Comment by iSevenDays** [comment]
@kshitijgaur-kiwi
Hello. Please provide us with full log from both sides from our sample-video chat.

**Comment by iSevenDays** [comment]
Issue is closed due to no response.

Also if you still have problems please update to the newest version QuickbloxWebRTC SDK 2.1.1.

**Comment by neeru-thakur** [comment]
Getting same issue after accepting Audio Call,.

**Comment by neeru-thakur** [comment]
Any idea how to resolve this and what is the reason of getting this error. I am using  QuickBlox (2.8) and Quickblox-WebRTC (2.2) SDKS

**Comment by Haribabu-Appit** [comment]
Getting same issue after accepting video call. Call is initiated from javascript to ios. I'm using below ios sdk versions. Anybody has solution this

QuickBlox (2.17.11)
 Quickblox-WebRTC (2.7.6):

**Comment by Haribabu-Appit** [comment]
Please ignore my above comments. It's working.

**Comment by QB-nikolay-zolotarov** [comment]
@Haribabu-Appit how did you solve the issue? It will be useful for others
