### ISSUE TITLE
How to update dialog unread message count after reading messages.

### ISSUE THREAD

**Issue by ajay2c9** [QuickBlox/quickblox-ios-sdk#182]
Hi,
how to update the unread messages count after reading messages. i am using the SDK 2.4 before version.

**Comment by Raikerian** [comment]
Hi,

Unread messages count should be updated after you read messages. If its not, please check if you are reading messages in a correct way. Our sample-chat is providing such functionality, you can look at method "- (void)readMessages: forDialogID:" in ChatViewController.
