### ISSUE TITLE
Crash with Swift in 

### ISSUE THREAD

**Issue by fstephany** [QuickBlox/quickblox-ios-sdk#183]
After updating to SDK 2.4.5, calling

    let successBlock = { (response: QBResponse, dialogObjects: [QBChatDialog]?, dialogsUsersIDs: Set<String>?, page: QBResponsePage?) -> Void in
            //do something
        }

    QBRequest.dialogsForPage(
            page,
            extendedRequest: extendedRequest,
            successBlock: successBlock,
            errorBlock: errorBlock)

crashes at Runtime with `swift_bridgeNonVerbatimFromObjectiveC`(`"value type is not bridged to Objective-C"`).

If I pass `nil` instead of the `successBlock` it doesn't crash.

Any hint ?

**Comment by Jak9i** [comment]
Got the same problem

**Comment by AndreyMoskvin** [comment]
Hi!

Thank you for reporting issues. We will investigate it as soon as possible.

**Comment by AndreyMoskvin** [comment]
Hi, we fixed this issue, fix will be available in Quickblox SDK 2.5.

**Comment by fstephany** [comment]
Thanks !

**Comment by rajanshahsa** [comment]
@Berk0ld  Hello,

I am using quickblox v2.5 for video call in Swift(iOS). I am getting same error in v2.5 as well in the "**QBRTCManager.didReceiveNewSession**".

Can you please help me out in this?

Thanks in advance.

**Comment by Raikerian** [comment]
@rajanshahsa please create separate issue and attach full logs using gist.github.com
