### ISSUE TITLE
Retrieve list of dialogs return error 422

### ISSUE THREAD

**Issue by ahmadmd** [QuickBlox/quickblox-ios-sdk#186]
I am trying to get list of dialoges after a user login. I can signup and signin user even i can send message to other users
here is my code for list of dialoges

QBResponsePage *page = [QBResponsePage responsePageWithLimit:20];
[QBRequest dialogsForPage:page extendedRequest:nil successBlock:^(QBResponse *response, NSArray *dialogObjects, NSSet *dialogsUsersIDs, QBResponsePage *page) {
NSLog(@"response = %@\n\n",response);
     NSLog(@"-------\ndialogObjects = %@",dialogObjects);
} errorBlock:^(QBResponse *response) {
    NSLog(@"error is %@",response);
}];

it gives me error 422. console log is

[QBCore] Response headers: {
"Access-Control-Allow-Origin" = "*";
"Cache-Control" = "no-cache";
Connection = "keep-alive";
"Content-Length" = 45;
"Content-Type" = "application/json; charset=utf-8";
Date = "Wed, 28 Oct 2015 14:07:30 GMT";
"QB-Token-ExpirationDate" = "2015-10-28 16:07:30 UTC";
"QuickBlox-REST-API-Version" = "0.1.1";
Server = "nginx/1.6.2";
Status = "422 Unprocessable Entity";
"X-Rack-Cache" = miss;
"X-Request-Id" = 560260a8bf98da9b7c3d8ba133c8d7a7;
"X-Runtime" = "0.007757";
"X-UA-Compatible" = "IE=Edge,chrome=1";

**Comment by AndreyMoskvin** [comment]
Hi!

Could you please send full log with exact error message?
