### ISSUE TITLE
value type is not bridged to Objective-C

### ISSUE THREAD

**Issue by inglucifer83** [QuickBlox/quickblox-ios-sdk#187]
When trying to get list of dialogs other than Public Groups (i.e Private and Groups), an exception is thrown from libswiftCore.dylib`swift_bridgeNonVerbatimFromObjectiveC: telling me that "value type is not bridged to Objective-C". I'm using the same method from my iOS SDK to retrieve dialogs. For Public Groups  the call is QBRequest.dialogsForPage(QBResponsePage(limit: 100), extendedRequest: ["type":"1"]... for Private and Groups the call is QBRequest.dialogsForPage(QBResponsePage(limit: 100), extendedRequest: ["type[in]":"2,3"]...

**Comment by AndreyMoskvin** [comment]
Hi! This issue is already fixed. This fix will be available in Quickblox iOS SDK 2.5.
