### ISSUE TITLE
Call gets attended automatically

### ISSUE THREAD

**Issue by murugaprabum** [QuickBlox/quickblox-ios-sdk#188]
I am trying out the VideoChat feature in iOS. Some times the Video call gets attended automatically without user pressing the Accept call button. I am not even shown incoming call is coming but the call is attended automatically and I don't see the other side video but hear their audio. 

I went through your sample code to find out why this happens. Check out https://github.com/QuickBlox/quickblox-ios-sdk/blob/master/sample-videochat-webrtc/sample-videochat-webrtc/Classes/CallManager/CallManager.m#L118 . 
@QuickBlox-team Why is the call being accepted automatically when the iOS application is in background state?

**Comment by iSevenDays** [comment]
Hello

You can see there a comment that it is only to test background mode.

If you don't want that behavior, you can remove that line.

**Comment by murugaprabum** [comment]
@iSevenDays What's the rationale behind that? There is no indication to the attender of the call that the call is attended.

**Comment by iSevenDays** [comment]
There is no ability to show any alerts in background mode, so we simply do accept a call. If you do not need that behavior, you are welcome to change everything you need in sample.
