### ISSUE TITLE
Login with social without ACAccount

### ISSUE THREAD

**Issue by vvvimal** [QuickBlox/quickblox-ios-sdk#190]
If the user has not configured his facebook and twitter account under settings of his phone, then how can the 
-- loginWithSocialProvider: accessToken: accessTokenSecret:  
method work, is there anyway the user can be shown the facebook/twitter login screen as where he can enter his credentials and login.

This was possible previously(in 2.3 SDK) via createSessionWithExtendedParameters: and loginWithSocialProvider: scope: methods

**Comment by AndreyMoskvin** [comment]
Hi!

You will need to use [Facebook iOS SDK](https://developers.facebook.com/docs/facebook-login/ios/advanced) to get access token and secret.

The same for twitter - [Twitter iOS SDK](https://docs.fabric.io/ios/twitter/authentication.html).
