### ISSUE TITLE
QBSession documentation

### ISSUE THREAD

**Issue by eagle-dan1349** [QuickBlox/quickblox-ios-sdk#195]
This class severely lacks documentation. To be specific, there's just NO documentation.
I have to search for answers through your code, and, well, it's not self-explaining.

**Comment by AndreyMoskvin** [comment]
Hi,

Thanks for reporting issue, we will add documentation in next release. Do you have questions about this class?

**Comment by eagle-dan1349** [comment]
Well, yes, I have questions on it's behavior:
+currentSession is most likely singleton, my question is, does it survive between application launches, or should I better store it myself?

**Comment by AndreyMoskvin** [comment]
It is a singleton and it is automatically restored between application launches. You don't need to save it yourself.
