### ISSUE TITLE
QBRequest.createMessage does not replaces + sign with " " for group chat.

### ISSUE THREAD

**Issue by Anurag15990** [QuickBlox/quickblox-ios-sdk#198]
Hi, 

When i try to create a message for a phone number with the country code as prefix e.g. +18494838494, The create message function removes the "+" sign and replaces it with a " " space character. Please can anyone let me know how i can retain the "+" sign. As per my observation, only that character is replaced. 

Looking to hear from you on this issue. 

Thanks & Regards,

Anurag

**Comment by AndreyMoskvin** [comment]
Hi! 

Thanks for reporting issue, we will investigate it.

**Comment by AndreyMoskvin** [comment]
@Raikerian Could you please take a look?

**Comment by AndreyMoskvin** [comment]
The fastest fix on the client side is to use - stringByAddingPercentEscapesUsingEncoding: for the message text.

We are going to fix this issue on server, but I can't provide ETA for this now.

**Comment by Anurag15990** [comment]
Okay cool. Please let me know when you guys add the fix.

Thanks & Regards,
Anurag Agnihotri

**Comment by soulfly** [comment]
Hi there,

could you please try again, our team deployed a patch to the backend 
and get back to us

thank you
