### ISSUE TITLE
library not found for -lBolts

### ISSUE THREAD

**Issue by mobilemindtec** [QuickBlox/quickblox-ios-sdk#201]
Hi, I'm following the instructions, but the build not work. This error is showed: 

ld: warning: directory not found for option '-F/Users/ricardobocchi/sources/repository/quickblox-ios-sdk/sample-chat/Pods/../External'
ld: library not found for -lBolts
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by Raikerian** [comment]
Hi,

make sure you are opening .xworkspace, if yes, then try to update pods with 'pod update' command.

**Comment by mobilemindtec** [comment]
Now it work! I don't know very well Cocoapods.. Thanks!
