### ISSUE TITLE
QBChat -disconnectWithCompletionBlock:

### ISSUE THREAD

**Issue by eagle-dan1349** [QuickBlox/quickblox-ios-sdk#203]
Completion block is called ONLY if error has occurred.
Is the method supposed to behave this counter-obvious way?
If yes, then it's more convince to call it -disconnectWithErrorBlock:
if no, then it's convince to call completion block if everything went fine

**Comment by Raikerian** [comment]
Hi,

Thank you for reporting the issue, it was confirmed and fixed. This fix will be available in next Quickblox iOS SDK release.

**Comment by eagle-dan1349** [comment]
Thank you for reply, I'll adapt my code for it

**Comment by eagle-dan1349** [comment]
Guys, in which release this one is fixed?

**Comment by Raikerian** [comment]
Hi,

It was fixed in version 2.6.
