### ISSUE TITLE
QBRequest documentation

### ISSUE THREAD

**Issue by eagle-dan1349** [QuickBlox/quickblox-ios-sdk#204]
The method +dialogsForPage:extendedRequest:successBlock:errorBlock: accepts additional parameters as extendedRequest dictionary.
List of available parameters will look just great as 'extern NSString* const's 
I'm opening this issue due to inconsistency between documentation and code examples:
http://quickblox.com/developers/SimpleSample-chat_users-ios#Filters this section lists available filters, while real code uses some different filter: 'updated_at[gt]' that is not listed in web documentation.

Thank you in advance

**Comment by soulfly** [comment]
Thanks
added updated_at to the list of fields
