### ISSUE TITLE
Using your API can we user our database for USER mangement.

### ISSUE THREAD

**Issue by anil03** [QuickBlox/quickblox-ios-sdk#205]
hi I am develping one video app for education and medical.
I want you your QB API for calling purpose.
As i read you documentation we need to create and account to get ID and password.
Your also halding the USERs. 
Can we do user management to custom server i mean  AMAZON server.

**Comment by AndreyMoskvin** [comment]
Hi,

Only by using custom server - no. But you can connect QB user with custom server user by 'externaUserID' property of QBUUser.

**Comment by iSevenDays** [comment]
Hi,

We haven't heard back from you in a few days, so we are marking this post as Closed for tracking purposes. If you're still experiencing this issue, please provide us with additional information.
