### ISSUE TITLE
How to save the device tokens for every user who is registered in same device

### ISSUE THREAD

**Issue by ajay2c9** [QuickBlox/quickblox-ios-sdk#207]
hi,

I am using quickblox registration in background.  I make 4 registrations in same device, while check in the quickblox server only few token ids are saved . how to save the device UDID of every user registered in the same device or different devices.
Thank you

**Comment by soulfly** [comment]
If multiple users use the same devices for pushes then only the latest will be receiving pushes

Quickblox automatically unsubscribes previous users form this particular device

**Comment by ajay2c9** [comment]
Then suggest me how to save the device UDID when the user login in to the app.

**Comment by AndreyMoskvin** [comment]
What is the reason of saving device UDID?

**Comment by ajay2c9** [comment]
We are updating the device UDID when the user in login in our app. For the Chat Push notification, i want to update the device UDID when the user login to the app.

Please Give suggestion for updating the device UDID.

**Comment by ajay2c9** [comment]
While registration the device UDID are saved in push notifications-->subscriptions in admin panel. while Login the device UDID of the user is updated in there or inserted.

Is there any possibilities to the save the device UDID in subscriptions while login.

Please Give suggestions.
Thank you

**Comment by Raikerian** [comment]
Answered here: https://github.com/QuickBlox/quickblox-ios-sdk/issues/231

This feature is in progress.
