### ISSUE TITLE
How to Video Chat feature into my Own App

### ISSUE THREAD

**Issue by anil03** [QuickBlox/quickblox-ios-sdk#210]
Hi All
Thanks for creating such elegant feature.

I am developing app which support video calling features. I am trying to get your API into my application.
I foolow the tutorial of Getting Application ID, Secret KEY etc. I create some users into QB account too.
When i am replacing my ID into Sample Applcaion it always shows 10 USERs So I am not getting the IDEA that how to fetch My USER from QB acct into my applcation. How to integrate your all API s into our application. Please suggest i am little confused.

**Comment by iSevenDays** [comment]
Our 10 users were created in our QB sample application admin panel.

So if you want to replace our credentials with yours, you should do the following:

1. Create an account on Quickblox
2. Replace our credentials with yours
3. Create 10 users in your admin panel, preferably with the same password
4. Change plist that is located in Project_Dir/Resources/Plists/Users
There you can find login-fullName-ID items which you need to replace with yours created in step 3
5. Class UsersDataSource -loadUsersWithList is responsible for loading users from plist

Now I think you have all needed information to test QuickbloxWebRTC

thanks!

**Comment by anil03** [comment]
Thanks for support.

As i created account into QB and i updated Account Key and others keys.
As i want make it dynamic not static. I mean i want to make app like Skype. when user logged in and he makes call that user which in his account he can call him provided user should also online.
So i do not want to use your plists.

**Comment by iSevenDays** [comment]
Then you are welcome to use our Q-municate open source application that has an ability to register users  http://q-municate.com
Thanks!
