### ISSUE TITLE
Don't have audio output on one side of a call when current route is QBRTCSoundRouteSpeaker

### ISSUE THREAD

**Issue by OgrePet** [QuickBlox/quickblox-ios-sdk#211]
Steps to reproduce
1. Make a video call from device A (iPhone with ios9) to device B(iPad with ios9). Also tried it on two iPhones
2. Set currentSoundRoute to QBRTCSoundRouteSpeaker, on both devices (it also reproduces on quikblox webrtc sample, without explicit route set)
3. See that on device A speaker works correctly, and on device B it isn't working
4. If you change sound route on device A to receiver, it starts work fine on device B.

Expected Result:
Sound output through speaker should work on both devices.

**Comment by iSevenDays** [comment]
Hello!
1. Could you please attach logs? 
2. Please ensure that neither speaker nor headset works fine on both devices

**Comment by iSevenDays** [comment]
Hi,

We haven't heard back from you in a few days, so we are marking this post as Closed for tracking purposes. If you're still experiencing this issue, please provide us with additional information.
