### ISSUE TITLE
bitcode ios9.1

### ISSUE THREAD

**Issue by gask** [QuickBlox/quickblox-ios-sdk#217]
Hey there, is this issue being taken care of? I want to build my app with bitcode activated.
Downloaded the latest SDK and I still can't build with bitcode.

ld: bitcode bundle could not be generated because '/Users/gbferraro/Documents/Djengo/djengo-ios/djengo-ios/djengo-ios/Quickblox.framework/Quickblox(QBResponse.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Thanks in advance
Giovanni.

**Comment by Raikerian** [comment]
Hi,

We have just tested and enabled bitcode in our [Q-municate](https://github.com/QuickBlox/q-municate-ios/tree/development) project (see development branch) which is using our latest Quickblox SDK and latest Quickblox WebRTC SDK, and it's working correctly for us. Please try to clean your project and verify that version of your SDK is the latest one.

Also, which way are you using to install SDK? Cocoapods or github download?

**Comment by gask** [comment]
Hey there Raikerian,
I downloaded the SDK via github.
Also, when I run the app with the development config, it's working ok.
But when I try to ARCHIVE it, with the release config, this error shows.

**Comment by AndreyMoskvin** [comment]
Hi,

We've finally found the issue, will drop a fix in next release.

**Comment by Raikerian** [comment]
Support for bitcode added in 2.6.0.2.

**Comment by LeeroyDing** [comment]
Is bitcode supported in the WebRTC framework?

**Comment by Pro100Andrey** [comment]
Hi @LeeroyDing, for now no, but we are considering to do it in a near future

**Comment by GiacomoSilli** [comment]
I would like to integrate the quickblox ios sdk with my app that requires bitocode enabled.
How can I do to solve? Quickblox wants bitcode disabled
