### ISSUE TITLE
Duplicate symbols when using in the same app with Twilio SDK

### ISSUE THREAD

**Issue by vvrinne** [QuickBlox/quickblox-ios-sdk#226]
We are developing an app for a client where we have the need to combine video calls with outgoing telephone calls (audio only). To implement this we have been evaluating QuickBlox and Twilio. My issue is that if I add both QuickBlox and Twilio pods to the same XCode project I get a ton of duplicate symbols from libssl.a and libcrypto.a. I guess both libraries are linking to the same libraries.

Since Twilio sdk is distributed as just the static library I can just delete libssll.a and libcrypto.a from that but then I get several missing symbols from Twilio. I am guessing this has to do with Quickblox linking to a slightly different version of libssl and libcrypto.

Are you aware of any method of solving this other than acquiring a version of either Quickblox SDK or Twilio SDK with prefixed symbols?

**Comment by Raikerian** [comment]
Hi!

We are also distributing QuickbloxWebRTC as a static library.
Can you please tell us the reason using both QuickbloxWebRTC and Twilio SDK for calls.

**Comment by Raikerian** [comment]
We haven't received any updates on this issue from you. If you still have any questions please create new issue.
