### ISSUE TITLE
how to update the device UDID when the single user login in different devices.

### ISSUE THREAD

**Issue by ajay2c9** [QuickBlox/quickblox-ios-sdk#231]
Hi,
I am using the QuickBlox Chat sdk in my app. When a user is login in different devices, I want to update the device UDID for receiving push notification in last device user logged in.If a single user has two or more  accounts in the same device how to handle Chat Push notifications for all the accounts. and how to update the  device UDID.

Please Give Suggestions.

Thank you

**Comment by Raikerian** [comment]
Hi!

This feature is in progress, but for now it is only possible to receive push notifications for the latest device you subscribed on.

**Comment by ajay2c9** [comment]
Thank you.

**Comment by Raikerian** [comment]
In order to receive updates about Quickblox new features, follow our [blog here](http://quickblox.com/blog/).

We are closing this thread for tracking purposes.
If you have any other questions please create separate issue.

**Comment by phamminhvu** [comment]
Hi everybody,

This feature is in progress, but for now it is only possible to receive push notifications for the latest device you subscribed on.

Anyone can tell me the feature already implemented or not. and which's version then I can use to solve this issue

Thanks for your support!

**Comment by shoaibHassanAttech** [comment]
QBRequest.subscriptions(successBlock: { (response, subscriptions) in
           if subscriptions!.count > 0
           {
               for sub in subscriptions!
               {
                   QBRequest.deleteSubscription(withID: sub.id, successBlock: nil, errorBlock: nil)
               }
           }
            // Create new subscriciption for current device here
           }) { (errorResponse) in
           // Create new subscriciption for current device here
           }
