### ISSUE TITLE
After integrating WebRTC it shows error in class QBRTCFrameConverter.h on build

### ISSUE THREAD

**Issue by rathod24** [QuickBlox/quickblox-ios-sdk#235]
![screen shot 2015-12-24 at 2 44 32 pm](https://cloud.githubusercontent.com/assets/16424775/11993588/e1dd7fb8-aa58-11e5-8616-57105e91952e.png)
I'm getting error from QBRTCFrameConverter.h on method named prepareForSourceDimensions on project build

**Comment by Raikerian** [comment]
Hi!

Which version of QuickbloxWebRTC are you using?

**Comment by Raikerian** [comment]
You need to import CoreMedia in your pch file.
Fix for this issue will be available in the next releases.

**Comment by rathod24** [comment]
i'm using version 2.1.1 with xcode 6.4

**Comment by Raikerian** [comment]
Were you able to fix it?

**Comment by rathod24** [comment]
Yes.. it worked !! thanks man for this quick help.
