### ISSUE TITLE
File uploading time getting this error

### ISSUE THREAD

**Issue by kondak3** [QuickBlox/quickblox-ios-sdk#238]
[QBCore] Response error: Error Domain=com.alamofire.error.serialization.response Code=-1011 "Request failed: length required (411)" UserInfo=0x167aa9e0 {com.alamofire.serialization.response.error.response=<NSHTTPURLResponse: 0x16703840> { URL: https://qbprod.s3.amazonaws.com/ } { status code: 411, headers {
    Connection = close;
    "Content-Type" = "application/xml";
    Date = "Thu, 31 Dec 2015 12:16:23 GMT";
    Server = AmazonS3;
    "Transfer-Encoding" = Identity;
    "x-amz-id-2" = "BuDInwV6aKPSMj4o0UsJhFZkmwEeCRQkYi6nkMfT+MMA4yEPYxXHfyTEfFOtf784";
    "x-amz-request-id" = 275DB5EB0E7675E8;
} }, NSErrorFailingURLKey=https://qbprod.s3.amazonaws.com/, NSLocalizedDescription=Request failed: length required (411),

**Comment by Raikerian** [comment]
Hi!

What is your Quickblox and iOS versions?

**Comment by Raikerian** [comment]
We are currently aware of this issue on iOS 7 and will release fix soon.

**Comment by kondak3** [comment]
thank you for your response. 
Quickblox 2.6.1 and ios target 7.0. currently getting this issue in ios 7.1.

**Comment by kondak3** [comment]
thank you for your response.
Quickblox 2.6.1 and ios target 7.0. currently getting this issue in ios 7.1.

On Thu, Dec 31, 2015 at 8:17 PM, Vitaliy Gorbachov <notifications@github.com
> wrote:

> We are currently aware of this issue on iOS 7 and will release fix soon.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/QuickBlox/quickblox-ios-sdk/issues/238#issuecomment-168206271>
> .
>



-- 


Thanks &  Regards

Kondaiah V
iOS Apps Developer
Impressol e-Services
Mobile no: +919966659101

**Comment by Raikerian** [comment]
Fix available in Quickblox iOS SDK 2.6.2.
