### ISSUE TITLE
Too large to clone

### ISSUE THREAD

**Issue by yakubbaev** [QuickBlox/quickblox-ios-sdk#239]
I want to take a glance into chat demo, but must clone whole repo (which is 300Mb+ I think). Can you structure your codebase to be more elegant please?

**Comment by yakubbaev** [comment]
Found a workaround: <code>git clone https://github.com/QuickBlox/quickblox-ios-sdk.git --depth 1</code> which checks out only latest commit (without whole commit history). 
Anyway, reorganizing codebase should be considered IMHO.

**Comment by Raikerian** [comment]
Hi,

We have already tried to compress our repository, however the size of it decreased only for 10%.
In order to not download every patch you can, of course, use that command, or just download zip without cloning the whole repository.

**Comment by yakubbaev** [comment]
Thank you for your response. 
It still will be an issue for cases when someone wants to send you pull requests.

**Comment by Raikerian** [comment]
We will consider doing this in a near future. For now I'm closing this issue for tracking purposes.
If you are still having any troubles, feel free to create separate issue.
