### ISSUE TITLE
<Quickblox/Quickblox.h> file not found 

### ISSUE THREAD

**Issue by fletcher100** [QuickBlox/quickblox-ios-sdk#240]
I have been getting the '<Quickblox/Quickblox.h> file not found' error in the QMChatSections.m file.  
Any suggestions?
Thanks.

**Comment by Raikerian** [comment]
Hi,

Please give us more info on your problem, e.g. which project you are trying to compile?

**Comment by Pyrolr** [comment]
Hi , I am also having the same problem , when i try to run 'sample-chat-swift' target it gives #import <Quickblox/Quickblox.h> not found error in the QMChatSection.m which is in the pods

I have also added PCH file and add QuickBlox sdk via cocoapods but none of them are working

**Comment by iSevenDays** [comment]
Hi!

Have you tried to run "pod install" in a directory with project?

**Comment by Pyrolr** [comment]
Yes i have done that , objective C project is working perfect but having problem in swift target

**Comment by fletcher100** [comment]
I was able to get it to work by running pod install and cleaning the project the other day. Thanks for the replies!

**Comment by Raikerian** [comment]
Good to see you fix it, we will fix all that issues from our side in the near release, so you will not need to reinstall pods.

**Comment by Raikerian** [comment]
Fixed this in master branch

**Comment by 12345555** [comment]
I have been getting the ' file not found' error in the QMChatSections.m,QMChatSectionManager.h files.

Any suggestions?
Thanks.
