### ISSUE TITLE
avatarUrl of QBUUser is nil

### ISSUE THREAD

**Issue by yakubbaev** [QuickBlox/quickblox-ios-sdk#241]
I'm trying to set avatar to test user.

Steps:
1. Log in as user john in sample-chat-swift iOS project
2. Send image to another user, so image appears in Content service
3. Log in as admin to admin.quickblox.com and access that image in Content service
4. Copy content ID of that image
5. Edit user john and make it's Blob ID = Content ID
6. Save user
7. Load user john as QBUUser

Expected result:
avatarUrl of user john is the url of uploaded image
Actual result:
avatarUrl is nil.

How avatarUrl is computed?

**Comment by Raikerian** [comment]
Hi,

avatarUrl is our custom field in QMServices. It is basically setting avatar url in customData field of QBUUser. You can see it's implementation in QBUUser+CustomData.m file.

**Comment by yakubbaev** [comment]
So I can't set avatarUrl to the image uploaded to the Content module, can I?

**Comment by Raikerian** [comment]
Yes you can. Just use url of the uploaded blob.

**Comment by Raikerian** [comment]
If you have any other questions please create separate issue.
