### ISSUE TITLE
QBrequest createDialog:successBlock:errorBlock: 422

### ISSUE THREAD

**Issue by eagle-dan1349** [QuickBlox/quickblox-ios-sdk#242]
I'm trying to create 1-1 chat dialog, with existing user, request always fails with error 422 and following userInfo {"errors":{"base":["Forbidden. Need user."]}}
My code is following:

QBChatDialog* privateDialog = [[QBChatDialog alloc] initWithDialogID:nil type:QBChatDialogTypePrivate];
privateDialog.occupantIDs = @[@(companion.ID)];

[QBRequest createDialog:privateDialog successBlock: ... errorBlock: ...];

**Comment by Raikerian** [comment]
Hi,

In order to use requests you need to login in REST. Use 'loginWithUser' methods.

**Comment by eagle-dan1349** [comment]
When I check [QBSession currentSession].currentUser it already exists.
I log in using QBChat mechanics, [[[QBChat instance] connectWithUser: ... completion: ... ]; do I need to log in via QBRequest instead, or in addition to that? That sound ridiculous.

**Comment by Raikerian** [comment]
Which SDK version are you using?

**Comment by Raikerian** [comment]
You need to login in REST every time you are opening app from scratch.

**Comment by eagle-dan1349** [comment]
I'm using latest one, 2.6.1 via CocoaPods.
My scenario is following:
App launches > configure QuickBloxSDK > Check session > if session exists and have user - reconnect with current user and saved password (via QBChat methods), if session does not exist or have no user, log user in via [QBRequest logInWithUserLogin:password:successBlock:errorBlock:]
App gets user that I want to create dialog with via [QBRequest usersWithLogins:successBlock:errorBlock:] and everything worked up to the dialog creation.
Thank you for quick reply.

**Comment by eagle-dan1349** [comment]
Tried to use [QBRequest usersWithLogins:successBlock:errorBlock:] if session has user.
This way I am able to create new chat dialog now.
IMHO, it's strange that QBChat does not encapsulate this logic.
