### ISSUE TITLE
How to check online status of recipient?

### ISSUE THREAD

**Issue by yakubbaev** [QuickBlox/quickblox-ios-sdk#243]
I have a private chat and want to determine whether person I'm talking to is online (or offline).
Tried <code>requestOnlineUsersWithCompletionBlock</code>, but it's callback never gets called.

**Comment by Raikerian** [comment]
Hi,

We have just tested it and completion block is working correctly. Can you provide us any logs or source code on how do you do this?

**Comment by yakubbaev** [comment]
Simple call
<code>
        self.dialog?.requestOnlineUsersWithCompletionBlock({ (onlineUsers: NSMutableArray?, error: NSError?) -> Void in
            NSLog("online users: \(onlineUsers)")
        })
</code>
in ChatViewController's <code>viewDidLoad</code> method.

**Comment by yakubbaev** [comment]
I've found http://stackoverflow.com/questions/17962614/quickblox-how-find-out-whether-the-user-is-online SO discussion. 
Tried first approach by using REST API, but <code>QBUUser</code>'s <code>lastRequestAt</code> is always nil.
Second approach with Contact List API is a bit overkill for just checking status.

**Comment by Raikerian** [comment]
lastRequestAt is only valid if you are loading user from REST, e.g. using QBRequest method.

**Comment by Raikerian** [comment]
If you are still having any troubles please create separate issue.

**Comment by tanujtak1986** [comment]
Hi,
I am facing same problem, last request at flag only updated when we login to the app.though conceptually it should be updated when user perform any activity with QB Server.but it the same, please help me.

**Comment by Raikerian** [comment]
@tanujtak1986 it is being updated on server, of course you need to update it locally by fetch that user.

**Comment by tanujtak1986** [comment]
means you are saying if we find out recipient status(offline/online) then we have to fetch his/her details from QBRequest method then then we will compare right?

suppose:-
A login in QB at 9:10 then last request at is 9:10 
if we have to find B which logged in 9:12 then his/her last request is 9:12
and according to DOC
NSInteger currentTimeInterval = [[NSDate date] timeIntervalSince1970];
NSInteger userLastRequestAtTimeInterval   = [[user lastRequestAt] timeIntervalSince1970];

// if user didn't do anything last 5 minutes (5*60 seconds)    
if((currentTimeInterval - userLastRequestAtTimeInterval) > 5*60){ 
     // user is offline now
}

you are saying like this right?

**Comment by Raikerian** [comment]
Yes, you got it right.

**Comment by tanujtak1986** [comment]
if this is right then suppose user A login at 9:10 and still do some stuff and still in app around 15 minutes and user B login at 9:20 and check according to this concepts then,
if( i am user B) I am checking for 5 minutes difference for online  then also it will give false result..because when user B fetch user A details then it's give last request at 9:10 (though user A is still login with QB) and now suppose time is 9:20 then difference will be for 10 min and it will give offline..while User A still online(login with QB and perform some stuff like chat e.t.c)...please help me it will give Wrong result.

**Comment by Raikerian** [comment]
Please create a separate issue and describe your point one more time. Also check our lastActivity methods in QBChat, that were added in 2.9 (read changeling here: http://quickblox.com/developers/IOS#Framework_changelog ).

**Comment by tanujtak1986** [comment]
ok thanks..i am checking DOC and let you know..

**Comment by saifan95** [comment]
check this ans - https://stackoverflow.com/a/58235163/7301439
