### ISSUE TITLE
Is possible to getting all push notification from server.

### ISSUE THREAD

**Issue by kondak3** [QuickBlox/quickblox-ios-sdk#244]
hi
there is any possibility to download all push notification from server. i mean pending push notifications.
user getting any notification from server at time, some default notification getting like "you have 100 message" like that.

**Comment by Raikerian** [comment]
Hi,

You can view all pending push notifications in admin panel. But there is no feature to see it through the SDK for now. Maybe we will consider adding this feature in future.
