### ISSUE TITLE
is one-to-many live streaming like periscope app supported in iOS sdk?

### ISSUE THREAD

**Issue by seshubonam** [QuickBlox/quickblox-ios-sdk#245]
I am using Quickblox iOS sdk to build a live streaming app like periscope.

However I wont have hundreds of users to test if a one-to-many broadcast scenario would work with the current sdk.

The video traffic will be routed to a server instead of peer-to-peer.

I am trying to find an answer since a month, so will be thankful if you can point me in the right direction.

Cheers!

**Comment by iSevenDays** [comment]
Hi!

Now we support only peer to peer calls and multi-calls to QB users.

If you want to make a stream video using Quickblox WebRTC SDK you can route received video frames using your server. We have support for custom video capturers http://quickblox.com/developers/Sample-webrtc-ios#Custom_video_capture , so you can make pre and post processing of your video frames.

But as for now we don't have live stream broadcast support, it is planned feature for the future and now we do investigate this.

**Comment by seshubonam** [comment]
Thanks for your support. I am very much convinced on using quickblox for my livestreaming needs, so I will look forward for an update on Broadcast solution.

Can you give an estimated time for Broadcast feature to be enabled in iOS Sdk?

Thanks!

**Comment by iSevenDays** [comment]
As for now we do not have estimated time because this feature will be given a priority after some iterations. But we confident that iPhone 6s+ can handle at least tens of users.

Thanks!

**Comment by TempTest313** [comment]
can we make broadcast using Quick Blox?
