### ISSUE TITLE
Pod install not working in sample-chat-swift project

### ISSUE THREAD

**Issue by gloryluu** [QuickBlox/quickblox-ios-sdk#246]
Analyzing dependencies
Pre-downloading: `QMCVDevelopment` from `git@github.com:QuickBlox/QMChatViewController-ios.git`, branch `development`

[!] Error installing QMCVDevelopment
[!] /usr/bin/git clone git@github.com:QuickBlox/QMChatViewController-ios.git /var/folders/h5/389cxcs94_l5z19qwjptzy040000gn/T/d20160106-6846-3aysss --single-branch --depth 1 --branch development

Cloning into '/var/folders/h5/389cxcs94_l5z19qwjptzy040000gn/T/d20160106-6846-3aysss'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

I know because i dont have the permission to access to your git. But can you guy make it elsewhere to pull ?

**Comment by Raikerian** [comment]
Hi,

Basically error says that you cannot download QMCVDevelopment because of bad public key. Try to configure your git user following this article: https://help.github.com/articles/set-up-git/

**Comment by gloryluu** [comment]
Thanks so much.
Now I get the problem 'Quickblox/Quickblox.h' file not found in QMServicesDevelopment-prefix.pch and QMChatSection in sample-chat-swift project. I even re-add the Quickblox.framwork but the issue still there. How can I fix it ?

**Comment by Raikerian** [comment]
Fixed this in master branch. Please redownload.

**Comment by nakul1296** [comment]
Hi,
I have installed QMServices and QMChatViewController. I am finding an issue 'assignment to read only property' in CDDialog.m line no 13 of QMServices. It seems that QMUsersService class is not available that is present in sample-chat app.
How can I fix it?
