### ISSUE TITLE
Screen share performance

### ISSUE THREAD

**Issue by ruipfcosta** [QuickBlox/quickblox-ios-sdk#247]
I've been playing with the VideoChat-WebRTC sample for the last couple of days and, although the screen share functionality works, the experience cannot be described as really smooth.
Is there anything that can be done to improve the screen share performance and make things smoother? I was exploring the QBRTCVideoCapture class, and adjusting the frameInterval property of the CADisplayLink, which doesn't seem to make any difference.

Thanks in advance.

**Comment by ruipfcosta** [comment]
Any ideas on this guys?

**Comment by iSevenDays** [comment]
We do investigate possible solutions.

Thanks!
