### ISSUE TITLE
Assertion failure in -[QMChatCollectionView _endItemAnimationsWithInvalidationContext:tentativelyForReordering:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit_Sim/UIKit-3505.16/UICollectionView.m

### ISSUE THREAD

**Issue by iPhoneyDev** [QuickBlox/quickblox-ios-sdk#248]
Hi, 

I am getting following error while entering into chat room.

Assertion failure in -[QMChatCollectionView _endItemAnimationsWithInvalidationContext:tentativelyForReordering:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit_Sim/UIKit-3505.16/UICollectionView.m

Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid update: invalid number of sections.  The number of sections contained in the collection view after the update (1) must be equal to the number of sections contained in the collection view before the update (1), plus or minus the number of sections inserted or deleted (1 inserted, 0 deleted).'

Please check and let me know.

Thanks

**Comment by Raikerian** [comment]
Hi,

Please provide us more information on how to reproduce this bug, e.g.the exact steps on how to reproduce it.

**Comment by iPhoneyDev** [comment]
Thanks for reply. Actually my issue was when I am calling "insertMessagesToTheBottomAnimated" method its giving above error.

But I solved this issue using the following lines of code before calling "insertMessagesmethod"

 NSIndexSet *indexSet0 = [NSIndexSet indexSetWithIndexesInRange:NSMakeRange(0,0)];

    [self.collectionView reloadSections:indexSet0];

**Comment by Raikerian** [comment]
Thank you for your report, we have already fixed it. It will be available in the next release.

**Comment by iPhoneyDev** [comment]
Thanks for informing
