### ISSUE TITLE
Not able to join chatroom

### ISSUE THREAD

**Issue by neethz2092** [QuickBlox/quickblox-ios-sdk#25]
The following error message is obtained when tried to send message in chatroom.
[QBChat sendChatMessage:toRoom:] -> return. Room is not joined.
Please check the sample app to reproduce the issue.

**Comment by kondak3** [comment]
hi,
how to get all push notifications, when the user login into chat. 
And one more issue, example one of the user removed from the group, we have to send message to that user also but the use not get that message, because the user already exited from the group.
