### ISSUE TITLE
quickblox framework not linked to project

### ISSUE THREAD

**Issue by anuragbisht** [QuickBlox/quickblox-ios-sdk#250]
Hi ,
I have followed this link to install quickblox framework to my projects.
http://quickblox.com/developers/IOS-how-to-connect-Quickblox-framework

i have added `pod 'QuickBlox'` to my pod file along with the code in sample pod file i.e :

`pod 'QMServicesDevelopment', :git => 'git@github.com:QuickBlox/q-municate-services-ios.git', :branch => 'development'`
`pod 'QMCVDevelopment', :git => 'git@github.com:QuickBlox/QMChatViewController-ios.git', :branch => 'development'`

after the pods are being installed QMServicesDevelopment faramework gives linking error:

`"_OBJC_CLASS_$_QBChat", referenced from:`
     ` objc-class-ref in QMChatService+Bolts.o`
     ` objc-class-ref in QMChatService.o`
      `objc-class-ref in QMContactListService+Bolts.o`
      `objc-class-ref in QMContactListService.o`
      `objc-class-ref in QMUsersService.o`
it remains the same when i tried adding the framework using `.pch` way.
i am using swift 2.0
please help me

**Comment by Pro100Andrey** [comment]
Hi @anuragbisht!
Please add to your pod file:

pod 'QMCVDevelopment', :git => 'git@github.com:QuickBlox/QMChatViewController-ios.git', :commit => '7244eaf609797a5dc5ec6d28dc2b284633b03a1f'

pod 'QMServicesDevelopment', :git => 'git@github.com:QuickBlox/q-municate-services-ios.git', :commit => 'ab56ac143bb770e76409a027bfb38de582d728aa'

and `pod update`

**Comment by anuragbisht** [comment]
Hi Andrey,
Thanks for the reply. I updated the pods but still my project shows the same error.

**Comment by Pro100Andrey** [comment]
Hi @anuragbisht 

Please provide full build logs

**Comment by Pro100Andrey** [comment]
Did you have duplicate symbols?

**Comment by anuragbisht** [comment]
i did it again and this time it worked.

Thanks a lot.

**Comment by Pro100Andrey** [comment]
@anuragbisht Thanks!

**Comment by Fisky-Alan** [comment]
Hi ,, am facing an issue while trying `QMCVDevelopment` from `git@github.com:QuickBlox/QMChatViewController-ios.git`, commit `7244eaf609797a5dc5ec6d28dc2b284633b03a1f`
 Unable to satisfy the following requirements:

- `TTTAttributedLabel (= 2.0.0)` required by `Podfile.lock`
- `TTTAttributedLabel (~> 1.13)` required by `QMCVDevelopment (0.3.3)`

Specs satisfying the `TTTAttributedLabel (= 2.0.0), TTTAttributedLabel (~> 1.13)` dependency were found, but they required a higher minimum deployment target.

**Comment by imobdev-nucitrus** [comment]
hi i'm facing an issue while i trying to update pod 
 $ pod update
Update all pods
Updating local specs repositories
  $ /usr/bin/git -C /Users/imobdev/.cocoapods/repos/master fetch origin --progress
  remote: Counting objects: 9, done.        
  remote: Compressing objects: 100% (8/8), done.        
  remote: Total 9 (delta 6), reused 0 (delta 0), pack-reused 0        
  From https://github.com/CocoaPods/Specs
     ccdb908..47e089f  master     -> origin/master
  $ /usr/bin/git -C /Users/imobdev/.cocoapods/repos/master rev-parse --abbrev-ref HEAD
  master
  $ /usr/bin/git -C /Users/imobdev/.cocoapods/repos/master reset --hard origin/master
  HEAD is now at 47e089f [Add] WRLD 0.0.333

CocoaPods 1.3.0.beta.1 is available.
To update use: `sudo gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.3.0.beta.1

Analyzing dependencies
Pre-downloading: `QMCVDevelopment` from `git@github.com:QuickBlox/QMChatViewController-ios.git`, commit `7244eaf609797a5dc5ec6d28dc2b284633b03a1f`

[!] Error installing QMCVDevelopment
[!] Failed to download 'QMCVDevelopment'.
