### ISSUE TITLE
archiving live video to server

### ISSUE THREAD

**Issue by seshubonam** [QuickBlox/quickblox-ios-sdk#251]
Dear Quickblox,

I'm trying to archive a live video call to the server so I can use it instantly to stream live to a wider audience.

I do not find any documentation for archiving a video call session. Is this feature currently supported?

Thank you

**Comment by Raikerian** [comment]
Hi,

Unfortunately this feature is not available yet and we are not planning to do it in the near future. However we are working on local live video archiving, but there is no ETA yet.
If you are still facing any problems please create separate issue.
