### ISSUE TITLE
after upgrading to sdk 2.6.1 remote view does not fill full sreen

### ISSUE THREAD

**Issue by dmitryvmr** [QuickBlox/quickblox-ios-sdk#252]
Hi, we have recently upgraded QB sdk from v2.4.6 to v2.6.1, and started facing the issue where opponent camera view doesn't stretch to the full screen of the phone.
(testing on Iphone 6, 6s plus, ios 9.2)

In details:
I use Quickblox SDK to capture camera on my phone. I use QBRTCRemoteVideoView to get video track like sample code of Quickblox SDK. I want to make video full frame but it can't. I change ViewMode of QBRTCRemoteVideoView to UIViewContentModeScaleAspectFit or UIViewContentModeScaleAspectFill like their suggest but it can't fill full frame. I config QBRTCVideoFormat but it can't work.

we tried many ways, but still no luck. any advice from you would be great. thanks

this is our pods file:
PODS:
  - Bolts (1.3.0):
    - Bolts/AppLinks (= 1.3.0)
    - Bolts/Tasks (= 1.3.0)
  - Bolts/AppLinks (1.3.0):
    - Bolts/Tasks
  - Bolts/Tasks (1.3.0)
  - libextobjc/EXTKeyPathCoding (0.4.1):
    - libextobjc/RuntimeExtensions
  - libextobjc/EXTScope (0.4.1):
    - libextobjc/RuntimeExtensions
  - libextobjc/RuntimeExtensions (0.4.1)
  - QMServices (0.3.3):
    - Bolts (= 1.3.0)
    - libextobjc/EXTKeyPathCoding (= 0.4.1)
    - libextobjc/EXTScope (= 0.4.1)
    - QuickBlox (~> 2.5)
  - QuickBlox (2.6.1)
  - Quickblox-WebRTC (2.1.1)

DEPENDENCIES:
  - QMServices
  - QuickBlox
  - Quickblox-WebRTC

SPEC CHECKSUMS:
  Bolts: 805a4a87413e49d4a0c2b7d469084cbc46b09342
  libextobjc: a650fc1bf489a3d3a9bc2e621efa3e1006fc5471
  QMServices: 920f3e4df78378e8dfb801890ea72c2975d54c49
  QuickBlox: 870ae1b33cc4f0687b0fff6a29438a12f1c4f7d5
  Quickblox-WebRTC: e0ce2b16a793d16e86cfacb5b3fdb08d944ac77b

COCOAPODS: 0.39.0

**Comment by Raikerian** [comment]
Hi,

This issue will be fixed in the near future releases.
For now please use the following category(as for now it is an internal API) :

```objectivec
@interface QBRTCRemoteVideoView (VideoGravity)

@property (nonatomic, strong, readonly) QBRTCSampleBufferRenderer *renderer;

@end
```

Then you can use property

```objectivec
QBRTCRemoteVideoView *videoView = your_video_view;
QBRTCSampleBufferView *view = (QBRTCSampleBufferView *)videoView.renderer.rendererView;
 view.videoGravity = AVLayerVideoGravityResizeAspectFill;
```

**Comment by dmitryvmr** [comment]
thanks! that worked.

**Comment by RamandeepGosal** [comment]
Hi, 
I am new to Quickblox, can you please explain the above code a bit
```
QBRTCRemoteVideoView *videoView = your_video_view;
QBRTCSampleBufferView *view = (QBRTCSampleBufferView *)videoView.renderer.rendererView;
 view.videoGravity = AVLayerVideoGravityResizeAspectFill;

```

and where and how to use - 
```
@interface QBRTCRemoteVideoView (VideoGravity)

@property (nonatomic, strong, readonly) QBRTCSampleBufferRenderer *renderer;

@end

```

**Comment by RamandeepGosal** [comment]
I did create a category 
but was not able to find 
```
QBRTCSampleBufferRenderer
```
class.
