### ISSUE TITLE
senderID is a QMMessageType sometimes?

### ISSUE THREAD

**Issue by yakubbaev** [QuickBlox/quickblox-ios-sdk#253]
I want to create a couple of custom message types, that's why digged into this part of your sample.

Can't understand why you are comparing <code>senderID</code> as <code>QMMessageType</code> in [viewClassForItem](https://github.com/QuickBlox/quickblox-ios-sdk/blob/master/sample-chat-swift/sample-chat-swift/Classes/ViewControllers/ChatViewController.swift#L399) method.
Is there any implicit assumption? Why you are not comparing <code>messageType</code> property instead of <code>senderID</code>?

**Comment by iSevenDays** [comment]
Hi! 

Flow is always go to else statement https://github.com/QuickBlox/quickblox-ios-sdk/blob/master/sample-chat-swift/sample-chat-swift/Classes/ViewControllers/ChatViewController.swift#L414

So you are right.

We have this fixed in develop branch.

Thanks for pointing us to this problem!
