### ISSUE TITLE
How to receive push notification for offline user with public group

### ISSUE THREAD

**Issue by buithuyen** [QuickBlox/quickblox-ios-sdk#254]
I have configured notification in QuickBlox dashboard and `Enable automatic notifications for offline users`. 
I received push notification from dashboard, but I could not receive push notification in public group.
What's wrong? Is there something that I forgot to enable?

**Comment by Raikerian** [comment]
Hi,

Unfortunately you cannot receive push notifications for public group chats for now. This is due to public chats not having occupants in it.

**Comment by vickysaini** [comment]
Hi,

I am using version 3.3.5. I know Public Groups does not have occupant Ids. But a QBUser who joins a Public Group can be stored as the occupants in the table at backend. Is there any method to get the QBUsers who has joined a particular Public Group.
