### ISSUE TITLE
How to get chatSections from QMChatViewController

### ISSUE THREAD

**Issue by iPhoneyDev** [QuickBlox/quickblox-ios-sdk#256]
Hi,

I have override the  "sectionHeaderAtIndexPath" in my ChatViewController with customization.

Now, I want to display date. I am unable to get chatSections array from "QMChatViewController".

Could you please help how to get the "lastmessageDate" from QMChatSections.

Thanks

**Comment by Raikerian** [comment]
Hi,

You can use this method to get last or first QMChatMessage of section:
```
- (QBChatMessage *)messageForIndexPath:(NSIndexPath *)indexPath
```

There you can get message date.
For now this is the only way to get it. We will improve our chat datasource so it will be easily overridden in the near future.

**Comment by iPhoneyDev** [comment]
Thanks for reply. I am using QBChatMessage dateSent method for sections date.
