### ISSUE TITLE
Customize input toolbar 

### ISSUE THREAD

**Issue by iPhoneyDev** [QuickBlox/quickblox-ios-sdk#258]
Hi,

I want to move attachment button in input toolbar to right side and in between the message textfield and send button.

I know this can achieve by total customisation of QMInputToolbar but is there any way to exchange left bar button item and message textfield in input toolbar.

Please give me suggestions.

Thanks

**Comment by iPhoneyDev** [comment]
Please help me on this customization of input toolbar

**Comment by Raikerian** [comment]
Hi,

there is a property in QMInputToolBar that can help you:
```objective-c
/**
 *  A boolean value indicating whether the send button is on the right side of the toolbar or not.
 *
 *  @discussion The default value is `YES`, which indicates that the send button is the right-most subview of
 *  the toolbar's `contentView`. Set to `NO` to specify that the send button is on the left. This
 *  property is used to determine which touch events correspond to which actions.
 *
 *  @warning Note, this property *does not* change the positions of buttons in the toolbar's content view.
 *  It only specifies whether the `rightBarButtonItem `or the `leftBarButtonItem` is the send button.
 *  The other button then acts as the accessory button.
 */
@property (assign, nonatomic) BOOL sendButtonOnRight;
```

if Its not enough, you will need to customise it by yourself.

**Comment by Raikerian** [comment]
Were you able to achieve this?

**Comment by iPhoneyDev** [comment]
sendButtonOnRight is not suitable for me. So i have to customize total QMInputToolBar. I haven't implemented as it will take time to achieve.

**Comment by Raikerian** [comment]
Okay, if you will have any troubles please let us know by creating separate issue :)
