### ISSUE TITLE
App audio volume while in call

### ISSUE THREAD

**Issue by ruipfcosta** [QuickBlox/quickblox-ios-sdk#259]
On this app where I'm integrating QuickBlox, the user has the ability to play videos and listen to some sounds. One of the features of the app is that the call window can be minimised, so that the user can continue using the app while in a call. 
However, I noticed that, while in a call, the volume of those sounds and videos on the app is really low. It looks like QuickBlox "takes over" the sound control when a call is ongoing.
Is there any way to control the sound of the app to make them louder at the same time a call is ongoing?

**Comment by iSevenDays** [comment]
Hi!

Do you use sample webrtc video chat and QMSoundManager?

**Comment by ruipfcosta** [comment]
Hi there,

Yes I started with the WebRTC sample, and I'm using QMSoundManager as a convenience (at least that was what I thought) to play the call sounds - calling, ringtone, etc. The app sounds and video (implemented in the past) are using the typical AVAudioPlayer and MPMoviePlayerController.
Am I doing something wrong?

**Comment by ruipfcosta** [comment]
@iSevenDays any ideas on this? Thanks.

**Comment by iSevenDays** [comment]
QMSoundManager uses system sounds. QMSoundManager does not allow you to change sound volume(by this implementation). So for your case you should use other sound manager.

Thanks!

**Comment by ruipfcosta** [comment]
Thanks for the reply @iSevenDays, although I'm not sure if I understand what you mean. What is the relation between a sound manager and the AVAudioPlayer/MPMoviePlayerController I'm using? Do you mean I shouldn't be using AVAudioPlayer/MPMoviePlayerController to play my custom sounds and videos on the app?
Can you give me some pointers here?

Thanks!

**Comment by iSevenDays** [comment]
QBRTCSoundManager uses category AVAudioSessionCategoryPlayAndRecord. When this category is set, audio will not be silenced by the mute switch or the screen lock. 

So I suggest you to use the following code( I haven't tried it)

UInt32 allowMixing = true;
AudioSessionSetProperty(kAudioSessionProperty_OverrideCategoryMixWithOthers, sizeof(allowMixing), &allowMixing);

[2:48] 
You're on the right way. First, set the kAudioSessionProperty_OverrideCategoryMixWithOther to true. This will allow your app's sound mixes with sounds from another apps.

UInt32 allowMixing = true;
AudioSessionSetProperty(kAudioSessionProperty_OverrideCategoryMixWithOthers, sizeof(allowMixing), &allowMixing);
After that, you will need to set MPMoviePlayerController to not use your app's AudioSession:

[yourMPMoviePlayerControllerInstance setUseApplicationAudioSession:NO];

**Comment by ruipfcosta** [comment]
Thanks for the support, I tried this on my MPMoviePlayerControllerInstance instance but once I set it my call loses the audio (although I can now hear my video normally). What I would like to achieve is overlapping sounds: my video and audio sounds over the call audio.
Also the code you posted appears to be deprecated on iOS 6.0 and 7.0 (in Swift I can't even do the equivalent to ```[yourMPMoviePlayerControllerInstance setUseApplicationAudioSession:NO];```).

**Comment by iSevenDays** [comment]
Seems that you have case we have not seen before as we haven't tested audio renderer from multiple sources at the same time.

From our conversation I see that you have two audio sources: call and movie player. And you want to hear both audio sources at the same time, right?

Could you please create for us test project where we can reproduce your issues?

Also, we are happy to test your related issue with "buzz" sound.

Thanks!

**Comment by ruipfcosta** [comment]
Exactly, I want to play two audio sources at the same time (audio or video and call).
I will create a test project which hopefully will allow us to reproduce the problem.

**Comment by iSevenDays** [comment]
We are waiting for test project from you and we hope we can get everything fixed as soon as possible. Thanks!

**Comment by ruipfcosta** [comment]
@iSevenDays I changed your WebRTC sample to make it play a video and an audio file during a call and I wasn't able to reproduce any of the audio problems I reported (either this one or https://github.com/QuickBlox/quickblox-ios-sdk/issues/257). This leads me to believe it must be something on our side, I'm investigating in more detail.
Thanks for the support!

**Comment by ruipfcosta** [comment]
This issue seems to be similar/related to https://github.com/QuickBlox/quickblox-ios-sdk/issues/60.

**Comment by Raikerian** [comment]
Hi again @ruipfcosta

We have just released our new WebRTC SDK 2.3 which is containing completely new audio module.
You can now configure category, category options and mode of AVAudioSession used in WebRTC, read more here: http://quickblox.com/developers/Sample-webrtc-ios#Audio_Session_.28Previously_Sound_Router.29

Category options provides such things as Ducking and Mixing, you might want to look more into it.
Here is full changelog of version 2.3: http://quickblox.com/developers/Sample-webrtc-ios#Framework_changelog
Also check mode.

Anyway, if you will have any other problems or questions, feel free to start new issue to let us know. 

Have a nice holidays.

**Comment by Jaimin2208** [comment]
Hello Raikerian,

When My App in Foreground & Background then didReceiveNewSession method is called.
but when in "lock-Mode" then it's not work.
