### ISSUE TITLE
Landscape video of Back Camera is 180° rotated

### ISSUE THREAD

**Issue by pzoechner** [QuickBlox/quickblox-ios-sdk#26]
I'm experiencing an issue where the back camera is wrongly interpreted when received.
As the back camera goes into "Landscape Mode" (happens with both, left and right), the receiver will see the picture upside down.
However, the front camera will be correctly received!

**Comment by soulfly** [comment]
New generation of Video samples is here http://quickblox.com/developers/VideoChat
