### ISSUE TITLE
Control video quality on iPad

### ISSUE THREAD

**Issue by andrewjackman** [QuickBlox/quickblox-ios-sdk#260]
I have an iPad-only app that I'm integrating Quickblox with. We want to send the front camera to the remote device, where it is displayed full-screen (much like FaceTime). I'm trying to improve the video quality, as the default 640x480@30fps doesn't look great.

When I change my video format settings from the default, it doesn't seem to make any difference to the video quality.

```swift
let videoFormat = QBRTCVideoFormat(width: 1024, height: 768, frameRate: 30, pixelFormat: QBRTCPixelFormat.Format420f)
let position = AVCaptureDevicePosition.Front
let cameraCapture = QBRTCCameraCapture(videoFormat: videoFormat, position: position)
...
```

I notice in the logs:

    Best device format is: <AVCaptureDeviceFormat: 0x17fa9920 'vide'/'420f'  640x 480, { 2- 30 fps}, fov:54.370, ISO:29.0-928.0, SS:0.000028-0.500000>

And things like:
```
rtc::{640, 480}
rtc::{320, 240}
```
which I presume is the resolution changing to cope with a higher frame rate.

So exactly how can I control the video quality? Am I missing something?

**Comment by Raikerian** [comment]
Hi,

You can see available resolutions by calling method

```
+ (NSArray *)formatsWithPosition:(AVCaptureDevicePosition)position;
```

of QBRTCCameraCapture class. This means that you will able to use only returned QBRTCVideoFormat formats, and nothing else.

**Comment by andrewjackman** [comment]
Ah OK thanks for explaining. I just experimented with a few devices to see what they supported.
