### ISSUE TITLE
Self video orientation

### ISSUE THREAD

**Issue by ruipfcosta** [QuickBlox/quickblox-ios-sdk#262]
There's this behaviour (also present on the WebRTC sample) which is not ideal for me: when the device is flat on a surface, the device is assumed to be in portrait orientation, showing the self video preview layer vertically and streaming the video vertically to the other party.
I would like to be able to control the orientation of the stream but there doesn't seem to be a way to do it. I found that if I do this:

```swift
selfVideoLayer.connection.videoOrientation = AVCaptureVideoOrientation.LandscapeLeft
```

I can set the layer's orientation to what I want, but the video is still streamed in portrait. Is there a way to control the orientation of the stream too?
This is only happening when the device is flat on a surface, in other positions everything seems to be ok.

Thanks in advance!

**Comment by Raikerian** [comment]
Hi,

We are currently working on this feature, it will be available in the near future releases.

**Comment by ruipfcosta** [comment]
Thanks @Raikerian!

**Comment by Raikerian** [comment]
In order to receive updates about Quickblox new features, follow our [blog here](http://quickblox.com/blog/).

We are closing this thread for tracking purposes.
If you have any other questions please create separate issue.

**Comment by ruipfcosta** [comment]
Hi @Raikerian, what is the progress on this issue, will a fix be available anytime soon? 

Thanks!

**Comment by iSevenDays** [comment]
Hi ruipfcosta, we have fix for you.

Create your class **Derived** that inherits from **QBRTCCameraCapture**

Then define category
```
@interface QBRTCCameraCapture(Private)

- (AVCaptureVideoOrientation)videoOrientationForDeviceOrientation:(UIDeviceOrientation)orientation;

@end
```

Then in **Derived** class override
- (AVCaptureVideoOrientation)videoOrientationForDeviceOrientation:(UIDeviceOrientation)orientation {

/*
    switch ([UIDevice currentDevice].orientation) {
        case UIDeviceOrientationPortrait:
            return AVCaptureVideoOrientationPortrait;
        case UIDeviceOrientationPortraitUpsideDown:
            return AVCaptureVideoOrientationPortraitUpsideDown;
        case UIDeviceOrientationLandscapeLeft:
            return AVCaptureVideoOrientationLandscapeRight;
        case UIDeviceOrientationLandscapeRight:
            return AVCaptureVideoOrientationLandscapeLeft;
        case UIDeviceOrientationFaceUp:
        case UIDeviceOrientationFaceDown:
        case UIDeviceOrientationUnknown:
            return AVCaptureVideoOrientationPortrait;
    }

*/
    return AVCaptureVideoOrientationPortrait;   
}


Then, for example

**#pragma mark - Update orientation

- (void)updateVideoCaptureOrientation {
    
    AVCaptureVideoOrientation newOrientation = [self videoOrientationForDeviceOrientation:[UIDevice currentDevice].orientation];
    
    AVCaptureConnection *connection = [self videoOutputConnection];
    AVCaptureConnection *previewConnection = self.previewLayer.connection;
    
    [self enqueueSessionBlock:^{
        
        if (previewConnection.videoOrientation != newOrientation) {
            previewConnection.videoOrientation = newOrientation;
        }
        
        if (connection.videoOrientation != newOrientation) {
            connection.videoOrientation = newOrientation;
        }
    }];
}**

Thank you for being patient!

**Comment by ruipfcosta** [comment]
Thanks, I will have a look and confirm it works. But shouldn't this be included in the SDK itself as it is a bug?

**Comment by iSevenDays** [comment]
Soon we will release minor update, but this fix will be included in major release.

We will open new API. Or you can implement your custom camera capture.

Thanks!
