### ISSUE TITLE
Updating the unread message Count issue.

### ISSUE THREAD

**Issue by ajay2c9** [QuickBlox/quickblox-ios-sdk#264]
Hi,
  How to update the unread messages count fastly.when a message is send, the message is updated in the dialog but the unread messages count is not updated.how to update the unread message count fastly in the chatdialog.

Thank you

**Comment by Raikerian** [comment]
Hi,

Do you mean you want to update unread message counter locally? If yes you can easily increment it:

```
chatDialog.unreadMessageCounter++;
```

**Comment by ajay2c9** [comment]
When the App enter from background to foreground,When the message is send from one person to another the last message is updated. but Unread message count is not incremented.Actually I am showing a indication for unread messages not count.

**Comment by Raikerian** [comment]
You need to increment unread message counter locally by yourself after message sending.

**Comment by ajay2c9** [comment]
how to increase the unread message counter locally on which comparison?i am using the QBChatdialog for displaying the dialogs.How can I identify that the message is updated in dialog and the message is unread.

**Comment by Raikerian** [comment]
QBChatMessage has property readIDs, there you can check if a specific user has marked it as read.

**Comment by ajay2c9** [comment]
I didn't get your point. how to use the QBChatMessage's property readIDs, In dialogs and How to get the  QBChatMessage from QBChatdialog last message.

Actually i have two screens and Screen 1 and Screen2. In Screen1  by using this method  i am getting the chat dialogs. (dialogs screen)
[QBRequest dialogsForPage:pageDialogs extendedRequest:nil successBlock:^(QBResponse *response, NSArray *dialogObjects, NSSet *dialogsUsersIDs, QBResponsePage *pageResponseDialogs)
{
}error
{
}];

In screen 2 by using this method i am getting the chat messages (QBChat messages) by using this method. (chatting screen)
[QBRequest messagesWithDialogID:self.dialog.ID extendedRequest:extendedRequest                           forPage:page successBlock:^(QBResponse *response, NSArray *messages, QBResponsePage *page) 
{
}error
{
}];
 in screen 2. i am using this method for mark the read messages.
 [QBRequest markMessagesAsRead:[[[ChatService shared] messagsForDialogId:self.dialog.ID] valueForKey:@"ID"] dialogID:Appdelegate.chatdialog.ID successBlock:^(QBResponse *response)
     {
         //NSLog(@"dialog is updated");
     } errorBlock:^(QBResponse *response)
     {
         //NSLog(@"dialog is not  updated");
         
     }];

5 members are chatting in a group .After some time  one person(Me) is come to Screen 1 and he is getting the unread count correctly.he read the messages in screen 2 and minimise the app, other persons are chatting. after some time opened the app and read the remaining messages and come to Screen 1.other persons are still chatting. In the chat dialogs the last message are updating but the unread messages count is not updating.Now I am in the Screen1.

I didn't understand that how to use the QBChatMessage property readIDs property in Screen 1. where i am using the QBChatdialog.

 Please give suggestions.
 Thank you

**Comment by Raikerian** [comment]
You are marking message as read with REST request. This means, that you will able to receive the update about message readIDs only using method:

```objectivec
[QBRequest messagesWithDialogID:self.dialog.ID extendedRequest:extendedRequest                           forPage:page successBlock:^(QBResponse *response, NSArray *messages, QBResponsePage *page) 
{
}error
{
}];
```

In order to mark messages and receive updates LIVE you should use QBChat method:

```objectivec
[[QBChat instance] readMessage:message completion:^(NSError *error) {

}
```

By this method you will receive XMPP updates on message marking with this delegate:

```objectivec
- (void)chatDidReadMessageWithID:(NSString *)messageID dialogID:(NSString *)dialogID readerID:(NSUInteger)readerID
{
}
```

**Comment by Raikerian** [comment]
We haven't heard back from you in a few days, so we are marking this post as Closed for tracking purposes. If you're still experiencing this issue, please provide us with additional information.
