### ISSUE TITLE
display message in different format not like chat messages when some one joined in group chat

### ISSUE THREAD

**Issue by iPhoneyDev** [QuickBlox/quickblox-ios-sdk#265]
Hi,

Could you please tell me how to achieve this display message(in a rectangle background) in different format not like chat message(down arrow) when some one joined in group chat.

Please suggest me

Thanks

**Comment by Raikerian** [comment]
Hi,

This feature is not implemented in our samples yet, however check out our [Q-municate](https://github.com/QuickBlox/q-municate-ios'Q-municate') project, which is using QMChatViewController and it's Notification cells.
You can achieve this by customising 'viewClassForItem:' method in your QMChatViewController subclass, here is the example for you:

```
- (Class)viewClassForItem:(QBChatMessage *)item
{
    if (item.isNotificatonMessage) {
        
       return [QMChatNotificationCell class];
    } else {
        if (item.senderID != self.senderID) {
            if ((item.attachments != nil && item.attachments.count > 0) || item.attachmentStatus != QMMessageAttachmentStatusNotLoaded) {
                return [QMChatAttachmentIncomingCell class];
            } else {
                return [QMChatIncomingCell class];
            }
        } else {
            if ((item.attachments != nil && item.attachments.count > 0) || item.attachmentStatus != QMMessageAttachmentStatusNotLoaded) {
                return [QMChatAttachmentOutgoingCell class];
            } else {
                return [QMChatOutgoingCell class];
            }
        }
    }
    return nil;
}
```

Now just make your message type QMMessageTypeUpdateGroupDialog for example (please note, message types are QMServices feature). isNotificationMessage property always true if message type is not QMMessageTypeText.

**Comment by iPhoneyDev** [comment]
I sent a message with QMMessageTypeUpdateGroupDialog type. But app is crashing with the followin message "You can only send text messages with this method".

Please help me on this

**Comment by iPhoneyDev** [comment]
Can anyone please help me on this. 

Thanks

**Comment by Raikerian** [comment]
We have different methods for a specific message types, please check it out:

```objectivec
/**
 *  Send message about accepting or rejecting contact requst.
 *
 *  @param accept     YES - accept, NO reject
 *  @param opponent   opponent ID
 *  @param completion completion block with failure error
 */
- (void)sendMessageAboutAcceptingContactRequest:(BOOL)accept
                                   toOpponentID:(NSUInteger)opponentID
                                     completion:(QBChatCompletionBlock)completion;

/**
 *  Sending notification message about adding occupants to specific dialog.
 *
 *  @param occupantsIDs     array of occupants that were added to a specific dialog
 *  @param chatDialog       chat dialog to send notification message to
 *  @param notificationText notification message body (text)
 *  @param completion       completion block with failure error
 */
- (void)sendNotificationMessageAboutAddingOccupants:(NSArray *)occupantsIDs
                                           toDialog:(QBChatDialog *)chatDialog
                               withNotificationText:(NSString *)notificationText
                                         completion:(QBChatCompletionBlock)completion;

/**
 *  Sending notification message about leaving dialog.
 *
 *  @param chatDialog       chat dialog to send message to
 *  @param notificationText notification message body (text)
 *  @param completion       completion block with failure error
 */
- (void)sendNotificationMessageAboutLeavingDialog:(QBChatDialog *)chatDialog
                             withNotificationText:(NSString *)notificationText
                                       completion:(QBChatCompletionBlock)completion;

/**
 *  Sending notification message about changing dialog photo.
 *
 *  @param chatDialog       chat dialog to send message to
 *  @param notificationText notification message body (text)
 *  @param completion       completion block with failure error
 */
- (void)sendNotificationMessageAboutChangingDialogPhoto:(QBChatDialog *)chatDialog
                                   withNotificationText:(NSString *)notificationText
                                             completion:(QBChatCompletionBlock)completion;

/**
 *  Sending notification message about changing dialog name.
 *
 *  @param chatDialog       chat dialog to send message to
 *  @param notificationText notification message body (text)
 *  @param completion       completion block with failure error
 */
- (void)sendNotificationMessageAboutChangingDialogName:(QBChatDialog *)chatDialog
                                  withNotificationText:(NSString *)notificationText
                                            completion:(QBChatCompletionBlock)completion;
```

For more information read our [QMServices](https://github.com/QuickBlox/q-municate-services-ios) or inline doc.

**Comment by iSevenDays** [comment]
Hi,

We haven't heard back from you in a few days, so we are marking this post as Closed for tracking purposes. If you're still experiencing this issue, please provide us with additional information.

**Comment by iPhoneyDev** [comment]
Hi,

I am able to send a notification message in the chat room. I have created a xib for that UI and subclassing QBChatCell. Everything is working fine. But the textView of QMChatCell is aligning in center. Could you please suggest me on this.

Thanks

**Comment by iSevenDays** [comment]
Hi!

Please look at the image I've attached
<img width="569" alt="screen shot 2016-02-01 at 14 24 24" src="https://cloud.githubusercontent.com/assets/3992716/12717286/8f613652-c8ef-11e5-82d7-116202d9e6ad.png">

**Comment by iPhoneyDev** [comment]
Thanks alot for your quick response. I already tried this one. If I will give center, it is taking as right alignment.

**Comment by iSevenDays** [comment]
I tried this minute ago with Alignment = center for chat incoming cell
<img width="480" alt="screen shot 2016-02-01 at 14 43 10" src="https://cloud.githubusercontent.com/assets/3992716/12717698/2b201a48-c8f2-11e5-8c9b-0844571d906c.png">
![img_0601](https://cloud.githubusercontent.com/assets/3992716/12717728/749f1ee4-c8f2-11e5-9886-3c8184420ab0.jpg)

Please re-download everything, then execute pod update and then try again.

Thanks!

**Comment by iPhoneyDev** [comment]
Thanks again. I will try and I will lwt you know. Is new update came for iOS?

**Comment by iSevenDays** [comment]
We release frequently and adapt according to your feedback. Thanks!

**Comment by iPhoneyDev** [comment]
Thanks alot. I didnt download quickblox again. But I have updated pods and its working now.


Is it required download quickblox or I can do pod update? Please let me know

**Comment by iSevenDays** [comment]
With quickblox-ios-sdk repo we always include the most recent version of Quickblox SDK. You don't have to download another version.

When you update pods you pull the most recent version of QMCVDevelopment( Chat View Controller) & QMServicesDevelopment (Services).

With every release you can download zip archive of our repo or you can setup github repo and only pull up the most recent changes. 

Thanks!
