### ISSUE TITLE
how to update the chat  when entering from background to foreground.

### ISSUE THREAD

**Issue by ajay2c9** [QuickBlox/quickblox-ios-sdk#266]
Hi,
I have  a chat room. after making of few chatting. I minimize my app and send few messages from the other.After some time I opened the app the QBChatdialog shows the last message correctly but in the detail last messages are missing. and First time i am unable to send the message.Chat is connected . but message is not sending after removing the instance or again login to the with same user all messages are showing.

Please give suggestions for updating the chat fastly and able send the message when entering from background to foreground.

Thank you.

**Comment by Raikerian** [comment]
Hi,

Please provide us more information on:
1. What is the type of dialog: Prvate, Group, Public group?
2. Your Quickblox iOS SDK version.
3. What is "detail"? Do you mean the property lastMessageText of QBChatDialog instance?

**Comment by ajay2c9** [comment]
1.Type of dialog:Group.
2.Quickblox iOS SDK version :2.4.1
3."detail" means getting the messages by sending the dialogid.

**Comment by Raikerian** [comment]
When the app going background we automatically leaving all group dialogs, so when you opening app from background you need to join it again (our QMServices doing this automatically).
If you are not using QMServices make sure the dialog is joined when you are trying to send message there.

**Comment by Raikerian** [comment]
Were you able to fix it?

**Comment by ajay2c9** [comment]
Thank you. It is working.But it is taking time for loading dialogs and join. is there any quick process to update fastly.I have one more doubt while the app is in background. someone sent messages and images. while entering it into foreground few messages are missing. Last message is displaying in the chat dialog but it is not displaying in the chat screen and some of the last messages (Messages send when the App in background ) are missing.after removing the instance of app or again logging in the App the total messages are displaying.

**Comment by Raikerian** [comment]
Are you loading messages from REST after entering chat screen?

**Comment by ajay2c9** [comment]
i didn't get you.

I am using this method .

- (void)syncMessages:(BOOL)loadPrevious
{
    NSArray *messages = [[ChatService shared] messagsForDialogId:self.dialog.ID];
    NSDate *lastMessageDateSent = nil;
    NSDate *firstMessageDateSent = nil;
    if(messages.count > 0){
        lastMessageDateSent = ((QBChatMessage *)[messages lastObject]).dateSent;
        firstMessageDateSent = ((QBChatMessage *)[messages firstObject]).dateSent;
    }
    
    __weak __typeof(self)weakSelf = self;
    
    NSMutableDictionary *extendedRequest = [[NSMutableDictionary alloc] init];
    if(loadPrevious){
        if(firstMessageDateSent != nil){
            extendedRequest[@"date_sent[lte]"] = @([firstMessageDateSent timeIntervalSince1970]-1);
        }
    }else{
        if(lastMessageDateSent != nil){
            extendedRequest[@"date_sent[gte]"] = @([lastMessageDateSent timeIntervalSince1970]+1);
        }
    }
    extendedRequest[@"sort_desc"] = @"date_sent";
    
    QBResponsePage *page = [QBResponsePage responsePageWithLimit:100 skip:0];
    [QBRequest messagesWithDialogID:self.dialog.ID
                    extendedRequest:extendedRequest
                            forPage:page
                       successBlock:^(QBResponse *response, NSArray *messages, QBResponsePage *page) {
                           if(messages.count > 0){
                               [[ChatService shared] addMessages:messages forDialogId:self.dialog.ID];
                           }
                           
                           if(loadPrevious){
                               NSDateFormatter *formatter = [[NSDateFormatter alloc] init];
                               [formatter setDateFormat:@"MMM d, h:mm a"];
                               NSString *title = [NSString stringWithFormat:@"Last update: %@", [formatter stringFromDate:[NSDate date]]];
                               NSDictionary *attrsDictionary = [NSDictionary dictionaryWithObject:[UIColor blackColor]
                                                                                           forKey:NSForegroundColorAttributeName];
                               NSAttributedString *attributedTitle = [[NSAttributedString alloc] initWithString:title attributes:attrsDictionary];
                               weakSelf.refreshControl.attributedTitle = attributedTitle;
                               
                               [weakSelf.refreshControl endRefreshing];
                               
                               [weakSelf.messagesTableView reloadData];
                           }else{
                               [weakSelf.messagesTableView reloadData];
                               NSInteger count = [[ChatService shared] messagsForDialogId:self.dialog.ID].count;
                               if(count > 0){
                                   [weakSelf.messagesTableView scrollToRowAtIndexPath:[NSIndexPath indexPathForRow:count-1 inSection:0]
                                                                     atScrollPosition:UITableViewScrollPositionBottom animated:NO];
                               }
                           }
                       } errorBlock:^(QBResponse *response) {
                           
                       }];
}

**Comment by Raikerian** [comment]
```objectivec
 if(loadPrevious){
        if(firstMessageDateSent != nil){
            extendedRequest[@"date_sent[lte]"] = @([firstMessageDateSent timeIntervalSince1970]-1);
        }
    }else{
        if(lastMessageDateSent != nil){
            extendedRequest[@"date_sent[gte]"] = @([lastMessageDateSent timeIntervalSince1970]+1);
        }
    }
```

What is the reason behind '+1' and '-1' on time intervals?

**Comment by ajay2c9** [comment]
I didn't  know that exactly.I used the previous chat files.In that this method is used for getting the messages from dialogs by passing dialog id.

**Comment by Raikerian** [comment]
It could be the reason behind missing messages. Try removing it and test.

**Comment by ajay2c9** [comment]
ok . I will check it.Thank you for suggesting me.

**Comment by iSevenDays** [comment]
Hi,

We haven't heard back from you in a few days, so we are marking this post as Closed for tracking purposes. If you're still experiencing this issue, please provide us with additional information.
