### ISSUE TITLE
Can not sign up 

### ISSUE THREAD

**Issue by buithuyen** [QuickBlox/quickblox-ios-sdk#269]
I have a problem:

```
[QBCore] Request URL:https://api.quickblox.com/users.json
[QBCore] Request method: POST

[QBCore] Request parameters:{
    user =     {
        "full_name" = "cu lac";
        login = 84902214169;
        password = "AddHours!@#Chat";
    };
}

[QBCore] Request headers: {
    "Content-Type" = "application/json";
    "QB-OS" = "iOS 8.4";
    "QB-SDK" = "iOS 2.6.1";
    "QB-Token" = cbc27568cd9b8d189d8391cd313a65de50039777;
    "QuickBlox-REST-API-Version" = "0.1.1";
}
```

And result:

```
[QBCore] Response error: Error Domain=com.alamofire.error.serialization.response Code=-1011 "Request failed: unauthorized (401)" UserInfo=0x7f82d0c62130 {com.alamofire.serialization.response.error.response=<NSHTTPURLResponse: 0x7f82d3306520> { URL: https://api.quickblox.com/users.json } { status code: 401, headers {
    "Access-Control-Allow-Origin" = "*";
    "Cache-Control" = "no-cache";
    Connection = "keep-alive";
    "Content-Length" = 55;
    "Content-Type" = "application/json; charset=utf-8";
    Date = "Fri, 22 Jan 2016 17:04:51 GMT";
    "QuickBlox-REST-API-Version" = "0.1.1";
    Server = "nginx/1.6.2";
    Status = "401 Unauthorized";
    "X-Rack-Cache" = "invalidate, pass";
    "X-Request-Id" = 1b56cb5a9de76efd83b7bc1fea55899a;
    "X-Runtime" = "0.007093";
    "X-UA-Compatible" = "IE=Edge,chrome=1";
} }, NSErrorFailingURLKey=https://api.quickblox.com/users.json, com.alamofire.serialization.response.error.data=<7b226572 726f7273 223a7b22 62617365 223a5b22 52657175 69726564 20736573 73696f6e 20646f65 73206e6f 74206578 69737422 5d7d7d>, NSLocalizedDescription=Request failed: unauthorized (401)}
```

Help me fix this. Thanks!

**Comment by iSevenDays** [comment]
Hi!

It means that you have created a session without user. 

You forgot to call [QBRequest [one of possible login with user methods]]

To check that you have a valid session with user you can examine [QBSession currentSession].currentUser property. 

Also please update your SDK to 2.6.3 to see detailed error reasons.

Thanks!

**Comment by buithuyen** [comment]
I have just update to 2.6.3 and it work for me. Thanks for yours help!

**Comment by ashiqsulaiman** [comment]
how to update the sdk to 2.6.3 ?

**Comment by Raikerian** [comment]
@ashiqsulaiman use `pod 'QuickBlox', '2.6.3'`, but if there is a possibility for you to update to latest 2.7.2, I would definitely recommend it.

**Comment by ashiqsulaiman** [comment]
[!] Unknown command: `QuickBlox,`
Did you mean: lib

this is the ,message i am getting when i am trying to update the pod file

**Comment by Raikerian** [comment]
@ashiqsulaiman please create a separate issue and attach full log.

**Comment by YogendraPatel** [comment]
@iSevenDays When i do signup using latest sdk 2.17.1 ,  i got below error everytime

error: Request failed: unauthorized (401)
reasons: {
    errors =     {
        base =         (
            "Required session does not exist"
        );
    };
}

Please help me if you know anything
