### ISSUE TITLE
connectWithUser:completion: completion block not called after disconnect

### ISSUE THREAD

**Issue by ruipfcosta** [QuickBlox/quickblox-ios-sdk#270]
I'm trying to implement a scenario where the app disconnects from QuickBlox after a call is finished. When a new user wants to make a call, I need to make sure making sure the previous user was disconnected successfully. If the previous user is still connected, I need to disconnect it and connect the new one. 
This is where I'm running into problems: I'm calling ```disconnectWithCompletionBlock:``` with a completion block where ```connectWithUser:completion:``` is called to authenticate the new user. My problem is that ```connectWithUser:completion:``` never calls its completion block.
Can this be a bug on the SDK due to the fact that I'm trying to call connect on the disconnect completion block (is there a better way to do this)?

Thanks in advance!

**Comment by iSevenDays** [comment]
Hi!

Yes, there is might be a problem in calling connectWithUser right after disconnection.

We will investigate this more and will give you an answer.

Thanks for your contribution!

**Comment by Raikerian** [comment]
Hi,

Thank you for reporting the issue, fix will be available in the near future release.

**Comment by iSevenDays** [comment]
Hi!

We have a new Quickblox SDK 2.6.5 with fix you asked us for.

http://quickblox.com/developers/IOS#Download_iOS_SDK

Thanks!

**Comment by ruipfcosta** [comment]
Thanks guys, I confirmed and is working now.
