### ISSUE TITLE
QMChatCollectionView crashes at performBatchUpdates

### ISSUE THREAD

**Issue by kevb10** [QuickBlox/quickblox-ios-sdk#273]
Using:
QMCVDevelopment 0.3.3 (was 0.3.3)
QMServicesDevelopment 0.3.5 (was 0.3.4)
QuickBlox 2.6.3 (was 2.6.2)

I can start a conversation thread and get out of there but if I go back in, it throws an error in the QMChatViewController.m file line 271:
```*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid update: invalid number of sections.  The number of sections contained in the collection view after the update (1) must be equal to the number of sections contained in the collection view before the update (1), plus or minus the number of sections inserted or deleted (1 inserted, 0 deleted).'
***```
And I pretty much followed your demo code. (http://quickblox.com/developers/SimpleSample-chat_users-ios#How_to_start)

**Comment by Raikerian** [comment]
Hi,

Are you unsubscribing from QBChat delegate when leaving chat controller?

**Comment by kevb10** [comment]
Yes I do believe so here is the gist
https://gist.github.com/kevb10/14ba2b37e924c0e925c1#file-chatviewcontroller-m-L209-L222

**Comment by Raikerian** [comment]
Can you send me a test/sample project with this crash being reproducible?

**Comment by kevb10** [comment]
Go ahead and clone https://github.com/kevb10/KevChatDemo 
(using cocoapods)

**Comment by Raikerian** [comment]
You are trying to perform animation before view did appear.

Just replace in viewWillAppear:

```
// Retrieving messages
    if ([[self storedMessages] count] > 0 && self.totalMessagesCount == 0) {
        
        [self insertMessagesToTheBottomAnimated:[self storedMessages]];
        [self refreshMessagesShowingProgress:NO];
    }
```

with

```
// Retrieving messages
    if ([[self storedMessages] count] > 0 && self.totalMessagesCount == 0) {
        
        [self updateDataSourceWithMessages:[self storedMessages]];
        [self refreshMessagesShowingProgress:NO];
    }
```

**Comment by kevb10** [comment]
Awesome. That solved the problem. :+1:
