### ISSUE TITLE
QuickBlox Video upload issue

### ISSUE THREAD

**Issue by ashfaque21** [QuickBlox/quickblox-ios-sdk#274]
Hi Team,

We are trying to upload video file as a content to Quickblox account. We have tried below code for same which has been mentioned for uploading image content. Please find below code snippet.
` NSString *filePath = [[NSBundle mainBundle] pathForResource:@"big_buck_bunny_720p_1mbUpload" ofType:@"mp4"];
    NSError *error = nil;
    NSData *imageData = [NSData dataWithContentsOfFile:filePath options:NSDataReadingMapped error:&error];
    if(imageData == nil && error!=nil)
    {
        NSLog(@"error is : %@",error);
    }
    [QBRequest TUploadFile:imageData fileName:@"big_buck_bunny_720p_1mbUpload.mp4" contentType:@"video/mp4" isPublic:YES successBlock:^(QBResponse *response, QBCBlob *blob)
    {
        blob.ID = 65268; // ID of exists file
        blob.name = @"video";
        // File uploaded, do something
         if (blob.isPublic)
         {
             NSString *url = [blob publicUrl];
         }
    } statusBlock:^(QBRequest *request, QBRequestStatus *status)
    {
        NSLog(@"request status loop.");
    } errorBlock:^(QBResponse *response)
    {
        NSLog(@"error: %@", response.error);
        NSString *errormsg = [NSString stringWithFormat:@"%ld",(long)response.status];
}`

Once I start process for upload, I got below error in console which mention status error as : 422 & "Forbidden, Need User."
Please find below error code for same:

`2016-01-30 22:28:02.276 QuickBloxTest[8216:272675] [QBCore] Request headers: {
    "Content-Type" = "application/json";
    "QB-Account-Key" = qVKXi1WDSqxkBeoYbM3g;
    "QB-OS" = "iOS 9.2";
    "QB-SDK" = "iOS 2.6.3";
    "QB-Token" = 05bbeaaee5bd5f7435b151fb16751a1499b5fc88;
    "QuickBlox-REST-API-Version" = "0.1.1";
}
2016-01-30 22:28:03.835 QuickBloxTest[8216:272672] [QBCore] Response headers: {
    "Access-Control-Allow-Origin" = "*";
    "Cache-Control" = "max-age=0, private, must-revalidate";
    Connection = "keep-alive";
    "Content-Length" = 175;
    "Content-Type" = "application/json; charset=utf-8";
    Date = "Sat, 30 Jan 2016 16:58:03 GMT";
    Etag = "\"6f4e5e7ed781de9132ac224ed7593bdf\"";
    "QuickBlox-REST-API-Version" = "0.1.1";
    Server = "nginx/1.8.0";
    Status = "304 Not Modified";
    "Strict-Transport-Security" = "max-age=15768000;";
    "X-Rack-Cache" = miss;
    "X-Request-Id" = f74e8487838b627020d07521b8c84357;
    "X-Runtime" = "0.004949";
    "X-UA-Compatible" = "IE=Edge,chrome=1";
}
2016-01-30 22:28:03.835 QuickBloxTest[8216:272672] [QBCore] Response object: {
    "account_id" = 43386;
    "api_endpoint" = "https://api.quickblox.com";
    "chat_endpoint" = "chat.quickblox.com";
    "s3_bucket_name" = qbprod;
    "turnserver_endpoint" = "turnserver.quickblox.com";
}
2016-01-30 22:28:03.837 QuickBloxTest[8216:272674] [Core] accountSettings: 
 apiEndpoint: https://api.quickblox.com
 chatEndpoint: chat.quickblox.com, 
 turnServerEndpoint: turnserver.quickblox.com, 
 S3BucketName: qbprod, 
 lastCheckDate: 2016-01-30 16:58:03 +0000
2016-01-30 22:28:03.837 QuickBloxTest[8216:272674] [QBCore] Request URL:https://api.quickblox.com/session.json
2016-01-30 22:28:03.837 QuickBloxTest[8216:272674] [QBCore] Request method: POST
2016-01-30 22:28:03.838 QuickBloxTest[8216:272674] [QBCore] Request parameters:{
    "application_id" = 34256;
    "auth_key" = ObWRQn6fbTmtvzb;
    nonce = 345;
    signature = 7e7db9b56c1cc943ca2451aacf1377b5a0fbd078;
    timestamp = 1454173083;
}
2016-01-30 22:28:03.838 QuickBloxTest[8216:272674] [QBCore] Request headers: {
    "Content-Type" = "application/json";
    "QB-OS" = "iOS 9.2";
    "QB-SDK" = "iOS 2.6.3";
    "QB-Token" = 05bbeaaee5bd5f7435b151fb16751a1499b5fc88;
    "QuickBlox-REST-API-Version" = "0.1.1";
}
2016-01-30 22:28:05.122 QuickBloxTest[8216:272674] [QBCore] Response headers: {
    "Access-Control-Allow-Origin" = "*";
    "Cache-Control" = "max-age=0, private, must-revalidate";
    Connection = "keep-alive";
    "Content-Length" = 257;
    "Content-Type" = "application/json; charset=utf-8";
    Date = "Sat, 30 Jan 2016 16:58:04 GMT";
    Etag = "\"8a67da0de8344b7c41d18fa15e76f043\"";
    "QB-Token-ExpirationDate" = "2016-01-30 18:58:04 UTC";
    "QuickBlox-REST-API-Version" = "0.1.1";
    Server = "nginx/1.6.2";
    Status = "201 Created";
    "Strict-Transport-Security" = "max-age=15768000;";
    "X-Rack-Cache" = "invalidate, pass";
    "X-Request-Id" = 8d9867ceff1bce7d6260a9b981832276;
    "X-Runtime" = "0.027425";
    "X-UA-Compatible" = "IE=Edge,chrome=1";
}
2016-01-30 22:28:05.130 QuickBloxTest[8216:272674] [QBCore] Response object: {
    session =     {
        "_id" = 56aceb9ca0eb47a1a7000015;
        "application_id" = 34256;
        "created_at" = "2016-01-30T16:58:04Z";
        "device_id" = 0;
        id = 15165;
        nonce = 345;
        token = 1b27df50e7a2114739327e28bb05b3e8f194e4f7;
        ts = 1454173083;
        "updated_at" = "2016-01-30T16:58:04Z";
        "user_id" = 0;
    };
}
2016-01-30 22:28:05.134 QuickBloxTest[8216:272672] [QBCore] Request URL:https://api.quickblox.com/blobs.json
2016-01-30 22:28:05.135 QuickBloxTest[8216:272672] [QBCore] Request method: POST
2016-01-30 22:28:05.135 QuickBloxTest[8216:272672] [QBCore] Request parameters:{
    blob =     {
        "content_type" = "video/mp4";
        name = "big_buck_bunny_720p_1mbUpload.mp4";
        public = true;
    };
}
2016-01-30 22:28:05.135 QuickBloxTest[8216:272672] [QBCore] Request headers: {
    "Content-Type" = "application/json";
    "QB-OS" = "iOS 9.2";
    "QB-SDK" = "iOS 2.6.3";
    "QB-Token" = 1b27df50e7a2114739327e28bb05b3e8f194e4f7;
    "QuickBlox-REST-API-Version" = "0.1.1";
}
2016-01-30 22:28:05.453 QuickBloxTest[8216:272672] [QBCore] Response error: Error Domain=com.alamofire.error.serialization.response Code=-1011 "Request failed: client error (422)" UserInfo={com.alamofire.serialization.response.error.response=<NSHTTPURLResponse: 0x7ff84ca2f6d0> { URL: https://api.quickblox.com/blobs.json } { status code: 422, headers {
    "Access-Control-Allow-Origin" = "*";
    "Cache-Control" = "no-cache";
    Connection = "keep-alive";
    "Content-Length" = 45;
    "Content-Type" = "application/json; charset=utf-8";
    Date = "Sat, 30 Jan 2016 16:58:05 GMT";
    "QB-Token-ExpirationDate" = "2016-01-30 18:58:04 UTC";
    "QuickBlox-REST-API-Version" = "0.1.1";
    Server = "nginx/1.6.2";
    Status = "422 Unprocessable Entity";
    "X-Rack-Cache" = "invalidate, pass";
    "X-Request-Id" = e37dce787a87d90779438f99935c7bd7;
    "X-Runtime" = "0.013294";
    "X-UA-Compatible" = "IE=Edge,chrome=1";
} }, NSErrorFailingURLKey=https://api.quickblox.com/blobs.json, com.alamofire.serialization.response.error.data=<7b226572 726f7273 223a7b22 62617365 223a5b22 466f7262 69646465 6e2e204e 65656420 75736572 2e225d7d 7d>, NSLocalizedDescription=Request failed: client error (422)}
2016-01-30 22:28:05.453 QuickBloxTest[8216:272507] error: 
   Error reasons:{
    errors =     {
        base =         (
            "Forbidden. Need user."
        );
    };
}
`
Even if I have added all login credentials in code still I m getting same error.

Kindly do let me know is it possible to upload video files to server in quickblox? If yes, do help me out with my mistake.

Ashfaque.

**Comment by Raikerian** [comment]
Hi,

In order to perform QBRequest operations you need to login in REST using QBRequest loginWithUser methods.

**Comment by Raikerian** [comment]
Any updates? Were you able to fix this?

**Comment by ashfaque21** [comment]
Yes. I am able to resolve that request as I also got understood to login to
Quickblox user.

More than that, now I want to use Augmented reality with Quickblox SDK, I
went through ChattAR app which has been specifically developed for Chat
along with Augmented Reality.

Can I implement Augmented Reality in quickblox in general? If yes, How
should I implement it?

Can I use third party API's to implement same?



On Fri, Feb 5, 2016 at 5:25 PM, Vitaliy Gorbachov <notifications@github.com>
wrote:

> Any updates? Were you able to fix this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/QuickBlox/quickblox-ios-sdk/issues/274#issuecomment-180319282>
> .
>



-- 
Ashfaque H. Tamboli
Pune.
9762478745.

**Comment by iSevenDays** [comment]
Hi ashfaque21!

ChattAR was implemented a very long time ago and by this time we do not support it.

You can use Quickblox SDK with any framework you want to extend its features.

Quickblox SDK provides many great features and you are able to do everything you want.

Quickblox do not provide integrated support for augmented reality, but you are able to do this with Quickblox WebRTC [custom video capture ](http://quickblox.com/developers/Sample-webrtc-ios#Custom_video_capture)

Thanks!

**Comment by mallikaD** [comment]
i am also facing same error while attaching the video in the sample project downloaded from github.Please let me know how to solve this issue.

Please find below error code:
Error Domain=com.alamofire.error.serialization.response Code=-1011 "Request failed: client error (422)" UserInfo={com.alamofire.serialization.response.error.response=<NSHTTPURLResponse: 0x7920eaf0> { URL: https://api.quickblox.com/blobs.json } { status code: 422, headers {
    "Access-Control-Allow-Origin" = "*";
    "Cache-Control" = "no-cache";
    Connection = "keep-alive";
    "Content-Length" = 42;
    "Content-Type" = "application/json; charset=utf-8";
    Date = "Tue, 31 May 2016 07:42:14 GMT";
    "QB-Token-ExpirationDate" = "2016-05-31 09:34:46 UTC";
    "QuickBlox-REST-API-Version" = "0.1.1";
    Server = "nginx/1.8.1";
    Status = "422 Unprocessable Entity";
    "X-Rack-Cache" = "invalidate, pass";
    "X-Request-Id" = 9769a41012ba22c608360a0235356b1b;
    "X-Runtime" = "0.032498";
    "X-UA-Compatible" = "IE=Edge,chrome=1";
} }, NSLocalizedRecoverySuggestion={"errors":{"content_type":["is invalid"]}}, NSErrorFailingURLKey=https://api.quickblox.com/blobs.json, NSLocalizedDescription=Request failed: client error (422), com.alamofire.serialization.response.error.data=<7b226572 726f7273 223a7b22 636f6e74 656e745f 74797065 223a5b22 69732069 6e76616c 6964225d 7d7d>}

**Comment by ashfaque21** [comment]
Hi Mallika,

Could you elaborate more on this. With error code I will not be able to
help you out.

Ashfaque.

On Tue, May 31, 2016 at 2:21 PM, Mallika Damisetty <notifications@github.com
> wrote:

> i am also facing same error while attaching the video in the sample
> project downloaded from github.Please let me know how to solve this issue.
>
> Please find below error code:
> Error Domain=com.alamofire.error.serialization.response Code=-1011
> "Request failed: client error (422)"
> UserInfo={com.alamofire.serialization.response.error.response= { URL:
> https://api.quickblox.com/blobs.json } { status code: 422, headers {
> "Access-Control-Allow-Origin" = "*";
> "Cache-Control" = "no-cache";
> Connection = "keep-alive";
> "Content-Length" = 42;
> "Content-Type" = "application/json; charset=utf-8";
> Date = "Tue, 31 May 2016 07:42:14 GMT";
> "QB-Token-ExpirationDate" = "2016-05-31 09:34:46 UTC";
> "QuickBlox-REST-API-Version" = "0.1.1";
> Server = "nginx/1.8.1";
> Status = "422 Unprocessable Entity";
> "X-Rack-Cache" = "invalidate, pass";
> "X-Request-Id" = 9769a41012ba22c608360a0235356b1b;
> "X-Runtime" = "0.032498";
> "X-UA-Compatible" = "IE=Edge,chrome=1";
> } }, NSLocalizedRecoverySuggestion={"errors":{"content_type":["is
> invalid"]}}, NSErrorFailingURLKey=https://api.quickblox.com/blobs.json,
> NSLocalizedDescription=Request failed: client error (422),
> com.alamofire.serialization.response.error.data=<7b226572 726f7273 223a7b22
> 636f6e74 656e745f 74797065 223a5b22 69732069 6e76616c 6964225d 7d7d>}
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/QuickBlox/quickblox-ios-sdk/issues/274#issuecomment-222629227>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AGd7gVojmrviAUrkMVxEA6_saESpUGACks5qG_aAgaJpZM4HP199>
> .
>



-- 
Ashfaque H. Tamboli
Pune.
9762478745.

**Comment by UpasnaGandhi** [comment]
Hi Mallika, 

I am getting the same error. Could you able to solve the problem? If yes, Then can you please share the solution?

Upasna

**Comment by ashfaque21** [comment]
Please post me error code along with you program.
