### ISSUE TITLE
Documentation updates

### ISSUE THREAD

**Issue by coreman000** [QuickBlox/quickblox-ios-sdk#276]
I'm starter iOS/Swift developer. For now I was very close to send my second App to Apple, but received announcement about Parse - it's closing in a year.
That's not about only me - i think there are lot's of developers - who needed a cheap/free backend, and relied on Parse. So, according to this I have some questions:
- Is Quickblox a real alter to Parse?
- Does Quickblox want to accept big part of Parse Users?
- Is Quickblox going to live long?

Quickblox documentation for iOS and especially for Swift is quite poor. It's hard to see the example project and read it - because I need to get all of it. But for me and lots of others it's more important to see QB Methods another way - clear and with small parts.
I'd like to know how to:
Log in with Login-Password or Social (check if it's a new User)
Write/Read/Delete/Update Custom Classes with simple queries.
And may be some more, but short code snippets, short examples, short examples...
Not too much?

Well, I believe, that I can handle this. But what's the reason to fight?

I think Vitaliy, Anton and Igor can save hours and days and weeks writing some "easy-to-read" Doc.

- My last question is about russian support. I'm not sure, that it's important, but it should be pretty easy for you.

**Comment by soulfly** [comment]
Hi Mikhail, 

> Is Quickblox a real alter to Parse?
Yes, QuickBlox is mainly about real time communications, but in past we were close to what Parse does now.

We provide Users, Push Notifications, Custom Objects modules. This is what we have similar to Parse.
Also we are working on CloudCode feature at the moment (alpha testing)

> Does Quickblox want to accept big part of Parse Users?
Definitely, we are working on Parse-to-QuickBlox guide, which will be released later this week.

> Is Quickblox going to live long?
for sure. We have huge plans how to scale and also have a lot of things in our roadmap.

> Log in with Login-Password or Social (check if it's a new User)
http://quickblox.com/developers/SimpleSample-users-ios#Signing_In_.26_Social_authorization

> Write/Read/Delete/Update Custom Classes with simple queries.
http://quickblox.com/developers/SimpleSample-customObjects-ios

> My last question is about russian support. I'm not sure, that it's important, but it should be pretty easy for you.
yes, we all speak russian, feel free to ask questions in russian

**Comment by coreman000** [comment]
Thanx for the answer. I missed this handy Simple-Sample Doc , sorry. Now I feel, that I made the right choice with you))) 
Good luck guys!

**Comment by Raikerian** [comment]
If you have any other questions please create separate issue :)
