### ISSUE TITLE
how to delete the user from chat dialogs from admin. 

### ISSUE THREAD

**Issue by ajay2c9** [QuickBlox/quickblox-ios-sdk#279]
Hi,
I am using the Quickblox in the my app.We have a option from our admin side that we can disable the user. when the user is disabled from admin we are not showing the user's data. 
 
Is there any api service calling from admin... for removing the user(either admin or like a user (apart from admin)) from dialogs(related to user) at a time.

Please give suggestions

Thank you

**Comment by Raikerian** [comment]
Hi,

After deleting user he will be automatically removed from all group dialogs.

**Comment by ajay2c9** [comment]
Thank you for reply.

Is there any service (from admin side) to delete the user?

Please give suggestions

Thank you

**Comment by Raikerian** [comment]
Do you want to delete user completely from app or from a specific chat?

**Comment by ajay2c9** [comment]
I want to remove the user from complete app.

**Comment by Raikerian** [comment]
You can completely remove from the app only current user using this method:

```objectivec
/**
 Delete Current User
 
 @note You should login firstly in order to delete current user
 
 @param successBlock Block with response instance if request succeded
 @param errorBlock Block with response instance if request failed
 
 @return An instance of QBRequest for cancel operation mainly.
 */
+ (QB_NONNULL QBRequest *)deleteCurrentUserWithSuccessBlock:(QB_NULLABLE void (^)(QBResponse * QB_NONNULL_S response))successBlock
												 errorBlock:(QB_NULLABLE void (^)(QBResponse * QB_NONNULL_S response))errorBlock;
```

**Comment by ajay2c9** [comment]
My requirement is to delete the user from admin side, not from the app side.

**Comment by iSevenDays** [comment]
Hi ajay2c9!

You are able to delete any user in Admin Panel.

With API you can delete only your current user.

Thanks!

**Comment by ajay2c9** [comment]
Thank you for reply.

I have 2 admins (admin panels) one is My app admin(A) and other is Quickblox admin panel(B).In my app (A) admin panel, List of users are displaying with one button "Disable".
             My requirement is When admin select the "Disable" button. In my app (A) admin panel I need to remove the user from both admin panel. In our (A) admin panel we are removing the user when the "Disable" Button is selected.This total functionality  is handled by our server side.
          I understand your answer i.e select the user in admin panel and select the remove selected option.User is deleted. 
             My intension is that any quickblox service(Api) is called from our server end. that remove the user in Quickblox admin panel, Without selecting the user from Quickblox admin panel.
                             
![screen shot 2016-02-08 at 3 10 48 pm](https://cloud.githubusercontent.com/assets/9112899/12882269/67071f5a-ce76-11e5-8e94-448471bfca62.png)
