### ISSUE TITLE
Landscape mode issue.

### ISSUE THREAD

**Issue by wonderfulmobileworld** [QuickBlox/quickblox-ios-sdk#280]
Hello.. 

I am trying scaled screen in landscape mode of the ios version. so localvideo view is available to the scaled screen but remote Video view does not implemented for scaled screen.
anyway, I did tried for solution but did not found the best yet. 
I hope to quickblox's guide for it.

Regards:)

**Comment by Raikerian** [comment]
Hi,

What do you mean by scaled screen?
If you are talking about VideoGravity: https://github.com/QuickBlox/quickblox-ios-sdk/issues/252

**Comment by wonderfulmobileworld** [comment]
yes right.
I mean, AVLayerVideoGravityResizeAspectFill property. anyway, I did change the gravity of the local video view as ResizeAspectFill.
but QBRTCRemoteVideoView does not work with this property. 

How to change the gravity of the QBRTCRemoteVideoView ?

Regards.

**Comment by Pro100Andrey** [comment]
Hi @wonderfulmobileworld! Please check answer https://github.com/QuickBlox/quickblox-ios-sdk/issues/252

**Comment by Raikerian** [comment]
Were you able to fix this using category?

**Comment by wonderfulmobileworld** [comment]
Hi,

right. I was tried with VideoGravity category. anyway, I could not found the this category from QuickbloxWebRTC framework. so i was make the custom category like answer #252.
and I was use the this view category on the videoViewWithOpponentID function of the CallViewcontroller view class.
but remote video view does not work anything.

Regards.

**Comment by Raikerian** [comment]
Were you able to fix this issue?

**Comment by argonaut1** [comment]
No, could not get it work. Any additional suggestions, code snippet example?
@wonderfulmobileworld @Raikerian

**Comment by Raikerian** [comment]
@argonaut1 no results with AVLayerVideoGravityResizeAspectFill ?

**Comment by Raikerian** [comment]
Closing this for now due to tracking purposes.
If you are still experiencing this issue just reopen it and post updates.
If you are having any other troubles feel free to let us know by creating a separate issue.
