### ISSUE TITLE
Recording remote view

### ISSUE THREAD

**Issue by argonaut1** [QuickBlox/quickblox-ios-sdk#281]
@Raikerian  On original video chat demo i did some changes so now it works more like Periscope app. One user "broadcasting" and other user( Viewer)  is watching( full screen) broadcast. According to documentation, it is possible to record local camera view to Camera Roll so in this case I am able to record it on the phone that user does "broadcasting". What i would like to be able to do is to record video on the other side, Viewer's side.
I was told to use this  approach http://quickblox.com/developers/Sample-webrtc-ios#Custom_video_capture    but i am not really sure how to proceed and how to make it work.

**Comment by iSevenDays** [comment]
Hi, argonaut1!

This feature is planned for the next release in the near future and soon you will see how to do it.
Also, of course, we will show you our sample application.

Thanks!
