### ISSUE TITLE
Target has transitive dependencies that include static binaries:

### ISSUE THREAD

**Issue by abhineet-mobile** [QuickBlox/quickblox-ios-sdk#284]
hi
 Analyzing dependencies
Downloading dependencies
Installing Bolts (1.5.0)
Installing QMServices (0.3.5)
Installing QuickBlox (2.6.5)
[!] The 'Pods-SwiftQuickBloxApp' target has transitive dependencies that include static binaries: (/Users/4bitappsutios/Desktop/SwiftQuickBloxApp/Pods/QuickBlox/Quickblox.framework)
I am facing the problem while i am trying to download the Qmservices using cocospods
The Podfile i.e. i am using as
 platform :ios, '8.0'

use_frameworks!

target 'SwiftQuickBloxApp' do

pod 'QMServices', '~> 0.3'

end

target 'SwiftQuickBloxAppTests' do

pod 'QMServices', '~> 0.3'
end
Please help me how can i solve this problem
Thanks.

**Comment by Raikerian** [comment]
Hi!

We are aware of this issue, unfortunately we don't have Quickblox built as a dynamic framework. Mainly because we still need to support iOS 7.
So, removing option 'use_frameworks!' from your Podfile will fix described issue.

We will try to find out more appropriate solution in nearest future.
