### ISSUE TITLE
App admin want to delete the users  programaticaly.

### ISSUE THREAD

**Issue by ajay2c9** [QuickBlox/quickblox-ios-sdk#285]
Hi.
We are using the Quickblox in our app.My app admin want to delete the users programmatically. how to delete the users from Quickblox admin panel (Programmatically) from admin side.

Note:We are saving the Quickblox login id in our admin panel.

![screen shot 2016-02-08 at 3 10 48 pm](https://cloud.githubusercontent.com/assets/9112899/12882619/e07b282a-ce78-11e5-8426-1a14010e5e2e.png)

Please give suggestions.

**Comment by iSevenDays** [comment]
1. Go to http://admin.quickblox.com/apps
2. Create new App
3. Then go to edit panel http://admin.quickblox.com/apps/<your_application_id>/edit
4. And straight to Users(you have that button on the left side panel) http://admin.quickblox.com/apps/<your_application_id>/service/users
5. You will see only one created default user

This user has super admin privileges. Only this user can delete everything in your application


Login with that default user and then with JS api you can delete any user you want

Thanks!
