### ISSUE TITLE
new or old user? and can i add custom field to QBUUser.

### ISSUE THREAD

**Issue by coreman000** [QuickBlox/quickblox-ios-sdk#286]
For example, i want to add a wallet with 100 coins to new created user.

first of all i try to discover is this new user or not 

     func signInToQuickblox (tokenString: String) {
        QBRequest.logInWithSocialProvider("facebook", accessToken: tokenString, accessTokenSecret: nil, successBlock: { (response: QBResponse, user: QBUUser?) -> Void in
            // user signed in
            if QBSession.currentSession().currentUser?.lastRequestAt == nil {    
            // add wallet to user            
            }
            }, errorBlock: { (errorResponse: QBResponse) -> Void in
                //process Error
        })        
    }

but i'm not sure, that this would work properly.

second - is it possible to add Uint field "wallet" to QBUUser ?

**Comment by iSevenDays** [comment]
Hi coreman000,

Yes, it is possible. Please use QBUUser customData property.

**Comment by iSevenDays** [comment]
Hi,

We haven't heard back from you in a few days, so we are marking this post as Closed for tracking purposes. If you're still experiencing this issue, please provide us with additional information.
