### ISSUE TITLE
XCode LLDB debug doesn't work with version 2.6.5

### ISSUE THREAD

**Issue by thebrankoo** [QuickBlox/quickblox-ios-sdk#287]
When application stops at some breakpoint I can't see current variables in xcode debugging console. I only see varible names without any values like on image below:
<img width="406" alt="screen shot 2016-02-08 at 10 46 48 pm" src="https://cloud.githubusercontent.com/assets/15704568/12900402/7b38edb0-ceb6-11e5-93bb-4f48c8429a2e.png">
When I try to print variable descrption I get: Unable to determine byte size.
When I run po or print command I get huge list that looks like this (it's only starting of list, but everything is similar to this)
![ex](https://cloud.githubusercontent.com/assets/15704568/12900731/2a52f07e-ceb8-11e5-92c9-57d529141dc5.png)

I'm using cocoapods to generate project with quickblox sdk and I put @ import Quickblox; in my bridging header.

Anyone knows how to enable normal xcode debugging?

**Comment by iSevenDays** [comment]
Hi thebrankoo,

Please tell us:
1. Xcode version you use
2. Which operating system?
3. Does this problem exist on 2.6.2, 2.6.3, 2.6.4 sdk?
4. Does this problem only with swift and not with Objective C?
5. If it is possible, please attach your test project

Thanks!

**Comment by thebrankoo** [comment]
@iSevenDays 
1. Xcode version: 7.2.1
2. OS: OS X El Capitan 10.11.3
3. This problem existed on 2.6.4. I did't use prior versions.
4. My project is completely in Swift, so I didn't try Objective C
5. Unfortunately I can't share my whole project, but here's how bridging header looks like
```swift
#import <Parse/Parse.h>
#import <PubNub/PubNub.h>
#import <CocoaLumberjack/DDLog.h>
@import Quickblox;
```
I've also tried to create simple project that has the same problem as my main project but I didn't manage to build it since Xcode is complaining about "Include of non-modular header" inside framework module QuickBlox. That test project can be found here https://github.com/thebrankoo/QBFailTestProject
I've used same Podfile as in my original project, and all dependecies are the same.

**Comment by iSevenDays** [comment]
Hi! I'm unable to build your test project

Also we do not support !use_frameworks

https://github.com/QuickBlox/QMChatViewController-ios/issues/5

**Comment by thebrankoo** [comment]
I've just managed to fix this by stop using cocopods. 
The solution is to add framewrok to the project without using cocopods (like it's decribed here http://quickblox.com/developers/IOS-how-to-connect-Quickblox-framework). 

I couldn't remove !use_frameworks since other framewroks need that line. It seems that there are some problems when installing this sdk using cocopods.

**Comment by iSevenDays** [comment]
Thank you for reporting your solution!

**Comment by ankitaugurs** [comment]
Does Quick blox work on Xcode 7.2.1?  Kindly reply
