### ISSUE TITLE
Core Data Migration Problem going from 2.6.4 -> 2.6.5?

### ISSUE THREAD

**Issue by coredream** [QuickBlox/quickblox-ios-sdk#288]
Hi, I'm seeing an issue with core data when upgrading to 2.6.5.  Please consider this case:

1. I currently have an app in the AppStore running QuickBlox 2.6.4 and QMServices 0.3.5
2. I release a new version in the AppStore running QuickBlox 2.6.5 and QMServices 0.3.6

When the new version is installed and starts up, there is an error "The model used to open the store is incompatible with the one used to create the store", which is probably as expected.  However, I don't see that the DB actually gets upgraded/migrated after this.  Since QM_shouldDeletePersistentStoreOnModelMismatch is set to NO, no action seems to take place, and the persistent store is nil through the lifetime of the app.

When trying to enter a group dialog for the first time, I'm seeing error: "Illegal attempt to save to a file that was never opened.  "This NSPersistentStoreCoordinator has no persistent stores (schema mismatch or migration failure).  It cannot perform a save operation.".

I can recreate this using the sample-chat app in your SDK with these steps:

1.  git checkout 45482f73b1274e4363726e9312ca4376daf7ee81 (which should be 2.6.4).
2.  Run sample-app, login as any user.
3.  git checkout 825f00572d35de6d1dd0c1b5505eb67d3f9b78aa (which should be 2.6.5).
4.  Run sample-app, login as same user.
5.  Observe core data error at startup, and error when first entering each group dialog.
6.  Restart app, same errors still appear.

Additional note: DialogsViewController is empty if you never logout (I believe that is due to lastActivityDate not being set to nil).

**Comment by iSevenDays** [comment]
Hi coredream,

Thank you for reporting this bug!

I was able to reproduce the issue.

You can check my fix in feature/coreVersion branch in q-municate-services-ios repo. https://github.com/QuickBlox/q-municate-services-ios

To use this fix right now please change the following lines in pod file

#Production pod
pod 'QMServicesDevelopment', :git => 'git@github.com:QuickBlox/q-municate-services-ios.git', :commit => '87d96dc8c1ec78712f305a0bd0219c443e7e3a16'

We will release updated version in master soon.

Thanks!

**Comment by tomahn** [comment]
Thanks for the quick update @iSevenDays

**Comment by coredream** [comment]
Thanks for the quick update @iSevenDays

**Comment by iSevenDays** [comment]
Fix with CoreData was merged https://github.com/QuickBlox/q-municate-services-ios/pull/122

Thank you for your report!
