### ISSUE TITLE
Quickblox + Augmented Reality integration

### ISSUE THREAD

**Issue by ashfaque21** [QuickBlox/quickblox-ios-sdk#289]
Hi Team,

We would like to implement Augmented Reality in Quickblox SDK. I got to know that there is QuickBloxWebRTC framework is available for same.

Below are my questions related with Augmented Reality Integration
1. Do I need to integrate any other 3rd party Framework for AR?
2. Should I use same API for uploading video on Quickblox cloud?
3. Will AR API or QuickBlox API support each other?

Kindly give me some clue so that I can start implementing it.

Ashfaque

**Comment by iSevenDays** [comment]
Hi ashfaque21,

1. Quickblox does not provide API for augmented reality, you have to implement this by yourself.
For example, you can use QuickbloxWebRTC with custom capture and GPUImage for image effects, post-processing

2. You can use Quickblox for uploading files.

3. It depends on you. You can use Quickblox to improve AR experience and to have chat/video-chat/custom objects(custom tables)

Thanks!

**Comment by iSevenDays** [comment]
We haven't heard back from you in a few days, so we are marking this post as Closed for tracking purposes. If you're still experiencing this issue, please provide us with additional information.

**Comment by ashfaque21** [comment]
Hi,

Sorry for delay. 

Actually we want to integrate third party AR SDK with our Quickblox App but we are not understanding how to stream our 3D video from Quickblox cloud server. 

It will be good if you help us here about same.

Ashfaque
