### ISSUE TITLE
How to integrate the latest QMChatViewController and QMServices in the  project.

### ISSUE THREAD

**Issue by ajay2c9** [QuickBlox/quickblox-ios-sdk#291]
Hi ,
I am using Quickblox sdk in a project. I want to update the Quickblox.I don't understand how to update it. I checked in podfile in chat sample(new one) it shows the pods like this                                                  
pod 'QMCVDevelopment'
pod 'QMServicesDevelopment' 

while adding these two in pod file and while installing using the terminal it shows some
![screen shot 2016-02-12 at 2 40 25 pm](https://cloud.githubusercontent.com/assets/9112899/13002710/ad110b28-d196-11e5-8d0a-ba564455ab0d.png)

How to install pods of QMChatViewController and QMServices

Please Give suggestions 

Thank you

**Comment by iSevenDays** [comment]
Hi ajay2c9,

What happens if you enter "yes" ?

It seems that you was not able to connect to github.

This may help you https://help.github.com/articles/set-up-git/
https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/

If you still have problems, please describe them in details

Thanks!

**Comment by ajay2c9** [comment]
Hi iSevenDays,

Thank you for Reply.

If i enter "yes" it shows like this.
![screen shot 2016-02-12 at 6 00 20 pm](https://cloud.githubusercontent.com/assets/9112899/13006975/cd429a4e-d1b2-11e5-9243-4d654010b5bb.png).

Is there any other way to install these pods (pod 'QMCVDevelopment'
pod 'QMServicesDevelopment') easily .I mean just add them in pod file and enter pod install in terminal. it install directly like other pods are installing. 

If possible please suggest in that way.If not, please guide me that i can easily integrate in to my app.

Thank you.

**Comment by iSevenDays** [comment]
Hi 

You should specify git repo because Development pods are not in CocoaPods master repo.

pod 'QMServicesDevelopment', :git => 'git@github.com:QuickBlox/q-municate-services-ios.git', :commit => '1fa05f5cea6ff10a2bd216a154233eba51100bd8'
pod 'QMCVDevelopment', :git => 'git@github.com:QuickBlox/QMChatViewController-ios.git', :commit => '74f5c78fca84f947c2b9d67a12fb4892e8576e30'

Thanks!

**Comment by ajay2c9** [comment]
Thank you for Reply.

$ cd MyXcodeProjectFolder
$ git submodule add https://github.com/QuickBlox/quickblox-ios-sdk.git Vendor/QMServices
$ git commit -m "Added QMServices submodule"

Is the above process is correct to add those pods(QMChatViewController and QMServices).
The link i added above is quickblox git link.

If the process is wrong please suggest me elaborately . I didn't get the above process.

**Comment by Raikerian** [comment]
Hi,

In your error using cocoapods you can see this:
> Permission denied (publickey).

Looks like you haven't set up neither github credentials nor ssh key. Please check it out: https://help.github.com/articles/set-up-git/

> If the process is wrong please suggest me elaborately . I didn't get the above process.

It is correct. We also have manual installation guide in both QMChatViewController and QMServices repo.

**Comment by Raikerian** [comment]
@ajay2c9 
Were you able to fix this issue?

**Comment by Raikerian** [comment]
If you are still having any troubles please let us know by creating a separate issue.

**Comment by swetaagicent** [comment]
getting same error

**Comment by swetaagicent** [comment]
can i add both folders manually

**Comment by ajay2c9** [comment]
For me development pods are not installed. I Install main pods i.e pod 'QMServices'
pod 'QMChatViewController' and modified the changes.

**Comment by swetaagicent** [comment]
how could i install with pods? m getting same error

**Comment by ajay2c9** [comment]
For which pods you are getting issues first or second in below
1. pod 'QMServices'   pod 'QMChatViewController'
2. pod 'QMCVDevelopment' pod 'QMServicesDevelopment'

**Comment by swetaagicent** [comment]
pod 'Alamofire', '~> 3.0'
pod 'AlamofireImage'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'ReachabilitySwift', '~> 2.4'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'Firebase/Core'
pod 'Firebase/Messaging'



pod 'QMServicesDevelopment', :git => 'git@github.com:QuickBlox/q-municate-services-ios.git', :commit => '1fa05f5cea6ff10a2bd216a154233eba51100bd8'

pod 'QMCVDevelopment', :git => 'git@github.com:QuickBlox/QMChatViewController-ios.git', :commit => '74f5c78fca84f947c2b9d67a12fb4892e8576e30'

**Comment by ajay2c9** [comment]
I faced the same problem what you are facing now. Instead of those development pods. try these pods.  pod 'QMServices' pod 'QMChatViewController' . You will get the solution.

**Comment by swetaagicent** [comment]
by using pod 'QMServices' pod 'QMChatViewController' m getting error i.e
Type 'ServicesManager' has no member 'instance'

**Comment by swetaagicent** [comment]
in Bridging_Header how to add QMServices

**Comment by ajay2c9** [comment]
you are getting error missing files QMServicesManager class. Add ServicesManager.h and ServicesManager.m files from quickblox chat sample and check once again .The error will be removed.

**Comment by swetaagicent** [comment]
still getiing error 'QMServicesManager.h' file not found after adding ServicesManager.h file
