### ISSUE TITLE
UICollectionView not showing recent messages after "Send" action

### ISSUE THREAD

**Issue by kevb10** [QuickBlox/quickblox-ios-sdk#293]
This actually used to work before but now after sending a message it doesn't insert a new cell. This behavior only happens in private chat mode. If it's a group chat it works fine. I have the gist below. 
https://gist.github.com/kevb10/f8daff4555088d64d9d4

  - QMServicesDevelopment (0.3.6)
  - QuickBlox (2.6.5)

**Comment by Raikerian** [comment]
Hi,

Add breakpoint to 'didAddMessageToMemoryStorage' delegate method to see if it's called when you are sending private message.

Also check out our latest samples with latest QMChatViewController, we have improved them alot :)

**Comment by iSevenDays** [comment]
Hi kevb10, have you resolved your problem?

**Comment by Raikerian** [comment]
If you are still having any troubles please let us know by creating a separate issue.

**Comment by sushmithaGope** [comment]
I'm facing this same issue.

**Comment by VitaliyGuru** [comment]
@sushmithaGope, Hello.
Please create a separate issue and provide as much information as you can.
