### ISSUE TITLE
How can I get online/offline status of a member that is not my friend?

### ISSUE THREAD

**Issue by tranngoclinh88** [QuickBlox/quickblox-ios-sdk#294]
Please help me with the question above.

**Comment by iSevenDays** [comment]
Hi tranngoclinh88,

Please see http://quickblox.com/developers/SimpleSample-users-ios#Online.5COffline_status

**Comment by nikeboi89** [comment]
Hi all,

I tried but I can't get other user's lastRequestAt. It is null all the time. I only can get lastRequestAt of current user. Is there other way to determine the status?

Thanks!

**Comment by Raikerian** [comment]
Hi,

lastRequestedAt of user is only available if you are getting user from REST (e.g. QBRequest methods).
I have tested it and it is working as intended.

**Comment by nikeboi89** [comment]
Thanks! It works. I have another question regarding this.
How can I get online users in a dialog that is a group chat? I use requestOnlineUsersWithCompletionBlock of QBChatDialog but it only returns current user's id. I also tried to get users by ID use usersWithIDs of QBRequest but lastRequestAt is null.

**Comment by Raikerian** [comment]
Seems like you have created separate issue already, closing this.
