### ISSUE TITLE
fetch request by UserID field

### ISSUE THREAD

**Issue by coreman000** [QuickBlox/quickblox-ios-sdk#295]
Hi! Is it possible to pull "this User" Custom object? Only objects created by himself. 
If I try something like this - 

    QBRequest.objectsWithClassName("UserNotes", extendedRequest: ["UserID" : QBSession.currentSession().currentUser!.ID], 
    successBlock: { (response : QBResponse, retreivedNotes : [QBCOCustomObject]?, page: QBResponsePage?) -> Void in
    ...
    }

... i receive ALL the notes. Unsurprisingly. Because built-in UserID is not contained in "fields".

should I add custom userID field (that would be weird)?

**Comment by coreman000** [comment]
Sorry, found the answer, feel like an idiot. field name should be "user_id".
May be it's reasonable to make this more clear in the docs? ;-)

**Comment by iSevenDays** [comment]
Hi coreman000,

Thank you for the feedback!

In the near future we will improve our documentation to be more user friendly .

Thanks!
