### ISSUE TITLE
Array Index Out of Range - ServicesManager filtered User

### ISSUE THREAD

**Issue by lenichols** [QuickBlox/quickblox-ios-sdk#298]
I am getting a weird error when I try to simulate the sample chat. "Array Index out of Range" and simulator quits in error at this line:

`let filteredUsers = unsortedUsers[0..<kUsersLimit].filter { (user: QBUUser) -> Bool in return user.login?.lowercaseString.rangeOfString(containsString) != nil }`

I am using the Swift example. Not sure how to get past this error. Saw someone else had the same issue but the answer wasn't clear. What am I missing here? I did create 1 user and tag that user 'dev' but it still crashes. I'm assuming im not the only one with this issue. How would I resolve this?

**Comment by Raikerian** [comment]
Hi,

checkout this issue: https://github.com/QuickBlox/quickblox-ios-sdk/issues/290

We will simplify our samples users logic in a near future.
