### ISSUE TITLE
EndpointsAPIStorage retrieveEndpoints Bad Access

### ISSUE THREAD

**Issue by shillam** [QuickBlox/quickblox-ios-sdk#30]
We are currently using version 1.9.2 of the iOS SDK in a production app and the iOS 8 update has caused frequent crashing when trying to retrieve custom objects. It's always the same Quickblox method, [EndpointsAPIStorage retrieveEndpoints]. I noticed you have implemented a fix in version 2.0.9 of the SDK. Are you able to implement the same fix into version 1.9.2? Or do you have any workarounds?
![screen shot 2014-11-21 at 09 29 53](https://cloud.githubusercontent.com/assets/5928460/5140278/005ad09e-7161-11e4-9aec-436ce8e39cef.png)

**Comment by shillam** [comment]
Any update on this issue?

**Comment by iSevenDays** [comment]
Please use our new SDK 2.2.4 http://quickblox.com/developers/IOS#CocoaPods_integration. If you still have problems, please do let us know and send us your crash log.
