### ISSUE TITLE
How to Invalidate Session Token. 

### ISSUE THREAD

**Issue by itsaboutcode** [QuickBlox/quickblox-ios-sdk#301]
I believe following method should invalidate the token, but it don't. Just wondering how to invalidate it?

`[QBRequest logOutWithSuccessBlock:errorBlock:]`

**Comment by Raikerian** [comment]
Hi,

Please use this method:
`/**
 Session Destroy
 
 @param successBlock Block with response instance if request succeded
 @param errorBlock Block with response instance if request failed
 
 @return An instance of QBRequest for cancel operation mainly.
*/
+ (QB_NONNULL QBRequest *)destroySessionWithSuccessBlock:(QB_NULLABLE void (^)(QBResponse * QB_NONNULL_S response))successBlock
                                              errorBlock:(QB_NULLABLE QBRequestErrorBlock)errorBlock;`
