### ISSUE TITLE
How can I get list of online users in group chat?

### ISSUE THREAD

**Issue by nikeboi89** [QuickBlox/quickblox-ios-sdk#302]
How can I get online users in a dialog that is a group chat? I use requestOnlineUsersWithCompletionBlock of QBChatDialog but it only returns current user's id. I also tried to get users by ID use usersWithIDs of QBRequest but lastRequestAt is null.

**Comment by Raikerian** [comment]
Hi,

In order to get list of online users in group chat with that method, you need to join chat dialog first.
Use 'joinWithCompletionBlock' method of QBChatDialog.

**Comment by nikeboi89** [comment]
Hi,

I have already joined the group. But can't get the list of online users. I used joinWithCompletionBlock again but still can't. There is an error: Error Domain=com.quickblox.chat Code=-1006 "(null)" UserInfo={NSLocalizedRecoverySuggestion=You are already joined to the dialog.}

Please check!

Thanks!

**Comment by Raikerian** [comment]
I have just checked requestOnlineUsersWithCompletionBlock method and it is working file. Are you sure that there is some one online in the group except you? :)
