### ISSUE TITLE
Push notification not working 

### ISSUE THREAD

**Issue by iPhoneyDev** [QuickBlox/quickblox-ios-sdk#303]
Hi,

I am able to send message but not able to send to push notification.

       [QBRequest` createEvent:event successBlock:^(QBResponse *response, NSArray *events) {
            // Successful response with event
            NSLog(@"Private push notification success");
            
        } errorBlock:^(QBResponse *response) {
            // Handle error
            NSLog(@"Private push notification failure");
            
        }]
Here I am getting success message and also in my admin panel it is showing sent in Push notification section.But I am unable to receive notification in iOS or Android.

Could you please check once.

Thanks

**Comment by iPhoneyDev** [comment]
Could you please reply on this?

**Comment by Raikerian** [comment]
Hi,

Try resetting your location settings in iOS device.
Also check if you have registered your app for push notifications: https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/IPhoneOSClientImp.html

**Comment by iPhoneyDev** [comment]
Hi,

Earlier we have tested in the same iphone, it was working fine. From mobile to quickblox it is going but from quickblox it is not coming to the phone. Please check on this.

Thanks

**Comment by Raikerian** [comment]
Please specify:
1. Your account plan.
2. Are you sure that subscription with createSubscription method went through without any errors?
3. Are you sure that device is registered and AppDelegate's didRegisterForRemoteNotificationsWithDeviceToken was called?
4. Try to set a breakpoint to didReceiveRemoteNotification AppDelegate method and see if it gets called after you sending push notification from admin panel.

**Comment by iPhoneyDev** [comment]
Hi,

Today it is working. I havent changed anything but its working today.

**Comment by Raikerian** [comment]
Good to see it is working.

If you are still having any troubles please let us know by creating a separate issue :)
