### ISSUE TITLE
Push notifications are not receiving.

### ISSUE THREAD

**Issue by ajay2c9** [QuickBlox/quickblox-ios-sdk#304]
HI,
Push notifications are not receiving to the devices.I registered with new user. device subscription is added to the user in the admin panel and when push notification is send,it shows the success status 201.In admin  panel Push notification status shows as sent. but i am not receiving any push notifications.Even push notification send from the admin panel i am not receiving the pushnotification.

QBMPushMessage *messageQB = [[QBMPushMessage alloc] initWithPayload:payload];
                                   
                                   NSMutableArray*dialogArray=[dialog.occupantIDs mutableCopy];
  NSUInteger senderid=dialog.lastMessageUserID;
 [QBRequest sendPush:messageQB toUsers:str successBlock:^(QBResponse *response, QBMEvent *event)  {
   NSLog(@"success is %@",response.description);
                                    } errorBlock:^(QBError *error)
                                    {
                                        NSLog(@"send error %@",error);
                                    }];

Thank you

**Comment by Raikerian** [comment]
Hi,

Try resetting your location settings in iOS device.
Also check if you have registered your app for push notifications: https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/IPhoneOSClientImp.html
