### ISSUE TITLE
Error while debugging: include of non-modular header inside framework module 'Quickblox'

### ISSUE THREAD

**Issue by tonchis** [QuickBlox/quickblox-ios-sdk#306]
Hello @QuickBlox-team! I'm experiencing an error in the debugger when using the `po` command, which doesn't let me debug.

```
    Swift had fatal errors constructing the ast context for this module: <module-includes>:1:9: note: in file included from <module-includes>:1:
#import "/Users/tonchis/code/properati/chaterati-ios/Pods/QuickBlox/Quickblox.framework/Headers/Quickblox.h"
        ^
/Users/tonchis/code/properati/chaterati-ios/Pods/QuickBlox/Quickblox.framework/Headers/Quickblox.h:9:9: error: include of non-modular header inside framework module 'Quickblox'
#import <Quickblox/BaseServiceFramework.h>
```

[Here's the full log](https://gist.github.com/tonchis/1d56d3d0a4b6d4fb61d8). Instead of crash-and-burning in the inaccurate attempt of explaining what I tried and didn't work to resolve this, let me point you to the links and docs I've been looking at:

* https://github.com/CocoaPods/CocoaPods/issues/4420
* https://forums.developer.apple.com/thread/23554 (ddunbar's response)

Also:
* I'm using Cocoapods v1.0.0.beta.3
* I'm using Swift. My bridging header import line is `#import "Quickblox/Quickblox.h"`. I still get the same error using `@import Quickblox;`

I reckon this problem is a bit out of my league, so working together to solve this would be great.

Thanks!

**Comment by tonchis** [comment]
So I just arrived to #287 and I see the problem lays in using `use_frameworks!` in the Podfile.

Other dependencies in my project need to be frameworks so I was wondering if there's a plan to support this anytime soon.

Thanks again :)

**Comment by Raikerian** [comment]
Hi,

Unfortunately we doesn't have framework build as dynamic framework, mainly because we still need to support iOS 7. We are planning to do it, but there is no ETA yet.
There is a workaround for you, just install Quickblox iOS SDK manually, and not using cocoapods.

**Comment by tonchis** [comment]
@Raikerian ahh, I see. I actually tried to fork this repository in the hopes I could find the way to make it build as a dynamic framework (never done this before), but I wasn't able to even find the `.podspec` to get started.

I ended up installing manually without cocoapods, yes. I'd love to give my fork a try, to make it compatible with Cocoapods for iOS8+ but I would need some help from you to get me started. What do you think?

**Comment by Raikerian** [comment]
Unfortunately our SDK is private and we are not planning to release it source files in a near future.

**Comment by tonchis** [comment]
@Raikerian I understand. We're good to close this, then.
