### ISSUE TITLE
Quick blox IOS SDK give error like "APNS (Apple Push) is not enabled for the current application" while sending push notification

### ISSUE THREAD

**Issue by nirav700** [QuickBlox/quickblox-ios-sdk#307]
I am using Quick Blox IOS SDK Latest Version in my application, I am implementing one to one push notification , I have setup only Production certification on admin panel and try to send push notification, but when ever try to send push notification its give error like "APNS (Apple Push) is not enabled for the current application. Please enable this notification channel in the settings tab of the admin panel"

can anybody guide me what i am doing wrong here.....

**Comment by Raikerian** [comment]
Hi,

Have you set up development certificate as well? We have auto environment detection in our SDK, so if you are sending push notifications from app using development provision, it will only send push notifications to development environment.

**Comment by nirav700** [comment]
@Raikerian thanks for guide... yes now i am getting push notification on production , because i am trying to send push notifications from development to production not to production to production thats why its cause problem

Thanks for quick guide..

**Comment by Raikerian** [comment]
Good to see that you have fixed it.
If you are still having any troubles please let us know by creating a separate issue :)

**Comment by iosdoth** [comment]
I have same problem. I have upload both development and production certificates on quickblox admin panel.
