### ISSUE TITLE
Is there a way to execute a batch maintenance job in an app account

### ISSUE THREAD

**Issue by cvezina** [QuickBlox/quickblox-ios-sdk#310]
This is a must in order to purge data that are no longer used or simply to fix incoherence in the data due to bugs

**Comment by iSevenDays** [comment]
Hi cvezina,

Please explain your problem with more detail.

Thanks

**Comment by cvezina** [comment]
Hi,

It is not really a problem. I need to do some clean up batch task. For exemple, remove custom contents that are no longer being used. I guess I can create an iOS app for management task that would use the admin credential to do this kind of task. Another example, is that since we are in development mode, I often need to clean up the app account but there is no easy way to do this. I have to check each item individually to remove them (no select all is available).

Thanks,

Claude Vezina
PCV

**Comment by iSevenDays** [comment]
Hi cvezina,

Sorry for delayed answer.

By default in Admin panel you have one user - it is the only one user with admin privileges, he can delete everything from your account.

You can login with that user and perform any action you want
http://quickblox.com/developers/Javascript

https://github.com/QuickBlox/quickblox-ios-sdk/issues/285

**Comment by Raikerian** [comment]
Were you able to accomplish this?

**Comment by Raikerian** [comment]
Closing this for tracking purposes for now.
If you are still having this issue feel free to reopen it and post updates.
If you are having any other troubles, just create a separate issue :)
