### ISSUE TITLE
add feature

### ISSUE THREAD

**Issue by spyexe1** [QuickBlox/quickblox-ios-sdk#312]
hello 
can you please add some feature to source code for both ios and android
send location
voice message
video message
and there is some thing else
read feature not working on q-municate app on app store I download it and noticed this feature not working

**Comment by iSevenDays** [comment]
Hi spyexe1,

Thanks for the feedback, we will take this into consideration.

Also we update q-municate frequently so stay tuned.

Thanks!

**Comment by Raikerian** [comment]
Hi @spyexe1 

> read feature not working on q-municate app on app store I download it and noticed this feature not 
Please specify you case a little bit in a details. You can also download [Q-municate](https://github.com/QuickBlox/q-municate-ios) and test it by yourself.

**Comment by Raikerian** [comment]
We haven't heard any updates from you, so I'm closing this for tracking purposes.
In order to receive updates about Quickblox new features, follow our [blog here](http://quickblox.com/blog/).
