### ISSUE TITLE
Xcode does not show values

### ISSUE THREAD

**Issue by coreman000** [QuickBlox/quickblox-ios-sdk#313]
Hi. I've got an issue, Xcode does not show variables values on breakpoint. Full description is [here](http://stackoverflow.com/questions/35674870/xcode-debugger-does-not-show-values) 

at last i tried to print out a variable x in debugger window.
unfortunately, i don't understand the sense of the error response, is this an error in bridging header, or I should fix something in settings...

please explain and, if possible, teach, how to fix the issue.
(lldb) print x

warning: Swift error in module myProject: 

Swift had fatal errors constructing the ast context for this module: <module-includes>:1:9: note: in file included from <module-includes>:1:

#import "myRoot/Pods/QuickBlox/Quickblox.framework/Headers/Quickblox.h"
 ^
myRoot/Pods/QuickBlox/Quickblox.framework/Headers/Quickblox.h:9:9: error: include of non-modular header inside framework module 'Quickblox'
#import <Quickblox/BaseServiceFramework.h>
^
<module-includes>:1:9: note: in file included from <module-includes>:1:

#import "myRoot/Pods/QuickBlox/Quickblox.framework/Headers/Quickblox.h"
^

myRoot/Pods/QuickBlox/Quickblox.framework/Headers/Quickblox.h:10:9: error: include of non-modular header inside framework module 'Quickblox'

#import <Quickblox/ChatServiceFramework.h>
^

<module-includes>:1:9: note: in file included from <module-includes>:1:

#import "myRoot/Pods/QuickBlox/Quickblox.framework/Headers/Quickblox.h"
 ^

myRoot/Pods/QuickBlox/Quickblox.framework/Headers/Quickblox.h:12:9: error: include of non-modular header inside framework module 'Quickblox'

#import <Quickblox/QBCore.h>
 ^

<module-includes>:1:9: note: in file included from <module-includes>:1:

#import "myRoot/Pods/QuickBlox/Quickblox.framework/Headers/Quickblox.h"
 ^

myRoot/Pods/QuickBlox/Quickblox.framework/Headers/Quickblox.h:13:9: error: include of non-modular header inside framework module 'Quickblox'

#import <Quickblox/QBAuthHeader.h>
 ^

<module-includes>:1:9: note: in file included from <module-includes>:1:

#import "myRoot/Pods/QuickBlox/Quickblox.framework/Headers/Quickblox.h"
 ^

myRoot/Pods/QuickBlox/Quickblox.framework/Headers/Quickblox.h:14:9: error: include of non-modular header inside framework module 'Quickblox'

#import <Quickblox/QBLocationHeader.h>
 ^

<module-includes>:1:9: note: in file included from <module-includes>:1:

#import "myRoot/Pods/QuickBlox/Quickblox.framework/Headers/Quickblox.h"
 ^

myRoot/Pods/QuickBlox/Quickblox.framework/Headers/Quickblox.h:15:9: error: include of non-modular header inside framework module 'Quickblox'

#import <Quickblox/QBUsersHeader.h>
 ^

<module-includes>:1:9: note: in file included from <module-includes>:1:

#import "myRoot/Pods/QuickBlox/Quickblox.framework/Headers/Quickblox.h"
 ^

myRoot/Pods/QuickBlox/Quickblox.framework/Headers/Quickblox.h:16:9: error: include of non-modular header inside framework module 'Quickblox'

#import <Quickblox/QBPushNotificationsHeader.h>
 ^

<module-includes>:1:9: note: in file included from <module-includes>:1:

#import "myRoot/Pods/QuickBlox/Quickblox.framework/Headers/Quickblox.h"
^

myRoot/Pods/QuickBlox/Quickblox.framework/Headers/Quickblox.h:17:9: error: include of non-modular header inside framework module 'Quickblox'

#import <Quickblox/QBCustomObjectsHeader.h>
^

<module-includes>:1:9: note: in file included from <module-includes>:1:

#import "myRoot/Pods/QuickBlox/Quickblox.framework/Headers/Quickblox.h"
 ^

myRoot/Pods/QuickBlox/Quickblox.framework/Headers/Quickblox.h:18:9: error: include of non-modular header inside framework module 'Quickblox'

#import <Quickblox/QBContentHeader.h>
 ^

<module-includes>:1:9: note: in file included from <module-includes>:1:

#import "myRoot/Pods/QuickBlox/Quickblox.framework/Headers/Quickblox.h"
^

myRoot/Pods/QuickBlox/Quickblox.framework/Headers/Quickblox.h:19:9: error: include of non-modular header inside framework module 'Quickblox'

#import <Quickblox/QBChatHeader.h>
 ^

<module-includes>:2:9: note: in file included from <module-includes>:2:

#import "Headers/QBMulticastDelegate.h"
 ^

myRoot/Pods/QuickBlox/Quickblox.framework/Headers/QBMulticastDelegate.h:10:9: error: include of non-modular header inside framework module 'Quickblox.QBMulticastDelegate'

#import <Quickblox/QBNullability.h>
^

<module-includes>:2:9: note: in file included from <module-includes>:2:

#import "Headers/QBMulticastDelegate.h"
 ^

myRoot/Pods/QuickBlox/Quickblox.framework/Headers/QBMulticastDelegate.h:11:9: error: include of non-modular header inside framework module 'Quickblox.QBMulticastDelegate'

#import <Quickblox/QBGeneric.h>
 ^

could not build Objective-C module 'Quickblox'

Debug info from this module will be unavailable in the debugger.

error: Error in auto-import:

failed to get module 'myProject' from AST context

**Comment by iSevenDays** [comment]
Hi coreman000,

Please attach your test project so we can investigate it more.

Also please ensure that your project compiles and we can run it.

Thanks!

**Comment by coreman000** [comment]
i'm almost finished and a bit scared to send "almost ready project". nothing personal :-)

**Comment by Raikerian** [comment]
No need to send your own project. You can make a test one.

Can you check if this problem can be reproduced in our swift sample for you?

**Comment by coreman000** [comment]
as I noted, i'm very close to the end, so I don't have much time to create test projects, sorry. May be I open a new issue , when i will have more time?

**Comment by Raikerian** [comment]
Of course, feel free to do it whenever you will have a time :)

**Comment by Raikerian** [comment]
Btw, which way are you installing Quickblox iOS SDK? And how are you importing it in your bridging header?

**Comment by coreman000** [comment]
cocoa pods

    @import UIKit;
    @import Foundation;
    @import SystemConfiguration;
    @import MobileCoreServices;

    #import <Quickblox/Quickblox.h>

**Comment by iSevenDays** [comment]
Hello everyone

I've managed to resolve your issue.

Please set optimization level to None in Build Settings -> Swift

![pav3l](https://cloud.githubusercontent.com/assets/3992716/13745897/38c680d8-e9f9-11e5-982d-67e552f49570.png)

**Comment by coreman000** [comment]
![2016-03-14 16 32 39](https://cloud.githubusercontent.com/assets/14929454/13746127/de61e27c-ea02-11e5-8669-d57155518453.png)

**Comment by coreman000** [comment]
that is what i have

**Comment by Entea** [comment]
@coreman000 This doesn't help for me

**Comment by coreman000** [comment]
@Entea do you have the same issue?

**Comment by Entea** [comment]
@coreman000 Exactly, putting +1 here. Looks like other libraries had similar issues with xcode 7 - https://twittercommunity.com/t/xcode-7-debugger/50792

**Comment by coreman000** [comment]
If this is an Xcode issue,  issue here should be closed. I believe in Quickblox guys, but I doubt that they can cure apple bugs ;-)

May be some workaround here?

**Comment by Entea** [comment]
@coreman000 There is a workaround and the thread I posted link to may contain some clues

**Comment by Raikerian** [comment]
Were you managed to fix this with a workaround? Seems like this is common for objective c frameworks, nothing that we can do for now.

**Comment by Entea** [comment]
@Raikerian This helped me - http://stackoverflow.com/questions/31219422/swift-debugger-does-not-show-variable-values-when-importing-objc-framework/31455774#31455774
