### ISSUE TITLE
Session is nil

### ISSUE THREAD

**Issue by s612** [QuickBlox/quickblox-ios-sdk#315]
self.session.localMediaStream.videoTrack.videoCapture - Here the session is nil. How to create the session?

**Comment by Raikerian** [comment]
Hi,

Please provide full log from the app start till this error.

**Comment by Raikerian** [comment]
Were you able to fix this?

**Comment by s612** [comment]
Is the server again down?

**Comment by Raikerian** [comment]
Not sure what are you talking about, can you give us more information on your problem? If the problem is the same like this:
https://github.com/QuickBlox/quickblox-ios-sdk/issues/317
https://github.com/QuickBlox/quickblox-ios-sdk/issues/335

then please, stick to one issue.
