### ISSUE TITLE
Does QBRequest use dispatch_async?

### ISSUE THREAD

**Issue by tonchis** [QuickBlox/quickblox-ios-sdk#319]
Hello QB people! So I'm building a service around the SDK that adapts to my use case and was wondering: the `QBRequest` methods use `dispatch_async` for the network requests? If so, they're safe to call under my main queue, but if not I'm responsible for dispatching them.

Thanks!

**Comment by Raikerian** [comment]
Hi,

All QBRequest's are asynchronous operations in background thread, so it is totally safe to call them on main thread for you. Completion blocks are also being called under the main queue.

**Comment by tonchis** [comment]
I guess the same applies for `dialog.sendMessage` and `QBChat.instance().connect/disconnect` methods, right?

**Comment by iSevenDays** [comment]
Hi tonchis, XMPP methods like sendMessage/chatConnection execute on background XMPP serial queue.

Thanks!

**Comment by Raikerian** [comment]
Do you have any other questions?

**Comment by tonchis** [comment]
Nope! Thanks a lot :)

Closing now
