### ISSUE TITLE
Trying create public dialog

### ISSUE THREAD

**Issue by mrhaxic** [QuickBlox/quickblox-ios-sdk#321]
Hi

Im trying to create public dialog and this my code

```
QBChatDialog *chatDialog = [[QBChatDialog alloc] initWithDialogID:nil type:QBChatDialogTypePublicGroup];
    chatDialog.name = @"Chat with Bob, Sam, Garry";
    chatDialog.userID = 10510876;
    
    [QBRequest createDialog:chatDialog successBlock:^(QBResponse *response, QBChatDialog *createdDialog) {
        
    } errorBlock:^(QBResponse *response) {
        
    }];
```
    

but the return issue is

> [QBCore] Response error: Error Domain=com.alamofire.error.serialization.response Code=-1011 "Request failed: client error (422)" UserInfo={com.alamofire.serialization.response.error.response=<NSHTTPURLResponse: 0x145f74440> { URL: https://api.quickblox.com/chat/Dialog.json } { status code: 422, headers {
>     "Access-Control-Allow-Origin" = "*";
>     "Cache-Control" = "no-cache";
>     Connection = "keep-alive";
>     "Content-Length" = 45;
>     "Content-Type" = "application/json; charset=utf-8";
>     Date = "Fri, 04 Mar 2016 19:04:41 GMT";
>     "QB-Token-ExpirationDate" = "2016-03-04 20:55:48 UTC";
>     "QuickBlox-REST-API-Version" = "0.1.1";
>     Server = "nginx/1.8.1";
>     Status = "422 Unprocessable Entity";
>     "X-Rack-Cache" = "invalidate, pass";
>     "X-Request-Id" = a31017c19d55a8553f54126b81f26c33;
>     "X-Runtime" = "0.012285";
>     "X-UA-Compatible" = "IE=Edge,chrome=1";
> } }, NSErrorFailingURLKey=https://api.quickblox.com/chat/Dialog.json, com.alamofire.serialization.response.error.data=<7b226572 726f7273 223a7b22 62617365 223a5b22 466f7262 69646465 6e2e204e 65656420 75736572 2e225d7d 7d>, NSLocalizedDescription=Request failed: client error (422)}

can I know what is the problem ?

**Comment by Raikerian** [comment]
Hi,

Please print [response.error reasons] in dev console.

**Comment by mrhaxic** [comment]
> {
>     errors =     {
>         base =         (
>             "Forbidden. Need user."
>         );
>     };
> }
> 

here you are

**Comment by mrhaxic** [comment]
@Raikerian

**Comment by Raikerian** [comment]
You haven't logged in REST. Use QBRequest loginwithuser methods in order to do it.

**Comment by mrhaxic** [comment]
@Raikerian Done, Solved thanks alot

**Comment by Raikerian** [comment]
No problem, feel free to create separate issue if you'll have any other problems.
