### ISSUE TITLE
renewing user info after session awakening

### ISSUE THREAD

**Issue by coreman000** [QuickBlox/quickblox-ios-sdk#323]
I've got the following issue: 
when session expires, it automatically restarts, as you said. and App still has a user id in 
    
    QBSession.currentSession().currentUser
    // and clearly QBSession.currentSession().currentUser is not nil

but QBSession.currentSession().currentUser.facebookID
and QBSession.currentSession().currentUser.fullName
etcetera 
are all nil

and this is so confusing...

**Comment by Raikerian** [comment]
Hi,

It was fixed in 2.6.5.

**Comment by coreman000** [comment]
are there any instructions, how to upgrade?

**Comment by Raikerian** [comment]
What is your current SDK version?

**Comment by coreman000** [comment]
how can i check this?

**Comment by Raikerian** [comment]
You can see it in logs or just open Quickblox.h file.

**Comment by coreman000** [comment]
"QB-SDK" = "iOS 2.6.4";

**Comment by Raikerian** [comment]
Just update it using cocoapods or replace with github one from master. 2.6.5 and 2.6.6 contains only bug fixes.

**Comment by coreman000** [comment]
Oh, you speak with me, like I am the master of the game:))) 
That's so, so flattering, but can you please give me a little bit more instructions?

**Comment by Raikerian** [comment]
Which way you have Quickblox iOS SDK installed? (cocoapods or manual dragging in project)

**Comment by coreman000** [comment]
I used cocoa pods, and that was long and confusing process as i described [here](http://stackoverflow.com/questions/35118743/connecting-quickblox-to-app-using-cocoa-pods/35142400?noredirect=1#comment58041974_35142400)

**Comment by Raikerian** [comment]
Please, show your podfile content.

**Comment by coreman000** [comment]
pod ‘QuickBlox’ 

only this line

**Comment by Raikerian** [comment]
perform `pod update` in your project folder then.

**Comment by coreman000** [comment]
pod updated, but my "old" sessions seem to work "old way"
so I reinstalled the app and wait for two hours?

**Comment by Raikerian** [comment]
You can change phone time with +2 hrs (but not more).
Also check Quickblox.h file for version.

**Comment by coreman000** [comment]
Thank you for the support

**Comment by Raikerian** [comment]
If you are still having any troubles please let us know by creating a separate issue :)
