### ISSUE TITLE
One to One QBChatDialog is not updating

### ISSUE THREAD

**Issue by nirav700** [QuickBlox/quickblox-ios-sdk#327]
Hello,

I am trying to update one to one QBChatDialog but its not updating ,
Say for example i am trying to update last message but it's always give me original last message but not i have recently updated last message in qbchatDialog

I am using below method to update QBChatDialog in IOS Side.

/**
 Update existing chat dialog
 
 @param dialog The dialog instance to update
 @param successBlock Block with response and updated chat dialog instances if request succeded
 @param errorBlock Block with response instance if request failed
 
 @return An instance of QBRequest for cancel operation mainly.
 */
+ (QB_NONNULL QBRequest *)updateDialog:(QB_NONNULL QBChatDialog *)dialog
                          successBlock:(QB_NULLABLE void (^)(QBResponse * QB_NONNULL_S response, QBChatDialog * QB_NULLABLE_S chatDialog))successBlock
                            errorBlock:(QB_NULLABLE QBRequestErrorBlock)errorBlock;

**Comment by Raikerian** [comment]
Hi,

Last message text updates serverside. There is no reason to update it manually.

**Comment by nirav700** [comment]
Thanks For replay,

ok i understand this but when i am deleting all one to one chat records still QBChatDialog give me last message text and date.

There is no logic when user completely remove all one to one QBChatMessages after that QBChatDialog still give last message text and date.

Can you please tell me what should be do with that?

**Comment by Raikerian** [comment]
Thank you for your report. Seems like there is such problem. I will address this issue to our server team.
Unfortunately there is no way to modify that field from user side.

**Comment by Raikerian** [comment]
The fix should be available server-side next week. Will post update about it after :)

**Comment by Raikerian** [comment]
Hi @nirav700 
Fix is Live. Can you confirm that everything is working fine now?

**Comment by nirav700** [comment]
Thanks for replay...

Suppose another user created one to one dialog now i am deleting conversation from my side then what should be happen ?

is still  QBChatDialog will return last message and last date on my side or it will not show last message text and date on my side ?

what should be happen with other user side?

**Comment by Raikerian** [comment]
If you will load dialog from REST (QBRequest) it should have a correct lastMessageText.
