### ISSUE TITLE
How can I stretch video while calling like content mode AspectFill?

### ISSUE THREAD

**Issue by tranngoclinh88** [QuickBlox/quickblox-ios-sdk#328]
In Q-municate app, I saw that video calling is using  QBRTCRemoteVideoView to display video session and it can not stretch video like UIImageView with AspectFill mode.
Please let me know there is any way to display video call in stretch mode.

**Comment by Raikerian** [comment]
Hi,

Please see https://github.com/QuickBlox/quickblox-ios-sdk/issues/252

**Comment by tranngoclinh88** [comment]
Thank for your support @Raikerian
