### ISSUE TITLE
How to handle push notifications for 1-1 chat room and Group Chat room? 

### ISSUE THREAD

**Issue by ajay2c9** [QuickBlox/quickblox-ios-sdk#331]
Hi,

How to switch ON and OFF the Push notifications for 1-1 chat room and Group Chat room?
what i mean is 
For Example:
I had a button for every room in my iOS app, if i turn it on, then only i should receive the notifications, it it is turn off, then i shouldn’t receive the notifications for that room.

These scenarios will be possible or not? IF possible , How?

I already raised this Question in 175 and 177 issues. Is there any update for this? 
Please give suggestions

Thank you

**Comment by Raikerian** [comment]
Hi,

There is no possibility to do this with our automatic push notifications for now, cause there is no such feature yet. However you can turn them off, and send pushes manually from each user after every message sending. You can use custom objects to store ID of users, that want to receive push notifications from each chat dialog. Thats the only possible way to do it for now.

**Comment by ajay2c9** [comment]
Thank you for reply.
Is there any possibility for  enable and disable the chat notifications for particular user.(for all chat rooms)using code in ios.

**Comment by Raikerian** [comment]
As I've already mentioned, you need to use custom objects to store ids of a specific users, that want to receive push notifications. And every time you send a message, you need to also send a push notification (using QBRequest methods) to those user ids. There is property called 'data' in QBChatDialog for that.
Here is some helpful documentation for that: http://quickblox.com/developers/SimpleSample-chat_users-ios#Custom_parameters

**Comment by Raikerian** [comment]
Do you have any other question regarding this issue?

**Comment by ajay2c9** [comment]
No. Thank you for reply
