### ISSUE TITLE
privateUrlForFileUID now returns a JSON file

### ISSUE THREAD

**Issue by cjg552** [QuickBlox/quickblox-ios-sdk#333]
Hi, I have replaced deprecated function `+ (QB_NULLABLE NSString *)privateUrlForID:(NSUInteger)ID` by the new one `privateUrlForFileUID:` , and now instead of getting the final private URL for the file a get a JSON like this : `{"blob":{"app_id":null,"blob_status":"complete","content_type":"image/png","created_at":"2016-03-10T10:17:38Z","id":3874695,"last_read_access_ts":null,"lifetime":0,"name":"1457605058.04103.png","public":false,"ref_count":1,"set_completed_at":"2016-03-10T10:17:39Z","size":55754,"uid":"cb4211833bde41968abd5a94a6163XXXX","updated_at":"2016-03-10T10:17:39Z"}}`

Using QuickBlox (2.6.6) 

Thanks!

**Comment by Raikerian** [comment]
Hi,

This method returns URL to JSON, but not the complete JSON. Please post your code snippet as well as complete log.

**Comment by cjg552** [comment]
Old Code ( deprecated in 2.6.1):
`let privateURLPhoto = QBCBlob.privateUrlForID(UInt(idFile!)!)`

New Code: (comments in code say that return Public url to file not any JSON )
`let privateURLPhoto = QBCBlob.publicUrlForFileUID(idFile!)`

My file is a PNG file, I expect to get the final URL to this image but instead of that I am getting a JSON from QuickBlox

**Comment by Raikerian** [comment]
privateURLPhoto should be URL to JSON, that URL will automatically redirect you to image.
Can you print privateURLPhoto variable?

**Comment by cjg552** [comment]
privateURLPhoto : `https://api.quickblox.com/blobs/3874674.json?token=6beb6a01e82bac139192b2835591544f422a1134`

idFile: "3874674"

**Comment by Raikerian** [comment]
Can you please provide complete code for your blob uploading and png picture as well.
It will also be good if you can create a test project with this issue being reproducible there.

**Comment by cjg552** [comment]
**Upload image file code:**

`   let imageData : NSData = NSData(data: UIImagePNGRepresentation(avatarImage)!);
    let currentTimestamp = NSDate().timeIntervalSince1970
    let nameFile = "\(currentTimestamp).png"
    
     QBRequest.TUploadFile(imageData, fileName: nameFile, contentType: "image/png", isPublic: false, successBlock:
                        { (response : QBResponse!, uploadedBlob :QBCBlob!) -> Void in
                        
                        }, statusBlock: { (request : QBRequest?, status : QBRequestStatus?) -> Void in
                            
                        }) { (response : QBResponse!) -> Void in
                    }`

**Comment by Raikerian** [comment]
I have just tested it with this code:

```objectivec
let imageData : NSData = NSData(data: UIImagePNGRepresentation(UIImage(named: "BG")!)!);
        let currentTimestamp = NSDate().timeIntervalSince1970
        let nameFile = "(currentTimestamp).png"
        
        QBRequest.TUploadFile(imageData, fileName: nameFile, contentType: "image/png", isPublic: false, successBlock:
            { (response : QBResponse!, uploadedBlob :QBCBlob!) -> Void in
                
                print(QBCBlob.privateUrlForFileUID(uploadedBlob.UID!))
                
            }, statusBlock: { (request : QBRequest?, status : QBRequestStatus?) -> Void in
                
            }) { (response : QBResponse!) -> Void in
        }
```

I got this link:

```
https://api.quickblox.com/blobs/5433451914ad4217b96f7ba448619bc700.json?token=09dc2e6331fa7d21dfc887be37c33ffb3329ec5c
```

And there is image.
Please make sure that you are uploading image and not a json file. If the issue still existent, please make a test project with the issue being reproducible. You can use a static image for that.

**Comment by cjg552** [comment]
Hi, I found the problem. Now I have to use `blob.UID` instead of `blob.ID` to get the right ID for the file . Thanks a lot!

**Comment by Raikerian** [comment]
Good to see you have fixed it. If you are still having any other troubles please let us know by creating a separate issue :)
Have a nice day.
