### ISSUE TITLE
Automatic Call Disconnect

### ISSUE THREAD

**Issue by dharasisbehera** [QuickBlox/quickblox-ios-sdk#334]
I want to disconnect the video call that is established after certain time interval..
How can i achieve this..I don't find any delegate that is handeling this..Pls Help

**Comment by dharasisbehera** [comment]
I am asking for IOS SDK

**Comment by Raikerian** [comment]
Hi,

Not sure what do you mean, but if you just want to disconnect from call set up timer to call hangUp method of your current QBRTCSession.

**Comment by Raikerian** [comment]
Hi @dharasisbehera 
Any updates on this?

**Comment by Raikerian** [comment]
We haven't heard from you any updates for a long time, if you are still experiencing this issue, just reopen it. Closing this for now.
