### ISSUE TITLE
Video Call not working for latest idk

### ISSUE THREAD

**Issue by s612** [QuickBlox/quickblox-ios-sdk#335]
i got this response

</sdp><sdkVersion>1.0.7beta</sdkVersion><sessionID>5161DEF2-6AF9-4D94-A5E3-B534724B4B64</sessionID><signalType>call</signalType><userInfo><startCall>userInfo</startCall></userInfo><opponentsIDs><opponentID>10430891</opponentID></opponentsIDs></extraParams><error code="503" type="cancel"><service-unavailable xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/><text

**Comment by Raikerian** [comment]
Hi,

Please provide us full log.
