### ISSUE TITLE
How to get best video quality with Quickblox-iOS-SDK ?

### ISSUE THREAD

**Issue by gstream** [QuickBlox/quickblox-ios-sdk#337]
I m integrating quickblox for my enterprise app.
It's video quality looks good but not so good when making video call between iOS-android (android-iOS).
Quickblox android example support VP8, VP9, H264 for video codec. (I don't know it's working correctly.)
But iOS framework supports only VP8 and H264.
Is there any solution to improve video quality?
And how to add VP9 codec for my iOS app?

**Comment by gstream** [comment]
Hi, Quickblox friends !

Please help me :(

**Comment by iSevenDays** [comment]
Hi gstream,

H264 is the most preferred codec for video. Chrome started supporting H264 from 50 revision.

VP9 for iOS exists only in development and webrtc doesn't have a stable version, so we are waiting for a stable one.

VP8 should be used if you do support iOS7. Otherwise please always use H264. 

H264 is the only one video codec for iOS that has hardware support.

Thanks!

**Comment by gstream** [comment]
Hi iSevenDays
Thanks for your answer.
So what I need to use to get best quality between different platform (IOS-Android, Android-iOS) ?
Need to use H264 for both platform ?

**Comment by iSevenDays** [comment]
To get best quality and performance you should use H264.

If you support iOS 7, then WebRTC automatically switches to VP8 (even if you set H264)

If some android devices do not support H264, then automatically VP8 will be used.

If both caller and callee have H264 support, then H264 will be used.

Thanks!

**Comment by gstream** [comment]
Thanks for your help. :)

**Comment by DhananjayAwasthisyscraft** [comment]
I am also using pod 'Quickblox-WebRTC', '~> 2.6' for video calling. I am facing two problem the first one is, during video call volume is too slow an i am using this code 
            QBRTCAudioSession.instance().initialize()
            QBRTCAudioSession.instance().currentAudioDevice = QBRTCAudioDevice.speaker
the second one is that, during video calling video quality is poor and video is stretched also, for prevent to stretching i am using this line of code remoteView.videoGravity = AVLayerVideoGravityResizeAspect. 

Thanks
