### ISSUE TITLE
createSubscription problem

### ISSUE THREAD

**Issue by cvezina** [QuickBlox/quickblox-ios-sdk#338]
createSubscription is working but the subscription is always created in production environment when the build us uploaded for TestFlight users. I have checked the archive to make sure it is set to DEBUG environment. Also, in my code, I use [QBSettings setServiceZone: QBConnectionZoneTypeDevelopment]; to make sure the the development environment is used when in DEBUG mode.

If I run the app from Xcode, it creates a development subscription but in any other case it creates a production subscription. When I try to send a push notification to an existing user with a production subscription, it returns an error telling me that there are no recipients and nobody will receive the notification

**Comment by iSevenDays** [comment]
Hi cvezina,

QuickBlox automatically determines APNS environment.

If you use development provision, then development provision is used.

If you use production(adhoc, apple app store) provision, then production provision is used.

**Comment by Raikerian** [comment]
Hi @cvezina 

Were you able to fix this?

**Comment by Raikerian** [comment]
We haven't heard from you any updates for a long time, if you are still experiencing this issue, just reopen it. Closing this for now.
