### ISSUE TITLE
error 422

### ISSUE THREAD

**Issue by coreman000** [QuickBlox/quickblox-ios-sdk#340]
I've got error 422 similar to described [here](http://stackoverflow.com/questions/34172143/quickblox-v2-6-facebook-login-issue)

Strange, but different test fb users gave different results, I played with them a bit and found out that users with russian names can't login to quickblox. 

may be some issue with cyrillic encoding?

**Comment by iSevenDays** [comment]
Hi coreman000,

Yes, we aware of this problem with cyrillic encoding, we have planned this feature for the next release, please try again tomorrow and see if the problem is solved

Thanks!

**Comment by coreman000** [comment]
I see, that now Quickblox does not add anything to fullName of user. Is this a solution, or just temporary patch?

**Comment by Raikerian** [comment]
It was a server-side solution. You can update fullName field with any characters by yourself from now on :)

**Comment by Raikerian** [comment]
In order to receive updates about Quickblox new features, follow our [blog here](http://quickblox.com/blog/).
If you are still having any other troubles, feel free to create separate issue.
