### ISSUE TITLE
Dialog userID = 0 with not admin user.

### ISSUE THREAD

**Issue by nhuomtv** [QuickBlox/quickblox-ios-sdk#341]
1. When user  A create group B,C,D => group G.
2. A into group G and show G.userID != 0.
3. B,C or D into group G show   G.userID = 0. (not userID of user admin A)

**Comment by iSevenDays** [comment]
Hi nhuomtv,

Please tell us the name of project

**Comment by nhuomtv** [comment]
I used QMService in Quickblox ios sdk

**Comment by iSevenDays** [comment]
Please provide us full logs

**Comment by Raikerian** [comment]
Hi @nhuomtv 
Any updates on this?

**Comment by nhuomtv** [comment]
In file QMChatService.m function "handleSystemMessage" or "handleChatMessage" run when User create group. But value "userID" of QBChatDialog  have not been updated in this function. I think that is the cause of this error. ( userID is ID admin of group)

**Comment by Raikerian** [comment]
@nhuomtv 
userID is not changeable ID of group dialog owner, so there is no need to handle it on every message. I have just checked, and it has a correct value in our samples (it is also being cached, so the value is always exists).
If you are experiencing this issue for some reason, please provide us full logs, from app start till userID being non-existent.

**Comment by Raikerian** [comment]
Any updates on this?

**Comment by Raikerian** [comment]
@nhuomtv we haven't heard any updates from you on this issue. If you are still experiencing this just reopen it. If you are having any other troubles, please let us know by creating a separate issue.
