### ISSUE TITLE
lastMessageUserID = 0 in Dialog

### ISSUE THREAD

**Issue by nhuomtv** [QuickBlox/quickblox-ios-sdk#342]
1. When user A create group user A, B,C,D.
2. User Send message to group
3. User B,C,D: lastMessageUserID = 0 (true = userID of User A)

**Comment by iSevenDays** [comment]
Hi nhuomtv,

What is the project you have problems with?

In our samples we don't have IAWMessageContentTypeCreateDialog

**Comment by nhuomtv** [comment]
I used QMService in Quickblox ios sdk. Sorry IAWMessageContentTypeCreateDialog is custom message Type in my Pr

**Comment by nhuomtv** [comment]
In file QMChatService.m, I find somewhere  lastMessageText have been updated elqual "message.encodedText" but lastMessageUserID have not been updated. I think that is the cause of this error. Please check and fix bug!

**Comment by iSevenDays** [comment]
Hi nhuomtv,

Thank you for the report! 

We will check it soon and then we will let you know

**Comment by iSevenDays** [comment]
Thanks!
Related issue: https://github.com/QuickBlox/q-municate-services-ios/issues/155#issuecomment-197259130
