### ISSUE TITLE
How to update QMChatViewController and QMservices .

### ISSUE THREAD

**Issue by ajay2c9** [QuickBlox/quickblox-ios-sdk#344]
Hi,
I am using the quickblox in my app. I install the pods the of QMChatViewController and QMServices after installing i am getting the errors. I want to update QMChatViewController and QMServices. with latest updates.I updated the Quickblox version is 2.6.6. After install the QMChatViewController and QMServices. i used the these cmds

 git submodule init
git submodule update
git submodule foreach git pull origin master
It creates a folder called vendor in my project. I don't know how to proceed with that.

I clone the Latest sample project in the other folder. using this command.
git clone https://github.com/QuickBlox/quickblox-ios-sdk.git  
 
Please give suggestion to update the QMChatViewController and QMServices.
Thank you.

**Comment by Raikerian** [comment]
Is these issues linked with each other or are they same? https://github.com/QuickBlox/q-municate-services-ios/issues/160

**Comment by ajay2c9** [comment]
both are same issues after updating QMChatViewController(using pods) and QMservices with both process (pods and manual) i am getting those errors.

**Comment by ajay2c9** [comment]
After installing the pods i am getting the type argument cannot be applied to non parameterized class 'BFTask' and also this error. these are the screenshots applied
![screen shot 2016-03-18 at 9 43 36 am](https://cloud.githubusercontent.com/assets/9112899/13868433/a2c73b10-ecee-11e5-835d-4695552f655f.png)
![screen shot 2016-03-17 at 11 43 25 pm](https://cloud.githubusercontent.com/assets/9112899/13868434/a2cc8d68-ecee-11e5-9fcd-79cd4d1c14b0.png)
please give suggestions to fix these issues.

**Comment by ajay2c9** [comment]
I removed .xcworkspace, podfile.lock and Pods folder. its working fine now without facebook. in my project we have facebook login. the error is causing due to facebook framework. i removed it.After installing the facebook sdk, errors are generating some times like above errors and some times clang error is generating. I am attaching the facebook sdks here.please suggest me how to handle those errors. and also i tried this with chat sample. Same issue is generating. i am attaching the chat sample too . Please give suggestions to solve these errors

sample-chat.zip

FacebookSDK.zip

Thank you

**Comment by iSevenDays** [comment]
Hi ajay2c9,

You get error "duplicate symbols" because both Facebook iOS SDK and QMServices uses Bolts.

When you use .framework, cocoa pods manager does not know how to resolve dependencies correctly and you will have 2 copies of Bolts framework.

In documentation for FB iOS SDK https://github.com/facebook/facebook-ios-sdk you can find a way on how to install Facebook iOS SDK using CocoaPods

Download the SDK at https://developers.facebook.com/docs/ios or via CocoaPods by adding the 'FBSDKCoreKit', 'FBSDKLoginKit', and 'FBSDKShareKit' pods.


So to fix your problem you need to remove Facebook iOS SDK framework and use it via pods

Here is an example of correct podfile

```
platform :ios, "7.0"

pod 'SVProgressHUD'
pod 'TWMessageBarManager', '~> 1.7.2'

pod 'QuickBlox'

pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'

#Production pod
pod 'QMCVDevelopment', :git => 'git@github.com:QuickBlox/QMChatViewController-ios.git', :commit => '17ada21717a26235a73069a7ef0e396871ac8514'

#For development pods
#pod 'QMCVDevelopment', :path => '../../QMChatViewController-ios/'

#Production pod
pod 'QMServicesDevelopment', :git => 'git@github.com:QuickBlox/q-municate-services-ios.git', :commit => 'f79c5459c2ff92296c8173992a4884bb77b06e18'

#For development pods
#pod 'QMServicesDevelopment', :path => '../../q-municate-services-ios/'pod 'Bolts'

```

**Comment by ajay2c9** [comment]
Thank you for reply . I will Try and get back to you.

**Comment by iSevenDays** [comment]
Hi @ajay2c9 

were you able to fix that?

**Comment by ajay2c9** [comment]
Yes.Thank you for suggestion.

**Comment by sanjayjadon13** [comment]
unable to install 

#Production pod
pod 'QMCVDevelopment', :git => 'git@github.com:QuickBlox/QMChatViewController-ios.git', :commit => 'ac7ae17689e75f0554706447d19f2851fc46dc54'

#For development pods
#pod 'QMCVDevelopment', :path => '../../QMChatViewController-ios/'

#Production pod
pod 'QMServicesDevelopment', :git => 'git@github.com:QuickBlox/q-municate-services-ios.git', :commit => '2eb283ee18896182379a8a046d95f8b12362af73'

#For development pods
#pod 'QMServicesDevelopment', :path => '../../q-municate-services-ios/'


getting error

Analyzing dependencies
Pre-downloading: `QMCVDevelopment` from `git@github.com:QuickBlox/QMChatViewController-ios.git`, commit `17ada21717a26235a73069a7ef0e396871ac8514`

[!] Error installing QMCVDevelopment
[!] /usr/local/bin/git clone git@github.com:QuickBlox/QMChatViewController-ios.git /var/folders/6v/rv6wt8956yx_ptj833t1ppt40000gn/T/d20160723-3962-4uvqsf --template=

Cloning into '/var/folders/6v/rv6wt8956yx_ptj833t1ppt40000gn/T/d20160723-3962-4uvqsf'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by Fisky-Alan** [comment]
you have to set up ssh key
