### ISSUE TITLE
Cant join group chat IOS 

### ISSUE THREAD

**Issue by rvilches** [QuickBlox/quickblox-ios-sdk#346]
I tried to figure this out with no success. Since yesterday my app suddently started throwing this error: " Domain=XMPPStreamErrorDomain Code=1 "(null)"" .

If the app goes to the background and then back to foreground I see the chat reconnect succesfully but when I try to join the dialog again I got the above error msg

**Comment by Raikerian** [comment]
Hi,

Does this error occurs only after going back from background (this means that everything is working fine when you are opening app and joining for the first time)?

**Comment by rvilches** [comment]
Yes,everything runs fine if the app does not enter to background

**Comment by iSevenDays** [comment]
Hi rvilches,

Code=1 means error XMPPStreamInvalidState, "Invalid state for requested action, such as connect when already connected"

Please check that group chat dialog has not been joined when you try to join it.

**Comment by rvilches** [comment]
Thanks @Raikerian @iSevenDays you are the best guys!. With the "null" log I did not know what was happening. 

For the record and future reference to other people that could run into this problem: 
I was doing a dialog.leave exactly before the app left to the background and even though I was getting the log of success it looks that it was causing some trouble server-side or I do not know where. 

Again, thanks guys for your fast response

**Comment by Raikerian** [comment]
@rvilches it will be very helpful for us if you will try to reproduce this error with our unreleased SDK from [development branch](https://github.com/QuickBlox/quickblox-ios-sdk/tree/develop). It seems like we have already fixed it, if not we should look more into that issue.

Thanks again.

**Comment by rvilches** [comment]
Ok , I updated to the last version of the SDK and using the code as I had before (leaving the dialog just before the app left to background) and now everything is running fine. I have no error logs now.

**Comment by Raikerian** [comment]
@rvilches thank you very much for your feedback. Our development SDK is currently on testing, we will release it soon. For now please use release version with your own fix :)
