### ISSUE TITLE
How to Login as admin in the App.

### ISSUE THREAD

**Issue by ajay2c9** [QuickBlox/quickblox-ios-sdk#347]
I registered in quickBlox using Google connect and Create a application.I want to login as a admin in the app side.what are the credentials need to be used. Please give suggestions.
Thank you.

**Comment by iSevenDays** [comment]
https://github.com/QuickBlox/quickblox-ios-sdk/issues/310
https://github.com/QuickBlox/quickblox-ios-sdk/issues/285
