### ISSUE TITLE
QuickbloxWebRTC was built for newer iOS version (9.0) than being linked (8.0)

### ISSUE THREAD

**Issue by nirav700** [QuickBlox/quickblox-ios-sdk#348]
I am using quickblox using pods its working fine.

I have deployment target is IOS 8, but today i have updated my pods then it will give me warning like this

object file (/Users/dev/Documents/Iphone_projects/Application_name/Pods/Quickblox-WebRTC/QuickbloxWebRTC.framework/QuickbloxWebRTC(audio_device.RTCAudioSession.o)) was built for newer iOS version (9.0) than being linked (8.0)

object file (/Users/dev/Documents/Iphone_projects/Application_name/Pods/Quickblox-WebRTC/QuickbloxWebRTC.framework/QuickbloxWebRTC(webrtc_objc_target.RTCICECandidate.o)) was built for newer iOS version (9.0) than being linked (8.0)

and many more.......

can you please advice me what should i do?

i have try to remove pods and again install but still its give me same warning...

**Comment by iSevenDays** [comment]
Hi nirav700,

We aware of this issue.

You can continue to use QuickBloxWebRTC without any problem.

We will investigate this more and will try to fix that in next release.

Thanks!

**Comment by antoescu** [comment]
Hi! Just wondering if you guys are working on this topic. I have the same problem. Thanks!
