### ISSUE TITLE
custom field location

### ISSUE THREAD

**Issue by cvezina** [QuickBlox/quickblox-ios-sdk#349]
When I use a custom field of type "Location" and I named the key field "location", the key field used to store the data is not "location" but "_qb_location". Worst, since a few days, it is now named "loc" instead of "_qb_location". So, I can't retrieve the field "location" because it is stored as "_qb_location" and now as "loc".

Below is a print of custom fields of a dialog data. As you can see, the field for Location type is called "loc" instead of "location" as I set when I created the field. Few days ago, the same field was called "_qb_location".

Printing description of dialog->_data:
{
    accepted =     (
        9033987,
        9254449
    );
    alerts =     (
        3
    );
    "class_name" = GPPlanDetailsInfo;
    date = "2016-07-16 13:04:34";
    loc =     (
        "-71.2074252",
        "46.8141835"
    );
    scope = 2;
    spotAddress = "{\"SubAdministrativeArea\"=>\"Qu\U00e9bec\", \"CountryCode\"=>\"CA\", \"Name\"=>\"Quebec City QC\", \"State\"=>\"QC\", \"FormattedAddressLines\"=>[\"Quebec City QC\", \"Canada\"], \"Country\"=>\"Canada\", \"City\"=>\"Quebec City\"}";
    spotName = "Quebec City QC";
    spotPhone = "<null>";
    spotURL = "http://en.wikipedia.org/wiki/Quebec_City";
    spotZoomLevel = "12.7457880741685";
}

**Comment by iSevenDays** [comment]
Hi cvezina,

Thank you for reporting the issue.
We apologize for any inconvenience.

This bug has been assigned to the developer and a fix will be available in the next release.

We will let you know once we fix it.

Thanks!

**Comment by iSevenDays** [comment]
Hi cvezina,

Bug was fixed yesterday and you can check it on your account.

Thanks!
