### ISSUE TITLE
Can't re-join Group Dialog after app goes background

### ISSUE THREAD

**Issue by fayfers** [QuickBlox/quickblox-ios-sdk#352]
Hey guys.

It seems like from a few previous tickets you already were trying to fix this issue, however it still appears to be actual.

SDK 2.7

When I join a dialog then sent an app into background and then try rejoining a previously active dialog, sometimes this error is shown:

> Error Domain=com.quickblox.xmpp Code=-1 "Cannot create/join room when already creating/joining/joined." UserInfo={NSLocalizedDescription=Cannot create/join room when already creating/joining/joined.

I'm executing leaving the room every time a user leaves the current room or app goes into background:
```
[dialog leaveWithCompletionBlock:^(NSError * _Nullable error) {
                [[QBChat instance] removeDelegate:self];
 }];
```

And sometimes after app went background and then becomes active and tries to rejoin a previously active dialog, it is terminated on the line when I check if dialog is joined flag:

```
- (void)connectToChat{
    [self.dialog joinWithCompletionBlock:^(NSError * _Nullable error) {
        // joined
        if ([self.dialog isJoined] == YES){
            [[LocalStorageService shared] setJoinedDialog:self.dialog];
            NSLog(@"**** joined dialog ****");
        }else{
            [self performSelector:@selector(connectToChat) withObject:self afterDelay:0.5];
        }
    }];
} 
```
It throws: Thread 1: EXC_BAD_ACCESS: (code=1, address=0x420)

And sometimes, when it's finally joined after being in the background, when I try to send the message to the group it goes:

> 2016-03-20 04:12:59.878 textbit[908:244072] ERROR SENDING A MESSAGE Error Domain=com.quickblox.chat Code=-1001 "(null)" UserInfo={NSLocalizedRecoverySuggestion=You are not joined to the dialog.}

In this situation group isJoined flag is YES.

When I go back and forth between dialogs in the app when it's active and never went in background state everything works well and this issue never appears.

**Comment by Raikerian** [comment]
Hi,

There is no need to leave from room when app is going to background. It is automatically done by chat disconnect.

**Comment by fayfers** [comment]
Wow, thank you guys for such a fast response! I've removed leaving a dialog on app going to background.
However, I still can't join a previously active dialog after app had been in background.

Steps to reproduce:

1) Create three dialogs
2) Join two of them one after another.
Go to the first one and join with: 
```
- (void)connectToChat{
    [self.dialog joinWithCompletionBlock:^(NSError * _Nullable error) {
       NSLog(@"Joined");
    }];
} 
```
Go back to the list of dialogs. Before going to the list of dialogs, leave a joined dialog with 
```
[self.dialog leaveWithCompletionBlock:^(NSError * _Nullable error) {
    [[QBChat instance] removeDelegate:self];
}];
```
Do the same thing for a second dialog. But don't do anything with a third dialog.
3) Go background. When going background in app delegate's applicationDidEnterBackground:
```
  [[QBChat instance] disconnectWithCompletionBlock:^(NSError * _Nullable error) {
      [[LocalStorageService shared] setCurrentUser:nil];
  }];
```
4) Go foreground. On applicationDidBecomeActive:
```
[QBRequest logInWithUserLogin:username password:password successBlock:^(QBResponse *response, QBUUser *user) {

        QBUUser *userToLogIn = [QBUUser user];
        userToLogIn.ID = user.ID;
        userToLogIn.password = password;
        
        if (response.success){        
            if ([[QBChat instance] isConnected] == YES){
                [[LocalStorageService shared] setCurrentUser:user];
                NSTimer *presenceTimer;
                presenceTimer = [NSTimer scheduledTimerWithTimeInterval:45 target:[QBChat instance] selector:@selector(sendPresence) userInfo:nil repeats:YES];
            }else{
                [[QBChat instance] connectWithUser:userToLogIn completion:^(NSError * _Nullable error) {
                [[LocalStorageService shared] setCurrentUser:user];
                NSTimer *presenceTimer;
                presenceTimer = [NSTimer scheduledTimerWithTimeInterval:45 target:[QBChat instance] selector:@selector(sendPresence) userInfo:nil repeats:YES];
                 }];
            }
        }
    } errorBlock:^(QBResponse *response) {
        [Flurry logEvent:@"MAIN_VIEW: ERROR! When authing user"];
    }];
```
5) Try to rejoin two previously joined dialogs after app becomes active. joinWithCompletionBlock method for previously dialogs is never called, however you can join a third dialog that hasn't been joined before.

**Comment by iSevenDays** [comment]
Hi fayfers,

I've just tried to reproduce the issue, but I failed to do it.

Everything's working fine and I can successfully join dialog1, dialog2, dialog3 in order you gave me.

Could you please give us a test project where we can reproduce the issue?

Thanks

**Comment by VitaliyGuru** [comment]
Hi @fayfers, 

Were you able to fix the issue?

**Comment by Raikerian** [comment]
@fayfers we have not heard any updates from you. If you are still experiencing this issue, just reopen it. If you are having any other troubles, let us know by creating a separate issue.
