### ISSUE TITLE
Error is generating the by adding the Facebook SDK after updating QMChatViewController and QMServices Pods

### ISSUE THREAD

**Issue by ajay2c9** [QuickBlox/quickblox-ios-sdk#353]
After updating pods QMChatViewController and QMServices, installing the facebook sdk,  clang error is generating . I am attaching the facebook sdks here.please suggest me how to handle those errors. and also i tried this with chat sample. Same issue is generating. i am attaching the chat sample too . Please give suggestions to solve these errors

[FacebookSDK.zip](https://github.com/QuickBlox/quickblox-ios-sdk/files/181860/FacebookSDK.zip)
[sample-chat.zip](https://github.com/QuickBlox/quickblox-ios-sdk/files/181861/sample-chat.zip)

thank you

**Comment by Raikerian** [comment]
Please stick to one issue if the problem is the same: https://github.com/QuickBlox/quickblox-ios-sdk/issues/344
