### ISSUE TITLE
Location on QBCOCustomObject will only show [0, 0]

### ISSUE THREAD

**Issue by prometheon** [QuickBlox/quickblox-ios-sdk#354]
I have a field on a custom object called 'location' that is of type Location in Quickblox. Here is the code I currently am using to update that location:

    let object = QBCOCustomObject()
    object.className = "User"

    let geodata = QBLGeoData()
    geodata.latitude = 3
    geodata.longitude = 3

    object.fields?.setObject(geodata, forKey: "location")
    QBRequest.createObject(object, successBlock: nil, errorBlock: nil)`

The object is saved but has a location of [0, 0] no matter the value of the latitude and longitude. I've tried other datatypes such as an array with two values, CLLocation, and string separating the longitude and latitude by a comma. This results in either no object creation at all or a location value of NIL.

Thank you for any help with this issue!

**Comment by Raikerian** [comment]
Hi,

Please attach full logs that will represent the issue.

**Comment by soulfly** [comment]
For this, you can't use a QBLGeoData class

just use an array with 2 elements: lat and lon, for example:

     let geodata = [0, 0]

**Comment by prometheon** [comment]
Thank you! I saved using an array a couple days ago and it wouldn't uploading the object, but it seems to be working great now. Appreciate the prompt response!
