### ISSUE TITLE
Chat is crash while loading messages

### ISSUE THREAD

**Issue by ajay2c9** [QuickBlox/quickblox-ios-sdk#356]
Hi,
My project is in xib.I updated the Quickblox, QMChatViewController and QMservices in the project. while loading the the messages in chatViewController it crashed in the app. in this method

 - (CGSize)collectionView:(QMChatCollectionView *)collectionView dynamicSizeAtIndexPath:(NSIndexPath *)indexPath maxWidth:(CGFloat)maxWidth {
     QBChatMessage *item = [self.chatSectionManager messageForIndexPath:indexPath];
    Class viewClass = [self viewClassForItem:item];
    CGSize size = CGSizeZero;
    if (viewClass == [QMChatAttachmentIncomingCell class]) {
                size = CGSizeMake(MIN(200, maxWidth), 200);
    }
    else if(viewClass == [QMChatAttachmentOutgoingCell class]) {
                NSAttributedString *attributedString = [self bottomLabelAttributedStringForItem:item];
                CGSize bottomLabelSize = [TTTAttributedLabel sizeThatFitsAttributedString:attributedString
                                                                  withConstraints:CGSizeMake(MIN(200, maxWidth), CGFLOAT_MAX)
                                                     limitedToNumberOfLines:0];
        size = CGSizeMake(MIN(200, maxWidth), 200 + ceilf(bottomLabelSize.height));
    }
    else {
        
        NSAttributedString *attributedString = [self attributedStringForItem:item];
        
        size = [TTTAttributedLabel sizeThatFitsAttributedString:attributedString
                                                withConstraints:CGSizeMake(maxWidth, CGFLOAT_MAX)
                                         limitedToNumberOfLines:0];
    }
        return size;
}
 Give suggestion for solve the crash.I check the log but it doesn't show any thing.

**Comment by Raikerian** [comment]
Hi,

Please provide the full crashlog.

Also add exception to all exceptions in order to see where did it exactly crashes.

**Comment by ajay2c9** [comment]
while loading the message in the dialog it crash is occurring . it displays the log like this

2016-03-24 15:57:25.494 [11383:135505] dialog 
    ID:56f3bf49a0eb472853000004                      
    Created At:(null)                      
    Updated At:2016-03-24 10:20:16 +0000                      
    Room JID:36508_56f3bf49a0eb472853000004@muc.chat.quickblox.com                      
    name:GAME123,ADAMSTELLENT,BRAIN,LOOSE,MINDY                      
    photo:(null)                      
    type:2                      
    lastMessage:Update the dialogand check                      
    lastMessageDate:2016-03-24 10:20:15 +0000                      
    occupantIDs:(
    11071986,
    11105126,
    11105246,
    11105275,
    11105305
)                      
    userID:11071986                      
    data:(null)                      
    unreadMessagesCount:0                      
    lastMessageUserID:11071986
2016-03-24 15:57:25.802 [11383:135614] [QBCore] Request URL:https://api.quickblox.com/chat/Message.json?chat_dialog_id=56f3bf49a0eb472853000004&limit=10&sort_desc=date_sent
2016-03-24 15:57:25.802  [11383:135614] [QBCore] Request method: GET
2016-03-24 15:57:25.805  [11383:135614] [QBCore] Request parameters:{
    "chat_dialog_id" = 56f3bf49a0eb472853000004;
    limit = 10;
    "sort_desc" = "date_sent";
}
2016-03-24 15:57:25.807  [11383:135614] [QBCore] Request headers: {
    "Content-Type" = "application/json";
    "QB-OS" = "iOS 9.2";
    "QB-SDK" = "iOS 2.7";
    "QB-Token" = ad9c961831723eb3013371fac0e075d7a79bb70a;
    "QuickBlox-REST-API-Version" = "0.1.1";
}
2016-03-24 15:57:26.394  [11383:135614] [QBCore] Response headers: {
    "Access-Control-Allow-Origin" = "*";
    "Cache-Control" = "max-age=0, private, must-revalidate";
    Connection = "keep-alive";
    "Content-Length" = 399;
    "Content-Type" = "application/json; charset=utf-8";
    Date = "Thu, 24 Mar 2016 10:27:26 GMT";
    Etag = "\"7083a159e93244ef9fc8298a32bee0ee\"";
    "QB-Token-ExpirationDate" = "2016-03-24 12:17:45 UTC";
    "QuickBlox-REST-API-Version" = "0.1.1";
    Server = "nginx/1.8.1";
    Status = "304 Not Modified";
    "Strict-Transport-Security" = "max-age=15768000;";
    "X-Rack-Cache" = miss;
    "X-Request-Id" = 4a2ee6a92c4452fc30119b266603468e;
    "X-Runtime" = "0.033109";
    "X-UA-Compatible" = "IE=Edge,chrome=1";
}
2016-03-24 15:57:26.395  [11383:135614] [QBCore] Response object: {
    items =     (
                {
            "_id" = 56f3bf5f29143db52a0041b0;
            attachments =             (
            );
            "chat_dialog_id" = 56f3bf49a0eb472853000004;
            "created_at" = "2016-03-24T10:20:16Z";
            "date_sent" = 1458814815;
            "delivered_ids" =             (
                11071986
            );
            "dialog_id" = 56f3bf49a0eb472853000004;
            message = "Update the dialogand check";
            read = 0;
            "read_ids" =             (
                11071986
            );
            "recipient_id" = "<null>";
            "sender_id" = 11071986;
            "updated_at" = "2016-03-24T10:20:16Z";
        }
    );
    limit = 10;
    skip = 0;
}
2016-03-24 15:57:26.396  [11383:135614] [QBCore] Response object: {
    items =     (
                {
            "_id" = 56f3bf5f29143db52a0041b0;
            attachments =             (
            );
            "chat_dialog_id" = 56f3bf49a0eb472853000004;
            "created_at" = "2016-03-24T10:20:16Z";
            "date_sent" = 1458814815;
            "delivered_ids" =             (
                11071986
            );
            "dialog_id" = 56f3bf49a0eb472853000004;
            message = "Update the dialogand check";
            read = 0;
            "read_ids" =             (
                11071986
            );
            "recipient_id" = "<null>";
            "sender_id" = 11071986;
            "updated_at" = "2016-03-24T10:20:16Z";
        }
    );
    limit = 10;
    skip = 0;
}
2016-03-24 15:57:26.405  [11383:135616] Messages to insert 1
2016-03-24 15:57:26.405  [11383:135616] Messages to update 0
2016-03-24 15:57:26.407  [11383:135601] [QBCore] Request URL:https://api.quickblox.com/chat/Message.json?chat_dialog_id=56f3bf49a0eb472853000004&date_sent%5Blt%5D=1458814815&limit=10&sort_desc=date_sent
2016-03-24 15:57:26.408  [11383:135601] [QBCore] Request method: GET
2016-03-24 15:57:26.408  [11383:135601] [QBCore] Request parameters:{
    "chat_dialog_id" = 56f3bf49a0eb472853000004;
    "date_sent[lt]" = 1458814815;
    limit = 10;
    "sort_desc" = "date_sent";
}
2016-03-24 15:57:26.409  [11383:135601] [QBCore] Request headers: {
    "Content-Type" = "application/json";
    "QB-OS" = "iOS 9.2";
    "QB-SDK" = "iOS 2.7";
    "QB-Token" = ad9c961831723eb3013371fac0e075d7a79bb70a;
    "QuickBlox-REST-API-Version" = "0.1.1";
}
(lldb)

**Comment by Raikerian** [comment]
There is no crash in your log. I guess you have catch an exception breakpoint, press Resume until crash will appear in your console.

**Comment by Raikerian** [comment]
@ajay2c9 

Any updates?

**Comment by ajay2c9** [comment]
Hi, Thank you for suggestion.I just find the exception crash and fixed it .Its working fine now.
Thank you
