### ISSUE TITLE
Error: unable to perform requested action: authorization failed

### ISSUE THREAD

**Issue by woutergoossens** [QuickBlox/quickblox-ios-sdk#36]
![02ad3b8b98d34500a37d9d230f9979ed00](https://cloud.githubusercontent.com/assets/355048/5372136/83360942-8044-11e4-90b1-85bf1581556a.jpeg)

Hi,

I am using the QuickBlox SDK in my application and sometimes I do get this error.
When is this showed to the user and how can I capture an error like this because this error is not shown by my application itself but by the SDK?

Thanks in advance,

Wouter

**Comment by v-ken** [comment]
Any update on this issue? I'm getting the exact same error pop up.

**Comment by soulfly** [comment]
"Forbidden. Need user" means that you have to sign in with user or create a session with user.

This is not about chat login, this is about REST API login
