### ISSUE TITLE
Longitude appears to be the first coordinate for Location fields in Custom Objects

### ISSUE THREAD

**Issue by prometheon** [QuickBlox/quickblox-ios-sdk#361]
When I call this code,
```
let object = QBCOCustomObject()
let coordinates = [37.785834, -122.406417]
object.fields?.setObject(coordinates, forKey: "Location")
QBRequest.createObject(object, successBlock: nil, errorBlock: nil)
```
no object is created. But when I switch the coordinates so that -122.406 is first, the object is created. It appears that the second value can't range from -180 to 180 (the range for longitude). Traditionally latitude comes first in coordinates. Maybe it just got switched?

**Comment by soulfly** [comment]
http://quickblox.com/developers/Custom_Objects#Module_description

**Location (array with 2 elements: longitude, latitude)**
