### ISSUE TITLE
Double View when open a chat

### ISSUE THREAD

**Issue by MJDev1518** [QuickBlox/quickblox-ios-sdk#364]
Hi, i have navigation controller, and when i am on the DialogsController and i PerformSegue to the chat with the dialog id, It work but i have a useless view between Dialog and chat. 
So when i'm on the ChatController and I back I go on a Blank chat .. and i Need to Back again to go to DialogController ?? I don't understand this issue ... 

![img_4334](https://cloud.githubusercontent.com/assets/17512679/14040892/360b0366-f26c-11e5-8613-f402ad6668b3.jpg)
![img_4335](https://cloud.githubusercontent.com/assets/17512679/14040894/363d5992-f26c-11e5-8de8-1bdd8b3a30d0.jpg)
![img_4336](https://cloud.githubusercontent.com/assets/17512679/14040893/363ad29e-f26c-11e5-8402-944ef04d7952.jpg)

**Comment by Raikerian** [comment]
Hi,

It is your own custom UI and we do not have this problem in our samples.
To help you solve the issue please do the following:
1. While you on chat controller, print in console 'self.navigationController.viewControllers' to see all controllers in navigation stack.
2. Try to search your code for unexpected controller push.

**Comment by MJDev1518** [comment]
Hi,

thank you for this quick response , I look at that and I stand abreast

**Comment by MJDev1518** [comment]
Ok thanks a lot it's the issue, i have 2 prepareForSegue called but juste 1 performSegue ... I don't understand Why but is the issue and it's not issue of Quickblox, thanks

just for prouve 

=======================================
push in dialog :  [<Flashy.FJTabBarController: 0x140014a60>]
=======================================
=======================================
push in dialog :  [<Flashy.FJTabBarController: 0x140014a60>, <Flashy.ChatViewController: 0x13f10e800>]
=======================================


=======================================
Chat :  [<Flashy.FJTabBarController: 0x140014a60>, <Flashy.ChatViewController: 0x13f10e800>]
=======================================
=======================================
Chat :  [<Flashy.FJTabBarController: 0x140014a60>, <Flashy.ChatViewController: 0x13f10e800>, <Flashy.ChatViewController: 0x13f5a7000>]
=======================================

**Comment by Raikerian** [comment]
Glad to see you have fixed it. If you are still having any other troubles regarding our framework, feel free to create separate issue.
