### ISSUE TITLE
Getting error while install pod file of quickblox project

### ISSUE THREAD

**Issue by muraribohra** [QuickBlox/quickblox-ios-sdk#365]
hello developers,

I am getting errror while installing pod file. It saying that 

[!] Error installing QMCVDevelopment
[!] /usr/bin/git clone git@github.com:QuickBlox/QMChatViewController-ios.git /var/folders/_9/89s12fsj1rz4y0fg6wkm5crm0000gn/T/d20160325-9845-v4bllq

Cloning into '/var/folders/_9/89s12fsj1rz4y0fg6wkm5crm0000gn/T/d20160325-9845-v4bllq'...
Warning: Permanently added the RSA host key for IP address '192.30.252.130' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Please Help what to do.

**Comment by Raikerian** [comment]
Hi,

Follow this guide in order to install github ssh keys: https://help.github.com/articles/set-up-git/

**Comment by muraribohra** [comment]
ya it's done. But now iam getting error that quickblox/quickblox.h file not found. But i already added this framework.

**Comment by Raikerian** [comment]
Please double check framework search paths in Build settings.

Or you can install framework with cocoapods and removed the manual installed one.

**Comment by muraribohra** [comment]
Thnx raikerian.. Can u please tell me, what should i write in podfile to install quickblox from cocoapods?

**Comment by iSevenDays** [comment]
Hi @muraribohra 

you should have the following line in podile

pod 'QuickBlox'

Thanks!
