### ISSUE TITLE
registerSubscriptionForDeviceToken always register for development

### ISSUE THREAD

**Issue by alanfeng99** [QuickBlox/quickblox-ios-sdk#367]
Hi Sir, 

I was wondering why the push notification is not working for my app.

I found out that [QBRequest registerSubscriptionForDeviceToken: ..] always register my user's token as development token. (as I check in QuickBlox backend, all users have only development token)

Any suggestion would be appreciated.

**Comment by iSevenDays** [comment]
Hi @alanfeng99 

https://github.com/QuickBlox/quickblox-ios-sdk/issues/338

**Comment by alanfeng99** [comment]
Hi @iSevenDays , I read that post, but my problem is all my client tokens got marked as development even if this client was downloaded from AppStore. It is still relate to wrong provisioning profile?
