### ISSUE TITLE
User always unauthorized even after successfull login.

### ISSUE THREAD

**Issue by muraribohra** [QuickBlox/quickblox-ios-sdk#369]
Hello , user is successfully login but [[servicemanager instance]isAuthorized] always returns false.
Why this is happening ? Please help.

**Comment by iSevenDays** [comment]
Hi @muraribohra 

QMServicesManager uses QMAuthService isAuthorized property which set after login in REST.

Please provide us full logs

**Comment by muraribohra** [comment]
Thnx. its solved.

**Comment by Brightness99** [comment]
@iSevenDays,
Awesome.
You saved my time.
Thanks.

**Comment by SalmanGhumsani** [comment]
I have successful login with facebook and connected to chat -->
ServicesManager.instance().authService.logInWithFacebookSessionToken(accessToken, completion: { (response, qbUser) in
       print(response)               
})
==============================================================
Now issue is after application restart -->
ServicesManager.instance().chatService.connectWithCompletionBlock { (error) in
            if error != nil {
                print("user not connected error: ",error?.description)
            } else {
                print("user succesful connected")
            }
}
Response -->
Error Domain=com.q-municate.chatservice Code=-1000 \"(null)\" UserInfo={NSLocalizedRecoverySuggestion=You are not authorized in REST.
==============================================================
I re-login via this code -->
let user = ServicesManager.instance().currentUser()!
user.password = QBSession.currentSession().sessionDetails?.token
ServicesManager.instance().authService.logInWithUser(user) { (response, user) in
          print(response.error.debugDescription)
 }
Response -->
Error reasons:{
    errors =     (
        Unauthorized
    );
==============================================================
