### ISSUE TITLE
Delete/leave 1:1 private chat

### ISSUE THREAD

**Issue by woutergoossens** [QuickBlox/quickblox-ios-sdk#37]
Hi,

I am trying to delete/leave a private chat for the 2 users in a private chat.

This works on for 1 user (the dialog is deleted locally and on the server) but how can I delete the dialog for the other user? I don't get a notification on the other device and the dialog still exists when I fetch all the dialogs.

I am using the  [QBChat deleteDialogWithID:dialog.ID .. method.

Thanks in advance,

Wouter Goossens

**Comment by RahulTBI** [comment]
If admin can delete group, all participant will get just system message regarding user has delete group, but how can i update dialog for other user.

other user can see that chat dialog and remaining participant in info about group
