### ISSUE TITLE
So many warnings from QuickbloxWebRTC.

### ISSUE THREAD

**Issue by tranngoclinh88** [QuickBlox/quickblox-ios-sdk#371]
I updated QuickbloxWebRTC to 2.2 and Xcode shows many warnings.
This is a part of it.

<img width="1255" alt="screen shot 2016-03-31 at 8 49 49 am" src="https://cloud.githubusercontent.com/assets/1511264/14163233/8dcca07c-f71d-11e5-8c4c-f96991045d59.png">

Please check!

**Comment by iSevenDays** [comment]
https://github.com/QuickBlox/quickblox-ios-sdk/issues/348
