### ISSUE TITLE
QBSession.startSessionWithDetails Ambiguous use error

### ISSUE THREAD

**Issue by rvilches** [QuickBlox/quickblox-ios-sdk#376]
Hi, I am trying to update my session using the startSessionWith Details but I can't use neither of those methods because they throw this error:

"Ambiguous use of 'startSession With Details(_:expiration Date:)"

Maybe I am using it wrong , I am checking the expiration date of my current session with my current date , if my current session date is older I will call this function.

**Comment by iSevenDays** [comment]
Hi @rvilches 

Please try again

Here is the test code we use

```
let asession = QBASession()
asession.userID = 777
asession.token = "token"
asession.applicationID = 1
		
QBSession.currentSession().startSessionWithDetails(asession) {
			
    // synchronous REST request to a server
    asession.token = "received token"
			
    QBSession.currentSession().startSessionWithDetails(asession)
			
}
```

**Comment by rvilches** [comment]
Ohh thanks I was using it wrong I guess.

**Comment by AnkitSS77** [comment]
I have use the same code 
QBSession.currentSession().startSessionWithDetails(session)
        {
            
            let updatedSession = QBASession.init()
            session.token = "new token"
            QBSession.currentSession().startSessionWithDetails(updatedSession)
             self.performSegueWithIdentifier("chat", sender: self)
        }
but the blog is not call and no logs are available  so what can do for connect with quickblox ?
