### ISSUE TITLE
Emoji not recorded in custom data of users

### ISSUE THREAD

**Issue by cvezina** [QuickBlox/quickblox-ios-sdk#378]
It looks like emojis are not recorded correctly when a call to update users custom data. The emoji is replaced by a question mark. You can reproduce the problem if you try to add an emoji in the custom data part as a json structure using the admin panel. Just save and reload.

**Comment by VitaliyGuru** [comment]
Hi @cvezina,

We were able to reproduce this bug. Looks like it's a server-side issue. Our server team is currently working on it. 

Thank you for reporting the issue.

**Comment by ajay2c9** [comment]
Hi guys  is there any update for this issue. i provided log for this issue in #459. is any log is required.
Please give suggestion to solve this issue.

Thank you.

**Comment by ajay2c9** [comment]
is there any update on this issue?

**Comment by VitaliyGuru** [comment]
@ajay2c9  Unfortunately there is no ETA for this fix. Please follow our [blog](https://quickblox.com/blog/). There you can find all updates.

**Comment by ajay2c9** [comment]
Suggest me for this issue, that how you guys are decoding the text in ChatViewController. This is my code.
NSString*str=@"I&amp;amp;apos;m so tired &amp;amp;amp; I can&amp;amp;apos;t";
 NSString*text = [str gtm_stringByUnescapingFromHTML];
    NSLog(@"the text after decoding is %@",text);
it prints like this     "I&amp;apos;m so tired &amp;amp; I can&amp;apos;t"
But in the detail it is displaying correctly. Give suggestions to decode the text and display the text and emojis correctly.

Thank you

**Comment by Raikerian** [comment]
@ajay2c9 

In out latest version of SDK we are no longer encoding it in chat controller. Encoding/Decoding are managed by SDK itself.

**Comment by ajay2c9** [comment]
Thank you for reply.I got the solution for that. Maybe this useful for others.

NSString *str=@"I&amp;apos;m so tired &amp;amp; I can&amp;apos;t";
NSString *text = [str gtm_stringByUnescapingFromHTML];
text = [text gtm_stringByUnescapingFromHTML];
NSLog(@"the text after decoding is %@",text);

It gives the correct text.

Thank you
