### ISSUE TITLE
Quickblox iOS - group Chat 

### ISSUE THREAD

**Issue by vandanaagile** [QuickBlox/quickblox-ios-sdk#38]
Hi All , 

We have implemented group chat functionality but we are facing one issue . 

After joining group when i come out from dialog i am not able to receive messages of group , so how i can increment badge counter of unread message , though i am getting incoming messages in one to one chat . 

but in group chat  : not able to receive incoming messages from below method . 
- (void)chatRoomDidReceiveMessage:(QBChatMessage )message fromRoomJID:(NSString )roomJID

**Comment by ajay2c9** [comment]
Hi,
I am facing same problem like this way, I read all the messages in the Chat room.but unread messages count is not updated in ChatDialog . How to update the unread messages count after reading all messages. 

Please Give suggestions.
Thank you

**Comment by Raikerian** [comment]
Hi,

in order to receive messages from group chats you need to join them.
Our sample-chat is providing such functionality.

**Comment by iSevenDays** [comment]
@ajay2c9 
Hi
Please use [QBRequest markMessagesAsRead:dialogID:successBlock:errorBlock:]

To read all messages you can call [QBRequest markMessagesAsRead:nil dialogID:dialog_id successBlock:successBlock errorBlock:errorBlock]

**Comment by ajay2c9** [comment]
Thank you for giving suggestions.
