### ISSUE TITLE
Error during sign up

### ISSUE THREAD

**Issue by muraribohra** [QuickBlox/quickblox-ios-sdk#380]
hello sir, I am getting error "Bad timestamp" when i signup in quickblox. Running project in simulator and time is correctly setting. Then why this issue is occuring. 

Log 

Error Domain=com.alamofire.error.serialization.response Code=-1011 "Request failed: client error (422)" UserInfo={com.alamofire.serialization.response.error.response=<NSHTTPURLResponse: 0x79080b50> { URL: https://api.quickblox.com/session.json } { status code: 422, headers {
    "Access-Control-Allow-Origin" = "*";
    "Cache-Control" = "no-cache";
    Connection = "keep-alive";
    "Content-Length" = 37;
    "Content-Type" = "application/json; charset=utf-8";
    Date = "Mon, 04 Apr 2016 10:14:30 GMT";
    "QuickBlox-REST-API-Version" = "0.1.1";
    Server = "nginx/1.8.1";
    Status = "422 Unprocessable Entity";
    "X-Rack-Cache" = "invalidate, pass";
    "X-Request-Id" = e76ef438d617b269033210c6cbe8f102;
    "X-Runtime" = "0.004257";
    "X-UA-Compatible" = "IE=Edge,chrome=1";
} }, NSErrorFailingURLKey=https://api.quickblox.com/session.json, NSLocalizedDescription=Request failed: client error (422), com.alamofire.serialization.response.error.data=<7b226572 726f7273 223a7b22 62617365 223a5b22 42616420 74696d65 7374616d 70225d7d 7d>}
2016-04-04 15:44:08.489 Demo[10619:176317] [QBAuth] Create Session request error: {"errors":{"base":["Bad timestamp"]}}
2016-04-04 15:44:08.512 Demo[10619:176212] error {
    errors =     {
        base =         (
            "Bad timestamp"
        );
    };
}

**Comment by SergeyOleynich** [comment]
@muraribohra Do you fix the problem?

**Comment by muraribohra** [comment]
yes. its done now
