### ISSUE TITLE
Group Call Limitations?

### ISSUE THREAD

**Issue by wukerplank** [QuickBlox/quickblox-ios-sdk#381]
Is there a limitation to how many people join into a group video call?

**Comment by VitaliyGuru** [comment]
Hi @wukerplank ,

The number of users in the group video call is limited only by your hardware. Also, please, notice that there is no ability to join into existing group video chat.

**Comment by VitaliyGuru** [comment]
@wukerplank 
For more further explanation please refer to this link on stackoverflow http://goo.gl/jrR1um

**Comment by wukerplank** [comment]
Thanks for the info!
