### ISSUE TITLE
How to getUsers?

### ISSUE THREAD

**Issue by muraribohra** [QuickBlox/quickblox-ios-sdk#382]
Hello , 
 I want to get users by their ID's but it returning nil.
My code is:

[[[ServicesManager instance].usersService getUsersWithIDs:dialog.occupantIDs] continueWithBlock:^id(BFTask *task) {
        //
        NSLog(@"bftask result %@",task.result);
        return nil;
  }];

if i doing any mistake , then please guide me.
Thanks

**Comment by VitaliyGuru** [comment]
Hi @muraribohra ,

Please attach some logs. Unfortunately we cannot help you with your problem unless we see the them.

**Comment by muraribohra** [comment]
This is the complete log.

[QBCore] Request URL:https://api.quickblox.com/users.json?filter%5B%5D=number%20id%20in%2011126799%2C11240919&page=1&per_page=2
2016-04-04 05:32:43.470 Demo[14280:224300] [QBCore] Request method: GET
2016-04-04 05:32:43.471 Demo[14280:224300] [QBCore] Request parameters:{
    "filter[]" = "number id in 11126799,11240919";
    page = 1;
    "per_page" = 2;
}
2016-04-04 05:32:43.472 Demo[14280:224300] [QBCore] Request headers: {
    "Content-Type" = "application/json";
    "QB-OS" = "iOS 9.0";
    "QB-SDK" = "iOS 2.7";
    "QB-Token" = 070fc435b4b5c97aa531768ce9b867c19674e2fb;
    "QuickBlox-REST-API-Version" = "0.1.1";
}
2016-04-04 05:32:43.776 Demo[14280:224300] [QBCore] Response error: Error Domain=com.alamofire.error.serialization.response Code=-1011 "Request failed: forbidden (403)" UserInfo={com.alamofire.serialization.response.error.response=<NSHTTPURLResponse: 0x7b969d20> { URL: https://api.quickblox.com/users.json?filter%5B%5D=number%20id%20in%2011126799%2C11240919&page=1&per_page=2 } { status code: 403, headers {
    "Access-Control-Allow-Origin" = "*";
    "Cache-Control" = "no-cache";
    Connection = "keep-alive";
    "Content-Length" = 150;
    "Content-Type" = "application/json; charset=utf-8";
    Date = "Mon, 04 Apr 2016 12:32:43 GMT";
    "QB-Token-ExpirationDate" = "2016-04-04 14:20:05 UTC";
    "QuickBlox-REST-API-Version" = "0.1.1";
    Server = "nginx/1.8.1";
    Status = "403 Forbidden";
    "X-Rack-Cache" = miss;
    "X-Request-Id" = eccc14673e12c096ab592af5e8972b02;
    "X-Runtime" = "0.057966";
    "X-UA-Compatible" = "IE=Edge,chrome=1";
} }, NSErrorFailingURLKey=https://api.quickblox.com/users.json?filter[]=number%20id%20in%2011126799%2C11240919&page=1&per_page=2, NSLocalizedDescription=Request failed: forbidden (403), com.alamofire.serialization.response.error.data=<7b226572 726f7273 223a7b22 62617365 223a5b22 55736572 73207265 74726965 76696e67 20666f72 62696464 656e2069 6e206164 6d696e20 70616e65 6c2c2061 70706c69 63617469 6f6e2073 65747469 6e67732e 20536574 75702069 74206865 72652068 74747073 3a2f2f61 646d696e 2e717569 636b626c 6f782e63 6f6d2f61 7070732f 33373938 302f7365 7474696e 6773225d 7d7d>}

**Comment by VitaliyGuru** [comment]
@muraribohra 
As you can see, the request returns you an error. 

We need to get details on this error. Please put a breakpoint in the method implementation
```objectivec
- (BFTask *)getUsersWithIDs:(NSArray *)ids foundUsers:(NSArray *)foundUsers forceDownload:(BOOL)forceDownload page:(QBGeneralResponsePage *)page
```

in the error block, where we set error to the source `[source setError:response.error.error]` and when breakpoint called please print out `[response.error reasons]`

If you need any help feel free to ask.

**Comment by VitaliyGuru** [comment]
@muraribohra 
I think I know where is the problem.   

1. You need to go to the admin.quickblox.com.
2. Then select your app and go to the settings. http://joxi.ru/p27bp9dt8adxm7
3. Then you should select this checkmark. http://joxi.ru/VrwbG80tk9GMAX

It will allow you to retrieve a list of users.

**Comment by muraribohra** [comment]
thnx Guru, It's done.

**Comment by VitaliyGuru** [comment]
@muraribohra 
Glad to hear it.

**Comment by raviWestAgileLabs** [comment]
@ Guru

Hi i followed user steps but getting 404 error

Log:

2017-04-27 12:00:44.296 Graylor[2569:51477] [QBCore] Request URL:https://api.quickblox.com/account_settings.json
2017-04-27 12:00:44.297 Graylor[2569:51477] [QBCore] Request method: GET
2017-04-27 12:00:44.297 Graylor[2569:51477] [QBCore] Request parameters:(null)
2017-04-27 12:00:44.299 Graylor[2569:51477] [QBCore] Request headers: {
    "Accept-Language" = "en;q=1";
    "QB-Account-Key" = uQ9AqrHwonRzzThZ9P7A;
    "QB-OS" = "iOS 10.3";
    "QB-SDK" = "iOS 2.9.2";
    "QB-Token" = 9bbdab39f21f8150142f14db55033803bb00dd8c;
    "QuickBlox-REST-API-Version" = "0.1.1";
    "User-Agent" = "Graylor/1.0 (iPhone; iOS 10.3; Scale/2.00)";
}
2017-04-27 12:00:45.896 Graylor[2569:51661] [QBCore] Response headers: {
    "Access-Control-Allow-Origin" = "*";
    "Cache-Control" = "max-age=0, private, must-revalidate";
    Connection = "keep-alive";
    "Content-Length" = 175;
    "Content-Type" = "application/json; charset=utf-8";
    Date = "Thu, 27 Apr 2017 08:00:45 GMT";
    Etag = "\"dd3ef25cb6cdc6e0f939a0fa9953e3a7\"";
    "QuickBlox-REST-API-Version" = "0.1.1";
    Server = "openresty/1.9.15.1";
    Status = "304 Not Modified";
    "Strict-Transport-Security" = "max-age=15768000;";
    "X-Rack-Cache" = miss;
    "X-Request-Id" = 9fa05000de0aba52752c3261cd3deb19;
    "X-Runtime" = "0.004592";
    "X-UA-Compatible" = "IE=Edge,chrome=1";
}
2017-04-27 12:00:45.897 Graylor[2569:51661] [QBCore] Response object: {
    "account_id" = 70798;
    "api_endpoint" = "https://api.quickblox.com";
    "chat_endpoint" = "chat.quickblox.com";
    "s3_bucket_name" = qbprod;
    "turnserver_endpoint" = "turnserver.quickblox.com";
}
2017-04-27 12:00:45.957 Graylor[2569:51661] [Core] accountSettings: 
 apiEndpoint: https://api.quickblox.com
 chatEndpoint: chat.quickblox.com, 
 turnServerEndpoint: turnserver.quickblox.com, 
 S3BucketName: qbprod, 
 lastCheckDate: 2017-04-27 08:00:45 +0000
2017-04-27 12:00:45.958 Graylor[2569:51661] [QBCore] Request URL:https://api.quickblox.com/users/by_tags.json?page=1&per_page=100&tags=dev
2017-04-27 12:00:45.958 Graylor[2569:51661] [QBCore] Request method: GET
2017-04-27 12:00:45.959 Graylor[2569:51661] [QBCore] Request parameters:{
    page = 1;
    "per_page" = 100;
    tags = dev;
}
2017-04-27 12:00:45.959 Graylor[2569:51661] [QBCore] Request headers: {
    "Accept-Language" = "en;q=1";
    "QB-OS" = "iOS 10.3";
    "QB-SDK" = "iOS 2.9.2";
    "QB-Token" = 9bbdab39f21f8150142f14db55033803bb00dd8c;
    "QuickBlox-REST-API-Version" = "0.1.1";
    "User-Agent" = "Graylor/1.0 (iPhone; iOS 10.3; Scale/2.00)";
}
2017-04-27 12:00:46.999 Graylor[2569:51665] [QBCore] Response error: Error Domain=com.alamofire.error.serialization.response Code=-1011 "Request failed: not found (404)" UserInfo={com.alamofire.serialization.response.error.response=<NSHTTPURLResponse: 0x60000042cc20> { URL: https://api.quickblox.com/users/by_tags.json?page=1&per_page=100&tags=dev } { status code: 404, headers {
    "Access-Control-Allow-Origin" = "*";
    "Cache-Control" = "no-cache";
    Connection = "keep-alive";
    "Content-Length" = 1;
    "Content-Type" = "application/json; charset=utf-8";
    Date = "Thu, 27 Apr 2017 08:00:46 GMT";
    "QB-Token-ExpirationDate" = "2017-04-27 09:50:44 +0000";
    "QuickBlox-REST-API-Version" = "0.1.1";
    Server = "openresty/1.9.15.1";
    Status = "404 Not Found";
    "X-Rack-Cache" = miss;
    "X-Request-Id" = 629c18d0875d9d46d309e8e5aa538a83;
    "X-Runtime" = "0.070628";
    "X-UA-Compatible" = "IE=Edge,chrome=1";
} }, NSErrorFailingURLKey=https://api.quickblox.com/users/by_tags.json?page=1&per_pagError Domain=com.alamofire.error.serialization.response Code=-1011 "Request failed: not found (404)" UserInfo={com.alamofire.serialization.response.error.response=<NSHTTPURLResponse: 0x60000042cc20> { URL: https://api.quickblox.com/users/by_tags.json?page=1&per_page=100&tags=dev } { status code: 404, headers {
    "Access-Control-Allow-Origin" = "*";
    "Cache-Control" = "no-cache";
    Connection = "keep-alive";
    "Content-Length" = 1;
    "Content-Type" = "application/json; charset=utf-8";
    Date = "Thu, 27 Apr 2017 08:00:46 GMT";
    "QB-Token-ExpirationDate" = "2017-04-27 09:50:44 +0000";
    "QuickBlox-REST-API-Version" = "0.1.1";
    Server = "openresty/1.9.15.1";
    Status = "404 Not Found";
    "X-Rack-Cache" = miss;
    "X-Request-Id" = 629c18d0875d9d46d309e8e5aa538a83;
    "X-Runtime" = "0.070628";
    "X-UA-Compatible" = "IE=Edge,chrome=1";
} }, NSErrorFailingURLKey=https://api.quickblox.com/users/by_tags.json?page=1&per_page=100&tags=dev, com.alamofire.serialization.response.error.data=<20>, NSLocalizedDescription=Request failed: not found (404)}
e=100&tags=dev, com.alamofire.serialization.response.error.data=<20>, NSLocalizedDescription=Request failed: not found (404)}
2017-04-27 12:00:47.001 Graylor[2569:51665] [QBCore] Response error reasons: (null)

**Comment by raviWestAgileLabs** [comment]
We need to provide tags while creating the user , otherwise we will get 404 Error.

 Note: Got the 404 error and added tags to user issue resolved

**Comment by VitaliyGuru** [comment]
@raviWestAgileLabs, 
Hello. 
Please create a separate issue and describe actual and expected behavior in details.

**Comment by primeappsin** [comment]
I have check Allow to retrieve a list of users and add tags the also getting 404 error

**Comment by mikeRozen** [comment]
I started to experience the same issue  
It seems that this option no longer exists in the setting....

**Comment by VitaliyGuru** [comment]
@mikeRozen, Please create a separate issue and attach full logs.
