### ISSUE TITLE
Users not getting in sequence as request.

### ISSUE THREAD

**Issue by muraribohra** [QuickBlox/quickblox-ios-sdk#385]
Hello, I am facing an issue. I am getting users by thier ID's. 

My array is: (
9049458,
9049449,
11459612,
11461657
)

but it doesn't retrun users in sequence as my request.

Please help. Thank you

**Comment by VitaliyGuru** [comment]
Hello @muraribohra ,
What method do you use to get users by ID's? Could you please show your code.

**Comment by muraribohra** [comment]
@VitaliyGuru  I am using this code:

 [[[ServicesManager instance].usersService getUsersWithIDs:occupantIds] continueWithBlock:^id(BFTask *task) {
        arrUserinfo= task.result;
        return nil;
    }];

**Comment by VitaliyGuru** [comment]
@muraribohra 
unfortunately we haven't this functionality, in method  getUsersWithIDs we sort users by ID's.

You can write your own logic for custom sorting of users.

**Comment by muraribohra** [comment]
ok thanks.. I done it on my level.

**Comment by Raikerian** [comment]
Hey @muraribohra , glad to see you were able to solve it. If you are still having any other troubles, feel free to let us know by creating a separate issue. Have a good day!
