### ISSUE TITLE
<QBChatDialog 0x7b046870> valueForUndefinedKey:]: this class is not key value coding-compliant for the key lastMessage.

### ISSUE THREAD

**Issue by muraribohra** [QuickBlox/quickblox-ios-sdk#386]
Hello , When i fetch dialogs it returning me this:

ID:**********0001c                      
    Created At:(null)                      
    Updated At:2016-04-08 06:56:36 +0000                      
    Room JID:(null)                      
    name:userplus                      
    photo:(null)                      
    type:3                      
    lastMessage:user plus                      
    lastMessageDate:2016-04-08 06:56:36 +0000                      
    occupantIDs:(
    ******49,
    ******30
)                      
    userID:******49                      
    data:(null)                      
    unreadMessagesCount:0                      
    lastMessageUserID:******30,

But when i try to access "lastMessage", it giving me above error.

I think it's a sdk issue. Because QBChatDialog don't have any variable named "lastMessage". There is "lastMessageText". By using "lastMessageText", it's working fine.

If I am not wrong then please fix it.

Thanks

**Comment by VitaliyGuru** [comment]
Hi @muraribohra ,
There is no property for QBChatDialog with name lastMessage. 
lastMessage we get from response and set it to lastMessageText property for QBChatDialog.

Please, use lastMessageText.

**Comment by muraribohra** [comment]
thanks @VitaliyGuru
