### ISSUE TITLE
Issues when creating the new. I am using QuickBlox SDK

### ISSUE THREAD

**Issue by Pinturaj** [QuickBlox/quickblox-ios-sdk#388]
user =     {
        login = login;
        password = password;
    };
}
2016-04-11 20:19:10.688 TravelX[12776:226512] [QBCore] Request headers: {
    "Content-Type" = "application/json";
    "QB-OS" = "iOS 9.2";
    "QB-SDK" = "iOS 2.7";
    "QB-Token" = 7f2100760be45e27b5d26ed67f265616656e1a2a;
    "QuickBlox-REST-API-Version" = "0.1.1";
}
2016-04-11 20:19:11.751 TravelX[12776:226547] [QBCore] Response error: Error Domain=com.alamofire.error.serialization.response Code=-1011 "Request failed: client error (422)" UserInfo={com.alamofire.serialization.response.error.response=<NSHTTPURLResponse: 0x7885ce20> { URL: https://api.quickblox.com/users.json } { status code: 422, headers {
    "Access-Control-Allow-Origin" = "*";
    "Cache-Control" = "no-cache";
    Connection = "keep-alive";
    "Content-Length" = 47;
    "Content-Type" = "application/json; charset=utf-8";
    Date = "Mon, 11 Apr 2016 14:41:00 GMT";
    "QB-Token-ExpirationDate" = "2016-04-11 16:29:04 UTC";
    "QuickBlox-REST-API-Version" = "0.1.1";
    Server = "nginx/1.8.1";
    Status = "422 Unprocessable Entity";
    "X-Rack-Cache" = "invalidate, pass";
    "X-Request-Id" = e05f43c0b5e93204d589aaa9aeb0fac9;
    "X-Runtime" = "0.109687";
    "X-UA-Compatible" = "IE=Edge,chrome=1";
} }, NSErrorFailingURLKey=https://api.quickblox.com/users.json, NSLocalizedDescription=Request failed: client error (422), com.alamofire.serialization.response.error.data=<7b226572 726f7273 223a7b22 6c6f6769 6e223a5b 22686173 20616c72 65616479 20626565 6e207461 6b656e22 5d7d7d>}
2016-04-11 20:19:11.751 TravelX[12776:226363] Failure [QBResponse], status: 422

AND ALREADY INSTIALISE THE SDK
[QBSettings setApplicationID:kQBApplicationID];
    [QBSettings setAuthKey:kQBAuthorizationKey];
    [QBSettings setAuthSecret:kQBAuthorizationSecret];
    [QBSettings setAccountKey:kQBAccountKey];

**Comment by Raikerian** [comment]
Hi @Pinturaj 

Please print this in errorBlock of QBRequest:

```objectivec
[response.error reasons]
```

**Comment by Pinturaj** [comment]
ok

**Comment by Pinturaj** [comment]
ok gotted.
Problem was from user.login, because i assign same user again and again. So that why this problem arise.

Thanks lot

**Comment by Raikerian** [comment]
If you are still having any other troubles, please let us know by creating a separate issue.
