### ISSUE TITLE
Quickblox iOS - Block User

### ISSUE THREAD

**Issue by vandanaagile** [QuickBlox/quickblox-ios-sdk#39]
Does Quickblox provides user block functionality ?

Thanks

**Comment by hiteshtrivedi** [comment]
Hi,
I am not able to add block multiple users in 1-1 private chat.
Can you please suggest what to do.

This is my code

let strUserID = String(qbFriendID)
        let item: QBPrivacyItem = QBPrivacyItem(type: USER_ID, valueForType: qbFriendID, action: DENY)
        let list: QBPrivacyList = QBPrivacyList(name: strUserID, items: [item])
        QBChat.instance().addDelegate(self)
        QBChat.instance().setPrivacyList(list)
        QBChat.instance().setDefaultPrivacyListWithName(strUserID)

**Comment by hiteshtrivedi** [comment]
Hi
How to resolve this issue.
"Can not modify list while being in use by other session"

**Comment by Raikerian** [comment]
@hiteshtrivedi 

Please create a separate issue and attach full logs using gist.github.com

**Comment by ajay2c9** [comment]
Hi,
I have multiple users in the privacy list with action: DENY. How to update the status of single user in the privacy list action: Allow or how to remove the user from privacy list and updated.
