### ISSUE TITLE
Some emojis are displaying as text.

### ISSUE THREAD

**Issue by ajay2c9** [QuickBlox/quickblox-ios-sdk#391]
Hi,
While sending the emojis, In ChatViewController those are displaying correctly but in the Dialog last message some emojis are displaying as text. how to display the emojis not like text.
![simulator screen shot apr 13 2016 10 16 03 pm](https://cloud.githubusercontent.com/assets/9112899/14501818/eafb18fc-01c5-11e6-9035-605ce199b610.png)
![simulator screen shot apr 13 2016 10 15 50 pm](https://cloud.githubusercontent.com/assets/9112899/14501819/eaff569c-01c5-11e6-92f0-601fa4e0cd7c.png)

**Comment by VitaliyGuru** [comment]
Hi @ajay2c9,
It's a server side issue. Last message of the dialog we get from the server. There are some issues with coding of emojis. Our server team is currently working on it.

**Comment by ajay2c9** [comment]
Thank you for reply

**Comment by ajay2c9** [comment]
HI, i am facing the same issue with emojis in my project. 
![screen shot 2016-05-17 at 8 19 31 pm](https://cloud.githubusercontent.com/assets/9112899/15326798/f35f6e3c-1c6c-11e6-834f-ec9985d32ece.png)

Not only with the emojis but also with some code like won't, don't, can't  some characters are printing before the ' , & symbols. plz check the below screen shots.
![screen shot 2016-05-17 at 8 19 42 pm](https://cloud.githubusercontent.com/assets/9112899/15326859/260f5996-1c6d-11e6-8c87-a55a4312b2e1.png)

Original text:

![screen shot 2016-05-17 at 8 19 55 pm](https://cloud.githubusercontent.com/assets/9112899/15326869/2f0845b2-1c6d-11e6-9988-cd476d3b1d80.png)


I am using the latest quickblox like 2.7.2 and QMServices 0.4. 
Please give suggestions for this. 

Thank you
