### ISSUE TITLE
How do I enforce Portrait mode in QBRTCCameraCapture?

### ISSUE THREAD

**Issue by shalem93** [QuickBlox/quickblox-ios-sdk#392]
Hi, we want to eliminate the landscape view from our video capture, how do we do this?

[self.videoCapture.previewLayer.connection setVideoOrientation:AVCaptureVideoOrientationPortrait];

It seems like the framework is resetting the video orientation upon tilting the camera and we would like to eliminate this^

Thank you

**Comment by Pro100Andrey** [comment]
Hi @shalem93
https://github.com/QuickBlox/quickblox-ios-sdk/issues/262

**Comment by shalem93** [comment]
Thanks that worked perfectly ! Appreciate the help
