### ISSUE TITLE
Audio is very quiet from speaker upon initializing call

### ISSUE THREAD

**Issue by shalem93** [QuickBlox/quickblox-ios-sdk#393]
When we first enter a video call, we are getting "rtc::Set override Speaker" which is the proper call, but the audio is very quiet coming from the phone. We then have a switch statement that handles when a headset is plugged and unplugged. Once we plug in the phone after we are connected by video chat, the audio becomes so much louder and clearer like it should be. We can even then disconnect the headphones and our speaker will then be much clearer as well. We do not know why the audio from the speaker is so quiet when we are first in the video chat without headphones and need help :)

Thanks

**Comment by kutakmir** [comment]
we got it sorted, the proper calling order of the QBRTC init methods is this:
```
    [QBRTCClient initializeRTC];
    [QBRTCSoundRouter.instance initialize];
    QBRTCSoundRouter.instance.currentSoundRoute = QBRTCSoundRouteReceiver;
```

and then you can check for the correct sound route and establish it. You cannot just set it to Speaker right away.
