### ISSUE TITLE
VideoCall error "Service not available".

### ISSUE THREAD

**Issue by muraribohra** [QuickBlox/quickblox-ios-sdk#397]
Hello, During video call , I am receiving this log.

Error RCV: <message xmlns="jabber:client" type="error" to="11485630-35210@chat.quickblox.com/208ABC10-1CB3-474C-B84F-10D0A1D1F1C5" id="1033370210" from="9049437-92@chat.quickblox.com"><extraParams xmlns="jabber:client"><callType>1</callType><sdkVersion>2.2</sdkVersion><sdp>v=0
o=- 3473108818335477502 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE audio video
a=msid-semantic: WMS com.quickblox.mediastream.device-simulator_ios-9.0_userid-11485630]
m=audio 48464 UDP/TLS/RTP/SAVPF 111 103 104 9 102 0 8 106 105 13 127 126
c=IN IP4 52.20.147.93
a=rtcp:54191 IN IP4 52.1.106.254
a=candidate:1434301788 1 udp 2122260223 192.168.0.10 60158 typ host generation 0
a=candidate:1434301788 2 udp 2122260222 192.168.0.10 52134 typ host generation 0
a=candidate:469649836 1 tcp 1518280447 192.168.0.10 50518 typ host tcptype passive generation 0
a=candidate:469649836 2 tcp 1518280446 192.168.0.10 50519 typ host tcptype passive generation 0
a=candidate:2741881992 1 udp 1686052607 115.252.121.85 60158 typ srflx raddr 192.168.0.10 rport 60158 generation 0
a=candidate:2741881992 2 udp 1686052606 115.252.121.85 52134 typ srflx raddr 192.168.0.10 rport 52134 generation 0
a=candidate:1746566506 1 udp 41885439 52.20.147.93 48464 typ relay raddr 115.252.121.85 rport 60158 generation 0
a=candidate:2276968504 2 udp 41885438 52.1.106.254 54191 typ relay raddr 115.252.121.85 rport 52134 generation 0
a=candidate:647594394 2 udp 25108478 52.20.147.93 47554 typ relay raddr 115.252.121.85 rport 50524 generation 0
a=candidate:3375641800 1 udp 25108479 52.1.106.254 43926 typ relay raddr 115.252.121.85 rport 50525 generation 0
a=ice-ufrag:dug/G2WCYmngkLUy
a=ice-pwd:RLdxgsylu585QJ6kbWj34DMJ
a=fingerprint:sha-256 0B:39:FE:12:8E:29:86:C8:BF:1B:06:E4:BC:07:C1:FE:14:3B:15:31:89:1B:B8:1E:17:FA:64:90:63:EC:71:21
a=setup:actpass
a=mid:audio
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=sendrecv
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10; useinbandfec=1
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:102 ILBC/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:127 red/8000
a=rtpmap:126 telephone-event/8000
a=maxptime:60
a=ssrc:764025993 cname:YmeZD9owx2D83ZV2
a=ssrc:764025993 msid:com.quickblox.mediastream.device-simulator_ios-9.0_userid-11485630] audioTrack
a=ssrc:764025993 mslabel:com.quickblox.mediastream.device-simulator_ios-9.0_userid-11485630]
a=ssrc:764025993 label:audioTrack
m=video 36595 UDP/TLS/RTP/SAVPF 100 101 107 116 117 96 97 99 98
c=IN IP4 52.20.147.93
a=rtcp:33589 IN IP4 52.1.106.254
a=candidate:1434301788 1 udp 2122260223 192.168.0.10 57813 typ host generation 0
a=candidate:1434301788 2 udp 2122260222 192.168.0.10 58326 typ host generation 0
a=candidate:469649836 1 tcp 1518280447 192.168.0.10 50520 typ host tcptype passive generation 0
a=candidate:469649836 2 tcp 1518280446 192.168.0.10 50521 typ host tcptype passive generation 0
a=candidate:2741881992 2 udp 1686052606 115.252.121.85 58326 typ srflx raddr 192.168.0.10 rport 58326 generation 0
a=candidate:2741881992 1 udp 1686052607 115.252.121.85 57813 typ srflx raddr 192.168.0.10 rport 57813 generation 0
a=candidate:1746566506 1 udp 41885439 52.20.147.93 36595 typ relay raddr 115.252.121.85 rport 57813 generation 0
a=candidate:2276968504 2 udp 41885438 52.1.106.254 33589 typ relay raddr 115.252.121.85 rport 58326 generation 0
a=candidate:3375641800 2 udp 25108478 52.1.106.254 43331 typ relay raddr 115.252.121.85 rport 50523 generation 0
a=candidate:647594394 1 udp 25108479 52.20.147.93 33061 typ relay raddr 115.252.121.85 rport 50522 generation 0
a=ice-ufrag:dug/G2WCYmngkLUy
a=ice-pwd:RLdxgsylu585QJ6kbWj34DMJ
a=fingerprint:sha-256 0B:39:FE:12:8E:29:86:C8:BF:1B:06:E4:BC:07:C1:FE:14:3B:15:31:89:1B:B8:1E:17:FA:64:90:63:EC:71:21
a=setup:actpass
a=mid:video
a=extmap:2 urn:ietf:params:rtp-hdrext:toffset
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:4 urn:3gpp:video-orientation
a=sendrecv
a=rtcp-mux
a=rtpmap:100 VP8/90000
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=rtcp-fb:100 goog-remb
a=rtcp-fb:100 transport-cc
a=rtpmap:101 VP9/90000
a=rtcp-fb:101 ccm fir
a=rtcp-fb:101 nack
a=rtcp-fb:101 nack pli
a=rtcp-fb:101 goog-remb
a=rtcp-fb:101 transport-cc
a=rtpmap:107 H264/90000
a=rtcp-fb:107 ccm fir
a=rtcp-fb:107 nack
a=rtcp-fb:107 nack pli
a=rtcp-fb:107 goog-remb
a=rtcp-fb:107 transport-cc
a=rtpmap:116 red/90000
a=rtpmap:117 ulpfec/90000
a=rtpmap:96 rtx/90000
a=fmtp:96 apt=100
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=101
a=rtpmap:99 rtx/90000
a=fmtp:99 apt=107
a=rtpmap:98 rtx/90000
a=fmtp:98 apt=116
a=ssrc-group:FID 3312872536 2459368284
a=ssrc:3312872536 cname:YmeZD9owx2D83ZV2
a=ssrc:3312872536 msid:com.quickblox.mediastream.device-simulator_ios-9.0_userid-11485630] videoTrack
a=ssrc:3312872536 mslabel:com.quickblox.mediastream.device-simulator_ios-9.0_userid-11485630]
a=ssrc:3312872536 label:videoTrack
a=ssrc:2459368284 cname:YmeZD9owx2D83ZV2
a=ssrc:2459368284 msid:com.quickblox.mediastream.device-simulator_ios-9.0_userid-11485630] videoTrack
a=ssrc:2459368284 mslabel:com.quickblox.mediastream.device-simulator_ios-9.0_userid-11485630]
a=ssrc:2459368284 label:videoTrack
</sdp><moduleIdentifier>WebRTCVideoChat</moduleIdentifier><sessionID>E4DE9982-596C-4C3C-981A-5E46DA7E613C</sessionID><callerID>11485630</callerID><platform>ios</platform><signalType>call</signalType><userInfo><startCall>userInfo</startCall></userInfo><opponentsIDs><opponentID>9049437</opponentID></opponentsIDs></extraParams><error type="cancel" code="503"><service-unavailable xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/><text xmlns="urn:ietf:params:xml:ns:xmpp-stanzas" lang="en">Service not available.</text></error></message>

What should i do?

**Comment by ErShreyansh12** [comment]
Hello
