### ISSUE TITLE
logOutWithSuccessBlock incomplete

### ISSUE THREAD

**Issue by cvezina** [QuickBlox/quickblox-ios-sdk#399]
Calling [QBRequest logOutWithSuccessBlock] does not call QBChat disconnect if a connection exist. I was expecting that everything was cleanup when calling logOutWithSuccessBlock. Right now, I have to disconnect from active chat before calling logOutWithSuccessBlock .

**Comment by Raikerian** [comment]
Hi @cvezina 

You are completely right, those methods are not linked. QBRequest and QBChat are separate models and it was never mentioned that logOutWithSuccessBlock will do QBChat cleanup.

Check out our [QMServices](https://github.com/QuickBlox/q-municate-services-ios) project, it has a lot of wrapper methods over our SDK and should be very helpful for you.
