### ISSUE TITLE
There is no success block in [[QBChat instance] sendMessage:message sentBlock:

### ISSUE THREAD

**Issue by mitchellporter** [QuickBlox/quickblox-ios-sdk#40]
Right now when you send a message, and call the method below, the block only fires if there has been an error. I am assuming this block is only being fired when there is an error, but at the least it should still be fired and passed a nil error object.

Otherwise there is no way to tell if the message object was successfully sent to the Quickblox database. As far as I can tell, no other chat delegate methods are being called when a message is successfully sent to Quickblox.

Is there currently a delegate method being called or a notification that I can listen for to make sure that my message objects are successfully being uploaded to Quickblox?

```Objective-C 
[[QBChat instance] sendMessage:message sentBlock:^(NSError *error) {
    
            }
       }];
```

**Comment by soulfly** [comment]
Look at QBChat.h, there should be a boolean property to enable it
Without it the sent block will not work at all

**Comment by mitchellporter** [comment]
Here are the properties that are in my `QBChat.h` file:
```Objective-C
/** QBChat delegate for callbacks */
@property (nonatomic, retain) id<QBChatDelegate> delegate;

/** Contact list */
@property (nonatomic, readonly) QBContactList *contactList;

/** Contact list mechanism */
@property (nonatomic, assign) BOOL useMutualSubscriptionForContactList;

/** Array of registered video chat instances */
@property (readonly) NSMutableArray *registeredVideoChatInstances;
```
Are you telling me to enable the `useMutualSubscriptionForContactList` property?

**Comment by ems305** [comment]
@mitchellporter I faced a similar question and found it hidden in the QBSettings file:

https://github.com/QuickBlox/quickblox-ios-sdk/blob/master/Framework/Quickblox.framework/Versions/A/Headers/QBSettings.h#l180-195

Without documentation (at least that I could find) one could easily assume this to be a bug. @soulfly any chance we could get this documented in the quickblox docs?

**Comment by mitchellporter** [comment]
@ems305 Thanks Erik! Definitely needs to be added to the docs.

**Comment by soulfly** [comment]
Already there with release iOS SDK 2.2
