### ISSUE TITLE
Unable to accept the video call.

### ISSUE THREAD

**Issue by lalitasaini** [QuickBlox/quickblox-ios-sdk#400]
Hello ,
 I am unable to receive video call. Generated Log is:

[log](https://gist.github.com/Pro100Andrey/b3824c2b0a02f7aacf2aee2ad5cd73e5)

What to do? Thanks

**Comment by VitaliyGuru** [comment]
Hi @lalitasaini ,
From your logs we've noticed that you call hangUp method. Do you have any reasons to do this?

**Comment by lalitasaini** [comment]
HangUp method is called when user press "RED" button.

**Comment by lalitasaini** [comment]
I noticed a thing.. if i use following coding then i unable to receive call.
Settings *settings = Settings.instance;
self.cameraCapture = [[QBRTCCameraCapture alloc] initWithVideoFormat:settings.videoFormat
                                                                    position:settings.preferredCameraPostion];
[self.cameraCapture startSession];


If i don't use 'Setting' class then it works but video quality is very poor.

 QBRTCVideoFormat *format = [QBRTCVideoFormat defaultFormat];
 AVCaptureDevicePosition postiong;
        
 self.cameraCapture = [[QBRTCCameraCapture alloc] initWithVideoFormat:format
                                                                    position:postiong];
 [self.cameraCapture startSession];
   


What is the problem with Setting class?

**Comment by VitaliyGuru** [comment]
@lalitasaini , Do you use your own AVCaptureSession somewhere in the project?

**Comment by lalitasaini** [comment]
no.I am not using my own AVCaptureSession.

**Comment by VitaliyGuru** [comment]
@lalitasaini  Could you please provide to use the test project with this issue?

**Comment by Raikerian** [comment]
Hi @lalitasaini 

Were you able to fix it? If not yet, any updates on this issue?

**Comment by Pro100Andrey** [comment]
Hi @lalitasaini, Any updates ?

**Comment by Raikerian** [comment]
We haven't received any updates from you.
If you are still having any other troubles, feel free to create a separate issue.
