### ISSUE TITLE
Error 414 after connectWithUser

### ISSUE THREAD

**Issue by redlabrat** [QuickBlox/quickblox-ios-sdk#401]
Receiving error 414 while user login or register. I think error occurred at method call:
[[QBChat instance] connectWithUser:user completion:completion];
Main question is why this error can occur and what does it mean for quickblox? Because I can not reproduce this error but one of my users faces with it all the time. Which parameters I should look for to solve this error?
![1 1](https://cloud.githubusercontent.com/assets/1981754/14607252/76638638-0589-11e6-894a-c20f4f55cc8e.jpg)

**Comment by VitaliyGuru** [comment]
Hi @redlabrat , 
Do you use for login and registration only Quickblox API or do you have requests to another API?
Are you sure that you are getting this error from Quickblox API?
Please, could you provide us code you're using for login/registration.

**Comment by redlabrat** [comment]
Line 
> [[QBChat instance] connectWithUser:user completion:completion]
, 
where I supose error 414 appears, placed inside 

> self.chatService.connectWithCompletionBlock(...)
.

//  QuickBlox service
class QMAPI: QMServicesManager {
func connectChat(completion: QMAPIChatSimpleCompletion?) {
    self.chatService.connectWithCompletionBlock { (error: NSError?) -> Void in   //  chatService - instance of class QMChatService
      completion?(error: error)
    }
    
}
func signUp(user: QBUUser, completion: QMAPIAuthSimpleCompletion?) {
    var request: QBRequest?
    request = self.authService.signUpAndLoginWithUser(user) { (response: QBResponse!, userProfile: QBUUser!) -> Void in  //  authService - instance of class QMAuthService
      if response.success {
        self.connectChat({ (error) -> () in
          if let error = error {
            completion?(error) }
          else { self.successLogin(completion) }
        })
      }
      else {
        completion?(response.error.error)
      }
    }
  }
    …
}
//  Code from controller to start sign up
…
let newUser = QBUUser()
newUser.login = userLogin
newUser.password = userPassword
newUser.phone = userPhone
    
self.signUp(newUser, completion: completion)

**Comment by Raikerian** [comment]
Hi @redlabrat 

That error looks like REST one. This is for sure not a QBChat error (XMPP). Does your user get this error when he is trying to sign up or log in? Let us know all QBRequest methods that you are using on that page. So far you have posted only sign up and login one. Those are POST method requests (and error is looking like a GET one).

But without any logs it is really hard to get into the issue. Any chance you can get them? (By asking user to catch them or by asking him for account to try).

Also, is there any chance you have your own GET requests in your app, or is it only Quickblox server module you are using?

**Comment by redlabrat** [comment]
Hi, @Raikerian 
Sorry, forgot to answer that part of the question: there are no other methods that works with the network on the screens for login and signup.
User get this error when tries to log in and when tries to register. I think that error occurred in  

> [[QBChat instance] connectWithUser:user completion:completion]

because I collected some log for all errors that server gives as answer for requests of login or signup on user side and I did not get any log for 414. And now I found this part and could not get any information about this error in log. And at the same time method 
self.chatService.connectWithCompletionBlock(...) was used in both cases signup and login.

**Comment by VitaliyGuru** [comment]
@redlabrat , connectWithCompletionBlock doesn't use API calls.

> But without any logs it is really hard to get into the issue. Any chance you can get them? (By asking user to catch them or by asking him for account to try).

Unfortunately without logs we can't help you.

**Comment by Raikerian** [comment]
@redlabrat any updates on this?

**Comment by redlabrat** [comment]
Solved!

Problem was with the sync of the contacts of the user with the server. If user had big list of contacts this will form very big query to the server which will generate Error 414. So we divided one sync query into several small queries and it works.
