### ISSUE TITLE
Mark all messages as read when joining the dialog

### ISSUE THREAD

**Issue by sertony** [QuickBlox/quickblox-ios-sdk#405]
Can I mark all messages in the dialog as read when I join it without downloading them all?

I'd like to have an experience when a user sees the number of unread messages in the dialogs list but after switching to a specific dialog screen he has no unread messages in this dialog anymore.

**Comment by VitaliyGuru** [comment]
Hi @sertony , please refer to this [issue](https://github.com/QuickBlox/q-municate-services-ios/issues/194)

**Comment by sertony** [comment]
Hi @VitaliyGuru, thank you
