### ISSUE TITLE
privateUrlForID replacement for privateUrlForFileUID

### ISSUE THREAD

**Issue by UtkuDalmaz** [QuickBlox/quickblox-ios-sdk#406]
- (NSString *)photoUrlWithGroup:(QBChatDialog *)dialog {
    return [QBCBlob privateUrlForID:[dialog.photo integerValue]];
}

Hi,
How can i replace this code with new privateUrlForFileUID ?

Thanks

**Comment by Raikerian** [comment]
Hi @UtkuDalmaz 

Just store from now on blob UID instead of ID in your photo url.
To determine whether your photo will be UID or ID next time, use this example from our QMServices project: https://github.com/QuickBlox/q-municate-services-ios/blob/master/QMChatService/QMChatService/QMChatAttachmentService.m#L134

**Comment by VitaliyGuru** [comment]
@UtkuDalmaz , 
Have you figured out?

**Comment by UtkuDalmaz** [comment]
@VitaliyGuru 
Nope. It is a wrapper library and i cannot change it :)

**Comment by VitaliyGuru** [comment]
You should just take code snippet from that example. 
For your needs you can use the following code:

```
    NSString *photoID = ... //dialog.photo;
    
    NSString * privateStringURL = nil;
    
    NSCharacterSet *notDigits = [[NSCharacterSet decimalDigitCharacterSet] invertedSet];
    
    if ([photoID rangeOfCharacterFromSet:notDigits].location == NSNotFound) {
        privateStringURL = [QBCBlob privateUrlForID:photoID.integerValue];
    }
    else {
        // photo ID is UID
        privateStringURL =  [QBCBlob privateUrlForFileUID:photoID];
    }
```

**Comment by Raikerian** [comment]
If you are still having any other troubles, feel free to create a separate issue.
