### ISSUE TITLE
Proper subclassing of QBCOCustomObject

### ISSUE THREAD

**Issue by kutakmir** [QuickBlox/quickblox-ios-sdk#407]
How should we subclass the custom object in order to directly create the custom classes from QBRequest objectsWithClassName?

In Parse and other Backendless you'd register the subclass so the framework will parse it and return respective subclasses automatically.

**Comment by Raikerian** [comment]
Hi @kutakmir 

You can subclass from QBCOCustomObject and set all your custom properties setters to fill data in fields property of super class.

We will consider to update this logic parse-like in a near future releases.

**Comment by Pro100Andrey** [comment]
@kutakmir thanks for reply, we will consider to add this to following 3.0 update
