### ISSUE TITLE
No chat message items in new version.

### ISSUE THREAD

**Issue by matrosovDev** [QuickBlox/quickblox-ios-sdk#408]
Hey guys, thanks for updates, seems we now don't have chat message items right `@property (strong, nonatomic) NSMutableArray *items`. The problem that I have used items in my subclasses, what else can I use to replace items?

Thanks!

**Comment by Raikerian** [comment]
Hi @matrosovDev 

I am assuming you are talking about [QMChatViewController](https://github.com/QuickBlox/QMChatViewController-ios) project? If yes, there is no single array of items anymore. See [QMChatSectionManager](https://github.com/QuickBlox/QMChatViewController-ios/blob/master/QMChatViewController/QMChatSection/QMChatSectionManager.h) class. If you need them for your own purposes there is a possibility to get them from all chat sections, just create readonly property or getter method:

```objectivec
- (NSArray *)allMessages {
    
    NSMutableArray *mutableItems = [NSMutableArray array];
    
    for (QMChatSection *chatSection in self.chatSections) {
        
        [mutableItems addObjectsFromArray:chatSection.messages];
    }
    
    return mutableItems.copy;
}
```

We will add this as an improvement in a future releases.

**Comment by matrosovDev** [comment]
@Raikerian Thanks one more time! your save all my day I guess! let me try)

**Comment by matrosovDev** [comment]
hm, can't find chatSection in ChatViewController(

**Comment by Raikerian** [comment]
> See [QMChatSectionManager](https://github.com/QuickBlox/QMChatViewController-ios/blob/master/QMChatViewController/QMChatSection/QMChatSectionManager.h) class.

**Comment by matrosovDev** [comment]
hm seems can't get it from swift files. do you have the same example for swift? thanks

**Comment by matrosovDev** [comment]
@property (strong, nonatomic) NSArray *chatSections is a private

**Comment by Raikerian** [comment]
It is private. You need to modify .m file.

**Comment by matrosovDev** [comment]
yea I modified but QMChatSection undeclared for me
`let sections = chatSectionManager.chatSections;
    
    let tempArray = [QBChatMessage]()
    
    for section in sections as! [QMChatSection] {
      for message in section.messages {
        tempArray.append(message)
      }
    }`

**Comment by Raikerian** [comment]
You need to modify QMChatSectionManager.m file and not QMChatSection one.
Also do not modify swift version of it. Open it as original file (use file inspector to find it).

**Comment by matrosovDev** [comment]
yea I have not modified QMChatSection it trows me an error:

Use of undeclared type 'QMChatSection'

**Comment by Raikerian** [comment]
You have linked me a swift code, open QMChatSectionManager as original file (objective-c).

**Comment by matrosovDev** [comment]
It's my sources I've added, I worked with QMChatSectionManager.m and move property to .h

**Comment by matrosovDev** [comment]
I mean outside pods in my custom classes it trows that issue

**Comment by Raikerian** [comment]
Cause it doesn't see QMChatSection class. Move it's import from QMChatSectionManager.m file to header one. Should be fixed.

**Comment by matrosovDev** [comment]
haha) you're right! thanks!!!!

**Comment by matrosovDev** [comment]
how to use encodedText also right now?

**Comment by Raikerian** [comment]
There is no needs to do it from now on. Our latest SDK encode/decode text automatically.

**Comment by matrosovDev** [comment]
can you suggest some links how to implement QBChatViewController, or there is only demo project that I can use as a reference? thank you!!!!

**Comment by Raikerian** [comment]
I didn't get your question, can you be more specific on what kind functionality you need in "demo propject"? If you are talking about all messages here is a commit for you: https://github.com/QuickBlox/QMChatViewController-ios/commit/d54044ad70f52d5dc0e0c05e6db0d2dc79b3136a
Patch: https://github.com/QuickBlox/QMChatViewController-ios/commit/d54044ad70f52d5dc0e0c05e6db0d2dc79b3136a.patch

**Comment by matrosovDev** [comment]
thanks for adding new fucntionality. I am actually trying to add quick blox messages in my view controller which is a child of QBChatViewController. In view did load method I add messages to section manager and seems it contains few messages but after collection view try to get that data it causes a crash

``` *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'request for number of items in section 0 when there are only 0 sections in the collection view'```

with stack:


```0   CoreFoundation                      0x07a1e494 __exceptionPreprocess + 180
	1   libobjc.A.dylib                     0x0744ce02 objc_exception_throw + 50
	2   CoreFoundation                      0x07a1e32a +[NSException raise:format:arguments:] + 138
	3   Foundation                          0x039d5322 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 118
	4   UIKit                               0x0507f828 -[UICollectionViewData numberOfItemsInSection:] + 242
	5   UIKit                               0x050275a4 -[UICollectionView numberOfItemsInSection:] + 70
	6   IRIS                                0x0042f09b _TFC4IRIS21IRSChatViewControllerP33_AA360469D96510CFC0F2FC3A5EE28D7B10reloadDatafGSqFT_T__T_ + 2027
	7   IRIS                                0x0042dda1 _TFC4IRIS21IRSChatViewController14viewWillAppearfSbT_ + 641
	8   IRIS                                0x0042ddff _TToFC4IRIS21IRSChatViewController14viewWillAppearfSbT_ + 63
	9   IRIS                                0x00b54785 _logos_method$VCModCore$__ABT$viewWillAppear$ + 113
	10  UIKit                               0x048645fb -[UIViewController _setViewAppearState:isAnimating:] + 659
	11  UIKit                               0x04864aa3 __52-[UIViewController _setViewAppearState:isAnimating:]_block_invoke + 191
	12  CoreFoundation                      0x079484c9 __53-[__NSArrayI enumerateObjectsWithOptions:usingBlock:]_block_invoke + 73
	13  CoreFoundation                      0x07948362 -[__NSArrayI enumerateObjectsWithOptions:usingBlock:] + 162
	14  CoreFoundation                      0x07932f95 -[NSArray enumerateObjectsUsingBlock:] + 53
	15  UIKit                               0x04864853 -[UIViewController _setViewAppearState:isAnimating:] + 1259
	16  UIKit                               0x04864ceb -[UIViewController __viewWillAppear:] + 147
	17  UIKit                               0x04887e45 -[UIViewController(UIContainerViewControllerProtectedMethods) beginAppearanceTransition:animated:] + 202
	18  UIKit                               0x0489a258 -[UINavigationController _startCustomTransition:] + 1389
	19  UIKit                               0x048ac02d -[UINavigationController _startDeferredTransitionIfNeeded:] + 803
	20  UIKit                               0x048ad39e -[UINavigationController __viewWillLayoutSubviews] + 68
	21  UIKit                               0x04a924b7 -[UILayoutContainerView layoutSubviews] + 252
	22  UIKit                               0x0475e3d4 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 810
	23  libobjc.A.dylib                     0x07461059 -[NSObject performSelector:withObject:] + 70
	24  QuartzCore                          0x0441a096 -[CALayer layoutSublayers] + 144
	25  QuartzCore                          0x0440d8b6 _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 388
	26  QuartzCore                          0x0440d71a _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE + 26
	27  QuartzCore                          0x043ffee7 _ZN2CA7Context18commit_transactionEPNS_11TransactionE + 317
	28  QuartzCore                          0x04434847 _ZN2CA11Transaction6commitEv + 561
	29  QuartzCore                          0x04435108 _ZN2CA11Transaction17observer_callbackEP19__CFRunLoopObservermPv + 92
	30  CoreFoundation                      0x0793075e __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 30
	31  CoreFoundation                      0x079306be __CFRunLoopDoObservers + 398
	32  CoreFoundation                      0x0792603c __CFRunLoopRun + 1340
	33  CoreFoundation                      0x07925846 CFRunLoopRunSpecific + 470
	34  CoreFoundation                      0x0792565b CFRunLoopRunInMode + 123
	35  GraphicsServices                    0x09d1b664 GSEventRunModal + 192
	36  GraphicsServices                    0x09d1b4a1 GSEventRun + 104
	37  UIKit                               0x0468deb9 UIApplicationMain + 160
	38  IRIS                                0x0035c261 main + 145
	39  libdyld.dylib                       0x09416a25 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**Comment by Raikerian** [comment]
Are you able to reproduce this in our samples? Also add exception breakpoint in order to see the exact line where the crash is occurred.

**Comment by Raikerian** [comment]
If you are still having any other troubles, feel free to create a separate issue.
