### ISSUE TITLE
Recording of both soundtracks

### ISSUE THREAD

**Issue by pzoechner** [QuickBlox/quickblox-ios-sdk#41]
Hi, I'm looking for a way to record one user's camera as well as both user's soundtracks!
Up to now all my tests merging the tracks failed. (I did some tests with the sample app.)

Has anyone accomplished this yet? Please let me know.

**Comment by pzoechner** [comment]
Yes, I did! But it didn't record both of my audio tracks.

**Comment by AndreyMoskvin** [comment]
Old videochat is no longer supported. We have this feature in QuickBlox WebRTC SDK.
