### ISSUE TITLE
Question about didDeleteChatDialogWithIDFromMemoryStorage when deleting dialog

### ISSUE THREAD

**Issue by coredream** [QuickBlox/quickblox-ios-sdk#410]
Hello,

I am currently implementing didDeleteChatDialogWithIDFromMemoryStorage, but I noticed that this doesn't fire when deleting a chat dialog from the Quickblox admin, or via QB.chat.dialog.delete (javascript API) from my backend server.

I can see this message getting logged:

`2016-04-26 08:58:53.155 TestApp[72174:24928164] [ChatService] Presence RCV: <presence xmlns="jabber:client" to="8511344-31608@chat.quickblox.com/0760612B-A660-470D-BD55-2844833A1D74" type="unavailable" from="31608_570e6132a28f9a01d5000075@muc.chat.quickblox.com/8511344"><x xmlns="http://jabber.org/protocol/muc#user"><item affiliation="none" nick="8511344" jid="8511344-31608@chat.quickblox.com/0760612B-A660-470D-BD55-2844833A1D74" role="none"/><status code="110"/><destroy jid="31608_570e6132a28f9a01d5000075@muc.chat.quickblox.com"><reason/></destroy></x></presence>
`

But nothing happens after that.  Is there any way to receive notification of this event in your iOS SDK?

**Comment by Raikerian** [comment]
Hi,

QMServices memory storage delegates are only getting called when you are deleting dialog FROM memory storage using QMServices methods. It has nothing to do with admin panel or any other sources. However you can understand that dialog was deleted when trying to join it (if it is a group dialog). We have such functionality in QMChatService, join error will have a specific code: https://github.com/QuickBlox/q-municate-services-ios/blob/master/QMChatService/QMChatService/QMChatService.m#L551
