### ISSUE TITLE
Audio not available through speakers in Video calling.

### ISSUE THREAD

**Issue by DagarAmit** [QuickBlox/quickblox-ios-sdk#415]
Able to hear audio through Headset clearly but as i unplug them audio is routed to earpiece in iPhone,(in iPad its working great) ,but i want audio on speakers and i facing this issue in latest update of quickblox framework only in iPhone.

  QBRTCSoundRouter.instance().currentSoundRoute = QBRTCSoundRoute.Speaker not work in swift
and i am using quickblox in SWIFT.
Please find this issue ASAP.

**Comment by Raikerian** [comment]
Hi @DagarAmit 

Are you sure that you are calling initialize of QBRTCSoundRoute before call start and deinitializing it after call ends?
If yes, can you please provide us test project with this issue being reproducible, so we can take a closer look on it.

**Comment by DagarAmit** [comment]
override func viewDidLoad() {
        super.viewDidLoad()
        self.view.endEditing(true)
        hideSideMenuView()
        QBRTCClient.instance().addDelegate(self)
        QBRTCClient .initializeRTC()
        QBRTCSoundRouter.instance().initialize()
       QBRTCSoundRouter.instance().setCurrentSoundRoute(QBRTCSoundRoute.Speaker)
  
        cameraCapture = QBRTCCameraCapture()
        let videoFormat = QBRTCVideoFormat()
        
        
        videoFormat.frameRate = 30
        videoFormat.pixelFormat = QBRTCPixelFormat.Format420f
        videoFormat.width = 100;
        videoFormat.height = 100;
        
        //MARK:-  QBRTCCameraCapture class used to capture frames using AVFoundation APIs
        
        self.cameraCapture = QBRTCCameraCapture.init(videoFormat: videoFormat, position: AVCaptureDevicePosition.Front)
        self.cameraCapture.previewLayer.frame = self.localVideoView.bounds
        self.cameraCapture.startSession()
        self.localVideoView.layer.insertSublayer(self.cameraCapture.previewLayer, atIndex: 0)
        
        self.imageViewHidden.hidden = false
        self.imageViwLocalHidden.hidden = false
        
    }
    
 //MARK:-  CALLED WHEN END UP BY OPPONENT
    func sessionDidClose(session: QBRTCSession!) {
        
        print("CALL VIEW  DID CLSE   \(isInComming)")
        updateMeetingLogs()
        print(self.timerTitle)
        totalTime = timeFormatted(Int(timeDuration))
        
        if let currentsessions = myNewCurrentSession{
            
            if (session == currentsessions) {
                
                myNewCurrentSession = nil
                QBRTCSoundRouter.instance().deinitialize()
                QBRTCClient.instance().removeDelegate(self)
                
                isConnected = true
                if(dialogTimer != nil){
                    
                    dialogTimer.invalidate()
                    
                    dialogTimer = nil
                    QMSoundManager.instance().stopAllSounds()
                }
                
                if(newbeepTimer != nil){
                    
                    newbeepTimer.invalidate()
                    newbeepTimer = nil
                    
                }
                if(isConnectedToUser){
                    
                    myNewCallTimer.invalidate()
                      timeDuration = 0.0
                    myNewCallTimer = nil
                    
                    
                }
                if(myNewCallTimer != nil){
                    timeDuration = 0.0
                    myNewCallTimer.invalidate()
                    myNewCallTimer = nil
                }
                
                
                //    self.timerTitle = "End - \(self.stringWithTimeDuration(self.timeDuration))"
                //  print("End call>>.   \(self.timerTitle)")
                
                
                self.navigationController?.popViewControllerAnimated(true)
                // self.dismissViewControllerAnimated(true, completion: nil)
            }
        
        }
    }

**Comment by Raikerian** [comment]
@DagarAmit were you able to fix it? If not can you provide some more code snippets and logs on this?

**Comment by Raikerian** [comment]
If you are still experiencing this issue, feel free to open it. If you are having any other troubles, let us know by creating a separate one.

**Comment by Ajayiosdeveloper** [comment]
Hello!
i am having problem with the audio in voice/video call.In both when call is accepted i am not able to hear any voice at both ends.Could you please help me on this.

**Comment by DhananjayAwasthisyscraft** [comment]
I am also using pod 'Quickblox-WebRTC', '~> 2.6' for video calling in ios swift and xcode 8.3.2. I am facing two problem the first one is, during video call volume is too slow an i am using this code
QBRTCAudioSession.instance().initialize()
QBRTCAudioSession.instance().currentAudioDevice = QBRTCAudioDevice.speaker
the second one is that, during video calling video quality is poor and video is stretched also, for prevent to stretching i am using this line of code remoteView.videoGravity = AVLayerVideoGravityResizeAspect.

**Comment by Raikerian** [comment]
Please create your own issues @Ajayiosdeveloper @DhananjayAwasthisyscraft as this one is not related to yours.
