### ISSUE TITLE
chatRoomDidReceiveMessage is not calling

### ISSUE THREAD

**Issue by sanderus2311** [QuickBlox/quickblox-ios-sdk#416]
Hello! 

Swift 2, iOS 9.0, QB v. 2.7.2

My method chatRoomDidReceiveMessage is not calling. I tried a lot of things but still not working. Every method is called, also self.joinChat() and it's seems to works but I can't send or receive any message but I'm getting push's. What should I do? Is it something wrong with my implementation?

http://pastebin.com/yPdTAqk1

**Comment by Raikerian** [comment]
Hi,

In order to send and receive messages from group chat dialog you need to join them first. See http://quickblox.com/developers/SimpleSample-chat_users-ios#Chat_in_group_dialog

**Comment by sanderus2311** [comment]
Yes, I joined. Line 34 (called in 11 and 16).

**Comment by Raikerian** [comment]
> also self.joinChat() and it's seems to works but I can't send or receive any message but I'm getting push's. What should I do? Is it something wrong with my implementation?

Please attach full logs from the app start till join till message sending error.

**Comment by sanderus2311** [comment]
Well, there is no message sending error. I'm using single and group chat. Single - works fine, there problem is with group. Sending message works because I get push's on second and third (Android) devices but "chatRoomDidReceiveMessage" is not calling. The flow is simple:

1. Login (connectWithUser) and set QBChat delegate to self
2. Check if dialog exist 
2a. If not - create new one
3. Join group chat
4. Fetch history 

No error while this process.

**Comment by Raikerian** [comment]
You have mentioned:

> also self.joinChat() and it's seems to works 

This does mean that 'chatRoomDidReceiveMessage' is called when you have joined. Therefore I cannot understand what the exact problem you have.

Lets start from scratch:
1. When does 'chatRoomDidReceiveMessage' not get called? Note, that its only should work when you are joined to a specific dialog.
2. When are you not able to send messages in group chat? Note, that you have to join group dialog first in order to send messages.

You are able to receive pushes from group dialog. But you will not be able to perform **any** operation with group chat dialog without being joined to it.

**Comment by sanderus2311** [comment]
1. When someoone send me message and I'm logged in and I joined to specific dialog. 

2. I'm almost sure that I'm joined dialog, because I can send new messages.

**Comment by Raikerian** [comment]
In order to check whether you are joined to group dialog call isJoined property.

For case 1, I need full logs:

>  from the app start till join till callbacks never get called till message sending success

**Comment by sanderus2311** [comment]
CHAT SERVICE::: Registered settings
CHAT SERVICE::: User credentials downloaded
CHAT SERVICE::: Connected with user 
  [QBUUser]:
  ID:12003877
  created at:2016-04-24 21:55:26 +0000
  updated at:2016-04-28 03:55:33 +0000
  externalUserID:0
  blobID:0
  facebookID:966934013389260
  twitterID:(null)
  twitterDigitsID:(null)
  full name:Dawid Koncewicz
  email:(null)
  login:e5c3b334-853c-49a2-9753-96a61b5e1019
  phone:(null)
  tags:(null)
  lastRequestAt:2016-04-28 13:33:54 +0000
  customData:(null)
  website:(null)
   password:****
CHAT SERVICE::: Chat dialog created 
    ID:369@jabber.org                      
    Created At:(null)                      
    Updated At:(null)                      
    Room JID:38727_369jabber.org@muc.chat.quickblox.com                      
    name:369@jabber.org                      
    photo:(null)                      
    type:2                      
    lastMessage:(null)                      
    lastMessageDate:(null)                      
    occupantIDs:(
    12003877,
    12006544
)                      
    userID:0                      
    data:(null)                      
    unreadMessagesCount:0                      
    lastMessageUserID:0
CHAT SERVICE::: Chat joined dialog with id 572211eaa28f9a3d1700000b

**Comment by Raikerian** [comment]
Please enable full logs: https://gist.github.com/Raikerian/ea57ae2da2c4ed8c56c5
And add them to gist.

**Comment by sanderus2311** [comment]
https://gist.github.com/sanderus2311/cef6351fd52d557be3ccc73dec38bf8b

**Comment by Raikerian** [comment]
Everything is fine in logs. You are successfully joined group dialog.
I cannot see any problems with message receiving here.

Can you show a code snippet of how are you sending message?

Also what is a point of creating dialog ID like this:
```swift
        let dialogId = "\(self.event.eventId)@jabber.org"
        let chatDialog = QBChatDialog(dialogID: dialogId, type: .Group)
```

If you need to create dialog using QBRequest pass nil as dialogID.

**Comment by sanderus2311** [comment]
https://gist.github.com/sanderus2311/7d457f028dbd0561f580962517f0227f

**Comment by Raikerian** [comment]
Seems strange. Are you able to reproduce this in our samples with your endpoints?

**Comment by VitaliyGuru** [comment]
Hi @sanderus2311 , Any updates on this?

**Comment by Raikerian** [comment]
If you are still having any other troubles, feel free to create a separate issue.
