### ISSUE TITLE
Another "You are not joined to the dialog" error

### ISSUE THREAD

**Issue by coredream** [QuickBlox/quickblox-ios-sdk#417]
*Help avoid duplicate issue reports, check [existing issues](https://github.com/QuickBlox/quickblox-ios-sdk/issues)*
 
**Environment details**
*iOS version, Quickblox iOS SDK version, QuickbloxWebRTC SDK version (optional)*
iOS 9.3.1
'QuickBlox', '2.7.2'
'QMServices', '0.4'

**Did this work before?**
Yes

**Expected behavior**
User can send messages.

**Actual behavior**
User can login, but once attempting to send a message, receive error "You are not joined to the dialog".  
Similar to previous issue: https://github.com/QuickBlox/quickblox-ios-sdk/issues/330.

This code is not completing:
`[dialog joinWithCompletionBlock:^(NSError *error) {`

Same error now occurring with other users that are members of the same chat dialogs as the original user.

**Logs**
*Attach full logs that will describe your problem (please, use github [gist](https://gist.github.com/))*

**Steps to reproduce the behavior**
Application ID: 31608
User ID: 8511344

**Any others comments?**
 No code changes were made, and this was working before.  Only thing I can think of is last night I was testing a lot of logging out/logging in, backgrounding/foregrounding, disabling/enabling wi-fi, etc.

**Comment by Raikerian** [comment]
Hi @coredream 

Thank you for reporting the issue. We will take a closer look on our server in a near days.

**Comment by Pro100Andrey** [comment]
Hi @coredream please provide full xmpp logs of join request

**Comment by coredream** [comment]
Hi @Pro100Andrey.  Sometime on Monday, May 2 this error stopped occurring for this user (also for the other users that are in the same group dialogs).  Unfortunately, I did not save the logs when the error was occurring.

I remember from #330, "It was a temporary shared server-side glitch, not SDK related".  Were any changes made on the server-side related to my account in the last couple days?

This is a mysterious problem for me since no code was changed, and I was able to repro this with your sample app previously.  And there appears to be no workaround except to report it here.

**Comment by Raikerian** [comment]
@coredream 

no server related fixes were implemented. Seems strange. Capture all logs next time you will be able to catch it, it will be very helpful for us.

**Comment by coredream** [comment]
@Raikerian Ok, thanks.  You can close this, and I will open a separate issue with logs if this happens again.  Just another question:  is there any sort of "lock out the user" logic on your backend for a certain period of time?  Perhaps due to rate limit exceeded, etc.

**Comment by coredream** [comment]
@Raikerian Since this is still open, here is some more information.  There appears to be one way to reproduce this reliably with your sample chat app (but using my account credentials):

1.  Login and Enter a group chat dialog
2.  Minimize app
3.  Foreground app
4.  Quickly minimize app again (while "Connecting to chat" HUD is visible).
5.  Foreground app
6.  Try to send message

So it seems like there is some timing issue with disconnectWithCompletionBlock and connectWithCompletionBlock since those are called within the AppDelegate method.  The user is stuck in this state, but it does seem to be repaired after logging out and logging back in.  This situation seems possible if the user is on a slow network, and due to the time it takes to reconnect to QuickBlox service after 

I've attached a log here: https://gist.github.com/coredream/5f4026ad9aa24e00b708b04bc0c392aa

**Comment by Raikerian** [comment]
@coredream we make some performance improvements for our join/leave methods, so it should work faster in a next release. Right now you can check our development branch using your credentials in sample chat and see if the issue is still reproducible.

**Comment by coredream** [comment]
Thanks @Raikerian.  I have tried several times on the development branch, and have not been able to reproduce it.
