### ISSUE TITLE
Fullscreen mode not working for remote video view

### ISSUE THREAD

**Issue by astanton** [QuickBlox/quickblox-ios-sdk#418]
In the sample chat docs, it says to set the content mode of `QBRTCRemoteVideoView` to either `UIViewContentMode.ScaleAspectFill` or `UIViewContentMode.ScaleAspectFit` to use full screen.

I've tried both and both times, the actual video has black bars at the top and bottom of the screen.  What iI really want is the ScaleAspectFill so that it fills out the full screen.  When stepping through, it appears that the actual frame of the view is correct and starts at 0,0, however, the full screen video isn't showing.

Is this a bug or is there a different way to do this?  I'm on QuickBlox 2.7.1 from Cocoapods and this is in Swift.

**Comment by astanton** [comment]
Okay after doing some digging into the sub views and stuff, I figured out a way to do it but just want to know if this is the correct way to do it or not.

`let layer = remoteVideoView.subviews[0].layer as! AVSampleBufferDisplayLayer
layer.videoGravity = AVLayerVideoGravityResizeAspectFill
`

Is there a cleaner way to do it or is that the way it should be done?

**Comment by Pro100Andrey** [comment]
@astanton We provided api for setting layer.videoGravity in new version of SDK.
For now please use the following category(as for now it is an internal API) : https://github.com/QuickBlox/quickblox-ios-sdk/issues/252 or your code:
```swift 
let layer = remoteVideoView.subviews[0].layer as! AVSampleBufferDisplayLayer
layer.videoGravity = AVLayerVideoGravityResizeAspectFill
```

**Comment by Raikerian** [comment]
If you are still having any other troubles, feel free to create a separate issue.
