### ISSUE TITLE
Chat messages are not being saved.

### ISSUE THREAD

**Issue by mitchellporter** [QuickBlox/quickblox-ios-sdk#42]
Five days ago my chat messages were saving just fine. Now they will not save. The logs indicate that the message has successfully been sent, but they no longer show up in the Quickblox admin panel. The dialog is successfully created, but the messages are never saved or show up in the Quickblox database.

It looks like other developers are having this issue as well. This StackOverflow question was asked 2 days ago: https://stackoverflow.com/questions/27678809/quickblox-messages-not-saved-group-dialog-creation-timeout

Also, I visited http://status.quickblox.com/ and it looks like "Private chat" and "Group chat" both have a red status of "failed."

**Comment by Sunfocus** [comment]
I am also having same problem. Messages are being delivered but they are saved on admin panel.

**Comment by soulfly** [comment]
Can you send an example of messages that have the issue

**Comment by Sunfocus** [comment]
Hello Soulfly,

   ID: 5638580fb9666332730041a8            
 senderID: 6509351            
 recipientID: 6509463            
 dateSent: 2015-11-03 06:45:28 +0000            
 text: hello            
 customParameters: (null)            
 attachments: (null)            
 delayed: 0            
 senderNick: (null)            
 dialogID: 56384758a0eb47e28800222c            
 read: 0            
 readIDs: (null)            
 deliveredIDs: (null)            
 markable: 1            
 createdAt: (null)            
 updatedAt: (null)

here is my message i am sending to other

**Comment by Sunfocus** [comment]
Hello Soulfly,

  Code snippets:
  QBChatMessage *message = [QBChatMessage message];
    QBUUser *currentUser = [QBSession currentSession].currentUser;
    
    if (self.currentDialog.type == QBChatDialogTypePrivate) {
        message.recipientID = self.currentDialog.recipientID;
        message.markable = YES;
    }
    message.text = text;
    message.senderID = currentUser.ID;
    message.dialogID = self.currentDialog.ID;
    message.dateSent=date;
  
    
//    self.currentDialog.lastMessageText = message.;
//    self.currentDialog.lastMessageDate = message.dateSent;
    
    self.currentDialog.lastMessageText = message.text;
    self.currentDialog.lastMessageDate = message.dateSent;
    self.currentDialog.updatedAt = message.dateSent;
    
    BOOL sent =  [self.currentDialog sendMessage:message sentBlock:^(NSError *error) {
       NSLog(@"Error: %@", error.localizedDescription);
        [self.items addObject:message];
         [self.collectionView reloadData];
        
    }];
    
    NSLog(@"Message sent: %i", sent);

**Comment by Sunfocus** [comment]
And one more thing here is XML Version:
Message RCV: <message xmlns="jabber:client" type="chat" to="6509351-30316@chat.quickblox.com" id="56385824816942c1010041a8" from="6509463-30316@chat.quickblox.com/626C9515-08A8-43A8-8F12-BC35BD849526"><received xmlns="urn:xmpp:chat-markers:0" id="5638580fb9666332730041a8"/><extraParams xmlns="jabber:client"><dialog_id/></extraParams></message>

**Comment by soulfly** [comment]
Can you add the 'save_to_history' to customParameters

for example

     NSMutableDictionary *params = [NSMutableDictionary dictionary];
     params[@"save_to_history"] = @YES;
     [message setCustomParameters:params];

**Comment by baafuor** [comment]
Hey was anyone able to come up with a solution for this issue?
