### ISSUE TITLE
trouble reconnecting to Chat

### ISSUE THREAD

**Issue by kevb10** [QuickBlox/quickblox-ios-sdk#422]
*Help avoid duplicate issue reports, check [existing issues](https://github.com/QuickBlox/quickblox-ios-sdk/issues)*
 
**Environment details**
*iOS version, Quickblox iOS SDK version, QuickbloxWebRTC SDK version (optional)*
iOS 9.3
QuickBlox (2.6.6)
QMCVDevelopment (0.3.4)

**Did this work before?**
No

**Expected behavior**
When app becomes active, it should reconnect successfully

**Actual behavior**
Stuck at "Connecting to Chat"
<img width="187" alt="screen shot 2016-05-01 at 12 28 23 pm" src="https://cloud.githubusercontent.com/assets/7396751/14943202/46231bc8-0f98-11e6-9836-4fe576fe6fee.png">

**Logs**
*Attach full logs that will describe your problem (please, use github [gist](https://gist.github.com/))*
https://gist.github.com/kevb10/effef0c0db1e241b8c646c006bf9fec4

**Steps to reproduce the behavior**
After regular successful login, chill for a few sec then hit home button so that app is in background and disconnects from chat, go to other apps, then come back, the app will try to reconnect to chat but will get stuck as "Connecting to Chat"

**Any others comments?**
 I'm pretty sure these delegates are what's called
```
- (void)applicationDidEnterBackground:(UIApplication *)application
{
    // Use this method to release shared resources, save user data, invalidate timers, and store enough application state information to restore your application to its current state in case it is terminated later.
    // If your application supports background execution, this method is called instead of applicationWillTerminate: when the user quits.
    
    // Logout from chat
    //
    [ServicesManager.instance.chatService disconnectWithCompletionBlock:nil];
}

- (void)applicationWillEnterForeground:(UIApplication *)application
{
    // Called as part of the transition from the background to the inactive state; here you can undo many of the changes made on entering the background.
    
    // Login to QuickBlox Chat
    //
    [ServicesManager.instance.chatService connectWithCompletionBlock:nil];
}
```

**Comment by Pro100Andrey** [comment]
Hi @kevb10, please update to latest version SDK v2.7.2 & QMServices v0.4

**Comment by kevb10** [comment]
Okay so I put the right versions in my podfile file then,
When I try to update using pod update, now I get this
https://gist.github.com/kevb10/7be6e45e8f7dda1197941d519b8a8c93

**Comment by kevb10** [comment]
Update. Issue persists but this time you can still interact with the app with the prorgressHUD present. It seems to be able to reconnect ok if you leave the app while you're in Chat/DialogViewController, any other ViewController, it will pretty much time out...My delegates in AppDelegate are implemented.

**Comment by Raikerian** [comment]
Hey @kevb10 

Please provide us **full **logs from the app start till the issue occurs. Thanks.

**Comment by kevb10** [comment]
https://gist.github.com/kevb10/b4d9968667b2e9d9b24671e60687275b

**Comment by kevb10** [comment]
When it's hanging at "Connecting to Chat.." and I navigate to ChatViewController it will finish the process but if I just stay there, it will just stay at "Connecting to Chat.."

**Comment by Raikerian** [comment]
Have you modified our samples somehow and are you able to reproduce this on them?

**Comment by Raikerian** [comment]
We haven't received any updates from you.
If you are still having any other troubles, feel free to create a separate issue.
