### ISSUE TITLE
Unable to create the ChatDialog and Send Messages

### ISSUE THREAD

**Issue by ajay2c9** [QuickBlox/quickblox-ios-sdk#423]
Hi i am unable to create and send  the messages. when creating the ChatDialog. few times dialog is created but unable to send messages . Below is the Log.

[QBCore] Request URL:https://api.quickblox.com/chat/Dialog.json
QBCore] Request method: POST
[QBCore] Request parameters:{
    name = "LACK,ADAMSTELLENT";
    "occupants_ids" = 12079806;
    type = 2;
}

[QBCore] Request headers: {
    "Content-Type" = "application/json";
    "QB-OS" = "iOS 9.2";
    "QB-SDK" = "iOS 2.7";
    "QB-Token" = 745e5b6e5453c466ae433bdc860de0c3c928f3af;
    "QuickBlox-REST-API-Version" = "0.1.1";
}

 [QBCore] Response headers: {
    "Access-Control-Allow-Origin" = "*";
    "Cache-Control" = "max-age=0, private, must-revalidate";
    Connection = "keep-alive";
    "Content-Length" = 389;
    "Content-Type" = "application/json; charset=utf-8";
    Date = "Mon, 02 May 2016 09:18:28 GMT";
    Etag = "\"f2926fbbfacff74092ff84b7b913449d\"";
    "QB-Token-ExpirationDate" = "2016-05-02 11:17:44 UTC";
    "QuickBlox-REST-API-Version" = "0.1.1";
    Server = "nginx/1.8.1";
    Status = "201 Created";
    "Strict-Transport-Security" = "max-age=15768000;";
    "X-Rack-Cache" = "invalidate, pass";
    "X-Request-Id" = 662975ef46ad2a3bb98f222a04b6e1f5;
    "X-Runtime" = "0.155135";
    "X-UA-Compatible" = "IE=Edge,chrome=1";
}

 [QBCore] Response object: {
    "_id" = 57271b64a0eb476afb000006;
    "created_at" = "2016-05-02T09:18:28Z";
    "last_message" = "<null>";
    "last_message_date_sent" = "<null>";
    "last_message_user_id" = "<null>";
    name = "LACK,ADAMSTELLENT";
    "occupants_ids" =     (
        12079806,
        12080382
    );
    photo = "<null>";
    type = 2;
    "unread_messages_count" = "<null>";
    "updated_at" = "2016-05-02T09:18:28Z";
    "user_id" = 12080382;
    "xmpp_room_jid" = "36508_57271b64a0eb476afb000006@muc.chat.quickblox.com";
}

 [ChatService] Presence SNT: <presence to="36508_57271b64a0eb476afb000006@muc.chat.quickblox.com/12080382"><x xmlns="http://jabber.org/protocol/muc"><history maxstanzas="0"/></x></presence>

[ChatService] StreamManagement: did request acknowledgment

[ChatService] StreamManagement: did receive acknowledgments for stanza ids count: 1

[ChatService] Presence SNT: <presence/>

[ChatService] Presence RCV: <presence xmlns="jabber:client" to="12080382-36508@chat.quickblox.com" from="12080382-36508@chat.quickblox.com/F43B6EF1-A466-41FC-B96E-902C754808F0"/>
[ChatService] Presence SNT: <presence/>
[ChatService] Presence RCV: <presence xmlns="jabber:client" to="12080382-36508@chat.quickblox.com" from="12080382-36508@chat.quickblox.com/F43B6EF1-A466-41FC-B96E-902C754808F0"/>

Please give suggestions.
Thank you

**Comment by ajay2c9** [comment]
I have another quickblox account The error in that is Like this.

 [QBCore] Request URL:https://api.quickblox.com/chat/Dialog.json
 [QBCore] Request method: POST
[QBCore] Request parameters:{
 name = "LACK,ADAMSTELLENT";
    "occupants_ids" = 7080932;
    type = 2;
}
 [QBCore] Request headers: {
    "Content-Type" = "application/json";
    "QB-OS" = "iOS 9.2";
    "QB-SDK" = "iOS 2.7";
    "QB-Token" = 7af80f8945a194e1087c75a02f3464a8d14288b3;
    "QuickBlox-REST-API-Version" = "0.1.1";
}
[QBCore] Request URL:https://api.quickblox.com/chat/Dialog.json
[QBCore] Request method: POST
[QBCore] Request parameters:{
    data =     {
        createdbyid = 7080996;
    };
    "occupants_ids" = 7080932;
    type = 2;
}
[QBCore] Request headers: {
    "Content-Type" = "application/json";
    "QB-OS" = "iOS 9.2";
    "QB-SDK" = "iOS 2.7";
    "QB-Token" = 7af80f8945a194e1087c75a02f3464a8d14288b3;
    "QuickBlox-REST-API-Version" = "0.1.1";
}
 [QBCore] Response headers: {
    "Access-Control-Allow-Origin" = "*";
    "Cache-Control" = "max-age=0, private, must-revalidate";
    Connection = "keep-alive";
    "Content-Length" = 386;
    "Content-Type" = "application/json; charset=utf-8";
    Date = "Mon, 02 May 2016 09:31:26 GMT";
    Etag = "\"0ace56f371eb84f1eb1195fc56a49a28\"";
    "QB-Token-ExpirationDate" = "2016-05-02 11:30:55 UTC";
    "QuickBlox-REST-API-Version" = "0.1.1";
    Server = "nginx/1.8.1";
    Status = "201 Created";
    "Strict-Transport-Security" = "max-age=15768000;";
    "X-Rack-Cache" = "invalidate, pass";
    "X-Request-Id" = 3398f240af9f1bf0b21e4c54621505bd;
    "X-Runtime" = "0.041471";
    "X-UA-Compatible" = "IE=Edge,chrome=1";
}
 [QBCore] Response object: {
    "_id" = 57271e6ea28f9a9a1f0000e0;
    "created_at" = "2016-05-02T09:31:26Z";
    "last_message" = "<null>";
    "last_message_date_sent" = "<null>";
    "last_message_user_id" = "<null>";
    name = "LACK,ADAMSTELLENT";
    "occupants_ids" =     (
        7080932,
        7080996
    );
    photo = "<null>";
    type = 2;
    "unread_messages_count" = "<null>";
    "updated_at" = "2016-05-02T09:31:26Z";
    "user_id" = 7080996;
    "xmpp_room_jid" = "26764_57271e6ea28f9a9a1f0000e0@muc.chat.quickblox.com";
}
 [QBCore] Response error: Error Domain=com.alamofire.error.serialization.response Code=-1011 "Request failed: client error (422)" UserInfo={com.alamofire.serialization.response.error.response=<NSHTTPURLResponse: 0x7f7fa55bdff0> { URL: https://api.quickblox.com/chat/Dialog.json } { status code: 422, headers {
    "Access-Control-Allow-Origin" = "*";
    "Cache-Control" = "no-cache";
    Connection = "keep-alive";
    "Content-Length" = 27;
    "Content-Type" = "application/json; charset=utf-8";
    Date = "Mon, 02 May 2016 09:31:26 GMT";
    "QB-Token-ExpirationDate" = "2016-05-02 11:30:55 UTC";
    "QuickBlox-REST-API-Version" = "0.1.1";
    Server = "nginx/1.8.1";
    Status = "422 Unprocessable Entity";
    "X-Rack-Cache" = "invalidate, pass";
    "X-Request-Id" = 0ff4bf64e4219668f9122cd816985599;
    "X-Runtime" = "0.075596";
    "X-UA-Compatible" = "IE=Edge,chrome=1";
} }, NSErrorFailingURLKey=https://api.quickblox.com/chat/Dialog.json, com.alamofire.serialization.response.error.data=<7b226e61 6d65223a 5b226361 6e277420 62652062 6c616e6b 225d7d>, NSLocalizedDescription=Request failed: client error (422)}
 [ChatService] Presence SNT: <presence to="26764_57271e6ea28f9a9a1f0000e0@muc.chat.quickblox.com/7080996"><x xmlns="http://jabber.org/protocol/muc"><history maxstanzas="0"/></x></presence>
 [ChatService] StreamManagement: did request acknowledgment
 [ChatService] StreamManagement: did receive acknowledgments for stanza ids count: 1
 [ChatService] Presence SNT: <presence/>

Please give suggestions
Thank you

**Comment by Raikerian** [comment]
Hi,

Please print `[response.error reasons]` in error block of QBRequest.

**Comment by VitaliyGuru** [comment]
@ajay2c9 Any updates?

**Comment by ajay2c9** [comment]
Thank you. it is working fine now.
