### ISSUE TITLE
Question about getting user's presence

### ISSUE THREAD

**Issue by UtkuDalmaz** [QuickBlox/quickblox-ios-sdk#424]
In documentation i see this code to get user's last activity

Can someone help me to use it in swift?

QBUUser *user = ...;

NSInteger currentTimeInterval = [[NSDate date] timeIntervalSince1970];
NSInteger userLastRequestAtTimeInterval   = [[user lastRequestAt] timeIntervalSince1970];

// if user didn't do anything last 1 minute (60 seconds)    
if((currentTimeInterval - userLastRequestAtTimeInterval) > 60)
{ 
 // user is offline now
}
I am on chat dialog viewcontroller.

I get dialog id, recipientID etc etc

But how can i retrieve user's lastRequestAt field ?

QBUUser *user = ...;
What is this three dots? ... what should i pass in this?

**Comment by UtkuDalmaz** [comment]
Tried this but lastRequestAt is 0 always

QBRequest.userWithID(rid, successBlock: { (response : QBResponse, user: QBUUser?) -> Void in
                userlastrew = Int((user?.lastRequestAt?.timeIntervalSince1970)!)
                }, errorBlock: {(response: QBResponse) -> Void in
                    // Handle error
            })

**Comment by astanton** [comment]
Are you trying to get the current user's presence status or another user's presence status?

If you are trying to get another user's status, I know from another question I asked on here that in order to get another user's status you must be on their contact list.

**Comment by UtkuDalmaz** [comment]
I am just trying to get another user's lastRequestAt field
Can't i do it without contact list ?

**Comment by UtkuDalmaz** [comment]
QBRequest.userWithID(rid, successBlock: { (response : QBResponse, user: QBUUser?) -> Void in
userlastrew = Int((user?.lastRequestAt?.timeIntervalSince1970)!)
}, errorBlock: {(response: QBResponse) -> Void in
// Handle error
})

it is now working, thanks
