### ISSUE TITLE
QBRTCConfig.mediaStreamConfiguration().videoCodec = QBRTCVideoCodec.H264 not working

### ISSUE THREAD

**Issue by astanton** [QuickBlox/quickblox-ios-sdk#426]
I know that it isn't working correctly in v2.2 of the SDK, however I am using v2.1.1 (as told it should work fine) and it is not working for me.  I am setting it in multiple places and it is always showing VP8 in my stats report delegate method.

I am using 2.1.1 from cocoapods so I am not sure if that matters or not.

But is there something else that I have to do to get this working?

I thought maybe it was my custom video capture class but I tried with the default QBRTCCameraCapture class and I'm seeing the same behavior, that it's showing VP8 in the report.

**Comment by VitaliyGuru** [comment]
Hi @astanton , What device and iOS version do you use for testing?

**Comment by astanton** [comment]
I'm using an iPhone 5 with iOS 9.1 (I think 9.1, may be 9.0) on it, and iPhone 6 with iOS 8.2 on it.

**Comment by VitaliyGuru** [comment]
@astanton , Please reinstall WebRTC with cocoapods. There are fixes for this issue.

**Comment by astanton** [comment]
@VitaliyGuru do you mean reinstall v2.1.1 or to install v2.2?

I "reinstalled" v2.1.1 by removing it from the podfile, then doing `pod install`, then adding it back, and doing `pod install` again and that is not working.  It's still showing VP8.

I am not sure if there is another way to reinstall pods or not though.

**Comment by VitaliyGuru** [comment]
Could you please provide full logs from both devices.
Also please enable stats report and send us this information.
```
   // Enables Quickblox REST API calls debug console output
    [QBSettings setLogLevel:QBLogLevelDebug];
    
    // Enables detailed XMPP logging in console output
    [QBSettings enableXMPPLogging];
```
`[QBRTCConfig setStatsReportTimeInterval:1.f];` - method for enabling stats report.

In your controller you should adopt QBRTCClientDelegate and use [this delegate method](https://github.com/QuickBlox/quickblox-ios-sdk/blob/master/sample-videochat-webrtc/sample-videochat-webrtc/ViewControllers/CallViewController/CallViewController.m#L353-404).

Also can you set up a test project with this issue being reproducible and attach it here?

**Comment by astanton** [comment]
Sure I can try that later this evening.  Is there anyway that I can verify what version of the framework I'm using, even though the podfile says 2.1.1 ?

**Comment by VitaliyGuru** [comment]
@astanton  Also you can get this information from logs.

**Comment by astanton** [comment]
Is there anyway to make it so that system messages aren't outputted to the console with these settings?  I am constantly sending signals whether faces were detected or not and it's basically cluttering the logs big time so you'd have to wade through it to get all of the other info.

**Comment by astanton** [comment]
Okay I can reproduce this with the sample app.  I've created a project with the sample app, with the v2.1.1 webRTC framework in it.  I tried attaching it but it's too large with the Frameworks included in the zip file.  I've attached it without the frameworks in it, but just add the QB one that is in the main sample zip file, then the 2.1.1 webRTC one to the project.

[sample-videochat-webrtc.zip](https://github.com/QuickBlox/quickblox-ios-sdk/files/260495/sample-videochat-webrtc.zip)

I'm doing this between an iPhone 5 on iOS 9.1 and an iPhone 6 with iOS 8.2 on it.

I've attached the 2 logs as well.

[ip6log.txt](https://github.com/QuickBlox/quickblox-ios-sdk/files/260493/ip6log.txt)
[ip5log.txt](https://github.com/QuickBlox/quickblox-ios-sdk/files/260492/ip5log.txt)

As you can see it says VP8 with that as well.

**Comment by Pro100Andrey** [comment]
Hi @astanton,
please update code in `CallViewController.m`
```objective-c
    
    if (self.session.conferenceType == QBRTCConferenceTypeVideo) {
        
        Settings *settings = Settings.instance;
        self.cameraCapture = [[QBRTCCameraCapture alloc] initWithVideoFormat:settings.videoFormat
                                                                    position:settings.preferredCameraPostion];
        [self.cameraCapture startSession];
    }
    //Configure codec here:
    [QBRTCConfig mediaStreamConfiguration].videoCodec = QBRTCVideoCodecH264;
```

**Comment by Pro100Andrey** [comment]
Hi @astanton, from your ip5log:
**No rtpmap for H264** 
So, H264 working only in arm64 (5s+), we add arm32 in new SDK (2.2.3 in development now)

**Comment by astanton** [comment]
So when connecting an iPhone 6 with an iPhone 5, H264 will not work on the iPhone 6 even?

Also is there any ETA on when the 2.2.3 will be released?  I'm definitely noticing some performance issues on the iPhone 5 when doing video chat, but I also believe it has to do with the face detection that is happening real time.  I'm hoping the H264 will help out with this a little bit too.

**Comment by Raikerian** [comment]
Hi @astanton 

We are aware of most issues with 2.2 and are currently working on them. However there is no any fast ETA on this, some problems are complicated but we are managing to fix them.
Right now we are recommending you to use the most stable version that meets your requirements.

**Comment by shalem93** [comment]
H264 isn't working on 5S either, and VP8 is incredibly low quality compared to Apple's FaceTime, is this almost fixed???
