### ISSUE TITLE
RTL issue

### ISSUE THREAD

**Issue by ronasc** [QuickBlox/quickblox-ios-sdk#427]
self.topContentAdditionalInset = self.navigationController.navigationBar.frame.size.height + [UIApplication sharedApplication].statusBarFrame.size.height;

Doesn't show the update, navigationBar has height

**Comment by Raikerian** [comment]
Hi @ronasc 

Where in your code you are setting this property? It should be done in viewDidLoad or earlier.

**Comment by ronasc** [comment]
It's in ViewDidLoad

**Comment by ronasc** [comment]
![screen shot 2016-05-08 at 5 02 00 pm](https://cloud.githubusercontent.com/assets/16338222/15098179/b2a073bc-153e-11e6-809a-b13dd60ec442.png)

I need the collectionView to end below the navigation bar

**Comment by ronasc** [comment]
Thanks. I am also having an RTL issue.
In the attached photo you can see an outgoing message.
![screen shot 2016-05-08 at 5 36 50 pm](https://cloud.githubusercontent.com/assets/16338222/15098332/abcfa882-1543-11e6-84a0-7cb9ffbcd294.png)

**Comment by VitaliyGuru** [comment]
You can [set custom container insets](https://github.com/QuickBlox/quickblox-ios-sdk/blob/fc35140c98eaecc4250f753406bf0f8cdea48cad/sample-chat/Pods/QMCVDevelopment/QMChatViewController/Views/Cells/QMChatOutgoingCell/QMChatOutgoingCell.m#L13-L22) for outgoing cell in `QMChatOutgoingCell.m `

**Comment by Raikerian** [comment]
If you are still having any other troubles, feel free to create a separate issue.
