### ISSUE TITLE
Best way to upload user's profile pic and show that pic in other users contact list and show that profile pic as dialog pic of others just like whatsapp one to one chat ?

### ISSUE THREAD

**Issue by WillsAtIOS** [QuickBlox/quickblox-ios-sdk#428]
*Help avoid duplicate issue reports, check [existing issues](https://github.com/QuickBlox/quickblox-ios-sdk/issues)*
 
**Environment details**
*iOS version, Quickblox iOS SDK version, QuickbloxWebRTC SDK version (optional)*

**Did this work before?**
Hi I have some issues in uploading user's profile pic and getting that back and showing as dialogs profile pic (for private chat) so I have posted. I explained the requirement and problem in detail in stack over flow. There are the links 
**LINK 1 :** [http://stackoverflow.com/questions/37043763/how-to-upload-the-users-profile-pic-and-how-to-fetch-that-profile-pic-from-anoth/37048260?noredirect=1#comment61651930_37048260]
This I did. 
Now Problem is this
**LINK 2 :** [http://stackoverflow.com/questions/37066109/how-to-give-photo-to-dialog-from-users-blob-id/37066618?noredirect=1#comment61686034_37066618]

**Expected behavior**
 I want to upload an image of each user which should be visible to other users in users contact list screen. and also as in dialogs list screen.

**Actual behavior**
I can able to upload the image of user as shown in link 1. But I'm struck at showing image for other users as dialog image. Means : For user1 dialog image should be user2's profile pic. and For User2 dialog image should be user1's profile pic (Here the dialog id is same)

**Logs**
*Attach full logs that will describe your problem (please, use github [gist](https://gist.github.com/))*

**Steps to reproduce the behavior**

**Any others comments?**

**Comment by VitaliyGuru** [comment]
You shouldn't set dialog's photo, you can handle this situation by yourself.

Every dialog has `occupantIDs`. You can get image for dialog by getting opponent's image.

You can get occupant's ID by excluding your ID from `occupantIDs`.
With occupantID you can get instance of `QBUUser` class, which has property `blobID`. With `blobID` you can get image and set this image for dialog's UIImageView for example.  
**Please notice**, that you needn't update `QBChatDialog's` `photo`.

As for real time updates (e.g. leaving from dialog, adding occupants, changing user's avatar image), for each of this situations you can send SystemMessage with custom parameters. Of course, you should handle this messages by yourself. this solution is for online users.

For offline users you should load users with changes from REST.

**Comment by WillsAtIOS** [comment]
Yeah I did the steps as you said to show avatar for dialog. Its working fine. 

But I didn't understand this part clearly. Could you please provide those methods how to execute and where to execute ? If you don't mind.

********As for real time updates (e.g. leaving from dialog, adding occupants, changing user's avatar image), for each of these situations you can send SystemMessage with custom parameters. Of course, you should handle these messages by yourself. This solution is for online users.

For offline users you should load users with changes from REST. *******

**Comment by VitaliyGuru** [comment]
I you want to immediately update dialog's photo when user A changes his avatar you should:

1. UserA: Send system message with custom parameters. (For example "new_photo_id" : "photo_id")
2. UserB: Handle this message and update dialog's photo if needed.

For more further explanation and examples please refer to [our services](https://github.com/QuickBlox/q-municate-services-ios#qmchatservice).

There you can find methods for sending system messages with additional handling.

**Comment by WillsAtIOS** [comment]
Thank you for your reply. I'm really thankful to your answers.

**Comment by WillsAtIOS** [comment]
I really liked this quick blox very much. And I want to master this quick blox application and QMservices. Could you suggest me the best way to master this. Now I'm going through the documentation that is provided at by the Quickblox IOS SDK http://quickblox.com/developers/IOS

**Comment by Raikerian** [comment]
Hi @WillsAtIOS 

Of course the best way is to follow documentation at first. But sometimes its hard without any real examples. For that we have our samples in current repository and our [Q-municate](https://github.com/QuickBlox/q-municate-ios) (more complicated) project, which contains contacts and profile management. Right now we are developing version 2.0 of it and it will be available soon, for now you can check the one that is in master branch (stable one).

**Comment by Raikerian** [comment]
If you are still having any other troubles, feel free to create a separate issue.
