### ISSUE TITLE
QBSession startSessionWithDetails:updateSessionBlock: never runs block

### ISSUE THREAD

**Issue by iurichiba** [QuickBlox/quickblox-ios-sdk#429]
Hi,

I'm trying to implement QB, but I'm running into a newbie problem, here.
We're managing QB's session server-side, but when I try to instantiate the the session using startSessionWithDetails:updateSessionBlock: as specified in http://quickblox.com/developers/IOS#Initialize_framework, the updateSessionBlock: block never runs.

If there're any details you need that I didn't provide, please ask and I'll reply ASAP.

Hope you guys can help me!
Thanks!

**Comment by iurichiba** [comment]
It doesn't appear to be a problem, anymore. I'm closing :)

**Comment by eshimitzu** [comment]
It's a huge problem for us.

**Comment by Pro100Andrey** [comment]
@eshimitzu, please provide more info

**Comment by eshimitzu** [comment]
We use server which generates QuickBlox tokens. I create session with following code, but update block never runs.

QBSettings.setApplicationID(11111)
let session = QBASession()
session.token = "8e2d311341561c0826263cceca11dffa9715ae0c"
QBSession.currentSession().startSessionWithDetails(session) {
     //TODO receive token from server
                       if let token = json["token"].string,
                            let applicationID = json["application_id"].uInt,
                            let nonce = json["nonce"].int,
                            let ts = json["ts"].uInt
                        {
                            let sessionDetails = QBASession()
                            sessionDetails.token = token
                            sessionDetails.applicationID = applicationID
                            sessionDetails.timestamp = ts
                            sessionDetails.nonce = nonce
                            
                            QBSession.currentSession().startSessionWithDetails(sessionDetails)
                        }
}

Maybe I'm doing something wrong?
Thanks!
