### ISSUE TITLE
App was rejected for having "audio" selected in info.plist - background mode

### ISSUE THREAD

**Issue by shalem93** [QuickBlox/quickblox-ios-sdk#430]
*Help avoid duplicate issue reports, check [existing issues](https://github.com/QuickBlox/quickblox-ios-sdk/issues)*
 
**Environment details**
*iOS version, Quickblox iOS SDK version, QuickbloxWebRTC SDK version (optional)*
iOS 9.3

**Did this work before?**
Yes

**Expected behavior**
Apple to accept the app for background mode 'audio.' I don't think they consider audio as a background behavior to work with VOIP. Are you guys sure I shouldn't select VOIP for background modes in Info.plist???

**Actual behavior**
Declined new binary submission for having 'audio' selected in my info.plist.
"Your app declares support for audio in the UIBackgroundModes key in your Info.plist but did not include features that require persistent audio."
-App Store

**Any others comments?**
 
 Let me know your thoughts when you can. I responded by saying we use audio when we are in a call but Ill see how they respond...

**Comment by Pro100Andrey** [comment]
Hi @shalem93 
1) [Please check](http://quickblox.com/developers/Sample-webrtc-ios#Background_mode)
> In the Info.plist file for your app, set up the background mode permissions as described in the Apple documentation for creating VoIP apps. The key is UIBackgroundModes. Add the audio value to this dictionary. Do not add voip to this dictionary. We have seen applications rejected from the App Store specifically for the use of the voip flag, so it is important not to skip this step.
There is also a UI for setting app background modes in XCode 5. Under the app build settings, open the "Capabilities" tab. In this tab, turn on "Background Modes" and set the "Audio and AirPlay" checkbox to set the audio background mode, just as in the method for editing Info.plist, above. For completeness, we describe both methods, but the results are identical — you only need to use one of the methods.

2)  Reply back to Apple and tell them where in your content they can find audio that's got background playback enabled

**Comment by shalem93** [comment]
I did this and apple rejected me. Please re-read my comment :)

**Comment by Raikerian** [comment]
Hi @shalem93 

You mentioned:

> I responded by saying we use audio when we are in a call but Ill see how they respond...

Have you got response already?

**Comment by shalem93** [comment]
Sorry let me re-explain. I DID set in my background mode to have audio capabilities allowed. Apple rejected me for this. I was wondering why, and if I should set VOIP?


This is Apple's reason in the resolution center: "Your app declares support for audio in the UIBackgroundModes key in your Info.plist but did not include features that require persistent audio."
-App Store

But technically our video calls use this audio. However it is when we use VOIP, so I'm confused...

**Comment by VitaliyGuru** [comment]
@shalem93 Our SDK needs only audio for UIBackgroundModes.
When you're uploading binary for Apple review you can add comments to the review team. Tell them that WebRTC SDK needs this background mode.

**Comment by Raikerian** [comment]
@shalem93 were you able to accomplish it?

**Comment by shalem93** [comment]
Yes, everything is ok

**Comment by smuppalaneni** [comment]
@shalem93 i have a project on this,let me know if you are interestred

**Comment by vivek5586** [comment]
@shalem93 can you let me know wat needs to be done if the app is rejected
