### ISSUE TITLE
user not logging in (xmpp messenger in swift)

### ISSUE THREAD

**Issue by ashiqsulaiman** [QuickBlox/quickblox-ios-sdk#431]
*Help avoid duplicate issue reports, check [existing issues](https://github.com/QuickBlox/quickblox-ios-sdk/issues)*
 
**Environment details**
*iOS version, Quickblox iOS SDK version, QuickbloxWebRTC SDK version (optional)*

**Did this work before?**
nope

**Expected behavior**
to log in with the selected user

**Actual behavior**
displays Request failed: unauthorised 401

**Logs**

2016-05-10 14:56:49.803 sample-chat-swift[3925:631540] Init - QMAuthService service...
2016-05-10 14:56:49.804 sample-chat-swift[3925:631540] Init - QMChatService service...
2016-05-10 14:56:49.834 sample-chat-swift[3925:631540] Init - QMUsersService service...

*Attach full logs that will describe your problem (please, use github [gist](https://gist.github.com/))*

**Steps to reproduce the behavior**

**Any others comments?**
 I have entered the app id,secret, auth key in the app delegate of downloaded code. I also added users in the app's admin panel. But when i fire up the application i am not able to see the registered user names and when i select the sample user names i get the 401 error. The code works fine when i run the sample as such without changing the app id, secret etc

**Comment by VitaliyGuru** [comment]
@ashiqsulaiman  please update you issue with full logs. 
```
// Enables Quickblox REST API calls debug console output
    [QBSettings setLogLevel:QBLogLevelDebug];

// Enables detailed XMPP logging in console output
    [QBSettings enableXMPPLogging];
```

**Comment by ashiqsulaiman** [comment]
@VitaliyGuru where do i enter these pieces of code ? and is this in swift ?

**Comment by VitaliyGuru** [comment]
@ashiqsulaiman 
In the `AppDelegate.swift` file in `func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {`
for swift use methods:

```
 // Enables Quickblox REST API calls debug console output.
		QBSettings.setLogLevel(QBLogLevel.Debug)
        
 // Enables detailed XMPP logging in console output.
        QBSettings.enableXMPPLogging()
```

**Comment by ashiqsulaiman** [comment]
@VitaliyGuru It is still not printing in the log.
2016-05-10 17:30:20.701 sample-chat-swift[4636:1336137] Init - QMAuthService service...
2016-05-10 17:30:20.703 sample-chat-swift[4636:1336137] Init - QMChatService service...
2016-05-10 17:30:20.708 sample-chat-swift[4636:1336137] Init - QMUsersService service...
in login table

this is the only thing that is printed in the log

**Comment by VitaliyGuru** [comment]
@ashiqsulaiman in sample chat project we search users by tag "dev".

`self.usersService.searchUsersWithTags([enviroment]).continueWithBlock {`

If you want to get users you have registered you should  change the method above to the following:

```
 let page = QBGeneralResponsePage(currentPage: 0, perPage:100);

        QBRequest.usersForPage(page, successBlock: { (response:QBResponse, responsePage:QBGeneralResponsePage?, users:[QBUUser]?) in
             successBlock?(users)
        }) { (responce:QBResponse) in
            errorBlock?((responce.error?.error)!)
        }
```
You see our test users because they've been cached on the first launch with our credentials. 
And when you change the app id, secret etc you can't login, because this users belong to other app id.

**Comment by ashiqsulaiman** [comment]
in which file can i find
self.usersService.searchUsersWithTags([enviroment]).continueWithBlock {

**Comment by Raikerian** [comment]
Hi @ashiqsulaiman 

You can see tags management in ServicesManager class. Just replace it with your own users loading method.
All users loading methods are available in QMUsersService class. See header file for inline documentation.

**Comment by Raikerian** [comment]
If you are still having any other troubles, feel free to create a separate issue.
