### ISSUE TITLE
Getting unreadMessages to mark it as read question.

### ISSUE THREAD

**Issue by matrosovDev** [QuickBlox/quickblox-ios-sdk#432]
Hey guys!) I've played with demo project, I have question regarding ChatViewController and unreadMessages.

So we have two delegate callbacks:
`func chatServiceChatDidConnect(chatService: QMChatService)`
`func chatServiceChatDidReconnect(chatService: QMChatService)`

where we call `func refreshAndReadMessages()` and we call `func readMessages(messages: [QBChatMessage])` right after that with passing messages to read which is unread.

I searched trough the demo project and there is only one place where we setup unreadMessages and this is in the same function `func readMessages(messages: [QBChatMessage])` and my question is why we get messages from `self.unreadMessages` and then passing it to `func readMessages(messages: [QBChatMessage])` and then again set it to `self.unreadMessages` if chat is not connected.

**Comment by matrosovDev** [comment]
Actually seems `chatServiceChatDidConnect` is never called

**Comment by Raikerian** [comment]
Hi @matrosovDev 

Yes, it seems there is some unused logic in our samples. Right now we are marking messages on cell being displayed on screen.

**Comment by WillsAtIOS** [comment]
If you want to know the status of any message you should MessageStatusStringBuilder.h  and MessageStatusStringBuilder.m and this you can handle where ever you want to know the status of the message. Once go through this you will find these classes in sample-chat application provided in quickblox. I hope it is clear.

**Comment by matrosovDev** [comment]
@Raikerian Hey, how then I can mark my messages as read, Looks like it works in demo project, but as I found out we never use unreadMessages instance?

Thanks!

**Comment by matrosovDev** [comment]
Seems I fount it thanks!

**Comment by Raikerian** [comment]
@matrosovDev that instance was supposed to keep messages, that you need to read after internet connection been restored. However that logic is unused now due to messages been marked as read only if they are visible and read request was successful.
