### ISSUE TITLE
Getting Video call pop up after decline video call

### ISSUE THREAD

**Issue by rawat555** [QuickBlox/quickblox-ios-sdk#44]
Hi,
 I am using QuickBlox video call API.

Sometime I am getting unnecessary video call pop up after declining video call. 
Steps :

1.Call User2 from User1 and decline it from User2 device.
Result: Declined pop up appear that is ok.

2.Now call User1 from User2 and decline.
Result : unnecessary video call pop up appearing on  again if user decline call

Please fix this issue if it is possible
Thanks

**Comment by soulfly** [comment]
You can fix it on app side, 

for example if the user declined call and received another incoming request from the same user during next 2 seconds for example - just ignore it
