### ISSUE TITLE
QBChatMessage how to show displayName

### ISSUE THREAD

**Issue by matrosovDev** [QuickBlox/quickblox-ios-sdk#440]
How to display user name instead of user id. When I send a message I set `message.customParameters = ["displayName": userDisplayName, "senderIdentityId" : senderIdentityId]`

but when I am in group chat I see senderIdentityId at top and don't see nothing for private chat. How can I solve it.

thanks

**Comment by Raikerian** [comment]
Hi,

Please specify your question with more details. Right now in our samples we have a user login on top of messages in group chat, you can replace it with your custom field.
