### ISSUE TITLE
See the first unread message instead of last cell.

### ISSUE THREAD

**Issue by matrosovDev** [QuickBlox/quickblox-ios-sdk#446]
If we received a lot of messages about 100 we still see the last 8 for example and we still have 92 messages that we don't see. My question is there any available method to display not the last cell in chat view controller, but instead show the first unread cell? So I guess we need to be at the message that we just receive and then we can scroll up to see the latest message, like Skype does.

Thanks

**Comment by VitaliyGuru** [comment]
Hi @matrosovDev ,
There is no such functionality for now. We also in thoughts about this feature, and maybe in near future we will implement it. 
Thanks for suggestion.

**Comment by Raikerian** [comment]
We will consider adding such functionality in our chat controller in a near future, but there is no any ETA yet. Please follow our [blog](http://quickblox.com/blog) for more information.
Also, you are always welcome to fork from our QMChatViewController repository for custom functionality implementation :)

**Comment by matrosovDev** [comment]
ok got cool! thanks!
