### ISSUE TITLE
A lot of messages cause scrolling and memory issue.

### ISSUE THREAD

**Issue by matrosovDev** [QuickBlox/quickblox-ios-sdk#447]
Sending 3000 messages from other device cause memory issue and scrolling issues.

I've sent 3000 messages to another account and after opening chat view controller I see that it's stuck and crashes due a lot of messages. I've checked seems there is a dequeueing when building a new cell, though still got a crash here.

**Comment by Raikerian** [comment]
Hi,

In order to fix this, pagination should be implemented. If you have a lot of messages, some of them should be removed from collection view.

We will implement this in a near future, but for now you can do it by yourself.
