### ISSUE TITLE
XMPP crash

### ISSUE THREAD

**Issue by svlaev** [QuickBlox/quickblox-ios-sdk#448]
Hello, QB people!

I stumbled on a crash, which happens from time to time when I get the list of messages for dialog and start marking them as read. Xcode can't catch the exception, although I have Exceptions breakpoint enabled. That's why I assume the exception is raised by the QB SDK. Please find Xcode's crash stack trace in the Gist below.
**Logs**
[Gist](https://gist.github.com/svlaev/e23bdb3868c71eb74930351960b6492f) (Hint: I have replaced app's name with **AppName** )
**Edit:** 
[Here's](https://gist.github.com/svlaev/627ffc82f450c9937604ccfd0d63f043) a stack trace from Fabric, which seems like the same crash(happens on the same spot).

**Environment details**
iOS version - 9.3.1, Quickblox iOS SDK version - 2.7.2

**Comment by tonchis** [comment]
Hello people! I'm experiencing the same crash. I also replaced my app's name.

[Gist](https://gist.github.com/tonchis/7fca63855122685502575dcc1c550d1b)

**Comment by Raikerian** [comment]
Hi @svlaev and @tonchis 

Can you please disable exception breakpoint and give us the exact log you are receiving in debug console? (with full crash details).

**Comment by svlaev** [comment]
@Raikerian thanks for the response. 
Disabling exception breakpoint helped me to realise some things and I figured out I had a nasty GCD issue. I haven't thought disabling this particular breakpoint will make things better in terms of stack traces.
It's all clear now.
Sorry for the inconvenience!
