### ISSUE TITLE
QuickBlox  "Request failed: client error (422)"  on some devices 

### ISSUE THREAD

**Issue by MuqeemAhmad** [QuickBlox/quickblox-ios-sdk#452]
Error Domain=com.alamofire.error.serialization.response Code=-1011 "Request failed: client error (422)" UserInfo={com.alamofire.serialization.response.error.response=<NSHTTPURLResponse: 0x1355db790> { URL: https://api.quickblox.com/session.json } { status code: 422, headers {
    "Access-Control-Allow-Origin" = "*";
    "Cache-Control" = "no-cache";
    Connection = "keep-alive";
    "Content-Length" = 37;
    "Content-Type" = "application/json; charset=utf-8";
    Date = "Tue, 17 May 2016 08:36:18 GMT";
    "QuickBlox-REST-API-Version" = "0.1.1";
    Server = "nginx/1.8.1";
    Status = "422 Unprocessable Entity";
    "X-Rack-Cache" = "invalidate, pass";
    "X-Request-Id" = 0517162073ceae4d87d5ebf3df20d1d1;
    "X-Runtime" = "0.007235";
    "X-UA-Compatible" = "IE=Edge,chrome=1";
} }, NSErrorFailingURLKey=https://api.quickblox.com/session.json, NSLocalizedRecoverySuggestion={"errors":{"base":["Bad timestamp"]}}, com.alamofire.serialization.response.error.data=<7b226572 726f7273 223a7b22 62617365 223a5b22 42616420 74696d65 7374616d 70225d7d 7d>, NSLocalizedDescription=Request failed: client error (422)}

**Comment by VitaliyGuru** [comment]
Hi @MuqeemAhmad ,
Do you manage session manually?

Bad timestamp means that while Creating Session you sent invalid 'timestamp' value which is based on your phone time.Your device time shouldn't differ from server more then 2 hours.
We suggest you synchronise time on your devices with NTP service or just set tick 2 checkboxes in Settings in your device: Automatic date & time and Automatic time zone

Hope this help

**Comment by MuqeemAhmad** [comment]
Thanks @VitaliyGuru 
The error has been removed and the friends list appears.
But we are facing one more problem.when we try to conncect for video calling then its too long time and after that its gives an error.and the error is "Destroy dialing timer".and after that call is disconnect.

**Comment by Raikerian** [comment]
@MuqeemAhmad 

Seems like your new issue does not have any reference to this one anymore. Please create a separate one with full WebRTC logs (according to your post you have problems with logs). Thank you.

**Comment by atulawasthimarch** [comment]
I want to integrate chat and pushnotification in my ios app ,i am dfacing following issue

[QBCore] Response error: Error Domain=com.alamofire.error.serialization.response Code=-1011 "Request failed: client error (422)" UserInfo={com.alamofire.serialization.response.error.response=<NSHTTPURLResponse: 0x165845e0> { URL: https://api.quickblox.com/subscriptions.json } { status code: 422, headers {
    "Access-Control-Allow-Origin" = "*";
    "Cache-Control" = "no-cache";
    Connection = "keep-alive";
    "Content-Type" = "application/json; charset=utf-8";
    Date = "Wed, 01 Mar 2017 19:29:25 GMT";
    "QB-Token-ExpirationDate" = "2017-03-01 21:17:48 UTC";
    "QuickBlox-REST-API-Version" = "0.1.1";
    Server = "openresty/1.9.15.1";
    Status = "422 Unprocessable Entity";
    "Transfer-Encoding" = Identity;
    "X-Rack-Cache" = "invalidate, pass";
    "X-Request-Id" = 7b07c1c2ae10671ed5d7e25b47876000;
    "X-Runtime" = "0.013668";
    "X-UA-Compatible" = "IE=Edge,chrome=1";
} }, NSErrorFailingURLKey=https://api.quickblox.com/subscriptions.json, NSLocalizedDescription=Request failed: client error (42
2017-03-02 00:59:25.228194 MyAppTest[3958:2667145] Errors = 
   Error reasons:{
    code = "<null>";
    message = "unknown attribute: bundle_identifier";
}
2017-03-02 00:59:25.230975 MyAppTest[3958:2667200] [QBCore] Response error reasons: {
    code = "<null>";
    message = "unknown attribute: bundle_identifier";
}

Please help me

**Comment by vineeshtp** [comment]
How did you resolve this issue?. I am facing the same when register new user.
