### ISSUE TITLE
WebRTC video call gets disconnected on iPhone 4S - high CPU usage

### ISSUE THREAD

**Issue by scorchio** [QuickBlox/quickblox-ios-sdk#454]
This is possibly relevant to #121.

**Environment details**
- iOS: 9.3.1
- QuickBlox: 2.7.2
- Quickblox-WebRTC: 2.2

**Expected behavior**
The connection should build up properly and we should see the video stream coming from the iPhone 4S on the other device.

**Actual behavior**
The iPhone 4S connects to the other device, but after a very short amount of time (several seconds) the device disconnects from the other one. The CPU usage of the iPhone goes well over 100% before disconnecting.

**Logs**
https://gist.github.com/scorchio/f4587df96dd108b1f934e610a2354870

**Steps to reproduce the behavior**
Start video call on an iPhone 4S with the following settings:
```objc
[QBRTCConfig setAnswerTimeInterval:20];
[QBRTCConfig setDisconnectTimeInterval:20];
[QBRTCConfig setDialingTimeInterval:5];
[QBRTCConfig setDTLSEnabled:YES];
[QBRTCConfig setMediaStreamConfiguration:[QBRTCMediaStreamConfiguration defaultConfiguration]];
[QBRTCClient initializeRTC];
```

**Comment by VitaliyGuru** [comment]
Hi @scorchio , for iPhone 4s try to set resolution lower than 640x480 and decrease `frameRate`. 
`frameRate` is the property of the `QBRTCVideoFormat` class. 
```
        Settings *settings = [SampleCore settings];
        self.cameraCapture = [[QBRTCCameraCapture alloc] initWithVideoFormat:settings.videoFormat
                                                                    position:settings.preferredCameraPosition];
        [self.cameraCapture startSession];
```
The instance of the `QBRTCVideoFormat` is a property of `Settings *settings`

And then could you please enable stats report and send us this information.

`[QBRTCConfig setStatsReportTimeInterval:1.f];` - method for enabling stats report.

In your controller you should adopt QBRTCClientDelegate and use [this delegate method](https://github.com/QuickBlox/quickblox-ios-sdk/blob/master/sample-videochat-webrtc/sample-videochat-webrtc/ViewControllers/CallViewController/CallViewController.m#L353-404).

**Comment by scorchio** [comment]
Thanks for letting me know, @VitaliyGuru. I'm closing this.
