### ISSUE TITLE
Any way to disable local notifications when the app's on the foreground?

### ISSUE THREAD

**Issue by iurichiba** [QuickBlox/quickblox-ios-sdk#463]
*Help avoid duplicate issue reports, check [existing issues](https://github.com/QuickBlox/quickblox-ios-sdk/issues)*
 
**Environment details**
*iOS version, Quickblox iOS SDK version, QuickbloxWebRTC SDK version (optional)*
Any iOS version, I guess. Using Quickblox Pod v2.7.2

**Did this work before?**
I don't think so

**Expected behavior**
I'd like to disable local notifications, they mimic Apple notifications when you receive a new message, but I can't disable or customize it. I'd like to change it to something else.

**Actual behavior**
A local notification appears when a message is received and the app's on the foreground.

**Logs**
*Attach full logs that will describe your problem (please, use github [gist](https://gist.github.com/))*
No logs needed.

**Steps to reproduce the behavior**
Just receive a message, while the app's on the foreground. I see this behaviour when I'm on the dialogs view.

**Any others comments?**
Hope you guys can help me. Thanks! :)

**Comment by Raikerian** [comment]
Hi,

Not sure what are you talking about. If this is about our samplechat, you can disable message notification here: https://github.com/QuickBlox/quickblox-ios-sdk/blob/master/sample-chat/sample-chat/Services/ServicesManager.m#L147

The actual method: https://github.com/QuickBlox/quickblox-ios-sdk/blob/master/sample-chat/sample-chat/Services/ServicesManager.m#L38

**Comment by iurichiba** [comment]
That's it, thanks! Sorry for the dumb question, I'm still a bit lost with these QB interactions... things like what method's called when a message comes in and so on, haha! Sorry. But thanks for that help either way :)
