### ISSUE TITLE
How to remove dialog from dialog list Using QMServicesManager in case of Group and Public chat?

### ISSUE THREAD

**Issue by WillsAtIOS** [QuickBlox/quickblox-ios-sdk#467]
Hi, I'm trying to delete dialogs. So I did like this.. stack over flow solution StackOverFlow Link for my previous question and suggested solution by V.Guru Quickblox Now its working fine. And now I got new requirement So I have some doubts here.

Now If I want to delete group chat how I should handle this ? If I use the same method inside it we are passing forAllUsers as "NO" which is hard coded. written inside QMChatServices.m

```
- (void)deleteDialogWithID:(NSString *)dialogId completion:(void (^)(QBResponse *))completion {

    NSParameterAssert(dialogId);

    __weak __typeof(self)weakSelf = self;

    [QBRequest deleteDialogsWithIDs:[NSSet setWithObject:dialogId] forAllUsers:NO successBlock:^(QBResponse *response, NSArray *deletedObjectsIDs, NSArray *notFoundObjectsIDs, NSArray *wrongPermissionsObjectsIDs) {
        //
        [weakSelf.dialogsMemoryStorage deleteChatDialogWithID:dialogId];
        [weakSelf.messagesMemoryStorage deleteMessagesWithDialogID:dialogId];

        if ([weakSelf.multicastDelegate respondsToSelector:@selector(chatService:didDeleteChatDialogWithIDFromMemoryStorage:)]) {
            [weakSelf.multicastDelegate chatService:weakSelf didDeleteChatDialogWithIDFromMemoryStorage:dialogId];
        }

        [weakSelf.loadedAllMessages removeObjectsForKeys:deletedObjectsIDs];

        if (completion) {
            completion(response);
        }
    } errorBlock:^(QBResponse *response) {
        //
        if (response.status == QBResponseStatusCodeNotFound || response.status == 403) {
            [weakSelf.dialogsMemoryStorage deleteChatDialogWithID:dialogId];

            if ([weakSelf.multicastDelegate respondsToSelector:@selector(chatService:didDeleteChatDialogWithIDFromMemoryStorage:)]) {
                [weakSelf.multicastDelegate chatService:weakSelf didDeleteChatDialogWithIDFromMemoryStorage:dialogId];
            }
        }
        else {

            [weakSelf.serviceManager handleErrorResponse:response];
        }

        if (completion) {
            completion(response);
        }
    }];
}

```

So Now my doubt is..

Question 1 : What if we want to delete dialog for all the users. Question 2 : Lets say there are 3 users. User1 , User2 and User3. Now User1 has created group with User2 and User3.

So how this method is useful for all the different 3 users. I mean What happens if User1 uses

`[ServicesManager.instance.chatService deleteDialogWithID:dialog.ID completion:nil];
`and what happens if User2 and User3 uses the same method.

Weather it works as exit from the dialog or deleting dialog. I'm little confused how this method works for different users in case of group and public chat.

Question 3 : Is there any other way to exit from the group chat ? I hope it is clear !!

Environment details
iOS version, Quickblox iOS SDK version, QMServices version, Objective - C

**Comment by Raikerian** [comment]
Hi,

1. You right, there is no interface for deleting dialog for all users right now. But keep in mid that only the owner of group dialog (its creator) [can delete it](http://quickblox.com/developers/Chat#Delete_dialog). And owner cannot be changed, even if he will left the dialog. We will consider adding such method in a near future, but for now you can easily modify it for your needs (you are welcome to fork from our services repository).

2. If any of the user uses this method - he will be out of that group (by server), but group itself will still exist with other members. But other members will only know about left users when they will redownload dialog from REST. So in order to notify them live, we are sending XMPP notifications before leaving, like this one: https://github.com/QuickBlox/quickblox-ios-sdk/blob/master/sample-chat/sample-chat/ViewController/DialogsViewController.m#L235

3. Pretty much what I said in 2. Notifying users live about our leaving and deleting dialog through REST (QBRequest) request.

**Comment by Raikerian** [comment]
If you are still having any other troubles or questions, let us know by creating a separate issue.

**Comment by ajayrigaps** [comment]
I have an issue with Chat dialog delete . Below are the major issues i am facing while implementing the chat in my project . need help asap on the same . 

1 . I have pinged opponent and a chat dialog get created for example with id -123456789. 
     Now this dialog is same for both initiator and opponent .
     a . Now If initiator deletes his dialog , It will be deleted successfully . (Delete for all users - NO)
     b. But if Opponent is trying to delete the same dialog at his end , getting Wrong Permission      error 

2. Same scenario there is a dialog get created between 2 users  ID - 123456789
    now if either one of the user deleted the dialog , It will be deleted in his end . Now Opponent doesn't know that the dialog is deleted . If opponent ping some thing on dialog messages are appearing on the screen but going no where , There is no dialog created and no initiator receives messages . But the message sender is in a perception that messages are going fine .
How to handle this scenario .

**Comment by ajayrigaps** [comment]
Every chat is a private chat in the above case i explained .
