### ISSUE TITLE
Lost messages issue

### ISSUE THREAD

**Issue by matrosovDev** [QuickBlox/quickblox-ios-sdk#472]
Hey guys I use new SDK
pod 'QMChatViewController', '~> 0.3.7'
pod 'QMServices', '0.4'
pod 'QuickBlox', '2.7.2'

Currently I faced with the issue when not all time I can see all messages, the last messages I sent sometimes I lost after quick connect.

I've implemented these delegates:
func chatService(chatService: QMChatService, didLoadMessagesFromCache messages
func chatService(chatService: QMChatService, didAddMessageToMemoryStorage message
func chatService(chatService: QMChatService, didUpdateChatDialogInMemoryStorage chatDialog
func chatService(chatService: QMChatService, didUpdateMessage message: QBChatMessage
func chatService(chatService: QMChatService, didUpdateMessages messages: [QBChatMessage]

and all of them update chatSection messages. But sometimes not all messages in the table.

**Comment by matrosovDev** [comment]
I found that sometimes this code does not have _chatService:

let _chatService = QMServicesManager.instance().chatService
let messages = _chatService.messagesMemoryStorage.messagesWithDialogID(dialog.ID!)

My question where we actually initialize it?

**Comment by matrosovDev** [comment]
I also found that @property (strong, nonatomic, readonly, QB_NONNULL) QMChatService* chatService;

can't never be nil, so I assuming that I every time receive messages. But there is no messages at some cases from messagesMemoryStorage.messagesWithDialogID

**Comment by matrosovDev** [comment]
seems we don't have message in storage before creating a chat right?

**Comment by Raikerian** [comment]
Hi,

chatService is always alive after your first access to QMServicesManager singleton (in any way). So it could not be the case in your situation. Unfortunately I cannot give you any explanation on why you missing some messages without seeing any kind of code snippet or logs (where we can exactly see that message has been arrived but chat service did not save it).
