### ISSUE TITLE
Error when installing quickblox and Quickblox-WebRTC using cocoapods

### ISSUE THREAD

**Issue by muraribohra** [QuickBlox/quickblox-ios-sdk#475]
When i am installing quickblox and Quickblox-WebRTC using cocoapods, getting following error.

library not found for -lBolts

What is the issue. Thanks

**Comment by Raikerian** [comment]
Hi,

Quickblox-WebRTC does not have any reference to Bolts framework. Please show us your podfile and complete error.

**Comment by muraribohra** [comment]
my pod file is this:

# Uncomment this line to define a global platform for your project
 platform :ios, '7.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target '***' do
pod 'Quickblox-WebRTC', '~> 2.2'
pod 'QuickBlox'
pod 'SVProgressHUD'
pod 'TWMessageBarManager', '~> 1.7.2'


#Production pod
pod 'QMCVDevelopment', :git => 'git@github.com:QuickBlox/QMChatViewController-ios.git', :commit => '5bb608405c89bbb3b0189a4e188098f27c2af72a'

#For development pods
#pod 'QMCVDevelopment', :path => '../../QMChatViewController-ios/'

#Production pod
pod 'QMServicesDevelopment', :git => 'git@github.com:QuickBlox/q-municate-services-ios.git', :commit => '84e55c43f028589d9f6304b1224bcdc62926b619'


end

**Comment by VitaliyGuru** [comment]
Hi @muraribohra , Please remove `use_frameworks!` and reinstall pods. We don't support dynamic frameworks.
