### ISSUE TITLE
Connection Hanging / Connection refused

### ISSUE THREAD

**Issue by coredream** [QuickBlox/quickblox-ios-sdk#489]
*Help avoid duplicate issue reports, check [existing issues](https://github.com/QuickBlox/quickblox-ios-sdk/issues)*
 
**Environment details**
*iOS version, Quickblox iOS SDK version, QuickbloxWebRTC SDK version (optional)*
iOS 9.3.2, 'QuickBlox', '2.7.2', 'QMServices', '0.4'

**Did this work before?**
Yes

**Expected behavior**
Connect to chat

**Actual behavior**
Connection hanging 

**Logs**
*Attach full logs that will describe your problem (please, use github [gist](https://gist.github.com/))*
I was unable to get full logs, but was told error in console was constantly:
Error Code 61, Connection refused, Error in connect() function

**Steps to reproduce the behavior**
Use sample chat, login as a user.

**Any others comments?**
 Last night and this morning 26/May/2016:15:47:50 +0000, (for a period of about 10-15 minutes), the Quickblox server appeared to be down.  Couple questions:
1.  Was there a known maintenance/downtime period on your shared server?
2.  Why does QMServicesManager logInWithUser not call completion with error in this case?  The end user experience seems like connection attempt hanging forever.
3.  Would this have anything to do with using setChatDNSLookupCacheEnabled:YES?

Currently, everything seems to be working ok.  Will try to get better logging if I see it again.

**Comment by Raikerian** [comment]
Hi @coredream 

Does the issue still exists?

**Comment by coredream** [comment]
Hi @Raikerian 

After looking into this more, it seems that calls to "api.quickblox.com" were succeeding (initial login), but calls to "chat.quickblox.com" (chat service) were getting connection refused.

Although this problem hasn't occurred since I last reported it, there is actually an easy way to repro this on a Mac/using an iOS simulator:

1. Open your /etc/hosts/file, add this line and save:  `0.0.0.0 chat.quickblox.com`
2. Run the sample chat app in any iOS simulator.

It's understandable that the chat service may be down in real life, but it would seem more ideal if this code actually returned an error instead of trying/hanging indefinitely:

`[weakSelf.chatService connectWithCompletionBlock:^(NSError *error) `

Here is a log after setting QBLogLevelDebug:  https://gist.github.com/coredream/fc2db1b5b30d7040c4fe2ba889267014
