### ISSUE TITLE
How can I get the status/progress of a QBRequest for both creating and retrieving a custom class?

### ISSUE THREAD

**Issue by mitchellporter** [QuickBlox/quickblox-ios-sdk#49]
Here is an example of how I retrieve objects of a custom class from Quickblox:

```Objective-C
[QBRequest objectsWithClassName:@"My_Custom_Class" extendedRequest:getRequest successBlock:^(QBResponse *response, NSArray *objects, QBResponsePage *page) {
        // Success
    } errorBlock:^(QBResponse *response) {
        // Error
    }];
```
Here is an example of how I create new objects for a custom class in Quickblox:
```Objective-C
QBCOCustomObject *object = [QBCOCustomObject customObject];
    object.className = @"My_Custom_Class";
    
    // Object fields
    [object.fields setObject:self.titleTextView.text forKey:@"Title"];
    [object.fields setObject:self.bodyTextView.text forKey:@"Body"];
    [object.fields setObject:self.userSession.fullName forKey:@"Author_Name"];
    [object.fields setObject:@"self.username" forKey:@"Author_Username"];
    
    [QBRequest createObject:object successBlock:^(QBResponse *response, QBCOCustomObject *object) {

        // Response

    } errorBlock:^(QBResponse *response) {
        // Error
    }];
```
I need to be able to get the status/progress of these, so that I can show a loading/progress bar to my users based on actual progress made.

How can I do this?

**Comment by soulfly** [comment]
There is no such feature, progress is only for files upload/download

**Comment by mitchellporter** [comment]
@soulfly Would it be possible if I was using the REST API instead of the SDK?

**Comment by soulfly** [comment]
I think so, but not sure why you need this

**Comment by mitchellporter** [comment]
@soulfly Anytime your doing any type of networking, its best to show the user some type of activity indicator so they know that new content is being fetched. My problem is that I want to show an activity indicator that shows the actual percentage of progress the loading has made so far.

**Comment by soulfly** [comment]
Well in that case it will be too fast for the end user because it's actually works fast without any visible phases

For upload/download files it does make sence

For other queries you can emulate such a logic an a client side
