### ISSUE TITLE
Unable to sign up with the same username on different apps

### ISSUE THREAD

**Issue by prometheon** [QuickBlox/quickblox-ios-sdk#493]
I have a user "test" on Application A. When I attempt to sign up a user on Application B with the username "test", I get a client 422 error. 

**Did this work before?**
No.

**Expected behavior**
Should be able to have a user on Application A with username "test" as well as a different user with the username "test" on Application B.

**Actual behavior**
Client 422 error

**Steps to reproduce the behavior**
1. Sign up user with username "test" on Application A.
2. Attempt to sign up a user on another application on your account, Application B, with the same username.

**Comment by VitaliyGuru** [comment]
@prometheon Could you please print the full description of the error?

**Comment by Raikerian** [comment]
Hi @prometheon 

Users login are unique for account (so you cannot have same login for too apps), but users are not shared between applications. So you cannot login in application B with user from application A.

**Comment by Raikerian** [comment]
If you are still having any other troubles, feel free to let us know by creating a separate issue.

Also, if you are receiving any kind of error, always prinit `[response.error reasons]` to see the exact reason of error.

**Comment by prometheon** [comment]
Hi @Raikerian . Thanks for the response. Just a quick question, will you guys be implementing unique logins for each app in the future?

**Comment by Raikerian** [comment]
The new version of admin panel and server are in progress, there is no any ETA yet. Follow our blog for any news regarding our platform [here](http://quickblox.com/blog).
The new architecture of server will allow only 1 app per account therefore there will no be any problems like yours in a future :)

**Comment by prometheon** [comment]
@Raikerian Will those who have been paying for Quickblox that have multiple Apps be forced to kill all but one running instance? I have several apps and this would be reason for me to move to another service. I'm not sure how most of your paying users use your service though, whether one or multiple apps. Perhaps it wouldn't effect your main user base as much.

**Comment by Raikerian** [comment]
@prometheon all apps will stay as they are, you will only be asked to move shared users to one of the existent apps.

**Comment by lennynero** [comment]
Hi@Raikerian,
i have readed about shared instance to solve same username on 2 different apps on blog article [here](https://quickblox.com/blog/shared-instance-quickblox-application-upgrade-on-3rd-march-at-1500-eet/), but i cant know when this new service is available. Can you say when upgrade is completed?
