### ISSUE TITLE
when Attach video it shows the error.

### ISSUE THREAD

**Issue by mallikaD** [QuickBlox/quickblox-ios-sdk#496]
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSConcreteData size]: unrecognized selector sent to instance 0x7d5a49a0'
*** First throw call stack:
(
	0   CoreFoundation                      0x04819494 __exceptionPreprocess + 180
	1   libobjc.A.dylib                     0x042d1e02 objc_exception_throw + 50
	2   CoreFoundation                      0x04823253 -[NSObject(NSObject) doesNotRecognizeSelector:] + 275
	3   CoreFoundation                      0x0475889d ___forwarding___ + 1037
	4   CoreFoundation                      0x0475846e _CF_forwarding_prep_0 + 14
	5   UIKit                               0x02ba8942 -[UIImageView _updateImageViewForOldImage:newImage:] + 406
	6   UIKit                               0x02ba3ffa -[UIImageView setImage:] + 413
	7   samplechat                          0x0010e29c -[QMChatAttachmentOutgoingCell setAttachmentImage:] + 204
	8   samplechat                          0x000e404f __64-[ChatViewController collectionView:configureCell:forIndexPath:]_block_invoke + 511
	9   samplechat                          0x0016c410 -[QMChatAttachmentService getImageForAttachmentMessage:completion:] + 656
	10  samplechat                          0x000e3c53 -[ChatViewController collectionView:configureCell:forIndexPath:] + 3491
	11  samplechat                          0x001237c8 -[QMChatViewController collectionView:cellForItemAtIndexPath:] + 584
	12  samplechat                          0x000e4639 -[ChatViewController collectionView:cellForItemAtIndexPath:] + 1161
	13  UIKit                               0x032dd5ee -[UICollectionView _createPreparedCellForItemAtIndexPath:withLayoutAttributes:applyAttributes:isFocused:] + 448
	14  UIKit                               0x032dd2ff -[UICollectionView _createPreparedCellForItemAtIndexPath:withLayoutAttributes:applyAttributes:] + 65
	15  UIKit                               0x032fb4f9 __51-[UICollectionView _viewAnimationsForCurrentUpdate]_block_invoke1587 + 549
	16  UIKit                               0x032f877b -[UICollectionView _viewAnimationsForCurrentUpdate] + 5550
	17  UIKit                               0x032fd949 __62-[UICollectionView _updateWithItems:tentativelyForReordering:]_block_invoke1657 + 184
	18  UIKit                               0x02a17db2 +[UIView(Animation) performWithoutAnimation:] + 82
	19  UIKit                               0x032fcba1 -[UICollectionView _updateWithItems:tentativelyForReordering:] + 3757
	20  UIKit                               0x032f6b62 -[UICollectionView _endItemAnimationsWithInvalidationContext:tentativelyForReordering:] + 17325
	21  UIKit                               0x032f27b0 -[UICollectionView _endItemAnimationsWithInvalidationContext:] + 48
	22  UIKit                               0x032f254c -[UICollectionView _updateRowsAtIndexPaths:updateAction:] + 400
	23  UIKit                               0x032f2619 -[UICollectionView reloadItemsAtIndexPaths:] + 48
	24  samplechat                          0x0011f691 -[QMChatViewController chatSectionManager:didUpdateMessagesWithIDs:atIndexPaths:] + 785
	25  samplechat                          0x0011a2f5 __39-[QMChatSectionManager updateMessages:]_block_invoke_2 + 309
	26  libdispatch.dylib                   0x04d359cd _dispatch_client_callout + 14
	27  libdispatch.dylib                   0x04d1cd90 _dispatch_barrier_sync_f_slow_invoke + 133
	28  libdispatch.dylib                   0x04d359cd _dispatch_client_callout + 14
	29  libdispatch.dylib                   0x04d1af7c _dispatch_main_queue_callback_4CF + 910
	30  CoreFoundation                      0x047631be __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 14
	31  CoreFoundation                      0x04721434 __CFRunLoopRun + 2356
	32  CoreFoundation                      0x04720846 CFRunLoopRunSpecific + 470
	33  CoreFoundation                      0x0472065b CFRunLoopRunInMode + 123
	34  GraphicsServices                    0x06050664 GSEventRunModal + 192
	35  GraphicsServices                    0x060504a1 GSEventRun + 104
	36  UIKit                               0x02953eb9 UIApplicationMain + 160
	37  samplechat                          0x000e80ea main + 138
	38  libdyld.dylib                       0x04d60a25 start + 1
	39  ???                                 0x00000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Logs**
*Attach full logs that will describe your problem (please, use github [gist](https://gist.github.com/))*

**Steps to reproduce the behavior**

**Any others comments?**

**Comment by VitaliyGuru** [comment]
@mallikaD , are you sure that the exception you got belongs to Quickblox SDK?
Are you able to reproduce this in our samples? 
Also add exception breakpoint in order to see the exact line where the crash is occurred.

**Comment by Raikerian** [comment]
Hi @mallikaD 

Any updates on this issue?

**Comment by mallikaD** [comment]
Yes i checked d samples.It is related to quickblox.i got error while attaching the video.
Here is my code.I took the video from simulator and covert that into NSData formate and send the data  like as in below code.It enters into the success block also.

- (void)uploadAndSendAttachmentMessageWithVideo:(QBChatMessage *)message toDialog:(QBChatDialog *)dialog withChatService:(QMChatService *)chatService withAttachedImage:(NSData *)videoData completion:(QBChatCompletionBlock)completion {
    
    [self changeMessageAttachmentStatus:QMMessageAttachmentStatusLoading forMessage:message];
   // [[NSData alloc]initWithContentsOfURL:[NSURL URLWithString:mapURL]]
    NSData *imageData=videoData;
    //NSData *imageData =[[NSFileManager defaultManager]contentsAtPath:videoData];
    
    
    [QBRequest TUploadFile:imageData fileName:@"attachment" contentType:@"video/mp4" isPublic:NO successBlock:^(QBResponse *response, QBCBlob *blob) {
        
        QBChatAttachment *attachment = [QBChatAttachment new];
        attachment.type = @"video";
        attachment.ID = blob.UID;
        attachment.url = [blob privateUrl];
        
        message.attachments = @[attachment];
        message.text = @"Attachment image";
        
        [self saveImageData:imageData chatAttachment:attachment error:nil];
        [self.attachmentsStorage setObject:imageData forKey:attachment.ID];
        
        [self changeMessageAttachmentStatus:QMMessageAttachmentStatusLoaded forMessage:message];
        
        [chatService sendMessage:message type:QMMessageTypeText toDialog:dialog saveToHistory:YES saveToStorage:YES completion:completion];
        
    } statusBlock:^(QBRequest *request, QBRequestStatus *status) {
        
        if ([self.delegate respondsToSelector:@selector(chatAttachmentService:didChangeUploadingProgress:forMessage:)]) {
            [self.delegate chatAttachmentService:self didChangeUploadingProgress:status.percentOfCompletion forMessage:message];
        }
        
    } errorBlock:^(QBResponse *response) {
        
        [self changeMessageAttachmentStatus:QMMessageAttachmentStatusNotLoaded forMessage:message];
        
        if (completion) completion(response.error.error);
    }];
}

**Comment by mallikaD** [comment]
It executes every line in success block code.while displaying it shows the above error.

**Comment by rakii** [comment]
To summarize the above comment, Attaching a video can be done but, can't see it in earlier message collectionviewcell and play the video

**Comment by Raikerian** [comment]
@mallikaD @rakii there is no such feature in our chat controller yet, so you need to implement chat cells for video playing by yourself.

**Comment by mallikaD** [comment]
@VitaliyGuru i dont necessary want to okay the video, as long as the file is transferred properly. how do i ensure that. thanks

**Comment by Raikerian** [comment]
I didn't get your question, can you specify the exact task you need to implement?

**Comment by mallikaD** [comment]
@VitaliyGuru  we are trying to attach a video file to chat and send it to another user, we have had success with the image file but not with the video.

**Comment by Raikerian** [comment]
@mallikaD do you have a problem uploading or downloading? Also as I have already mentioned there is no video attach support in our QMChatViewController and if you are using it you need to implement a video attach cell and uploading/downloading method using Quickblox SDK by yourself.

**Comment by VitaliyGuru** [comment]
@mallikaD Any updates?

**Comment by mallikaD** [comment]
Adding QMServices and QMChatViewController pod files having dependencies with bolts,SDWebImage,TTTAttributedLabel.Already my project contains bolts framework through drag and drop.so i removed that bolts framework.Now bolts with pod files only but i am getting the below linker error attached in screenshot.

![screen shot 2016-06-23 at 1 30 39 pm](https://cloud.githubusercontent.com/assets/10229968/16295832/be421cda-3946-11e6-8c24-b591a0303da0.png)

**Comment by Raikerian** [comment]
Try to clear pods and reinstall them. If no luck, create a new clean test project and try it there.

**Comment by Raikerian** [comment]
@mallikaD were you able to fix this?
