### ISSUE TITLE
APNS Invalid Token

### ISSUE THREAD

**Issue by yishus** [QuickBlox/quickblox-ios-sdk#497]
Push notifications from both dashboard and chatalert are failing and shows up as `"error_code":8,"error_description":"Invalid token (8)"` on the push log. Have gotten a new cert and re-uploaded the .p12 file, unable to solve this issue.

**Comment by Raikerian** [comment]
Hi,

Please provide us your app id, so we can check server side logs.

**Comment by soulfly** [comment]
This can be because of wrong environments

make sure that your push subscription has the same zone you are trying to send a push from dashboard  to

**Comment by yishus** [comment]
@Raikerian app id is 37238

@soulfly i didn't really get what you mean. could you elaborate?

**Comment by yishus** [comment]
@Raikerian without doing anything, it started working haha. thanks!

**Comment by Raikerian** [comment]
If you are still having any other troubles, feel free to let us know by creating a separate issue.

**Comment by SurajPandey23** [comment]
getting the same error please @Raikerian  tell how to resolve my app id is:52498
