### ISSUE TITLE
Receive attachment in swift

### ISSUE THREAD

**Issue by xeravim** [QuickBlox/quickblox-ios-sdk#498]
**Environment details**
I just want to ask, why the hell is this 
http://quickblox.com/developers/SimpleSample-chat_users-ios#Receive_attachment 

failed when compiling, there is a lot of error in this swift syntax. Could you please gentlemen, help me to update the tutorial above so that i can copy and paste the syntax without asking them here??

      for attachment : QBChatAttachment in message.attachments as! [QBChatAttachment] {
        QBRequest.downloadFileWithID(UInt(attachment.ID.toInt()!), successBlock: {(response: QBResponse!, fileData: NSData!) in            var image: UIImage? = UIImage(data: fileData)
 
            }, statusBlock: {(request: QBRequest!, status: QBRequestStatus!) in
 
            }, errorBlock: {(response: QBResponse!) in
                NSLog("error: %@", response.error)
        })
    }

FYI, I did copy paste this chunk to your swift sample, and as you can guess. error.

**Comment by Raikerian** [comment]
Hi,

Thank you for reporting the issue, I have checked every swift code sample in a link you provided and updated it to the latest Swift syntax.

If you are still having any other troubles, feel free to let us know by creating a separate issue.
