### ISSUE TITLE
Cannot Delete Blob

### ISSUE THREAD

**Issue by ems305** [QuickBlox/quickblox-ios-sdk#50]
I am attempting to delete a blob without success. I read on some SO posts [Here](http://stackoverflow.com/questions/20545222/quickblox-an-issue-in-deleting-content-item-picture-file-blob) and [Here](http://stackoverflow.com/questions/21575360/quickblox-trying-to-update-user-and-set-blobid-to-zero-does-not-update) which mention you need to first set the blob to 0 and then delete the blob. Here is a simple piece of code and it does not work. I always get a 422 error, with NO error message when attempting to delete the blob. 

*I also came across the change log from version 1.8.3 which states:* 

QBUUser. blobID type changed to NSInteger. Now you can unset blob_id field of user - pass blob_id=-1

*This does not work either*

Any idea? Version 2.1

    ...

    NSInteger blobId = self.qbUser.blobID;
    self.qbUser.blobID = 0;
    
    [QBRequest updateUser:self.qbUser successBlock:^(QBResponse *response, QBUUser *user) {
        if (response.success) { // Always a Success
            [QBRequest deleteBlobWithID:blobId successBlock:^(QBResponse *response) {
                // Never Gets Here...
            } errorBlock:^(QBResponse *response) {
                // !!! Always Gets Here!!! 422 Error
            }];
        }
    } errorBlock:^(QBResponse *response) {
        // Doesn't Get Here Either...
    }];

**Comment by soulfly** [comment]
Please post exact error description 

    NSLog(@"Response error: %@", response.error);

**Comment by ems305** [comment]
@soulfly 

Here is the log of response.error:

    Error reasons:{
        errors =     {
        };
    }

**Comment by ems305** [comment]
@soulfly any update on this?

**Comment by AndreyMoskvin** [comment]
Sorry, use following snippet: 

    NSLog(@"Response error: %@", response.error.error);
