### ISSUE TITLE
IPv6 networks required

### ISSUE THREAD

**Issue by sertony** [QuickBlox/quickblox-ios-sdk#502]
I uploaded my app to AppStore and the build was rejected because all apps are reviewed on an IPv6 network since the 1st of June.

When they tried to connect QuickBlox SDK returned the following error:
Error Domain=NSPOSIXErrorDomain Code=51 "Network is unreachable" UserInfo={NSLocalizedDescription=Network is unreachable, NSLocalizedFailureReason=Error in connect() function}

Need help.

Here is some information I found which may help:
https://github.com/robbiehanson/XMPPFramework/issues/718

**Comment by Raikerian** [comment]
Hi @sertony 

Thank you for reporting the issue, we are now investigating it in a high priority and will post update as soon as possible.

**Comment by Raikerian** [comment]
@sertony we have pushed an update with version 2.7.2.1. The only change is this fix. Working good for us. Please let us know if it is also good for you.

**Comment by sertony** [comment]
@Raikerian thank you for a quick fix. I'll check it.

**Comment by Raikerian** [comment]
@sertony please let us know if you will be able to successfully publish your app.

**Comment by sertony** [comment]
@Raikerian yes, I will upload the build to iTunes today.

**Comment by sertony** [comment]
@Raikerian the build has been approved. Thanks!
