### ISSUE TITLE
Unable to sign up with same Facebook account on two different Apps on same account

### ISSUE THREAD

**Issue by prometheon** [QuickBlox/quickblox-ios-sdk#504]
This is a run-off of a previous issue I posted [here](https://github.com/QuickBlox/quickblox-ios-sdk/issues/493) . 

What's established is that one is not able to sign up with the same login on multiple different apps on a Quickblox account. This seems to be the same for Facebook sign in. 

1. I created an account with FB sign in through Quickblox on App A and changed the login to "fbtest".
2. I created an account with FB sign in on App B on the same FB account and changed the login to "fbtest2". 
3. There is now the same user in the User database for both App A **and** App B named "fbtest2".
4. I changed the display name of the user in App A and it also changed the display name for the user shown in App B. So the same user is listed in both apps.

Please implement unique login and FB authorization functionality between apps!

**Comment by Raikerian** [comment]
Hi,

Well, the answer is pretty much [same](https://github.com/QuickBlox/quickblox-ios-sdk/issues/493#issuecomment-223941816). Just create a different accounts for your test application.
