### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by mallikaD** [QuickBlox/quickblox-ios-sdk#507]
How to login from my app to quickblox? In sample code nearly 10 users are  there but in my app we have to login by default.In quickblox dashboard users are there.How we create that list? I am not able to understand the backend process and connectivity of quickblox to my app. Please help me out.Thank u

**Comment by mallikaD** [comment]
I wrote the code like this in viewdidLoad but it shows error.How i get this "ID","password","name",etc., 

    QBUUser *currentUser = [QBUUser user];
    currentUser.ID = 13452674;
    currentUser.password = @"test137";
    
    [[QBChat instance] connectWithUser:currentUser completion:^(NSError * _Nullable error) {
        NSLog(@"Error: %@", error);
    }];

## It shows error like below.It doesn't goes to success block.

 *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[QB_DDXMLElement attributeFloatValueForName:withDefaultValue:]: unrecognized selector sent to instance 0x7be43210'
*** First throw call stack:
(
	0   CoreFoundation                      0x04ba7494 __exceptionPreprocess + 180
	1   libobjc.A.dylib                     0x0465fe02 objc_exception_throw + 50
	2   CoreFoundation                      0x04bb1253 -[NSObject(NSObject) doesNotRecognizeSelector:] + 275
	3   CoreFoundation                      0x04ae689d ___forwarding___ + 1037
	4   CoreFoundation                      0x04ae646e _CF_forwarding_prep_0 + 14
	5   ConnectPro                          0x0037d47b QB_sortItems + 243454
	6   ConnectPro                          0x00386203 QB_sortItems + 279686
	7   ConnectPro                          0x0038b984 QB_sortItems + 302087
	8   libdispatch.dylib                   0x074a2363 _dispatch_call_block_and_release + 15
	9   libdispatch.dylib                   0x074c59cd _dispatch_client_callout + 14
	10  libdispatch.dylib                   0x074a963c _dispatch_queue_drain + 2227
	11  libdispatch.dylib                   0x074a8af0 _dispatch_queue_invoke + 570
	12  libdispatch.dylib                   0x074ab7a7 _dispatch_root_queue_drain + 550
	13  libdispatch.dylib                   0x074ab57a _dispatch_worker_thread3 + 115
	14  libsystem_pthread.dylib             0x0780c25c _pthread_wqthread + 1050
	15  libsystem_pthread.dylib             0x07809f56 start_wqthread + 34
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by VitaliyGuru** [comment]
@mallikaD Hi, 
**To be able to use QuickBlox API you have to create a user and be signed in.** 
So you should create user(via admin panel or application) and sign in.

**In order to use real time features you have to be logged in to Chat.**

Please refer to [this link](http://quickblox.com/developers/IOS#A_few_words_about_Authentication_and_Authorization) for additional information.

**Comment by VitaliyGuru** [comment]
@mallikaD Also you can take a look at our application  [Q-municate](https://github.com/QuickBlox/q-municate-ios) and at our [QMServices](https://github.com/QuickBlox/q-municate-services-ios).

 Q-municate is an open source code of chat application with full range of communication features on board using the Quickblox API.

QMServices are easy-to-use services for Quickblox SDK, for speeding up development of iOS chat applications. The main feature is high level API for Chat features including authentication service for logging to Quickblox REST and XMPP

**Comment by mallikaD** [comment]
Thank u @vitaliyGuru for your quick response. Actually i want to know that for chatting purpose every user have to signup and login thhrough quickblox again in the same app??

**Comment by mallikaD** [comment]
In my app we have a one tab view which contains chat module.so when i click that tab all the friends list will come. After select any of my friend i will able to chat with that friend. this is my funtionality to implement. So where i have to implement signup and login process? If i want to chat with my friend,is it mandatory to create user(via admin panel or application) for my friend also??

**Comment by mallikaD** [comment]
I wrote the code like this to signup for creating the user.

QBUUser *user = [QBUUser user];
    user.login = @"Mallika Test";
    user.password = @"123456";
    
    [QBRequest signUp:user successBlock:^(QBResponse *response, QBUUser *user) {
        // Success, do something
    } errorBlock:^(QBResponse *response) {
        // error handling
        NSLog(@"error: %@", response.error);
    }];

**It shows the below error**
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[QBRequest signUp:successBlock:errorBlock:]: unrecognized selector sent to class 0x5bce4c'
*** First throw call stack:
(
	0   CoreFoundation                      0x04ba1494 __exceptionPreprocess + 180
	1   libobjc.A.dylib                     0x04659e02 objc_exception_throw + 50
	2   CoreFoundation                      0x04bab0f3 +[NSObject(NSObject) doesNotRecognizeSelector:] + 275
	3   CoreFoundation                      0x04ae089d ___forwarding___ + 1037
	4   CoreFoundation                      0x04ae046e _CF_forwarding_prep_0 + 14
	5   ConnectPro                          0x00259812 -[ChatViewController viewDidLoad] + 226
	6   UIKit                               0x016abb72 -[UIViewController _sendViewDidLoadWithAppearanceProxyObjectTaggingEnabled] + 44
	7   UIKit                               0x016b0692 -[UIViewController loadViewIfRequired] + 1384
	8   UIKit                               0x016b0ab1 -[UIViewController view] + 35
	9   UIKit                               0x01711d33 -[UITabBarController _viewForViewController:] + 33
	10  UIKit                               0x0171e491 -[UITabBarController transitionFromViewController:toViewController:transition:shouldSetSelected:] + 606
	11  UIKit                               0x0171d3ae -[UITabBarController transitionFromViewController:toViewController:] + 76
	12  UIKit                               0x01718a7e -[UITabBarController _setSelectedViewController:] + 453
	13  UIKit                               0x01718885 -[UITabBarController setSelectedViewController:] + 252
	14  UIKit                               0x0171d1d9 -[UITabBarController _tabBarItemClicked:] + 587
	15  libobjc.A.dylib                     0x0466e0b5 -[NSObject performSelector:withObject:withObject:] + 84
	16  UIKit                               0x014e1e38 -[UIApplication sendAction:to:from:forEvent:] + 118
	17  UIKit                               0x014e1db7 -[UIApplication sendAction:toTarget:fromSender:forEvent:] + 64
	18  UIKit                               0x0193cfd3 -[UITabBar _sendAction:withEvent:] + 525
	19  libobjc.A.dylib                     0x0466e0b5 -[NSObject performSelector:withObject:withObject:] + 84
	20  UIKit                               0x014e1e38 -[UIApplication sendAction:to:from:forEvent:] + 118
	21  UIKit                               0x014e1db7 -[UIApplication sendAction:toTarget:fromSender:forEvent:] + 64
	22  UIKit                               0x01685f3b -[UIControl sendAction:to:forEvent:] + 79
	23  UIKit                               0x016862d4 -[UIControl _sendActionsForEvents:withEvent:] + 433
	24  UIKit                               0x01685f7b -[UIControl sendActionsForControlEvents:] + 48
	25  UIKit                               0x01942dc3 -[UITabBar(Static) _buttonUp:] + 123
	26  libobjc.A.dylib                     0x0466e0b5 -[NSObject performSelector:withObject:withObject:] + 84
	27  UIKit                               0x014e1e38 -[UIApplication sendAction:to:from:forEvent:] + 118
	28  UIKit                               0x014e1db7 -[UIApplication sendAction:toTarget:fromSender:forEvent:] + 64
	29  UIKit                               0x01685f3b -[UIControl sendAction:to:forEvent:] + 79
	30  UIKit                               0x016862d4 -[UIControl _sendActionsForEvents:withEvent:] + 433
	31  UIKit                               0x016852c1 -[UIControl touchesEnded:withEvent:] + 714
	32  UIKit                               0x0156252e -[UIWindow _sendTouchesForEvent:] + 1095
	33  UIKit                               0x015635cc -[UIWindow sendEvent:] + 1159
	34  UIKit                               0x01504be8 -[UIApplication sendEvent:] + 266
	35  UIKit                               0x014d9769 _UIApplicationHandleEventQueue + 7795
	36  CoreFoundation                      0x04ab3e5f __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 15
	37  CoreFoundation                      0x04aa9aeb __CFRunLoopDoSources0 + 523
	38  CoreFoundation                      0x04aa8f08 __CFRunLoopRun + 1032
	39  CoreFoundation                      0x04aa8846 CFRunLoopRunSpecific + 470
	40  CoreFoundation                      0x04aa865b CFRunLoopRunInMode + 123
	41  GraphicsServices                    0x0724d664 GSEventRunModal + 192
	42  GraphicsServices                    0x0724d4a1 GSEventRun + 104
	43  UIKit                               0x014dfeb9 UIApplicationMain + 160
	44  ConnectPro                          0x0028f20a main + 138
	45  libdyld.dylib                       0x074eaa25 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by VitaliyGuru** [comment]
@mallikaD  Have you added -lxml2, -ObjC, -lstdc++ flags to Other Linker Flags section in project settings?
Please, look through [this guide](https://quickblox.com/developers/IOS-how-to-connect-Quickblox-framework)

**Comment by mallikaD** [comment]
Can u please answer the above questions also @VitaliyGuru

**Comment by VitaliyGuru** [comment]
@mallikaD  Could you please attach here you test project with this crash.

**Comment by VitaliyGuru** [comment]
@mallikaD 

> So where i have to implement signup and login process?
It depends on you. In our samples and Q-municate whe use login screen as initial screen.
>  If i want to chat with my friend,is it mandatory to create user(via admin panel or application) for my friend also??
Yes. All users you want to chat with should exist in your application.

**Comment by mallikaD** [comment]
Actually without "-Objc" flag the program will run or not? In my app i used parse so when i placed "-Objc" it shows errors.so i want to know is "-Objc" is mandatory?

**Comment by VitaliyGuru** [comment]
@mallikaD , ObjC flag is mandatory.

Objective-C does not define linker symbols for each function (or method, in Objective-C) - instead, linker symbols are only generated for each class. If you extend a pre-existing class with categories, the linker does not know to associate the object code of the core class implementation and the category implementation. This prevents objects created in the resulting application from responding to a selector that is defined in the category.
To resolve this issue, the static library should pass the -ObjC option to the linker. This flag causes the linker to load every object file in the library that defines an Objective-C class or category. While this option will typically result in a larger executable (due to additional object code loaded into the application), it will allow the successful creation of effective Objective-C static libraries that contain categories on existing classes.

**Comment by VitaliyGuru** [comment]
@mallikaD  What specific errors did you get?

**Comment by mallikaD** [comment]
Yes. Gud explanation @VitaliyGuru .thank you so much. when i placed "-Objc" in other linker flags it gives 18 errors.I attached screen shot below.

![screen shot 2016-06-09 at 4 27 10 pm](https://cloud.githubusercontent.com/assets/10229968/15927402/29fc8246-2e5f-11e6-8cfb-0e90fca3b95d.png)

**Comment by VitaliyGuru** [comment]
Are you using PFTwitterUtils? In that case, add Social.framework. If Twitter SSO is being used, Accounts.framework and Twitter.framework might be needed too.

**Comment by mallikaD** [comment]
Yes i used PFTwitterUtils. I added all the 3 frameworks then it shows 15 errors.All twitter related errors are solved by adding those frameworks. All those are linker errors??  Here is the screenshot of linker error.

![screen shot 2016-06-09 at 5 01 12 pm](https://cloud.githubusercontent.com/assets/10229968/15928397/3aea9cd2-2e64-11e6-9ab4-f92e0b2a3f7e.png)

**Comment by VitaliyGuru** [comment]
Including 'libstdc++.6.dylib' framework as suggested AND making sure you add all the other frameworks to ALL TARGETS looks like will fix these issues.

**Comment by mallikaD** [comment]
@VitaliyGuru  thank u so much. When i added 'libstdc++.6.dylib' framework it shows only one error. Please can you help me out to solve this error also.

![screen shot 2016-06-09 at 5 20 06 pm](https://cloud.githubusercontent.com/assets/10229968/15928853/08a52b9a-2e67-11e6-8bdc-4fe05aa0ee6c.png)

**Comment by VitaliyGuru** [comment]
You're using two framerworks with identical methods. ParseFacebookUtils and ParseFacebookUtilsV4.
Try to remove  parseFacebookUtils.framework

**Comment by mallikaD** [comment]
Again it shows the linker error.Here duplicate for facebook and bolts framework. please see the below screenshot.
![screen shot 2016-06-09 at 5 37 11 pm](https://cloud.githubusercontent.com/assets/10229968/15929267/bf744a66-2e69-11e6-8fe2-7385291a22d2.png)

If i remove bolts framework it shows below 2 errors attached in below screenshot

![screen shot 2016-06-09 at 5 43 55 pm](https://cloud.githubusercontent.com/assets/10229968/15929279/cb0dd6f8-2e69-11e6-8f8c-f1483983c91a.png)

**Comment by VitaliyGuru** [comment]
Could you please show me your podfile?
Which way have you added the frameworks?

**Comment by mallikaD** [comment]
I am not used the pod files. Through drag and drop i used the frameworks.This is the screenshot of frameworks.
![screen shot 2016-06-09 at 5 56 45 pm](https://cloud.githubusercontent.com/assets/10229968/15929598/91a43eaa-2e6b-11e6-8556-5525bb934477.png)

**Comment by VitaliyGuru** [comment]
Instead of adding the Bolts.framework and FacebookSDK.framework as framework to your project, add them as Pods:

pod 'Bolts'
pod 'Facebook-iOS-SDK'

**Comment by mallikaD** [comment]
I used pods in my project. Duplicate errors are solved but it shows These two errors attached in screenshot.Please help me out @VitaliyGuru  

![screen shot 2016-06-09 at 7 04 03 pm](https://cloud.githubusercontent.com/assets/10229968/15931477/87835d70-2e75-11e6-99e2-099574a51974.png)

**Comment by VitaliyGuru** [comment]
@mallikaD  Please try some of the approaches from [this link](http://goo.gl/CzEfpn)

**Comment by mallikaD** [comment]
Ok.I added the quickblox library to binary libraries and also i took bolts from pod file.It shows below error.
![screen shot 2016-06-10 at 10 38 11 am](https://cloud.githubusercontent.com/assets/10229968/15954824/3e91265e-2ef9-11e6-8e32-21a8d5362801.png)

**Comment by VitaliyGuru** [comment]
> also i took bolts from pod file

Could you be more specific about this?

**Comment by mallikaD** [comment]
I took bolts framework without pod then it shows 75 duplicate files with facebook sdk, which i mentioned above.If i took bolts framework with pods then it compiles without error but at run time it shows exception in debugger like below

**Error is**
objc[8958]: Class BFAppLinkNavigation is implemented in both /Users/hemant/Library/Developer/CoreSimulator/Devices/10B159F0-EE88-45E0-9A77-2877275D5E8E/data/Containers/Bundle/Application/80230CE7-245C-4161-BBE7-136F99234C1E/ConnectPro.app/Frameworks/Bolts.framework/Bolts and /Users/hemant/Library/Developer/CoreSimulator/Devices/10B159F0-EE88-45E0-9A77-2877275D5E8E/data/Containers/Bundle/Application/80230CE7-245C-4161-BBE7-136F99234C1E/ConnectPro.app/ConnectPro. One of the two will be used. Which one is undefined.
objc[8958]: Class BFAppLinkReturnToRefererView is implemented in both /Users/hemant/Library/Developer/CoreSimulator/Devices/10B159F0-EE88-45E0-9A77-2877275D5E8E/data/Containers/Bundle/Application/80230CE7-245C-4161-BBE7-136F99234C1E/ConnectPro.app/Frameworks/Bolts.framework/Bolts and /Users/hemant/Library/Developer/CoreSimulator/Devices/10B159F0-EE88-45E0-9A77-2877275D5E8E/data/Containers/Bundle/Application/80230CE7-245C-4161-BBE7-136F99234C1E/ConnectPro.app/ConnectPro. One of the two will be used. Which one is undefined.
2016-06-10 14:13:08.192 ConnectPro[8958:96616] [QBCore] Request DNS chat.quickblox.com:5222 [connectivity-1]
2016-06-10 14:13:08.257 ConnectPro[8958:96348] +[BFTask taskFromExecutor:withBlock:]: unrecognized selector sent to class 0x7b3ff4
2016-06-10 14:13:08.390 ConnectPro[8958:96348] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[BFTask taskFromExecutor:withBlock:]: unrecognized selector sent to class 0x7b3ff4'
*** First throw call stack:
(
	0   CoreFoundation                      0x05568494 __exceptionPreprocess + 180
	1   libobjc.A.dylib                     0x05020e02 objc_exception_throw + 50
	2   CoreFoundation                      0x055720f3 +[NSObject(NSObject) doesNotRecognizeSelector:] + 275
	3   CoreFoundation                      0x054a789d ___forwarding___ + 1037
	4   CoreFoundation                      0x054a746e _CF_forwarding_prep_0 + 14
	5   ConnectPro                          0x00560b7d +[PFFileManager createDirectoryIfNeededAsyncAtPath:withOptions:executor:] + 148
	6   ConnectPro                          0x005626ea -[PFFileManager parseLocalSandboxDataDirectoryPath] + 248
	7   ConnectPro                          0x005625da -[PFFileManager parseDefaultDataDirectoryPath] + 542
	8   ConnectPro                          0x005629aa -[PFFileManager parseDataItemPathForPathComponent:] + 130
	9   ConnectPro                          0x005a5abe +[PFInternalUtils checkCacheApplicationId] + 123
	10  ConnectPro                          0x005ce375 +[Parse setApplicationId:clientKey:] + 185
	11  ConnectPro                          0x00186674 -[AppDelegate application:didFinishLaunchingWithOptions:] + 612
	12  UIKit                               0x027b818c -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 337
	13  UIKit                               0x027b96a8 -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:] + 3863
	14  UIKit                               0x027c0f0f -[UIApplication _runWithMainScene:transitionContext:completion:] + 2010
	15  UIKit                               0x027e6b2c __84-[UIApplication _handleApplicationActivationWithScene:transitionContext:completion:]_block_invoke3246 + 68
	16  UIKit                               0x027bdb8a -[UIApplication workspaceDidEndTransaction:] + 163
	17  FrontBoardServices                  0x07c31110 __37-[FBSWorkspace clientEndTransaction:]_block_invoke_2 + 71
	18  FrontBoardServices                  0x07c30be7 __40-[FBSWorkspace _performDelegateCallOut:]_block_invoke + 54
	19  FrontBoardServices                  0x07c4e27f __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 23
	20  FrontBoardServices                  0x07c4e0ab -[FBSSerialQueue _performNext] + 174
	21  FrontBoardServices                  0x07c4e4fa -[FBSSerialQueue _performNextFromRunLoopSource] + 52
	22  FrontBoardServices                  0x07c4d7e8 FBSSerialQueueRunLoopSourceHandler + 33
	23  CoreFoundation                      0x0547ae5f __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 15
	24  CoreFoundation                      0x05470aeb __CFRunLoopDoSources0 + 523
	25  CoreFoundation                      0x0546ff08 __CFRunLoopRun + 1032
	26  CoreFoundation                      0x0546f846 CFRunLoopRunSpecific + 470
	27  CoreFoundation                      0x0546f65b CFRunLoopRunInMode + 123
	28  UIKit                               0x027bd2da -[UIApplication _run] + 540
	29  UIKit                               0x027c2eb9 UIApplicationMain + 160
	30  ConnectPro                          0x002696da main + 138
	31  libdyld.dylib                       0x06af2a25 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by VitaliyGuru** [comment]
`Looks like you need to update your Facebook SDK. Go directly to developer.facebook.com, download the SDK and copy over the FacebookSDK and the Bolts framework. You should be set after that.

**Comment by VitaliyGuru** [comment]
And please, clean your project and derived data before every new launch of the application.

**Comment by mallikaD** [comment]
Actually i took bolts framework using pods.But it shows 2 paths and saying that "One of the two will be used. Which one is undefined."  and says unrecognized selector.

 *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[BFTask taskFromExecutor:withBlock:]: unrecognized selector sent to class 0x7b3ff4'
*** First throw call stack:
(
0 CoreFoundation 0x05568494 exceptionPreprocess + 180

**Comment by VitaliyGuru** [comment]
@mallikaD Try to update parse framework or move all frameworks to podfile.
 It's difficult for me to solve your issues 'cause I don't see your project and I make decisions only with  your help and my experience.

**Comment by mallikaD** [comment]
If i want to share my project. can i attach it here or anywhere?

**Comment by VitaliyGuru** [comment]
You can use my email if you project is private.

**Comment by VitaliyGuru** [comment]
@mallikaD  Any updates?

**Comment by mallikaD** [comment]
hi @VitaliyGuru ! Actually we stopped the development for some days.now again started the implementation.Actually i want to know is "i have a friends list in my app.how can i connect that friends list to quickblox? I want to chat with my friends in the app using quickblox".How can i proceed? Im totally confused by seeing the sample app.

**Comment by mallikaD** [comment]
yes.I totally removed the parse framework then its working fine.

**Comment by VitaliyGuru** [comment]
@mallikaD  I'm glad to hear that you resolved this.
