### ISSUE TITLE
Apple Non public API Issue

### ISSUE THREAD

**Issue by umarchohan** [QuickBlox/quickblox-ios-sdk#508]
Hi , I tried to upload my app for beta testing and got this reply from Apple.
"
Dear developer,

We have discovered one or more issues with your recent delivery for "App name". To process your delivery, the following issues must be corrected:

Non-public API usage:

The app references non-public selectors in App name: sendMessage
If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed.
"

There is a conflict due to name of Apple sendMessage function signature and Quickblox sendMessage signtaure. I cannot rename the function for sending message so what shall I do ? Can you change the function signature for "- (void)sendMessage:(QB_NONNULL QBChatMessage *)message completionBlock:(QB_NULLABLE_S QBChatCompletionBlock)completion;
"

Regards

**Comment by VitaliyGuru** [comment]
Hi @umarchohan ,
How do you use sendMessage method?
Do you use `performSelector`?

**Comment by umarchohan** [comment]
Hi @VitaliyGuru  no I did not use performSelector, here is my code from app.

  [self.dialog sendMessage:msg completionBlock:^(NSError * _Nullable error)
         {
             if (error == nil)
             {
                 message.messageID = msg.ID;
                 
                 [self.dataModel.messages addObject:message];
                 
                 [self sendPushforTextMessage];
                 
                 [lastMessages addObject:msg];
                 [self finishSendingMessageAnimated:YES];
             }
             else
             {
                 NSLog(@"Error..%@",error);
             }
         }];

**Comment by VitaliyGuru** [comment]
@umarchohan It looks strange. 
Some days ago we released new app on the AppStore and it passed the review. 
We will investigate this issue. FYI we don't use beta testing.

**Comment by umarchohan** [comment]
Yes sure you can investigate the issue. I wonder how your app got approved. You know if it beta testing on testflight or you need to make the app live you must upload this to itunes connect. Thats what I am doing but apple is not accepting the build I upload.

**Comment by VitaliyGuru** [comment]
@umarchohan  I've found some solutions.
1. Try delete all derived data for xcode project
2. Try to submit binary using Application Loader

**Comment by umarchohan** [comment]
Ok I shall try this and let you know @VitaliyGuru

**Comment by VitaliyGuru** [comment]
@umarchohan  Any updates?
FYI yesterday we added our another build for review and today it passed without any problems.

**Comment by umarchohan** [comment]
@VitaliyGuru  I have deleted derived data and now creating the build lets see what happens?
Thanks for you support :)

**Comment by umarchohan** [comment]
@VitaliyGuru no success bro... still same ... please recommend something else ..

**Comment by VitaliyGuru** [comment]
@umarchohan Have you tried to upload using Application Loader?

**Comment by umarchohan** [comment]
Yes I uploaded using Application Loader

**Comment by VitaliyGuru** [comment]
Do you use the latest XCode version?

**Comment by umarchohan** [comment]
yes it is Xcode 7.3

**Comment by Raikerian** [comment]
What is your SDK version?
If it is latest SDK, the only thing you can do for now is to open appeal on apple itunes connect, describe them the situation about method usage, that it is not some kind of a private API, but our SDK custom class. Also check that you are not calling any performSelector things.

We have successfully released our Q-municate update yesterday without any problems.

**Comment by umarchohan** [comment]
hi @VitaliyGuru 
I have sent itunes mail 3 times but they don't solve the problem.

**Comment by Raikerian** [comment]
@umarchohan what was the answer on your emails and what was your email content?

**Comment by Raikerian** [comment]
@umarchohan have you used [this form](https://developer.apple.com/contact/app-store/?topic=appeal) to open appeal?

**Comment by Raikerian** [comment]
@umarchohan have you used [this form](https://developer.apple.com/contact/app-store/?topic=appeal) to open appeal?
Also, I do not see any answer in your post, have you got any answers from Apple?

**Comment by umarchohan** [comment]
@Raikerian yes I have used the same platform...

**Comment by Raikerian** [comment]
So, what was the answer?

**Comment by umarchohan** [comment]
Actually I sent them a support ticket on my behalf.They said that I have to use the same email as on itunes to send the support ticket. So let me send one and I shall get back to you.

Thanks

**Comment by Pro100Andrey** [comment]
Hi @umarchohan - Any Updates?

**Comment by umarchohan** [comment]
hi @VitaliyGuru ..
I have not received any reply yet from Apple.

Thanks for asking

**Comment by umarchohan** [comment]
Hi @Pro100Andrey  I have not received any reply from Apple.

**Comment by umarchohan** [comment]
@VitaliyGuru 
Here is what Apple has to say about the issue..


Thank you for contacting the App Store Review Team.

This issue can occur if an app calls names that are similar to or directly calls our non-public APIs. It would be appropriate to remove all references to the listed selectors before resubmitting this app for review. We recommend that you use the "nm" tool or the command line tools "strings" or "otool -ov" to find the entities that are causing this rejection.

scott
App Store Review



My Message:

Hello Apple Support,
 
I am trying to upload an app for beta testing in itunes connect but it is been rejected. 
My App ID is Apple ID: **********
 
The rejection is due to follwing
Non-public API usage:
 
The app references non-public selectors in App Name: sendMessage
 
 
 
I need to tell you that I am using QuickBlox chat SDK for implementation of chat service in this app. The call sendMessage is one of the SDK Class function which is not public. So I cannot change the function signaure. Whats the solution now please? 
 
Kindly guide me.

**Comment by umarchohan** [comment]
Hi @VitaliyGuru  have you checked out the apple reply ?
Can you guide me now ?

Regards

**Comment by Raikerian** [comment]
> We recommend that you use the "nm" tool or the command line tools "strings" or "otool -ov" to find the entities that are causing this rejection.

Have you tried this? It can be possibly not Quickblox related issue.

**Comment by umarchohan** [comment]
@VitaliyGuru  No I see this is a command that tells where issue lies ...

**Comment by Raikerian** [comment]
@umarchohan Indeed, so where does it take you at?

**Comment by Raikerian** [comment]
@umarchohan if you are still experiencing this issue, just reopen it. If you are having any other troubles, let us know by creating a separate one.

**Comment by umarchohan** [comment]
I am currenlty facing this issue. Will let you know sometime later
