### ISSUE TITLE
logInWithUser:quickBloxUser

### ISSUE THREAD

**Issue by luka1995** [QuickBlox/quickblox-ios-sdk#509]
Hi, We upload app to AppStore but apple reject app because stuck in quickblox method on IPv6 network.

Please how can we fix it?

And maybe it is not problem only with this method...

[[QMServicesManager instance] logInWithUser:quickBloxUser completion:^(BOOL success, NSString * _Nullable errorMessage) {

<img width="824" alt="screen shot 2016-06-10 at 15 10 48" src="https://cloud.githubusercontent.com/assets/3648001/15965798/4e14035e-2f20-11e6-8fd1-647ffde510fa.png">

**Comment by VitaliyGuru** [comment]
@luka1995 We added IPv6 support in QBSDK v2.7.2.1. Now v 2.7.3 is available.

**Comment by luka1995** [comment]
@VitaliyGuru I know, because i have 2.7.3, but stuck on [QMServicesManager instance] logInWithUser, what can be?

**Comment by luka1995** [comment]
Fixed! I added parameters to info.plist
<img width="196" alt="screen shot 2016-06-10 at 16 19 27" src="https://cloud.githubusercontent.com/assets/3648001/15967250/29ccd71c-2f27-11e6-87ec-2907bcb7959f.png">
:
