### ISSUE TITLE
Trouble uploading video files

### ISSUE THREAD

**Issue by mitchellporter** [QuickBlox/quickblox-ios-sdk#51]
I was able to successfully upload several videos earlier today, but for the past 4 hours I have not been able to upload any. The new file shows up in the Content module, but it just gets stuck at a status of "Not uploaded."

In Xcode while the app is running the CPU hovers around 97-99%. Here's the code I'm using:

```Objective-C
[QBRequest TUploadFile:[NSData dataWithContentsOfURL:movieURL] fileName:@"mynewvideo" contentType:@"video/quicktime" isPublic:YES successBlock:^(QBResponse *response, QBCBlob *blob) {
                NSUInteger uploadedFileID = blob.ID;
             
            } statusBlock:^(QBRequest *request, QBRequestStatus *status) {
                // handle progress
                NSLog(@"progress");

            } errorBlock:^(QBResponse *response) {
                NSLog(@"error: %@", response.error);
            }];
```
The success block never fires. The status block never fires, and the failure block never fires either. I've kept the app running for 10 minutes now and it's just stuck trying to upload the video file to Quickblox.

**Comment by soulfly** [comment]
//CPU hovers around 97-99%

that sounds strange

Please post Xcode logs of QB SDK

**Comment by mitchellporter** [comment]
It's not happening anymore, the next day the issue was no longer happening.

I just sent an email to both enterprise and assist to see if it would be in our best interest to upgrade our plan. 

Looking forward to hearing back from you guys thanks.
