### ISSUE TITLE
<QBRTCClient  delegates[X]>  Stack Up 

### ISSUE THREAD

**Issue by shanmarkus** [QuickBlox/quickblox-ios-sdk#512]
*Help avoid duplicate issue reports, check [existing issues](https://github.com/QuickBlox/quickblox-ios-sdk/issues)*
 
**Environment details**
Quickblox-WebRTC', '~> 2.2'
Apple Swift version 2.2

**Did this work before?**

**Expected behavior**
QBRTClient delegates will gone after calling
QBRTCClient.instance().removeDelegate(self)

**Actual behavior**
QBRTClient Stack up every time i receive call from QB Web

**Logs**

*Attach full logs that will describe your problem 
https://gist.github.com/shanmarkus/032693e4ca6563519c253cb40a260339

**Comment by shanmarkus** [comment]
and i also realize that my VC does not get dealloc

**Comment by Pro100Andrey** [comment]
Hi @shanmarkus, QBMulticastDelegte is [NSHashTable hashTableWithOptions:NSPointerFunctionsWeakMemory];  Please check http://stackoverflow.com/questions/24042949/block-retain-cycles-in-swift

**Comment by VitaliyGuru** [comment]
@shanmarkus  Have you got a chance to check your code for retain cycles?

**Comment by shanmarkus** [comment]
sorry @VitaliyGuru and @Pro100Andrey i have not try it yet since my client already satisfy with the prototype that i made. 

But hey, thank you so much your answer. Really appreciate it. 

Cheers
