### ISSUE TITLE
Can't install QMChatViewController

### ISSUE THREAD

**Issue by astanton** [QuickBlox/quickblox-ios-sdk#513]
I'm having issues installing this either via pods or via the manual instructions.

When I try via pods, I get the transitive dependencies error:

`[!] The 'Pods' target has transitive dependencies that include static binaries: (/ios/Pods/QuickBlox/Quickblox.framework)`

When I try to install it manually, by copying the directory to my project and linking with target, and installing the other Pods, when I go to compile, the QMViewChatController code can't find any of the header files for the required pods, and I get errors like the following:

`'TTTAttributedLabel.h' file not found`

The pods are successfully installed with no issues too (the TTAttributedLabel and SDWebImage ones) and those files are clearly in my project.  I tried adding those files to my bridge header file since this is in swift, and that isn't making any difference either, still having the errors.

I'm trying to add the QMViewChatController.h to my bridge file so I can access it in my classes, but when I do that, I am getting these errors so I can't compile and use it with it added to my project currently.

Any ideas?

**Comment by VitaliyGuru** [comment]
@astanton Hi, we have [separate](https://github.com/QuickBlox/QMChatViewController-ios) repo for questions relating to QMChatViewController. Could you create and open this issue again there?
