### ISSUE TITLE
Issues deleting QB custom object - 403 error

### ISSUE THREAD

**Issue by shalem93** [QuickBlox/quickblox-ios-sdk#514]
*Help avoid duplicate issue reports, check [existing issues](https://github.com/QuickBlox/quickblox-ios-sdk/issues)*
 
**Environment details**
*iOS version, Quickblox iOS SDK version, QuickbloxWebRTC SDK version (optional)*

**Did this work before?**
No

**Expected behavior**
I would like to be able to delete this custom object upon refreshing the tableview as long as it fits the for loops criteria.

**Actual behavior**
The code runs, but I receive a "Response Error: [QBResponse], status: 403"

**Logs**
*Attach full logs that will describe your problem (please, use github [gist](https://gist.github.com/))*
Logs are as follows: 
" -601837.739584
2016-06-12 18:18:07.739 XpandU[18498:1154594] -616709.739852
2016-06-12 18:18:07.740 XpandU[18498:1154594] -2740042.740067
2016-06-12 18:18:07.740 XpandU[18498:1154594] -706285.740614
2016-06-12 18:18:07.740 XpandU[18498:1154594] -599877.740917
2016-06-12 18:18:07.742 XpandU[18498:1154594] CONNECTION LOG refreshTopicParticipants
2016-06-12 18:18:07.742 XpandU[18498:1154594] CONNECTION LOG getUniversities
2016-06-12 18:18:07.924 XpandU[18498:1154594] Response zerror: [QBResponse], status: 403 "

**Steps to reproduce the behavior**
Refresh my table view. Once table view refreshes, a if statement runs, checking if the object meets certain criteria (whether time elapsed exceeds two hours) , if it does, it runs the delete method, and returns an error.

**Any others comments?**
 Here is our code:
 -(void) refreshTableview
{
    NSInteger i = 0;

    while (i < ([DataStore instance].arrTopics.count)) {
        
    
    
    QBCOCustomObject *topic = [DataStore instance].arrTopics[i];

    NSTimeInterval timeInterval = [topic.createdAt timeIntervalSinceNow];
        
    
        if ((timeInterval < (-7200)) && ([topic.fields objectForKey:@"totalCallCount"] == nil)){
        
        [QBRequest deleteObjectWithID:topic.ID className:kQBClassTopics successBlock:^(QBResponse *response) {
            // object deleted
            
        } errorBlock:^(QBResponse *error) {
            // error handling
            NSLog(@"Response error: %@", [error description]);
        }];
    }
        i++ ;
    }
    
    
    [AppDelegate refreshTopicParticipantsSuccess:^{
            [self.tableView reloadData];
            [refreshControl endRefreshing];
    }];
    
}

**Comment by shalem93** [comment]
Any updates?

**Comment by VitaliyGuru** [comment]
@shalem93 ,
In brief:
Owners always have access to their own records. If you want to delete object by another user you should crea records with Permissions.

Please, take a look at [this guide for edit permissions by the code](http://quickblox.com/developers/SimpleSample-customObjects-ios#Permissions) and at [this guide for changing permission level via Admin Panel](http://quickblox.com/developers/Custom_Objects#Permission_levels).

**Comment by VitaliyGuru** [comment]
@shalem93  Have we resolved your issue?

**Comment by shalem93** [comment]
Yes issue is resolved!

**Comment by mayurdhvaj11** [comment]
Hi,

I have implemented quickblox in both mobile side and admin side(PHP).

In Quickblox, I want to delete dialogues from admin panel. I can delete those dialogues which are created from admin side. But, not able to delete dialogues which are created from mobile side.

I want to delete all dialogues dialogues from admin side whether I am owner of that dialogue or not. 

Please provide me solution on above issue

Thanks,
Mayur
