### ISSUE TITLE
Chat message are not receiving after reconnecting 

### ISSUE THREAD

**Issue by rawat555** [QuickBlox/quickblox-ios-sdk#52]
I have problem with sending messages after reconnecting with the quickblox server.If I disconnect my internet from device then again reconnect, the chat messages is not sending. But the log shown it was sent , not showing the receive log. The reconnect code works fine but cannot chat anymore.

when it was working as fine,

2013-10-12 10:48:37.033 football365[1000:8517] -[QBChat xmppStream:didSendMessage:] ->              Message: <message to="4099_000000001000000003@muc.chat.quickblox.com" id="7" type="groupchat"><body>hello</body></message>
2013-10-12 10:48:37.463 football365[1000:8517] -[QBChat xmppRoom:didReceiveMessage:fromNick:] -> message: <message xmlns="jabber:client" type="groupchat" to="578338-4099@chat.quickblox.com/tigase-11258" from="4099_000000001000000003@muc.chat.quickblox.com/578338"><body>hello</body></message> fromNick: 578338
when message only sent, the received log is not shown.

2013-10-12 10:48:37.033 football365[1000:8517] -[QBChat xmppStream:didSendMessage:]

**Comment by soulfly** [comment]
What is the reconnect code ?

**Comment by rawat555** [comment]
//Check Internet connection
-(void)checkInternetConnection:(NSNotification*)notification
{
    if ([reachability currentReachabilityStatus] != NotReachable)
    {
        //Re login into QuickBlocks Chat
        [self.view makeToast:@"re connecting" duration:3.0f position:CSToastPositionCenter];
        [self chatLoginSetup];
        [[ChatService instance] customeInit];
    }
    else
    {
        [self.view makeToast:@"Please check your internet Connection" duration:3.0f position:CSToastPositionCenter];
    }
}




-(void)chatLoginSetup
{
    
    [activityIndicatorView setHidden:NO];
    [activityIndicatorView startAnimating];
    
    self.sendMessageButton.alpha = .70f;
    self.sendMessageButton.userInteractionEnabled = NO;
    
    if([[QBChat instance] isLoggedIn])
    {
        [self goToChatRoomIfuserAlreadyLoggedIN];
    }
    else
    {    //log in User
        ChatLogIN *chatLogin = [[ChatLogIN alloc]init];
        chatLogin.chatLoginDelegate = self;
        [chatLogin enterIntoChatroomWithUser:ownUserName password:ownUserPassWord];
    }
}

-(void)successLoginIntoChat:(BOOL)status
{

//chat login delegate

//Yes for success 
//No for failed
    if (status)
    {
        [self goToChatRoomIfuserAlreadyLoggedIN];
    }
    else
    {
        [self.view makeToast:@"There is some technical problem in group chat please try later" duration:3.0f position:CSToastPositionCenter];
         activityIndicatorView.hidden = YES;
    }
}


-(void)goToChatRoomIfuserAlreadyLoggedIN
{
    if (self.dialog ==nil)
    {
        NSMutableDictionary *extendedRequest = [NSMutableDictionary new];
        extendedRequest[@"limit"] = @(100);
        [QBChat dialogsWithExtendedRequest:extendedRequest delegate:self];
    }
    else
    {
        if (self.chatRoom.isJoined)
        {
            self.sendMessageButton.alpha = 1.0f;
            self.sendMessageButton.userInteractionEnabled = YES;
        } 
        else
        {
            [self joinChatRoom];
        }
    }
}

-(void)joinChatRoom
{
    QBChatRoom *room1 = self.dialog.chatRoom;
    self.chatRoom = room1;
    
    [self join];
}

-(void)join
{
    NSLog(@"chat room identity %@",self.chatRoom);
    
    [[ChatService instance] joinRoom:self.chatRoom completionBlock:^(QBChatRoom *joinedChatRoom) {
        
        if (self.chatRoom.isJoined)
        {
            [self.view makeToast:@" chat room Successs" duration:3.0f position:CSToastPositionCenter];
            self.sendMessageButton.alpha = 1.0f;
            self.sendMessageButton.userInteractionEnabled = YES;
            
            [activityIndicatorView stopAnimating];
            [activityIndicatorView removeFromSuperview];
        }
        
        
        if (self.dialog.chatRoom.isJoined)
        {
            [self.view makeToast:@" dialog chat room Successs" duration:3.0f position:CSToastPositionCenter];
            self.sendMessageButton.alpha = 1.0f;
            self.sendMessageButton.userInteractionEnabled = YES;
            
            [activityIndicatorView stopAnimating];
            [activityIndicatorView removeFromSuperview];
        }
        
        else
        {
        //[self.view makeToast:@"Connected" duration:3.0f position:CSToastPositionCenter];
            [activityIndicatorView stopAnimating];
            [activityIndicatorView removeFromSuperview];
        }
    }
     ];

**Comment by soulfly** [comment]
Could you also add the whole Xcode log where internet goes down and back and then you send messages
