### ISSUE TITLE
Update read message status even without client code requested it.

### ISSUE THREAD

**Issue by matrosovDev** [QuickBlox/quickblox-ios-sdk#520]
Hi guys! New issue with unread messages.

As I found in the project the next methods:

`- (void)readMessage:(QBChatMessage *)message completion:(QBChatCompletionBlock)completion`

`- (void)readMessages:(NSArray *)messages forDialogID:(NSString *)dialogID completion:(QBChatCompletionBlock)completion`

`- (BFTask *)readMessages:(NSArray *)messages forDialogID:(NSString *)dialogID`

So I debugged this method but we never call this messages, but by some reason (I don't know somehow) we mark message as read.

So I use `ChatViewController` and there is one place where we call readMessage method. But even before initialization `ChatViewController` my messages were marked as read.

I sent a message from user A to user B.

I press home button and disconnect all chats on user B that has one unread message. Then I renter to app and try to get all dialogs:

`QMServicesManager.instance().chatService.allDialogsWithPageLimit` and doing this few times cause an issue with reseting unread messages for latest dialog.

I use pods:
> pod 'QMChatViewController', '~> 0.3.7'
> pod 'QMServices', '0.4'
> pod 'QuickBlox', '2.7.2'
> 

Your demo use another pods:

> platform :ios, "7.0"
> 
> pod 'SVProgressHUD', '~> 1.1.3'
> 
> #Production pod
> pod 'QMCVDevelopment', :git => 'git@github.com:QuickBlox/QMChatViewController-ios.git', :commit => 'ac7ae17689e75f0554706447d19f2851fc46dc54'
> 
> #For development pods
> #pod 'QMCVDevelopment', :path => '../../QMChatViewController-ios/'
> 
> #Production pod
> pod 'QMServicesDevelopment', :git => 'git@github.com:QuickBlox/q-municate-services-ios.git', :commit => '2eb283ee18896182379a8a046d95f8b12362af73'
> #For development pods
> #pod 'QMServicesDevelopment', :path => '../../q-municate-services-ios/'
> 
> pod 'SearchEmojiOnString'

**Comment by matrosovDev** [comment]
As I found out more. When I sent 5 messages to use A, and use A try to get all dialogs one more time, the dialog decreases unread messages by one each time.

So each new get all dialogs decrease by one (5, 4, 3 and etc) =)

**Comment by VitaliyGuru** [comment]
Hi @matrosovDev , We will investigate this issue and behaviour. We appreciate your help and attention to details.

**Comment by matrosovDev** [comment]
Hey guys, have you chance to check that issue? Thanks

**Comment by VitaliyGuru** [comment]
@matrosovDev  Are you sure that you don't call this method?
```smalltalk
+ (QB_NONNULL QBRequest *)messagesWithDialogID:(QB_NONNULL NSString *)dialogID
                                  successBlock:(QB_NULLABLE void(^)(QBResponse * QB_NONNULL_S response, NSArray QB_GENERIC(QBChatMessage *) * QB_NULLABLE_S messages))successBlock
                                    errorBlock:(QB_NULLABLE QBRequestErrorBlock)errorBlock;
```
By default all messages retrieved from server are marked as read, if you need another behaviour please use mark_as_read parameter in extendedParameters dictionary.

**Comment by matrosovDev** [comment]
Hi Vitaliy, thanks for response I really appreciate your help!

I just use this method to get all messages from memory storage:
`QMServicesManager.instance().chatService.messagesMemoryStorage.messagesWithDialogID(dialog.ID!)`

But I just invoke it when I show chat view controller.  But the problem that by some reason something clear unread messages for latest dialog even without opening chat view controller. I am not sure why, but there is no extra calls to QB library.

If it will help I can share logic how it works on my side. I can explain step by step what I did or maybe even upload my test project with my changes.

**Comment by VitaliyGuru** [comment]
Please, upload test build with your custom changes.

**Comment by matrosovDev** [comment]
do you mean a build or a project?

**Comment by VitaliyGuru** [comment]
@matrosovDev  project

**Comment by matrosovDev** [comment]
ok I will prepare test project and will share a link to it.

**Comment by matrosovDev** [comment]
Let me add also comment to it, so I will add comments `// CustomizedQuickBlox Step 1. Getting P2P chat` ok kind like that, so you will see how I implemented all steps.

I guess it should simplify navigation trough my sources.

Thank you!

**Comment by matrosovDev** [comment]
Sorry, unfortunately I can't share my work project with you, but I can try to prepare new test one.

One problem I faced with new one, when I did pod install and load needed libraries it says that I can't use objective-c files and seems I can't use `use_frameworks!` flag. Do you have any link how can I bind objective c files downloaded from cocoa pods and bind it with my swift project.

I am talking about bridging I guess.

Thanks

**Comment by matrosovDev** [comment]
Added an question here: http://stackoverflow.com/questions/37949524/cocoa-pods-objective-c-files-in-swift-project-bridging-issue

thanks for help

**Comment by VitaliyGuru** [comment]
@matrosovDev  please refer to [this documentation](http://quickblox.com/developers/IOS-how-to-connect-Quickblox-framework#Additional_steps_for_Swift_using_CocoaPods)

**Comment by matrosovDev** [comment]
Not sure, but maybe UIApplicationExitsOnSuspend can lead some issues?

I found that your demo project uses:
```
func applicationWillTerminate(application: UIApplication) {
        // Logging out from chat.
        ServicesManager.instance().chatService.disconnectWithCompletionBlock(nil)
    }
```

Not sure that force closing app call this method.

**Comment by matrosovDev** [comment]
By the way, creating demo project! thanks for the link, it's helpful!

**Comment by matrosovDev** [comment]
Also guys, I want to check API request using CURL, but got this issue:
http://stackoverflow.com/questions/37887048/quick-blox-signature-generation-issue

can you check it?

**Comment by Pro100Andrey** [comment]
Hi @matrosovDev, please check http://stackoverflow.com/questions/37887048/quick-blox-signature-generation-issue

**Comment by matrosovDev** [comment]
thanks appreciate your help! I answered on it.

**Comment by Pro100Andrey** [comment]
@matrosovDev please check issue in your repo, and remove my skype)

**Comment by Raikerian** [comment]
@matrosovDev if you are still experiencing this issue, just reopen it. If you are having any other troubles, let us know by creating a separate one.
