### ISSUE TITLE
Connecting friends list in app to quickblox

### ISSUE THREAD

**Issue by mallikaD** [QuickBlox/quickblox-ios-sdk#526]
Actually i want to know is "i have a friends list in my app.How can i connect that friends list to quickblox? I want to chat with my friends in the app using quickblox".How can i proceed? Im totally confused by seeing the sample app.I added quickblox framework successfully and also created in quickblox dashboard also.

**Comment by VitaliyGuru** [comment]
@mallikaD If you want to chat with friends and see 'em in your contact list please look at our [Q-municate](https://github.com/QuickBlox/q-municate-ios). There is implementation of contacts list. You can  add or remove users from your contact list, see theirs online status.

Also you can sign up/sign in using email, telephone or facebook.

But first of all every of your friend should be registered as user in Quickblox (via admin panel or application)

**Comment by mallikaD** [comment]
" Cannot find interface declaration for 'QMServicesManager', superclass of 'ServicesManager'."Where i can get this class?If i took from pod it shows file path not found..Through drag drop it shows below error.

**Comment by mallikaD** [comment]
I registered every user into quickblox who are in my friends list.This is the below code i did.**After this what is the process?How can i connect to chat session?**

QBUUser *user = [QBUUser user] ;
    user.login = @"test.user";
    user.password = @"12345678";
    
    [QBRequest signUp:user successBlock:^(QBResponse *response, QBUUser *user) {
        // Success, do something
        [QBRequest logInWithUserLogin:@"test.user" password:@"12345678" successBlock:^(QBResponse *response, QBUUser *user) {
            // Success, do something
            NSLog(@"Successfully Login");
        } errorBlock:^(QBResponse *response) {
            // error handling
            NSLog(@"error: %@", response.error);
        }];
    } errorBlock:^(QBResponse *response) {
        // error handling
        NSLog(@"error: %@", response.error);
    }];

**Comment by mallikaD** [comment]
@VitaliyGuru  Please help me out on this issue.

**Comment by Pro100Andrey** [comment]
Hi @mallikaD, 
1. After this what is the process? [Please check guide](https://quickblox.com/developers/SimpleSample-chat_users-ios)
2. How can i connect to chat session? - 
```objective-c
QBUUser *user = [QBUUser user] ;
user.login = @"test.user";
user.password = @"12345678";
 
[[QBChat instance] connectWithUser:user completion:^(NSError * _Nullable error) {
    NSLog(@"Error: %@", error);
}];
```

**Comment by mallikaD** [comment]
Thank u @Pro100Andrey

**Comment by mallikaD** [comment]
In this below method user means which user??

[[QBChat instance] connectWithUser:user completion:^(NSError * _Nullable error) {
    NSLog(@"Error: %@", error);
}];

Here "user" means which user? Is the user who logged in to the quickblox account and created the backend app that user or with whom i want to chat(registered user in Quickblox (via admin panel or application)) that user? **This is the main confusion i had**

Please clarify me on this concept.

**Comment by mallikaD** [comment]
**If i try your above code then it shows below error**

error: Error Domain=com.quickblox.chat Code=401 "<failure xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><not-authorized/></failure>" UserInfo={NSLocalizedDescription=<failure xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><not-authorized/></failure>}

**Comment by VitaliyGuru** [comment]
@mallikaD  You should connect with that user, who logged in the application.

**Comment by mallikaD** [comment]
Who login to the quickblox? That user??

**Comment by VitaliyGuru** [comment]
You have a user, e.g. 
`QBUUser user =  [QBUUser new];`
`user.login = ... `//login of user, who registered in this app(all registered users you can find in admin panel)
`user.password = ...`//

The you login this user by the method below:
` [QBRequest logInWithUserLogin:user.login password:user.password successBlock:successBlock errorBlock:errorBlock];`
if you want to login user via email you should use 
`[QBRequest logInWithUserEmail:user.email password:user.password successBlock:successBlock errorBlock:errorBlock];`
After successfully login you should connect to chat with this user.

`  [[QBChat instance] connectWithUser:user completion:completion];`

**Comment by mallikaD** [comment]
Exactly i tried like above what you told.i "connectWithUser" which are in admin panel.But i got the error like below:
Error:
[[QBChat instance] connectWithUser:user completion:^(NSError * _Nullable error) {
NSLog(@"Error: %@", error);
}];

**Comment by VitaliyGuru** [comment]
@mallikaD  Show me please your code snippet for login and connecting to chat.

**Comment by mallikaD** [comment]
QBUUser *user = [QBUUser user] ;
    user.login = @"Mallika137";
    user.password = @"12345678";
    
    [QBRequest signUp:user successBlock:^(QBResponse *response, QBUUser *user) {
        // Success, do something
        NSLog(@"Successfully signup");
        [QBRequest logInWithUserLogin:@"Mallika137" password:@"12345678" successBlock:^(QBResponse *response, QBUUser *user) {
            // Success, do something
            NSLog(@"Successfully Login");
            [[QBChat instance] connectWithUser:user completion:^(NSError * _Nullable error) {
    NSLog(@"Error: %@", error);
}];
        } errorBlock:^(QBResponse *response) {
            // error handling
            NSLog(@"error: %@", response.error);
        }];
        
        
    } errorBlock:^(QBResponse *response) {
        // error handling
        NSLog(@"error: %@", response.error);
    }];

**Comment by mallikaD** [comment]
Please let me know why this error is coming? I am strucked over here.

**Comment by VitaliyGuru** [comment]
In success block of the method 
`[QBRequest logInWithUserLogin:@"CheckUser" password:@"12345678"`
you are receiving user without password, because this method doesn't return  the password.

try to set password before connecting to chat.

   ```
QBUUser *user = [QBUUser user] ;
    user.login = @"CheckUser1";
    user.password = @"12345678";
    
    
    [QBRequest signUp:user successBlock:^(QBResponse *response, QBUUser *user) {
        // Success, do something
        NSLog(@"Successfully signup");
        [QBRequest logInWithUserLogin:@"CheckUser" password:@"12345678" successBlock:^(QBResponse *response, QBUUser *user) {
            // Success, do something
            NSLog(@"Successfully Login");

            //setting password again, because method returns user without password
            user.password = @"12345678";

            [[QBChat instance] connectWithUser:user completion:^(NSError * _Nullable error) {
                NSLog(@"Error: %@", error);
            }];
        } errorBlock:^(QBResponse *response) {
            // error handling
            NSLog(@"error: %@", response.error);
        }];
        
    } errorBlock:^(QBResponse *response) {
        // error handling
        NSLog(@"error: %@", response.error);
    }];
```

**Comment by Raikerian** [comment]
Hi @mallikaD 

Were you able to fix this?

**Comment by Raikerian** [comment]
@mallikaD if you are still experiencing this issue, just reopen it. If you are having any other troubles, let us know by creating a separate one.

**Comment by calvinvbigyi** [comment]
I have the same issue with @mallikaD in this case. No matter how I tried, I can't connect the user to Chat by using `QBChat.instance().connect(...)` method. The most weird thing is, when I tried to get the error message of the event, I can only get `nil` in the end..Does this occur to you guys before?
