### ISSUE TITLE
You are not joined to the dialog / No callback from joinWithCompletionBlock

### ISSUE THREAD

**Issue by coredream** [QuickBlox/quickblox-ios-sdk#527]
*Help avoid duplicate issue reports, check [existing issues](https://github.com/QuickBlox/quickblox-ios-sdk/issues)*
 
**Environment details**
*iOS version, Quickblox iOS SDK version, QuickbloxWebRTC SDK version (optional)*
iOS 9.3.2,  QuickBlox 2.7.3, QMServices 0.4.2

**Did this work before?**
Yes

**Expected behavior**
User is joined to group dialog

**Actual behavior**
Two of our users so far have reported this error.  Logging out or deleting/reinstalling app does not fix the problem.
Error: "You are not joined to the dialog"

**Logs**
*Attach full logs that will describe your problem (please, use github [gist](https://gist.github.com/))*
2016-06-21 07:27:41.197 samplechat[92403:38455284] [QMChatCache] Messages to insert 10, update 0
2016-06-21 07:27:44.912 samplechat[92403:38455256] -[QBChatDialog sendIsTypingInGroup] -> Error Domain=com.quickblox.chat Code=-1001 "(null)" UserInfo={NSLocalizedRecoverySuggestion=You are not joined to the dialog.}
2016-06-21 07:27:49.424 samplechat[92403:38455249] -[QBChatDialog sendStopTypingInGroup] -> Error Domain=com.quickblox.chat Code=-1001 "(null)" UserInfo={NSLocalizedRecoverySuggestion=You are not joined to the dialog.}

**Steps to reproduce the behavior**
1.  Fresh install of your sample-chat app with our account credentials.
2.  Login as user reporting problem.
3.  User cannot send message.  Console shows error.

**Any others comments?**
There may be a similar problem going on w/ JS SDK.  So problem may be unrelated to iOS SDK:
 https://github.com/QuickBlox/quickblox-javascript-sdk/issues/102

**Comment by VitaliyGuru** [comment]
@coredream Hi, it's a server-side issue. Will be fixed today at 1:00 PM UTC.

**Comment by VitaliyGuru** [comment]
@coredream  Could you please test it again?

**Comment by coredream** [comment]
@VitaliyGuru I have tried again with these 2 users in the sample app, and it appears to be fixed (self.dialog.isJoined is YES now).  I will notify my users to try again in our real app, and will report back in case there's still an issue.  Thanks.

**Comment by VitaliyGuru** [comment]
Could you please close the issue after success testing on real app?

**Comment by coredream** [comment]
Yes, will do.
