### ISSUE TITLE
QMChatSectionManager

### ISSUE THREAD

**Issue by ronasc** [QuickBlox/quickblox-ios-sdk#528]
Hi, I want my sections to be divided by day - Today, Yesterday, Tuesday, Monday etc. 
How can I do that? 

Tried to subclass QMChatSectionManager but it doesn't work. Please advice

**Comment by Pro100Andrey** [comment]
Hi @ronasc. 
```objective-c
/**
 *  Time interval between sections.
 *  Default value: 300 seconds
**/
self.chatSectionManager.timeIntervalBetweenSections = 86400;
```
and override :

```objective-c
/**
 *  Generating name for section with date.
 *
 *  @param date Date of section
 *
 *  @discussion override this method if you want to generate custom name for section with it's date.
 */
- (NSString *)nameForSectionWithDate:(NSDate *)date;
```

**Comment by ronasc** [comment]
That's not good enough for mw since I need it to be by date and not by last message sent time

**Comment by VitaliyGuru** [comment]
@ronasc Sorry, but I'm not quite clear on 
>  I need it to be by date and not by last message sent time

What date did you mean?

**Comment by VitaliyGuru** [comment]
@ronasc  Any updates?
