### ISSUE TITLE
Chat connectivity from users list

### ISSUE THREAD

**Issue by TungMallika** [QuickBlox/quickblox-ios-sdk#529]
I am using quickblox in my app.I created the users list in quickblox dashboard.Now how to implement the chat session using those users.I saw the Q-municate app but it is different from the sample-chat.So can you please suggest me to implement the chat connectivity.I refer sample-chat but it is having 10 static users list.How can i customise with my friends list?

**Comment by VitaliyGuru** [comment]
To be able to test users in our samples you should create/edit user(or users) with tag "dev" and change kTestUsersDefaultPassword to the password you've chosen for user (For our samples we're retrieving users with tag `dev` and for this users we have similar password `kTestUsersDefaultPassword`. You can change this password in LoginVC).

Then: 1)To be able to use QuickBlox API you have to create a user and be signed in.

2)In order to use real time features you have to be logged in to Chat.

For more further explanation, please refer to [this link](http://quickblox.com/developers/IOS#A_few_words_about_Authentication_and_Authorization)

If you want to retrieve users not by tags please refer to [this link](http://quickblox.com/developers/SimpleSample-users-ios#Retrieving_users)

**Comment by TungMallika** [comment]
I took the 
 'QMServices'  and 'QMChatViewController' using pod in my project but it gives the below error attached in screenshot. Please guide me .

![screen shot 2016-06-24 at 12 33 59 pm](https://cloud.githubusercontent.com/assets/20105257/16330651/86acb7b8-3a08-11e6-9970-585502c435f2.png)

**Comment by VitaliyGuru** [comment]
Make sure that you don't have a duplicate version of the Bolts.framework.
What Xcode version do you use?
And show me your podfile please.

**Comment by TungMallika** [comment]
yes duplicate of bolts framework is there in my project.Thank you. and one more thing i have to ask is:
For chat connectivity i used "connectWithUser" method but i got a doubt that **which user i have to give to this method?** Either user  who logged into quickblox dashboard or register users which will be there in the users list of quickblox(attached in below screenshot)

![screen shot 2016-06-24 at 6 41 56 pm](https://cloud.githubusercontent.com/assets/20105257/16338636/9f4c9f94-3a3b-11e6-98ec-8c81222510d6.png)

**Comment by VitaliyGuru** [comment]
@TungMallika  
You should connect with that user, who logged in the application. 
1. You login or register and login user (any existed user in the application)
2. You connectToChat with this user.

**Comment by VitaliyGuru** [comment]
>or  register users which will be there in the users list of quickblox(attached in below screenshot)
Yes.

**Comment by TungMallika** [comment]
I have added all classes and every thing in my app and also place my credential in AppDelegate.h.Clicking on 'new chat' ,QuickBlox user list for my app is not comming .Please suggest me.

**Comment by TungMallika** [comment]
I Wrote the code like below.First i am retriving  all the users from admin panel and assign one of the user as a login user.But it won't goes to success block,it goes to error block shows unauthorised user.
**My Code:**

[QBRequest usersForPage:[QBGeneralResponsePage responsePageWithCurrentPage:page perPage:100] successBlock:^(QBResponse *response, QBGeneralResponsePage *pageInformation, NSArray *users) {
        QBUUser *selectedUser = [users objectAtIndex:0] ;
        selectedUser.password = kTestUsersDefaultPassword;
        [SVProgressHUD showWithStatus:[NSLocalizedString(@"SA_STR_LOGGING_IN_AS", nil) stringByAppendingString:selectedUser.login] maskType:SVProgressHUDMaskTypeClear];
        // __weak __typeof(self)weakSelf = self;
        // Logging in to Quickblox REST API and chat.
        [ServicesManager.instance logInWithUser:selectedUser completion:^(BOOL success, NSString *errorMessage) {
            if (success) {
            //    __typeof(self) strongSelf = weakSelf;   
                [SVProgressHUD showSuccessWithStatus:NSLocalizedString(@"SA_STR_LOGGED_IN", nil)];
            } else {
                [SVProgressHUD showErrorWithStatus:NSLocalizedString(@"SA_STR_ERROR", nil)];
            }
        }];
    } errorBlock:^(QBResponse *response) {
        // Handle error
    }];

**I am getting the users list and when check the selected user it shows the exact user also.But why it show error like unauthorised?**

**Comment by TungMallika** [comment]
Facing problem here,please reply me @VitaliyGuru.

**Comment by VitaliyGuru** [comment]
@TungMallika 
Are you sure that for `kTestUsersDefaultPassword` you're using your user's password and not our hardcoded?

**Comment by Raikerian** [comment]
Hi @TungMallika 

Any updates on this issue?

**Comment by Raikerian** [comment]
@TungMallika if you are still experiencing this issue, just reopen it. If you are having any other troubles, let us know by creating a separate one.
