### ISSUE TITLE
Duplicated notifications issue.

### ISSUE THREAD

**Issue by matrosovDev** [QuickBlox/quickblox-ios-sdk#530]
I faced with duplicated notifications issues.

1. For making subscription I invoke this code:

```
 let subscription = QBMSubscription()
    subscription.notificationChannel = QBMNotificationChannelAPNS
    subscription.devicePlatform = "iOS"
    subscription.deviceToken = deviceToken
    subscription.deviceUDID = UIDevice.currentDevice().identifierForVendor!.UUIDString
    
    QBRequest.createSubscription(subscription, successBlock: { (response: QBResponse!, objects :[QBMSubscription]?) in
      if let createdSubscription = objects?.first {
        self.currentSubscriptionID = createdSubscription.ID
      } else {
        print("failure in Subscription to apns for QB with failureResponse: \(response) and objects:\(objects)")
      }
      }) {(failureResponse: QBResponse) in
        print("failure in Subscription to apns for QB: : \(failureResponse)")
    }
```

So when I tested it all was subscribed with success but not on all devices but on iPhone 6 plus 9 iOS 9.2.1 (and other 9+).

2. Also for unsubscribe I use this code
```
let deviceUDIDStr  = UIDevice.currentDevice().identifierForVendor!.UUIDString
    
    QBRequest.unregisterSubscriptionForUniqueDeviceIdentifier(deviceUDIDStr, successBlock: { (response: QBResponse) in
      print("unregisterSubscriptionToNotification successBlock:\(response)")
      completion()
    }) { (error: QBError?) in
      print("unregisterSubscriptionToNotification error:\(error)")
      completion()
    }

```
but I got error:

```
errors =     (
        "Device UDID is different"
    );
```

Thanks for help

**Comment by VitaliyGuru** [comment]
So this issue can be closed?

**Comment by Pro100Andrey** [comment]
Hi @matrosovDev, Please check if UDID is the same for subscribe and unsubscribe

**Comment by matrosovDev** [comment]
Hey Andrey, by the way the UDID is the second issue, the main issue duplicated notifications. As I've described above when I create subscription I use this:

`subscription.deviceUDID = UIDevice.currentDevice().identifierForVendor!.UUIDString`

and when I unsubscribe I use:

`let deviceUDIDStr  = UIDevice.currentDevice().identifierForVendor!.UUIDString`

As you see it's the same UDID received from SDK.

But in any case most important issue that I have duplicated notifications that I can see seems only on iPhone 6 plus.

Thanks

**Comment by VitaliyGuru** [comment]
@matrosovDev  I've tested subscribing  and unsubscribing  on device iPhone 6 iOS 9.3.2 on your server
and I haven't caught this error.

**Comment by matrosovDev** [comment]
let's skip subscribe and unsubscribe issue, the main issue for now it's duplicated issues, though that may connected to subscribe/unsubscribe issue.

**Comment by VitaliyGuru** [comment]
You said and I figured out that double notifications is Apple bug, so how can we fix it?

**Comment by matrosovDev** [comment]
I resolved apple bug, because we don't need to use device token twice as I shared with link above, though the issue with duplicated push notification is still there.

I fixed Apple bug, but not an issue.

**Comment by Raikerian** [comment]
Hi @matrosovDev 

In order to understand this issue we require a full logs from app start till the error occurs. Those logs should contain successful subscribe and unsuccessful unsubscribe requests.

**Comment by Raikerian** [comment]
@matrosovDev do you have any updates? Were you able to fix this?

**Comment by nikhilchaurasia** [comment]
I am also getting same issue. The control is coming back two times in error block.
