### ISSUE TITLE
request for index path for global index 5073583552 when there are only 16 items in the collection view

### ISSUE THREAD

**Issue by mjasa** [QuickBlox/quickblox-ios-sdk#533]
crash on

QMChatCollectionViewFlowLayout.m line 177
-[QMChatCollectionViewFlowLayout prepareForCollectionViewUpdates:]

`- (void)prepareForCollectionViewUpdates:(NSArray *)updateItems {
    
    [super prepareForCollectionViewUpdates:updateItems];
	
	
	__weak __typeof(self)weakSelf = self;
    [updateItems enumerateObjectsUsingBlock:^(UICollectionViewUpdateItem *updateItem, NSUInteger index, BOOL *stop) {
        __typeof(self)strongSelf = weakSelf;
        if (updateItem.updateAction == UICollectionUpdateActionInsert) {
            
            CGFloat collectionViewHeight = CGRectGetHeight(strongSelf.collectionView.bounds);
            
            QMChatCellLayoutAttributes *attributes =
            [QMChatCellLayoutAttributes layoutAttributesForCellWithIndexPath:updateItem.indexPathAfterUpdate];
            
            if (attributes.representedElementCategory == UICollectionElementCategoryCell) {
                [strongSelf configureCellLayoutAttributes:attributes];
            }
            
            attributes.frame = CGRectMake(0.0f,
                                          collectionViewHeight + CGRectGetHeight(attributes.frame),
                                          CGRectGetWidth(attributes.frame),
                                          CGRectGetHeight(attributes.frame));
        }
    }];
}`

**Comment by mjasa** [comment]
Fatal Exception: NSInternalInconsistencyException
0  CoreFoundation                 0x183512e38 __exceptionPreprocess
1  libobjc.A.dylib                0x182b77f80 objc_exception_throw
2  CoreFoundation                 0x183512d08 +[NSException raise:format:]
3  Foundation                     0x183e98124 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:]
4  UIKit                          0x1888440a4 -[UICollectionViewData indexPathForItemAtGlobalIndex:]
5  UIKit                          0x188842ffc -[UICollectionViewLayout prepareForCollectionViewUpdates:]
6  Fitnes                         0x1000d4e7c -[QMChatCollectionViewFlowLayout prepareForCollectionViewUpdates:] (QMChatCollectionViewFlowLayout.m:177)
7  UIKit                          0x188842db4 -[UICollectionView _prepareLayoutForUpdates]
8  UIKit                          0x188eace68 -[UICollectionView _updateWithItems:tentativelyForReordering:]
9  UIKit                          0x188eab188 -[UICollectionView _endItemAnimationsWithInvalidationContext:tentativelyForReordering:]
10 UIKit                          0x188eae518 -[UICollectionView _performBatchUpdates:completion:invalidationContext:tentativelyForReordering:]
11 UIKit                          0x188eae394 -[UICollectionView _performBatchUpdates:completion:invalidationContext:]
12 UIKit                          0x18884c24c -[UICollectionView performBatchUpdates:completion:]
13 Fitnes                         0x1000b002c __79-[QMChatViewController chatSectionManager:didInsertSections:andItems:animated:]_block_invoke (QMChatViewController.m:183)
14 Fitnes                         0x1000afeac -[QMChatViewController chatSectionManager:didInsertSections:andItems:animated:] (QMChatViewController.m:193)
15 Fitnes                         0x100105224 __45-[QMChatSectionManager addMessages:animated:]_block_invoke_2 (QMChatSectionManager.m:123)
16 libdispatch.dylib              0x182f5d47c _dispatch_client_callout
17 libdispatch.dylib              0x182f6cae8 _dispatch_barrier_sync_f_slow_invoke
18 libdispatch.dylib              0x182f5d47c _dispatch_client_callout
19 libdispatch.dylib              0x182f62b84 _dispatch_main_queue_callback_4CF
20 CoreFoundation                 0x1834c8dd8 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
21 CoreFoundation                 0x1834c6c40 __CFRunLoopRun
22 CoreFoundation                 0x1833f0d10 CFRunLoopRunSpecific
23 GraphicsServices               0x184cd8088 GSEventRunModal
24 UIKit                          0x1886c5f70 UIApplicationMain
25 Fitnes                         0x100139124 main (main.m:14)
26 libdispatch.dylib              0x182f8e8b8 (Missing)

Crashed: com.twitter.crashlytics.ios.exception
0  Fitnes                         0x1003adf08 CLSProcessRecordAllThreads + 4298661640
1  Fitnes                         0x1003adf08 CLSProcessRecordAllThreads + 4298661640
2  Fitnes                         0x1003ae328 CLSProcessRecordAllThreads + 4298662696
3  Fitnes                         0x10039efdc CLSHandler + 4298600412
4  Fitnes                         0x1003ac620 __CLSExceptionRecord_block_invoke + 4298655264
5  libdispatch.dylib              0x182f5d47c _dispatch_client_callout + 16
6  libdispatch.dylib              0x182f68728 _dispatch_barrier_sync_f_invoke + 100
7  Fitnes                         0x1003ac0cc CLSExceptionRecord + 4298653900
8  Fitnes                         0x1003abf08 CLSExceptionRecordNSException + 4298653448
9  Fitnes                         0x1003abb68 CLSTerminateHandler() + 4298652520
10 libc++abi.dylib                0x182b6af44 std::__terminate(void (*)()) + 16
11 libc++abi.dylib                0x182b6afd0 std::set_new_handler(void (*)()) + 90
12 libobjc.A.dylib                0x182b781a4 _destroyAltHandlerList + 10
13 libdispatch.dylib              0x182f5d490 _dispatch_client_callout + 36
14 libdispatch.dylib              0x182f6cae8 _dispatch_barrier_sync_f_slow_invoke + 644
15 libdispatch.dylib              0x182f5d47c _dispatch_client_callout + 16
16 libdispatch.dylib              0x182f62b84 _dispatch_main_queue_callback_4CF + 1844
17 CoreFoundation                 0x1834c8dd8 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
18 CoreFoundation                 0x1834c6c40 __CFRunLoopRun + 1628
19 CoreFoundation                 0x1833f0d10 CFRunLoopRunSpecific + 384
20 GraphicsServices               0x184cd8088 GSEventRunModal + 180
21 UIKit                          0x1886c5f70 UIApplicationMain + 204
22 Fitnes                         0x100139124 main (main.m:14)
23 libdispatch.dylib              0x182f8e8b8 (Missing)

#0. com.qmunicate.QMChatCacheBackgroundQueue
0  libsystem_kernel.dylib         0x183091014 semaphore_wait_trap + 8
1  libsystem_platform.dylib       0x18316e97c _os_semaphore_wait + 24
2  libdispatch.dylib              0x182f68378 _dispatch_barrier_sync_f_slow + 560
3  CoreData                       0x18540c708 _perform + 212
4  CoreData                       0x18541acec -[NSManagedObjectContext(_NestedContextSupport) managedObjectContextDidRegisterObjectsWithIDs:] + 64
5  CoreData                       0x1853b9494 -[NSManagedObjectContext(_NSInternalAdditions) _informParentStore:ofInterestInObjects:] + 300
6  CoreData                       0x18539e548 -[NSManagedObjectContext save:] + 1220
7  Fitnes                         0x1001511e0 __67-[NSManagedObjectContext(QMCDSaves) QM_saveWithOptions:completion:]_block_invoke.55 (NSManagedObjectContext+QMCDSaves.m:135)
8  Fitnes                         0x100151018 -[NSManagedObjectContext(QMCDSaves) QM_saveWithOptions:completion:] (NSManagedObjectContext+QMCDSaves.m:178)
9  Fitnes                         0x100150c28 -[NSManagedObjectContext(QMCDSaves) QM_saveToPersistentStoreAndWait] (NSManagedObjectContext+QMCDSaves.m:64)
10 Fitnes                         0x100129948 __20-[QMDBStorage save:]_block_invoke (QMDBStorage.m:90)
11 Fitnes                         0x1001296c4 __21-[QMDBStorage async:]_block_invoke (QMDBStorage.m:73)
12 libdispatch.dylib              0x182f5d4bc _dispatch_call_block_and_release + 24
13 libdispatch.dylib              0x182f5d47c _dispatch_client_callout + 16
14 libdispatch.dylib              0x182f694c0 _dispatch_queue_drain + 864
15 libdispatch.dylib              0x182f60f80 _dispatch_queue_invoke + 464
16 libdispatch.dylib              0x182f5d47c _dispatch_client_callout + 16
17 libdispatch.dylib              0x182f6b914 _dispatch_root_queue_drain + 2140
18 libdispatch.dylib              0x182f6b0b0 _dispatch_worker_thread3 + 112
19 libsystem_pthread.dylib        0x183175470 _pthread_wqthread + 1092
20 libsystem_pthread.dylib        0x183175020 start_wqthread + 4

#1. com.apple.libdispatch-manager
0  libsystem_kernel.dylib         0x1830ad4d8 kevent_qos + 8
1  libdispatch.dylib              0x182f707d8 _dispatch_mgr_invoke + 232
2  libdispatch.dylib              0x182f5f648 _dispatch_source_invoke + 50

#2. Thread
0  libsystem_kernel.dylib         0x1830acb48 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x183175530 _pthread_wqthread + 1284
2  libsystem_pthread.dylib        0x183175020 start_wqthread + 4

#3. Thread
0  libsystem_kernel.dylib         0x1830acb48 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x183175530 _pthread_wqthread + 1284
2  libsystem_pthread.dylib        0x183175020 start_wqthread + 4

#4. WebThread
0  libsystem_kernel.dylib         0x183090fd8 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x183090e54 mach_msg + 72
2  CoreFoundation                 0x1834c8ce8 __CFRunLoopServiceMachPort + 196
3  CoreFoundation                 0x1834c69ec __CFRunLoopRun + 1032
4  CoreFoundation                 0x1833f0d10 CFRunLoopRunSpecific + 384
5  WebCore                        0x1873da558 RunWebThread(void*) + 456
6  libsystem_pthread.dylib        0x183177b28 _pthread_body + 156
7  libsystem_pthread.dylib        0x183177a8c _pthread_body + 154
8  libsystem_pthread.dylib        0x183175028 thread_start + 4

#5. com.q-municate.chatsectionmanager.queue
0  libsystem_kernel.dylib         0x183091014 semaphore_wait_trap + 8
1  libsystem_platform.dylib       0x18316e97c _os_semaphore_wait + 24
2  libdispatch.dylib              0x182f68378 _dispatch_barrier_sync_f_slow + 560
3  Fitnes                         0x100104eb8 __45-[QMChatSectionManager addMessages:animated:]_block_invoke (QMChatSectionManager.m:126)
4  libdispatch.dylib              0x182f5d4bc _dispatch_call_block_and_release + 24
5  libdispatch.dylib              0x182f5d47c _dispatch_client_callout + 16
6  libdispatch.dylib              0x182f694c0 _dispatch_queue_drain + 864
7  libdispatch.dylib              0x182f60f80 _dispatch_queue_invoke + 464
8  libdispatch.dylib              0x182f5d47c _dispatch_client_callout + 16
9  libdispatch.dylib              0x182f6b914 _dispatch_root_queue_drain + 2140
10 libdispatch.dylib              0x182f6b0b0 _dispatch_worker_thread3 + 112
11 libsystem_pthread.dylib        0x183175470 _pthread_wqthread + 1092
12 libsystem_pthread.dylib        0x183175020 start_wqthread + 4

#6. com.apple.NSURLConnectionLoader
0  libsystem_kernel.dylib         0x183090fd8 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x183090e54 mach_msg + 72
2  CoreFoundation                 0x1834c8ce8 __CFRunLoopServiceMachPort + 196
3  CoreFoundation                 0x1834c69ec __CFRunLoopRun + 1032
4  CoreFoundation                 0x1833f0d10 CFRunLoopRunSpecific + 384
5  CFNetwork                      0x183b71af4 +[NSURLConnection(Loader) _resourceLoadLoop:] + 412
6  Foundation                     0x183ee7e1c __NSThread__start__ + 1000
7  libsystem_pthread.dylib        0x183177b28 _pthread_body + 156
8  libsystem_pthread.dylib        0x183177a8c _pthread_body + 154
9  libsystem_pthread.dylib        0x183175028 thread_start + 4

#7. Thread
0  libsystem_kernel.dylib         0x1830acb48 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x183175530 _pthread_wqthread + 1284
2  libsystem_pthread.dylib        0x183175020 start_wqthread + 4

#8. com.twitter.crashlytics.ios.MachExceptionServer
0  libsystem_kernel.dylib         0x183090fd8 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x183090e54 mach_msg + 72
2  Fitnes                         0x10039a028 CLSMachExceptionServer + 4298580008
3  libsystem_pthread.dylib        0x183177b28 _pthread_body + 156
4  libsystem_pthread.dylib        0x183177a8c _pthread_body + 154
5  libsystem_pthread.dylib        0x183175028 thread_start + 4

#9. Thread
0  libsystem_kernel.dylib         0x1830acb48 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x183175530 _pthread_wqthread + 1284
2  libsystem_pthread.dylib        0x183175020 start_wqthread + 4

#10. AFNetworking
0  libsystem_kernel.dylib         0x183090fd8 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x183090e54 mach_msg + 72
2  CoreFoundation                 0x1834c8ce8 __CFRunLoopServiceMachPort + 196
3  CoreFoundation                 0x1834c69ec __CFRunLoopRun + 1032
4  CoreFoundation                 0x1833f0d10 CFRunLoopRunSpecific + 384
5  Foundation                     0x183e00d8c -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 308
6  Foundation                     0x183e55ff8 -[NSRunLoop(NSRunLoop) run] + 88
7  Fitnes                         0x10018199c +[AFURLConnectionOperation networkRequestThreadEntryPoint:] (AFURLConnectionOperation.m:190)
8  Foundation                     0x183ee7e1c __NSThread__start__ + 1000
9  libsystem_pthread.dylib        0x183177b28 _pthread_body + 156
10 libsystem_pthread.dylib        0x183177a8c _pthread_body + 154
11 libsystem_pthread.dylib        0x183175028 thread_start + 4

#11. com.apple.CFSocket.private
0  libsystem_kernel.dylib         0x1830ac344 __select + 8
1  CoreFoundation                 0x1834cf250 __CFSocketManager + 648
2  libsystem_pthread.dylib        0x183177b28 _pthread_body + 156
3  libsystem_pthread.dylib        0x183177a8c _pthread_body + 154
4  libsystem_pthread.dylib        0x183175028 thread_start + 4

#12. GCDAsyncSocket-CFStream
0  libsystem_kernel.dylib         0x183090fd8 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x183090e54 mach_msg + 72
2  CoreFoundation                 0x1834c8ce8 __CFRunLoopServiceMachPort + 196
3  CoreFoundation                 0x1834c69ec __CFRunLoopRun + 1032
4  CoreFoundation                 0x1833f0d10 CFRunLoopRunSpecific + 384
5  Foundation                     0x183e00d8c -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 308
6  Fitnes                         0x1005842a8 QB_sortItems + 4300587688
7  Foundation                     0x183ee7e1c __NSThread__start__ + 1000
8  libsystem_pthread.dylib        0x183177b28 _pthread_body + 156
9  libsystem_pthread.dylib        0x183177a8c _pthread_body + 154
10 libsystem_pthread.dylib        0x183175028 thread_start + 4

#13. com.apple.CoreMotion.MotionThread
0  libsystem_kernel.dylib         0x183090fd8 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x183090e54 mach_msg + 72
2  CoreFoundation                 0x1834c8ce8 __CFRunLoopServiceMachPort + 196
3  CoreFoundation                 0x1834c69ec __CFRunLoopRun + 1032
4  CoreFoundation                 0x1833f0d10 CFRunLoopRunSpecific + 384
5  CoreFoundation                 0x18343e464 CFRunLoopRun + 112
6  CoreMotion                     0x1893ab41c (null) + 100061224
7  libsystem_pthread.dylib        0x183177b28 _pthread_body + 156
8  libsystem_pthread.dylib        0x183177a8c _pthread_body + 154
9  libsystem_pthread.dylib        0x183175028 thread_start + 4

**Comment by VitaliyGuru** [comment]
Hi @mjasa 
Could you give me steps to reproduce this crash?
Did you face with this issue in our chat sample?

**Comment by Raikerian** [comment]
Hi @mjasa 

Any updates on this issue?

**Comment by Raikerian** [comment]
@mjasa if you are still experiencing this issue, just reopen it. If you are having any other troubles, let us know by creating a separate one.
