### ISSUE TITLE
-[__NSArrayM objectAtIndex:]: index 11 beyond bounds [0 .. 10]

### ISSUE THREAD

**Issue by mjasa** [QuickBlox/quickblox-ios-sdk#534]
QMChatSectionManager.m line 407
-[QMChatSectionManager messageForIndexPath:]

`- (QBChatMessage *)messageForIndexPath:(NSIndexPath *)indexPath {
    
    if (indexPath.item == NSNotFound) {
        // If the update item's index path has an "item" value of NSNotFound, it means it was a section update, not an individual item.
        return nil;
    }
    
    QMChatSection *currentSection = self.chatSections[indexPath.section];
    return currentSection.messages[indexPath.item];
}`

0  CoreFoundation                 0x1852f659c __exceptionPreprocess
1  libobjc.A.dylib                0x195a4c0e4 objc_exception_throw
2  CoreFoundation                 0x1851db62c -[__NSArrayM removeObjectAtIndex:]
3  Fitnes                         0x1000db1f0 -[QMChatSectionManager messageForIndexPath:] (QMChatSectionManager.m:407)
4  Fitnes                         0x1000866d8 -[QMChatViewController collectionView:itemIdAtIndexPath:] (QMChatViewController.m:621)
5  Fitnes                         0x1000a9200 -[QMChatCollectionViewFlowLayout containerViewSizeForItemAtIndexPath:] (QMChatCollectionViewFlowLayout.m:217)
6  Fitnes                         0x1000a9594 -[QMChatCollectionViewFlowLayout sizeForItemAtIndexPath:] (QMChatCollectionViewFlowLayout.m:277)
7  Fitnes                         0x10008665c -[QMChatViewController collectionView:layout:sizeForItemAtIndexPath:] (QMChatViewController.m:616)
8  UIKit                          0x18a142688 -[UICollectionViewFlowLayout _getSizingInfos]
9  UIKit                          0x18a143020 -[UICollectionViewFlowLayout _fetchItemsInfoForRect:]
10 UIKit                          0x189c1c090 -[UICollectionViewFlowLayout prepareLayout]
11 UIKit                          0x189b06288 -[UICollectionViewData _prepareToLoadData]
12 UIKit                          0x189c7ca64 -[UICollectionView _setupCellAnimations]
13 UIKit                          0x189c7c8d0 -[UICollectionView _updateRowsAtIndexPaths:updateAction:]
14 Fitnes                         0x1000847f0 __111-[QMChatViewController chatSectionManager:didDeleteMessagesWithIDs:atIndexPaths:withSectionsIndexSet:animated:]_block_invoke (QMChatViewController.m:231)
15 Fitnes                         0x100084638 -[QMChatViewController chatSectionManager:didDeleteMessagesWithIDs:atIndexPaths:withSectionsIndexSet:animated:] (QMChatViewController.m:237)
16 Fitnes                         0x1000da39c __48-[QMChatSectionManager deleteMessages:animated:]_block_invoke_2 (QMChatSectionManager.m:236)
17 libdispatch.dylib              0x19609136c _dispatch_client_callout
18 libdispatch.dylib              0x19609e1fc _dispatch_barrier_sync_f_slow_invoke
19 libdispatch.dylib              0x19609136c _dispatch_client_callout
20 libdispatch.dylib              0x196095980 _dispatch_main_queue_callback_4CF
21 CoreFoundation                 0x1852adfa4 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
22 CoreFoundation                 0x1852ac04c __CFRunLoopRun
23 CoreFoundation                 0x1851d90a4 CFRunLoopRunSpecific
24 GraphicsServices               0x18e37b5a4 GSEventRunModal
25 UIKit                          0x189b0e3c0 UIApplicationMain
26 Fitnes                         0x10010d124 main (main.m:14)
27 libdyld.dylib                  0x1960baa08 start

Crashed: com.twitter.crashlytics.ios.exception
0  Fitnes                         0x100381f08 CLSProcessRecordAllThreads + 4298432264
1  Fitnes                         0x100381f08 CLSProcessRecordAllThreads + 4298432264
2  Fitnes                         0x100382328 CLSProcessRecordAllThreads + 4298433320
3  Fitnes                         0x100372fdc CLSHandler + 4298371036
4  Fitnes                         0x100380620 __CLSExceptionRecord_block_invoke + 4298425888
5  libdispatch.dylib              0x19609136c _dispatch_client_callout + 16
6  libdispatch.dylib              0x19609a6e8 _dispatch_barrier_sync_f_invoke + 76
7  Fitnes                         0x1003800cc CLSExceptionRecord + 4298424524
8  Fitnes                         0x10037ff08 CLSExceptionRecordNSException + 4298424072
9  Fitnes                         0x10037fb68 CLSTerminateHandler() + 4298423144
10 libc++abi.dylib                0x195239bb4 std::__terminate(void (*)()) + 16
11 libc++abi.dylib                0x195239c24 std::terminate() + 64
12 libobjc.A.dylib                0x195a4c318 _destroyAltHandlerList + 10
13 libdispatch.dylib              0x196091380 _dispatch_client_callout + 36
14 libdispatch.dylib              0x19609e1fc _dispatch_barrier_sync_f_slow_invoke + 488
15 libdispatch.dylib              0x19609136c _dispatch_client_callout + 16
16 libdispatch.dylib              0x196095980 _dispatch_main_queue_callback_4CF + 932
17 CoreFoundation                 0x1852adfa4 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
18 CoreFoundation                 0x1852ac04c __CFRunLoopRun + 1492
19 CoreFoundation                 0x1851d90a4 CFRunLoopRunSpecific + 396
20 GraphicsServices               0x18e37b5a4 GSEventRunModal + 168
21 UIKit                          0x189b0e3c0 UIApplicationMain + 1488
22 Fitnes                         0x10010d124 main (main.m:14)
23 libdyld.dylib                  0x1960baa08 start + 4

#0. com.apple.libdispatch-manager
0  libsystem_kernel.dylib         0x1961b8c94 kevent64 + 8
1  libdispatch.dylib              0x1960a0980 _dispatch_mgr_invoke + 276
2  libdispatch.dylib              0x1960933b4 _dispatch_source_invoke + 50

#1. WebThread
0  libsystem_kernel.dylib         0x1961b8e7c mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1961b8cf8 mach_msg + 72
2  CoreFoundation                 0x1852aded0 __CFRunLoopServiceMachPort + 200
3  CoreFoundation                 0x1852abe24 __CFRunLoopRun + 940
4  CoreFoundation                 0x1851d90a4 CFRunLoopRunSpecific + 396
5  WebCore                        0x192d2c858 RunWebThread(void*) + 468
6  libsystem_pthread.dylib        0x19626fe80 _pthread_body + 164
7  libsystem_pthread.dylib        0x19626fddc _pthread_body + 158
8  libsystem_pthread.dylib        0x19626cfb0 thread_start + 4

#2. com.twitter.crashlytics.ios.MachExceptionServer
0  libsystem_kernel.dylib         0x1961b8e7c mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1961b8cf8 mach_msg + 72
2  Fitnes                         0x10036e028 CLSMachExceptionServer + 4298350632
3  libsystem_pthread.dylib        0x19626fe80 _pthread_body + 164
4  libsystem_pthread.dylib        0x19626fddc _pthread_body + 158
5  libsystem_pthread.dylib        0x19626cfb0 thread_start + 4

#3. com.apple.NSURLConnectionLoader
0  libsystem_kernel.dylib         0x1961b8e7c mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1961b8cf8 mach_msg + 72
2  CoreFoundation                 0x1852aded0 __CFRunLoopServiceMachPort + 200
3  CoreFoundation                 0x1852abe24 __CFRunLoopRun + 940
4  CoreFoundation                 0x1851d90a4 CFRunLoopRunSpecific + 396
5  CFNetwork                      0x184cde4e8 +[NSURLConnection(Loader) _resourceLoadLoop:] + 440
6  Foundation                     0x1861c9c0c __NSThread__main__ + 1072
7  libsystem_pthread.dylib        0x19626fe80 _pthread_body + 164
8  libsystem_pthread.dylib        0x19626fddc _pthread_body + 158
9  libsystem_pthread.dylib        0x19626cfb0 thread_start + 4

#4. AFNetworking
0  libsystem_kernel.dylib         0x1961b8e7c mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1961b8cf8 mach_msg + 72
2  CoreFoundation                 0x1852aded0 __CFRunLoopServiceMachPort + 200
3  CoreFoundation                 0x1852abe24 __CFRunLoopRun + 940
4  CoreFoundation                 0x1851d90a4 CFRunLoopRunSpecific + 396
5  Foundation                     0x1860e1804 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 316
6  Foundation                     0x18613bef8 -[NSRunLoop(NSRunLoop) run] + 96
7  Fitnes                         0x10015599c +[AFURLConnectionOperation networkRequestThreadEntryPoint:] (AFURLConnectionOperation.m:190)
8  Foundation                     0x1861c9c0c __NSThread__main__ + 1072
9  libsystem_pthread.dylib        0x19626fe80 _pthread_body + 164
10 libsystem_pthread.dylib        0x19626fddc _pthread_body + 158
11 libsystem_pthread.dylib        0x19626cfb0 thread_start + 4

#5. com.apple.CFSocket.private
0  libsystem_kernel.dylib         0x1961d3498 __select + 8
1  CoreFoundation                 0x1852b38c8 __CFSocketManager + 660
2  libsystem_pthread.dylib        0x19626fe80 _pthread_body + 164
3  libsystem_pthread.dylib        0x19626fddc _pthread_body + 158
4  libsystem_pthread.dylib        0x19626cfb0 thread_start + 4

#6. Thread
0  libsystem_kernel.dylib         0x1961b8e7c mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1961b8cf8 mach_msg + 72
2  CoreFoundation                 0x1852aded0 __CFRunLoopServiceMachPort + 200
3  CoreFoundation                 0x1852abe24 __CFRunLoopRun + 940
4  CoreFoundation                 0x1851d90a4 CFRunLoopRunSpecific + 396
5  CoreFoundation                 0x18522b1fc CFRunLoopRun + 112
6  CoreMotion                     0x185bd6990 (null) + 6538750352
7  libsystem_pthread.dylib        0x19626fe80 _pthread_body + 164
8  libsystem_pthread.dylib        0x19626fddc _pthread_body + 158
9  libsystem_pthread.dylib        0x19626cfb0 thread_start + 4

#7. Thread
0  libsystem_kernel.dylib         0x1961d3c78 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x19626d394 _pthread_wqthread + 992
2  libsystem_pthread.dylib        0x19626cfa8 start_wqthread + 4

#8. GCDAsyncSocket-CFStream
0  libsystem_kernel.dylib         0x1961b8e7c mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1961b8cf8 mach_msg + 72
2  CoreFoundation                 0x1852aded0 __CFRunLoopServiceMachPort + 200
3  CoreFoundation                 0x1852abe24 __CFRunLoopRun + 940
4  CoreFoundation                 0x1851d90a4 CFRunLoopRunSpecific + 396
5  Foundation                     0x1860e1804 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 316
6  Fitnes                         0x1005582a8 QB_sortItems + 4300358312
7  Foundation                     0x1861c9c0c __NSThread__main__ + 1072
8  libsystem_pthread.dylib        0x19626fe80 _pthread_body + 164
9  libsystem_pthread.dylib        0x19626fddc _pthread_body + 158
10 libsystem_pthread.dylib        0x19626cfb0 thread_start + 4

#9. Thread
0  libsystem_kernel.dylib         0x1961d3c78 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x19626d394 _pthread_wqthread + 992
2  libsystem_pthread.dylib        0x19626cfa8 start_wqthread + 4

#10. Thread
0  libsystem_kernel.dylib         0x1961d3c78 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x19626d394 _pthread_wqthread + 992
2  libsystem_pthread.dylib        0x19626cfa8 start_wqthread + 4

#11. Thread
0  libsystem_kernel.dylib         0x1961d3c78 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x19626d394 _pthread_wqthread + 992
2  libsystem_pthread.dylib        0x19626cfa8 start_wqthread + 4

#12. Thread
0  libsystem_kernel.dylib         0x1961d3c78 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x19626d394 _pthread_wqthread + 992
2  libsystem_pthread.dylib        0x19626cfa8 start_wqthread + 4

#13. Thread
0  libsystem_kernel.dylib         0x1961d3c78 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x19626d394 _pthread_wqthread + 992
2  libsystem_pthread.dylib        0x19626cfa8 start_wqthread + 4

#14. com.q-municate.chatsectionmanager.queue
0  libsystem_kernel.dylib         0x1961b8eb8 semaphore_wait_trap + 8
1  libsystem_platform.dylib       0x1962659e4 _os_semaphore_wait + 24
2  libdispatch.dylib              0x19609a3e4 _dispatch_barrier_sync_f_slow + 520
3  Fitnes                         0x1000da234 __48-[QMChatSectionManager deleteMessages:animated:]_block_invoke (QMChatSectionManager.m:239)
4  libdispatch.dylib              0x1960913ac _dispatch_call_block_and_release + 24
5  libdispatch.dylib              0x19609136c _dispatch_client_callout + 16
6  libdispatch.dylib              0x19609b4c0 _dispatch_queue_drain + 1216
7  libdispatch.dylib              0x196094474 _dispatch_queue_invoke + 132
8  libdispatch.dylib              0x19609d224 _dispatch_root_queue_drain + 664
9  libdispatch.dylib              0x19609e75c _dispatch_worker_thread3 + 108
10 libsystem_pthread.dylib        0x19626d2e4 _pthread_wqthread + 816
11 libsystem_pthread.dylib        0x19626cfa8 start_wqthread + 4

**Comment by VitaliyGuru** [comment]
Hi @mjasa 
Could you give me steps to reproduce this crash?
Did you face with this issue in our chat sample?

**Comment by Raikerian** [comment]
Hi @mjasa 

Any updates on this issue?

**Comment by Raikerian** [comment]
@mjasa We haven't heard any updates from you on this issue. If you are still experiencing it, just reopen it. If you are having any other problems, let us know by creating a separate issue.

**Comment by swetaagicent** [comment]
i am facing the same issue. how i resolved it

**Comment by Raikerian** [comment]
@swetaagicent please create a separate issue with more information
