### ISSUE TITLE
QBMEvent with type email doesn't work

### ISSUE THREAD

**Issue by neshyurik** [QuickBlox/quickblox-ios-sdk#535]
I'm using QBMEvent to send email to users. But when I try to call it responses the error: "No recipients. At least one user should be subscribed for E-mail (through SDK or REST API)". 

    QBMEvent *event = [QBMEvent event];
    event.notificationType = QBMNotificationTypeEmail;
    event.type = QBMEventTypeOneShot;
    
    event.usersIDs = [NSString stringWithFormat:@"%lu", (unsigned long)user.ID];
   
    
    event.message = [NSString stringWithFormat:@"%@ has sent a friend request", [UserManager shared].currentUser.nickname];
    
    [QBRequest createEvent:event successBlock:^(QBResponse *response, NSArray *events) {
        
    }
                errorBlock:^(QBResponse *response) {
                    
                }];

**Environment details**
IOS 9.3.1 (Deployment target -8.0)
Xcode Version 7.3.1

**Logs**
Response object: (
        {
        event =         {
            active = 1;
            "application_id" = 41443;
            "created_at" = "2016-06-30T14:43:37Z";
            date = "<null>";
            "end_date" = "<null>";
            "event_type" = "one_shot";
            id = 7638023;
            kind = API;
            message = "payload=eyJhcHMiOnsiYWxlcnQiOiJvbGVrc2FuZHIgaGFzIHNlbnQgYSBmcmllbmQgcmVxdWVzdCIsInNvdW5kIjoiZGVmYXVsdCJ9fQ==";
            name = "<null>";
            "notification_channel" =             {
                name = apns;
            };
            "occured_count" = 0;
            period = "<null>";
            "subscribers_selector" =             {
                environment = development;
                "tags_query" = "<null>";
                "user_ids" =                 (
                    13296078
                );
            };
            "updated_at" = "2016-06-30T14:43:37Z";
            "user_id" = 14416584;
        };
    }
 
Request parameters:{
    event =     {
        environment = development;
        "event_type" = "one_shot";
        message = "b2xla3NhbmRyIGhhcyBzZW50IGEgZnJpZW5kIHJlcXVlc3Q=";
        "notification_type" = email;
        user =         {
            ids = 13296078;
        };
    };

**Comment by VitaliyGuru** [comment]
Hi @neshyurik , Are you sure that you have subscribed user with id  13296078 for email notifications?
`   QBMSubscription *subscription = [QBMSubscription subscription];
    subscription.notificationChannel = QBMNotificationChannelEmail;
    [QBRequest createSubscription:subscription successBlock:nil errorBlock:nil];
`

**Comment by neshyurik** [comment]
It is working now. Thanks a lot!!

**Comment by VitaliyGuru** [comment]
@neshyurik  You're welcome.
