### ISSUE TITLE
Login Questions

### ISSUE THREAD

**Issue by dmitry9890** [QuickBlox/quickblox-ios-sdk#537]
Hello Guys,

Can I login in ServicesManager with token, which I recieved from REST API?

**Comment by Raikerian** [comment]
Hi,

Not sure what are you talking about. ServicesManager is a part of our [QMServices](https://github.com/QuickBlox/q-municate-services-ios) project. It is managing all those request by itself. You just need to use any of [these](https://github.com/QuickBlox/q-municate-services-ios#qmauthservice) methods to login.

**Comment by Raikerian** [comment]
@dmitry9890 if you are still experiencing this issue, just reopen it. If you are having any other troubles, let us know by creating a separate one.
