### ISSUE TITLE
Getting login user friends List

### ISSUE THREAD

**Issue by mallikaD** [QuickBlox/quickblox-ios-sdk#538]
I used quickblox chat in my app.Everything is ok but when showing the friends list the problem is i am getting the total list who are in admin panel.But the functionality is only get the particular user friends not all the users in admin panel.How can i implement this functionality(**Getting only the  login user friends list**).Please suggest me on this.

**Comment by VitaliyGuru** [comment]
Hi @mallikaD , Could you please show me your code snippet for retrieving  the friends list?

**Comment by mallikaD** [comment]
I just placed the code whatever there in the sample chat project

**Comment by VitaliyGuru** [comment]
@mallikaD  Take a look at our [QMContactListService](https://github.com/QuickBlox/q-municate-services-ios/tree/master/QMContactListService/QMContactListService) which is part of [QMServices](https://github.com/QuickBlox/q-municate-services-ios)

**Comment by Raikerian** [comment]
HI @mallikaD 

As @VitaliyGuru stated, you need to use contact list. From contact list you can easily fetch friends user IDs, then just fetch all that users IDs from backend using QBRequest method.

**Comment by mallikaD** [comment]
ok thank you @Raikerian .Let me try and get back to you.

**Comment by VitaliyGuru** [comment]
@mallikaD  Any updates?

**Comment by Raikerian** [comment]
@mallikaD if you are still experiencing this issue, just reopen it. If you are having any other troubles, let us know by creating a separate one.
