### ISSUE TITLE
APNS (Apple Push) is not enabled for the current application. Please enable this notification channel in the settings tab of the admin panel

### ISSUE THREAD

**Issue by hagile** [QuickBlox/quickblox-ios-sdk#54]
I'm getting this error message when trying to send a push from the iOS application.

I've already configured my app (on the QuickBlox site) with specific push certificates and I'm able to get a push from the site from send message section on to the site. 

What's wrong? Is there something that I forgot to enable?

**Comment by soulfly** [comment]
Do you use the same environment in admin panel and app?

**Comment by hagile** [comment]
Got it working. I used the different environment.

**Comment by nirav700** [comment]
@soulfly please elaborate your answer , i have uploaded only production certification in admin panel and nothing changes in application side , can you please guid me what i am doing wrong.

**Comment by Raikerian** [comment]
@nirav700 please create separate issue and describe your it in more details.
