### ISSUE TITLE
QBChatDialog documentation clarification

### ISSUE THREAD

**Issue by eagle-dan1349** [QuickBlox/quickblox-ios-sdk#540]
Quickblox iOS 2.7.3
I'm looking through documentation, wiki, examples and SO.
The following remains unclear to me: is it safe and would QBChatDialog objects work IF I save and restore them between app launches?
Via NSUserDefaults, CoreData or whatever
(I assume NO, am I right?)

**Comment by VitaliyGuru** [comment]
@eagle-dan1349 
You can save  QBChatDialog objects.
They adopt `<NSCoding, NSCopying>`.
Take a look at our [iOS-Chat-Sample](https://github.com/QuickBlox/quickblox-ios-sdk/tree/master/sample-chat). There you can find [QMServices](https://github.com/QuickBlox/q-municate-services-ios). The main features of `QMServices` are:
-Inbox persistent storage for messages, dialogs and users
-Inbox memory storage for messages, dialogs and users.

Feel free to ask any questions.

**Comment by eagle-dan1349** [comment]
I see, thanks.

**Comment by VitaliyGuru** [comment]
@eagle-dan1349 Can i close this issue?
