### ISSUE TITLE
Sending QBChatMessage with "content-available" in APNS Payload is not possible

### ISSUE THREAD

**Issue by cvezina** [QuickBlox/quickblox-ios-sdk#541]
*Help avoid duplicate issue reports, check [existing issues](https://github.com/QuickBlox/quickblox-ios-sdk/issues)*
 
**Environment details**
*iOS version, Quickblox iOS SDK version, QuickbloxWebRTC SDK version (optional)*

iOS 9.3 and Quickblox iOS SDK 2.7.3

**Did this work before?**

Don't know how to make this work

**Expected behavior**

Should be allowed to activate this parameter

**Actual behavior**

None

**Logs**
*Attach full logs that will describe your problem (please, use github [gist](https://gist.github.com/))*

**Steps to reproduce the behavior**

Here is a sample code that send a chat message that is received correctly on the receiver end but the payload of the push notification doesn't include the parameter "content-available"

    QBChatMessage *message = [[QBChatMessage alloc] init];

    message.text = text;

    NSMutableDictionary *params = [NSMutableDictionary dictionary];
    params[@"save_to_history"] = @YES;
	params[@"senderDisplayName"] = senderDisplayName;
	params[@"avatar"] = [BEUser currentUser].photos.count > 0 ? [BEUser currentUser].photos[0] : @"";
    [message setCustomParameters: params];

	[self.dialog sendMessage: message completionBlock:^(NSError * _Nullable error) {
		[self stopLoading];
		if (error != nil) {
			[[TWMessageBarManager sharedInstance] showMessageWithTitle: @"Something went wrong!" description: nil type: TWMessageBarMessageTypeError];
		} else {
		}
	}];

**Any others comments?**

**Comment by Raikerian** [comment]
Hi,

There is no any push notifications sending in the code you have provided. It is just a message sending code. Maybe you are talking about message alert when the app is in a foreground?

**Comment by cvezina** [comment]
Hi,

Using sendMessage of QBChatDialog is implicitly sending a push notification to the recipient but I haven’t found a way to set params of the “aps” fields used by APNS.

**Comment by cvezina** [comment]
Ok, I found where to set the parameters for content available and badge count number. You need to select "Chat" in the admin panel and pick "Settings" on the top right.
