### ISSUE TITLE
Unable to send message

### ISSUE THREAD

**Issue by Shafqat-Mehmood** [QuickBlox/quickblox-ios-sdk#542]
I am unable to send message in the following scenario

When app goes to sleep mode and after sometime come to active mode then unable to send message. Message is not receive to the user. I am using 2.7.3 SDK

Please help me.

**Comment by VitaliyGuru** [comment]
Hi @Shafqat-Mehmood , Have you try to send message in chat sample?
Did you connect to chat after disconnect in background?

**Comment by Raikerian** [comment]
@Shafqat-Mehmood if you are still experiencing this issue, just reopen it. If you are having any other troubles, let us know by creating a separate one.
