### ISSUE TITLE
How to remove the reconnect and attempt to reconnect notification banners.

### ISSUE THREAD

**Issue by ajay2c9** [QuickBlox/quickblox-ios-sdk#544]
How to remove reconnect and attempt to reconnect these type of banners from the app when the network is changed or bad network connection.

![screen shot 2016-07-12 at 11 14 19 am](https://cloud.githubusercontent.com/assets/9112899/16756736/ba717c44-4824-11e6-8db5-f6b5cc6b9445.png)

**Comment by Raikerian** [comment]
Hi,

We do not have this custom UI implementation in our samples. Where did you get this?
