### ISSUE TITLE
QBChatDelegate inconsistency

### ISSUE THREAD

**Issue by eagle-dan1349** [QuickBlox/quickblox-ios-sdk#545]
**Environment details**
Quickblox iOS SDK 2.7.3

Probably, a feature request.
Involved are QBChat, QBChatDelegate and QBChatDialog.
As I see QBChatDialog is an attempt to incapsulate chat mechanics for a single chat.
Ideally, I'd use QBChatDelegate instance from viewmodel without any concerns,
while my core classes handle everything else.

However, when I send message via -[QBChatDialog sendMessage:completionBlock:] I cannot perform any handling via QBChatDelegate methods or any other. To save said message to persistent store I'll have to either do it from viewmodel (I'll skip why it's just a bad place to do), OR avoid using QBChatDialog from within viemodel classes altogerther.
This issue nullifies any advantages of QBChatDialog incapsulation.

I propose to add method like
-(void)chatDidSendMessage:(QBChatMessage *)message; to QBChatDelegate
and of course call it when a message is successfully send.

Just take a look:
``- (void)sendMessage:(QBChatMessage *)message
               type:(QMMessageType)type
           toDialog:(QBChatDialog *)dialog
      saveToHistory:(BOOL)saveToHistory
      saveToStorage:(BOOL)saveToStorage
completion:(QBChatCompletionBlock)completion
{
...``
^ whenever someone come up with code like this a kitten dies.

**Comment by Raikerian** [comment]
Hi @eagle-dan1349 

The method you have lined at the end is a part of QMServices project, a wrapper over our SDK. It has as much options as possible to meet requirements from different people and has nothing to do with our SDK QBChatDelegate. As I understand you have some problems with our SDK itself. So lets clarify some things here.
Completion blocks are part of our SDK philosophy at this moment, maybe we will consider change it in a future releases, but we have had those delegate methods before.

Please tell, what is the problem to handle sent message in completion block? If you don't want block to be long, you can predefine it somewhere else, and send it in the method whenever you need to. You can also create a separate own method and call it in completion block. send a message instance in it if needed to handle something.

Right now QBChat delegate methods are methods of chat, and it applies only to chat. QBChatDialog is its own model.

**Comment by eagle-dan1349** [comment]
@Raikerian I probably missexpressed my point, OK...
I definetly do not state that completion blocks are bad or badly implemented, I took your method as an example because I see responsibility problem with it.

1. What I want to do is **centralized** handling of outgoing messages, just like it works in XMPPFramework. I'm writing my chat history module and it would be very nice to just connect it to wrapper class for QBChat and let it work peacefully.

2. To achieve this, I need an ability to get notified on outgoing messages **without** messing with QBChatDialog instances.

3. However, I'd like to preserve abstraction in my viewmodels and work via individual QBChatDialogs so that viewmodels have only read access to actual chat history.

**Comment by eagle-dan1349** [comment]
Any news or other sort of reply?

**Comment by Raikerian** [comment]
The philosophy of our SDK is built over completion blocks, not sure if we are looking into any changes in a near future. Send message is a part of QBChatDialog model, therefore it will not be good to put it to QBChat delegate.
