### ISSUE TITLE
Receiving duplicate push notification

### ISSUE THREAD

**Issue by Shafqat-Mehmood** [QuickBlox/quickblox-ios-sdk#548]
I am Receiving duplicate push notification e.g I have send message "Hello" to User B then User B received two notification for that message "Hello"

**Comment by Raikerian** [comment]
Hi,

Does the problem still exists? Check that you are not subscribed for push notifications twice. And check if you are not sending your pushes manually, cause server is handling them automatically.

**Comment by Raikerian** [comment]
@Shafqat-Mehmood any updates?

**Comment by rajeevsharma2811** [comment]
For iOS as well it is handling automatically? No need to send an event object? What if I have to send a custom parameter?
