### ISSUE TITLE
Crash when instantiating QBRTCRemoteVideoView (signal SIGABRT)

### ISSUE THREAD

**Issue by astanton** [QuickBlox/quickblox-ios-sdk#549]
Here is the call that I am using to instantiate it:

`let videoView = QBRTCRemoteVideoView(frame: CGRect(x: 0, y: 0, width: UIScreen.mainScreen().bounds.width, height: UIScreen.mainScreen().bounds.height))`

It's not happening every time, it is happening randomly after connecting like the 5th or 6th time, but it's just random.

I've attached a screen shot of the stack and error as well.

Any ideas?

<img width="1673" alt="screen shot 2016-07-17 at 9 28 21 pm" src="https://cloud.githubusercontent.com/assets/3637526/16904492/8887fbf0-4c65-11e6-8d13-14adcf44fc83.png">

**Comment by Pro100Andrey** [comment]
Hi @astanton please provide code snippet of VideoCallViewController

**Comment by Raikerian** [comment]
@astanton any updates?

**Comment by astanton** [comment]
I haven't seen this since I changed from H264 to VP8 due to other crash bugs with H264, so it may be related to that.  If I see it again I will revisit this thread with more details.
