### ISSUE TITLE
Can't change audio session route

### ISSUE THREAD

**Issue by dragospanoiu** [QuickBlox/quickblox-ios-sdk#55]
After initiating WebRTC call the app crashes when trying to redirect audio to speaker:
[QBRTCSession setAudioCategoryOptions:]: unrecognized selector sent to instance

The only solution I've found is to manually override audio session output when connectedToUser:
AVAudioSession *audioSession = [AVAudioSession sharedInstance];
[audioSession setCategory:AVAudioSessionCategoryPlayAndRecord error:nil];
[audioSession setActive:YES error:nil];
[audioSession overrideOutputAudioPort:AVAudioSessionPortOverrideSpeaker error:nil];

Thanks,
Dragos

**Comment by soulfly** [comment]
Investigating this

**Comment by AndreyMoskvin** [comment]
Fixed in WebRTC 2.0.
