### ISSUE TITLE
Push notifications are not working from iOS to Android and Android to iOS release production

### ISSUE THREAD

**Issue by lakshmibomma** [QuickBlox/quickblox-ios-sdk#550]
_Help avoid duplicate issue reports, check [existing issues](https://github.com/QuickBlox/quickblox-ios-sdk/issues)_

**Environment details**
_iOS version, Quickblox iOS SDK version, QuickbloxWebRTC SDK version (optional)_

**Did this work before?** :Yes

**Expected behavior**: Push notifications should work from iOS to Android and Android to iOS on release (production) version as well as development

**Actual behavior**: Users are not receiving the push notifications

**Logs**
_Attach full logs that will describe your problem (please, use github [gist](https://gist.github.com/))_

**Steps to reproduce the behavior**
We are creating the event like this for push notification.
**iOS:**
    QBMEvent *event = [QBMEvent event];
    event.notificationType = QBMNotificationTypePush;
    event.usersIDs = [@(message.recipientID) stringValue];
    event.type = QBMEventTypeOneShot;
[QBRequest createEvent:event successBlock:^(QBResponse \* _Nonnull response, NSArray<QBMEvent *> \* _Nullable events) {
       // Successful response with event
   } errorBlock:^(QBResponse \* _Nonnull response) {
       // Handle error
        //NSLog(@"Push Message Error: %@",[response description]);
   }];

**Any others comments?**

 Push notifications are not working from iOS to Android and Android to iOS on release (production) version. It was working earlier almost 20 days back on both development and production. Now my app is only working on development on both the platforms. Can you guys please lets us know what will be the fix for that. We are using Quickblox framework 2.7.4 version.

**Comment by VitaliyGuru** [comment]
Hi @lakshmibomma ,
Could you please provide your application id from the admin panel of Quickblox?

**Comment by lakshmibomma** [comment]
Application id on Quickblox admin panel 34191
No error, appearing in queue but still not getting push notification on ios from android and android from ios.
It is also creating the chat in queue
![img_0136](https://cloud.githubusercontent.com/assets/1056094/16962898/ae17cd48-4dc1-11e6-8f5d-bcfc1ff9d64a.jpg)

**Comment by lakshmibomma** [comment]
We are able to create the chat on production but it is not sending the push notification on both the platforms ios and android.  Do you have separate servers for development and production. Is there any quickblox server or framework issue on production for push notification. Can you please suggest us.

**Comment by Pro100Andrey** [comment]
@lakshmibomma Any updates?
