### ISSUE TITLE
Public chat occupants

### ISSUE THREAD

**Issue by kirillkhlopko** [QuickBlox/quickblox-ios-sdk#551]
iOS 9.0, v2.7.3

Now adding quickblox to app and faced with one problem.
User joined public group chat and write message. Next time when we load chats from user which join it before, this chat again not joined by this user. And this behaviour confuse me. Is it right behaviour or I missed something? And if it's right, how works leaving for public group chats?
Also, something strange with group chats (not public). They also not joined by user as default, but when group chat created with list of occupants means user join this group chat.
It will be great if you will explain behaviour more detailed, because after reading documentation and adding features to project, this all not clear for me.

**Comment by Raikerian** [comment]
Hi,

Not sure what is your exact question, but here are some of the answers:

1. Public room does not have occupants, but it has joined users.
2. You will leave from chat dialog if QBChatDialog instance is deallocated. Try to update already existent instance while loading new one from server instead of replacing it.

**Comment by kirillkhlopko** [comment]
Hi!
Thanks for answer! Not exactly what I've asked about, but it helps me with questions.

**Comment by Raikerian** [comment]
Any other questions we can help you with?

**Comment by kirillkhlopko** [comment]
About this : "You will leave from chat dialog if QBChatDialog instance is deallocated."
This is how iOS SDK works or REST API?

**Comment by Raikerian** [comment]
If you do not have any instances of a specific dialog, you are simply will be out of the dialog room.

Lets see: you have 2 QBChatDialog instances of same group chat, and joined one of them -> isJoined will be YES for both of them. One of the two deallocates -> isJoined for second one is still true. After last instance of this group dialog will be deallocated, room will perform leave.

**Comment by Gurwinder1234** [comment]
How to create public group  from QuickBlox service for iOS Swift. Please help me.

could you please provide me the solution ??

**Comment by Gurwinder1234** [comment]
@Raikerian I want to create public group (QBChatDialogTypePublicGroup) from mobile is it feasible ?
if yes , Could you please provide the solution
