### ISSUE TITLE
How to stop the "You have 8 new messages" type of notifications

### ISSUE THREAD

**Issue by ajay2c9** [QuickBlox/quickblox-ios-sdk#553]
Hi
I am using quickblox in myapp.I am sending the Push notifications using the below request.

[QBRequest sendPush:PushMsg toUsers:str successBlock:^(QBResponse *response, QBMEvent *event){ } errorBlock:^(QBError *error) { }];

But i am also receiving another Push Notification like : You have 8 new messages.

How to stop above type of notifications.
Thank you

**Comment by Raikerian** [comment]
Hi @ajay2c9 

Go to your admin panel, application settings. Switch to chat settings:

![screenshot 2016-07-26 16 19 43](https://cloud.githubusercontent.com/assets/8850270/17139370/d1c3c7e8-534c-11e6-9f38-1a0211d1fc30.png)

Switch to alert tab upper right corner:

![screenshot 2016-07-26 16 20 33](https://cloud.githubusercontent.com/assets/8850270/17139400/eba96e92-534c-11e6-87d2-3856d2ae2195.png)

Remove mark from "Enable automatic notifications for offline users".
