### ISSUE TITLE
QBCOFileUploadInfo.h missing in framework

### ISSUE THREAD

**Issue by mskrischke** [QuickBlox/quickblox-ios-sdk#559]
**Environment details**
iOS 9-10, Quickblox 2.7.4

**Did this work before?**
Probably in 2.4, did not use it at that time.

**Expected behavior**
QBCOFileUploadInfo.h is part of the framework.

**Actual behavior**
QBCOFileUploadInfo.h is not part of the framework headers. This results in not being able to use the QBRequest.uploadFile:className:objectID:objectID:successBlock:statusBlock:errorBlock from Swift. Using the API from Objective-C seems to work but auto completion for the QBCOFileUploadInfo type is also not working.

**Steps to reproduce the behavior**
Create a new Swift project with QuickBlox and try to use the mentioned API call.

**Any others comments?**
 Manually adding the header from a previous version (2.4) to the framework and adding it to Quickblox.h seems to fix the problem.

**Comment by Raikerian** [comment]
Hi @mskrischke 

Thank you for reporting the issue, I have confirmed it and working on fix at this moment. It will be available in the next release approx. next week

**Comment by Raikerian** [comment]
We have released a 2.7.5 today, which contains this fix. Please check it out.

If you are still having any other issues, let us know by creating a separate issue.

**Comment by mskrischke** [comment]
I can confirm the problem is fixed for us :)
