### ISSUE TITLE
Storing a custom object in the field of a different custom object

### ISSUE THREAD

**Issue by mitchellporter** [QuickBlox/quickblox-ios-sdk#56]
Let's say I have a Movie custom object and a Comment custom object.

I need to add a field to the Movie class that I can store the Comment object in.

How can I do this because right now when I go to add a field the only options are Integer, Float, Boolean, String, File, and Location?

**Comment by soulfly** [comment]
There is no way to do it, 
you can create a String  field and store an ID of another record

The other way is to use a field ParentID in the Comment record and point it to the Movie record.
ParentID allows cascade deletion on objects.
For example when you delete a Movie record then all Comment records also will be deleted

**Comment by mitchellporter** [comment]
@soulfly Thanks for the fast response Igor!
