### ISSUE TITLE
Error when import WebRTC in swift project

### ISSUE THREAD

**Issue by iTehdrew** [QuickBlox/quickblox-ios-sdk#562]
When import library using CocoaPods Xcode response errors:
http://prntscr.com/bzsvi8
http://prntscr.com/bzsvpc

If Import using additional steps Xcode don't see library when write in class file: import QuickbloxWebRTC

What could be the problem?

**Comment by Pro100Andrey** [comment]
Hi @iTehdrew, please add `#import <UIKit/UIKit.h>` in to header

**Comment by iTehdrew** [comment]
Ty, it fix the problem.

But in my project It sets the minimum support for iOS 8. After your modification both showed more than 200 warning notices related quickblox. At the moment, support only iOS 9?

I fix all warning using this method:
1) Select your Project
2) Select your Target
3) Select "Build Settings" tab
4) Scroll down to "Linking"
4) Edit "Other Linker Flags" and add "-w"

**Comment by Pro100Andrey** [comment]
@iTehdrew please provide logs

**Comment by Pro100Andrey** [comment]
@iTehdrew 7+
