### ISSUE TITLE
QuickBlox custom object Retrieve records using Search operators, How do I get the results into a QBCOCustomObject

### ISSUE THREAD

**Issue by testmodulesgit** [QuickBlox/quickblox-ios-sdk#564]
*This is a question not a issue

Just started integrating QuickBlox into one of my apps, I am using the following code

`NSMutableDictionary *getRequest = [NSMutableDictionary dictionary];
[getRequest setObject:@"5.5" forKey:@"rating[gt]"];
[getRequest setObject:@"5" forKey:@"limit"];
[getRequest setObject:[NSNumber numberWithBool:NO]     forKey:@"documentary"];
[getRequest setObject:@"rating" forKey:@"sort_asc"];

[QBRequest objectsWithClassName:@"Movie" extendedRequest:getRequest  successBlock:^(QBResponse *response, NSArray *objects, QBResponsePage  *page) {
    // response processing
} errorBlock:^(QBResponse *response) {
// error handling
NSLog(@"Response error: %@", [response.error description]);
}];`

I am getting the result in NSArray *objects. Is there a way to get the results to a QBCOCustomObject. How can I do this?

**Comment by VitaliyGuru** [comment]
Hi @testmodulesgit ,
I'm not sure what you mean. In success block you will receive array of QBCOCustomObjects.
Could you explain in more detail the thing about expected result.

**Comment by Raikerian** [comment]
@testmodulesgit any updates on the issue?
