### ISSUE TITLE
Push notifications for public group chats

### ISSUE THREAD

**Issue by kirillkhlopko** [QuickBlox/quickblox-ios-sdk#567]
Hello guys!
Is it possible to send push notifications for users that connected to public group chat? In docs I did not find anything that can help me.

**Comment by Raikerian** [comment]
Hi @kirillkhlopko 

It is possible, but you will need to store connected users to the public chat. As you know, public group does not have occupants list. And you have to join every time after re-login.
You can use custom objects, for example to store joined users IDs. And request it every time you need to send a push notification. You can combine it with QBChatDialog customData field: http://quickblox.com/developers/Chat#Custom_parameters

**Comment by kirillkhlopko** [comment]
Yes, I thought about this way. But public group chats can be updated only by it's owner:

> The following rules are applied if dialog's type is 1(PUBLIC_GROUP):
Only dialog’s owner can update it.

**Comment by Raikerian** [comment]
So the owner should create custom data and attach it to dialog, then custom data can be updated not only by owner.
