### ISSUE TITLE
Opponent video is not displaying.

### ISSUE THREAD

**Issue by tvadde** [QuickBlox/quickblox-ios-sdk#568]
Hi,

I am trying to integrate a quickblox video calling into my application. And below is my code for showing video on view.  Please help me in this area why i am unable to get the opponent video.

Please let me know if you required more info.

- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view from its nib.
    [QBRTCClient.instance addDelegate:self];
//    [QBRTCSoundRouter.instance initialize];
}

- (void)viewDidAppear:(BOOL)animated{
    [super viewDidAppear:animated];
    
    self.cameraCapture = [[QBRTCCameraCapture alloc] initWithVideoFormat:[QBRTCVideoFormat defaultFormat]
                                                                position:AVCaptureDevicePositionFront];
    [self.cameraCapture startSession];
    self.cameraCapture.previewLayer.frame = self.userView.bounds;
    self.cameraCapture.previewLayer.videoGravity = AVLayerVideoGravityResizeAspect;
    [self.userView.layer insertSublayer:self.cameraCapture.previewLayer atIndex:0];
//    [QBRTCSoundRouter instance].currentSoundRoute = QBRTCSoundRouteSpeaker;
    
    if (IsDoctorApp && self.onGoingsession) {
        NSDictionary *userInfo = @{@"startCall" : @"userInfo"};
        [self.onGoingsession startCall:userInfo];
    }
}

- (void)session:(QBRTCSession *)session updatedStatsReport:(QBRTCStatsReport *)report forUserID:(NSNumber *)userID {
    
}

- (void)session:(QBRTCSession *)session initializedLocalMediaStream:(QBRTCMediaStream *)mediaStream {
    
    session.localMediaStream.videoTrack.videoCapture = self.cameraCapture;
}

- (void)session:(QBRTCSession *)session receivedRemoteVideoTrack:(QBRTCVideoTrack *)videoTrack fromUser:(NSNumber *)userID {
    
    if (IsDoctorApp){
        NSLog(@"patine userid : %@",userID);
    }else{
        NSLog(@"doctor userid : %@",userID);
    }
//    QBRTCVideoTrack *remoteVideoTrak = [session remoteVideoTrackWithUserID:userID];
//    QBRTCSampleBufferView *view = (QBRTCSampleBufferView *)self.oponentView.rendererType.rendererView;
//    view.videoGravity = AVLayerVideoGravityResizeAspectFill;

    
    [self.oponentView setVideoTrack:videoTrack];
    
}

- (void)session:(QBRTCSession *)session userDoesNotRespond:(NSNumber *)userID {
    
    NSLog(@"userDoesNotRespond");
}

- (void)session:(QBRTCSession *)session rejectedByUser:(NSNumber *)userID userInfo:(NSDictionary *)userInfo {
    
    NSLog(@"rejectedByUser");
}

- (void)session:(QBRTCSession *)session hungUpByUser:(NSNumber *)userID userInfo:(NSDictionary *)userInfo {
    
    NSLog(@"hungUpByUser");
}

- (void)session:(QBRTCSession *)session startedConnectionToUser:(NSNumber *)userID {
    
    NSLog(@"startedConnectionToUser");
}

- (void)session:(QBRTCSession *)session connectedToUser:(NSNumber *)userID {
    
    NSLog(@"connectedToUser");
}

- (void)session:(QBRTCSession *)session connectionClosedForUser:(NSNumber *)userID {
    
    NSLog(@"connectionClosedForUser");
}

- (void)session:(QBRTCSession *)session disconnectedFromUser:(NSNumber *)userID {
    
    NSLog(@"disconnectedFromUser");
}

- (void)session:(QBRTCSession *)session disconnectedByTimeoutFromUser:(NSNumber *)userID {
    
    NSLog(@"disconnectedByTimeoutFromUser");
}

- (void)session:(QBRTCSession *)session connectionFailedWithUser:(NSNumber *)userID {
    
    NSLog(@"connectionFailedWithUser");
}

- (void)sessionDidClose:(QBRTCSession *)session {
    
    NSLog(@"sessionDidClose");
}

-(IBAction)endVideoCallBtnTapped:(id)sender{
    [self.onGoingsession hangUp:@{@"hangup" : @"hang up"}];
    [self.navigationController popViewControllerAnimated:YES];
}

**Comment by Pro100Andrey** [comment]
Hi @tvadde, please provide full logs
