### ISSUE TITLE
Playing sounds while in call

### ISSUE THREAD

**Issue by pesho11** [QuickBlox/quickblox-ios-sdk#569]
Hello,
I'm using QuickBlox for video calls and everything is looking great, but I'm having one problem with the audio. I'm using AVAudioPlayer to play sounds, but after the first call my sounds are not working proper at all. I'm trying to play ringing sound until the opponent pick up, then sound for call started and ended (something like FaceTime sounds). After the call is started every sound volume is reduced to minimum, even after the call is ended the sounds volume are still very low.
I'm trying to achieve playing sounds with the same volume level as the call, any ideas how to do that?

QuickBlox versions:
Using QuickBlox (2.7.4)
Using Quickblox-WebRTC (2.2)

**Comment by Raikerian** [comment]
Hi,

Can you show how and where you are setting sound router?

**Comment by pesho11** [comment]
Hello,

I will provide everything you need. I'm pretty much following the instructions on the https://quickblox.com/developers/Sample-webrtc-ios#Getting_Started_with_Video_Calling_API

First in viewDidLoad:
- (void)viewDidLoad
{
    // set up QuickBlox
    [QBRTCClient initializeRTC];
    [QBSettings setApplicationID:kApplicationID];
    [QBSettings setAuthKey:kAuthKey];
    [QBSettings setAuthSecret:kAuthSecret];
    [QBSettings setAccountKey:kAccountKey];
    [QBSettings setLogLevel:QBLogLevelErrors];
    [QBRTCConfig setAnswerTimeInterval:120];
    [QBRTCClient.instance addDelegate:self];

    // set up localVideoView
    QBRTCVideoFormat *videoFormat = [QBRTCVideoFormat videoFormatWithWidth:640 height:480 frameRate:30 pixelFormat:QBRTCPixelFormat420f];
    self.videoCapture = [[QBRTCCameraCapture alloc] initWithVideoFormat:videoFormat position:AVCaptureDevicePositionFront];
    self.videoCapture.previewLayer.frame = self.localVideoView.bounds;
    self.videoCapture.previewLayer.videoGravity = AVLayerVideoGravityResizeAspectFill;
    [self.videoCapture startSession];
    [self.localVideoView.layer insertSublayer:self.videoCapture.previewLayer atIndex:0];
}

After standard set up I'm calling other user. I want to use speakers for sound  output and I have tried several places in the code to switch it and finally I manage to achieve this in:

- (void)session:(QBRTCSession *)session receivedRemoteVideoTrack:(QBRTCVideoTrack *)videoTrack fromUser:(NSNumber *)userID
{
    QBRTCRemoteVideoView *view = [[QBRTCRemoteVideoView alloc] initWithFrame:self.opponentVideoView.bounds];
    [view setVideoTrack:videoTrack];
    [self.opponentVideoView insertSubview:view atIndex:0];

    [QBRTCSoundRouter.instance initialize];
    [QBRTCSoundRouter.instance setCurrentSoundRoute:QBRTCSoundRouteSpeaker];
}

If I move QBRTCSoundRouter methods the sound output is switched back to the receiver after the first call.

**Comment by pesho11** [comment]
If you have problems reproducing the problem I can send you sample project with my implementation

**Comment by Raikerian** [comment]
Are you deinitializing sound router after call ending?

**Comment by pesho11** [comment]
Hello,

I tried using the example from https://quickblox.com/developers/Sample-webrtc-ios#Getting_Started_with_Video_Calling_API

The part "Sound router"
//Save current audio configuration before start call or accept call
[QBRTCSoundRouter.instance initialize];
//Set headphone
QBRTCSoundRouter.instance.currentSoundRoute = QBRTCSoundRouteReceiver;
//or set speaker
QBRTCSoundRouter.instance.currentSoundRoute = QBRTCSoundRouteSpeaker;
//deinitialize after session close 
[QBRTCSoundRouter.instance deinitialize];

Right before my call to start I initialize the sound router and I set the speaker option:
    [QBRTCSoundRouter.instance initialize];
    QBRTCSoundRouter.instance.currentSoundRoute = QBRTCSoundRouteSpeaker;
    self.session = [QBRTCClient.instance createNewSessionWithOpponents:@[@(self.operator.callID)] withConferenceType:QBRTCConferenceTypeVideo];
    self.session.localMediaStream.audioTrack.enabled = YES;
    [self.session startCall:nil];

I deinitialize it after the call is closed:
- (void)sessionDidClose:(QBRTCSession *)session
{
   self.session = nil;
   [QBRTCSoundRouter.instance deinitialize];
}

In this scenario I have issues with the sound thru the speakers, I can't hear anything on the calling device, the speaker or the receiver are not playing any sound. The opponent device is receiving sound normally. 

After several tries the only working solution for me was to use
    [QBRTCSoundRouter.instance initialize];
    QBRTCSoundRouter.instance.currentSoundRoute = QBRTCSoundRouteSpeaker;
in the delegates method session: receivedRemoteVideoTrack: fromUser:. In this case I do not call the deinitialize method and everything is working well. Every call is going thru the speakers and its great. When I try to add my sounds with AVAudioPlayer I have the issues described above, the sound is played with minimum volume after the first call, barely hearable and I can't make it back to normal unless I "kill" the app. Every try I did with [QBRTCSoundRouter.instance deinitialize]; wasn't working for me. 
Any ideas how can I have video call and use AVAudioPlayer for other sounds during the call?

**Comment by pesho11** [comment]
Hello,
is there any solution? 

If it's possible we can arrange a technical call.

**Comment by xpressmobtech** [comment]
@Raikerian i'm having the same issue

**Comment by Raikerian** [comment]
We are aware of this issue and we are currently working on a new version of our WebRTC, which will have absolutely new audio engine (so sound router will be gone). Unfortunately there is no any ETA for the new release yet.

So, for now I can suggest you to look into our QBRTCSoundRouter source files and try to fix it by yourself.
Here they are:

[QBRTCSoundRouter class with implementation file](https://gist.github.com/Raikerian/a60a4d3cdeb7d3f15694c3085d3fc660)

**Comment by Raikerian** [comment]
Hi again @pesho11 ,

We have just released our new WebRTC SDK 2.3 which is containing completely new audio module.
You can now configure category, category options and mode of AVAudioSession used in WebRTC, read more here: http://quickblox.com/developers/Sample-webrtc-ios#Audio_Session_.28Previously_Sound_Router.29

Category options provides such things as Ducking and Mixing, you might want to look more into it.
Here is full changelog of version 2.3: http://quickblox.com/developers/Sample-webrtc-ios#Framework_changelog

Anyway, if you will have any other problems or questions, feel free to start new issue to let us know.

Have a nice holidays.

**Comment by sv-dev2** [comment]
HI 
I implement the video calling. Sound is come and remotevideoTrack delegate is also called but video is not coming i do all the possible things but nothing is worked. I all changes for video showing but cant work. So anybody please help me to solve this issue.
Here is my code for showing the video track in a view.

- (void)session:(QBRTCSession *)session receivedRemoteVideoTrack:(QBRTCVideoTrack *)videoTrack fromUser:(NSNumber *)userID {
    
    
    
    QBRTCRemoteVideoView *view = [[QBRTCRemoteVideoView alloc]initWithFrame:CGRectMake(0, 0, self.callView.frame.size.width, self.callView.frame.size.height)];
    [view setVideoTrack:videoTrack];
    [view setVideoGravity:AVLayerVideoGravityResizeAspectFill];
    
    [self.callView addSubview:view];
    NSLog(@"%@",videoTrack);
    
    
}

**Comment by Raikerian** [comment]
Hi @sv-dev2 

Please create a separate issue and attach as many info as possible.

**Comment by sv-dev2** [comment]
Here is my class, can you please check what i missing here?
