### ISSUE TITLE
Retrieve dialog object by dialog ID

### ISSUE THREAD

**Issue by gandhisahil** [QuickBlox/quickblox-ios-sdk#57]
Is there a way to retrieve the particular dialog by its ID in the iOS-SDK?

**Comment by ems305** [comment]
Look into QBRequest dialogsForPage. Use the extendedRequest parameter to specify the ID.

**Comment by gandhisahil** [comment]
Whats the key for the value of ID? Can you help me out with some code?
Will this work? Also why doesn't `QBChatDialog initWithDialogID:` work?
     QBResponsePage *respPage = [QBResponsePage responsePageWithLimit:1 skip:0];
     QBChatDialog *dialog = [QBRequest dialogsForPage:respPage
                                          extendedRequest:@{@"ID":@"5527e3c5535c12313a002108"}
                                             successBlock:^(QBResponse *response, NSArray *dialogObjects, NSSet *dialogsUsersIDs, QBResponsePage *page) {
                                              //
                                          } errorBlock:^(QBResponse *response) {
                                              // error
                                          }];

**Comment by gandhisahil** [comment]
Whats the key for the value of ID? Can you help me out with some code?
Will this work? Also why doesn't `QBChatDialog initWithDialogID:` work?
    
      QBResponsePage *respPage = [QBResponsePage responsePageWithLimit:1 skip:0];
     QBChatDialog *dialog = [QBRequest dialogsForPage:respPage
                                          extendedRequest:@{@"ID":@"5527e3c5535c12313a002108"}
                                             successBlock:^(QBResponse *response, NSArray *dialogObjects, NSSet *dialogsUsersIDs, QBResponsePage *page) {
                                              //
                                          } errorBlock:^(QBResponse *response) {
                                              // error
                                          }];

**Comment by ems305** [comment]
I would suggest a thorough reading of the documentation (even though it can be confusing at times).

Look here for extended request parameters:
http://quickblox.com/developers/Chat#Dialog_model

In your case you're looking for "_id'

**Comment by soulfly** [comment]
Yes, that will work

     extendedRequest:@{@"_id":@"5527e3c5535c12313a002108"}
