### ISSUE TITLE
How can i implement stickers in to my iOS code

### ISSUE THREAD

**Issue by balat1607** [QuickBlox/quickblox-ios-sdk#572]
I am integrating Stickers to my chatviewcontroller . 

But am not able to understand how can i take it forward , There is some code snippet provided on Quickblox documentation but confused where to place the code and how to handle stickers . 

https://quickblox.com/developers/SimpleSample-chat_users-ios#Stickers

1 . pod "StickerPipe"  - Done 
2 . [STKStickersManager initWitApiKey:@"API_KEY"];   - Done 
3.  if ([STKStickersManager isStickerMessage:message]) {
    [self.stickerImageView stk_setStickerWithMessage:message placeholder:nil placeholderColor:nil progress:nil completion:nil];
}

Is this the code i need to write for Input textview on chat . And how 

4. @property (strong, nonatomic) STKStickerController *stickerController;
 
self.inputTextView.inputView = self.stickerController.stickersView;
[self reloadStickersInputViews];

Wrote the property , but not sure how to handle the sticker 

5 . - (void)stickerController:(STKStickerController *)stickerController didSelectStickerWithMessage:(NSString *)message {
 
    //Send sticker message
}

What would be the code inside the delegate . 

Please suggest .

**Comment by balat1607** [comment]
Could you please reopen 573 and close this issue (572) . We both are from same team . He is also working along with me .

**Comment by balat1607** [comment]
Or not a problem let us know how to start of with

**Comment by Raikerian** [comment]
Hi @balat1607 

The code inside the delegate should be send message code. You are basically should send a message with sticker ID in custom data. And when you are receiving sticker, you should show appropriate sticker by taking ID from custom data. You also need to create a specific cell (see QMChatCell) to display sticker.
