### ISSUE TITLE
How can i implement stickers in to my iOS code

### ISSUE THREAD

**Issue by ajayrigaps** [QuickBlox/quickblox-ios-sdk#573]
I am integrating Stickers to my chatviewcontroller .
But am not able to understand how can i take it forward , There is some code snippet provided on Quickblox documentation but confused where to place the code and how to handle stickers .
https://quickblox.com/developers/SimpleSample-chat_users-ios#Stickers
1 . pod "StickerPipe" - Done  2 . [STKStickersManager initWitApiKey:@"API_KEY"]; - Done  3. if ([STKStickersManager isStickerMessage:message]) { [self.stickerImageView stk_setStickerWithMessage:message placeholder:nil placeholderColor:nil progress:nil completion:nil]; }
Is this the code i need to write for Input textview on chat . And how
	1.	@property (strong, nonatomic) STKStickerController *stickerController;
self.inputTextView.inputView = self.stickerController.stickersView; [self reloadStickersInputViews];
Wrote the property , but not sure how to handle the sticker
5 . - (void)stickerController:(STKStickerController *)stickerController didSelectStickerWithMessage:(NSString *)message {
//Send sticker message
}
What would be the code inside the delegate .
Please suggest .

**Comment by VitaliyGuru** [comment]
closed as duplicated [572](https://github.com/QuickBlox/quickblox-ios-sdk/issues/572)
