### ISSUE TITLE
Login not happening

### ISSUE THREAD

**Issue by KuriakosePious** [QuickBlox/quickblox-ios-sdk#575]
**Environment details**
*iOS 9, Quickblox iOS SDK version 2.7,

**Did this work before?**

NO

**Expected behavior**

LOGIN/SIGNUP

**Actual behavior**
Getting error.

**Logs**
https://gist.github.com/KuriakosePious/b40ee2550b8f62f98da4f1171aaac12a

**Comment by Pro100Andrey** [comment]
Hi @KuriakosePious, https://gist.github.com/kuruvi37/b40ee2550b8f62f98da4f1171aaac12a - 404

**Comment by KuriakosePious** [comment]
[QBCore] Response error: Error Domain=NSURLErrorDomain Code=-999 "cancelled" UserInfo={NSErrorFailingURLKey=https://api.dev.quickblox.com/session.json, NSErrorFailingURLStringKey=https://api.dev.quickblox.com/session.json, NSLocalizedDescription=cancelled} 2016-08-17 16:10:33.207 MediEN[270:54815] [QBCore] Response error reasons: { error = { message = cancelled; }; } 2016-08-17 16:10:33.208 MediEN[270:54815] [QBAuth] Create Session request error: (null) 2016-08-17 16:10:33.221 MediEN[270:54898] [QBCore] Response error: Error Domain=NSURLErrorDomain Code=-999 "cancelled" UserInfo={NSErrorFailingURLKey=https://api.dev.quickblox.com/session.json, NSErrorFailingURLStringKey=https://api.dev.quickblox.com/session.json, NSLocalizedDescription=cancelled} 2016-08-17 16:10:33.222 MediEN[270:54898] [QBCore] Response error reasons: { error = { message = cancelled; }; }

**Comment by KuriakosePious** [comment]
@Pro100Andrey please have a look at above log

**Comment by VitaliyGuru** [comment]
Hi @KuriakosePious ,
Could you please show your code snippet for login/sign up?

**Comment by VitaliyGuru** [comment]
@KuriakosePious Do you use custom endpoints?

**Comment by KuriakosePious** [comment]
[QBSettings setApplicationID:44907];
    [QBSettings setAuthKey:@"qha5pegavkq-n-K"];
    [QBSettings setAuthSecret:@"BTFsj7Rtt27DAmT"];
    [QBSettings setAccountKey:@"Ep97pSstBQ9WQfw"];
     [QBSettings setChatDNSLookupCacheEnabled:YES];
    [QBSettings setServiceZone:3];
    QBUUser *user = [QBUUser user];
    user.login = @"kuriakose2";
    user.password = @"kuriakose37";
    
    
    
    [QBRequest signUp:user successBlock:^(QBResponse * _Nonnull response, QBUUser * _Nullable user) {
        [self showAlertWithMessage:response.debugDescription title:response.description];
    } errorBlock:^(QBResponse * _Nonnull response) {
        [self showAlertWithMessage:response.debugDescription title:response.description];
    }];


@Pro100Andrey  only this one.

**Comment by Pro100Andrey** [comment]
[QBSettings setServiceZone:3]; ?

**Comment by KuriakosePious** [comment]
@Pro100Andrey  for setting developement mode (tried with and without this).

**Comment by Pro100Andrey** [comment]
@KuriakosePious remove this

**Comment by KuriakosePious** [comment]
@Pro100Andrey  done, but same issue exist.

**Comment by Pro100Andrey** [comment]
@KuriakosePious please provide logs without  [QBSettings setServiceZone:3]

**Comment by Pro100Andrey** [comment]
@KuriakosePious + set [QBSettings setLogLevel:QBLogLevelDebug];

**Comment by Pro100Andrey** [comment]
@KuriakosePious and provide full logs

**Comment by KuriakosePious** [comment]
@Pro100Andrey 

[QBAuth] Create Session request error: {"errors":{"base":["Unexpected signature"]}}
2016-08-17 19:02:10.036 MediEN[303:76499] [QBCore] Response error: Error Domain=com.alamofire.error.serialization.response Code=-1011 "Request failed: client error (422)" UserInfo={com.alamofire.serialization.response.error.response=<NSHTTPURLResponse: 0x16fa1900> { URL: https://api.quickblox.com/session.json } { status code: 422, headers {
    "Access-Control-Allow-Origin" = "*";
    "Cache-Control" = "no-cache";
    Connection = "keep-alive";
    "Content-Length" = 44;
    "Content-Type" = "application/json; charset=utf-8";
    Date = "Wed, 17 Aug 2016 13:32:10 GMT";
    "QuickBlox-REST-API-Version" = "0.1.1";
    Server = "openresty/1.9.15.1";
    Status = "422 Unprocessable Entity";
    "X-Rack-Cache" = "invalidate, pass";
    "X-Request-Id" = 9cfcb76928f575868ddafd5427ed2b16;
    "X-Runtime" = "0.012644";
    "X-UA-Compatible" = "IE=Edge,chrome=1";
} }, NSLocalizedRecoverySuggestion={"errors":{"base":["Unexpected signature"]}}, NSErrorFailingURLKey=https://api.quickblox.com/session.json, NSLocalizedDescription=Request failed: client error (422), com.alamofire.serialization.response.error.data=<7b226572 726f7273 223a7b22 62617365 223a5b22 556e6578 70656374 65642073 69676e61 74757265 225d7d7d>}
2016-08-17 19:02:10.041 MediEN[303:76499] [QBCore] Response error reasons: {
    errors =     {
        base =         (
            "Unexpected signature"
        );
    };
}

**Comment by Pro100Andrey** [comment]
@KuriakosePious please check your settings with admin panel :
    [QBSettings setAccountKey:@""];
    [QBSettings setApplicationID:];
    [QBSettings setAuthKey:@""];
    [QBSettings setAuthSecret:@""];

**Comment by KuriakosePious** [comment]
where i can get AccountKey

**Comment by KuriakosePious** [comment]
@Pro100Andrey  my setAuthSecret was wrong

**Comment by Pro100Andrey** [comment]
@KuriakosePious - worked now ?

**Comment by KuriakosePious** [comment]
@Pro100Andrey  no asking for  AccountKey from where i can get it?

**Comment by Pro100Andrey** [comment]
Profile -> Settings ->

**Comment by KuriakosePious** [comment]
@Pro100Andrey  @VitaliyGuru  thanks alot it's working now.

**Comment by Pro100Andrey** [comment]
@KuriakosePious , please close issue :)

**Comment by primeappsin** [comment]
Getting error 404 always

ServicesManager.instance().downloadCurrentEnvironmentUsers(successBlock: { (users) -> Void in
                        
                        guard let unwrappedUsers = users else {
                            
                            SVProgressHUD.showError(withStatus: "No users downloaded")
                            return
                        }
                        
                        SVProgressHUD.showSuccess(withStatus: "SA_STR_COMPLETED".localized())
                        
                        
                    }, errorBlock: { (error) -> Void in
                        
                        SVProgressHUD.showError(withStatus: error.localizedDescription)
                    })
