### ISSUE TITLE
Multiple messages are displaying with delay while sending at a time.

### ISSUE THREAD

**Issue by ajay2c9** [QuickBlox/quickblox-ios-sdk#576]
Hi,
I created a group chat with 5 and more users. When users are sending messages at a time continuously those messages are displaying lately. how to displaying the messages fastly without delay. We are using the Starter account.
Quickblox SDK Version is 2.7

Thank you

**Comment by VitaliyGuru** [comment]
Hi @ajay2c9 ,
What did you mean when you wrote "those messages are displaying lately. how to displaying the messages fastly without delay." ? Could you explain in more detail actual and expected behaviour?

**Comment by ajay2c9** [comment]
Group chat is started with 5 users and those users are sending messages continuously. After Sending few messages (150 messages and more ) sending messages are displaying with delay.

Thank you

**Comment by VitaliyGuru** [comment]
@ajay2c9  Have you faced with this problem in our chat sample?

**Comment by Raikerian** [comment]
Hi @ajay2c9 

Are you using QMChatViewController? If yes, at this moment we are displaying messages in controller only when server did notify us about success of message sending. We are currently working on more user friendly message displaying.

**Comment by VitaliyGuru** [comment]
@ajay2c9 Any updates?
