### ISSUE TITLE
Notification badge count for QBChatMessage & QBMEvent

### ISSUE THREAD

**Issue by aperotech** [QuickBlox/quickblox-ios-sdk#578]
**Environment details**
iOS 8+ , Quickblox iOS SDK version v2.7.2

This is a question involving  QBChatMessage and QBMEvent and managing badge count in iOS.

We are using both Chat & Push Notification services in our app. I understand - 
1. Different options available to set the badge count in Chat (1, unread count, none)
2. Setting the iOS_badge parameter in QBMEvent 

Is there a way for us to manage both together so that the correct badge count is shown? As an example - 
1. I receive an event, having a badge of 1.
2. I receive 3 chat messages, having badge value 3. **Total badge count should now be 4** , however, it gets overridden to 3. 

Any thoughts on this will be appreciated. Thanks.

**Comment by Raikerian** [comment]
Hi,

If you are using [automatic chat alerts](http://quickblox.com/developers/Chat#Alerts) it will always override your current badge to number of unread messages on server.

**Comment by Pro100Andrey** [comment]
@aperotech Any updates?
