### ISSUE TITLE
QuickBlox Airplay Audio not working

### ISSUE THREAD

**Issue by rajatsis** [QuickBlox/quickblox-ios-sdk#579]
**Environment details**
iOS version - 9.3
QuickBlox iOS SDK version - 2.7.6 
QuickbloxWebRTC SDK version - (v2.2, r11951)

I have tried to extend the display of my iPhone to my Mac via AirPlay and it is working fine but the Audio is not coming through Mac the audio is still coming from the speaker of iPhone.

I have also tried to Play a video through my app on Mac through Airplay and in that case the Audio and Video both are working fine.

So i just want to know whether the Audio with Airplay is supported by QuickBlox or not ? Also is there any workaround for that ?

Thanks

**Comment by Raikerian** [comment]
Hi,

It is not possible to stream audio from calls through air play because device cannot play and record at the same time. Therefore iOS device will not display any of the air play servers while you are in call.
See http://stackoverflow.com/questions/11319100/avaudiosessioncategoryplayandrecord-with-airplay

**Comment by rajatsis** [comment]
@Raikerian but i have checked Skype also and through Skype Audio is playing through Airplay.

**Comment by Raikerian** [comment]
@rajatsis State as of now is this is a confirmed bug/not available feature. New version will have AVAudioSession category options customization, this will also add AirPlay and Bluetooth support. Expect it near the end of December.

**Comment by Raikerian** [comment]
We have just released our new WebRTC SDK 2.3 which is containing completely new audio module.
You can now configure category, category options and mode of AVAudioSession used in WebRTC, read more here: http://quickblox.com/developers/Sample-webrtc-ios#Audio_Session_.28Previously_Sound_Router.29

Basically, according to doc in the link I have provided, you need to set `configuration.mode = AVAudioSessionModeVideoChat`. This will play audio only through speakers, but will fully support airplay audio mirror.

Here is full changelog of version 2.3: http://quickblox.com/developers/Sample-webrtc-ios#Framework_changelog

Anyway, if you will have any other problems or questions, feel free to start new issue to let us know.

Have a nice holidays.
