### ISSUE TITLE
upgraded from starter, app stopped working

### ISSUE THREAD

**Issue by mgiraldo** [QuickBlox/quickblox-ios-sdk#58]
I upgraded from the Free tier to Advanced and the app stopped working. Is there a status page for the advanced service? status.quickblox.com is only for the free tier. I am unsure if the problem I am having is due to the service being down or some other issue.

I can see users and try to initiate a call but neither `chatCallDidAcceptByUser:` nor `chatCallDidAcceptByUser:customParameters:` get fired. The only change I made was upgrading to the paid version.

iOS SDK 2.2.3

**Comment by soulfly** [comment]
Hey, 

status.quickblox.com is also for Advanced and Pro

do you have any other details of that issue?Can you post Xcode log of caller side

**Comment by mgiraldo** [comment]
Got it. Thanks for the reply. I managed to get it working. The problem was `chatCallDidAcceptByUser:customParameters:` not liking the `customParameters` but also not throwing any errors.

The status site should be more informative. It is very hard to diagnose when the error is due to the service being down and this not being evident in the site.
