### ISSUE TITLE
Revert back deleted chat dialogs from admin panel

### ISSUE THREAD

**Issue by nirav700** [QuickBlox/quickblox-ios-sdk#584]
Hello team

From admin panel i have by mistakely removed some chat dialogs, its possible i can get back that chat dialogs.

Please help me because my application is live.

**Comment by Raikerian** [comment]
Hi,

Please leave your App ID. Also, are you on shared instance?

**Comment by nirav700** [comment]
Hi @Raikerian 

Thanks for replay my Application ID is 36853 , please have look from your side.

And, sorry I could understand by shared instance? can you please elaborate ?

I need to fix this as soon as possible, my application users is live and I afford to loose them.

**Comment by Raikerian** [comment]
@nirav700 has your problem been solved?

**Comment by nirav700** [comment]
NO it's not resolved by your end...

but I have added all the users and dialog manually in quickblox , because I don't loose my users.

you guys are not supporting , you give me replayed after 7 days latter , how you build product ?

any way I am wasting time on you please close these issues, I don't need your help any more thanks.
