### ISSUE TITLE
Swift - How to search user with full name in swift.

### ISSUE THREAD

**Issue by vibha22** [QuickBlox/quickblox-ios-sdk#585]
Please help me with Quickblox search bar implementation in swift. I need search functionality for quickblox. Please help.

In Objective c -  [[[QMCore instance].usersService searchUsersWithFullName:self.cachedSearchText page:self.responsePage] continueWithBlock:^id _Nullable(BFTask<NSArray<QBUUser *> *> * _Nonnull task) {
        
        [UIApplication sharedApplication].networkActivityIndicatorVisible = NO;
        

But in swift I am not able to implement.

**Comment by VitaliyGuru** [comment]
@vibha22 HI!

` let fullName = "Foo Bar"
            let page = QBGeneralResponsePage(currentPage: 0, perPage:100)
            
            QMServicesManager.instance().usersService.searchUsersWithFullName(fullName, page: page).continueWithBlock({
                [weak self](task :BFTask!) -> AnyObject? in
                UIApplication.sharedApplication().networkActivityIndicatorVisible = false
                return nil
                })`

**Comment by vibha22** [comment]
Yes..It work.. Thanks @VitaliyGuru
