### ISSUE TITLE
Image Url: privateUrlForID deprecated

### ISSUE THREAD

**Issue by LucasCoelho** [QuickBlox/quickblox-ios-sdk#588]
I'm having the exact same problem as https://github.com/QuickBlox/quickblox-ios-sdk/issues/333 only I don't understand how he solved it.

I used to have `QBCBlob.privateUrlForID(blobID)` which worked fine and returned the link to the image but is now deprecated ("http://myApp.quickblox.com/blobs/4154973/download?token=myToken")

Now `QBCBlob.privateUrlForFileUID(blobID)` returns a link to a json ("http://myApp.quickblox.com/blobs/4154973.json?token=myToken")

**Comment by VitaliyGuru** [comment]
Hi @LucasCoelho,
For new method you should use blob.UID instead of blob.ID

**Comment by LucasCoelho** [comment]
I'm not sure I understand. I am not using blob.ID

In my case blobID is a number that corresponds to the image file.

**Comment by VitaliyGuru** [comment]
@LucasCoelho 
When you use method:

```
+ (QB_NONNULL QBRequest *)TUploadFile:(QB_NONNULL NSData *)data
                             fileName:(QB_NONNULL NSString *)fileName
                          contentType:(QB_NONNULL NSString *)contentType
                             isPublic:(BOOL)isPublic
                         successBlock:(QB_NULLABLE void(^)(QBResponse * QB_NONNULL_S response, QBCBlob * QB_NONNULL_S blob))successBlock
                          statusBlock:(QB_NULLABLE QBRequestStatusUpdateBlock)statusBlock
                           errorBlock:(QB_NULLABLE void(^)(QBResponse * QB_NONNULL_S response))errorBlock;

```
You will receive blob with UID not ID.

Does you blob have value for UID?

**Comment by LucasCoelho** [comment]
The images were already uploaded. I'm having trouble retrieving them.

**Comment by VitaliyGuru** [comment]
Does you blob have value for UID?

**Comment by LucasCoelho** [comment]
I don't think we're using a blob

**Comment by VitaliyGuru** [comment]
In the problem https://github.com/QuickBlox/quickblox-ios-sdk/issues/333 user handles blobs (instance of QBCBlob) and they have UID. So he can download file using blob's UID with method QBCBlob.privateUrlForFileUID(blobUID).

If you store only ID for files, not UID , then you should use deprecated method QBCBlob.privateUrlForID(blobID).

**Comment by VitaliyGuru** [comment]
@LucasCoelho 

Alternative way to download file by id is: 

```
[QBRequest downloadFileWithID:ID.integerValue successBlock:^(QBResponse *response, NSData *fileData) {
            if (completion) {
                completion(error, image);
            }
            
        } statusBlock:^(QBRequest *request, QBRequestStatus *status) {
           
        } errorBlock:^(QBResponse *response) {
            if (completion) {
                completion(response.error.error, nil);
            }
            
        }];
```

**Comment by VitaliyGuru** [comment]
@LucasCoelho  Do you have any issue-related questions? Feel free to ask.

**Comment by Raikerian** [comment]
@LucasCoelho if you are still having any troubles, please let us know by creating a separate issue.
