### ISSUE TITLE
downloadFileWithUID returns invalid data.

### ISSUE THREAD

**Issue by aprat** [QuickBlox/quickblox-ios-sdk#59]
When I try to retrieve an image using the new method, the ```objectivec imageWithData ``` is nil although the data is not. It looks like that the data returned is the blob metadata or something like that.
It only occurs in this method, the deprecated method to download a file works perfectly.

Upload code:
```objectivec
    NSData *avatar = UIImageJPEGRepresentation(self.avatar.image, 0.7);
    if (0 < avatar.length)
    {
        NSString * fileName = [NSString stringWithFormat:@"avatar-%lu",(unsigned long)[LocalStorageService shared].currentUser.ID];
        [QBRequest TUploadFile:avatar
                      fileName:fileName
                   contentType:@"image/jpeg"
                      isPublic:YES
                  successBlock:^(QBResponse *response, QBCBlob *blob) {
                      self.uploadedFileID    = blob.ID;
                      [self updateProfile];
        }
                   statusBlock:nil
                    errorBlock:nil];
    }
```

Download code:
```objectivec
    [QBRequest downloadFileWithUID:[NSString stringWithFormat:@"%lu", (unsigned long)[LocalStorageService shared].currentUser.blobID]
                      successBlock:^(QBResponse *response, NSData *fileData) {
                          UIImage *image = [UIImage imageWithData:fileData];
                          if (image) {
                              self.avatar.image = image;
                          } else {
                              //!!!: DEPRECATED but working!
                              [QBContent TDownloadFileWithBlobID:[LocalStorageService shared].currentUser.blobID delegate:[[PCTDownloadAvatarDelegate alloc]initWithImageView:self.avatar]];
                          }
                      }
                       statusBlock:nil
                        errorBlock:^(QBResponse *response) {
                            DLog(@"%@",response.description);
                        }
     ];

```

Returned data information:
![captura de pantalla 2015-04-14 a las 16 23 51](https://cloud.githubusercontent.com/assets/3799567/7138847/11fe8c90-e2c3-11e4-8320-0131037d5561.png)

**Comment by iSevenDays** [comment]
Console log shows me that the content type is application/xml, but it should be image/jpeg. I've tested your code in http://quickblox.com/developers/IOS/sample-content-2.0 and the image has been successfully uploaded to the server. To debug your problem please send me your test project or test credentials.

**Comment by iSevenDays** [comment]
Lets take a deeper look into the problem.
1. The image has a name "avatar-1148712"
2. I applied your settings to the Sample-content iOS application.
3. Everything works as expected
See a log at http://pastebin.com/XT0yMWV1 (link will expire tomorrow)
As you can see
2015-04-15 16:25:22.860 Content[3962:362748] progress for avatar-1148712: 0.558178
2015-04-15 16:25:23.016 Content[3962:362748] progress for avatar-1148712: 1.000000

I have downloaded and successfully displayed your images.

![img_0920](https://cloud.githubusercontent.com/assets/3992716/7159755/123b59e8-e38d-11e4-9030-dea9a7c0b494.jpg)


4. Compare your code with http://quickblox.com/developers/IOS/sample-content-2.0

**Comment by aprat** [comment]
Ok, my mistake. 
Instead of using the blob.UID, I've been using the blob.ID
