### ISSUE TITLE
QBMEvent: custom parameters for message occur wrong push

### ISSUE THREAD

**Issue by neshyurik** [QuickBlox/quickblox-ios-sdk#591]
I'm using Quickblox to send remote notifications via APNs from iPhones using the Quickblox iOS SDK.
When I create event and set custom parameters to message like in documentation it sends me JSON instead of normal message. It's look like { message: "Hi!", "ios_badge" : "6" }

            QBMEvent *event = [QBMEvent event];
            event.notificationType = QBMNotificationTypePush;
            event.type = QBMEventTypeFixedDate;
            event.date = dateToSend;
            event.pushType = QBMPushTypeAPNS;
            
            NSMutableDictionary  *dictPush = [NSMutableDictionary  dictionary];
            [dictPush setObject:@"You have a new ClipOn!" forKey:@"message"];
            [dictPush setObject:[NSString stringWithFormat:@"%lu", self.badgeCount] forKey:@"ios_badge"];
            
            NSError *error = nil;
            NSData *sendData = [NSJSONSerialization dataWithJSONObject:dictPush options:NSJSONWritingPrettyPrinted error:&error];
            NSString *jsonString = [[NSString alloc] initWithData:sendData encoding:NSUTF8StringEncoding];

            event.message = jsonString;
            
            event.usersIDs = [NSString stringWithFormat:@"%lu", (unsigned long)user.ID];
            //event.isDevelopmentEnvironment = ![QBApplication sharedApplication].productionEnvironmentForPushesEnabled;
            
            [QBRequest createEvent:event successBlock:^(QBResponse *response, NSArray *events) {
                if (user.email) {
                    
                    QBMEvent *event = [QBMEvent event];
                    event.notificationType = QBMNotificationTypeEmail;
                    event.type = QBMEventTypeFixedDate;
                    event.date = dateToSend;
                    
                    event.usersIDs = [NSString stringWithFormat:@"%lu", (unsigned long)user.ID];
                    
                    event.message = @"You have a new ClipOn!";
                    
                    [QBRequest createEvent:event successBlock:^(QBResponse *response, NSArray *events) {
                        
                    }
                                errorBlock:^(QBResponse *response) {
                                    
                                }];
                }
            }
                        errorBlock:^(QBResponse *response) {
                            
                        }];

*iOS version, Quickblox iOS SDK version, QuickbloxWebRTC SDK version (optional)*
IOS 9.3.1 (Deployment target -8.0)
Xcode Version 7.3.1

*Logs 
<__NSArrayI 0x136413570>(

  [QBMEvent]:
  ID:8593555
  created at:2016-08-30 11:27:30 AM +0000
  updated at:2016-08-30 11:27:30 AM +0000
  active:YES
  notificationType:push
  pushType:apns
  usersIDs:15717173
  usersExternalIDs:(null)
  usersTagsAny:(null)
  usersTagsAll:(null)
  usersTagsExclude:(null)
  name:(null)
  message:payload=eyJhcHMiOnsiYWxlcnQiOiJ7XG4gIFwibWVzc2FnZVwiIDogXCJZb3UgaGF2ZSBhIG5ldyBDbGlwT24hXCIsXG4gIFwiaW9zX2JhZGdlXCIgOiBcIjExXCJcbn0iLCJzb3VuZCI6ImRlZmF1bHQifX0=
  type:fixed_date
  date:2016-08-30 11:28:25 AM +0000
  endDate:(null)
  period:0
  occuredCount:0
  senderID:15717173
)

**Comment by VitaliyGuru** [comment]
Hello @neshyurik , Try to remove this line `event.pushType = QBMPushTypeAPNS;`and send again.

**Comment by neshyurik** [comment]
@VitaliyGuru Thank you 👍 Now everything is perfect!

**Comment by soulfly** [comment]
More info is here
http://quickblox.com/developers/SimpleSample-messages_users-ios#Platform_based_Push_Notifications

**Comment by manojkraftly** [comment]
How it will work Android to iOS?

**Comment by wayupdev** [comment]
Hello @neshyurik, I'm very interested in one of your projects. How can I contact you?
