### ISSUE TITLE
Unexpectedly found nil while unwrapping an optional value... trying to receive localvideoview

### ISSUE THREAD

**Issue by xpressmobtech** [QuickBlox/quickblox-ios-sdk#594]
I'm trying to receive local video view using QBRTCCameraCapture method, i am using iphone 5c to test iOS 9.3.4, i will include both my code and logs down below. 

Here is my entire code so far:

import UIKit
import Quickblox
import AVFoundation

class VideoCallController: UIViewController, QBRTCClientDelegate {

    @IBOutlet weak var localVideoView: UIView!
    
    var videoCapture: QBRTCCameraCapture?
    
    override func viewDidLoad() {
        super.viewDidLoad()

        QBRTCClient.instance().addDelegate(self)
        
        let videoFormat = QBRTCVideoFormat.init()
        videoFormat.frameRate = 30
        videoFormat.pixelFormat = QBRTCPixelFormat.Format420v
        videoFormat.width = 640
        videoFormat.height = 480
        
        self.videoCapture = QBRTCCameraCapture.init(videoFormat: videoFormat!, position: AVCaptureDevicePosition.Front)
        self.videoCapture!.previewLayer.frame = self.localVideoView.frame
        self.videoCapture!.startSession()
        self.localVideoView.layer.insertSublayer(self.videoCapture!.previewLayer, atIndex: 0)
        
        
    }   
}
 
//-------------------------------------------------------------------------

my error logs:

libswiftCore.dylib`function signature specialization <Arg[0] = Exploded, Arg[1] = Exploded, Arg[2] = Dead, Arg[3] = Dead> of Swift._fatalErrorMessage (Swift.StaticString, Swift.StaticString, Swift.StaticString, Swift.UInt) -> ():
    0x18ee064 <+0>:   push   {r4, r5, r6, r7, lr}
    0x18ee068 <+4>:   add    r7, sp, #12
    0x18ee06c <+8>:   push   {r8, r10, r11}
    0x18ee070 <+12>:  sub    sp, sp, #40
    0x18ee074 <+16>:  bfc    sp, #0, #3
    0x18ee078 <+20>:  mov    r11, r3
    0x18ee07c <+24>:  mov    r6, r0
    0x18ee080 <+28>:  ldr    r0, [r7, #0xc]
    0x18ee084 <+32>:  ldr    r3, [r7, #0x8]
    0x18ee088 <+36>:  tst    r2, #1
    0x18ee08c <+40>:  bne    0x18ee0b0                 ; <+76>
    0x18ee090 <+44>:  cmp    r1, #0
    0x18ee094 <+48>:  blt    0x18ee0d8                 ; <+116>
    0x18ee098 <+52>:  add    r1, r6, r1
    0x18ee09c <+56>:  str    r0, [sp]
    0x18ee0a0 <+60>:  mov    r0, r6
    0x18ee0a4 <+64>:  mov    r2, r11
    0x18ee0a8 <+68>:  bl     0x1943138                 ; function signature specialization <Arg[0] = Exploded, Arg[1] = Exploded> of Swift.(_fatalErrorMessage (Swift.StaticString, Swift.StaticString, Swift.StaticString, Swift.UInt) -> ()).(closure #2)
->  0x18ee0ac <+72>:  trap   
    0x18ee0b0 <+76>:  mov    r0, #0
    0x18ee0b4 <+80>:  str    r0, [sp, #0x24]
    0x18ee0b8 <+84>:  str    r0, [sp, #0x20]
    0x18ee0bc <+88>:  lsr    r0, r6, #11
    0x18ee0c0 <+92>:  cmp    r0, #26
    0x18ee0c4 <+96>:  bhi    0x18ee100                 ; <+156>
    0x18ee0c8 <+100>: lsr    r0, r6, #16
    0x18ee0cc <+104>: cmp    r0, #16
    0x18ee0d0 <+108>: bhi    0x18ee14c                 ; <+232>
    0x18ee0d4 <+112>: b      0x18ee110                 ; <+172>
    0x18ee0d8 <+116>: mov    r0, #2
    0x18ee0dc <+120>: str    r0, [sp, #0x4]
    0x18ee0e0 <+124>: mov    r1, #39
    0x18ee0e4 <+128>: movw   r0, #0xfd6e
    0x18ee0e8 <+132>: movt   r0, #0xa
    0x18ee0ec <+136>: add    r0, pc, r0
    0x18ee0f0 <+140>: movw   r3, #0xff60
    0x18ee0f4 <+144>: movt   r3, #0xa
    0x18ee0f8 <+148>: add    r3, pc, r3
    0x18ee0fc <+152>: b      0x18ee390                 ; <+812>
    0x18ee100 <+156>: cmp    r6, #57344
    0x18ee104 <+160>: blo    0x18ee174                 ; <+272>
    0x18ee108 <+164>: cmp    r6, #1114112
    0x18ee10c <+168>: bhs    0x18ee14c                 ; <+232>
    0x18ee110 <+172>: cmp    r6, #128
    0x18ee114 <+176>: blo    0x18ee19c                 ; <+312>
    0x18ee118 <+180>: lsr    r3, r6, #6
    0x18ee11c <+184>: mov    r1, #0
    0x18ee120 <+188>: cmp    r1, r6, lsr #11
    0x18ee124 <+192>: bne    0x18ee1b0                 ; <+332>
    0x18ee128 <+196>: mov    r0, #0
    0x18ee12c <+200>: str    r0, [sp, #0x18]
    0x18ee130 <+204>: mvn    r0, #63
    0x18ee134 <+208>: orr    r3, r3, r0
    0x18ee138 <+212>: str    r3, [sp, #0x1c]
    0x18ee13c <+216>: mov    r8, #0
    0x18ee140 <+220>: mov    r0, #0
    0x18ee144 <+224>: str    r0, [sp, #0x14]
    0x18ee148 <+228>: b      0x18ee23c                 ; <+472>
    0x18ee14c <+232>: mov    r0, #2
    0x18ee150 <+236>: str    r0, [sp, #0x4]
    0x18ee154 <+240>: mov    r1, #37
    0x18ee158 <+244>: movw   r0, #0xfcfa
    0x18ee15c <+248>: movt   r0, #0xa
    0x18ee160 <+252>: add    r0, pc, r0
    0x18ee164 <+256>: movw   r3, #0xaac
    0x18ee168 <+260>: movt   r3, #0xb
    0x18ee16c <+264>: add    r3, pc, r3
    0x18ee170 <+268>: b      0x18ee390                 ; <+812>
    0x18ee174 <+272>: mov    r0, #2
    0x18ee178 <+276>: str    r0, [sp, #0x4]
    0x18ee17c <+280>: mov    r1, #71
    0x18ee180 <+284>: movw   r0, #0xfcd2
    0x18ee184 <+288>: movt   r0, #0xa
    0x18ee188 <+292>: add    r0, pc, r0
    0x18ee18c <+296>: movw   r3, #0xa34
    0x18ee190 <+300>: movt   r3, #0xb
    0x18ee194 <+304>: add    r3, pc, r3
    0x18ee198 <+308>: b      0x18ee390                 ; <+812>
    0x18ee19c <+312>: mov    r8, #0
    0x18ee1a0 <+316>: mov    r0, #0
    0x18ee1a4 <+320>: str    r0, [sp, #0x1c]
    0x18ee1a8 <+324>: mov    r10, #0
    0x18ee1ac <+328>: b      0x18ee2cc                 ; <+616>
    0x18ee1b0 <+332>: lsr    r0, r6, #12
    0x18ee1b4 <+336>: cmp    r1, r6, lsr #16
    0x18ee1b8 <+340>: bne    0x18ee1d4                 ; <+368>
    0x18ee1bc <+344>: mvn    r1, #31
    0x18ee1c0 <+348>: orr    r0, r0, r1
    0x18ee1c4 <+352>: mov    r2, #0
    0x18ee1c8 <+356>: mov    r1, #0
    0x18ee1cc <+360>: mov    r9, #0
    0x18ee1d0 <+364>: b      0x18ee200                 ; <+412>
    0x18ee1d4 <+368>: mov    r1, #240
    0x18ee1d8 <+372>: orr    r1, r1, r6, lsr #18
    0x18ee1dc <+376>: uxtb   r2, r1
    0x18ee1e0 <+380>: cmp    r1, r2
    0x18ee1e4 <+384>: bne    0x18ee2f8                 ; <+660>
    0x18ee1e8 <+388>: mvn    r2, #-67108863
    0x18ee1ec <+392>: bfi    r0, r2, #6, #26
    0x18ee1f0 <+396>: mov    r9, #0
    0x18ee1f4 <+400>: str    r9, [sp, #0x24]
    0x18ee1f8 <+404>: str    r1, [sp, #0x20]
    0x18ee1fc <+408>: mov    r2, #1
    0x18ee200 <+412>: lsl    r5, r2, #3
    0x18ee204 <+416>: mvn    r4, #-67108863
    0x18ee208 <+420>: bfi    r3, r4, #6, #26
    0x18ee20c <+424>: str    r3, [sp, #0x1c]
    0x18ee210 <+428>: uxtb   r0, r0
    0x18ee214 <+432>: mov    r4, #31
    0x18ee218 <+436>: eor    r4, r4, r2, lsl #3
    0x18ee21c <+440>: lsr    r3, r0, #1
    0x18ee220 <+444>: orr    r1, r1, r0, lsl r5
    0x18ee224 <+448>: str    r1, [sp, #0x14]
    0x18ee228 <+452>: orr    r0, r9, r3, lsr r4
    0x18ee22c <+456>: str    r0, [sp, #0x18]
    0x18ee230 <+460>: str    r1, [sp, #0x20]
    0x18ee234 <+464>: str    r0, [sp, #0x24]
    0x18ee238 <+468>: add    r8, r2, #1
    0x18ee23c <+472>: mov    r0, #8
    0x18ee240 <+476>: smull  r10, r5, r8, r0
    0x18ee244 <+480>: mov    r4, #0
    0x18ee248 <+484>: mov    r2, #8
    0x18ee24c <+488>: mov    r3, #0
    0x18ee250 <+492>: mov    r0, r10
    0x18ee254 <+496>: mov    r1, r5
    0x18ee258 <+500>: bl     0x19afea8                 ; symbol stub for: __udivdi3
    0x18ee25c <+504>: eor    r1, r1, r8, asr #31
    0x18ee260 <+508>: eor    r0, r0, r8
    0x18ee264 <+512>: orrs   r0, r0, r1
    0x18ee268 <+516>: bne    0x18ee2f8                 ; <+660>
    0x18ee26c <+520>: cmp    r10, #63
    0x18ee270 <+524>: movwhi r4, #0x1
    0x18ee274 <+528>: cmp    r5, #0
    0x18ee278 <+532>: movwne r5, #0x1
    0x18ee27c <+536>: moveq  r5, r4
    0x18ee280 <+540>: cmp    r5, #0
    0x18ee284 <+544>: bne    0x18ee36c                 ; <+776>
    0x18ee288 <+548>: mvn    r0, #-67108863
    0x18ee28c <+552>: bfi    r6, r0, #6, #26
    0x18ee290 <+556>: ldr    r0, [sp, #0x1c]
    0x18ee294 <+560>: uxtb   r0, r0
    0x18ee298 <+564>: rsb    r1, r10, #32
    0x18ee29c <+568>: lsr    r1, r0, r1
    0x18ee2a0 <+572>: sub    r2, r10, #32
    0x18ee2a4 <+576>: cmp    r2, #0
    0x18ee2a8 <+580>: lslge  r1, r0, r2
    0x18ee2ac <+584>: ldr    r2, [sp, #0x14]
    0x18ee2b0 <+588>: orr    r2, r2, r0, lsl r10
    0x18ee2b4 <+592>: str    r2, [sp, #0x1c]
    0x18ee2b8 <+596>: ldr    r0, [sp, #0x18]
    0x18ee2bc <+600>: orr    r10, r1, r0
    0x18ee2c0 <+604>: str    r2, [sp, #0x20]
    0x18ee2c4 <+608>: str    r10, [sp, #0x24]
    0x18ee2c8 <+612>: add    r8, r8, #1
    0x18ee2cc <+616>: mov    r0, #8
    0x18ee2d0 <+620>: smull  r5, r4, r8, r0
    0x18ee2d4 <+624>: mov    r2, #8
    0x18ee2d8 <+628>: mov    r3, #0
    0x18ee2dc <+632>: mov    r0, r5
    0x18ee2e0 <+636>: mov    r1, r4
    0x18ee2e4 <+640>: bl     0x19afea8                 ; symbol stub for: __udivdi3
    0x18ee2e8 <+644>: eor    r1, r1, r8, asr #31
    0x18ee2ec <+648>: eor    r0, r0, r8
    0x18ee2f0 <+652>: orrs   r0, r0, r1
    0x18ee2f4 <+656>: beq    0x18ee2fc                 ; <+664>
    0x18ee2f8 <+660>: trap   
    0x18ee2fc <+664>: cmp    r5, #64
    0x18ee300 <+668>: mov    r0, #0
    0x18ee304 <+672>: movwlo r0, #0x1
    0x18ee308 <+676>: cmp    r4, #0
    0x18ee30c <+680>: mov    r1, #0
    0x18ee310 <+684>: movne  r0, r1
    0x18ee314 <+688>: cmp    r0, #0
    0x18ee318 <+692>: beq    0x18ee36c                 ; <+776>
    0x18ee31c <+696>: uxtb   r0, r6
    0x18ee320 <+700>: rsb    r1, r5, #32
    0x18ee324 <+704>: lsr    r1, r0, r1
    0x18ee328 <+708>: sub    r2, r5, #32
    0x18ee32c <+712>: cmp    r2, #0
    0x18ee330 <+716>: lslge  r1, r0, r2
    0x18ee334 <+720>: ldr    r2, [sp, #0x1c]
    0x18ee338 <+724>: orr    r0, r2, r0, lsl r5
    0x18ee33c <+728>: orr    r1, r1, r10
    0x18ee340 <+732>: str    r0, [sp, #0x20]
    0x18ee344 <+736>: str    r1, [sp, #0x24]
    0x18ee348 <+740>: add    r0, sp, #32
    0x18ee34c <+744>: add    r1, r8, r0
    0x18ee350 <+748>: add    r1, r1, #1
    0x18ee354 <+752>: ldr    r2, [r7, #0xc]
    0x18ee358 <+756>: str    r2, [sp]
    0x18ee35c <+760>: mov    r2, r11
    0x18ee360 <+764>: ldr    r3, [r7, #0x8]
    0x18ee364 <+768>: bl     0x1943138                 ; function signature specialization <Arg[0] = Exploded, Arg[1] = Exploded> of Swift.(_fatalErrorMessage (Swift.StaticString, Swift.StaticString, Swift.StaticString, Swift.UInt) -> ()).(closure #2)
    0x18ee368 <+772>: trap   
    0x18ee36c <+776>: mov    r0, #2
    0x18ee370 <+780>: str    r0, [sp, #0x4]
    0x18ee374 <+784>: mov    r1, #45
    0x18ee378 <+788>: movw   r0, #0xfada
    0x18ee37c <+792>: movt   r0, #0xa
    0x18ee380 <+796>: add    r0, pc, r0
    0x18ee384 <+800>: movw   r3, #0xfc6c
    0x18ee388 <+804>: movt   r3, #0xa
    0x18ee38c <+808>: add    r3, pc, r3
    0x18ee390 <+812>: str    r1, [sp]
    0x18ee394 <+816>: mov    r1, #11
    0x18ee398 <+820>: mov    r2, #2
    0x18ee39c <+824>: bl     0x18ee064                 ; <+0>

**Comment by VitaliyGuru** [comment]
@xpressmobtech Hello!
Could you please enable breakpoints and show me the line, where the crash was appeared?

**Comment by Raikerian** [comment]
Hi @xpressmobtech 

Any updates on this issue?

**Comment by xpressmobtech** [comment]
the crash occurs on this line "self.videoCapture!.previewLayer.frame = self.localVideoView.frame"

**Comment by xpressmobtech** [comment]
let opponentsIDs = [3245, 2123, 3122]

let newSession = QBRTCClient.instance().createNewSessionWithOpponents(opponentsIDs, withConferenceType: QBRTCConferenceType.Video)

let userInfo :[String:String] = ["key":"value"]

newSession.startCall(userInfo)"
--------------------------------------------------------------------------

these lines create a session for connecting with the opponent?

**Comment by Pro100Andrey** [comment]
@xpressmobtech  yes

**Comment by xpressmobtech** [comment]
i'm receiving multiple different errors stating "Entity: line 124: parser error : StartTag: invalid element name
<userInfo><></></userInfo>"

This is my userInfo var: 

let userInfo: [String: String] = ["": ""]

Is there a better to leave userInfo nil without a crash?

**Comment by xpressmobtech** [comment]
@Pro100Andrey in the first method of video docs it says "self.session = session" what does "self.session" refer to?

**Comment by djErock** [comment]
Change your lines to:

self.videoCapture?.previewLayer.frame = self.localVideoView.frame
self.videoCapture?.startSession()
