### ISSUE TITLE
Updated user parameters  are not showing in the app. 

### ISSUE THREAD

**Issue by mallikaD** [QuickBlox/quickblox-ios-sdk#597]
I am **updating the current user full name**.I used below method for **updating the name** which is in quickblox.

 QBUpdateUserParameters *user = [QBUpdateUserParameters new];
    user.fullName = _txt_name.text;//= [QBUUser user];
    [QBRequest updateCurrentUser:user successBlock:^(QBResponse *response, QBUUser *user) {
        // User updated successfully
        NSLog(@"Success : %@",[QBSession currentSession].currentUser.fullName);
    } errorBlock:^(QBResponse *response) {
        // Handle error
        NSLog(@"error :%@",[QBSession currentSession].currentUser.fullName);
    }];
**Output:**
Success : Mallika

It enters into success block and name is also updating in the backend of quickblox but it is not reflects on the app.The newly added users and updated changes are coming on the app only when removing the app and reinstalling it again then only all the updated changes are displaying in the app otherwise changes are not displaying.Please suggest me the solution for this issue.Thank you.

**Comment by Raikerian** [comment]
Hi,

Which app are you talking about? You need to update your own local user instance by yourself in success block.

**Comment by mallikaD** [comment]
I used quickblox in my own app. By using above mentioned code i am updating my logged in user details.It is updating in quickblox dashboard but not in my app.

**Comment by Raikerian** [comment]
Where are you storing your current user in the app?

**Comment by mallikaD** [comment]
By calling below method i am getting the current logged in user details

[QBSession currentSession].currentUser

**Comment by mallikaD** [comment]
If i remove the app and reinstall it again then only the updated changes are coming from the quickblox dashboard otherwise newly registered users and updating info is not updating(users list is not refreshing).I am calling the "retrieve all users"list  in 1st viewController of my app.

**Comment by Raikerian** [comment]
What is your SDK version?

**Comment by mallikaD** [comment]
i used pod file.
 pod 'QuickBlox'
pod 'QMServices'
pod 'QMChatViewController'

**Comment by Raikerian** [comment]
Open Quickblox.h file. There is version in it.

**Comment by mallikaD** [comment]
version is 2.7.2

**Comment by mallikaD** [comment]
Any Update please??

**Comment by Raikerian** [comment]
@mallikaD I have just tested it and it is working as intended. Please try our latest SDK 2.8.

**Comment by Pro100Andrey** [comment]
Hi @mallikaD, Any updates?
