### ISSUE TITLE
Quickblox : How to maintain call log for Swift / objective c ?

### ISSUE THREAD

**Issue by vibha22** [QuickBlox/quickblox-ios-sdk#599]
Please help me. I have one feature where I want to show call log. I tried a lot but no luck.

**Comment by Raikerian** [comment]
Hi, are you talking about developer logs? Or which logs?

**Comment by vibha22** [comment]
No. I am talking about call logs like Missed call , received call.  Same as we have in whats app application.

**Comment by VitaliyGuru** [comment]
@vibha22 , Take a look at our [Q-Municate](https://github.com/QuickBlox/q-municate-ios). There you can find handling and implementation of call logs.

**Comment by vibha22** [comment]
Yes.. I seen the code. but I am not getting how exactly they are handling the sessions. Also I want that in swift.

**Comment by Raikerian** [comment]
Just rewrite code in swift using our objc implementation.
We do not have any plans to move Q-municate into Swift, however we can help you by answering questions.

> but I am not getting how exactly they are handling the sessions

Just send custom messages in chat, where in customParameters set needed parameters, like whether call was ended/started, call time etc.

**Comment by vibha22** [comment]
Ok can you plz tell me how to get call history in quickblox?

**Comment by Raikerian** [comment]
Use Custom parameters in QBChatMessage message instance, to store data you need for call history. Refer to http://quickblox.com/developers/SimpleSample-chat_users-ios#Use_custom_parameters_in_a_message
After you received such a message, just draw it in your UI like notification message with call info you stored in custom parameters.

**Comment by Raikerian** [comment]
This is more of an implementation question, that is not related to our SDK. However you can always use our [Q-municate app](https://github.com/QuickBlox/q-municate-ios) as an example.

If you are still having any other troubles, please create a separate issue.

**Comment by ZeshanIlyas** [comment]
The Q-municate app does not save call logs/ call history in the application. It only saves adds a message with custom parameter in that particular dialog about calls. How to get list of all outgoing and incoming calls that I had from Quickblox ? @Raikerian
