### ISSUE TITLE
Audio player volume getting extremely low after video call

### ISSUE THREAD

**Issue by rawat555** [QuickBlox/quickblox-ios-sdk#60]
In my application there is video call functionality with music(optional). when  I connect video call and music is also playing in background. I pause the music and again play music when video call finished.

But After video call music is playing in a extremely low volume. I have to relaunch the app for getting normal volume.

My Playing music code is below
 player = [[AVAudioPlayer alloc] initWithContentsOfURL:[theSoundArrayGlobal objectAtIndex:i] error:nil];
    player.delegate = self;
    [player prepareToPlay];
     NSLog(@"current playing songs is %@",[theSoundArrayGlobal objectAtIndex:i]);
    [player play];
    index++;

Please tell me what I am doing wrong here. Looking for your positive response

**Comment by rawat555** [comment]
Some time I am getting this issue after accepting call

 [0x3da1e18c] 1202: AUIOClient_StartIO failed (560034163)
Error: Couldn't start the audio unit (The operation couldn’t be completed. (OSStatus error 560034163.))

**Comment by iSevenDays** [comment]
Please specify Quickblox SDK version and Quickblox WebRTC version.

**Comment by rawat555** [comment]
Hi iSevenDays 
I am not using  Quickblox WebRTC version. I am using following.
  "QB-SDK" = "iOS 2.0.10";
  "QuickBlox-REST-API-Version" = "0.1.1";

**Comment by rawat555** [comment]
I am also getting this during video call. When I lock my device during video call i got following crash. and in other end call disconnected due to bad network
-[QBXMPPStream sendElement:]: message sent to deallocated instance 0x12fd49a00

**Comment by AndreyMoskvin** [comment]
We are going to release Quickblox WebRTC SDK v2.0 - please try it and see if you still have described issues.

**Comment by ruipfcosta** [comment]
Did you manage to fix the audio volume problem?
