### ISSUE TITLE
Quickblox Webrtc 2.2 SoundRouter not working for both users.

### ISSUE THREAD

**Issue by xpressmobtech** [QuickBlox/quickblox-ios-sdk#602]
Qbrtcsoundrouter speaker only works for one user at a time.

**Comment by Raikerian** [comment]
Hi, 

We are aware of this issue and we are currently working on a new version of our WebRTC, which will have absolutely new audio engine (so sound router will be gone). Unfortunately there is no any ETA for the new release yet.

So, for now I can suggest you to look into our QBRTCSoundRouter source files and try to fix it by yourself.
Here they are:

[QBRTCSoundRouter class with implementation file](https://gist.github.com/Raikerian/a60a4d3cdeb7d3f15694c3085d3fc660)

**Comment by xpressmobtech** [comment]
Okay thanks, Can you point in me the right direction of what i'm suppose to be doing to fix the issue?

**Comment by xpressmobtech** [comment]
@Raikerian What in the implementation file should I be changing to go about fixing the issue of the sound router only working for one user??? Please help i'm not very experienced with Objective-C.

**Comment by xpressmobtech** [comment]
@Raikerian @Pro100Andrey what should I change in the in the files to fix the sound router issue of Quickblox webrtc 2.2???

**Comment by xpressmobtech** [comment]
@Raikerian  @Pro100Andrey  Please assist!

**Comment by Pro100Andrey** [comment]
@xpressmobtech  please check video sample, from master branch. We downgrade  Quickblox webrtc 2.2  in to 2.1 (QBRTCSoundRoute works fine, please check it).

**Comment by xpressmobtech** [comment]
@Pro100Andrey Should I re-install/update the pod for my current project already using QBWebrtc? or will it automatically work?

**Comment by xpressmobtech** [comment]
@Pro100Andrey 2.1.1 or 2.1.0?

**Comment by Pro100Andrey** [comment]
@xpressmobtech 2.1.1

**Comment by xpressmobtech** [comment]
@Pro100Andrey Okay, thanks!
