### ISSUE TITLE
hello  i am not uploading the attachement image in server backend quickblogs

### ISSUE THREAD

**Issue by esshaancheema** [QuickBlox/quickblox-ios-sdk#604]
*Help avoid duplicate issue reports, check [existing issues](https://github.com/QuickBlox/quickblox-ios-sdk/issues)*
 
**Environment details**
*iOS version, Quickblox iOS SDK version, QuickbloxWebRTC SDK version (optional)*

**Did this work before?**

**Expected behavior**

**Actual behavior**

**Logs**
*Attach full logs that will describe your problem (please, use github [gist](https://gist.github.com/))*

**Steps to reproduce the behavior**

**Any others comments?**

**Comment by VitaliyGuru** [comment]
@esshaancheema We can't help you until you provide:
1. SDK version
2. Logs
3. Actual and expected behaviour
4. Code snippet.

**Comment by Pro100Andrey** [comment]
Hi, @esshaancheema! Please check this [Guide] (http://quickblox.com/developers/SimpleSample-content-ios) and [QuickBlox iOS Content Sample](https://github.com/QuickBlox/quickblox-ios-sdk/tree/master/sample-content)

**Comment by Pro100Andrey** [comment]
Hi, @esshaancheema  - any updates?

**Comment by Raikerian** [comment]
@esshaancheema please create a more detailed issue next time. If you are still having any troubles, create a new one with more information. Until then we will not be able to help you.
