### ISSUE TITLE
Delete chat messages - for Single User (logged user)

### ISSUE THREAD

**Issue by HardikAjmeri** [QuickBlox/quickblox-ios-sdk#605]
**Environment details**
iOS version: iOS 8.0 or later
Quickblox iOS SDK version: 2.8

**Expected behavior**
User who have deleted all chat messages for him/her dialog's last message should be empty.

**Actual behavior**
User who have deleted all chat messages for him/her dialog's last message is not empty instead showing last message.

**Logs**
[Log 1](https://gist.github.com/HardikAjmeri/c3f15fce697d930dfc601a323dcdd104)

**Steps to reproduce the behavior**
[Log 2](https://gist.github.com/HardikAjmeri/fc66f04a148b99915e010e98c4ecea60)

**Comments**
I found that this was perviously fixed by referring following [ticket](https://github.com/QuickBlox/quickblox-ios-sdk/issues/327)

**Comment by VitaliyGuru** [comment]
For you links I'm getting the 404 error.

Anyway it's a server-side issue and not related to our SDK. 
To fix it for now you can send empty message before removing all messages.

**Comment by soulfly** [comment]
@HardikAjmeri 
That's known server-side issue, we are looking for an optimal solution here,
but it will take some time to figure out.
