### ISSUE TITLE
Sometimes QBChatDialog.joinWithCompletionBlock method does not call it's completion block.

### ISSUE THREAD

**Issue by Aziz38** [QuickBlox/quickblox-ios-sdk#609]
**Environment details**
iOS version = (Deployment target on Xcode) 9.0, 'QMServices' = v0.4.4, 'QMChatViewController' = v0.3.10

**Expected behavior**
Stable and bug free quickblox framework

**Actual behavior**
When we call QBChatDialog's joinWithCompletionBlock method, sometimes completion block is never called. It is totally irresponsive. There is no even error message.

**Comment by VitaliyGuru** [comment]
Hello, @Aziz38  We can't help you until you provide full logs.
Are there any steps to reproduce this issue?

**Comment by Aziz38** [comment]
The problem is active during 15-20 min a day and then it is working. We are using autoJoin enabled thus when we create group dialog it should automatically join it's participants. There framework is automatically calling QBChatDialog's joinWithCompletionBlock method and sometimes it's completion block is never called. We need to wait 15-20 min and then try to create chat group in order to make it work when the problem is encountered. I will post here logs as soon as we face this problem again.

**Comment by Raikerian** [comment]
Hi @Aziz38 

Can you check this now? Our server team has finished looking into it and the problem should be fixed.

**Comment by Aziz38** [comment]
Thank you for this. We hope it fixed now as we can't reproduce it.

**Comment by soulfly** [comment]
@Aziz38  what's your application_id ?

**Comment by Aziz38** [comment]
Here it is: 47916
