### ISSUE TITLE
App termination after 1 sec of launch

### ISSUE THREAD

**Issue by SM-devloper** [QuickBlox/quickblox-ios-sdk#610]
I have downloaded sample app and trying to run in simulator. when app starts running some `"EXC_BAD_ACCESS"` error cause terminating app. even `didFinishLaunchingWithOptions` is not getting called. Any help?

**Comment by VitaliyGuru** [comment]
@SM-devloper Hello,

Could you please specify:
- branch
- obj-c or swift sample

**Comment by SM-devloper** [comment]
It is stopping on memcmp. I am using obj-c

**Comment by manish12jain** [comment]
I also have same issue

**Comment by smadupu** [comment]
I am also getting same issue when installing in simulator. Crash log: **Message from debugger: Terminated due to code signing error**.

**Comment by smadupu** [comment]
dyld_sim`ImageLoaderMachO::crashIfInvalidCodeSignature:
    0x1052c5812 <+0>:  pushq  %rbp
    0x1052c5813 <+1>:  movq   %rsp, %rbp
    0x1052c5816 <+4>:  pushq  %r14
    0x1052c5818 <+6>:  pushq  %rbx
    0x1052c5819 <+7>:  movq   %rdi, %r14
    0x1052c581c <+10>: xorl   %eax, %eax
    0x1052c581e <+12>: cmpb   $0x0, 0x6c(%r14)
    0x1052c5823 <+17>: je     0x1052c586c               ; <+90>
    0x1052c5825 <+19>: xorl   %ebx, %ebx
    0x1052c5827 <+21>: movq   (%r14), %rax
    0x1052c582a <+24>: movq   %r14, %rdi
    0x1052c582d <+27>: movl   %ebx, %esi
    0x1052c582f <+29>: callq  *0x1a8(%rax)
    0x1052c5835 <+35>: testq  %rax, %rax
    0x1052c5838 <+38>: jne    0x1052c584d               ; <+59>
    0x1052c583a <+40>: movq   (%r14), %rax
    0x1052c583d <+43>: movq   %r14, %rdi
    0x1052c5840 <+46>: movl   %ebx, %esi
    0x1052c5842 <+48>: callq  *0x198(%rax)
    0x1052c5848 <+54>: testq  %rax, %rax
    0x1052c584b <+57>: jne    0x1052c585c               ; <+74>
    0x1052c584d <+59>: incl   %ebx
    0x1052c584f <+61>: movzbl 0x6c(%r14), %ecx
    0x1052c5854 <+66>: xorl   %eax, %eax
    0x1052c5856 <+68>: cmpl   %ecx, %ebx
    0x1052c5858 <+70>: jb     0x1052c5827               ; <+21>
    0x1052c585a <+72>: jmp    0x1052c586c               ; <+90>
    0x1052c585c <+74>: movq   (%r14), %rax
    0x1052c585f <+77>: movq   %r14, %rdi
    0x1052c5862 <+80>: movl   %ebx, %esi
    0x1052c5864 <+82>: callq  *0x1e0(%rax)
->  0x1052c586a <+88>: movl   (%rax), %eax
    0x1052c586c <+90>: popq   %rbx
    0x1052c586d <+91>: popq   %r14
    0x1052c586f <+93>: popq   %rbp
    0x1052c5870 <+94>: retq   
    0x1052c5871 <+95>: nop

**Comment by Pro100Andrey** [comment]
Hi @smadupu, please provide Xcode version

**Comment by Raikerian** [comment]
Hi,

We were able to fix that and the fresh updated Quickblox iOS SDK build is now available in master branch. Check out our latest commit in master.
The problem was, that the binary was built under the macOS sierra, which for some reason does not want to work with Xcode 7 simulators. Updated binary was built under the OSX 10.11.
