### ISSUE TITLE
SDK 2.8 Sometimes crashes on [QBChatDialog joinWithCompletion...] - EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by AleksandrKh** [QuickBlox/quickblox-ios-sdk#611]
#iOS 10.0, SDK 2.8

I join multiply dialogs and sometimes get this error.
Dialog exists on the backend and dialog object exists too.

It started after upgrade to iOS 10.0 and SDK 2.8
After downgrade to SDK 2.7.6 it seems to be working well again.

**Comment by Pro100Andrey** [comment]
Hi @AlexsandrKh, please provide crash stack trace + logs

**Comment by Pro100Andrey** [comment]
Hi @AleksandrKh, any updates?

**Comment by AleksandrKh** [comment]
I don't have full stack trace now, but I got at least screenshot, maybe it may give something
![screenshot](https://cloud.githubusercontent.com/assets/2961856/19161596/de26d814-8c0d-11e6-84cc-0a0b184b189d.png)

**Comment by Pro100Andrey** [comment]
@AleksandrKh JNChatDialog?

**Comment by Pro100Andrey** [comment]
@AleksandrKh Show me implementation JNChatDialog class

**Comment by AleksandrKh** [comment]
JNChatDialog has a QBChatDialog property.
self.qbDialog on the screenshot is QBChatDialog

**Comment by Pro100Andrey** [comment]
@AleksandrKh Please use main queue

**Comment by Pro100Andrey** [comment]
@AleksandrKh Any updates?

**Comment by AleksandrKh** [comment]
I'm testing with main thread. I will reopen if I meet this bug again.

**Comment by Pro100Andrey** [comment]
@AlexsandrKh Any updates?
