### ISSUE TITLE
Unable to create new user

### ISSUE THREAD

**Issue by manish12jain** [QuickBlox/quickblox-ios-sdk#612]
#611 I have following setting in my appdelegate

```
    [QBSettings setAccountKey:@""];
    [QBSettings setApplicationID:];
    [QBSettings setAuthKey:@""];
    [QBSettings setAuthSecret:@""];
    [QBSettings setLogLevel:QBLogLevelErrors];
    [QBSettings enableXMPPLogging];
    
    [QBRTCConfig setAnswerTimeInterval:kQBAnswerTimeInterval];
    [QBRTCConfig setDisconnectTimeInterval:kQBRTCDisconnectTimeInterval];
    [QBRTCConfig setDialingTimeInterval:kQBDialingTimeInterval];
    [QBRTCClient initializeRTC];
```

after that in my view controller i am using this code

`    QBUUser *user = [QBUUser user];
`

it always return me nil value . what can be cause ??

**Comment by Raikerian** [comment]
Hi,

`[QBUUser user]` is just `[QBUUser new]`. Are you sure you are getting nil there **and** there is no any errors anymore? Need for clarification on this.

**Comment by Pro100Andrey** [comment]
Hi @manish12jain, any updates?

**Comment by Pro100Andrey** [comment]
@manish12jain please provide sample project
