### ISSUE TITLE
QBRequest usersWithTags method is not working

### ISSUE THREAD

**Issue by itsaboutcode** [QuickBlox/quickblox-ios-sdk#614]
QBRequest usersWithTags method is not working

**Environment details**
*iOS 8.0, Quickblox iOS SDK 2.8.0.1

**Did this work before?**
Using this method for the first time

**Expected behavior**
I expect to get all the users with given tag.

**Actual behavior**
This method is not returning back any user (basically no call back is being called)

**Comment by Pro100Andrey** [comment]
Hi @itsaboutcode , please provide logs

**Comment by itsaboutcode** [comment]
@Pro100Andrey - Not sure what kind of logs to share with you. Just check the method being in question and you will know the issue.

**Comment by Pro100Andrey** [comment]
@itsaboutcode, checked:
<img width="799" alt="completion" src="https://cloud.githubusercontent.com/assets/1109916/19155075/c605f67a-8be5-11e6-8ade-5c7a0013bf4c.png">

**Comment by VitaliyGuru** [comment]
Hello, @itsaboutcode.

1.You need to go to the admin.quickblox.com.
2.Then select your app and go to the settings. http://joxi.ru/p27bp9dt8adxm7
3.Then you should select checkmark "Allow to retrieve a list of users". http://joxi.ru/VrwbG80tk9GMAX

It will allow you to retrieve a list of users.

**Comment by itsaboutcode** [comment]
@VitaliyGuru - It's checked. @Pro100Andrey - Strange it's not working on our end (Android and iOS) :(. Can you share how many tags this user have? Because if user have more than 1 tag, it don't work on our side.

**Comment by Pro100Andrey** [comment]
@itsaboutcode please provide logs to investigate this issue

**Comment by itsaboutcode** [comment]
@Pro100Andrey Please check this.
![screen shot 2016-10-06 at 7 10 40 pm](https://cloud.githubusercontent.com/assets/204423/19155637/9ce15588-8bf8-11e6-8ccb-731829f0a428.png)

**Comment by itsaboutcode** [comment]
@Pro100Andrey - We fixed one issue (it seems our quickblox server tags were not updated - sorry about that). But we have more than 1 user with given tags and it dont return them all but only one user. Just wondering if it's suppose to return the user with all the matching tags? We want users which match any tag.

![screen shot 2016-10-06 at 7 20 43 pm](https://cloud.githubusercontent.com/assets/204423/19156100/253ccde4-8bfa-11e6-98d6-adb3cb7e08c9.png)

**Comment by Pro100Andrey** [comment]
@itsaboutcode we use logical condition "AND" for search with tags

**Comment by itsaboutcode** [comment]
@Pro100Andrey - How we can use logical "OR" or give us alternative.

**Comment by itsaboutcode** [comment]
@Pro100Andrey - Please suggest use the alternative and how many tags are user can have at max?

**Comment by Pro100Andrey** [comment]
@itsaboutcode With [Custom Objects](http://quickblox.com/developers/Custom_Objects#Search_operators)

**Comment by Pro100Andrey** [comment]
@itsaboutcode The maximum number of tags per user: 5.

**Comment by itsaboutcode** [comment]
@Pro100Andrey - Please share the methods for iOS and Android which help to do this search via Custom Objects. Thanks.

**Comment by Pro100Andrey** [comment]
@itsaboutcode It should be like this:

+ [Guide: Getting Started with Custom Objects API]()
+ [Adding a Custom Data structure to your application](http://quickblox.com/developers/SimpleSample-customObjects-ios#Adding_a_Custom_Data_structure_to_your_application) for example - `ClassName` :`UserTags`, `fields` : `tags` (Array)
+ [Set permisions](http://quickblox.com/developers/SimpleSample-customObjects-ios#Permissions)
+ [Create record using iOS SDK](http://quickblox.com/developers/SimpleSample-customObjects-ios#Create_record_using_iOS_SDK)

for example:
```objc
QBCOCustomObject *object = [QBCOCustomObject customObject];
object.className = @"UserTags"; // your Class name
 
// Object fields
[object.fields setObject:@"tag_1" forKey:@"tags"];
 
[QBRequest createObject:object successBlock:^(QBResponse *response, QBCOCustomObject *object) {
     // do something when object is successfully created on a server
} errorBlock:^(QBResponse *response) {
     // error handling
     NSLog(@"Response error: %@", [response.error description]);
}];
```
+ [Retrive Records](http://quickblox.com/developers/Custom_Objects#Retrieve_records) Use Contained IN array operator for search

For example:

```objc
NSMutableDictionary *getRequest = [NSMutableDictionary dictionary];
[getRequest setObject:@"tag1,tag_1" forKey:@"tags[or]"];
 
[QBRequest objectsWithClassName:@"UserTags" extendedRequest:getRequest successBlock:^(QBResponse *response, NSArray *objects, QBResponsePage *page) {
    // response processing
} errorBlock:^(QBResponse *response) {
    // error handling
    NSLog(@"Response error: %@", [response.error description]);
}];
```

**Comment by Pro100Andrey** [comment]
@itsaboutcode Any updates?

**Comment by itsaboutcode** [comment]
@Pro100Andrey - Thanks for the code snipet. We will look into how we can use it in our app.

**Comment by histone** [comment]
@Pro100Andrey - How can we relate it with user?
We want other users related to some tags. not only the current one

**Comment by Pro100Andrey** [comment]
Hi @histone 

QBCOPermissionsAccessOpen (open) Such permission schema means that any user within application can access to record/records in the class and is allowed to perform action with the current permission level

**Comment by itsaboutcode** [comment]
@Pro100Andrey - So we create custom object "UserTags" with an array object "tags"

![usertags](https://cloud.githubusercontent.com/assets/204423/19186384/75b96156-8c9f-11e6-8ea7-fa9cd00132c6.png)

And did the query just like you mentioned. But I am empty objects array.

![screen shot 2016-10-07 at 3 09 51 pm](https://cloud.githubusercontent.com/assets/204423/19186569/5381cc8a-8ca0-11e6-952b-ceba0e6252d9.png)

**Comment by itsaboutcode** [comment]
@Pro100Andrey - Above mentioned issue is fixed. By the way, how we should treat the `QBResponsePage` object in this response. Currently we are getting this.

```
Optional(QBResponsePage            
  skip:0            
  limit:0			
  totalEntries:0)
```

**Comment by Pro100Andrey** [comment]
Hi @itsaboutcode, Please provide logs for this request and response

**Comment by Pro100Andrey** [comment]
@itsaboutcode 

QBResponsePage for `custom objects` don't provided `totalEntries` field

+ Get count:

```objc
    
NSMutableDictionary *getRequest = [NSMutableDictionary dictionary];
    
    getRequest[@"tags[or]"] = @"tag1,tag_1";
    getRequest[@"limit"] = @"10";
    
    [QBRequest countObjectsWithClassName:@"Your class name"
                         extendedRequest:getRequest
                            successBlock:^(QBResponse *response, NSUInteger count)
     {
         NSLog(@"Successfull response! Count: %lu", (unsigned long)count);
     } errorBlock:^(QBResponse *response) {
         NSLog(@"Response error:%@", response.error);
     }];
 
```

**Comment by itsaboutcode** [comment]
@Pro100Andrey - How many records are returned by `objectsWithClassName` method?

**Comment by Pro100Andrey** [comment]
@itsaboutcode 

Limit search results to N records. Useful for pagination. Default value - 100. Also can set 1000.If limit is equal to -1 only last record will be returned

**Comment by Pro100Andrey** [comment]
@itsaboutcode Please check for more information: [Filters](http://quickblox.com/developers/Custom_Objects#Filters)

**Comment by Pro100Andrey** [comment]
@itsaboutcode, if you have any other question please create separate issue.
