### ISSUE TITLE
Unable to join private group dialog

### ISSUE THREAD

**Issue by smadupu** [QuickBlox/quickblox-ios-sdk#616]
I am unable to join group dialog when received a new group private dialog request from admin of the dialog when app is running getting an issue with name **Cannot create/join room when already creating/joining/joined." UserInfo={NSLocalizedDescription=Cannot create/join room when already creating/joining/joined**
After relaunch the application or disconnect and connect to chat, able to join dialog same dialog with out any issues. Attached both the logs of before relaunch the application and after relaunch.

Please check out the issue and let me know the feedback.

*Help avoid duplicate issue reports, check [existing issues](https://github.com/QuickBlox/quickblox-ios-sdk/issues)*
 
**Environment details**
*iOS version:9.3, Quickblox iOS SDK version:2.8.0.1*

**Did this work before?**: Yes it was working before for the quickblox version 2.6.1

**Expected behavior**
Dialog has to join when a new group dialog request is created.

**Actual behavior**
Dialog is not joining

**Logs**
*Attach full logs that will describe your problem (please, use github [log1](https://gist.github.com/smadupu/b4098bcbee10618f4f3e9c8bd5c2f8fc)

*After restart app (please, use github [log2](https://gist.github.com/smadupu/5941ebcf10487102b0aa94b363a80cbd)

**Comment by Pro100Andrey** [comment]
@smadupu 404

Logs
*Attach full logs that will describe your problem (please, use github [](https://gist.github.com/smadupu/b4098bcbee10618f4f3e9c8bd5c2f8fc

*After restart app (please, use github [](https://gist.github.com/smadupu/5941ebcf10487102b0aa94b363a80cbd

**Comment by Pro100Andrey** [comment]
Hi @smadupu, thanks for reply. Our server side team is currently looking into this problem

**Comment by smadupu** [comment]
Can I know when the issue will be fixed.
