### ISSUE TITLE
Retrieve list of users instead of each user separately.

### ISSUE THREAD

**Issue by xpressmobtech** [QuickBlox/quickblox-ios-sdk#619]
Hello, I am using QBRequest.userwithid to retrieve users, but instead of getting an array of users each user is separate. Anyway, to receive array of all users?

**Comment by VitaliyGuru** [comment]
@xpressmobtech  Hello, 
Take a look at our [sample-users](http://quickblox.com/developers/IOS/sample-users-2.0).
There are lots of methods for retrieving users:
- Retrieve all Users
- Retrieve Users by IDs
- Retrieve Users by Logins
- Retrieve Users by Emails
- Retrieve Users by Phone numbers
- Retrieve Users by Twitter IDs
- Retrieve Users by Facebook IDs
- Retrieve Users by Tags. Tags like groups, in which we can group users
- Retrieve Users with full name

**Comment by xpressmobtech** [comment]
I am ablr to retriev the users but they show up like [User1] [User2] [User3] [User4] [User5], how can i get them to show like [User1, User2, User3, User4, User5]

**Comment by xpressmobtech** [comment]
all retrieved users in one array

**Comment by xpressmobtech** [comment]
@VitaliyGuru @Pro100Andrey @Raikerian is there anyway to achieve the question above?

**Comment by Raikerian** [comment]
Hi @xpressmobtech 

I don't really understand what do you mean by

> they show up like [User1] [User2] [User3] [User4] [User5]

They should be already as an array in completion block. Please provide us a code snippet and logs to help understand your question.

**Comment by xpressmobtech** [comment]
//qbids is a parsed list string of QB IDs, that i convert into int
if let peerints = Int(qbids) {
   let peersUInt = UInt(Int(peerints))

        guard let QBUid = QBSession.currentSession().currentUser?.ID else {
            return
        }
        let meint = Int(QBUid)
            
        QBRequest.userWithID(peersUInt, successBlock: { (QBResponse, qbuser) in
                                        
        if let user = qbuser {
        let user1 = user.ID
        
            print("IDS:", user1)
       
            
        }
                                                                      
        }, errorBlock: { (QBResponse) in
            print("ERROR ERROR!!!!",QBResponse)
        })

**Comment by xpressmobtech** [comment]
However the console prints:

IDS: 1234556
IDS: 3546748
IDS: 9087654
IDS: 4546363

instead of IDS: [1234556, 3546748, 9087654, 4546363]

how can i achieve array instead of individual users when using retrieve method?

@VitaliyGuru  @Raikerian  @Pro100Andrey

**Comment by Raikerian** [comment]
What is a point of using QBRequest.userWithID method then? This method is only retrieving 1 user. There is method for multiple user retrieve:

```objc
[QBRequest usersWithIDs:@[@300,@298] page:[QBGeneralResponsePage responsePageWithCurrentPage:1 perPage:10] successBlock:^(QBResponse *response, QBGeneralResponsePage *page, NSArray *users) {
    // Successful response with page information and users array
} errorBlock:^(QBResponse *response) {
    // Handle error here
}];
```

**Comment by xpressmobtech** [comment]
I can only retrieve users using that method on one page? and only up to 100?

**Comment by Raikerian** [comment]
Yes, implement your own pagination to retrieve more than 100.

**Comment by xpressmobtech** [comment]
How would I say go through every available page to find these specific users with ids and retrieve how ever many  users with these ids it is?

**Comment by VitaliyGuru** [comment]
@xpressmobtech, I'm not sure what you mean. Could you explain question in more detail ?
