### ISSUE TITLE
error while archiving the project which integrated this sdk

### ISSUE THREAD

**Issue by ITpakar** [QuickBlox/quickblox-ios-sdk#62]
This is the error message which I got after I tried to archive the project for submission.
Please let me know why this happened.

I'm using the most recent SDK and integrated it into my project using CocoaPods 0.36.4

duplicate symbol l108 in:
    /Users/it_pakar/Projects/dubbfreelancers/Pods/QuickBlox/Quickblox.framework/Quickblox(QBSocialLoginDialog.o)
    /Users/it_pakar/Projects/dubbfreelancers/Pods/QuickBlox/Quickblox.framework/Quickblox(QBDDAbstractDatabaseLogger.o)
duplicate symbol l109 in:
    /Users/it_pakar/Projects/dubbfreelancers/Pods/QuickBlox/Quickblox.framework/Quickblox(QBSocialLoginDialog.o)
    /Users/it_pakar/Projects/dubbfreelancers/Pods/QuickBlox/Quickblox.framework/Quickblox(QBDDAbstractDatabaseLogger.o)
duplicate symbol l084 in:
    /Users/it_pakar/Projects/dubbfreelancers/Pods/QuickBlox/Quickblox.framework/Quickblox(QBQuery.o)
    /Users/it_pakar/Projects/dubbfreelancers/Pods/QuickBlox/Quickblox.framework/Quickblox(QBLGeoDataGetRequest.o)
duplicate symbol l084 in:
    /Users/it_pakar/Projects/dubbfreelancers/Pods/QuickBlox/Quickblox.framework/Quickblox(QBQuery.o)
    /Users/it_pakar/Projects/dubbfreelancers/Pods/QuickBlox/Quickblox.framework/Quickblox(QBLGeoDataFilter.o)
ld: 4 duplicate symbols for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by soulfly** [comment]
Try to update Xcode to latest 6.3 - this should work

**Comment by kondak3** [comment]
Hi this warning got in Xcode 7.0. please let me know solution.


ld: warning: object file (/Users/Impressol/Desktop/QuickBlox/Grouper'sApp/GrouperApp/GrouperApp/Grouper_Assets/Quickblox.framework/Quickblox(QBSocialLoginDialog.o)) was built for newer iOS version (7.0) than being linked (6.0)
ld: warning: object file (/Users/Impressol/Desktop/QuickBlox/Grouper'sApp/GrouperApp/GrouperApp/Grouper_Assets/Quickblox.framework/Quickblox(QBSessionParameters.o)) was built for newer iOS version (7.0) than being linked (6.0)
ld: warning: object file (/Users/Impressol/Desktop/QuickBlox/Grouper'sApp/GrouperApp/GrouperApp/Grouper_Assets/Quickblox.framework/Quickblox(QBApplication.o)) was built for newer iOS version (7.0) than being linked (6.0)
ld: warning: object file (/Users/Impressol/Desktop/QuickBlox/Grouper'sApp/GrouperApp/GrouperApp/Grouper_Assets/Quickblox.framework/Quickblox(QBSession.o)) was built for newer iOS version (7.0) than being linked (6.0)
ld: warning: object file (/Users/Impressol/Desktop/QuickBlox/Grouper'sApp/GrouperApp/GrouperApp/Grouper_Assets/Quickblox.framework/Quickblox(QBCBlobObjectAccessResponseSerialisation.o)) was built for newer iOS version (7.0) than being linked (6.0)
ld: warning: object file (/Users/Impressol/Desktop/QuickBlox/Grouper'sApp/GrouperApp/GrouperApp/Grouper_Assets/Quickblox.framework/Quickblox(QBConnection.o)) was built for newer iOS version (7.0) than being linked (6.0)
ld: warning: object file (/Users/Impressol/Desktop/QuickBlox/Grouper'sApp/GrouperApp/GrouperApp/Grouper_Assets/Quickblox.framework/Quickblox(QBResponse.o)) was built for newer iOS version (7.0) than being linked (6.0)

**Comment by AndreyMoskvin** [comment]
Hi,

You can ignore this warnings - but it seems that your iOS deployment target is 6.0. Our SDK supports iOS 7.0+.
