### ISSUE TITLE
App Crashes:  Could not setAccountKey

### ISSUE THREAD

**Issue by williamtran1988** [QuickBlox/quickblox-ios-sdk#620]
Hi All,

I am facing a problem while upgrading quickblox android version to latest one. (android quickblox 3.0)

        String appID = info.getString("appID");
        String authKey = info.getString("authKey");
        String authSec = info.getString("authSecret");
        String accountKey = info.getString("accountKey");

        QBSettings.getInstance().init(cordova.getActivity().getApplicationContext(), appID, authKey,authSec);
        QBSettings.getInstance().setAccountKey(accountKey);

        QBRTCConfig.setMaxOpponentsCount(6);
        QBRTCConfig.setDisconnectTime(30);
        QBRTCConfig.setAnswerTimeInterval(60l);
        QBRTCConfig.setStatsReportInterval(60);
        QBRTCConfig.setDebugEnabled(true);

And we received this error message:
WebRTC:"accountKey is null. You must call QBSettings.getInstance().setAccountKey(String) before using the QuickBlox library

Could somebody help me on this?

**Comment by williamtran1988** [comment]
the problem actually could be:


10-18 14:17:26.654  4415  4500 E AndroidRuntime: FATAL EXCEPTION: JavaBridge
10-18 14:17:26.654  4415  4500 E AndroidRuntime: Process: ch.alarmpb_test, PID: 4415
10-18 14:17:26.654  4415  4500 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/gson/GsonBuilder;
10-18 14:17:26.654  4415  4500 E AndroidRuntime: 	at com.quickblox.core.parser.QBJsonParser.parseJsonResponse(QBJsonParser.java:103)
10-18 14:17:26.654  4415  4500 E AndroidRuntime: 	at com.quickblox.core.parser.QBJsonParser.parse(QBJsonParser.java:91)
10-18 14:17:26.654  4415  4500 E AndroidRuntime: 	at com.quickblox.core.Query.parseAccountRequest(Query.java:339)
10-18 14:17:26.654  4415  4500 E AndroidRuntime: 	at com.quickblox.core.Query.access$000(Query.java:36)
10-18 14:17:26.654  4415  4500 E AndroidRuntime: 	at com.quickblox.core.Query$1.completedWithResponse(Query.java:229)
10-18 14:17:26.654  4415  4500 E AndroidRuntime: 	at com.quickblox.core.server.HttpRequestRunnable$1.handleMessage(HttpRequestRunnable.java:43)
10-18 14:17:26.654  4415  4500 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
10-18 14:17:26.654  4415  4500 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:158)
10-18 14:17:26.654  4415  4500 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:61)
10-18 14:17:26.654  4415  4500 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.gson.GsonBuilder" on path: DexPathList[[zip file "/data/app/ch.alarmpb_test-1/base.apk"],nativeLibraryDirectories=[/data/app/ch.alarmpb_test-1/lib/arm, /data/app/ch.alarmpb_test-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
10-18 14:17:26.654  4415  4500 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
10-18 14:17:26.654  4415  4500 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
10-18 14:17:26.654  4415  4500 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
10-18 14:17:26.654  4415  4500 E AndroidRuntime: 	... 9 more
10-18 14:17:26.654  4415  4500 E AndroidRuntime: 	Suppressed: java.lang.ClassNotFoundException: com.google.gson.GsonBuilder
10-18 14:17:26.654  4415  4500 E AndroidRuntime: 		at java.lang.Class.classForName(Native Method)
10-18 14:17:26.654  4415  4500 E AndroidRuntime: 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
10-18 14:17:26.654  4415  4500 E AndroidRuntime: 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
10-18 14:17:26.654  4415  4500 E AndroidRuntime: 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
10-18 14:17:26.654  4415  4500 E AndroidRuntime: 		... 10 more
10-18 14:17:26.654  4415  4500 E AndroidRuntime: 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
10-18 14:17:26.654  3526  4983 W VirtualScreenManagerService: moveTaskBackToDisplayIfNeeded(): top activity or app is null
10-18 14:17:26.664  3526  4983 D InputDispatcher: Focused application set to: xxxx

**Comment by Raikerian** [comment]
Hi @williamtran1988 

This iOS SDK repository, please refer your issue to an appropriate android SDK repository here: https://github.com/QuickBlox/quickblox-android-sdk/issues

Have a nice day.

**Comment by josesanchezgruposellcom** [comment]
What happend with answer of this question. I have the same issue and cannot create a application session to.
