### ISSUE TITLE
quickblox support for tvOS

### ISSUE THREAD

**Issue by syscraftiOS** [QuickBlox/quickblox-ios-sdk#621]
This is not related to any issue, just want to know whether Quickblox supports tvOS yet or not.

Thanks

**Comment by Raikerian** [comment]
Hi,

Unfortunately I cannot give you any official answer on tvOS support. You can try and test it now.
As for official support, we are having plans to fully test tvOS integration with our framework in a near future, no any fixed ETA yet.
