### ISSUE TITLE
How to get the list of contact requests sent  to me?

### ISSUE THREAD

**Issue by sauvikatinnofied** [QuickBlox/quickblox-ios-sdk#623]
Hi

`QBChat.instance().contactList!.pendingApproval` is simply returning the _contact request sent **FROM** me_. I have gone through https://quickblox.com/developers/SimpleSample-chat_users-ios#Guide:_Getting_Started_with_Chat_API but could not find out a way to get _the list of contact requests sent to me_ through iOS Sdk. Can you please guide me to find out how to get the _list of contact requests sent **TO** me_?

**Comment by Raikerian** [comment]
Hi,

There is no such API as who sent you a contact request. Thats how XMPP roster feature works. In order to become "friends", you both need to subscribe to each other.

Thats why in our [Q-municate](https://github.com/QuickBlox/q-municate-ios) project we are sending notification messages about contact requests. Check it out.

**Comment by adil-appifytech** [comment]
@Raikerian - Can you point out exact location in code where that part is handled? That would be of great help. Thanks.

**Comment by Raikerian** [comment]
Sure, this is a part of our [QMServices](https://github.com/QuickBlox/q-municate-services-ios) project (wrapper methods over our SDK, which are very helpful, they are also including persistent storage).
You can find lots of helpful methods here: https://github.com/QuickBlox/q-municate-services-ios/blob/master/QMChatService/QMChatService/QMChatService.m (as well as their handling).

Here is contact request message example: https://github.com/QuickBlox/q-municate-ios/blob/4a539a2584b57a72342dd6eccc586d39971a6b43/Q-municate/Classes/Core/QMContactManager/QMContactManager.m#L52-L58

**Comment by VitaliyGuru** [comment]
@adil-appifytech  Any updates?
