### ISSUE TITLE
Not support emoji in QBUUser.fullName

### ISSUE THREAD

**Issue by dungnc** [QuickBlox/quickblox-ios-sdk#624]
Hi, i can't update full name with some emoji character, it replace with question mask

Anybody can help?

**Comment by Raikerian** [comment]
Hi,

This is a known server-side issue. Unfortunately we cannot give you any ETA on when this will be fixed.

**Comment by Raikerian** [comment]
Closing due to issue is not iOS SDK related. You can always check changelogs for server and other frameworks by following our blog here: http://quickblox.com/blog/
