### ISSUE TITLE
QBCBlob UID vs ID

### ISSUE THREAD

**Issue by harrisonsj** [QuickBlox/quickblox-ios-sdk#625]
I have been storing the ID of QBCBlobs (images) in my custom objects so that the images can be both displayed (using privateURLForID) and deleted (using QBRequest method deleteBlobWithID) without having to download the blob.

Now that privateURLForID has been removed I was hoping to just change all the IDs I have stored to the UIDs instead, however none of the QBRequest methods are available using the UID.

Are there any plans to add methods to QBRequest utilising the UID, or do I now need to either store both the ID & UID or download the Blob before displaying/deleting etc.?

**Comment by VitaliyGuru** [comment]
Hello @harrisonsj ,  Unfortunately we cannot give you any ETA for this methods. For now you can either store both the ID & UID.
