### ISSUE TITLE
Saving the chat images

### ISSUE THREAD

**Issue by mallikaD** [QuickBlox/quickblox-ios-sdk#626]
How to save the chat dialogue images into the device?Is it possible or not?

**Comment by VitaliyGuru** [comment]
@mallikaD  Hello. It's possible, but it's not implemented in our sample chat.
If you have instance of UIImage you can save it using different ways [e.g.](http://stackoverflow.com/questions/6821517/save-an-image-to-application-documents-folder-from-uiview-on-ios) . The approach depends on your needs.

**Comment by mallikaD** [comment]
ok thank you

**Comment by VitaliyGuru** [comment]
@mallikaD  If you have any questions related to this issue just reopen it.
