### ISSUE TITLE
chat is disconnecting itself calling the method chatDidAccidentallyDisconnect()

### ISSUE THREAD

**Issue by rvilches** [QuickBlox/quickblox-ios-sdk#627]
*Help avoid duplicate issue reports, check [existing issues](https://github.com/QuickBlox/quickblox-ios-sdk/issues)*
 
**Environment details**
iOS 9.3
quickblox SDK 2.7.3
**Did this work before?**
YES 

**Expected behavior**
To maintain a chat connection

**Actual behavior**
chats connects but afterwards, it disconnects itself without any user interaction and with an error

**Logs**
*Attach full logs that will describe your problem (please, use github [gist](https://gist.github.com/))*

https://gist.github.com/rvilches/96c79e0f6d7ca60e469a84261aaf7c83/revisions

**Steps to reproduce the behavior**
Just connect to the chat and it will disconnect automatically

**Any others comments?**

**Comment by VitaliyGuru** [comment]
@rvilches , Hello. Looks like it was a temporary server-side issue according to [maintenance](http://quickblox.com/blog/maintenance-on-shared-instance-on-october-26th-wednesday/).
Are you still facing with this problem?

**Comment by rvilches** [comment]
Indeed, it was fixed thanks.
