### ISSUE TITLE
User is fetching with ID. ChatRoom is not created with that User ID. 

### ISSUE THREAD

**Issue by ajay2c9** [QuickBlox/quickblox-ios-sdk#628]
Hi ,
    I am quickblox in my project. when i try to retrieve a user with id the user is not displaying.But other user are displaying with ids.
When i login into my app in the background I am saving the Quickblox userid in my server.
By using the Quickblox userid,i am retrieving the user.
I login with one user "A" some days before and make some chat another user "B". 
Currently when i login with some other user "C" and trying to make chat with "A". Chat Room is created without that user. But the user is fetch with that ID. When the user is checking in the admin panel user "A" is not displaying in users tab. When make a search in user tab user "A" suggestion is displayed.But user "A" is not displayed in the table and displays as "no matching record found". While searching in Chat tab. User "A" chatrooms  are  displaying.How to get that user(Activate) withoout re-login. How to create the chatrooms in that scenerio.

Thank you

**Comment by Raikerian** [comment]
Hi @ajay2c9 

Is this issue same as https://github.com/QuickBlox/quickblox-ios-sdk/issues/630 ?

If yes please close this one and lets continue investigating it in another one.
