### ISSUE TITLE
Error Email has already been taken

### ISSUE THREAD

**Issue by williamtran1988** [QuickBlox/quickblox-ios-sdk#629]
Hi All,

I have a problem that i could not signup or signin to application. When i go to admin page to check our users. I did not see that user in page. But i could see it in search box, however, when i click to search result "Blank error" appears. I tried to signup new user with current user's informations. But i got the error message in read line:
"Error
Email has already been taken"

It could be an issue from Quickblox. Please take a look at this. Just let me know if you need further information.

**Comment by soulfly** [comment]
@williamtran1988 how many applications do you have in QuickBlox admin panel?

**Comment by VitaliyGuru** [comment]
@williamtran1988 , Any updates?

**Comment by Raikerian** [comment]
@williamtran1988 we haven't hear any updates from you in a long time, if you are still having this problem, please let us know. If you have any other questions, feel free to let us know by creating a separate issue.

**Comment by miguelgutierrez** [comment]
I had the same problem but it was because I was using same "account key" with two projects: release and debug.  If I had to try signup a "user1" in release but "user1" exists in debug, the system responds with "has already been taken"
