### ISSUE TITLE
Issue in receiving offline messages with QuickBlox

### ISSUE THREAD

**Issue by rahulparikh** [QuickBlox/quickblox-ios-sdk#63]
I'm working on a app which supports private chat via QuickBlox iOS SDK. Everything working fine, except this scene, suppose we've two users, UserA and UserB. Both can able to receive messages if they successfully logged in into QBChat. Now UserB went to background from app (I've explicitly logged him out from the chat). Here, UserA sends a message "You're offline! And yeah, you'll never get this message because there's a possible bug in QuickBlox." Again, UserB back to the app (and I'll make him login in again in QBChat), but strangely he'll not receive that message, however its on application dashboard in QuickBlox page. Again, its also showing that message as lastMessageText of QBChatDialog object. Now the real horror scene will come, again UserB went to background, if UserA sends messages like, A, B, C, D, E. When he'll come back to the app, UserB would only receive B, C, D, E. And not the A which was the first message in queue. And yes, its also on application dashboard and also updated for QBChatDialog object.

**Comment by iSevenDays** [comment]
Please attach logs for UserA and UserB and IDs of messages.

**Comment by rahulparikh** [comment]
Hello,

I fixed this issue with the following code.

[QBSettings useTLSForChat:YES];
