### ISSUE TITLE
Chat dialog creation making an issue.

### ISSUE THREAD

**Issue by ajay2c9** [QuickBlox/quickblox-ios-sdk#630]
Hi,
I am using Quickblox in my project. when I am creating a chat dialog with one user it is not creating. I am getting the user detail.

login user:tatanga(16190990)
Other user :voon(16230578)
These are the details.
1. Getting the user detail by name. The user information output like below.
```
 [QBUUser]:
  ID:16230578
  created at:(null)
  updated at:(null)
  externalUserID:0
  blobID:0
  facebookID:(null)
  twitterID:(null)
  twitterDigitsID:(null)
  full name:(null)
  email:(null)
  login:VOON
  phone:(null)
  tags:(null)
  lastRequestAt:(null)
  customData:(null)
  website:(null)"
```

Generating the Chat dialog for creating the Chat room.
```
ID:(null)                      
    Created At:(null)                      
    Updated At:(null)                      
    Room JID:(null)                      
    name:Tatanga,VOON                      
    photo:(null)                      
    type:2                      
    lastMessage:(null)                      
    lastMessageDate:(null)                      
    occupantIDs:(
    16230578
)                      
    userID:0                      
    data:(null)                      
    unreadMessagesCount:0                      
    lastMessageUserID:0

```
But the chat dialog is created with the login userid.
 ```
ID:5816c944a0eb47d0b600013d                      
    Created At:2016-10-31 04:32:04 +0000                      
    Updated At:2016-10-31 04:32:04 +0000                      
    Room JID:36508_5816c944a0eb47d0b600013d@muc.chat.quickblox.com                      
    name:Tatanga,VOON                      
    photo:(null)                      
    type:2                      
    lastMessage:(null)                      
    lastMessageDate:(null)                      
    occupantIDs:(
    16190990
)                      
    userID:16190990                      
    data:(null)                      
    unreadMessagesCount:0                      
    lastMessageUserID:0

```
How to create the chatRoom with that user.
Please give suggestions.
Thank you

**Comment by VitaliyGuru** [comment]
@ajay2c9 , Hi.
We can't give you suggestion, because you haven't provided your code for dialog creation.
Did you follow (this instructions)[http://quickblox.com/developers/SimpleSample-chat_users-ios#Create_new_dialog]?

**Comment by ajay2c9** [comment]
1. For creating the chat dialog below method is used.
login user:tatanga(16190990)
NSMutableArray*users=[NSMutableArray new];
                QBUUser*user=[QBUUser new];
                user.login=[name uppercaseString];//VOON
                user.ID=[userid integerValue];//16230578
                [users addObject:user];

 NSString*name = [NSString stringWithFormat:@"%@,", [QBSession currentSession].currentUser.login];
                for (QBUUser *user2 in usersarray3) {
                    name = [NSString stringWithFormat:@"%@%@,", name, user2.login];
                }
[ServicesManager.instance.chatService createGroupChatDialogWithName:name photo:nil occupants:users completion:^(QBResponse *response, QBChatDialog *createdDialog) {
        if (response.success) {
} else {
            if (completion) completion(nil);
        }
    }];
For this I keep the occupants as user retrieved from step 1. I print the log before and after the creating the chat dialog. Those are shown in above comment

**Comment by Raikerian** [comment]
Hi,

Please provide full logs from app start till the issue is happened. To enable full logs use this lines of code: https://gist.github.com/Raikerian/ea57ae2da2c4ed8c56c5

**Comment by Raikerian** [comment]
@ajay2c9 any updates on this?

**Comment by Raikerian** [comment]
Closing due to lack of response from issue creator.
If the issue is still there, I recommend you to create a new one with logs being mandatory.
