### ISSUE TITLE
QBChatDialog roomJID is readonly, why?

### ISSUE THREAD

**Issue by adil-appifytech** [QuickBlox/quickblox-ios-sdk#637]
**Environment details**
*iOS version, Quickblox iOS SDK version, QuickbloxWebRTC SDK version (optional)*
iOS 8.0, Quickblox iOS SDK 2.8.0.1

**Did this work before?**
N/A

**Expected behavior**
To send the message to a dialog, I have to create one from my local db but I can't assign roomJID because it's readonly.

**Actual behavior**
roomJID is readonly => I can't create object of QBChatDialog.

**Logs**
N/A

**Steps to reproduce the behavior**
N/A

**Any others comments?**
 N/A

**Comment by Raikerian** [comment]
Hi,

roomJID is auto generated for group dialogs using dialogID. You do not need to modify it.

**Comment by adil-appifytech** [comment]
@Raikerian 

So following code will automatically get roomJID from server?

`QBChatDialog(dialogID: dialog.dialogID, type: .Group)`

**Comment by Raikerian** [comment]
Yes.

**Comment by adil-appifytech** [comment]
@Raikerian - Thanks 👍
