### ISSUE TITLE
Debug not works when adding Quickblox iOS SDK via CocoaPods

### ISSUE THREAD

**Issue by kirillkhlopko** [QuickBlox/quickblox-ios-sdk#639]
Hello!

I'm using now SDK version 2.7.4, but also checked it on v2.8 and v2.8.01. 
Faced with problem, that I'm not able to debug my app when Quickblox SDK loaded from CocoaPods. 

Earlier, I had a problem, that Xcode crashing every time in same case. For now, it do not crashing, but I still not able to debug app when sdk added via pods. 

Hope, you'll help with this problem or mark this as bug if it is.

**Comment by Raikerian** [comment]
Hi,

Please give us more details, how does it look that you cannot debug app? Any additional info would be helpful.

**Comment by kirillkhlopko** [comment]
For now debugger does not capture any values. On left side I'm able to see only names of variables, but not values or types. In console I'm not able to print any value too.
I'll add screenshot a bit later.

**Comment by Raikerian** [comment]
Are you using swift?

**Comment by Pro100Andrey** [comment]
Hi @kirillkhlopko, please provide your `pod` file, `Xcode` version or `demo project` for example

**Comment by Pro100Andrey** [comment]
@kirillkhlopko Any updates?

**Comment by Raikerian** [comment]
@kirillkhlopko we haven't hear any updates from you for a while, if you are still having this issue, please let us know. If you have any other questions, feel free to create a separate issue describing it.
