### ISSUE TITLE
Not able to build since I update the framework v2.2.3

### ISSUE THREAD

**Issue by rahulparikh** [QuickBlox/quickblox-ios-sdk#64]
I am not able to build in device since I update the QuickBlox Framework, I am able to run the app in simulator but not able to run on device.

![screen shot 2015-04-29 at 12 32 29 pm](https://cloud.githubusercontent.com/assets/4629057/7385954/a17b49c2-ee6b-11e4-9192-eb24a025a784.png)

**Comment by mohsinalimat** [comment]
Try to update Xcode to latest Xcode 6.3 - this should work
