### ISSUE TITLE
1-1 Chat notifications Offline

### ISSUE THREAD

**Issue by mallikaD** [QuickBlox/quickblox-ios-sdk#640]
Hi,

Is 1-1 chat notifications is supported by quickblox when user is in offline?Is that code is available in sample program?If supported please suggest me the link for offline chat messages.

**Comment by Raikerian** [comment]
Hi,

There are automatic chat alerts that are server-side. More info: http://quickblox.com/developers/Chat#Alerts

**Comment by mallikaD** [comment]
Can we integrate the APNS p12 file for this.I found this link for uploading.Is it mandatory to upload the p12 file?I attached this in below screen shot. If it is possible then can you please update the next procedure.
![screen shot 2016-11-07 at 6 18 20 pm](https://cloud.githubusercontent.com/assets/10229968/20058429/00f04818-a517-11e6-8885-7dc24d1a01c9.png)

**Comment by mallikaD** [comment]
Offline chat messages are not coming automatically. I followed the link you mentioned above that "automatic chat alerts that are server-side".I enable the option also.

**Comment by Raikerian** [comment]
Alerts are offline push notifications. If you are not receiving them check push notification queue in admin panel. If they are there, double check your certificates, they must not be valid.
Not really sure what do you mean about p12 question. You need to upload a valid certificate for all push notifications to work.

**Comment by mallikaD** [comment]
When i am sending the push notifications from admin panel below type of error is coming.

**Error
No recipients. At least one user should be subscribed for APNS (Apple Push) (through SDK or REST API)**

**Comment by Raikerian** [comment]
It says that you didn't subscribe user to push notifications. Check it by following guide here: http://quickblox.com/developers/SimpleSample-messages_users-ios#Giving_a_user_a_Push_Notification_subscription

**Comment by mallikaD** [comment]
For subscribing to the push notification i used the below code:

    QBMSubscription *subscription = [QBMSubscription subscription];
    subscription.notificationChannel = QBMNotificationChannelAPNS;
    subscription.deviceUDID = deviceIdentifier;
    subscription.deviceToken = deviceToken;
    [QBRequest createSubscription:subscription successBlock:^(QBResponse *response, NSArray *objects) {
    } errorBlock:^(QBResponse *response) {
                    NSLog(@"ERROR GROUP %@",response.error.reasons);
    }];

**Getting below error:**

ERROR GROUP {
    errors =     {
        "client_identification_sequence" =         (
            "is invalid"
        );
    };
}

**Comment by Raikerian** [comment]
Please attach logs for this error where we can see our QB request.

**Comment by mallikaD** [comment]
Now i am able to receive the push notifications from admin panel.But i want push notifications for 1-1 chat.If i am chatting with another user then that user receives my chat messages like push notification.

**Comment by Raikerian** [comment]
Can we see your logs for the error you have linked above?

**Comment by Raikerian** [comment]
Solved by OP here: https://github.com/QuickBlox/quickblox-ios-sdk/issues/646#issuecomment-259128198
