### ISSUE TITLE
Cannot create/join room when already creating/joining/joined

### ISSUE THREAD

**Issue by iurichiba** [QuickBlox/quickblox-ios-sdk#642]
Hi, I'm sorry that this is a duplicate issue, but the last issue I checked with this problem was created on Oct 7th, and it was closed because it _needed further investigation_ (#616) -- and there're lots of other issues explaining similar problems joining group chats.

Basically, what happens is:
- User can't send messages, it fails declaring that you can't send messages because you're not joined to the (group) dialog;
- We try to reconnect, using joinWithCompletionBlock, but it fails with the "Cannot create/join room when already creating/joining/joined" error.

Then it's the same loop: messages fail because the user didn't join the dialog - but when we try to join, we receive an error telling us that we can't because we're already joined.
 
**Environment details**
This issue is seen in every iOS version we tested (since 7).
We're using QuickBlox (2.7.4), QMServices (0.4.4) and QMChatViewController (0.3.10).

**Did this work before?**
I don't think so. We've been using QuickBlox for roughly 4-5 months and we've been encountering this issue on and off since then. It doesn't happen with everyone and it doesn't happen all the time, it's strange - if you close the app and try again, _sometimes_ it works (probably because it resets QB connections).

**Expected behavior**
Send messages reliably.

**Actual behavior**
Works around 80% of the time.

**Logs**
Here's my Xcode log, trying to send messages (we immediately try to reconnect when a message fails):
`2016-11-07 17:23:30.440256 Lassie Development[2158:573211] Failed to send message with error: Error Domain=com.quickblox.chat Code=-1002 "(null)" UserInfo={NSLocalizedRecoverySuggestion=You are not connected to chat.}
2016-11-07 17:23:32.874510 Lassie Development[2158:573364] -[QBChatDialog sendIsTypingInGroup] -> Error Domain=com.quickblox.chat Code=-1001 "(null)" UserInfo={NSLocalizedRecoverySuggestion=You are not joined to the dialog.}`

**Steps to reproduce the behavior**
I don't really know, sorry. I couldn't pinpoint what causes it to happen.

**Any others comments?**
We've been encountering this problem for months, and it's incredibly frustrating for our users (and for us). If it's still a server-side issue, is there _any_ expectation as to when it will be fixed?

**Comment by iurichiba** [comment]
I sent the wrong log, sorry -- it doesn't contain the reconnect error.
But that error shouldn't happen, either way.

We're experiencing the join error, but we shouldn't have to manually join, anyways. Doesn't the SDK automatically handle it? Any idea as to why it doesn't work, sometimes -- and how can I avoid this error. As it is, our users get frustrated trying to send a message just to realize it's not connected.

Oh, and btw, if you need it: we use the Advanced Plan.

**Comment by Pro100Andrey** [comment]
Hi @iurichiba. About `We're experiencing the join error, but we shouldn't have to manually join, anyways. Doesn't the SDK automatically handle it?` - `NO`

You should join in to chat dialogs (group, public) manually after these methods being called: 

See `QBChatDelegate.h`

```objc
- (void)chatDidConnect;
- (void)chatDidReconnect;
```

For every group dialogs you are working with.

**Comment by Raikerian** [comment]
We will also push an update somewhere tomorrow for our SDK which will contain some reconnect issues with rooms (although that doesn't affect any automatic join, you still need to iterate all rooms and join them on connect).

**Comment by iurichiba** [comment]
Thanks for the answer, guys - I'm gonna try the update when it's out.

And @Pro100Andrey, that's strange, because I don't do that and it _usually_ works. I use some of your classes as a base for our messaging controllers - maybe QMChatViewController does that? Or some of the classes in QMServices?

I'm gonna check the code for joinToGroupDialog messages, and maybe I can capture any join errors and use that to manually retry until it joins successfully.

**Comment by iurichiba** [comment]
I checked for chatDidConnect and it calls chatServiceChatDidConnect, that I **do** use, but I don't join any dialogs then -- I just get the messages and read them (we read them all, instead of one at a time)

Should I joinToGroupDialog, then? I don't see why it would make any difference, considering that around 80% of the time we're already joined, but I can try.

**Comment by iurichiba** [comment]
Hi, upon further investigation, I found out that QMServices autoJoins group dialogs.
I'm using QMServices v0.4.4.

**Comment by Raikerian** [comment]
Please check latest Quickblox iOS SDK 2.9.

**Comment by iurichiba** [comment]
@Raikerian thanks, I'm gonna try it and report back to you in a few days :)

**Comment by iurichiba** [comment]
@Raikerian hi! I think it worked, thanks!
But I got a few other bugs -- they're unrelated, so I'm creating another issue to discuss that.
