### ISSUE TITLE
How to reset user password (using Email)

### ISSUE THREAD

**Issue by rvilches** [QuickBlox/quickblox-ios-sdk#643]
*iOS version, Quickblox iOS SDK version, QuickbloxWebRTC SDK version (optional)*
iOS 9.3, QBVersion 2.7.3

**Did this work before?**
Dont know , I had not use it before
**Expected behavior**
to send an email with a password reset link

**Actual behavior**
Logs an 404 error "Not found"

**Logs**
https://gist.github.com/rvilches/fb9a4656fc655f1428ae5e6c96dd725c

**Steps to reproduce the behavior**
call the method:
```swift
QBRequest.resetUserPasswordWithEmail(QBSession.currentSession().currentUser!.email!, successBlock: { (response:QBResponse) in
    
                }, errorBlock: { (error:QBResponse) in
                
            })

```
**Any others comments?**

**Comment by Raikerian** [comment]
Hi,

That basically says that requested email does not exist.

**Comment by rvilches** [comment]
Does not exist on QB systems? Because I have 4 active  emails and I tried with each one but It returns the same error all the time. Plus when I try to update a user email it returns me a success response But the email doesnt change, it remains with the old one.

**Comment by Raikerian** [comment]
Is this email of an account owner? Or a simply new created user?

**Comment by Raikerian** [comment]
About email update, please attach logs for that issue as well.

**Comment by rvilches** [comment]
Both. Here is the thing, if I create a user an send it a "confirm email" and the user confirms it, then that user can use the methor "resetUserPasswordWithEmail". Otherwise if the user doesnt confirm his email account the method returns that error. I thing that that is a correct behaviour , but the problem with that is, that up to where I know, I can only send the confirmation email once , when the user signs up. So if the user havent confirm his email he will not be able to reset his password if he doesnt remember the oldone.

**Comment by rvilches** [comment]
Hi guys, any news?

**Comment by Raikerian** [comment]
This can be possible a server-side issue. I will investigate it and let you know.

**Comment by Raikerian** [comment]
This is confirmed server-side issue, it was reported to our server-side team. Although no any ETA from them for now.

**Comment by soulfly** [comment]
This should work now

**Comment by Raikerian** [comment]
Marking as fixed and closing. If you are still having troubles with this, please let us know by creating a new issue with reference.
