### ISSUE TITLE
Not able to receive message from GroupDialog

### ISSUE THREAD

**Issue by ramanseraphic** [QuickBlox/quickblox-ios-sdk#644]
I am trying to create a group dialog with three users. 
I am confused in usage of APIs and SDK methods. Are these to be used together? 
I am creating a group dialog using API
    https://api.quickblox.com/chat/Dialog.json

To send messages I am using API
    https://api.quickblox.com/chat/Message.json
While sending message, I am not sending  "recipient_id", as I want to send message to group. 

The message is sent successfully, as I can see the message in console. 
In console the group dialog is created successfully and all 3 users can be seen. 

But no delegate method is being called on receiver side for receiving the message. 

The strange thing is if I add "recipient_id" parameter while sending message and its sent as a Private Message, the delegate method is being called. 
and that is:
    - (void)chatDidReceiveMessage:(QBChatMessage *)message

The delegate method that should be called when its a group message is not being called which according to me is:
    - (void)chatRoomDidReceiveMessage:(QBChatMessage *)message fromDialogId:(NSString *)dialogId

I believe that the group has to be joined by other user as well. But to join the group I am not able to find a method. The method mentioned in your SDK is not available. 

More queries:
1. When the API is being used for sending messages but not SDK methods, will the delegate work?
I believe they should because when I send message as a private message its working. 
2. How to join the group dialog?

**Comment by VitaliyGuru** [comment]
As for second question you can use method 
`   QBChatDialog * dialog =  ... //your dialog
    [dialog joinWithCompletionBlock:^(NSError * _Nullable error) {
        
    }];`

**Comment by ramanseraphic** [comment]
Thanks for reply, I used the above code which you given but method giving some error screen shot given below. 
![screen shot 2016-11-09 at 11 41 38 am](https://cloud.githubusercontent.com/assets/23334871/20128868/95920276-a671-11e6-9c94-20cf24adf0f6.png)

**Comment by Pro100Andrey** [comment]
Hi @ramanseraphic please provide version of SDK.

**Comment by Pro100Andrey** [comment]
@ramanseraphic  Any updates

**Comment by ramanseraphic** [comment]
Thanks for reply
 "QB-SDK" = "iOS 2.1";

**Comment by Pro100Andrey** [comment]
@ramanseraphic  Sorry we don't support v 2.1 please upgrade to last version of SDK 2.9. Thanks

**Comment by ramanseraphic** [comment]
Thanks @Pro100Andrey

**Comment by VitaliyGuru** [comment]
@ramanseraphic Look's like you have the [same problem](https://github.com/QuickBlox/quickblox-ios-sdk/issues/654#issuecomment-260304684)
