### ISSUE TITLE
Can not take screenshot during video chat.

### ISSUE THREAD

**Issue by brtcck** [QuickBlox/quickblox-ios-sdk#649]
I want to take screenshot during to video chat. The videos not showing in screenshot image. 

When I used Quickblox-Webrtc version 1.0.6 I success to take screenshot with code below. And I used QBGLVideoView. But now I upgraded to Quickblox-Webrtc version to 2.2. I can't take screenshot with code below.

You can see screenshots below.

|I captured the screen on my iOS device using the Sleep/Wake and Home buttons.  |
| ------------- |
|![01](https://cloud.githubusercontent.com/assets/4985113/20136721/0c69723c-a67f-11e6-8f7e-47bf6ef2e2c3.png)|

| Programmatically Screnshot  |
| ------------- |
|![02](https://cloud.githubusercontent.com/assets/4985113/20136724/10280546-a67f-11e6-88b5-f60e6fa38309.png)|

I use these code for screenshot programmatically

```objc
UIGraphicsBeginImageContextWithOptions(view.bounds.size, NO, [UIScreen mainScreen].scale);

[view drawViewHierarchyInRect:view.bounds afterScreenUpdates:YES];

UIImage *image = UIGraphicsGetImageFromCurrentImageContext();

UIGraphicsEndImageContext();
```

**Environment details**
iOS version = iOS 10.1.1
Quickblox iOS SDK version = 2.8
QuickbloxWebRTC SDK version = 2.2

**Comment by Pro100Andrey** [comment]
Hi @brtcck, we need investigate this issue

**Comment by brtcck** [comment]
@Pro100Andrey We can work together if you want to simulate this issue.

**Comment by Pro100Andrey** [comment]
@brtcck 
Please check  `QBRTCRemoteVideoView.h` file 

``` objc 
@protocol QBRTCRemoteVideoViewDelegate;

typedef NS_ENUM(NSUInteger, QBRendererType) {
    
    QBRendererTypeSampleBuffer = 0, // Native renderer, supports acceleration on iOS 8+
    QBRendererTypeEAGL = 1 // OpenGL renderer
};

/// Class used to display remote video track from opponent
@interface QBRTCRemoteVideoView : UIView

//Default QBRendererType QBRendererTypeSampleBuffer;
@property (assign, nonatomic, readonly) QBRendererType rendererType;

/**
 *  Set video track
 *
 *  @param videoTrack QBRTCVideoTrack instance
 */
- (void)setVideoTrack:(QBRTCVideoTrack *)videoTrack;

@end
```

and send `rendererType` for your remote video view in to `QBRendererTypeEAGL` , default value - `QBRendererTypeSampleBuffer`

**Comment by Pro100Andrey** [comment]
@brtcck  known issue for [AVSampleBufferDisplayLayer](http://stackoverflow.com/questions/28774466/video-stream-in-avsamplebufferdisplaylayer-doesnt-show-up-in-screenshot)

**Comment by Pro100Andrey** [comment]
@brtcck Any updates?

**Comment by brtcck** [comment]
I investigated your answers. But I can not find how to get CVImageBufferRef. I maybe get CVImageBufferRef from LocalVideoTrack but I how can I get CVImageBufferRef from RemoteVideoTrack?

**Comment by Pro100Andrey** [comment]
Workaround :

1. Inherit with QBRemoteVideoTrack, and redefine  private method `- (void)renderFrame:(RTCVideoFrame *)frame`  with extension category, for example:

```objc
@interface QBRTCRemoteVideoView ()
- (void)renderFrame:(RTCVideoFrame *)frame;
@end

@interface MyRemoteVideoView : QBRTCRemoteVideoView
@property (nonatomic, strong) QBRTCFrameConverter *frameConverter;
@property (nonatomic, weak) RTCVideoFrame *currentFrame;
@end

@implementation MyRemoteVideoView

- (void)renderFrame:(RTCVideoFrame *)frame {

    [super renderFrame:frame];
    _ currentFrame = frame;

}
@end

//Any place

- (UIImage *)screenshot {

    MyRemoteVideoView *videoView = ....
    QBRTCFrameConverter *frameConverter = [[QBRTCFrameConverter alloc] init];
    CMSampleBufferRef ref = [frameConverter copyConvertedFrame: videoView.currentFrame];

    CIImage *ciImage = [CIImage imageWithCVPixelBuffer:imageBuffer];
    CIContext *temporaryContext = [CIContext contextWithOptions:nil];
    CGImageRef videoImage = [temporaryContext
                             createCGImage:ciImage
                             fromRect:CGRectMake(0, 0,
                                                 CVPixelBufferGetWidth(imageBuffer),
                                                 CVPixelBufferGetHeight(imageBuffer))];
    
    UIImage *image = [[UIImage alloc] initWithCGImage:videoImage];
    CGImageRelease(videoImage);
    
    return image;
}

```

**Comment by Pro100Andrey** [comment]
@brtcck Any updates?

**Comment by brtcck** [comment]
@Pro100Andrey Thanks for your reply. But I don't fully understand. I tried but not. Can you explain detaily for localvideoview and remotevideoview?

**Comment by Pro100Andrey** [comment]
Hi @brtcck  please check:
<img width="531" alt="v2 2" src="https://cloud.githubusercontent.com/assets/1109916/20265273/cf7c324e-aa78-11e6-9556-7bf70fa7761f.png">

**Comment by brtcck** [comment]
@Pro100Andrey I create VideoTrack class inherit from QBRTCVideoTrack. You can see screenshots below.

![ekran resmi 2016-11-14 16 40 09](https://cloud.githubusercontent.com/assets/4985113/20266867/b590d116-aa80-11e6-84f8-c55cde7287f3.png)

![ekran resmi 2016-11-14 16 40 00](https://cloud.githubusercontent.com/assets/4985113/20266881/c0d67788-aa80-11e6-8bbf-c52410d756ee.png)

And later. I create RemoteVideoView class inherit from QBRTCRemoteVideoView.

![ekran resmi 2016-11-14 16 40 21](https://cloud.githubusercontent.com/assets/4985113/20266893/c865a514-aa80-11e6-8c77-2679bfc68771.png)

![ekran resmi 2016-11-14 16 39 31](https://cloud.githubusercontent.com/assets/4985113/20266902/d070b8f2-aa80-11e6-9ceb-ff0e685b7bc8.png)

QBRTCVideoTrack and QBRTCRemoteVideoView not have renderFrame method. I add renderFrame method from RTCVideoRenderer protocol. But renderFrame method not called and currentFrame is nil object. 

![ekran resmi 2016-11-14 16 39 10](https://cloud.githubusercontent.com/assets/4985113/20266914/d6a3f266-aa80-11e6-8645-383f62e22c59.png)

What is my mistake? Can you explain me detaily?

**Comment by haifizarshad** [comment]
my app is getting crashed on this line, as i got NULL frame, 
CMSampleBufferRef ref = [frameConverter copyConvertedFrame:videoView.currentFrame];

**Comment by brtcck** [comment]
@Pro100Andrey I create category class from QBRTCRemoteVideoView. And I implemented RTCVideoRenderer Protocol. if I implemented delegate on my category class, RemoteVideoView can not showing video stream (RemoteVideoView is blank). And I can not render remoteVideoStream.

You can show my category class screenshows below.

![ekran resmi 2016-11-21 10 41 02](https://cloud.githubusercontent.com/assets/4985113/20474423/13bc5546-afcf-11e6-9e90-388cc8d17d0d.png)

![ekran resmi 2016-11-21 10 41 18](https://cloud.githubusercontent.com/assets/4985113/20474426/19eb26cc-afcf-11e6-9a36-025d9702e9ea.png)

**Comment by brtcck** [comment]
@Pro100Andrey Did you have an opportunity to examine?

**Comment by Pro100Andrey** [comment]
@brtcck , Sorry , I need more time for make workaround

**Comment by brtcck** [comment]
@Pro100Andrey Thank you for your interest. I'm doing research at the same time. But I have not succeeded yet. I'm waiting for your answer to solve this problem.

**Comment by haifizarshad** [comment]
@Pro100Andrey same issue here & still doing some R&D, In a mean while waiting for your response. Thanks.

**Comment by sveinungkb** [comment]
What's the progress here?
I see you removed the `needs further investigation` label @raikerian, any updates?

**Comment by Raikerian** [comment]
Hi @sveinungkb 

Unfortunately we don't have any workaround for now. This bug will be fixed in version 2.3 which is expected near the end of this year.

**Comment by Pro100Andrey** [comment]
Hi @sveinungkb Please use

```
- (UIImage *)screenshot {
    
    UIGraphicsBeginImageContextWithOptions(self.view.frame.size, NO, 1);
    [self.view drawViewHierarchyInRect:self.view.bounds afterScreenUpdates:NO];
    UIImage *image = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();
    
    return image;
}
```

**Comment by Pro100Andrey** [comment]
Hi @brtcck, any updates?

**Comment by Raikerian** [comment]
Hi again @brtcck @sveinungkb @haifizarshad ,

We have just released our new WebRTC SDK 2.3 which is fixing this issue, cause from now on we are using GLKit for video view.
Here is full changelog of version 2.3: http://quickblox.com/developers/Sample-webrtc-ios#Framework_changelog

Anyway, if you will have any other problems or questions, feel free to start new issue to let us know.

Have a nice holidays.

**Comment by NikunjKumbhani** [comment]
Hello Everyone,
      I would like to take a screenshot of local VideoCaptureView during a call in ios Swift. I used 'QuickBlox', '~> 2.15' and 'Quickblox-WebRTC', '~> 2.6.3' Please give me solution as soon as possible.

**Comment by dhara6894** [comment]
Hello Everyone,
I would like to take a screenshot of ongoing VideoCaptureView during a call in ios Swift. I used 'QuickBlox',
