### ISSUE TITLE
QBRTCPixelFormatBGRA and QBRTCPixelFormatARGB make crash.

### ISSUE THREAD

**Issue by brtcck** [QuickBlox/quickblox-ios-sdk#650]
When I tried to pixelFormat `QBRTCPixelFormatBGRA` and `QBRTCPixelFormatARGB`, the app crash. But When I use pixelFormat `QBRTCPixelFormat420f` and `QBRTCPixelFormat420v`, it works propperly.

My code is

```objc
QBRTCVideoFormat *videoFormat = [[QBRTCVideoFormat alloc] init];
videoFormat.frameRate = 30;
videoFormat.pixelFormat = QBRTCPixelFormatBGRA;
videoFormat.width = 640;
videoFormat.height = 480;

 self.cameraCapture = [[QBRTCCameraCapture alloc] initWithVideoFormat:videoFormat position:AVCaptureDevicePositionFront];
[self.cameraCapture startSession];
```
 
**Environment details**
iOS version = iOS 10.1.1
Quickblox iOS SDK version = 2.8
QuickbloxWebRTC SDK version = 2.2

**Logs**
```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[AVCaptureDevice _setActiveFormat:resetVideoZoomFactorAndMinMaxFrameDurations:] Unsupported format - use -formats to discover valid formats'
*** First throw call stack:
(0x18930a1c0 0x187d4455c 0x190a838b8 0x1006d56c0 0x1006d4498 0x1006cfddc 0x188195200 0x1881951c0 0x1881a3444 0x1881989a8 0x1881a538c 0x1881a50ec 0x18839e2b8 0x18839dda4)
libc++abi.dylib: terminating with uncaught exception of type NSException
Signal: SIGABRT (signal SIGABRT)
Terminated due to signal 6
```

**Comment by Pro100Andrey** [comment]
@brtcck ,please don't use `QBRTCPixelFormatBGRA` for cameraCapture, camera supported only `QBRTCPixelFormat420f` and `QBRTCPixelFormat420v` 

Use QBRTCPixelFormatBGRA for custom implementation `QBRTCVideoCapture` for example see [screen sharing] (https://github.com/QuickBlox/quickblox-ios-sdk/blob/master/sample-videochat-webrtc/sample-videochat-webrtc/ViewControllers/SharingViewController/QBRTCScreenCapture.m)

**Comment by Pro100Andrey** [comment]
@brtcck  If you haven't additional questions, please close the issue, thanks

**Comment by Pro100Andrey** [comment]
@brtcck Any updates?

**Comment by brtcck** [comment]
@Pro100Andrey Thanx.
