### ISSUE TITLE
Push notification on 2 iOS apps(different bundle identifiers) using 1 Quickblox app.

### ISSUE THREAD

**Issue by icarasiaofficial** [QuickBlox/quickblox-ios-sdk#655]
**Environment details**
iOS version All, Quickblox iOS SDK version All

**Did this work before?**
No

**Expected behavior**
Should be able to add 2 iOS apps (different bundle identifiers) on quick blox app i.e. Push Notifications-> settings page -> APNS.  So that both apps can receive push notifications between them.

**Actual behavior**
Right now on Push Notifications-> settings page -> APNS, you can add only one iOS app. Consequently if one quickblox app is used on 2 iOS apps (different bundle identifiers), only one will receive the push notification. i.e. push notifications on only the iOS app whose certificate is being  uploaded.

**Steps to reproduce the behavior**
1. Create an app on quickblox
2. Try to add 2 APNS certificates on Push Notifications-> settings page -> APNS
3. The second certificate replaces the first one when uploaded.

**Any others comments?**
Every other competitor product allows to add more than 1 iOS APNS certificates on the portal.

**Comment by soulfly** [comment]
This feature is in our roadmap now, better to say it's already in progress. 
Please follow our blog to receive more updates when it will be available
quickblox.com/blog
