### ISSUE TITLE
Quickblox 2.9 causes "Quickblox/Quickblox.h file not found "

### ISSUE THREAD

**Issue by xpressmobtech** [QuickBlox/quickblox-ios-sdk#659]
upon updating Quickblox from 2.8.0.1 to 2.9 i now receive the error "Quickblox/Quickblox.h file not found ", when i downgrade back to 2.8.0.1 it works fine.

**Comment by xpressmobtech** [comment]
@Pro100Andrey @Raikerian @VitaliyGuru

**Comment by VitaliyGuru** [comment]
@xpressmobtech  Hello, how did you add quickblox? via pods or manually?

**Comment by AleksandrKh** [comment]
same via pods

**Comment by VitaliyGuru** [comment]
@xpressmobtech , @AleksandrKh  let me check

**Comment by VitaliyGuru** [comment]
[testSample.zip](https://github.com/QuickBlox/quickblox-ios-sdk/files/594638/testSample.zip)
@xpressmobtech , @AleksandrKh 
I have created a test project and everything works as expected.

Try to remove all pods and add them again.

**Comment by AleksandrKh** [comment]
I've removed pods cache and reinstalled all pods but there is still no headers in Quickblox folder
<img width="312" alt="shot" src="https://cloud.githubusercontent.com/assets/2961856/20348022/6fc9aa8a-ac25-11e6-8f19-b957bba78945.png">

**Comment by xpressmobtech** [comment]
I installed via pods...I've uninstalled and re-installed with no luck... still says file not found...can you please answer this question aswell https://github.com/QuickBlox/quickblox-ios-sdk/issues/657

**Comment by VitaliyGuru** [comment]
@AleksandrKh , @xpressmobtech  Confirmed. Will be fixed ASAP.

**Comment by VitaliyGuru** [comment]
@AleksandrKh , @xpressmobtech fixed. Try now.

**Comment by xpressmobtech** [comment]
@VitaliyGuru any information about this issue -- https://github.com/QuickBlox/quickblox-ios-sdk/issues/657

**Comment by AleksandrKh** [comment]
it's ok now

**Comment by Pro100Andrey** [comment]
@AleksandrKh Thanks !

**Comment by xpressmobtech** [comment]
@Pro100Andrey @VitaliyGuru still no header files

**Comment by Raikerian** [comment]
@xpressmobtech remove Podfile.lock file, Pods folder and .xcworkspace file.
Clear cache of pods:
```
rm -rf "${HOME}/Library/Caches/CocoaPods"
rm -rf "`pwd`/Pods/"
```

And now perform pod install.

**Comment by xpressmobtech** [comment]
@Raikerian it worked thanks!
