### ISSUE TITLE
How can I send a push notification to multiple tags from the Quickblox admin dashboard?

### ISSUE THREAD

**Issue by mitchellporter** [QuickBlox/quickblox-ios-sdk#66]
On the Messages page, under the "Subscribers" section, you can enter in tags to include.

There is also a button to choose between "Any tags" or "All tags". I want to send this push notification to any users that have at least one of three different tags, so I choose "Any tags".

My question is, how do I correctly type in multiple tags in to the field. Do I just separate them by commas like this?

`group1,group2,group3`

Thanks for the help!

**Comment by soulfly** [comment]
yes, this should work like that http://qblx.co/1DS79mb

**Comment by mitchellporter** [comment]
Thanks @soulfly I should have tested entering multiple ones before assuming I needed commas.
