### ISSUE TITLE
UserData is Stored always 

### ISSUE THREAD

**Issue by ErAshu** [QuickBlox/quickblox-ios-sdk#661]
I have install videochat-webRTC and login with a user. It is storing values in keychain. I want to login with another user after uninstalling the app but it always login with old data.

It should be clear userdata after uninstalling the app or install first time.

**Core.currentUser is showing data always**
Kindly fix this. 

Thanks in Advance.

**Comment by VitaliyGuru** [comment]
@ErAshu , Hello
You should perform logout if you want to login with another user

**Comment by Pro100Andrey** [comment]
@ErAshu Any updates?

**Comment by VitaliyGuru** [comment]
@ErAshu If you have any additional questions feel free to ask. Closed for now.
