### ISSUE TITLE
How to update the user block status in the privacy list.

### ISSUE THREAD

**Issue by ajay2c9** [QuickBlox/quickblox-ios-sdk#662]
Hi,
I am using Quickblox in my app. I am implementing the block status of the user. I blocked the users by using below.
//
        QBPrivacyItem *item = [[QBPrivacyItem alloc]initWithPrivacyType:QBPrivacyTypeUserID userID:user.ID allow:NO];
        QBPrivacyList *list = [[QBPrivacyList alloc] initWithName:@"Block" items:@[item]];
       [[QBChat instance] setPrivacyList:list];
//
For multiple users i make an array with QBPrivacyItems and added to QBPrivacyList.
How to update the status of one user in the privacy list.

**Comment by Raikerian** [comment]
Hi,

Not sure what is a question here. If you want to unblock the user simply create an item with allow:YES and replace the old one in privacy list by user ID.

**Comment by ajay2c9** [comment]
Thank you for reply .

**Comment by ajay2c9** [comment]
Its working fine

**Comment by swetaagicent** [comment]
how to block /unblock multiple users,

**Comment by ajay2c9** [comment]
Hi swetaagicent,
 you have to create multiple privacy items like below.
For Block allow=NO; For UnBlock: allow=YES

QBPrivacyItem *item = [[QBPrivacyItem alloc]initWithPrivacyType:QBPrivacyTypeUserID userID:user.ID allow:NO];

QBPrivacyItem *item1 = [[QBPrivacyItem alloc]initWithPrivacyType:QBPrivacyTypeUserID userID:user1.ID allow:YES];
Add items to privacy list with name.

QBPrivacyList *list = [[QBPrivacyList alloc] initWithName:@"Block" items:@[item,item1]];
[[QBChat instance] setPrivacyList:list];
