### ISSUE TITLE
[[QBChat instance] removePrivacyListWithName:@"public"]; is not working

### ISSUE THREAD

**Issue by ajay2c9** [QuickBlox/quickblox-ios-sdk#663]
[[QBChat instance] removePrivacyListWithName:@"public"];

while using above the privacy items in the privacy list is not removing. and Shows the error in the delegate method     "chatDidNotSetPrivacyListWithName"   like below

the error is <iq xmlns="jabber:client" type="error" id="864C9BBD-E771-4D55-AC60-F32264D0445E" to="20428496-49587@chat.quickblox.com/FA2C8A4C-FF11-4B45-BF8D-079CB24B3CBC"><query xmlns="jabber:iq:privacy"><list name="public"/></query><error type="cancel" code="409"><conflict xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/><text xmlns="urn:ietf:params:xml:ns:xmpp-stanzas" lang="en">Can not modify list while being in use by other session</text></error></iq>

Please give suggestions
Thank you

**Comment by VitaliyGuru** [comment]
You couldn't remove privacy list which is set as default or active.
You should use another privacy list as active/default and then you will be able to remove this one.

**Comment by ajay2c9** [comment]
Thank you for reply its working.
