### ISSUE TITLE
QBRTCClient delegates not being removed!

### ISSUE THREAD

**Issue by xpressmobtech** [QuickBlox/quickblox-ios-sdk#664]
**Environment details**
*iOS version, Quickblox iOS SDK version, QuickbloxWebRTC SDK version (optional)*
iOS version - 10.1.1, Quickblox 2.9, QBWebrtc 2.2

**Did this work before?**
No

**Expected behavior**
Delegates should be removed from list when QBRTCClient.instance().removeDelegates is called.

**Actual behavior**
It says removed, however number of delegates does not change.

**Logs**

@VitaliyGuru @Pro100Andrey 
logs:

viewDidLoad -- QBRTCClient.instance().addDelegate(self)
rtc::<QBRTCClient 0x175cb900, delegates[1]> added <self.VideoChatViewController: 0x1777a7b0> to list of delegates_

It says it added one viewcontroller "0x1777a7b0" to delegates list.

viewDidDisappear -- QBRTCClient.instance().removeDelegate(self)
2016-11-17 08:05:45:298 self[1911:1180061] rtc::<QBRTCClient 0x175cb900, delegates[1]> removed <self.VideoChatViewController: 0x1777a7b0> from list of delegates

Notice it says it removed the viewcontroller "0x1777a7b0" from list of delegates, however as you can see there is still one delegate in the list, when there should be 0, which means it never removed anything, now if I instantiate the very same view once again, it adds another delegate to the list

rtc::<QBRTCClient 0x175cb900, delegates[2]> added <self.VideoChatViewController: 0x176b1320> to list of delegates

Trying to remove delegate when viewDidDisappear.

rtc::<QBRTCClient 0x175cb900, delegates[2]> removed <self.VideoChatViewController: 0x176b1320> from list of delegates

it still has both the original delegate "0x1777a7b0" and the 2nd delegate added "0x176b1320", QBRTCClient.instance().addDelegate(self) adds delegates to QBRTCClient delegates list fine, but QBRTCClient.instance().removeDelegate(self) does not actually remove anything from the delegates list, causing there to be a delegate added for every page transition(which could in the 100s) , also all rtc methods are fired one time for every one delegate...which is a huge issue.

ANY SOLUTIONS ON HOW TO REMOVE THE DELEGATES FROM THE LIST SO THAT THE LIST IS AT ZERO?

**Steps to reproduce the behavior**
Instantiate viewcontroller1 and in viewcontroller1's viewsidload call QBRTCClient.instance().addDelegate(self), 1 delegate should be added, now call QBRTCClient.instance().removeDelegate(self) in viewcontroller1's viewdiddisappear but if you dismiss the viewcontroller no delegate is removed.

**Comment by Pro100Andrey** [comment]
Hi @xpressmobtech, please check:

    ```objc
    QBMulticastDelegate *observer = [[QBRTCClient instance] valueForKey:@"observer"];
    NSLog(@"before remove - %@", observer.delegates);
    [observer removeDelegate:self];
    NSLog(@"after remove %@", observer.delegates);
```

**Comment by Pro100Andrey** [comment]
@xpressmobtech Any updates?
