### ISSUE TITLE
How to hang up a user from a conference call?

### ISSUE THREAD

**Issue by heavyBug** [QuickBlox/quickblox-ios-sdk#665]
I have seen a function in Android SDK
public void procHangUpOpponent(Integer opponentID,
Map<String,String> userInfo)
Close channel with concrete opponent
Parameters:
opponentID -

But there is no any method in ios SDK which can be called to hang up a specific user.

Any help will be appreciated

**Comment by Pro100Andrey** [comment]
Hi @heavyBug, [Use this method of delegate](https://github.com/QuickBlox/quickblox-ios-sdk/blob/master/Framework/QuickbloxWebRTC.framework/Versions/A/Headers/QBRTCClientDelegate.h#L82)

**Comment by heavyBug** [comment]
But there is no any specific method to hung up a single user ... If I use
the hung up method of QBRTCSession class it closes the whole session and
hence the whole call

**Comment by heavyBug** [comment]
HungUpByUser called when the receiver hung up the call himself... i want to hung up the call from the caller side

**Comment by Pro100Andrey** [comment]
@heavyBug use:
Side A:
```objc
    QBChatMessage *hangUpMsg  = [QBChatMessage message];
    hangUpMsg.recipientID = //recipient id;
    hangUpMsg.customParameters[@"custom_signal"] = @"hangup";
    [[QBChat instance] sendSystemMessage:hangUpMsg completion:^(NSError * _Nullable error) {
     
    }];
```
Side B:
see QBChatDelegate.h
```objc
- (void)chatDidReceiveSystemMessage:(QBChatMessage *)message {
    if ([message.customParameters[@"custom_signal"] isEqualToString:@"hangup"] ) {
        [self.session hangUp:nil];
    }
}
```

**Comment by Pro100Andrey** [comment]
@heavyBug updated

**Comment by heavyBug** [comment]
chatDidReceiveSystemMessage is not being called... message sent successfully from Side A

**Comment by Pro100Andrey** [comment]
@heavyBug  use `[[QBChat instance] addDelegate:self]`

For example:

yourfile.mm

```objc
- (void)viewDidLoad {
    ...
    [[QBChat instance] addDelegate:self]
    ...
}
```

```objc
- (void)chatDidReceiveSystemMessage:(QBChatMessage *)message {
    
    if ([message.customParameters[@"custom_signal"] isEqualToString:@"hangup"] ) {
        NSString *sessionID = message.customParameters[@"conference_id"];
        if ([self.session.ID isEqualToString:sessionID]) {
            [self.session hangUp:nil];
        }
    }
}
```

**Comment by heavyBug** [comment]
Thanks a lot buddy you saved my life... it really works like a magic trick
@Pro100Andrey  man of the day... :)
