### ISSUE TITLE
"Forbidden. Need user." error 

### ISSUE THREAD

**Issue by vikrant88** [QuickBlox/quickblox-ios-sdk#668]
I am working on Quickblox 2.6 in iOS with Objective-C. I am getting Token with Api.
https://api.quickblox.com/session.json. 
Token which I am getting from response, using in 
`  NSMutableURLRequest *request = [NSMutableURLRequest requestWithURL:[NSURL URLWithString:@"https://api.quickblox.com/chat/Dialog.json?type=2&sort_desc=last_message_date_sent"] cachePolicy:NSURLRequestUseProtocolCachePolicy timeoutInterval:30];
    [request setHTTPMethod:@"GET"];
    [request setValue:@"application/json" forHTTPHeaderField:@"Content-Type"];
    [request setValue:token forHTTPHeaderField:@"QB-Token"];
    [[UIApplication sharedApplication] setNetworkActivityIndicatorVisible:YES];`
But I am getting response error
`{
    errors =     {
        base =         (
            "Forbidden. Need user."
        );
    };
}` so please tell me my token is not correct or there is anything I am missing.
Thanks

**Comment by Pro100Andrey** [comment]
Hi @viktant88 , need login with user before retrieving gialogs

**Comment by Raikerian** [comment]
@vikrant88 any reason for not using our iOS SDK?

**Comment by vikrant88** [comment]
I have old project in which APIs used already.  But I am also using SDK

**Comment by vikrant88** [comment]
@Pro100Andrey  I am login already with following code. After that I call dialog APIs

`QBUUser *user = [QBUUser new];
    user.login = self.user.chat.login;
    user.password = kAPP_PASSWORD;
    
    NSString* password = user.password;
    
    //[QBRequest signUp:user successBlock:^(QBResponse *response, QBUUser *user) {
        
        [QBRequest logInWithUserLogin:user.login password:password successBlock:^(QBResponse *response, QBUUser *user)
         {
         }errorBlock:^(QBResponse *response) {
            
            NSLog(@"Errors=%@", [response.error description]);
            
            
        }];`

**Comment by Pro100Andrey** [comment]
@vikrant88 Please check QBToken after logInWithUserLogin (response logs) and after retrieve dialogs

**Comment by vikrant88** [comment]
can I get QBToken  loginWithUserLogin(response logs). If yes then I think no need to use
https://api.quickblox.com/session.json.

**Comment by Raikerian** [comment]
Our latest SDK managing session automatically. All you need to do is login with one of the login methods in QBRequest. Basically we are checking session and updating it if needed for every request.

**Comment by vikrant88** [comment]
@Raikerian  thanks for guide me. But I have project having many APIs so if I change the all APIs then its take time. Thats why I don't want to change.

**Comment by Raikerian** [comment]
What do you mean by don't want to change?
You said previously:

> I have old project in which APIs used already. But I am also using SDK
what version of SDK are you using? You can check it in `Quickblox.h` file.

**Comment by vikrant88** [comment]
when I got the old code QB-version was 2.2 but now I used pod 'QuickBlox' and get QuickBlox 2.6

**Comment by Raikerian** [comment]
So, you are using 2.6 or 2.2 currently?

**Comment by vikrant88** [comment]
so please tell me token getting from https://api.quickblox.com/session.json Api. Can I use as QB-Token in following code
`NSMutableURLRequest *request = [NSMutableURLRequest requestWithURL:[NSURL URLWithString:@"https://api.quickblox.com/chat/Dialog.json?type=2&sort_desc=last_message_date_sent"] cachePolicy:NSURLRequestUseProtocolCachePolicy timeoutInterval:30]; [request setHTTPMethod:@"GET"]; [request setValue:@"application/json" forHTTPHeaderField:@"Content-Type"]; [request setValue:token forHTTPHeaderField:@"QB-Token"]; [[UIApplication sharedApplication] setNetworkActivityIndicatorVisible:YES];`

**Comment by vikrant88** [comment]
Now I am using 2.6

**Comment by Raikerian** [comment]
2.6 version does have automatic session management.
I also would like to point that our old SDK's does not support IPv6 which is required for app store right now. We added this support in 2.7.5.

**Comment by vikrant88** [comment]
So please tell me what is the solution of my issue?. I got stuck on this.

**Comment by vikrant88** [comment]
I updated my QuickBlox version. Now it is "QB-SDK" = "iOS 2.7.6"

**Comment by VitaliyGuru** [comment]
@vikrant88 Now, with this version of SDK there is no need to manage session manually. 
All you need is to perform login with the user.

**Comment by vikrant88** [comment]
@Raikerian  @Pro100Andrey  @VitaliyGuru even after I am not able to get dialogs.Now I am also getting same error 

`{ errors = { base = ( "Forbidden. Need user." ); }; }`

**Comment by Raikerian** [comment]
Please use one of login methods before doing any other requests: http://quickblox.com/developers/SimpleSample-users-ios#Signing_In_.26_Social_authorization

**Comment by AleksandrKh** [comment]
I'm getting exactly the same error "Forbidden. Need user." after app idle in background, for any request. So I have to login every time after idle now.

**Comment by vikrant88** [comment]
@Raikerian I used `- (void)login
{
    // Authenticate user
    [QBRequest logInWithUserLogin:@"login" password:@"password"
                     successBlock:[self successBlock] errorBlock:[self errorBlock]];
}` and in success block I call dialog.josn API but same error occur still

**Comment by vikrant88** [comment]
Hello everyone, may I expect some other way to solve this issue ?
Thanks.

**Comment by AleksandrKh** [comment]
any comments for this issue in the last version?

**Comment by vikrant88** [comment]
Hello everyone, Today I updated Quickblox SDK. Now version is updated 2.9. But now also I am having same issue `{"errors":{"base":["Forbidden. Need user."]}` 
How I can solve this issue.

**Comment by Raikerian** [comment]
@AleksandrKh do you have shared keychain enable in your projects capabilities (iOS 10 required as we are storing our session in keychain)?

@vikrant88 so, have you performed login request before doing any other request?

**Comment by vikrant88** [comment]
@Raikerian Yes, I performed login request and in login success block I called GET Dialog Api. 
@Raikerian  Firstly please guide me   https://api.quickblox.com/session.json Api is correct Api to get the QB-TOKEN.

**Comment by Raikerian** [comment]
It is correct api but I still don't understand what is a point of using direct api calls when you have already installed our SDK which is managing this things automatically.

Also please provide full logs from app start till the error occures.

**Comment by vikrant88** [comment]
I am using  https://api.quickblox.com/session.json APi to get Token and this token I am using to get response from API. I am posting the API code to Get Dialogs in which I am using QB-Token. `    NSMutableURLRequest *request = [NSMutableURLRequest requestWithURL:[NSURL URLWithString:@"https://api.quickblox.com/chat/Dialog.json?type=2&sort_desc=last_message_date_sent"] cachePolicy:NSURLRequestUseProtocolCachePolicy timeoutInterval:30];
    [request setHTTPMethod:@"GET"];
    [request setValue:@"application/json" forHTTPHeaderField:@"Content-Type"];
    [request setValue:token forHTTPHeaderField:@"QB-Token"];
    
    
    // Create url connection and fire request
    [[UIApplication sharedApplication] setNetworkActivityIndicatorVisible:YES];
    [NSURLConnection sendAsynchronousRequest:request
                                       queue:[NSOperationQueue mainQueue]
                           completionHandler:^(NSURLResponse *response, NSData *data, NSError *error) {
                               
                               [[UIApplication sharedApplication] setNetworkActivityIndicatorVisible:NO];
                               
                               if (!error)
                               {
                                   // Call api again here..
                                   success(data);
                                   
                               }
                               else
                               {
                                   NSLog(@"respones is....   %@",[[NSString alloc] initWithData:data encoding:NSUTF8StringEncoding]);
                                   failure(error);
                               }
                           }];
    `In token parameter sending value getting from session API.

**Comment by vikrant88** [comment]
My complete code is `

    QBUUser *user = [LocalStorageService shared].currentUser;

    [QBRequest logInWithUserLogin:user.login password:user.password successBlock:^(QBResponse *response, QBUUser *user) {





   NSMutableURLRequest *request = [NSMutableURLRequest requestWithURL:[NSURL URLWithString:@"https://api.quickblox.com/chat/Dialog.json?type=2&sort_desc=last_message_date_sent"] cachePolicy:NSURLRequestUseProtocolCachePolicy timeoutInterval:30];
    [request setHTTPMethod:@"GET"];
    [request setValue:@"application/json" forHTTPHeaderField:@"Content-Type"];
    [request setValue:token forHTTPHeaderField:@"QB-Token"];
    
    
    // Create url connection and fire request
    [[UIApplication sharedApplication] setNetworkActivityIndicatorVisible:YES];
    [NSURLConnection sendAsynchronousRequest:request
                                       queue:[NSOperationQueue mainQueue]
                           completionHandler:^(NSURLResponse *response, NSData *data, NSError *error) {
                               
                               [[UIApplication sharedApplication] setNetworkActivityIndicatorVisible:NO];
                               
                               if (!error)
                               {
                                   // Call api again here..
                                   NSLog(@"respones is....   %@",[[NSString alloc] initWithData:data encoding:NSUTF8StringEncoding]);
                                   success(data);
                                   
                               }
                               else
                               {
                                   NSLog(@"respones is....   %@",[[NSString alloc] initWithData:data encoding:NSUTF8StringEncoding]);
                                   failure(error);
                               }
                           }];






    } errorBlock:^(QBResponse *response) {
        
        NSLog(@"Errors=%@", [response.error description]);
        
        
    }];
` Now what I am missing

**Comment by AleksandrKh** [comment]
> @AleksandrKh do you have keychain sharing enable in your projects capabilities (iOS 10 required as we are storing our session in keychain)?

@Raikerian Yes, it's enabled.

**Comment by Raikerian** [comment]
@vikrant88 `[QBRequest logInWithUserLogin:user.login password:user.password successBlock:^(QBResponse *response, QBUUser *user) {` automatically creating session. You don't need to create an API call. If you want to get session token just call `[QBSession currentSession].sessionToken` after login and thats it.

@AleksandrKh create a separate issue with full logs, from app start till the error occurs. Your issue is not the same even though it might sound like it.

**Comment by Raikerian** [comment]
@vikrant88 were you able to integrate SDK methods instead of URL requests on your own?

**Comment by vikrant88** [comment]
@Raikerian  I used `[QBSession currentSession].sessionDetails.token` and get token and api running.

**Comment by Raikerian** [comment]
Is this solved now? Close if it is please.

**Comment by vikrant88** [comment]
Yes issue is solved and thanks everyone to help me

**Comment by hiteshwork** [comment]
Is it required to LOGIN to quickblox EVERYTIME app is launched?
When i login for the first time , connect to chat and get dialogs of user it gets fetched successfully.
However after logging in once if i close the app. Open again (user is already logged in) , connect to chat (successfully) and try to retreive dialog list i get the error "Forbidden. Need User".
Here is the code ->
QBRequest.dialogs(for: page, extendedRequest: extendedRequest, successBlock: { (response: QBResponse, dialogs: [QBChatDialog]?, dialogsUsersIDs: Set<NSNumber>?, page: QBResponsePage?) -> Void in
            if (dialogs?.count)! > 0 {
                self.usersQBDialogID = (((dialogs as AnyObject).value(forKey: "ID") as! NSArray)[0] as? String)!
                self.getDialogMessages(self.usersQBDialogID)
            } else {
                self.createChatDialog()
            }
        }) { (response: QBResponse) -> Void in
            print(response)
        }

in the logs i notice the "user_id" = 0;
And the log is -> 
[QBCore] Request URL:https://api.quickblox.com/session.json
2017-09-19 11:43:47.657 xxxxx[2270:130992] [QBCore] Request method: POST
2017-09-19 11:43:47.658 xxxxxx[2270:130992] [QBCore] Request parameters:{
    "application_id" = xxxxx;
    "auth_key" = xxxxxxxxx;
    nonce = xx;
    signature = xxxxxxxxxx8fcfxxxxxxxxxd;
    timestamp = 1505801627;
}
2017-09-19 11:43:47.658 xxxxxx[2270:130992] [QBCore] Request headers: {
    "Accept-Language" = "en;q=1";
    "Content-Type" = "application/x-www-form-urlencoded";
    "QB-OS" = "iOS 10.2";
    "QB-SDK" = "iOS 2.9.2";
    "QuickBlox-REST-API-Version" = "0.1.1";
    "User-Agent" = "xxxxxxxx/1.0 (iPhone; iOS 10.2; Scale/3.00)";
}
2017-09-19 11:43:48.978 xxxxxx[2270:130992] [QBCore] Response headers: {
    "Access-Control-Allow-Origin" = "*";
    "Cache-Control" = "max-age=0, private, must-revalidate";
    Connection = "keep-alive";
    "Content-Length" = 232;
    "Content-Type" = "application/json; charset=utf-8";
    Date = "Tue, 19 Sep 2017 06:13:48 GMT";
    Etag = "W/\"c707d9134b2ff8fc5becde90f48bf88f\"";
    "QB-Token-ExpirationDate" = "2017-09-19 08:13:48 UTC";
    "QuickBlox-REST-API-Version" = "0.1.1";
    Server = "openresty/1.9.15.1";
    "Set-Cookie" = "_mkra_ctxt=46d623b0a811f9a8593082516786c4b9--201; path=/; max-age=5; HttpOnly; secure";
    Status = "201 Created";
    "Strict-Transport-Security" = "max-age=31536000, max-age=15768000;";
    "X-Content-Type-Options" = nosniff;
    "X-Frame-Options" = SAMEORIGIN;
    "X-Request-Id" = "364da9a8-4acb-4165-842a-200aa46939f8";
    "X-Runtime" = "0.023535";
    "X-XSS-Protection" = "1; mode=block";
}
2017-09-19 11:43:48.980 xxxxxx[2270:130992] [QBCore] Response object: {
    session =     {
        "_id" =xxxxxxxx;
        "application_id" = xxxxx
        "created_at" = "2017-09-19T06:13:48Z";
        id = xxxxxx;
        nonce = xxxx;
        token = xxxxxxxxxxxxxxabc200xxxx37;
        ts = xxxxx;
        "updated_at" = "2017-09-19T06:13:48Z";
        "user_id" = 0;
    };
}
2017-09-19 11:43:48.985 xxxxxxx[2270:130992] [QBCore] Request URL:https://api.quickblox.com/chat/Dialog.json?limit=100&sort_desc=_id
2017-09-19 11:43:48.985xxxxxx[2270:130992] [QBCore] Request method: GET
2017-09-19 11:43:48.986 xxxxxxr[2270:130992] [QBCore] Request parameters:{
    limit = 100;
    "sort_desc" = "_id";
}
2017-09-19 11:43:48.986 CobraSportUser[2270:130992] [QBCore] Request headers: {
    "Accept-Language" = "en;q=1";
    "QB-OS" = "iOS 10.2";
    "QB-SDK" = "iOS 2.9.2";
    "QB-Token" = 65e151ea9ea6e0ff450332f378d8c1abc200f137;
    "QuickBlox-REST-API-Version" = "0.1.1";
    "User-Agent" = "xxxxxxxx/1.0 (iPhone; iOS 10.2; Scale/3.00)";
}
2017-09-19 11:43:50.279 xxxxxxxr[2270:130992] [QBCore] Response error: Error Domain=com.alamofire.error.serialization.response Code=-1011 "Request failed: client error (422)" UserInfo={com.alamofire.serialization.response.error.response=<NSHTTPURLResponse: 0x608000230c00> { URL: https://api.quickblox.com/chat/Dialog.json?limit=100&sort_desc=_id } { status code: 422, headers {
    "Access-Control-Allow-Origin" = "*";
    "Cache-Control" = "no-cache";
    Connection = "keep-alive";
    "Content-Length" = 45;
    "Content-Type" = "application/json; charset=utf-8";
    Date = "Tue, 19 Sep 2017 06:13:50 GMT";
    "QB-Token-ExpirationDate" = "2017-09-19 08:13:48 +0000";
    "QuickBlox-REST-API-Version" = "0.1.1";
    Server = "openresty/1.9.15.1";
    "Set-Cookie" = "_mkra_ctxt=3ccde0f95c320ac6ed14cda1868f2a84--422; path=/; max-age=5; HttpOnly; secure";
    Status = "422 Unprocessable Entity";
    "Strict-Transport-Security" = "max-age=31536000";
    "X-Content-Type-Options" = nosniff;
    "X-Frame-Options" = SAMEORIGIN;
    "X-Request-Id" = "42cf0aae-cd8f-43b1-8dd3-f7aa1160accb";
    "X-Runtime" = "0.008738";
    "X-XSS-Protection" = "1; mode=block";
} }, NSErrorFailingURLKey=https://api.quickblox.com/chat/Dialog.json?limit=100&sort_desc=_id, com.alamofire.serialization.response.error.data=<7b226572 726f7273 223a7b22 62617365 223a5b22 466f7262 69646465 6e2e204e 65656420 75736572 2e225d7d 7d>, NSLocalizedDescription=Request failed: client error (422)}
[QBResponse], status: 422
2017-09-19 11:43:50.280 xxxxxxr[2270:130992] [QBCore] Response error reasons: {
    errors =     {
        base =         (
            "Forbidden. Need user."
        );
    };
}
