### ISSUE TITLE
Did disconnect with error: Error Domain=kCFStreamErrorDomainSSL Code=-9806

### ISSUE THREAD

**Issue by kittu4ios** [QuickBlox/quickblox-ios-sdk#669]
Did disconnect with error: Error Domain=kCFStreamErrorDomainSSL Code=-9806 "(null)" UserInfo={NSLocalizedRecoverySuggestion=Error code definition can be found in Apple's SecureTransport.h}

**Comment by VitaliyGuru** [comment]
@kittu4ios, Could you please specify iOS version, Quickblox iOS SDK version ?

**Comment by kittu4ios** [comment]
I am working on iPhone 6, IOS 9

**Comment by VitaliyGuru** [comment]
@kittu4ios  Look's like it's the [same issue](https://github.com/QuickBlox/quickblox-ios-sdk/issues/667)

**Comment by VitaliyGuru** [comment]
@kittu4ios  BTW , I've asked for Quickblox iOS SDK version not iOS version.

**Comment by Raikerian** [comment]
@kittu4ios please check this issue now. Our server did have some problems last week, should be fixed now.

**Comment by kittu4ios** [comment]
its fixed. Thanks now working fine.

**Comment by wanglouin1990925** [comment]
Hi I am getting this issue again.
It was worked before but app is started to getting this issue suddenly.
I am using quickblox sdk 2.10. its happening to me always.

Disconnected with error: Error Domain=kCFStreamErrorDomainSSL Code=-9806 "(null)" UserInfo={NSLocalizedRecoverySuggestion=Error code definition can be found in Apple's SecureTransport.h}

Can you please help me to solve this issue asap?
