### ISSUE TITLE
New Chat dialog creating causing issue.

### ISSUE THREAD

**Issue by ajay2c9** [QuickBlox/quickblox-ios-sdk#671]
Hi,
 While Creating the New chat dialog, it is not created. Spinner is rotated continuously. It is happening in Chat Sample too. Below is my log.

2016-11-25 15:40:35.562 ChatSample[10197:140441] [QBCore] Request URL:https://api.quickblox.com/chat/Dialog.json
2016-11-25 15:40:35.563 ChatSample[10197:140441] [QBCore] Request method: POST
2016-11-25 15:40:35.565 ChatSample[10197:140441] [QBCore] Request parameters:{
    name = FireWork;
    "occupants_ids" = "20428362,20610652,20762104,20428187,20759929,20763594";
    type = 2;
}
2016-11-25 15:40:35.569 ChatSample[10197:140441] [QBCore] Request headers: {
    "Accept-Language" = "en-US;q=1";
    "Content-Type" = "application/x-www-form-urlencoded";
    "QB-OS" = "iOS 9.3";
    "QB-SDK" = "iOS 2.9";
    "QB-Token" = de04ea63f6151dd8298a6bbfad0ed551c000c1b3;
    "QuickBlox-REST-API-Version" = "0.1.1";
    "User-Agent" = "ChatSample/1.0 (iPhone; iOS 9.3; Scale/2.00)";
}
2016-11-25 15:40:36.237 ChatSample[10197:140481] [QBCore] Response headers: {
    "Access-Control-Allow-Origin" = "*";
    "Cache-Control" = "max-age=0, private, must-revalidate";
    Connection = "keep-alive";
    "Content-Length" = 425;
    "Content-Type" = "application/json; charset=utf-8";
    Date = "Fri, 25 Nov 2016 10:10:35 GMT";
    Etag = "\"13ba008190b60a38e8ff2d8572a0c38c\"";
    "QB-Token-ExpirationDate" = "2016-11-25 12:10:05 UTC";
    "QuickBlox-REST-API-Version" = "0.1.1";
    Server = "openresty/1.9.15.1";
    Status = "201 Created";
    "Strict-Transport-Security" = "max-age=15768000;";
    "X-Rack-Cache" = "invalidate, pass";
    "X-Request-Id" = 2bd7254fef09be846f19ac3d532be5c7;
    "X-Runtime" = "0.208856";
    "X-UA-Compatible" = "IE=Edge,chrome=1";
}
2016-11-25 15:40:36.239 ChatSample[10197:140481] [QBCore] Response object: {
    "_id" = 58380e1ba28f9a78a9000003;
    "created_at" = "2016-11-25T10:10:35Z";
    "last_message" = "<null>";
    "last_message_date_sent" = "<null>";
    "last_message_user_id" = "<null>";
    name = FireWork;
    "occupants_ids" =     (
        20428187,
        20428362,
        20428496,
        20610652,
        20759929,
        20762104,
        20763594
    );
    photo = "<null>";
    type = 2;
    "unread_messages_count" = "<null>";
    "updated_at" = "2016-11-25T10:10:35Z";
    "user_id" = 20428496;
    "xmpp_room_jid" = "49587_58380e1ba28f9a78a9000003@muc.chat.quickblox.com";
}

**Comment by VitaliyGuru** [comment]
@ajay2c9  Let me check

**Comment by VitaliyGuru** [comment]
BTW: dialog created successfully. You received response with created dialog.

**Comment by ajay2c9** [comment]
Hi,
Yesterday it is not worked. while creating the dialog the spinner rotates continuously and dialog is not created. after removing the instance dialog is displayed, but messages not sent. I created few dialogs like this. Same process is happened. Now both dialog is created and messages are sent.
