### ISSUE TITLE
didAddMessageToMemoryStorage not called, UICollectionView not showing recent messages after "Send" action

### ISSUE THREAD

**Issue by sushmithaGope** [QuickBlox/quickblox-ios-sdk#672]
When I click on send button messages are being shown, but **few times** I cannot see messages updated. I have set breakpoint didAddMessageToMemoryStorage method is not being called.
Please suggest me to do any changes for the function to get called.

**Comment by VitaliyGuru** [comment]
@sushmithaGope What is your QB IOS SDK version, QMServices version?

**Comment by sushmithaGope** [comment]
QMServices (0.4.5)
QuickBlox (2.9)
I'm using swift
Yes i have tried to test in your sample I'm getting error message sending failed. Previously it has worked in your sample but now I'm getting error.

**Comment by VitaliyGuru** [comment]
@sushmithaGope Which exactly error did you get? 
Could you please enable full logs and send us this information?

```
[QBSettings setLogLevel:QBLogLevelDebug];
[QBSettings enableXMPPLogging];
```

**Comment by sushmithaGope** [comment]
I'm not getting any error, but i can able to see
[QMChatCache] Messages to insert 1, update 0
[QMChatCache] Dialogs to insert 0, update 1

It is not happening now. But I'm sure this function is not getting called sometimes.

**Comment by sushmithaGope** [comment]
I can able to solve this using QMDeferredQueueManager delegate methods. Please close this issue. Thanks
