### ISSUE TITLE
[QBChatDialog sendStopTypingInGroup] -> Error Domain=com.quickblox.chat Code=-1001 "(null)" UserInfo={NSLocalizedRecoverySuggestion=You are not joined to the dialog.

### ISSUE THREAD

**Issue by rahulkakadiya** [QuickBlox/quickblox-ios-sdk#673]
*Help avoid duplicate issue reports, check [existing issues](https://github.com/QuickBlox/quickblox-ios-sdk/issues)*
 
**Environment details**
*iOS version, Quickblox iOS SDK version, QuickbloxWebRTC SDK version (optional)*

**Did this work before?**

**Expected behavior**

**Actual behavior**

**Logs**
*Attach full logs that will describe your problem (please, use github [gist](https://gist.github.com/))*

**Steps to reproduce the behavior**

**Any others comments?**

**Comment by Raikerian** [comment]
Hi,

Please check this issue. Our server did have some troubles last week, should be fixed now.

**Comment by Raikerian** [comment]
Let us know if you are still experiencing this. Although it should be fixed by now.
