### ISSUE TITLE
opponent side receiving userInfo with other type field values

### ISSUE THREAD

**Issue by Shamsiddin** [QuickBlox/quickblox-ios-sdk#674]
**Environment details**
_First Device:_
iOS version: 10.0.2

_Second Device:_
iOS version: 9.3.2

Quickblox iOS SDK version: 2.7.6
QuickbloxWebRTC SDK version: 2.2
Language: Objective-C
XCode version: 8.1

**Did this work before?**
I don't know. I Implemented sending `userInfo` with `startCall:` method first time

**Expected behavior**
`userInfo` dictionary holds `NSNumber` values, they must not turn into `NSString` when opponent received it on `- (void)didReceiveNewSession:(QBRTCSession *)session userInfo:(NSDictionary *)userInfo`

**Actual behavior**
When I send `userInfo` dictionary with `[session startCall:userInfo];` method on call button click, opponent side  receiving this `userInfo` on `- (void)didReceiveNewSession:(QBRTCSession *)session userInfo:(NSDictionary *)userInfo`. Some of the `userInfo`'s fields hold `NSNumber` values, but opponent side received it in `NSStrings`

**Steps to reproduce the behavior**
Just send `userInfo` `NSDictionary` object with `startCall:` method and catch it on `- (void)didReceiveNewSession:(QBRTCSession *)session userInfo:(NSDictionary *)userInfo` on opponent side

**Any others comments?**
```
{
    "contact_id" : 346,
    "contact_type" : 1,
    "name" : "Jeremy"
}
```

if you send this dictionary with `startCall:` and catch it on `- (void)didReceiveNewSession:(QBRTCSession *)session userInfo:(NSDictionary *)userInfo`, you can observe that `contact_id` and `contact_type` keys hold `NSString` values not `NSNumber`. I really checked that sender side sending exactly `NSNumber` value, not `NSString`.

**Comment by Raikerian** [comment]
Hi,

Please use NSString instead of NSNumber for that. We are aware that there is some misconception with that, so we are adding generic NSString for that param in a new version of our WebRTC SDK.
