### ISSUE TITLE
Issue with saving the history in QuickBlox while creating as "QBChatDialogTypeGroup" dailog since 24th November 2016

### ISSUE THREAD

**Issue by NARESH627374** [QuickBlox/quickblox-ios-sdk#675]
**Environment details**
iOS SDK 10.0.2,
QuickBlox SDK: 2.7.4

**Did this work before?**
It was working fine earlier till 23rd November 2016.

**Type of Chat :**
Group Chat (QBChatDialogTypeGroup)

**Expected behavior**
Chat should update into the existing chat dialog created earlier when the chat message is being sent. 

**Actual behavior**

While sending the chat message, the message is being sent from the iOS device as observed in the log attached but the messages are not updated into the QuickBlox server we checked in online portal. Also we are not able to see any kind of errors or exceptions while sending the message. 

But if we change the type to private "QBChatDialogTypePrivate" everything is working fine as actual functionality existed before.

**Logs**
Not able to see any kind of errors from logs for the scenario. But attaching the log while creating new chat dialog, sending a new message, and receiving. [Logsfromdevice.txt](https://github.com/QuickBlox/quickblox-ios-sdk/files/615752/Logsfromdevice.txt)

**Steps to reproduce the behavior**
After Opening existing chat dialog unable to save chat messages into QuickBlox since 24.11.2016.

**Comment by VitaliyGuru** [comment]
Hello, @NARESH627374 
Could you please check it again?
Our server had some troubles last week, should be fixed now.

**Comment by Raikerian** [comment]
Closing due to all server-side issues were fixed by the date and a lack of issue creator's response.
