### ISSUE TITLE
How to get all friend requests for accept or reject IOS

### ISSUE THREAD

**Issue by kittu4ios** [QuickBlox/quickblox-ios-sdk#676]
Hi,

How can we retrieve all my friend request that are received from other users in IOS?  These is no direct method to fetch all friend requests. Please provide some steps to get this

**Comment by VitaliyGuru** [comment]
@kittu4ios,  Hello
Take a look at our [Q-municate project](https://github.com/QuickBlox/q-municate-ios). There you can find [QMContactManager](https://github.com/QuickBlox/q-municate-ios/tree/d43696b18c9c73fe22a64a81360c8d554e2734ba/Q-municate/Classes/Core/QMContactManager).

**Comment by kittu4ios** [comment]
Hi VitaliyGuru, Thanks for quick reply. I am asking about all contact request (for accept and reject). Not users that are already in my contact list. i.e list of all pending requests that I want accept or reject. I didnt find this feature on QMContactManager. I am using Q-municate project.

**Comment by Raikerian** [comment]
Hi @kittu4ios 

Check `[QBChat instance].contactList` it should have pending request array. But it is only showing **_your_** pending request. As of XMPP there is no initial way to know who have requests to you.
So what can you do is to send messages for contact request like we do in our app Q-municate, which was linked to you by @VitaliyGuru already.

You can always count dialogs with contact request messages to know which and from who contact requests you have.

**Comment by Raikerian** [comment]
Closing as an issue never existed and all issue creator's questions were answered.
If you are still having any other questions, feel free to create a new issue.
