### ISSUE TITLE
Messages are not displaying and updating.

### ISSUE THREAD

**Issue by ajay2c9** [QuickBlox/quickblox-ios-sdk#677]
**Environment details**
 "QB-OS" = "iOS 9.3";
  "QB-SDK" = "iOS 2.7";

**Did this work before?**
Yes

**Expected behavior**
When Messages are send,Those need to save and displayed when load the same dialog again. 

**Actual behavior**
When message is send. Messages is not saved and not displaying. When i relogin to the app or reinstall the app that time also messages are not displaying.

**Logs**
*Attach full logs that will describe your problem

 Error Domain=com.quickblox.chat Code=-1001 "(null)" UserInfo={NSLocalizedRecoverySuggestion=You are not joined to the dialog.}
dialog error is Cannot create/join room when already creating/joining/joined.

**Steps to reproduce the behavior**
step1: Go to existing Group chat or create a new GroupChat.
Step 2: Send messages.
 you got the above error.

Thank you

**Comment by VitaliyGuru** [comment]
@ajay2c9, Hello.
Could you please check it again?
Our server had some troubles last week, should be fixed now.

**Comment by Raikerian** [comment]
Closing due to all server-side issues were fixed by the date and a lack of issue creator's response.
