### ISSUE TITLE
Messages not saved on quickblox Admin panel

### ISSUE THREAD

**Issue by rahulparikh** [QuickBlox/quickblox-ios-sdk#68]
Hi There, I am using quickBlox in my Application, We have to give sync feature in our application. so we have created a API which will call quickBlox API to get message's of that user, now my problem is that when ever I start new chat (chat with new user) at that time 2-3 messages are stored on Admin Panel, but rest of the message are not getting stored.

I have added save flag to in my code. can you please suggest me what can I do?

QBChatMessage *message = [[QBChatMessage alloc] init];

NSMutableDictionary *paramaterDict = [self prepareDictionaryForMessage:strURL strAttachType:strAttachType];

message.text = [paramaterDict JSONRepresentation];
NSMutableDictionary *params = [[NSMutableDictionary alloc] init];
params[@"save_to_history"] = @YES;

long timeStamp = [[NSDate date] timeIntervalSince1970];
params[@"date_sent"] = [NSString stringWithFormat:@"%ld",timeStamp];

[message setCustomParameters:params];
.
.
. /*sendcode*/

**Comment by iSevenDays** [comment]
Hello! To resolve your problem I need more details.

1. Are you getting sent messages?
2. Whether the issue is reproduced without custom parameters (only with "save_to_history" ) and without attachments?
3. Which type of chat do you use? Group chat or peer-to-peer(1-1) chat?

**Comment by rahulparikh** [comment]
1:- Yes, I am able to send message.
2:- I have set the flag (save_to_history) flag to Yes, and sending only text message.
3:- This case is of group chat.

**Comment by AndreyMoskvin** [comment]
Are you still facing this issue?
