### ISSUE TITLE
block / unblock user

### ISSUE THREAD

**Issue by swetaagicent** [QuickBlox/quickblox-ios-sdk#680]
chatDidReceivePrivacyList not called when creating privacy list

**Logs**
*Attach full logs that will describe your problem (please, use github [gist](https://gist.github.com/))*

**Steps to reproduce the behavior**

**Any others comments?**

**Comment by VitaliyGuru** [comment]
@swetaagicent, Hello.
Coul you please send us your code snippet for privacy list creation?

**Comment by swetaagicent** [comment]
let item: QBPrivacyItem = QBPrivacyItem(type: USER_ID, valueForType:
selecterQBid, action: DENY)



                if self._blockPrivacyList != nil{

                    self._blockPrivacyList.addObject(item)

                }else{

                    self._blockPrivacyList = QBPrivacyList(name: "public",
items: [item])

                }

                QBChat.instance().setPrivacyList(self._blockPrivacyList)

                QBChat.instance().setActivePrivacyListWithName("public")


but now getting duplicate data on block and unblock ..i.e


*[PrivacyList name: public]*

* privacyItems: (*

*    "*

*   type: USER_ID*

*    userID: 20810359*

*    action: allow*

*    mutualBlock: NO",*

*    "*

*   type: USER_ID*

*    userID: 20810359*

*    action: deny*

*    mutualBlock: YES"*

*) *

**Comment by swetaagicent** [comment]
is there any update regarding this issue?

**Comment by Raikerian** [comment]
Hi @swetaagicent 

Who do you expect to receive chatDidReceivePrivacyList call upon its creation? You or the user that was blocked in that list?

**Comment by Pro100Andrey** [comment]
@swetaagicent Any updates?
