### ISSUE TITLE
Expected Identifier in NSManagedObjectModel+QMCDRecord.h

### ISSUE THREAD

**Issue by ErAshu** [QuickBlox/quickblox-ios-sdk#681]
I am implementing Quickblox in my project.
Getting error in NSManagedObjectModel+QMCDRecord.h file. 
See the attached screenshot. 
<img width="733" alt="screen shot 2016-11-30 at 11 33 15 am" src="https://cloud.githubusercontent.com/assets/4178384/20741704/f7d0aec0-b6f1-11e6-98c7-771426b48e9f.png">

Kindly help me out.

**Comment by Raikerian** [comment]
Answered https://github.com/QuickBlox/q-municate-ios/issues/201

Lets keep it one issue. Closing as duplicate.
