### ISSUE TITLE
QMServices-prefix.pch:5:9: 'Quickblox/Quickblox.h' file not found

### ISSUE THREAD

**Issue by ErAshu** [QuickBlox/quickblox-ios-sdk#682]
I am integrating quickblox in my project. getting 

/Project/testingQM/Pods/Target Support Files/QMServices/QMServices-prefix.pch:5:9: 'Quickblox/Quickblox.h' file not found

/Project/testingQM/Pods/Target Support Files/QMChatViewController/QMChatViewController-prefix.pch:5:9: 'Quickblox/Quickblox.h' file not found

**My Podfile details below**
pod 'QMServices'
pod 'QMChatViewController'
pod 'SearchEmojiOnString'
pod 'UIAlertView+Blocks'
pod 'Fabric'
pod 'Crashlytics'
pod 'MPGNotification'

<img width="1280" alt="screen shot 2016-11-30 at 8 25 47 pm" src="https://cloud.githubusercontent.com/assets/4178384/20757146/3499a2d2-b73b-11e6-9b49-59d4de8bf7e9.png">

**Comment by Raikerian** [comment]
Hi,

Which way is Quickblox sdk installed?

**Comment by ErAshu** [comment]
By POD....

**Comment by Raikerian** [comment]
Can you attach sample project with the exact same error? I can look into it. We don't have such problems in our samples so I can't understand whats really the problem in here.

**Comment by Pro100Andrey** [comment]
@ErAshu Any updates?
