### ISSUE TITLE
How to set Loudspeaker-receiver and Mute-audio in quickblox?

### ISSUE THREAD

**Issue by bhautikappv** [QuickBlox/quickblox-ios-sdk#683]
Can you please suggest me how to set Loudspeaker-receiver and Mute-audio in 2 different buttons in quickblox?
 
Thanks.

**Comment by Raikerian** [comment]
Hi,

This is not an issue but rather implementation question. For this we have our video sample that covering everything you have just asked, here it is: https://github.com/QuickBlox/quickblox-ios-sdk/tree/master/sample-videochat-webrtc

**Comment by bhautikappv** [comment]
Thanks Raikerian,

Got it. 
Implemented it and it's working fine.

Thanks Again.
