### ISSUE TITLE
Can not get reasons in QBError

### ISSUE THREAD

**Issue by mosluce** [QuickBlox/quickblox-ios-sdk#684]
**Did this work before?**
no, I just began to use Quickblox

**Expected behavior**
**Actual behavior**
Crash

**Logs**
none, the lldb did not show any log

**Steps to reproduce the behavior**
```swift
extension QBError {
    var localizedDescription: String? {
        return error?.localizedDescription
    }

    var reason: String? {
        guard let reasons = self.reasons else {  //crash on this line
            return nil
        }
        
        if let key = reasons.keys.first {
            return reasons[key]
        }
        
        return nil
    }
}
```

**Any others comments?**
Swift Version: 3.0.1

**Comment by Raikerian** [comment]
Hi,

Is this reproducible in our sample chat swift? Any other information would be helpful.

**Comment by mitrenegade** [comment]
Yes, this is reproducible simply by sending a push in appDelegate to a nonexistent user:

//
//  QMAppDelegate+Utils.swift
//  Q-municate
//
//  Created by Bobby Ren on 12/19/16.
//  Copyright © 2016 Quickblox. All rights reserved.
//

import Foundation
import Quickblox

extension QMAppDelegate {
    func sendPush() {
        let push = QBMPushMessage()
        push.alertBody = "test"
        push.soundFile = "default"
        QBRequest.sendPush(push, toUsersWithAnyOfTheseTags: "abcde", successBlock: { (response, events) in
            print("Successful push \(events)")
        }) { (error) in
            print("Push failed with error \(error?.reasons)")
        }
    }
}

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    ...    
    [self sendPush];
    
    return [[FBSDKApplicationDelegate sharedInstance] application:application
                                    didFinishLaunchingWithOptions:launchOptions];
}

Maybe reasons needs to be nullable? I'm not familiar enough with the new swift syntax but it only crashes if the error?.reasons is called in a swift file. If sendPush is implemented in the appdelegate objective-c file, this output is successful:


- (void)sendPush {
    QBMPushMessage * push = [[QBMPushMessage alloc] init];
    push.alertBody = @"test";
    push.soundFile = @"default";
    [QBRequest sendPush:push toUsersWithAnyOfTheseTags:@"test" successBlock:^(QBResponse * _Nonnull response, QBMEvent * _Nullable event) {
        NSLog(@"success %@, %@", response, event);
    } errorBlock:^(QBError * _Nullable error) {
        NSLog(@"Error %@", error.reasons);
    }];
}


(lldb) po error.reasons
{
    errors =     {
        base =         (
            "No recipients. At least one user should be subscribed for APNS (Apple Push) (through SDK or REST API)",
            "APNS (Apple Push) is not enabled for the current application. Please enable this notification channel in the settings tab of the admin panel"
        );
    };
}

**Comment by Raikerian** [comment]
The issue here was with incorrect generic for reasons property. Will be fixed in todays release.

**Comment by Pro100Andrey** [comment]
Fixed
