### ISSUE TITLE
ChatDidReciveMessage not being invoked

### ISSUE THREAD

**Issue by APavanKumar** [QuickBlox/quickblox-ios-sdk#685]
**Environment details**
*iOS version - 9.3, Quickblox iOS SDK version -2.8.0.1*

**Did this work before? - Yes**

**Expected behavior - For one- one chat once if chat is accidentally disconnected and reconnect automatically - (void)chatDidReceiveMessage:(QBChatMessage *)message method has to be invoked**

**Actual behavior - - (void)chatDidReceiveMessage:(QBChatMessage *)message is not being invoked automatically for one-one chat once if the chat is disconnected and reconnected automatically**

**Steps to reproduce the behavior**
Start chat using one-one chat. Switch of wifi or mobile data of the device( QB will be disconnected automatically). Once if you switch on the wifi previously - (void)chatDidReceiveMessage:(QBChatMessage *)message method was used to invoke automatically if there are any one-one messages not delivered in disconnected time. Now it is not working.

**Any others comments?**

**Comment by Raikerian** [comment]
Hi,

Is this reproducible in our samples? We haven't got such problems at all.
Are you sure you are subscribed to an appropriate chat delegate?

**Comment by kirillkhlopko** [comment]
Hi!

We have same issue in our app with receiving messages as desribed. After reconnecting to chat (chatDidReconnect method called successfully), any notifications about receiving message until send one. It occurs one or two times not each day while using app. We have tried to reproduce on sample, but no success, it requires a lot of time to reproduce.

**Comment by Raikerian** [comment]
Hi @kirillkhlopko 

Specific case would be helpful, our testers did not encounter this issue. All I can say just now is to check whether you have a QBChatDelegate subscription when chat message is received.

**Comment by kirillkhlopko** [comment]
@Raikerian, we will try to reproduce it again to provide more information.

For now, can mention, that SDK's delegate wrapped in our and we setting in once when created chats screen. Next one, it always reproduced after disconnect (by locking screen, for example) while some chat opened. After that started and handled reconnection in chatDidReconnect (it called, so subscription to QBChatDelegate exists), and we re-join current chat if it necessary. And next step is to send message in this chat from other account. 

This is steps that we found to reproduce (rarely). Maybe it will be helpful for you.

**Comment by kirillkhlopko** [comment]
One more, here is a link to a ticket with bug describing and video - https://assist.quickblox.com/index.php?/Default/Tickets/Ticket/View/35540. Support gave us some advices how we can log more information, we are going to try find some more in nearest week or two, if can :)

**Comment by Pro100Andrey** [comment]
Hi @kirillkhlopko,  any updates?
