### ISSUE TITLE
Is there any way to record video call ?

### ISSUE THREAD

**Issue by gstream** [QuickBlox/quickblox-ios-sdk#686]
Hello

Hope you are doing well. I am using this library for video call function of my project and it works well.
Now I want to record video/audio call. Is there any way to implement this feature ? or is it impossible with this framework ?

Thanks,
gstream

**Comment by Raikerian** [comment]
Hi,

It is in our plans, but you unfortunately cannot do it for now. No any ETA yet.

**Comment by Raikerian** [comment]
Closing as the question was answered.
If you are having any other questions or troubles please let us know by creating a separate issue.
