### ISSUE TITLE
How to display messages in Chat from where the User added. 

### ISSUE THREAD

**Issue by ajay2c9** [QuickBlox/quickblox-ios-sdk#687]
Hi, 
How to implement that display messages in Chat from where the User added. Currently When the user is added in the Middle of the Chat, Total Chat messages(i.e before and after the user added) are displaying.

**Comment by ajay2c9** [comment]
Hi,
I created the chat room with 3 users A,B,C .For some time three users are chatting ex: 30 messages. After that i added the 4th user in the Chat and start chatting (ex:Total messages are : 50)  . For users A,B,C,D all messages (50 messages)are displaying 
My requirement is.. Messages need to for user D is after user D is added (i.e From 31 to 50).
Please give suggestions how to implement the above functionality.

**Comment by Raikerian** [comment]
Hi,

This is more of an implementation question. The answer here is to use custom data in our QBChatMessage model. Just send any appropriate information you need to display there. For example user IDs that were added/left, and then just parse that message and display something like "User A has added user B". Thats the rough explanation, the only possible one.

If you need the real example:
Please check our Q-municate project, it has everything you have asked implemented. Look into QBChatMessage's with update types: https://github.com/QuickBlox/q-municate-ios

**Comment by ajay2c9** [comment]
Hi ,I checked my requirement in this project. It is not implemented in tis project

**Comment by Raikerian** [comment]
Then you should describe it better. With description you have provided I explained everything you need to do.
