### ISSUE TITLE
Kindly provide me some directions as i want to integrate call kit in my quickblox

### ISSUE THREAD

**Issue by heavyBug** [QuickBlox/quickblox-ios-sdk#689]
I want to integrate qb-callkit in my swift project. I am a newbie to objective c kindly provide me some directions... i tried to do it with ProviderDelegate ... successfully did it but the problem is how to accept and reject the user call ... I have integrated all objective c classes of quickblox in my swift project. I don't know how to integrate it ...

**Comment by Raikerian** [comment]
Hi,

VOIP push notifications are in development right now on our server. Without it it is not possible to implement call kit. Server-side team is currently working on it.

**Comment by heavyBug** [comment]
i have already implemented VOIP notifications ... My point is to accept and reject QuickBlox call from system Phone  UI

**Comment by Raikerian** [comment]
If you already have thme on your kind of server, then you should follow this apple provided guide https://developer.apple.com/reference/callkit

As for accept and reject just use our WebRTC api: https://quickblox.com/developers/Sample-webrtc-ios#Getting_Started_with_Video_Calling_API

**Comment by heavyBug** [comment]
when i click the native UI of incoming call ... Call kit opens up my app. my app control the call but at the back the system native call is also in progress which should close when i press the green button. Sorry for the bad english

**Comment by heavyBug** [comment]
Kindly tell me what you want me to explain to you... I am totally confused

**Comment by Raikerian** [comment]
I am a bit confused as well.
So the issue is, you are pressing accept button on Apple call kit while phone is locked, but instead of accepting call it opens app? Correct me if I got it wrong.

**Comment by heavyBug** [comment]
No it's not opening the app it accept a the call ... But with no voice

**Comment by Raikerian** [comment]
Can you attach extended stat reports for that call without voice, use this to turn on stat reports:
https://github.com/QuickBlox/quickblox-ios-sdk/issues/651#issuecomment-259616384

**Comment by AnkitSS77** [comment]
Hi Raikerian,

Does VOIP push notifications are  still in development or it is completed. I also want to implement call kit in my quickblox.

**Comment by VitaliyGuru** [comment]
@heavyBug, @AnkitSS77, Glad to inform you that we [have already released VOIP notifications](https://quickblox.com/blog/voip-push-notifications/).

**Comment by v-anh** [comment]
Hi guys,

Could you help me to advice me how to answer the call with CallKit. Because Quickblox just can answer the call by QBRTCSession. So how can I got QBRTCSession without didReceiveNewSession ?

Thanks

**Comment by Raikerian** [comment]
Hi @v-anh 

Please, next time create own issues if you have one.
Regarding your question, you can use push notifications for this.

**Comment by heavyBug** [comment]
Place your didreceivenewsession in your callkit class and pick up the
session to accept the cell

**Comment by v-anh** [comment]
Hi @Raikerian, @heavyBug 

I have already put a question in here: https://github.com/QuickBlox/quickblox-ios-sdk/issues/826
Thanks for your answer.

@heavyBug: Did you mean to put the QBRTCClientDelegate inside my callkit class? If yes, could you point me which place that I could put QBRTCClientDelegate in? In initial function? or when received VOIP push notifications?

Thanks

**Comment by Jaimin2208** [comment]
Quick Blox not Any Good Tutorial

**Comment by Jaimin2208** [comment]
please any one ask me when implement call kit then which place didReciveNewsession method move

**Comment by VitaliyGuru** [comment]
CallKit is implemented in Q-municate. 
Please take a look at [QMCallKitAdapter](https://github.com/QuickBlox/q-municate-ios/blob/8b00f2270f970cc32539e4e609433abb2b24a14a/Q-municate/Classes/QMCallKitAdapter/QMCallKitAdapter.h) and [QMCallManager](https://github.com/QuickBlox/q-municate-ios/blob/8b00f2270f970cc32539e4e609433abb2b24a14a/Q-municate/Classes/Core/QMCallManager/QMCallManager.h)
