### ISSUE TITLE
How to get all room with the help of chat dialoge API

### ISSUE THREAD

**Issue by rahulparikh** [QuickBlox/quickblox-ios-sdk#69]
Hello All,
I want to get all room information, based on that room information I want to join user to all the groups in order to receive message among different group. so I am thinking that at the time of logging into chat, I will fetch all room list and forcefully joined all the rooms. so user can receive messages event he is on the other screen. is there is any other work around for this ?

Now my problem is I am using the above method to finding all rooms.
[[QBChat instance] requestAllRooms]
but this method is deprecated and suggested to use ("Use Chat Dialogs API instead.").

How can I use chat dialogs API here. I mean I am not able to find this API.
Can you please help me.

Thanks a lot for you help.

**Comment by soulfly** [comment]
Hi, 

yes, 'requestAllRooms' is deprecated and will be removed 

A new solution is described here http://quickblox.com/developers/SimpleSample-chat_users-ios

**Comment by rahulparikh** [comment]
How to use chat dialog API ?

**Comment by soulfly** [comment]
Please check my link I sent
it provides step by step instructions

**Comment by rahulparikh** [comment]
Do I need to check section 3.7 ?

**Comment by soulfly** [comment]
Yes

and also read all guide

**Comment by rahulparikh** [comment]
I read, but not get any detail about chat dialoge api, how to use it

**Comment by AndreyMoskvin** [comment]
Rooms API is no longer available - we are moving to dialog API in term of unification of interface.
In sample-chat we are using chat dialog API - you can use it as an example.
