### ISSUE TITLE
Attachment image order changes in chat history after upload

### ISSUE THREAD

**Issue by ameenudheenirshad** [QuickBlox/quickblox-ios-sdk#690]
Steps to recreate
Sent a attachment image in chat.
Sent 3 or more messages before the attachment get uploaded. 
You can see the attachment image comes to last in chat when it get uploaded.
Its index changes once it uploaded and collection view rearranges.
This is seen in latest QMService project with Quickblox 2.9 SDK.
Please fix this.

**Comment by Raikerian** [comment]
Hi,

It is always being like that. Cause after attachment was uploaded we are sending message, therefore it will have a fresh date sent.

**Comment by ameenudheenirshad** [comment]
From user point of view its a bad usability. I expect you will fix it in
future release.

**Comment by Raikerian** [comment]
As for me it is a good usability.
Attachment is uploading, it is still wasn't sent. Meanwhile you are sending messages which are immediately being sent. Attachment message being sent only after being uploaded. You don't need attachment upload UI to pop under your sent messages, you only need to know about it when it is sent, but not sending. As for it I do not see any bug here, there are some live app examples of this attachment sending philosophy. 
If you are having any other view you can try to explain it, as an original post in this thread doesn't contain any explanation of your view on how should it work.

That is an answer if you are considering this as a bug. If you are considering this as a question on how to change this, then first try to explain what you are trying to achieve.

> You can see the attachment image comes to last in chat when it get uploaded.
Its index changes once it uploaded and collection view rearranges.

As I've already said, dateSent date is only possible to know when attachment image has been uploaded. So if you don't want this behavior to happen, then. approach and philosophy of sending attachment messages that we are currently using is not for you. In your case you should not show a message before attachment being uploaded, but instead show some kind of UI that is representing attachment upload, and only after it is done, show message (send message) in chat.

**Comment by sandeep102** [comment]
I face same Issue when i send message. collection view rearranges. send message.

**Comment by VitaliyGuru** [comment]
@sandeep102  Hello. An explanation given by @Raikerian isn't changed. We didn't change the workflow for messages with attachments.
