### ISSUE TITLE
QMChatSectionManager.m

### ISSUE THREAD

**Issue by swetaagicent** [QuickBlox/quickblox-ios-sdk#692]
QMChatSectionManager.m line 407
-[QMChatSectionManager messageForIndexPath:]

getting this error on crashlytics.But unable to find in code. Any idea how to resolve this.

i think i have same issue like this..

http://stackoverflow.com/questions/37150746/fatal-exception-nsrangeexception-index-2-beyond-bounds-0-1

thanks

**Comment by Raikerian** [comment]
Hi,

Chat section manager was deprecated in our latest version of QMChatViewController. Update to 0.4 and use QMChatDataSource from now on, example is in our samples in this repository.
QMChatDataSource fixing most of the problems chat section manager had.

**Comment by swetaagicent** [comment]
hi,
Thanku for your reply..its working now

**Comment by Raikerian** [comment]
If you are still having any other troubles let us know by creating a separate issue.
