### ISSUE TITLE
How to show time in normal format in quickblox

### ISSUE THREAD

**Issue by swetaagicent** [QuickBlox/quickblox-ios-sdk#694]
![screen shot 2016-12-06 at 3 34 42 pm]

**Comment by Raikerian** [comment]
Hi,

You screenshot is not displaying.

**Comment by swetaagicent** [comment]
![screen shot 2016-12-06 at 3 34 42 pm](https://cloud.githubusercontent.com/assets/16878444/20921649/23f5cd2c-bbcb-11e6-8c4f-c04c173dfb67.png)

**Comment by swetaagicent** [comment]
HI,thnakx. i solved the issue

**Comment by Pro100Andrey** [comment]
@swetaagicent Any updates?

**Comment by Raikerian** [comment]
Closing due to invalid description.
