### ISSUE TITLE
Custom Object extendedRequest filter by id or created_at

### ISSUE THREAD

**Issue by ilkerdagli** [QuickBlox/quickblox-ios-sdk#695]
I am trying to fetch quickblox custom objects by filtering created_at or _id field with no luck. When I do:

```
let getRequest = NSMutableDictionary()
getRequest["limit"] = 20
getRequest["sort_desc"] = "_id"
QBRequest.objects(withClassName: "Admission", extendedRequest: getRequest, successBlock: {(response, objects, page) in {
    print(objects)
} , errorBlock: {(error) in

})
```
It works as expected. Hence, the records coming sorted by _id desc. But, when I try to do:
```

let getRequest = NSMutableDictionary()
getRequest["limit"] = 20
getRequest["sort_desc"] = "_id"
getRequest["_id[lt]"] = self.admissions.last?.id
QBRequest.objects(withClassName: "Admission", extendedRequest: getRequest, successBlock: {(response, objects, page) in {
    print(objects)
} , errorBlock: {(error) in

})
```
the filter is not working. Response comes some as the first example. I will use this for pagination. When tableview scrolled to the bottom, it will request 20 more objects which their ids are less than tableview's last object. Btw, I have tried with:

`getRequest["created_at[lt]"] = self.admissions.last?.createdAt`

and again with no luck.

**Comment by Raikerian** [comment]
Hi,

I will look into it and post update soon.

**Comment by Raikerian** [comment]
This was confirmed as server-side issue, although no any ETA on fix. Will update if there will be any information regarding this issue.

**Comment by soulfly** [comment]
You can now use _id filter, it's fixed
