### ISSUE TITLE
Issue when registering for Push Notification with updated 'QuickBlox' and 'Quickblox-WebRTC'.

### ISSUE THREAD

**Issue by bhautikappv** [QuickBlox/quickblox-ios-sdk#696]
Hi,

I have recently updated my pods from 
    pod 'QuickBlox', '2.7.3'
    pod 'Quickblox-WebRTC', '2.2'  
to latest one

I got the error for Push Notification.
shows in the below screenshot.

![push](https://cloud.githubusercontent.com/assets/24278294/20937932/f2f8187e-bbb6-11e6-9d60-7bc54bdda5e2.png)

Please see the above issue and suggest me what is the next step to resolve?

Thanks.

**Comment by pethanihiten** [comment]
Thanks bhautikappv

I also having the same problem.

Please give solution for that ASAP.

Thanks

**Comment by Pro100Andrey** [comment]
Hi @bhautikappv, please provide swift version

**Comment by Pro100Andrey** [comment]
@bhautikappv please check [swift example](https://github.com/QuickBlox/quickblox-ios-sdk/blob/master/sample-chat-swift/sample-chat-swift/AppDelegate.swift#L58)

**Comment by bhautikappv** [comment]
It's working

Thanks @Pro100Andrey
