### ISSUE TITLE
Unexpectedly stop video calling at any time.  

### ISSUE THREAD

**Issue by pethanihiten** [QuickBlox/quickblox-ios-sdk#698]
--> **When video call start, it’s working fine and no issue occur but it’s unexpectedly disconnect after some time.**
time is not fixed it is disconnected at 3 minutes, 8 minutes, 15 minutes or any other timing.

please suggest what can i do?

here is the log after disconnected call.

rtc::<Peer:0x1702ef900, UID:20229589, r:Offer> Ice connection changed: Disconnected
rtc::<Peer:0x1702ef900, UID:20229589, r:Offer> Began handling disconnect
rtc::Started timer: disconnect timer, background task id 13 ...
rtc::-[QBRTCCameraCapture dealloc]
rtc::<Peer:0x1702ef900, UID:20229589, r:Offer> Ice connection changed: Connected
rtc::<Peer:0x1702ef900, UID:20229589, r:Offer> Stopped handling disconnect
rtc::Invalidated timer:disconnect timer, background task id 13 ...
rtc::<Peer:0x1702ef900, UID:20229589, r:Offer> Stopped dialing
rtc::<Peer:0x1702ef900, UID:20229589, r:Offer> Ice connection changed: Completed
rtc::Destroy disconnect timer

rtc::Pool is out of buffers, dropping frame
rtc::Pool is out of buffers, dropping frame
rtc::Pool is out of buffers, dropping frame
rtc::Pool is out of buffers, dropping frame
rtc::Pool is out of buffers, dropping frame
rtc::Pool is out of buffers, dropping frame
rtc::Pool is out of buffers, dropping frame
rtc::Pool is out of buffers, dropping frame
rtc::{180, 240}
rtc::Deleting converter buffer pool. <QBRTCFrameConverter: 0x1702d6dc0>
rtc::Pool is out of buffers, dropping frame
rtc::Pool is out of buffers, dropping frame
rtc::Pool is out of buffers, dropping frame

is there any way to restrict it?

Please reply ASAP.

Thanks in advance.

**Comment by Raikerian** [comment]
Hi,

Have connect been restored after this disconnect or not?
Any other description would be helpful.

**Comment by Raikerian** [comment]
We have just released our new WebRTC SDK 2.3 which is containing lots of fixes and improvements.
Here is full changelog of version 2.3: http://quickblox.com/developers/Sample-webrtc-ios#Framework_changelog Please check it out.

We have also updated our video sample in this repository, check your issue there as well.

Anyway, if you will have any other problems or questions, feel free to start new issue to let us know.

Have a nice holidays.
