### ISSUE TITLE
Displaying a user as 0 in  1-1 Chatroom.

### ISSUE THREAD

**Issue by ajay2c9** [QuickBlox/quickblox-ios-sdk#699]
ID:5848180da0eb473a35000014                      
    Created At:2016-12-07 14:09:17 +0000                      
    Updated At:2016-12-08 07:08:47 +0000                      
    Room JID:(null)                      
    name:Miracle                      
    photo:(null)                      
    type:3                      
    lastMessage:Ok                      
    lastMessageDate:2016-12-08 07:08:47 +0000                      
    occupantIDs:(
    20857331,
    21237621
)                      
    userID:0                      
    data:(null)                      
    unreadMessagesCount:0                      
    lastMessageUserID:21237621

 When 1-1 chat room is created userID is displaying as 0.
plz give suggestions to solve this issue.

**Comment by Raikerian** [comment]
Hi,

Please attach logs of dialog creation.

**Comment by Raikerian** [comment]
@ajay2c9 any updates on this?
