### ISSUE TITLE
How to delete the 1-1 Chatroom when any one user is left from the Chat.

### ISSUE THREAD

**Issue by ajay2c9** [QuickBlox/quickblox-ios-sdk#700]
Hi, 
I created a 1-1 chat room.When one user is left from the chatroom, How to delete the Chat from other side too.

**Comment by Raikerian** [comment]
Hi,

Please attach logs of dialog creation.

**Comment by Raikerian** [comment]
Hi,

You can send message with a specific custom data, saying to other use that he should delete that dialog.

**Comment by Raikerian** [comment]
Closing due to question being answered.
