### ISSUE TITLE
Last message is displaying in ChatDialog for user in 1-1 chat after leave the chat and create the chat with same user

### ISSUE THREAD

**Issue by ajay2c9** [QuickBlox/quickblox-ios-sdk#701]
Hi,
Last message is displaying when user is left and again initiate the chat with same user.
For Example:

A and B are two user having 1-1 chat room(Private chat). After some chat B left the Chat room.
after that B create a new chat room with A(Private chat). In that chat dialog last message is displaying. but in detail there is no messages.

Please give suggestions for without displaying last message in above case.
Thank you.

**Comment by Raikerian** [comment]
Hi,

Thank you for reporting the issue, seems like a bug. Will be fixed in a future releases.
