### ISSUE TITLE
Stop download image from server when user tapped cancelButton

### ISSUE THREAD

**Issue by Daewoox** [QuickBlox/quickblox-ios-sdk#703]
Hi! I am trying release stop download image from server when user tapped cancelButton. QBRequst have method cancel(). But i get crash threads error when I used it. Like this:
#0 0x06476b01 in swift_bridgeNonVerbatimFromObjectiveC ()
Can you give me please any suggestion?

**Comment by haifizarshad** [comment]
It might be the issue with the bridge created to communication b/w Swift and ObjC, try to debug using breakpoints and set [QBSettings setLogLevel:QBLogLevelDebug]; value in "AppDelegate.h", it will give u clear picture whats going on under the hood!

**Comment by Raikerian** [comment]
Hi @Daewoox 

I have just tested it in our sample chat swift and everything is working fine. Can you reproduce it in our sample?

If not please provide more information on your issue, such as how you connect our SDK,  swift and xcode version.

**Comment by Pro100Andrey** [comment]
Hi @Daewoox, any updates?
