### ISSUE TITLE
No Such Module 'QuickbloxWebRTC' - Xcode8 - Swift project - Cocoapods

### ISSUE THREAD

**Issue by PranavJaiswal** [QuickBlox/quickblox-ios-sdk#704]
I'm trying to do  'import QuickbloxWebRTC' in my swift project AppDelegate.h. I keep getting error(attached screenshot).
<img width="1145" alt="screen shot 2016-12-10 at 04 42 53" src="https://cloud.githubusercontent.com/assets/5711820/21067721/296be370-be93-11e6-953d-4da08feac7cb.png">

I'm also attaching podfile that i've been using.
[Podfile.zip](https://github.com/QuickBlox/quickblox-ios-sdk/files/643410/Podfile.zip)

 
**Environment details**
*iOS version, Quickblox iOS SDK version, QuickbloxWebRTC SDK version (optional)*
Xcode 8.0, iOS 10.0 Deployment target 

**Did this work before?**
No

**Expected behavior**
Should be able to compile app after 'import QuickbloxWebRTC', so that i can implement video calling feature.

**Actual behavior**
Unable to Compile the App

**Logs**
*Attach full logs that will describe your problem (please, use github [gist](https://gist.github.com/))*

**Steps to reproduce the behavior**

**Any others comments?**

**Comment by Raikerian** [comment]
Hi,

Use bridging header to import Quickblox WebRTC framework.

**Comment by PranavJaiswal** [comment]
@Pro100Andrey Can you please help me with this issue?

**Comment by Raikerian** [comment]
Remove use_frameworks flag, you cannot use it while installing QuickbloxWebRTC framework through pods. Because it is a static library rather than a dynamic framework.

After that create a bridging header as intended (here is a guide: http://www.learnswiftonline.com/getting-started/adding-swift-bridging-header/). Import Quickblox and QuickbloxWebRTC frameworks in bridging header. If its still not working, attach the project with bridging header.

**Comment by PranavJaiswal** [comment]
@Raikerian 
Still Does not work. Created a new swift project, then created a pod file with below contents
```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
target "QBSwiftTest1" do
    pod 'Quickblox-WebRTC', '~> 2.2'
    pod 'QuickBlox'
end
```

Added a bridging header file with following two lines of Code & it throws error
```
#import "Quickblox.h"
#import "QuickbloxWebRTC.h"
```

<img width="811" alt="screen shot 2016-12-15 at 03 11 10" src="https://cloud.githubusercontent.com/assets/5711820/21203134/1ff77150-c277-11e6-8dd9-3bec1abad06e.png">

Attaching my project https://drive.google.com/file/d/0B5nqEBSJjCriVnNYbmZ1T1gzaTA/view?usp=sharing please refer & let me know.

Thank you for your time & looking forward to your reply.

**Comment by Raikerian** [comment]
For the versions you are using, your imports there should be like this:

```objc
#import <Quickblox/Quickblox.h>
#import <QuickbloxWebRTC/QuickbloxWebRTC.h>
```

**Comment by Pro100Andrey** [comment]
@PranavJaiswal, Any updates ?

**Comment by DhananjayAwasthisyscraft** [comment]
Can u Please share updated code in swift

**Comment by optimumbrew** [comment]
i have try to video calling ,  calling to another user but can not be show video , the video screen are black window. please help be.

**my code file attach the file
[VideoVC.swift.zip](https://github.com/QuickBlox/quickblox-ios-sdk/files/1547660/VideoVC.swift.zip)

** 
**my output are also attach** 
![image1](https://user-images.githubusercontent.com/34236449/33830443-31d6f3a6-de9a-11e7-8ad9-6fe4f56a2f90.PNG)
