### ISSUE TITLE
Is there a way to change group chat admin

### ISSUE THREAD

**Issue by ahmetws** [QuickBlox/quickblox-ios-sdk#706]
I try to change the userID parameter of dialog with QBRequest.updateDialog but it did not work. 

I want to change the group admin when the actual admin left the group.

**Comment by Raikerian** [comment]
Hi @ayalcinkaya 

You mean ownerID of QBChatDialog? Unfortunately for now there is no possible way to do it (not supported by our server).

**Comment by ayalcinkaya** [comment]
Is there a possibility to workaround this ? Do you have any suggestion ?

**Comment by Raikerian** [comment]
For what purposes do you need this admin user ID? If you want to remove occupants, then there is no workaround. If only to display, you can use custom object storage to store admin user ID.

**Comment by Raikerian** [comment]
If you are a user of our dedicated enterprise plan you can contact our support on this, and server team will look into it.

**Comment by tarunseerayash** [comment]
Hello I have the similar problem 

In our app QB chat is associated with our app Wall's , so there can be multiple chats on a single wall.
Every chat owner is different but if main wall is get deleted all chats associated with this get deleted.

So is there any way so we can provide access to our wall owner to delete all chats having on the wall??

We can go with dedicated server plan if you support these custom features.

Is there any feasibility with current SDK?

Thanks,
Tarun Seera

**Comment by Ahmadpashaquarterpi** [comment]
Is it possible to change the Group Owner now?
