### ISSUE TITLE
How to check offline/online real time status in QB?

### ISSUE THREAD

**Issue by tanujtak1986** [QuickBlox/quickblox-ios-sdk#708]
Hi, I have to fetch real time recipient online/offline status.i tried with last request at method that is mentioned in QB but it not give proper result.
I also mention example please help me, my App is pending with this issues.

For Instance:-
According to QB Doc by last request at method:- suppose user A login at 9:10 and still do some stuff and still in app around 15 minutes and user B login at 9:20 and check according to this concepts then,
if( i am user B) I am checking for 5 minutes difference for online then also it will give false result..because when user B fetch user A details then it's give last request at 9:10 (though user A is still login with QB) and now suppose time is 9:20 then difference will be for 10 min and it will give offline..while User A still online(login with QB and perform some stuff like chat e.t.c)...please help me it is giving Wrong result.

**Comment by tanujtak1986** [comment]
Last request at flag never be updated until we explicit login in QB if i am still in chat let say 20 minutes then it's only give login(last request time), which is wrong, please help me.

  [QBUUser]:
  ID:17935032
  created at:2016-09-19 10:30:01 +0000
  updated at:2016-12-21 05:57:15 +0000
  externalUserID:86
  blobID:6323469
  facebookID:(null)
  twitterID:(null)
  twitterDigitsID:(null)
  full name:atal kumar
  email:atalsinghmgstt@gmail.com
  login:+917276280594
  phone:+917276280594
  tags:(
    online,
    Male,
    MessageON,
    GoyoON
)
  lastRequestAt:2016-12-21 05:57:14 +0000
  customData:(null)
  website:(null)



  [QBUUser]:
  ID:17935032
  created at:2016-09-19 10:30:01 +0000
  updated at:2016-12-21 05:57:15 +0000
  externalUserID:86
  blobID:6323469
  facebookID:(null)
  twitterID:(null)
  twitterDigitsID:(null)
  full name:atal kumar
  email:atalsinghmgstt@gmail.com
  login:+917276280594
  phone:+917276280594
  tags:(
    online,
    Male,
    MessageON,
    GoyoON
)
  lastRequestAt:2016-12-21 05:57:14 +0000
  customData:(null)
  website:(null)


  [QBUUser]:
  ID:17935032
  created at:2016-09-19 10:30:01 +0000
  updated at:2016-12-21 06:01:42 +0000
  externalUserID:86
  blobID:6323469
  facebookID:(null)
  twitterID:(null)
  twitterDigitsID:(null)
  full name:atal kumar
  email:atalsinghmgstt@gmail.com
  login:+917276280594
  phone:+917276280594
  tags:(
    online,
    Male,
    MessageON,
    GoyoON
)
  lastRequestAt:2016-12-21 05:57:14 +0000
  customData:(null)
  website:(null)
  lastRequestAt:2016-12-21 05:57:14 +0000
  lastRequestAt:2016-12-21 05:57:14 +0000

**Comment by Raikerian** [comment]
Hi,

You can use QBContact list for this, every QBContactListItem has isOnline property.

**Comment by Pro100Andrey** [comment]
@tanujtak1986 Any updates?

**Comment by Raikerian** [comment]
Closing due to question being answered and no further issue creator response.
