### ISSUE TITLE
Getting the total of all unread messages

### ISSUE THREAD

**Issue by kevb10** [QuickBlox/quickblox-ios-sdk#709]
**Environment details**
*iOS version, Quickblox iOS SDK version, QuickbloxWebRTC SDK version (optional)*
2.7.6
iOS 10

What I tried
```objc
[QBRequest totalUnreadMessageCountForDialogsWithIDs:[NSSet setWithObject:@""] successBlock:^(QBResponse * _Nonnull response, NSUInteger count, NSDictionary<NSString *,id> * _Nullable dialogs) {
    messageIDFormatted = [NSString stringWithFormat:@"Messages (%lu)", (unsigned long)count];
} errorBlock:^(QBResponse * _Nonnull response) {
    messageIDFormatted = @"ERROR";
}];
```

 What do I pass in if I want all dialogs?

**Comment by Raikerian** [comment]
Hi,

As the doc states:

> Returns unread message count for dialogs with ids. Includes total count for all dialogs for user also.

It should also include all dialogs unread counter.

**Comment by Raikerian** [comment]
So you get correct response? If yes then its correct.

**Comment by kevb10** [comment]
I don't get anything in response

**Comment by Raikerian** [comment]
Then you should pass any other dialog ID to get unread counter for all ones.

**Comment by kevb10** [comment]
let me try that

**Comment by Pro100Andrey** [comment]
Hi @kevb10,  any updates ?

**Comment by kevb10** [comment]
I am assuming the unread count is in 'count'. It's only giving me the total unread for the specific ID I provide. I am looking for all unread count for the currently logged in user so that I can display it on the main screen of my app

**Comment by VitaliyGuru** [comment]
@kevb10, If you pass an empty set as a parameter you will get `count` of all unread messages.

**Comment by Pro100Andrey** [comment]
Hi @kevb10, any updates?

**Comment by kevb10** [comment]
@VitaliyGuru Here is what I passed in initially as I mentioned above [NSSet setWithObject:@""] .

**Comment by VitaliyGuru** [comment]
@kevb10 
Could you please enable full logs, perform this request and send us this information?

```
[QBSettings setLogLevel:QBLogLevelDebug];
```

**Comment by kushal211** [comment]
Did you able to get the total number of unread messages for all the dialogs?
