### ISSUE TITLE
how to stop the receiving messages  in both 1-1 and group chat when user Blocked using privacy item.

### ISSUE THREAD

**Issue by ajay2c9** [QuickBlox/quickblox-ios-sdk#710]
I used the privacy item for block the user. IN this i keep the privacy type as QBPrivacyTypeUserID to block the user. and keeping the mutual YES. but it is not working in GroupChat. how to implement the block condition in both 1-1 Chat and GroupChat.

Thank you

**Comment by Raikerian** [comment]
Hi,

Use `QBPrivacyTypeGroupUserID` instead of `QBPrivacyTypeUserID` to block user in group chat.
So, you need to block user with both those params in order to block him in group chat and private one.

**Comment by ajay2c9** [comment]
HI,
By using "QBPrivacyTypeGroupUserID"  I can block the user in both 1-1 Chat and GroupChat.Am i right?

**Comment by Raikerian** [comment]
No, only group chat. So you need to use both.

**Comment by ajay2c9** [comment]
Ok.
So I need to create two privacy items with same userID and with different privacyItems to block the user in both 1-1 chat and group Chat . am i right?

**Comment by Raikerian** [comment]
Right.

**Comment by ajay2c9** [comment]
Thankyou.

**Comment by ajay2c9** [comment]
Hi,
I added both the QBPrivacyTypeGroupUserID and QBPrivacyTypeUserID for the same user in the privacy list for block the user in both Private Chat and GroupChat . when i set "mutual block=YES" in both privacy items and added to them to the Privacy List and updated the list .Before adding items to the privacy list, I print the log it prints the items with mutual block "YES". 
             I checked the List after updating. In that list the mutual block status is changed to "NO" for both items of same User. Mutual block is not working in GroupChat.
