### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by ameenudheenirshad** [QuickBlox/quickblox-ios-sdk#711]
Sometimes my app crashes when I press back button from chatviewcontroller. Below is the log i got when debugging.

2016-12-27 13:06:05.596 MyApp[957:209178] [QMChatCache] Dialogs to insert 0, update 0
2016-12-27 13:06:05.625 MyApp[957:209178] *** Terminating app due to uncaught exception 'NSGenericException', reason: '*** Collection <__NSArrayM: 0x17136ca0> was mutated while being enumerated.'
*** First throw call stack:
(0x25218137 0x332a8c77 0x25217bbd 0x25134199 0x169ff8d 0x16ce94d 0x332c2d57 0x2511b681 0x251300f7 0x332c2d57 0x78ae65 0x3386badb 0x7ccc71 0x3386badb 0x307ad89 0x3074ac5 0x307cb1b 0x307de21 0x33994da9 0x33994afc)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) po 0x17136ca0
<__NSArrayM 0x17136ca0>(
39454_585a54cca28f9ac5c400015b@muc.chat.quickblox.com,
39454_585a54cca28f9a9f8d000061@muc.chat.quickblox.com,
39454_585a54d7a28f9ac5c400016b@muc.chat.quickblox.com,
39454_585a54d7a0eb4797eb000013@muc.chat.quickblox.com,
39454_585a54d8a28f9aa2fa0000a1@muc.chat.quickblox.com,
39454_585a54d8a0eb47f0fb00008e@muc.chat.quickblox.com,
39454_585a54d9a0eb4797eb000017@muc.chat.quickblox.com,

**Comment by Raikerian** [comment]
Hi,

Add [breakpoint for all exceptions](http://blog.manbolo.com/2012/01/23/xcode-tips-1-break-on-exceptions) in Xcode to see the exact line where it is crashing.

**Comment by ameenudheenirshad** [comment]
I think it happens inside the class QMDBStorage, From stack trace I found exception occurs in below function.

- (void)async:(void(^)(NSManagedObjectContext *context))block {
    dispatch_async(self.queue, ^{  //I think exception occurs here 
        block(self.bgContext);
    });
}

**Comment by VitaliyGuru** [comment]
@ameenudheenirshad, Hello. Could you please tell me SDK and QMServices versions?

**Comment by ameenudheenirshad** [comment]
Latest SDK 2.9 and qmservice version 0.4.5

**Comment by Pro100Andrey** [comment]
Hi @ameenudheenirshad, we have reproduced this issue on our side, thanks for reporting, will be fixed in next release

**Comment by Pro100Andrey** [comment]
Fixed
