### ISSUE TITLE
Crash when accepting video chat

### ISSUE THREAD

**Issue by diegothucao** [QuickBlox/quickblox-ios-sdk#712]
Dear all,
I am working on my ios project that integrates Quickblox video call.
However, when user accept the video call, the app crashes at 

[QBRTCFrameConverter dequeuePixelBufferForFrame:] at /Users/koma/Projects/SDK-ios-WebRTC/QuickbloxWebRTC/QuickbloxWebRTC/Classes/VideoRenderer/Converters/QBRTCFrameConverter.m:373

Have you ever meet this issue, please support me.

Thanks in advance.

**Comment by Raikerian** [comment]
Hi,

Add [breakpoint for all exceptions](http://blog.manbolo.com/2012/01/23/xcode-tips-1-break-on-exceptions) in Xcode to see the exact line where it is crashing.

**Comment by diegothucao** [comment]
It does not show the line in my code, it go directly to the quickblox library

**Comment by Pro100Andrey** [comment]
Hi @diegothucao, Please provide full stack trace for crash

**Comment by Pro100Andrey** [comment]
@diegothucao Any updates?

**Comment by pwsharma** [comment]
@diegothucao did you find any solution for this issue. I am facing the same issue with latest version of QuickBlox iOS SDK.
