### ISSUE TITLE
Internal crash

### ISSUE THREAD

**Issue by kirillkhlopko** [QuickBlox/quickblox-ios-sdk#713]
Hi! 
Yesterday I've updated version of QB's SDK to 2.9 in project. 
Today got crash after starting application, here is a part of crashlog:
<img width="703" alt="c6e36ae4ff124eb1bdd5f58621de80ec" src="https://cloud.githubusercontent.com/assets/17878067/21561778/13abb6b8-ce7a-11e6-831c-f6fbacf07903.png">

**Comment by Pro100Andrey** [comment]
Hi @kirillkhlopko, any updates?
