### ISSUE TITLE
limit in conjunction with location[near]

### ISSUE THREAD

**Issue by michaelbanholzer** [QuickBlox/quickblox-ios-sdk#716]
*Help avoid duplicate issue reports, check [existing issues](https://github.com/QuickBlox/quickblox-ios-sdk/issues)*
 
**Environment details**
*iOS version, Quickblox iOS SDK version, QuickbloxWebRTC SDK version (optional)*
2.8.0.1

**Did this work before?**
no

**Expected behavior**
the result count as specified by the limit parameter

**Actual behavior**
the max limit is still 100

**Logs**
*Attach full logs that will describe your problem (please, use github [gist](https://gist.github.com/))*

**Steps to reproduce the behavior**
```swift
QBRequest.objects(withClassName: userPropertiesClassName, extendedRequest: ["location[near]" : nearProperties, "limit" : 1000], successBlock: { (response, customObjects, responsePage) in
            log("objects count \(customObjects?.count)")    
        }) { (errorResponse) in
            log("objects error \(errorResponse)")
        }
```

**Any others comments?**

**Comment by VitaliyGuru** [comment]
As [documentation](http://quickblox.com/developers/Custom_Objects#Filters) says the limit is 100.
If you want to increase the limit you should change your [plan] (http://quickblox.com/plans/) to Enterprise.

**Comment by Pro100Andrey** [comment]
Hi @michaelbanholzer, any updates?
