### ISSUE TITLE
3g/4g connection problems

### ISSUE THREAD

**Issue by GiacomoSilli** [QuickBlox/quickblox-ios-sdk#717]
Hello everyone, I'm using quickblox sdk sample videochat for ios and android.
Working properly using the wifi network.

If I try to use 3g / 4g the device can not connect.

What is the problem? Thanks

**Comment by Pro100Andrey** [comment]
Hi @GiacomoSilli, please provide full logs from iOS & Android side

**Comment by GiacomoSilli** [comment]
Thanks for answer, i hope it will help

Android log
http://pastebin.com/46QPhnU8

iOS log
http://pastebin.com/BqyxL2kG

iOS using wifi
Android using 3g/4g

**Comment by Pro100Andrey** [comment]
@GiacomoSilli please check only audio call

**Comment by GiacomoSilli** [comment]
I'm sorry, what files I have to edit for those settings
I can not find the correct file with this config
Same for android

(I have the same problem with simple call)

**Comment by Pro100Andrey** [comment]
@GiacomoSilli, for set ice server use: https://quickblox.com/developers/Sample-webrtc-android#Set_custom_ICE_servers but quickblox ice server - https://quickblox.com/developers/Sample-webrtc-ios#Set_custom_ICE_servers

**Comment by GiacomoSilli** [comment]
I have found these guides on the site, but do not know in what files i have to include these configurations,

**Comment by Pro100Andrey** [comment]
@GiacomoSilli  call to me from android : room123

**Comment by GiacomoSilli** [comment]
I'm using my account/key, if you can wait some minuts, i restore the originals

**Comment by Pro100Andrey** [comment]
@GiacomoSilli  ok )

**Comment by GiacomoSilli** [comment]
I've downloaded sdk from here
`http://quickblox.com/developers/Sample-webrtc-android`

Running quickblox-videochat-webrtc
I'm in room123, i see user "SharpBlade". its you ?:)
I'm user2

**Comment by Pro100Andrey** [comment]
@GiacomoSilli  no, I'm - user1

**Comment by Pro100Andrey** [comment]
@GiacomoSilli my app settings
```objc
    [QBSettings setAccountKey:@"7yvNe17TnjNUqDoPwfqp"];
    [QBSettings setApplicationID:40718];
    [QBSettings setAuthKey:@"AnB-JpA6r4y6RmS"];
    [QBSettings setAuthSecret:@"3O7Sr5Pg4Qjexwn"];
```

**Comment by Pro100Andrey** [comment]
@GiacomoSilli any updates?

**Comment by GiacomoSilli** [comment]
```
    String APP_ID = "40718";
    String AUTH_KEY = "AnB-JpA6r4y6RmS";
    String AUTH_SECRET = "3O7Sr5Pg4Qjexwn";
    String ACCOUNT_KEY = "7yvNe17TnjNUqDoPwfqp";
```

"error creating new user, please try again"

**Comment by Pro100Andrey** [comment]
@GiacomoSilli please create other user

**Comment by GiacomoSilli** [comment]
Sorry dude, it wont work
I'm trying to create a new user in any way, on 3g/4g/wifi/ , or different rooms or with different name
always
"error creating new user, please try again"

Do you want to try with my keys?

**Comment by Pro100Andrey** [comment]
@GiacomoSilli please remove and install Sample-webrtc-android sample, if you have the same error please provide full logs

**Comment by GiacomoSilli** [comment]
Same error.
http://pastebin.com/LAAYsMvJ

**Comment by Pro100Andrey** [comment]
@GiacomoSilli please check again

**Comment by GiacomoSilli** [comment]
I've installed again sample-videochat-webrtc

Same error

**Comment by Pro100Andrey** [comment]
@GiacomoSilli I will come back to you tomorrow, i need more time for investigation these issues

**Comment by GiacomoSilli** [comment]
Ok thank you for help

**Comment by Pro100Andrey** [comment]
hi @GiacomoSilli, please check only iOS side with 3g/4g

**Comment by GiacomoSilli** [comment]
Hello,
Android 3g/4g to web app working pretty good.
The problem persists using different connections with smartphones.

Do you have any updates about my problem or yours? :)

**Comment by GiacomoSilli** [comment]
Commented 10 minutes ago 
Hello,
Android 3g/4g to web app working pretty good.
The problem persists using different connections with smartphones.

Do you have any updates about my problem or yours? :)

EDIT: I wrote at the same time, amazing.
You want me to try iOS to iOS using 3g/4g?

**Comment by Pro100Andrey** [comment]
@GiacomoSilli, thank you for reporting this. Our QA engineers will reproduce these issues, will keep you posted

**Comment by GiacomoSilli** [comment]
I also tested using two iOS devices with 3g / 4g. Does not work.
I wait your news, thanks

**Comment by GiacomoSilli** [comment]
Update
It does not work on two different wireless networks.
It only works if the devices use the same wifi network

**Comment by Pro100Andrey** [comment]
@GiacomoSilli, we have reproduced this issue, we are going to release new version of the sdk tomorrow, thanks!

**Comment by GiacomoSilli** [comment]
Nice to know, thank you for your work, see u tomorrow.

**Comment by Pro100Andrey** [comment]
@GiacomoSilli i will upload RC 2.3.1 - https://github.com/QuickBlox/quickblox-ios-sdk/tree/develop

**Comment by GiacomoSilli** [comment]
Ok i'm downloading it, i'll give you some info.
What about android?

**Comment by Pro100Andrey** [comment]
This is iOS side issue

**Comment by GiacomoSilli** [comment]
Ok its working pretty good, iOS to Android, both with 4g, good work, thank you

**Comment by Pro100Andrey** [comment]
Thanks!
