### ISSUE TITLE
How to update manually QB message for particuler userid 

### ISSUE THREAD

**Issue by vikrantrajput** [QuickBlox/quickblox-ios-sdk#719]
Hello every one, I am using QB group chat. I have three user in group chat and when I send message and another user receiving then delegates method called proper. But I want to read and delivered to 3rd user manually. For this I am using [API](https://api.quickblox.com/chat/Message.json) with sending parameter 
```objc
param = @{@"read":@"1",@"chat_dialog_id":chatDialogID,@"user_id":@"user_ID",@"message_id":messageID};
```
and get 200 response. But after that when I get all messages form dialog then message contain only two IDs with sender and receive not that iD for which I used the above api. 
Please help I got stuck on this problem

**Comment by VitaliyGuru** [comment]
@vikrantrajput  Unfortunately you can't do this. Message information(read and delivered statuses of the user) can be updated only by this user.

**Comment by vikrantrajput** [comment]
@VitaliyGuru  Thanks for reply. According to our requirement we have to  create dummy user to create group chat or group dialog. I want if I am chatting  with main user then dummy user can also read every message manually. I want to manually set read and delivered status for messages for dummy user. I have his user id as I created that user. How can I do it ? This is my main requirement.
Thanks!

**Comment by VitaliyGuru** [comment]
@vikrantrajput  Unfortunately Quickblox can't match your scenario. Could you expand a little bit on why you need a dummy user? Maybe we can suggest an alternative for you.

**Comment by VitaliyGuru** [comment]
@vikrantrajput, Any updates?
