### ISSUE TITLE
QBMEvent scheduled is not firing (not shown in dashboard too)

### ISSUE THREAD

**Issue by radvansky-tomas** [QuickBlox/quickblox-ios-sdk#72]
My current code in swift:

let protestEvent:QBMEvent = QBMEvent();
                    protestEvent.active = false
                    protestEvent.notificationType = QBMNotificationTypePush
                    protestEvent.usersTagsAny = uniqueString
                    protestEvent.pushType = QBMPushTypeAPNS
                    protestEvent.name = created.fields.objectForKey("title") as? String
                    protestEvent.type = QBMEventTypeFixedDate
                    var dateFormatter = NSDateFormatter()
                    dateFormatter.dateFormat = "yyyy-MM-dd HH:mm:ss ZZZ"
                    protestEvent.date = protestObj.protestScheduledDate
                    protestEvent.isDevelopmentEnvironment = true
                    
                    // custom params
                    let dictPush:NSMutableDictionary = NSMutableDictionary()
                    dictPush.setObject("Message received from Bob", forKey: "message")
                    dictPush.setObject("1", forKey: "ios_badge")
                    
                    var error:NSError?
                    if let sendData:NSData = NSJSONSerialization.dataWithJSONObject(dictPush, options: NSJSONWritingOptions.PrettyPrinted, error: &error)
                    {
                        if let jsonString:NSString = NSString(data: sendData, encoding: NSUTF8StringEncoding)
                        {
                            protestEvent.message = jsonString
                        }
                    }
                    
                    QBRequest.createEvent(protestEvent, successBlock: { (eventResponse:QBResponse!, event:[AnyObject]!) -> Void in
                        println("Event scheduled!")
                        if successBlock != nil
                        {
                            successBlock!(eventResponse: eventResponse,event: event)
                        }
                        }, errorBlock: { (eventError:QBResponse!) -> Void in
                            if errorBlock != nil
                            {
                                errorBlock!(error: eventError)
                            }
                            println(eventError.error.description)
                    })
                    }, errorBlock: { (error:QBResponse!) -> Void in
                        if errorBlock != nil
                        {
                            errorBlock!(error: error)
                        }
                        println(error.error.description)
                })

Is there any chance to get source to iOS SDK ?

**Comment by AndreyMoskvin** [comment]
Right now it is impossible to share sources of iOS SDK. Maybe in future we will make part of sources opened.
Are you still facing this issue?
