### ISSUE TITLE
How to send private message in iOS video Chat (ObjC)

### ISSUE THREAD

**Issue by marshad13** [QuickBlox/quickblox-ios-sdk#720]
I am currently using video demo for my app, i needed to send a message to selected user (single one) during video chat without using APNS, how it can be done, any idea?
"QB-OS" = "iOS 10.1.1"
"QB-SDK" = "iOS 2.9"
"QuickBlox-REST-API-Version" = "0.1.1"
"QuickbloxWebRTC version" = "2.3"

**Comment by Pro100Andrey** [comment]
Hi @marshad13, Use:

See `QBChat.h`:

```objc
/**
 *  Send system message to dialog.
 *
 *  @param message      QBChatMessage instance of message to send.
 *  @param completion   Completion block with failure error.
 */
- (void)sendSystemMessage:(QBChatMessage *)message completion:(nullable QBChatCompletionBlock)completion;

```

for example:

``` objc 
    QBChatMessage *message = [QBChatMessage message];
    message.text = @"Hey";
    message.recipientID = 123;
    
    [[QBChat instance] sendSystemMessage:message completion:^(NSError * _Nullable error) {
        
        if (error) {
            
            NSLog(@"System message sent with error: %@", error);
        }
        else {
            NSLog(@"System message successfully sent");
        }
    }];
```

**Comment by marshad13** [comment]
thanks for such a quick response, let me check it first!

**Comment by marshad13** [comment]
I am able to send message successfully, but this method never called,
- (void)chatDidReceiveSystemMessage:(QBChatMessage *)message
i have also setup QBChat delegates into my view controller. Do i need to add anything else?

**Comment by Pro100Andrey** [comment]
Hi @marshad13,  [[QBChat instance] addDelegate: self<You view controller >]

**Comment by Pro100Andrey** [comment]
@marshad13 Please see documentation  [Chat in dialog](https://quickblox.com/developers/SimpleSample-chat_users-ios#Chat_in_dialog)

**Comment by marshad13** [comment]
I have already added this into my controller, not still not able to get any massage, My code is,

- (void)viewDidLoad {
    [super viewDidLoad];
    
    [[QBChat instance] addDelegate:self];

   .... other code 
}

- (void)sendText {
    QBChatMessage *message = [QBChatMessage message];
    message.text = @"Hey";
    message.recipientID = (NSInteger)recepentId;
    
    [[QBChat instance] sendSystemMessage:message completion:^(NSError * _Nullable error) {
        if (error) {
            [self showScreenMessage:[NSString stringWithFormat:@"System message sent with error: %@", error]];
        } else {
            [self showScreenMessage:@"System message successfully sent"];
        }
    }];
}

#pragma mark QBChatDelegates
- (void)chatDidReceiveSystemMessage:(QBChatMessage *)message{
    NSLog(@"message ;%@", message.text);
    [self showScreenMessage:message.text];
}

By the way, i am connecting with chat in previous view controller and added delegates there too, this method,
- (void)chatDidConnect {}
Called when connected with chat in previous controller, but in next controller where m sending message and i have also added delegates but non called

**Comment by Pro100Andrey** [comment]
@marshad13 please provide full logs from both sides (sender & recipient)

for enable log use code bellow:

```objc
[QBSettings setLogLevel:QBLogLevelDebug];
[QBSettings enableXMPPLogging];
```

**Comment by marshad13** [comment]
Currently m working on single system, here is the log when i send message,
2017-01-07 19:44:15.435 LoomIn[940:307401] [ChatService] Message SNT: <message id="5870febd6b8b99ac030041a8" type="headline" to="12682136551034310675-51943@chat.quickblox.com"><body>Hey h r u????????????????????</body><extraParams xmlns="jabber:client"><moduleIdentifier>SystemNotifications</moduleIdentifier><date_sent>1483800255</date_sent></extraParams></message>
2017-01-07 19:44:15.440 LoomIn[940:307327] [ChatService] StreamManagement: did request acknowledgment
2017-01-07 19:44:16.451738 LoomIn[940:306596] System message successfully sent
2017-01-07 19:44:16.458 LoomIn[940:307401] [ChatService] StreamManagement: did receive acknowledgments for stanza ids count: 2

**Comment by Pro100Andrey** [comment]
Hi @marshad13, please provide full logs from both sides (sender & recipient)

**Comment by marshad13** [comment]
Actually i was able to send text via "QBChatDialog",

QBChatDialog *chatDialog = [[QBChatDialog alloc] initWithDialogID:NULL type:QBChatDialogTypePrivate];
    chatDialog.occupantIDs = @[recepentId];
[QBRequest createDialog:chatDialog successBlock:^(QBResponse *response, QBChatDialog *createdDialog) {
QBChatMessage *message = [QBChatMessage message];
        [message setText:@"Hey there yes i think"];
        message.recipientID = (NSInteger)recepentId;
        //
        NSMutableDictionary *params = [NSMutableDictionary dictionary];
        params[@"save_to_history"] = @NO;
        [message setCustomParameters:params];
        
        [chatDialog sendMessage:message completionBlock:^(NSError * _Nullable error) {
            NSString *msg = @"System message successfully sent";
            [self showScreenMessage:msg];
        }];
 } errorBlock:^(QBResponse *response) {
        NSLog(@"response : %@", (response.success) ? @"Yes" : @"No");
    }];

And receive message via, 
- (void)chatDidReceiveMessage:(QBChatMessage *)message {}

Thanks for ur link,
https://quickblox.com/developers/SimpleSample-chat_users-ios#Chat_in_dialog

**Comment by shoaibHassanAttech** [comment]
@marshad13  did you receive offline message via this code?
because if my chat is disconnected and peer sent me messages, i want to receive them when connected to chat,please guide.
Thanks in advance.
