### ISSUE TITLE
Calling method chatDidReceiveMessage: after sending the message to private dialog

### ISSUE THREAD

**Issue by srgzah** [QuickBlox/quickblox-ios-sdk#724]
When sending messages to private dialog, the device from which the message was sent, does not receive the call.
`- (void)chatDidReceiveMessage:(QBChatMessage *)message;`

How can I find message.ID after sending a message?

**Comment by Pro100Andrey** [comment]
@srgzah message id generated before send message in client side

**Comment by srgzah** [comment]
So, I need to do it myself?

**Comment by srgzah** [comment]
I see...
But what about other fields?
 ```
recipientID: 0			
 dateSent: (null)			
 text: (null)			
 customParameters: (null)			
 attachments: (null)			
 delayed: 0			
 dialogID: (null)			
 read: 0			
 readIDs: (null)			
 deliveredIDs: (null)			
 markable: 0			
 createdAt: (null)			
 updatedAt: (null)
```

**Comment by Pro100Andrey** [comment]
@srgzah  after send message

**Comment by srgzah** [comment]
Ok, thanks.

**Comment by Pro100Andrey** [comment]
@srgzah please close issue if your issue is resolved

**Comment by Pro100Andrey** [comment]
@srgzah Thanks
