### ISSUE TITLE
Problem with retrieving unread messages count

### ISSUE THREAD

**Issue by iOSTestUser** [QuickBlox/quickblox-ios-sdk#725]
Hi, i configured push notification for user chat messages .i am using below code for finding unread messages count.It is working fine when user already open the app.Once user close the app,that time second user send message that time user 1 gets push message,if user1 clicks that message i got the **0** count from quickblox.
 ```swift
func badgeCOunt() -> Uint {
        
        var count:UInt = 0
        let unreadDialogs : NSArray = QMServicesManager.instance().chatService.dialogsMemoryStorage.unreadDialogs() as NSArray
        
        for dialog in unreadDialogs as! [QBChatDialog]{
            count += dialog.unreadMessagesCount
        }
        return count
    }
    
```

**Comment by Raikerian** [comment]
Hi,

use badge count in push notifications if you are using chat alerts (automatic server push notification s). Thats the only way to get badge counter to set the correct unread message counter.
You can't get it from dialog.unreadMessagesCount when app is starting, because memory storage might not load yet.

**Comment by Pro100Andrey** [comment]
Hi @iOSTestUser, any updates ?

**Comment by iOSTestUser** [comment]
in first time when user open app that time also i am not getting chat users list.
```
func dialogs() -> [QBChatDialog]? {
        // Returns dialogs sorted by updatedAt date.
        return QMServicesManager.instance().chatService.dialogsMemoryStorage.dialogsSortByUpdatedAt(withAscending: false)
    }
```

**Comment by Raikerian** [comment]
Yes, after you open an app there are some initialization asynchronous process, which is importing data from CoreData storage to memory storage. Use this delegate to be notified when that process is done:

```objc
/**
 *  Is called when ChatDialogs did load from cache.
 *
 *  @param chatService      instance
 *  @param dialogs          array of QBChatDialogs loaded from cache
 *  @param dialogsUsersIDs  all users from all ChatDialogs
 */
- (void)chatService:(QMChatService *)chatService didLoadChatDialogsFromCache:(NSArray QB_GENERIC(QBChatDialog *) *)dialogs withUsers:(NSSet QB_GENERIC(NSNumber *) *)dialogsUsersIDs;

```

**Comment by Pro100Andrey** [comment]
Hi @iOSTestUser, Any updates?

**Comment by iOSTestUser** [comment]
It is working fine.Thank you
