### ISSUE TITLE
We used cocoa pods to install quickblox and try integrating the simple chat but getting the below error.

### ISSUE THREAD

**Issue by SpeakfreelyApp** [QuickBlox/quickblox-ios-sdk#726]
we are Using QuickBlox (2.9) We used cocoa pods to install quickblox and try integrating the simple chat but getting the below error.
We used cocoa pods to install quickblox and try integrating the simple chat but getting the below error.

/Users/shrishtiinformatics/Desktop/Handychecks/Handychecks/Pods/QMServicesDevelopment/QMDBStorage/QMDBStorage/QMCDRecord/Categories/CoreData/Import/NSNumber+QMCDDataImport.h:9:12: Cannot find interface declaration for 'NSNumber'

Also we tried to run the simple-chat but getting the error below

/Users/shrishtiinformatics/Downloads/quickblox-ios-sdk-master/sample-chat/sample-chat/Pods/QMCVDevelopment/QMChatViewController/QMChatSection/QMChatSection.m:10:9: 'Quickblox/Quickblox.h' file not found

The Entire code is available here for your examination here

https://github.com/ramachandrantc/https---github.com-ramachandrantc-sample-chat

Your help is much appreciated

**Comment by VitaliyGuru** [comment]
@SpeakfreelyApp, Hello.
Could you please show your podfile?

**Comment by SpeakfreelyApp** [comment]
Hi Vitaliy

                   Thanks please find the podfile here

https://github.com/ramachandrantc/https---github.com-ramachandrantc-sample-chat/tree/master/sample-chat/Pods

we have uploaded the entire project in Git so that you could help

Regards

Steve

**Comment by VitaliyGuru** [comment]
@SpeakfreelyApp, Sorry for my inattention.
BTW, I've investigated your project in detail and found the following issues:
1. There are two QuickbloxSDK binaries in your project. The first one from pods and the second one added manually. You should remove the second one.
2. In your project folder (Handychecks), there is [a folder named 'Pods'](https://github.com/ramachandrantc/https---github.com-ramachandrantc-sample-chat/tree/master/sample-chat/Handychecks/Pods). You should remove this folder, cause you already have pods project in your root folder 'sample-chat'. 

Awaiting your updates.

**Comment by shrishti** [comment]
Removed the manually added framework. Also deleted the pods folder from project. Getting errors below

file:///Users/shrishtiinformatics/Desktop/Handychecks/Handychecks/CCResultViewController.xib: warning: Missing file: /Users/shrishtiinformatics/Desktop/Handychecks/Handychecks/CCResultViewController.xib is missing from working copy

Parse Issue Group
/Users/shrishtiinformatics/Desktop/Handychecks/Handychecks/Services/NotificationService.h:19:54: Expected a type
/Users/shrishtiinformatics/Desktop/Handychecks/Handychecks/Services/ServicesManager.h:35:96: Expected ')'
/Users/shrishtiinformatics/Desktop/Handychecks/Handychecks/Services/ServicesManager.h:42:12: Expected ')'
Semantic Issue Group
/Users/shrishtiinformatics/Desktop/Handychecks/Handychecks/Services/ServicesManager.h:15:30: Cannot find interface declaration for 'QMServicesManager', superclass of 'ServicesManager'
/Users/shrishtiinformatics/Desktop/Handychecks/Handychecks/Services/ServicesManager.h:35:85: Unknown type name 'QBUUser'
/Users/shrishtiinformatics/Desktop/Handychecks/Handychecks/Services/ServicesManager.h:35:66: Interface type 'NSArray' cannot be returned by value; did you forget * in 'NSArray'?
/Users/shrishtiinformatics/Desktop/Handychecks/Handychecks/Services/ServicesManager.h:42:1: Interface type 'NSArray' cannot be returned by value; did you forget * in 'NSArray'?
/Users/shrishtiinformatics/Desktop/Handychecks/Handychecks/Services/NotificationService.m:20:22: Property 'instance' not found on object of type 'ServicesManager

**Comment by shrishti** [comment]
latest files  https://github.com/ramachandrantc/chat

**Comment by SpeakfreelyApp** [comment]
Yes, got fixed

thanks

-- 
Regards
Sijo Mon
Technical Head
Shrishti Info Solutions Pvt Ltd
91-8593954829
