### ISSUE TITLE
How to handle attachment messages 

### ISSUE THREAD

**Issue by vikrantrajput** [QuickBlox/quickblox-ios-sdk#727]
Hello everyone, I am working on QB attachments messages. I stuck on point. My problem is when I created QBChatMessage object and attach any attachment like image with using following code `

```objc
NSData *imageData = UIImagePNGRepresentation(attachmentImage);   
[QBRequest TUploadFile:imageData fileName:@"Attachment.JPEG" contentType:@"image/JPEG" isPublic:NO successBlock:^(QBResponse *response, QBCBlob *uploadedBlob) {
  
    NSUInteger uploadedFileID = uploadedBlob.ID;
    // Create chat message with attach
    QBChatMessage *message = [QBChatMessage message]; 
    QBChatAttachment *attachment = QBChatAttachment.new;
    attachment.type = @"image";
    attachment.ID = [NSString stringWithFormat:@"%lu", (unsigned long)uploadedFileID];
    // use 'ID' property to store an ID of a file in Content or CustomObjects modules
    [message setAttachments:@[attachment]];
    // Array to store QBChatMessages
    [self.messages addObject:message];      
    // Method for sending  message
    [_usingChatDialog sendMessage:message completionBlock:^(NSError * _Nullable error) {}];

} statusBlock:^(QBRequest *request, QBRequestStatus *status) {
            // handle progress
} errorBlock:^(QBResponse *response) {
            NSLog(@"error: %@", response.error);
}];
```
I am able to send message after attachment successfully which is time taking. There is time gap between click on send button and successfully sent message in QB server. I can't update my table view until message not successfully sent on server. So now how  can I solve this issue.
Thanks!

**Comment by VitaliyGuru** [comment]
@vikrantrajput , Hello. Do you use QMChatViewController?

**Comment by vikrantrajput** [comment]
@VitaliyGuru Thanks for reply, NO I am using my custom viewController in which having tableview and custom cells.

**Comment by VitaliyGuru** [comment]
@vikrantrajput,
Closing due to [similar issue from you](https://github.com/QuickBlox/quickblox-ios-sdk/issues/728).
