### ISSUE TITLE
QuickBlox attachment Images changing when scrolling in tableview 

### ISSUE THREAD

**Issue by vikrantrajput** [QuickBlox/quickblox-ios-sdk#728]
Hello everyone, I am facing issue also when  showing attachments in tableview cell. When I scrolling tableview, images changes after downloading from message attachment. I am using following code on cellForRowAtIndexPath delegate method. 

```objc
[QBRequest backgroundDownloadFileWithID:[attachment.ID integerValue] successBlock:^(QBResponse * _Nonnull response, NSData * _Nonnull fileData) {
        attachmentCell.attachmentImageView.image = [UIImage imageWithData:fileData];
}
statusBlock:^(QBRequest * _Nonnull request, QBRequestStatus * _Nullable status) {} 
errorBlock:^(QBResponse * _Nonnull response) {}]
```

How I can solve this issue.

**Comment by VitaliyGuru** [comment]
@vikrantrajput  Take a look at your [image attachments handling](https://github.com/QuickBlox/quickblox-ios-sdk/blob/master/sample-chat/sample-chat/ViewController/ChatViewController.m) in SampleChat and at our [QMServices](https://github.com/QuickBlox/q-municate-services-ios/blob/master/QMChatService/QMChatService/QMChatAttachmentService.m). There you can find helpful methods and approaches to make attachments handling as easy as pie.

**Comment by vikrantrajput** [comment]
@VitaliyGuru  thanks for your reply. I am trying to use QMservice and QMChatViewController

**Comment by VitaliyGuru** [comment]
@vikrantrajput If QMChatViewController doesn't suit your needs you can use the approach from it for attachments. As for services - they are really helpful and can simplify your development.

**Comment by vikrantrajput** [comment]
@VitaliyGuru can't we completed my requirement without help from QMChatViewController

**Comment by VitaliyGuru** [comment]
@vikrantrajput, I'm not sure what you mean.

**Comment by VitaliyGuru** [comment]
@vikrantrajput Hello, Any updates?

**Comment by vikrantrajput** [comment]
@VitaliyGuru  I am using url from where I download attachments.
`"http://api.quickblox.com/blobs/" + fileId + "/download?token=" + qbSessionToken;`
But now my main issue is sending attachment time. When I send attachment Its taking long time. I am using following code `        NSData *imageData = UIImagePNGRepresentation(attachmentImage);
    
        [QBRequest TUploadFile:imageData fileName:@"Attachment.JPEG" contentType:@"image/JPEG" isPublic:NO successBlock:^(QBResponse *response, QBCBlob *uploadedBlob) {
            
            NSUInteger uploadedFileID = uploadedBlob.ID;
    
            // Create chat message with attach
            //
            //QBChatMessage *message = [QBChatMessage message];
            
            
             //[kAPP_DELEGATE hideHUD];
            QBChatAttachment *attachment = QBChatAttachment.new;
    
            attachment.type = @"image";
    
            attachment.ID = [NSString stringWithFormat:@"%lu", (unsigned long)uploadedFileID];
            // use 'ID' property to store an ID of a file in Content or CustomObjects modules
    
            [message setAttachments:@[attachment]];
            
            [self.messages addObject:message];
            
         
            
            // Method for sending  message
            [_usingChatDialog sendMessage:message completionBlock:^(NSError * _Nullable error) {
                
                
                //Attachment message
                [activityView hide:YES];
                NSLog(@"message sent  %@", error.description);
                [self.textView setText:@""];
                if(self.messages.count > 0) {
                    
                    // Reload table
                    [self.chatTableView reloadData];
                    
                    [self.chatTableView scrollToRowAtIndexPath:[NSIndexPath indexPathForRow:[self.messages count]-1 inSection:0] atScrollPosition:UITableViewScrollPositionBottom animated:YES];
                    
                    self.isLoadingChatHistory = YES;
                    
                }
                
            }];
    
    
    
        } statusBlock:^(QBRequest *request, QBRequestStatus *status) {
            // handle progress
        }
        errorBlock:^(QBResponse *response)
        {
            NSLog(@"error: %@", response.error);
        }];
` 
Please help this is main issue for me. How can I resolve this.

**Comment by vikrantrajput** [comment]
@VitaliyGuru  is there any solution of my problem

**Comment by VitaliyGuru** [comment]
@vikrantrajput, Uploading is a long task which depends on image size. 
Try to resize images before uploading and sending e.g :

`- (UIImage *)resizedImageFromImage:(UIImage *)image {
    
    CGFloat largestSide = image.size.width > image.size.height ? image.size.width : image.size.height;
    CGFloat scaleCoefficient = largestSide / 560.0f;
    CGSize newSize = CGSizeMake(image.size.width / scaleCoefficient, image.size.height / scaleCoefficient);
    
    UIGraphicsBeginImageContext(newSize);
    
    [image drawInRect:CGRectMake(0, 0, newSize.width, newSize.height)];
    UIImage *resizedImage = UIGraphicsGetImageFromCurrentImageContext();
    
    UIGraphicsEndImageContext();
    
    return resizedImage;
}`

**Comment by VitaliyGuru** [comment]
@vikrantrajput, Hello. Sent concept was just an example. It depends on your needs. You should check image quality before sending and choose `scaleCoefficient` that suit your needs.

**Comment by Pro100Andrey** [comment]
Hi @vikrantrajput, any updates?

**Comment by vikrantrajput** [comment]
@Pro100Andrey  If I have attachment image size of 3-5 mb then Its taking long time. How to use scaleCoefficient as you suggest me. 
Thanks!

**Comment by vikrantrajput** [comment]
@Pro100Andrey  thanks for reply, if I have the attachment image size of 3-4 mb then its taking long time to send/upload. Yes I know that I get image quality as I send on server. what is "scaleCoefficient" how can I use this concept so that uploading time will increase.
Thanks!
