### ISSUE TITLE
Add NSData type Custom parameter

### ISSUE THREAD

**Issue by vikrantrajput** [QuickBlox/quickblox-ios-sdk#729]
Hello everyone, 

I'm sending NSData in custom parameter but it i can not read that data while receiving.

**Comment by Pro100Andrey** [comment]
Hi @vikrantrajput, please provide full logs. For enable log use code bellow:

```objc
[QBSettings setLogLevel:QBLogLevelDebug];
[QBSettings enableXMPPLogging];
```

**Comment by Pro100Andrey** [comment]
Hi @vikrantrajput, Any updates?
