### ISSUE TITLE
Operation could not be completed com.quickblox.chat error -1002

### ISSUE THREAD

**Issue by ErAshu** [QuickBlox/quickblox-ios-sdk#730]
First time login then giving this issue
Operation could not be completed com.quickblox.chat error -1002

**Comment by Pro100Andrey** [comment]
Hi @ErAshu, please provide full logs. For enable log use code bellow:

```objc
[QBSettings setLogLevel:QBLogLevelDebug];
[QBSettings enableXMPPLogging];
```

**Comment by ErAshu** [comment]
Its not coming every time.

**Comment by Pro100Andrey** [comment]
@ErAshu Any updates?
