### ISSUE TITLE
iOS Push notification Error

### ISSUE THREAD

**Issue by ErAshu** [QuickBlox/quickblox-ios-sdk#731]
When app is in background No push notification Got. After open the app, Custom notification showing.

I have upload .pem file here. 
https://admin.quickblox.com/apps/XXXXX/service/push-notifications/settings
<img width="1052" alt="screen shot 2017-01-23 at 4 06 30 pm" src="https://cloud.githubusercontent.com/assets/4178384/22200717/48b78ebc-e186-11e6-9f65-12984e624c1b.png">

In https://admin.quickblox.com/apps/XXXXX/service/push-notifications/subscriptions 
i can see the list of subscribed users.
In Queue Tab, https://admin.quickblox.com/apps/XXXXX/service/push-notifications/queue
Not got any list of message.

In Send tab, https://admin.quickblox.com/apps/XXXXX/service/push-notifications
When i send test push notification, i got the notification on device.

---DEBUG---
- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo
**NOT ENTER IN THIS DELEGATE**

Please let me know if any changes required.

**Comment by VitaliyGuru** [comment]
Have you followed [this guide](http://quickblox.com/developers/Chat#Alerts) ?

You need to enable automatic chat alerts (chat alerts are offline push notifications that you need) in your admin panel.
Keep in mind, that user should be disconnected from chat in order to receive them.

**Comment by ErAshu** [comment]
Yes, I have setup this. 
See my Screenshot.
<img width="1058" alt="screen shot 2017-01-24 at 2 51 02 pm" src="https://cloud.githubusercontent.com/assets/4178384/22241248/938ffdac-e244-11e6-9e8f-12edcf7d8dbd.png">

**Delegate Method in App Delegate**

- (void)applicationWillEnterForeground:(UIApplication *)application {
   // Login to QuickBlox Chat
    [ServicesManager.instance.chatService connectWithCompletionBlock:nil];
}

- (void)applicationWillTerminate:(UIApplication *)application {
    // Logout from chat
    //
    [ServicesManager.instance.chatService disconnectWithCompletionBlock:nil];
}

Please help me out.

**Comment by VitaliyGuru** [comment]
@ErAshu, You should disconnect from chat not only when app is terminated but also when app is entered in the background.

```objective-c
- (void)applicationDidEnterBackground:(UIApplication *)application {
    
    [ServicesManager.instance.chatService disconnectWithCompletionBlock:nil]
}
```

**Comment by ErAshu** [comment]
Ohhh..  I missed that delegate. 
Now i am able to receive Push chat.

One more thing,
ios 2 ios - Receive Push when app in Background
Android 2 iOS -  Receive Push when app in Background
**ios 2 Android  - Not receive on Android App when app in Background**

Is anything missed on android side or iOS side?

**Comment by VitaliyGuru** [comment]
@ErAshu , please create a separate issue. 
Closed this as resolved.
