### ISSUE TITLE
GCM Notification not receive on Android

### ISSUE THREAD

**Issue by ErAshu** [QuickBlox/quickblox-ios-sdk#732]
iOS 2 iOS Push notification Receive when app is in BackGround and Android 2 iOS push notification receive on iOS when app is in background.
But
**ios 2 Android - Not receive on Android App when app in Background**

**Comment by VitaliyGuru** [comment]
@ErAshu, Hello. If with iOS side is everything OK, could you please create issue in [Android Repo](https://github.com/QuickBlox/quickblox-android-sdk)?
