### ISSUE TITLE
Pod: Error installing QuickBlox

### ISSUE THREAD

**Issue by nikunjazilen** [QuickBlox/quickblox-ios-sdk#734]
Hi,
I trying to install below pods but its give me below error. So please help me to resolve this issue.
pod 'Quickblox-WebRTC', '~> 2.3.1'

pod 'QuickBlox', '~> 2.9'

```logos
Error:--------------------------------------------------------------------------------
!] Error installing QuickBlox
[!] /usr/bin/unzip /var/folders/x5/3zyfh1pn6gg2wyfyql9m4hqr0000gp/T/d20170125-1822-1qx8rk2/file.zip -d /var/folders/x5/3zyfh1pn6gg2wyfyql9m4hqr0000gp/T/d20170125-1822-1qx8rk2

Archive:  /var/folders/x5/3zyfh1pn6gg2wyfyql9m4hqr0000gp/T/d20170125-1822-1qx8rk2/file.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /var/folders/x5/3zyfh1pn6gg2wyfyql9m4hqr0000gp/T/d20170125-1822-1qx8rk2/file.zip or
        /var/folders/x5/3zyfh1pn6gg2wyfyql9m4hqr0000gp/T/d20170125-1822-1qx8rk2/file.zip.zip, and cannot find /var/folders/x5/3zyfh1pn6gg2wyfyql9m4hqr0000gp/T/d20170125-1822-1qx8rk2/file.zip.ZIP, period.

```
Best Regards,
Nikunj Jadav

**Comment by Pro100Andrey** [comment]
hi @nikunjazilen, try this:

```bash
rm -rf "${HOME}/Library/Caches/CocoaPods"
rm -rf "`pwd`/Pods/"
pod update
```

**Comment by nikunjazilen** [comment]
Hi Andrey,
Thanks for the feedback. I tried this above one but its not working same error occurred.

**Comment by Pro100Andrey** [comment]
@nikunjazilen, please use verbose flag and provide full logs

```bash
pod update --verbose
```

**Comment by Pro100Andrey** [comment]
Hi @nikunjazilen Any  updates?

**Comment by nikunjazilen** [comment]
Hi Andrey,
Please see the below errors after used the command pod update --verbose
------------------------------------
Update all pods
  Preparing

Updating local specs repositories

Updating spec repo `master`

CocoaPods 1.2.0.rc.1 is available.
To update use: `sudo gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.2.0.rc.1


Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods-VideoConference`: (``)

Finding Podfile changes
  A QuickBlox
  A Quickblox-WebRTC

Resolving dependencies of `Podfile`

Comparing resolved specification to the sandbox manifest
  A QuickBlox
  A Quickblox-WebRTC

Downloading dependencies

-> Installing QuickBlox (2.9.1)
 > Http download
   $ /usr/bin/curl -f -L -o /var/folders/x5/3zyfh1pn6gg2wyfyql9m4hqr0000gp/T/d20170127-1212-iro2tg/file.zip
   http://sdk.quickblox.com/ios/iOS-QuickBlox-SDK-2.9.1.zip --create-dirs --netrc-optional
     % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                    Dload  Upload   Total   Spent    Left  Speed
   100  5086    0  5086    0     0   583k      0 --:--:-- --:--:-- --:--:--  620k
   $ /usr/bin/unzip /var/folders/x5/3zyfh1pn6gg2wyfyql9m4hqr0000gp/T/d20170127-1212-iro2tg/file.zip -d
   /var/folders/x5/3zyfh1pn6gg2wyfyql9m4hqr0000gp/T/d20170127-1212-iro2tg
   Archive:  /var/folders/x5/3zyfh1pn6gg2wyfyql9m4hqr0000gp/T/d20170127-1212-iro2tg/file.zip
     End-of-central-directory signature not found.  Either this file is not
     a zipfile, or it constitutes one disk of a multi-part archive.  In the
     latter case the central directory and zipfile comment will be found on
     the last disk(s) of this archive.
   unzip:  cannot find zipfile directory in one of /var/folders/x5/3zyfh1pn6gg2wyfyql9m4hqr0000gp/T/d20170127-1212-iro2tg/file.zip or
           /var/folders/x5/3zyfh1pn6gg2wyfyql9m4hqr0000gp/T/d20170127-1212-iro2tg/file.zip.zip, and cannot find /var/folders/x5/3zyfh1pn6gg2wyfyql9m4hqr0000gp/T/d20170127-1212-iro2tg/file.zip.ZIP, period.

[!] Error installing QuickBlox
[!] /usr/bin/unzip /var/folders/x5/3zyfh1pn6gg2wyfyql9m4hqr0000gp/T/d20170127-1212-iro2tg/file.zip -d /var/folders/x5/3zyfh1pn6gg2wyfyql9m4hqr0000gp/T/d20170127-1212-iro2tg

Archive:  /var/folders/x5/3zyfh1pn6gg2wyfyql9m4hqr0000gp/T/d20170127-1212-iro2tg/file.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /var/folders/x5/3zyfh1pn6gg2wyfyql9m4hqr0000gp/T/d20170127-1212-iro2tg/file.zip or
        /var/folders/x5/3zyfh1pn6gg2wyfyql9m4hqr0000gp/T/d20170127-1212-iro2tg/file.zip.zip, and cannot find /var/folders/x5/3zyfh1pn6gg2wyfyql9m4hqr0000gp/T/d20170127-1212-iro2tg/file.zip.ZIP, period.


/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/downloader.rb:142:in `rescue in execute_command'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/downloader.rb:140:in `execute_command'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-downloader-1.1.3/lib/cocoapods-downloader/base.rb:154:in `block in executable'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-downloader-1.1.3/lib/cocoapods-downloader/http.rb:101:in `extract_with_type'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-downloader-1.1.3/lib/cocoapods-downloader/http.rb:28:in `download!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-downloader-1.1.3/lib/cocoapods-downloader/base.rb:82:in `block in download'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/downloader.rb:157:in `block in ui_action'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/downloader.rb:156:in `ui_action'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-downloader-1.1.3/lib/cocoapods-downloader/base.rb:80:in `download'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/downloader.rb:108:in `download_source'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/downloader.rb:75:in `download_request'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/downloader/cache.rb:171:in `download'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/downloader/cache.rb:154:in `block in uncached_pod'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/downloader/cache.rb:181:in `call'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/downloader/cache.rb:181:in `in_tmpdir'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/downloader/cache.rb:153:in `uncached_pod'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/downloader/cache.rb:33:in `download_pod'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/downloader.rb:42:in `download'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/pod_source_installer.rb:120:in `download_source'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/pod_source_installer.rb:60:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:355:in `install_source_of_pod'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:322:in `block (2 levels) in install_pod_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:85:in `titled_section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:321:in `block in install_pod_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:313:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:313:in `install_pod_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:159:in `block in download_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:157:in `download_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:111:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/command/update.rb:60:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'

Please resolve the issue.
