### ISSUE TITLE
Email has already been taken

### ISSUE THREAD

**Issue by godwincharan** [QuickBlox/quickblox-ios-sdk#738]
I am using Facebook token for logging into quickblox.
I get this weird error.

```objc
[QBCore] Response error reasons: {
    errors =     {
        email =         (
            "has already been taken"
        );
    };
}
```

This is only logging in. Not sign up.
User can anytime log out and log in to the application right.

There seems to be bug in this.

**Comment by VitaliyGuru** [comment]
@godwincharan, Hello. Could you please provide full logs. 
Could you please enable full logs and send us this information?

```
[QBSettings setLogLevel:QBLogLevelDebug];
```

**Comment by godwincharan** [comment]
Using of following code will give the above error.
- (void)viewDidLoad {
    [super viewDidLoad];
   
    FBSDKLoginButton *loginButton = [[FBSDKLoginButton alloc] init];
    loginButton.center = self.view.center;
    [loginButton setLoginBehavior:FBSDKLoginBehaviorWeb];
    [loginButton setDelegate:self];
    [self.view addSubview:loginButton];
}

#pragma mark -FBSDKLoginButtonDelegate
- (void)  loginButton:(FBSDKLoginButton *)loginButton didCompleteWithResult:(FBSDKLoginManagerLoginResult *)result error:(NSError *)error{
    if( [result isCancelled] == NO && error == nil){
        [QBRequest logInWithSocialProvider:@"facebook"  accessToken:[[result token] tokenString]
                            accessTokenSecret:nil
                          successBlock:^(QBResponse * _Nonnull response, QBUUser * _Nullable user) {
            //sucess
    } errorBlock:^(QBResponse * _Nonnull response) {
            //error
    }];
    }

**Comment by VitaliyGuru** [comment]
@godwincharan, Hello. Are you sure that email that you're getting from facebook has not been already taken by other registered user?

**Comment by Pro100Andrey** [comment]
@godwincharan any updates?
