### ISSUE TITLE
App Archive Validate issue

### ISSUE THREAD

**Issue by ErAshu** [QuickBlox/quickblox-ios-sdk#740]
Hi Quickblox Team,
I have integrated QuickBlox in my project and when i am going to upload to app store getting 3 issues. Please find the below attachment. Kindly help me out so that i upload this on app store.

1) **iTunes Store operation failed.**
Unsupported Architectures. The executable for Docquity.app/Frameworks/Quickblox.framework contains unsupported architectures '[x86_64, i386]'.

2) **iTunes Store operation failed.**
Invalid Segment Alignment. The app binary at 'Docquity.app/Frameworks/Quickblox.framework/Quickblox' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version.

3) **iTunes Store operation failed.**
The binary is invalid. The encryption info in the LC_ENCRYPTION_INFO load command is either missing or invalid, or the binary is already encrypted. This binary does not seem to have been built with Apple's linker.

<img width="586" alt="screen shot 2017-01-30 at 3 35 31 pm" src="https://cloud.githubusercontent.com/assets/4178384/22419213/6e4b7bee-e702-11e6-92c7-3bd6db58d182.png">

**Comment by VitaliyGuru** [comment]
Hello @ErAshu , What Xcode and SDK versions do you use?

**Comment by ErAshu** [comment]
<img width="529" alt="screen shot 2017-01-30 at 3 43 25 pm" src="https://cloud.githubusercontent.com/assets/4178384/22419303/e0ae4252-e702-11e6-8c89-958a50e5bb67.png">

**Comment by ErAshu** [comment]
How to check QB SDK Version. I had download by PODFILE

**Comment by Pro100Andrey** [comment]
hi @ErAshu, please read https://quickblox.com/developers/IOS-how-to-connect-Quickblox-framework

section https://quickblox.com/developers/IOS-how-to-connect-Quickblox-framework#Run_Script_Phase_for_Dynamic_framework

**Comment by Pro100Andrey** [comment]
@ErAshu Any updates?

**Comment by ErAshu** [comment]
Yes, Now validation Success...

**Comment by ErAshu** [comment]
Thanks a lot QBTeam.
