### ISSUE TITLE
How to implement that dialog owner can delete other users in that chat dialog.

### ISSUE THREAD

**Issue by ajay2c9** [QuickBlox/quickblox-ios-sdk#743]
Hi,
I am using the Quickblox in my app. I have a group chat . Chat dialog owner want to delete the other users from the chat. 
 Please give suggestion to implement that dialog owner can delete other users from that chat dialog.

Thank you

**Comment by Pro100Andrey** [comment]
Hi @ajay2c9, Use [Update group dialog](https://quickblox.com/developers/SimpleSample-chat_users-ios#Update_group_dialog)
The following rules are applied if dialog's type is 2(GROUP):

* Any user from `occupants_ids` can add other users.
* Any user from `occupants_ids` can remove only himself.
* Only dialog's creator(`owner`) can remove any users from `occupants_ids`.
The following rules are applied if dialog's type is 1(PUBLIC_GROUP):

Only dialog’s owner can update it.
User can update group chat dialog name, add new occupants or leave this group chat. To add more occupants use `push` operator. To leave group chat (remove yourself) - use `pull` operator:

for example (from documentation):

```objc
QBChatDialog *updateDialog = [[QBChatDialog alloc] initWithDialogID:@"53aac645535c12bd3b008a40" type:QBChatDialogTypeGroup];
updateDialog.pullOccupantsIDs = @[@"300"];
updateDialog.name = @"school friends";
 
[QBRequest updateDialog:updateDialog successBlock:^(QBResponse *responce, QBChatDialog *dialog) {
 
} errorBlock:^(QBResponse *response) {
 
}];
```

**Comment by Pro100Andrey** [comment]
@ajay2c9 any updates?

**Comment by ajay2c9** [comment]
Thank you for reply. I am working on this.If any issues i will get back to you
