### ISSUE TITLE
Gif and Custom keyboards are not working.

### ISSUE THREAD

**Issue by ajay2c9** [QuickBlox/quickblox-ios-sdk#744]
Hi,
I am using the Quickblox in my app. I am using QMChatViewController as chat. In this Gif and Custom keyboards are not working.
Please give suggestion for implementing the Gif and Custom keyboards in Chat. when custom keyboard is opened text entering field is displaying. how to implement the chat without getting any issues while changing the keyboard to gif Keyboard or custom keyboard  

Thank you

**Comment by Pro100Andrey** [comment]
https://github.com/QuickBlox/quickblox-ios-sdk/issues/746

**Comment by VitaliyGuru** [comment]
@ajay2c9  Could you please expand a little bit on what you're trying to implement? Code and additional information will be helpful.
