### ISSUE TITLE
How to implement the video posting and gif posting in Quickblox.

### ISSUE THREAD

**Issue by ajay2c9** [QuickBlox/quickblox-ios-sdk#746]
Hi,
We are using the quickblox in my app. Client requirement is to post the Videos and Gifs in the Chat. How to implementing Gif and Video posting in Chat.
Please give suggestions.

Thank you

**Comment by VitaliyGuru** [comment]
@ajay2c9, Hello. This feature is in development. For now, you can use the [branch of QMServices](https://github.com/QuickBlox/q-municate-services-ios/tree/feature/mediaAttachments).

**Comment by Pro100Andrey** [comment]
HI @ajay2c9, any updates ?

**Comment by ajay2c9** [comment]
Hi, i will work on this.If any issues i will get back to you. If any updates regarding this pl tell me.

Thank you

**Comment by abhishek33u** [comment]
Hi any update because its very urgent .
