### ISSUE TITLE
QuickBlox IOS SDK App Store Listing Error

### ISSUE THREAD

**Issue by SpeakfreelyApp** [QuickBlox/quickblox-ios-sdk#747]
we couldn't upload latest build to app store getting below listed  error message
Could you Please Help

ERROR ITMS-90087: "Unsupported Architectures. The executable for OurGreatChat.app/Frameworks/Quickblox.framework contains unsupported architectures '[x86_64]'."
ERROR ITMS-90087: "Unsupported Architectures. The executable for OurGreatChat.app/Frameworks/Quickblox.framework contains unsupported architectures '[x86_64]'."

ERROR ITMS-90209: "Invalid Segment Alignment. The app binary at 'OurGreatChat.app/Frameworks/Quickblox.framework/Quickblox' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version."
ERROR ITMS-90209: "Invalid Segment Alignment. The app binary at 'OurGreatChat.app/Frameworks/Quickblox.framework/Quickblox' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version."

ERROR ITMS-90125: "The binary is invalid. The encryption info in the LC_ENCRYPTION_INFO load command is either missing or invalid, or the binary is already encrypted. This binary does not seem to have been built with Apple's linker."

ERROR ITMS-90125: "The binary is invalid. The encryption info in the LC_ENCRYPTION_INFO load command is either missing or invalid, or the binary is already encrypted. This binary does not seem to have been built with Apple's linker."

WARNING ITMS-90080: "The executable 'Payload/OurGreatChat.app/Frameworks/Quickblox.framework' is not a Position Independent Executable. Please ensure that your build settings are configured to create PIE executables.

**Comment by VitaliyGuru** [comment]
@SpeakfreelyApp, Hello. Please read [additional notes before submitting](https://quickblox.com/developers/IOS-how-to-connect-Quickblox-framework#Run_Script_Phase_for_Dynamic_framework)

**Comment by Pro100Andrey** [comment]
Hi @SpeakfreelyApp, Any updates?

**Comment by SpeakfreelyApp** [comment]
Thanks Andrey we will try and let you know                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: andreySent: Saturday, 4 February 2017 14:06To: QuickBlox/quickblox-ios-sdkReply To: QuickBlox/quickblox-ios-sdkCc: SpeakfreelyApp; MentionSubject: Re: [QuickBlox/quickblox-ios-sdk] QuickBlox IOS SDK App Store Listing Error (#747)Hi @SpeakfreelyApp, Any updates?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/QuickBlox/quickblox-ios-sdk","title":"QuickBlox/quickblox-ios-sdk","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/QuickBlox/quickblox-ios-sdk"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Pro100Andrey in #747: Hi @SpeakfreelyApp, Any updates?"}],"action":{"name":"View Issue","url":"https://github.com/QuickBlox/quickblox-ios-sdk/issues/747#issuecomment-277433157"}}}

**Comment by Pro100Andrey** [comment]
Hi @SpeakfreelyApp, Any updates ?

**Comment by Allan-Nava** [comment]
I have this problem when I i try to upload the Archive Release.
> ERROR ITMS-90087: "Unsupported Architectures. The executable for Sportube.app/Frameworks/GoogleCast.framework contains unsupported architectures '[x86_64, i386]'."

I use this script:
```
APP_PATH="${TARGET_BUILD_DIR}/${WRAPPER_NAME}"

# This script loops through the frameworks embedded in the application and
# removes unused architectures.
find "$APP_PATH" -name '*.framework' -type d | while read -r FRAMEWORK
do
    FRAMEWORK_EXECUTABLE_NAME=$(defaults read "$FRAMEWORK/Info.plist" CFBundleExecutable)
    FRAMEWORK_EXECUTABLE_PATH="$FRAMEWORK/$FRAMEWORK_EXECUTABLE_NAME"
    echo "Executable is $FRAMEWORK_EXECUTABLE_PATH"

    EXTRACTED_ARCHS=()

    for ARCH in $ARCHS
    do
        echo "Extracting $ARCH from $FRAMEWORK_EXECUTABLE_NAME"
        lipo -extract "$ARCH" "$FRAMEWORK_EXECUTABLE_PATH" -o "$FRAMEWORK_EXECUTABLE_PATH-$ARCH"
        EXTRACTED_ARCHS+=("$FRAMEWORK_EXECUTABLE_PATH-$ARCH")
    done

    echo "Merging extracted architectures: ${ARCHS}"
    lipo -o "$FRAMEWORK_EXECUTABLE_PATH-merged" -create "${EXTRACTED_ARCHS[@]}"
    rm "${EXTRACTED_ARCHS[@]}"

    echo "Replacing original executable with thinned version"
    rm "$FRAMEWORK_EXECUTABLE_PATH"
    mv "$FRAMEWORK_EXECUTABLE_PATH-merged" "$FRAMEWORK_EXECUTABLE_PATH"

done
```

I use ionic cordova build ios --release and it works "build succeeded", but when I try to upload to app store I have this problem:
> ERROR ITMS-90087: "Unsupported Architectures. The executable for Sportube.app/Frameworks/GoogleCast.framework contains unsupported architectures '[x86_64, i386]'."
