### ISSUE TITLE
QuickbloxWebRTC 2.4  Core.currentUser alway is nil

### ISSUE THREAD

**Issue by KloversOrg** [QuickBlox/quickblox-ios-sdk#748]
Hi All Friends.
  QuickbloxWebRTC 2.4  Core.currentUser alway is nil. Alway is new open app  , i can store currentUser use after
Log currentUser
sample-videochat-webrtc[612:80974] 
  ```logos
[QBUUser]:
  ID:23556213
  created at:2017-02-03 09:48:46 +0000
  updated at:2017-02-04 02:45:07 +0000
  externalUserID:0
  blobID:0
  facebookID:(null)
  twitterID:(null)
  twitterDigitsID:(null)
  full name:somkid2
  email:(null)
  login:99C53146-9B70-4C60-A6A9-B073732CD7C5
  phone:(null)
  tags:(
    test
)
  lastRequestAt:2017-02-04 02:45:07 +0000
  customData:(null)
  website:(null)

```
Thx.

**Comment by Pro100Andrey** [comment]
Hi @KloversOrg, please provide full logs. For enable logs use code bellow:

```objc

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
...
    [QBSettings setLogLevel:QBLogLevelDebug];
    [QBSettings enableXMPPLogging];
...
}
```

**Comment by KloversOrg** [comment]
Thx. Pro100Andrey
Full Log
2017-02-05 12:21:26.152 rtc::[RTCClient] x86_64, 10.2, SDK: 2.4, webrtc: 16262
2017-02-05 12:21:26.158 rtc::[RTCClient] Initializing SSL...
2017-02-05 12:21:26.158 rtc::[RTCClient] Wating signaling channel
2017-02-05 12:21:26.208 sample-videochat-webrtc[26217:432146] [QBCore] Request URL:https://api.quickblox.com/account_settings.json
2017-02-05 12:21:26.209 sample-videochat-webrtc[26217:432146] [QBCore] Request method: GET
2017-02-05 12:21:26.209 sample-videochat-webrtc[26217:432146] [QBCore] Request parameters:(null)
2017-02-05 12:21:26.209 sample-videochat-webrtc[26217:432146] [QBCore] Request headers: {
    "Accept-Language" = "en;q=1";
    "QB-Account-Key" = 5HhKAkvTeQFHkApZgGez;
    "QB-OS" = "iOS 10.2";
    "QB-SDK" = "iOS 2.9.1";
    "QB-Token" = 3ddf5db877bd985ac74bc9945f81ab14e000cb32;
    "QuickBlox-REST-API-Version" = "0.1.1";
    "User-Agent" = "sample-videochat-webrtc/1.4 (iPhone; iOS 10.2; Scale/2.00)";
}
2017-02-05 12:21:27.671 sample-videochat-webrtc[26217:432162] [QBCore] Response headers: {
    "Access-Control-Allow-Origin" = "*";
    "Cache-Control" = "max-age=0, private, must-revalidate";
    Connection = "keep-alive";
    "Content-Length" = 175;
    "Content-Type" = "application/json; charset=utf-8";
    Date = "Sun, 05 Feb 2017 05:21:28 GMT";
    Etag = "\"4e83beafaef5496f1b86cf799eb35245\"";
    "QuickBlox-REST-API-Version" = "0.1.1";
    Server = "openresty/1.9.15.1";
    Status = "304 Not Modified";
    "Strict-Transport-Security" = "max-age=15768000;";
    "X-Rack-Cache" = miss;
    "X-Request-Id" = e699c3fac4c00b895ecd51cc9d7bdc9e;
    "X-Runtime" = "0.006883";
    "X-UA-Compatible" = "IE=Edge,chrome=1";
}
2017-02-05 12:21:27.672 sample-videochat-webrtc[26217:432162] [QBCore] Response object: {
    "account_id" = 54591;
    "api_endpoint" = "https://api.quickblox.com";
    "chat_endpoint" = "chat.quickblox.com";
    "s3_bucket_name" = qbprod;
    "turnserver_endpoint" = "turnserver.quickblox.com";
}
2017-02-05 12:21:27.675 sample-videochat-webrtc[26217:432162] [Core] accountSettings: 
 apiEndpoint: https://api.quickblox.com
 chatEndpoint: chat.quickblox.com, 
 turnServerEndpoint: turnserver.quickblox.com, 
 S3BucketName: qbprod, 
 lastCheckDate: 2017-02-05 05:21:27 +0000
2017-02-05 12:21:27.678 sample-videochat-webrtc[26217:432162] [QBCore] Request URL:https://api.quickblox.com/session.json
2017-02-05 12:21:27.678 sample-videochat-webrtc[26217:432162] [QBCore] Request method: POST
2017-02-05 12:21:27.678 sample-videochat-webrtc[26217:432162] [QBCore] Request parameters:{
    "application_id" = 52018;
    "auth_key" = Rrzwk6ZywCwrmkj;
    nonce = 487;
    signature = 150d00eb228925ea566bfcbbb3c2cce8317ca833;
    timestamp = 1486272087;
    user =     {
        login = "1CBD1F14-7038-44F2-823F-943CE78AD63D";
        password = x6Bt0VDy5;
    };
}
2017-02-05 12:21:27.679 sample-videochat-webrtc[26217:432162] [QBCore] Request headers: {
    "Accept-Language" = "en;q=1";
    "Content-Type" = "application/x-www-form-urlencoded";
    "QB-OS" = "iOS 10.2";
    "QB-SDK" = "iOS 2.9.1";
    "QB-Token" = 3ddf5db877bd985ac74bc9945f81ab14e000cb32;
    "QuickBlox-REST-API-Version" = "0.1.1";
    "User-Agent" = "sample-videochat-webrtc/1.4 (iPhone; iOS 10.2; Scale/2.00)";
}
2017-02-05 12:21:28.976 sample-videochat-webrtc[26217:432162] [QBCore] Response headers: {
    "Access-Control-Allow-Origin" = "*";
    "Cache-Control" = "max-age=0, private, must-revalidate";
    Connection = "keep-alive";
    "Content-Length" = 264;
    "Content-Type" = "application/json; charset=utf-8";
    Date = "Sun, 05 Feb 2017 05:21:29 GMT";
    Etag = "\"73f75d9a1d366aa4dea52ea0b3fc6bfc\"";
    "QB-Token-ExpirationDate" = "2017-02-05 07:21:29 UTC";
    "QuickBlox-REST-API-Version" = "0.1.1";
    Server = "openresty/1.9.15.1";
    Status = "201 Created";
    "Strict-Transport-Security" = "max-age=15768000;";
    "X-Rack-Cache" = "invalidate, pass";
    "X-Request-Id" = 4a6e8172bbc12eea358810be69c1a99e;
    "X-Runtime" = "0.020594";
    "X-UA-Compatible" = "IE=Edge,chrome=1";
}
2017-02-05 12:21:28.989 sample-videochat-webrtc[26217:432162] [QBCore] Response object: {
    session =     {
        "_id" = 5896b659a28f9abff7000009;
        "application_id" = 52018;
        "created_at" = "2017-02-05T05:21:29Z";
        "device_id" = 0;
        id = 30414;
        nonce = 487;
        token = 95141f0f90bbd622baced49d77b0302c8c00cb32;
        ts = 1486272087;
        "updated_at" = "2017-02-05T05:21:29Z";
        "user_id" = 23593955;
    };
}
2017-02-05 12:21:28.996 sample-videochat-webrtc[26217:432162] [QBCore] Request URL:https://api.quickblox.com/login.json
2017-02-05 12:21:28.996 sample-videochat-webrtc[26217:432162] [QBCore] Request method: POST
2017-02-05 12:21:28.996 sample-videochat-webrtc[26217:432162] [QBCore] Request parameters:{
    login = "1CBD1F14-7038-44F2-823F-943CE78AD63D";
    password = x6Bt0VDy5;
}
2017-02-05 12:21:28.997 sample-videochat-webrtc[26217:432162] [QBCore] Request headers: {
    "Accept-Language" = "en;q=1";
    "Content-Type" = "application/x-www-form-urlencoded";
    "QB-OS" = "iOS 10.2";
    "QB-SDK" = "iOS 2.9.1";
    "QB-Token" = 95141f0f90bbd622baced49d77b0302c8c00cb32;
    "QuickBlox-REST-API-Version" = "0.1.1";
    "User-Agent" = "sample-videochat-webrtc/1.4 (iPhone; iOS 10.2; Scale/2.00)";
}
2017-02-05 12:21:29.378 sample-videochat-webrtc[26217:432157] [QBCore] Response headers: {
    "Access-Control-Allow-Origin" = "*";
    "Cache-Control" = "no-cache";
    Connection = "keep-alive";
    "Content-Length" = 403;
    "Content-Type" = "application/json; charset=utf-8";
    Date = "Sun, 05 Feb 2017 05:21:29 GMT";
    "QB-Token-ExpirationDate" = "2017-02-05 07:21:29 UTC";
    "QuickBlox-REST-API-Version" = "0.1.1";
    Server = "openresty/1.9.15.1";
    Status = "202 Accepted";
    "X-Rack-Cache" = "invalidate, pass";
    "X-Request-Id" = f4eb319f6ad7083b9e13347d8b1c2505;
    "X-Runtime" = "0.036268";
    "X-UA-Compatible" = "IE=Edge,chrome=1";
}
2017-02-05 12:21:29.379 sample-videochat-webrtc[26217:432157] [QBCore] Response object: {
    user =     {
        "blob_id" = "<null>";
        "created_at" = "2017-02-04T00:48:23Z";
        "custom_data" = "<null>";
        email = "<null>";
        "external_user_id" = "<null>";
        "facebook_id" = "<null>";
        "full_name" = somkid3;
        id = 23593955;
        "last_request_at" = "2017-02-05T05:21:29Z";
        login = "1CBD1F14-7038-44F2-823F-943CE78AD63D";
        "owner_id" = 54591;
        phone = "<null>";
        "twitter_digits_id" = "<null>";
        "twitter_id" = "<null>";
        "updated_at" = "2017-02-04T02:18:46Z";
        "user_tags" = test;
        website = "<null>";
    };
}
2017-02-05 12:21:52.221 sample-videochat-webrtc[26217:432077] 
  [QBUUser]:
  ID:23593955
  created at:2017-02-04 00:48:23 +0000
  updated at:2017-02-04 02:18:46 +0000
  externalUserID:0
  blobID:0
  facebookID:(null)
  twitterID:(null)
  twitterDigitsID:(null)
  full name:somkid3
  email:(null)
  login:1CBD1F14-7038-44F2-823F-943CE78AD63D
  phone:(null)
  tags:(
    test
)
  lastRequestAt:2017-02-05 05:21:29 +0000
  customData:(null)
  website:(null)

**Comment by Pro100Andrey** [comment]
Hi @KloversOrg, I have tested it, and this issue is not reproducible in our sample, please provide steps for reproduce this issue.

```logos
2017-02-05 11:15:37.304 rtc::[RTCClient] x86_64, 10.2, SDK: 2.4, webrtc: 16262
2017-02-05 11:15:37.307 rtc::[RTCClient] Initializing SSL...
2017-02-05 11:15:37.307 rtc::[RTCClient] Wating signaling channel

DEBUG CONSOLE
(lldb) po [[QBCore instance] currentUser]

  [QBUUser]:
  ID:23645188
  created at:2017-02-05 09:12:09 +0000
  updated at:2017-02-05 09:12:09 +0000
  externalUserID:0
  blobID:0
  facebookID:(null)
  twitterID:(null)
  twitterDigitsID:(null)
  full name:test
  email:(null)
  login:AB632CA3-2FD0-46EB-B36C-75F3ABCA9C4E
  phone:(null)
  tags:(
    test
)
  lastRequestAt:(null)
  customData:(null)
  website:(null)

```

**Comment by Pro100Andrey** [comment]
Hi @KloversOrg Any updates ?

**Comment by vineeshtp** [comment]
I have the same issue
