### ISSUE TITLE
User Block Unblock

### ISSUE THREAD

**Issue by ErAshu** [QuickBlox/quickblox-ios-sdk#749]
Hi,
How can we block and unblock any user from quickblox? Can we apply it for cross platform?

**Comment by VitaliyGuru** [comment]
@ErAshu, Hello. Take a look at out privacy [list documentation](https://quickblox.com/developers/SimpleSample-chat_users-ios#Privacy_list)

**Comment by Pro100Andrey** [comment]
Hi @ErAshu, Any updates?

**Comment by VitaliyGuru** [comment]
Issue is closed due to no response.
