### ISSUE TITLE
iPhone 7 Video is not Transmitting to iPhone 6 or lower

### ISSUE THREAD

**Issue by adil-appifytech** [QuickBlox/quickblox-ios-sdk#750]
**Environment details**
*iOS version, Quickblox iOS SDK version, QuickbloxWebRTC SDK version (optional)*
Quickblox-WebRTC => 2.4
QuickBlox => 2.9.1

**Did this work before?**
Not Sure

**Expected behavior**
Calling from **iPhone 7 to iPhone 6**
iPhone 7 receiving and sending video
iPhone 6 sending video and receiving video

Calling from **iPhone 6 to iPhone 7**
iPhone 7 receiving and sending video
iPhone 6 sending video and receiving video

**Actual behavior**

Calling from **iPhone 7 to iPhone 6**
iPhone 7 receiving and sending video
iPhone 6 sending video and **not receiving video**

Calling from **iPhone 6 to iPhone 7**
iPhone 7 receiving and sending video
iPhone 6 sending video and **not receiving video**

**Logs**
[iPhone7Initiated.txt](https://github.com/QuickBlox/quickblox-ios-sdk/files/760640/iPhone7Initiated.txt)
[iPhone7Received.txt](https://github.com/QuickBlox/quickblox-ios-sdk/files/760641/iPhone7Received.txt)
[iPhone6SIntiated.txt](https://github.com/QuickBlox/quickblox-ios-sdk/files/760642/iPhone6SIntiated.txt)
[iPhone6SReceived.txt](https://github.com/QuickBlox/quickblox-ios-sdk/files/760643/iPhone6SReceived.txt)

<img width="1597" alt="screen shot 2017-02-08 at 5 28 18 pm" src="https://cloud.githubusercontent.com/assets/10629648/22738426/38aabe2c-ee29-11e6-9635-4562bc4d5f15.png">

**Steps to reproduce the behavior**
Call from iPhone 7 to iPhone 6 or vice versa

**Comment by Raikerian** [comment]
Hi,

> rtc::Requested video format is not available (<QBRTCVideoFormat:0x170a493f0, dimensions: 115x150, frame rate: 30, pixel format: 420f>), using (null) instead.

You are trying to set dimension 115x150 which is not supported. You can get correct video formats by calling this method of QBRTCCameraCapture:

```objc
/**
 *  Retrieve available array of QBRTCVideoFormat instances for given camera position.
 *
 *  @param position requested camera position
 *
 *  @return Array of possible QBRTCVideoFormat video formats for requested position
 */
+ (NSArray <QBRTCVideoFormat *> *)formatsWithPosition:(AVCaptureDevicePosition)position;
```

**Comment by adil-appifytech** [comment]
@Raikerian 

1. This array return many formats, how we will decide which one to use?
2. Where we can read documentation regarding whole rtcc debug logs?
3. When we switch the camera, what's the best way to handle it?

**Comment by adil-appifytech** [comment]
@Raikerian - And please update your docs. They don't keep up with latest changes in the SDK.

**Comment by Raikerian** [comment]
1. Choose whatever format you want. They are all sorted from worst to best I think. You can choose the best one (whether it is first or last one in array, we are filtering formats that old devices will probably not handle our of that array).
2. What exact issues you have with logs? They are informative as is, if you are having any issues with them please be more specific.
3. We have updated it already, if you did find that something is wrong please let us know what exact so we can fix it.

As for (null) in log that I've quoted in a previous answer, we will take a look. But for now your issue is related to a bad format which is not supported, please use a supported one.

**Comment by adil-appifytech** [comment]
@Raikerian 

1. Choose whatever format you want. They are all sorted from worst **to best I think**. => Please be sure about what exactly is the case?

2. I have talked to Anton about it, we will be looking for detailed docs regarding that

3. Issue is fixed.

**Comment by Raikerian** [comment]
Just call this method to see output:

```objc
/**
 *  Retrieve available array of QBRTCVideoFormat instances for given camera position.
 *
 *  @param position requested camera position
 *
 *  @return Array of possible QBRTCVideoFormat video formats for requested position
 */
+ (NSArray <QBRTCVideoFormat *> *)formatsWithPosition:(AVCaptureDevicePosition)position;
```
