### ISSUE TITLE
connecting to chat from push notification 

### ISSUE THREAD

**Issue by rvilches** [QuickBlox/quickblox-ios-sdk#753]
**Environment details**
*iOS version - 9.3 - 10.1 
 Quickblox iOS SDK version - 2.9

**Did this work before?**
N/A

**Expected behavior**
 Since IOS wakes up the app for up to 30 seconds whenever I receives a push notification and the app is in the background or suspended, I would like to connect to the chat and process the message, so that the next time the user opens the app the message is already there. 

**Actual behavior**
The app wakes up and QBChat starts the connecting process but suddenly it get stuck with just one line of logs.

**Logs**
*Attach full logs that will describe your problem (please, use github [gist](https://gist.github.com/))*
https://gist.github.com/rvilches/cdd57a0558235baff34e751657b77702

**Steps to reproduce the behavior**
Connect to the chat inside of the function :
`func application(application: UIApplication, didReceiveRemoteNotification userInfo: [NSObject : AnyObject], fetchCompletionHandler completionHandler: (UIBackgroundFetchResult) -> Void)
    {}`

**Any others comments?**

**Comment by rvilches** [comment]
BTW this is a question I think it is not an issue

**Comment by Pro100Andrey** [comment]
Hi @rvilches, 
Could you please confirm that the issue is still reproducible?

Thanks.
