### ISSUE TITLE
Image resolution changes when sent as NSData

### ISSUE THREAD

**Issue by vikrantrajput** [QuickBlox/quickblox-ios-sdk#754]
Hi,
To send an image as attachment, I have to pass the image data as NSData object. 
When I check the image at QB dashboard the resolution is twice what I uploaded from iOS device. 
Before sending the image I rescale every image to a particular height and width and I know NSData changes the resolution and size of image, but I can decode the same NSData in original scale. 
I want to know why QB is not decoding the NSData in same scale. 

```objective-c
        CGSize size = [self changeDimensionWithImage:attachmentImage];
        
        CGFloat imageHt = size.height;
        
        CGFloat imageWd = size.width;
        
        UIImage *testImage = [self imageWithImage:attachmentImage scaledToSize:CGSizeMake(imageWd, imageHt) compressQuality:0.5];
        
        compressedData = UIImageJPEGRepresentation(testImage,0.5);
```

I pass this **compressedData** to QB method. 
If I decode it using this code `UIImage *newImg = [UIImage imageWithData:compressedDataa scale:2.0]`
I can get the image in same scale. 

Thanks

**Comment by VitaliyGuru** [comment]
@vikrantrajput, Hello. I had checked this behavior in our sample and wasn't able to reproduce the issue.

Could you please show the implementation of methods below:
```objective-c
[self changeDimensionWithImage:attachmentImage];
[self imageWithImage:attachmentImage scaledToSize:CGSizeMake(imageWd, imageHt) compressQuality:0.5];
```

**Comment by VitaliyGuru** [comment]
@vikrantrajput , Any updates?

**Comment by VitaliyGuru** [comment]
The issue is closed due to no response.
