### ISSUE TITLE
Application crashes while using screen share in swift 3

### ISSUE THREAD

**Issue by utkarshmaximess** [QuickBlox/quickblox-ios-sdk#755]
*Help avoid duplicate issue reports, check [existing issues](https://github.com/QuickBlox/quickblox-ios-sdk/issues)*
 
**Environment details**
*iOS version, Quickblox iOS SDK version, QuickbloxWebRTC SDK version (optional)*

**Did this work before?**

**Expected behavior**

**Actual behavior**
I was struggling with the screen sharing feature in IOS (Swift). I couldn't find the screenSharing feature documentation for Swift, where as Swift documentation helped in all other features. When I tried to change the available screenShare code to swift it is working fine for the start, but it is consuming a lot of memory, where it says CVPixalBufferRelease() doesn't work in swift anymore. And my application crashes due to heavy memory usage while screenSharing.

**Logs**
*Attach full logs that will describe your problem (please, use github [gist](https://gist.github.com/))*

**Steps to reproduce the behavior**

**Any others comments?**

**Comment by VitaliyGuru** [comment]
@utkarshmaximess, Hello. 
Try to create pixel buffer using the following method:
```swift
func allocPixelBuffer() -> CVPixelBuffer {
    let pixelBufferAttributes : CFDictionary = [...]
    let pixelBufferOut = UnsafeMutablePointer<CVPixelBuffer?>.alloc(1)
    _ = CVPixelBufferCreate(kCFAllocatorDefault, 
                            Int(Width), 
                            Int(Height), 
                            OSType(kCVPixelFormatType_32ARGB),
                            pixelBufferAttributes, 
                            pixelBufferOut)

    let pixelBuffer = pixelBufferOut.memory!
    pixelBufferOut.destroy()
    return pixelBuffer
}
```

**Comment by VitaliyGuru** [comment]
@utkarshmaximess, Any updates?
