### ISSUE TITLE
Info.plist CFBundleShortVersionString

### ISSUE THREAD

**Issue by yaroslavkol** [QuickBlox/quickblox-ios-sdk#757]
Apple rejects build upload with QuickBlox SDK version 2.9.2 included (installed via CocoaPods).
I believe somewhere inside compiled framework 2.9.1.1 value is set for CFBundleShortVersionString info.plist key.

Even using Framework v2.9.3. Taken from master (latest commit: aa336ba)

**Comment by Raikerian** [comment]
Hi,

What is the exact reason for reject? Quote it please.

**Comment by yaroslavkol** [comment]
My build has v 1.0 currently and I don't have any visible .plists with such values. I've got only one error:
**ERROR ITMS-90060: "This bundle is invalid. The value for key CFBundleShortVersionString '2.9.1.1' in the Info.plist file must be a period-separated list of at most three non-negative integers."**
ERROR ITMS-90060: "This bundle is invalid. The value for key CFBundleShortVersionString '2.9.1.1' in the Info.plist file must be a period-separated list of at most three non-negative integers."

**Comment by Raikerian** [comment]
We have updated version 2.9.3 with correct plist on pods, clean your pods cache and perform clean pod Install:

```
rm -rf "${HOME}/Library/Caches/CocoaPods"
rm -rf "`pwd`/Pods/"
pod update
```

**Comment by yaroslavkol** [comment]
Issue fixed.
