### ISSUE TITLE
QBChatMessage+CustomParameters

### ISSUE THREAD

**Issue by StrongFingers** [QuickBlox/quickblox-ios-sdk#758]
Hello, in my project that uses QuickBlox SDK we need to use "custom parameters" field in QBChatMessage. And i faced the trouble, which reproducing on your GIT hub repository for IOS 

The main thing of trouble lie in using customParameters field, it seems that QuickBlox uses it for some internal data transfer, 

If i use method below in the 

> ChatViewController.m

```
[ (void)didPressSendButton:(UIButton *)button
           withMessageText:(NSString *)text
                  senderId:(NSUInteger)senderId
         senderDisplayName:(NSString *)senderDisplayName
                      date:(NSDate *)date ]
```
And add to custom parameters those fields,

> NSDictionary *dict = @{@"created_at":[NSString stringWithFormat:@"%ld",(long)123123123],
>                            @"updated_at":[NSString stringWithFormat:@"%ld",(long)123123123]
>                            };
>     message.customParameters = [[NSMutableDictionary alloc] initWithDictionary:dict];

It fails if trying to 

> - (BFTask *)loadEarlierMessagesWithChatDialogID:(NSString *)chatDialogID 

in class QMChatService+Bolts.m

Is it normal behavior? I fixed the problem just using another dictionary keys, but you might know about such bug. 

**Environment details**
*iOS version, Quickblox iOS SDK version, QuickbloxWebRTC SDK version (optional)*
Framework version 2.9.1, IOS Simulator and devices

**Logs**
*Attach full logs that will describe your problem (please, use github [gist](https://gist.github.com/))*
2017-02-23 13:29:44.210 samplechat[40191:3185539] can not refresh messages: Error Domain=com.alamofire.error.serialization.response Code=-1011 "Request failed: internal server error (500)" UserInfo={NSUnderlyingError=0x600000259b60 {Error Domain=com.alamofire.error.serialization.response Code=-1016 "Request failed: unacceptable content-type: text/html" UserInfo={com.alamofire.serialization.response.error.response=<NSHTTPURLResponse: 0x608000232b60> { URL: https://api.quickblox.com/chat/Message.json?chat_dialog_id=580dd9fca28f9a9221000037&date_sent%5Bgte%5D=1487849331.623454&limit=10&sort_desc=date_sent } { status code: 500, headers {
    Connection = "keep-alive";
    "Content-Length" = 948;
    "Content-Type" = "text/html; charset=utf-8";
    Date = "Thu, 23 Feb 2017 11:29:37 GMT";
    Server = "openresty/1.9.15.1";
    Status = "500 Internal Server Error";
    "X-Rack-Cache" = miss;
    "X-Request-Id" = beb8e4ffeec7813a78684a78b82f5341;
    "X-Runtime" = "0.028666";
} }, NSErrorFailingURLKey=https://api.quickblox.com/chat/Message.json?chat_dialog_id=580dd9fca28f9a9221000037&date_sent%5Bgte%5D=1487849331.623454&limit=10&sort_desc=date_sent, com.alamofire.serialization.response.error.data=<3c21444f 43545950 45206874 6d6c2050 55424c49 4320222d 2f2f5733 432f2f44 54442058 48544d4c 20312e30 20547261 6e736974 696f6e61 6c2f2f45 4e220a20 20202020 20202268 7474703a 2f2f7777 772e7733 2e6f7267 2f54522f 7868746d 6c312f44 54442f78 68746d6c 312d7472 616e7369 74696f6e 616c2e64 7464223e 0a0a3c68 746d6c20 786d6c6e 733d2268 7474703a 2f2f7777 772e7733 2e6f7267 2f313939 392f7868 746d6c22 20786d6c 3a6c616e 673d2265 6e22206c 616e673d 22656e22 3e0a0a3c 68656164 3e0a2020 3c6d6574 61206874 74702d65 71756976 3d22636f 6e74656e 742d7479 70652220 636f6e74 656e743d 22746578 742f6874 6d6c3b20 63686172 7365743d 5554462d 3822202f 3e0a2020 3c746974 6c653e57 65277265 20736f72 72792c20 62757420 736f6d65 7468696e 67207765 6e742077 726f6e67 20283530 30293c2f 7469746c 653e0a09 3c737479 6c652074 7970653d 22746578 742f6373 73223e0a 0909626f 6479207b 20626163 6b67726f 756e642d 636f6c6f 723a2023 6666663b 20636f6c 6f723a20 23363636 3b207465 78742d61 6c69676e 3a206365 6e746572 3b20666f 6e742d66 616d696c 793a2061 7269616c 2c207361 6e732d73 65726966 3b207d0a 09096469 762e6469 616c6f67 207b0a09 09097769 6474683a 20323565 6d3b0a09 09097061 6464696e 673a2030 2034656d 3b0a0909 096d6172 67696e3a 2034656d 20617574 6f203020 6175746f 3b0a0909 09626f72 6465723a 20317078 20736f6c 69642023 6363633b 0a090909 626f7264 65722d72 69676874 2d636f6c 6f723a20 23393939 3b0a0909 09626f72 6465722d 626f7474 6f6d2d63 6f6c6f72 3a202339 39393b0a 09097d0a 09096831 207b2066 6f6e742d 73697a65 3a203130 30253b20 636f6c6f 723a2023 6630303b 206c696e 652d6865 69676874 3a20312e 35656d3b 207d0a09 3c2f7374 796c653e 0a3c2f68 6561643e 0a0a3c62 6f64793e 0a20203c 212d2d20 54686973 2066696c 65206c69 76657320 696e2070 75626c69 632f3530 302e6874 6d6c202d 2d3e0a20 203c6469 7620636c 6173733d 22646961 6c6f6722 3e0a2020 20203c68 313e5765 27726520 736f7272 792c2062 75742073 6f6d6574 68696e67 2077656e 74207772 6f6e672e 3c2f6831 3e0a2020 20203c70 3e576527 76652062 65656e20 6e6f7469 66696564 2061626f 75742074 68697320 69737375 6520616e 64207765 276c6c20 74616b65 2061206c 6f6f6b20 61742069 74207368 6f72746c 792e3c2f 703e0a20 203c2f64 69763e0a 3c2f626f 64793e0a 3c2f6874 6d6c3e0a>, NSLocalizedDescription=Request failed: unacceptable content-type: text/html}}, com.alamofire.serialization.response.error.response=<NSHTTPURLResponse: 0x608000232b60> { URL: https://api.quickblox.com/chat/Message.json?chat_dialog_id=580dd9fca28f9a9221000037&date_sent%5Bgte%5D=1487849331.623454&limit=10&sort_desc=date_sent } { status code: 500, headers {
    Connection = "keep-alive";
    "Content-Length" = 948;
    "Content-Type" = "text/html; charset=utf-8";
    Date = "Thu, 23 Feb 2017 11:29:37 GMT";
    Server = "openresty/1.9.15.1";
    Status = "500 Internal Server Error";
    "X-Rack-Cache" = miss;
    "X-Request-Id" = beb8e4ffeec7813a78684a78b82f5341;
    "X-Runtime" = "0.028666";
} }, NSErrorFailingURLKey=https://api.quickblox.com/chat/Message.json?chat_dialog_id=580dd9fca28f9a9221000037&date_sent%5Bgte%5D=1487849331.623454&limit=10&sort_desc=date_sent, com.alamofire.serialization.response.error.data=<3c21444f 43545950 45206874 6d6c2050 55424c49 4320222d 2f2f5733 432f2f44 54442058 48544d4c 20312e30 20547261 6e736974 696f6e61 6c2f2f45 4e220a20 20202020 20202268 7474703a 2f2f7777 772e7733 2e6f7267 2f54522f 7868746d 6c312f44 54442f78 68746d6c 312d7472 616e7369 74696f6e 616c2e64 7464223e 0a0a3c68 746d6c20 786d6c6e 733d2268 7474703a 2f2f7777 772e7733 2e6f7267 2f313939 392f7868 746d6c22 20786d6c 3a6c616e 673d2265 6e22206c 616e673d 22656e22 3e0a0a3c 68656164 3e0a2020 3c6d6574 61206874 74702d65 71756976 3d22636f 6e74656e 742d7479 70652220 636f6e74 656e743d 22746578 742f6874 6d6c3b20 63686172 7365743d 5554462d 3822202f 3e0a2020 3c746974 6c653e57 65277265 20736f72 72792c20 62757420 736f6d65 7468696e 67207765 6e742077 726f6e67 20283530 30293c2f 7469746c 653e0a09 3c737479 6c652074 7970653d 22746578 742f6373 73223e0a 0909626f 6479207b 20626163 6b67726f 756e642d 636f6c6f 723a2023 6666663b 20636f6c 6f723a20 23363636 3b207465 78742d61 6c69676e 3a206365 6e746572 3b20666f 6e742d66 616d696c 793a2061 7269616c 2c207361 6e732d73 65726966 3b207d0a 09096469 762e6469 616c6f67 207b0a09 09097769 6474683a 20323565 6d3b0a09 09097061 6464696e 673a2030 2034656d 3b0a0909 096d6172 67696e3a 2034656d 20617574 6f203020 6175746f 3b0a0909 09626f72 6465723a 20317078 20736f6c 69642023 6363633b 0a090909 626f7264 65722d72 69676874 2d636f6c 6f723a20 23393939 3b0a0909 09626f72 6465722d 626f7474 6f6d2d63 6f6c6f72 3a202339 39393b0a 09097d0a 09096831 207b2066 6f6e742d 73697a65 3a203130 30253b20 636f6c6f 723a2023 6630303b 206c696e 652d6865 69676874 3a20312e 35656d3b 207d0a09 3c2f7374 796c653e 0a3c2f68 6561643e 0a0a3c62 6f64793e 0a20203c 212d2d20 54686973 2066696c 65206c69 76657320 696e2070 75626c69 632f3530 302e6874 6d6c202d 2d3e0a20 203c6469 7620636c 6173733d 22646961 6c6f6722 3e0a2020 20203c68 313e5765 27726520 736f7272 792c2062 75742073 6f6d6574 68696e67 2077656e 74207772 6f6e672e 3c2f6831 3e0a2020 20203c70 3e576527 76652062 65656e20 6e6f7469 66696564 2061626f 75742074 68697320 69737375 6520616e 64207765 276c6c20 74616b65 2061206c 6f6f6b20 61742069 74207368 6f72746c 792e3c2f 703e0a20 203c2f64 69763e0a 3c2f626f 64793e0a 3c2f6874 6d6c3e0a>, NSLocalizedDescription=Request failed: internal server error (500)}

**Comment by Raikerian** [comment]
Hi,

QBChatMessage class has already those fields implemented (created_at, updated_at). What is the point sending them in custom parameters?

**Comment by StrongFingers** [comment]
We use chat messages as notes object(internal project entity),  also we need a history, to show user **state on the moment when message was sented**, so i added 

> "created_at"

 field to custom parameters as time of creation of the notes. 

So the custom parameters is solve the problem very good, but accidentally faced such error.

Also i tryed to insert in custom parameter as value a dictionary with data that i need, with custom key, that not reserved by Qblox,
but seems that those inserted "dict in dict" encodes to string.

Could you tell which field are reserved in 

> "custom parameters" 

field ?

**Comment by Raikerian** [comment]
```objc
/**
 *  Message custom parameters. Don't use 'body' & 'delay' as keys for parameters.
 */
@property (nonatomic, strong, null_resettable) NSMutableDictionary<NSString *, NSString *> *customParameters;
```

Well, there is generic for a reason, custom parameters can be string only :)
If you want dictionary there, make a son string out of it and send it using custom parameters.

**Comment by StrongFingers** [comment]
Okay, thanks!
