### ISSUE TITLE
Push notifications (version 2.9.2): Can't create subscription from iOS device - "unknown attribute: bundle_identifier"

### ISSUE THREAD

**Issue by ElectroBuddha** [QuickBlox/quickblox-ios-sdk#759]
There's an issue on latest QuickBlox SDK version 2.9.2. When trying to subsribe user for remote notifications, QBRequest.createSubscription() returns error: "unknown attribute: bundle_identifier";

On SDK versions prior to v2.9.2 it was working without problems.

The issue can also be observed in the sample application 'sample-push-notifications' (with latest sdk v2.9.2).

- Tested on iOS 10.2.1

**Request logs for working SDK version 2.9.1:**

```
Request parameters:{
    device =     {
        platform = ios;
        udid = "SOME_UDID_HERE";
    };
    "notification_channels" = apns;
    "push_token" =     {
        "client_identification_sequence" =  SOME_CLIENT_ID_HERE;
        environment = development;
    };
}

Response: Successfull response!
```

**Request logs for non-working latest SDK version 2.9.2:**

```
Request parameters:{
    device =     {
        platform = ios;
        udid = "SOME_UDID_HERE";
    };
    "notification_channels" = apns;
    "push_token" =     {
        "bundle_identifier" = "com.quickblox.supersample-test";
        "client_identification_sequence" = SOME_CLIENT_ID_HERE;
        environment = development;
    };
}

Response: Request failed: client error (422) - unknown attribute: bundle_identifier
```

As you can see, there is an extra parameter 'bundle_identifier' in request in the latest SDK v2.9.2, which causes problems.

**Comment by soulfly** [comment]
@ElectroBuddha 
It's fixed, you can check
Sorry for the inconvenience

**Comment by jlubeck** [comment]
This is happening to me on 2.13

**Comment by tonifirnandes** [comment]
Hello team, we are still facing this issue on version "2.17.1", we got this error : unknown attribute: bundle_identifier. Where on previous version "2.7.5" just working well. Thanks.
