### ISSUE TITLE
Problems with installing QuickBlox

### ISSUE THREAD

**Issue by rcorin** [QuickBlox/quickblox-ios-sdk#760]
I'm having a lot of trouble installing QuickBlox, to the point that I'm considering another chat framework.

I want to integrate the code for the simple-chat project, but have had problems. I want to use pods, but the pods that are in simple-chat are development and the sample-chat project has the framework added manually. If I use the QuickBlox pod then it seems to work fine but I have issues with 'ServicesManager'; in the pod a 'QMServicesManager' is provided but it's not the same and it breaks the chat project.

Do you have clear, up-to-date instructions to make sample-chat work using pods? 
Thank you.

**Comment by VitaliyGuru** [comment]
@rcorin, Hello. Please provide your test project with these issues. Also, could you please specify and explain in more detail steps to reproduce them?

I have tried to create a new project with the  podfile below
```
target 'TestPods' do
    
use_frameworks!

pod 'QMChatViewController'
pod 'QMServices'
pod 'QuickBlox'
end
```
and everything works as expected.

**Comment by rcorin** [comment]
Hi @VitaliyGuru I managed to make it work, thanks for replying. Now I have an issue with putting the sender fullname on top of the messages. I read in another issue that i should get the QBUUser messageSender if I use QMServices in the method to create the attributed string for top label, but I am getting nil. I don´t want to make a different QBRequest for each user id, if possible.
thanks!

**Comment by VitaliyGuru** [comment]
@rcorin, Please create a separate issue.
Closed as resolved.
