### ISSUE TITLE
Quickblox can't receive video chat

### ISSUE THREAD

**Issue by Tinyik** [QuickBlox/quickblox-ios-sdk#761]
I'm trying to test whether my app can initialize a video chat between two users. I've been spending hours but the function didReceiveNewSession: is still not called. Both users are logged in currently with QBRequest methods and I've also confirmed that QuickBlox keys and secrets are correct. Two users are logged in with different logins and passwords. The simplified code is as following:

```swift
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
        
        QBSettings.setApplicationID(K.quickbloxAppID)
        QBSettings.setAuthKey(K.quickbloxAuthKey)
        QBSettings.setAuthSecret(K.quickbloxAuthSecret)
        QBSettings.setAccountKey(K.quickbloxAccountKey)
        
        QBRTCClient.initializeRTC()
        return true
    }
```

ViewController:

```swift
    class ViewController: UIViewController, QBRTCClientDelegate {
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        
        QBRequest.logIn(withUserEmail: "login", password: "password", successBlock: { (res, us) in
            print((us?.login)! + " logged in")
        }, errorBlock: nil)
        
        
        QBRTCClient.instance().add(self)
        
        
    }
    

    
    @IBAction func callClicked(_ sender: Any) {
        let IDs: [NSNumber] = [NSNumber(value: 24875869)]
        
        let user = QBUUser()
        user.login = "login"
        user.password = "password"
        user.id = (QBSession.current().currentUser?.id)!
        
        QBChat.instance().connect(with: user) { (err) in
            if err != nil {
                print("ERROR") // No error here
                print(err.debugDescription)
            }
            let newSession = QBRTCClient.instance().createNewSession(withOpponents: IDs, with: QBRTCConferenceType.video)
            let userInfo :[String:String] = ["key":"value"]
            newSession.startCall(userInfo)
            
        }
        
    }
    
    func didReceiveNewSession(_ session: QBRTCSession, userInfo: [String : String]? = nil) {
        print("Session Received")
    }
    
    }
```

**Comment by Tinyik** [comment]
Any updates or suggestions?

**Comment by Raikerian** [comment]
Hi,

As I see you are connecting to chat only when clicking call button. In order to receive call you should also be connected to the chat.
If that is not the case, please provide full logs.

**Comment by Tinyik** [comment]
Thanks for replying. How do I connect to the chat on the receiver side?

**Comment by Raikerian** [comment]
Its all up to you when and where to connect to chat, You can follow our chat guide here: https://quickblox.com/developers/SimpleSample-chat_users-ios#Connect_to_Chat

You can also check video sample in current repository.

**Comment by Tinyik** [comment]
Is the didReceiveNewSession: only called after the receiver accepted the call?

**Comment by Raikerian** [comment]
No, it is never called for the caller, but called for the callee if he is connected to the chat.

**Comment by Tinyik** [comment]
Yes. I do know this is called on the callee side. But why on my callee side this method is never invoked? Which chat should I connect to? How can I get the user object in connectWithUser: method?

**Comment by Raikerian** [comment]
> Which chat should I connect to? How can I get the user object in connectWithUser: method?

Just connect to the chat with the user you need to receive call with. Checkout our sample for more use-cases.

**Comment by Tinyik** [comment]
Sorry. Thanks for replying. But how can I connect to someone before knowing who is calling me?

**Comment by Raikerian** [comment]
You don't need to connect to someone, you need to connect yourself to the chat.

**Comment by Tinyik** [comment]
Sorry I'm confused. But the connectWithUser: method asks to provide a user to connect to, which I assume should be the caller.

**Comment by Raikerian** [comment]
Method name is clearly connect**With**User, where **with** is objc naming pattern for method with parameters.

**Comment by Raikerian** [comment]
So you need to connect yourself with that method, not to connect to someone.

**Comment by Tinyik** [comment]
Ohh now I see. Did you mean the **user** here should be the currentUser using the app?

**Comment by Raikerian** [comment]
Right.

**Comment by Tinyik** [comment]
I now see the confusion. I'll try and update here in 15 mins. Thanks.

**Comment by Tinyik** [comment]
I now updated both caller and callee to the following code but keep getting this error log

`class ViewController: UIViewController, QBRTCClientDelegate {
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        
        QBRequest.logIn(withUserEmail: "login", password: "password", successBlock: { (res, us) in
            print((us?.login)! + " logged in")
             QBChat.instance().connect(with: QBSession.current().currentUser!, completion: nil)
        }, errorBlock: nil)
        
        
        QBRTCClient.instance().add(self)
        
        
        
        
    }
    
    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
    
    @IBAction func callClicked(_ sender: Any) {
        let IDs: [NSNumber] = [NSNumber(value: 24875869)]
        
        
        let newSession = QBRTCClient.instance().createNewSession(withOpponents: IDs, with: QBRTCConferenceType.video)
        let userInfo :[String:String] = ["key":"value"]
        newSession.startCall(userInfo)
        
    }
    
    func didReceiveNewSession(_ session: QBRTCSession, userInfo: [String : String]? = nil) {
        print("Session Received")
    }
    
    func session(_ session: QBRTCSession, startedConnectingToUser userID: NSNumber) {
        print("Start Connection")
    }
    
    func session(_ session: QBRTCSession, connectionFailedForUser userID: NSNumber) {
        print("Connection Failed")
    }
    
    func session(_ session: QBRTCSession, connectedToUser userID: NSNumber) {
        print("User Connected")
    }
}

`

` [ChatService] Did not authenticate, error: <failure xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><not-authorized/><text lang="en">Password not verified</text></failure>`

**Comment by VitaliyGuru** [comment]
Before calling QBChat.connectWithUser you need to set the password attribute to the user object returned by the first QBRequest.logInWithUserLogin.

**Comment by Raikerian** [comment]
Were you able to solve this?
