### ISSUE TITLE
how to update the chat rooms of deleted user with system notifications when chat room admin deleted the user.

### ISSUE THREAD

**Issue by ajay2c9** [QuickBlox/quickblox-ios-sdk#762]
Hi,
     I implemented the a requirement i.e dialog owner can delete other users in that chat dialog  #743
. And It is working . I am facing a problem with updating the chat dialogs for deleted users. i.e When chat room admin delete the one of the chat room user, for the admin and other users chat rooms are updated. But for the deleted user we need to perform the action like push-pop the view controller then it is updated. Please give the suggestion to update the chat rooms to the deleted user by using the system notification.

Thank you

**Comment by VitaliyGuru** [comment]
@ajay2c9, Hello.
1. Dialog owner wants to remove occupant.
2. Before removing he sends system message (You can specify your own type of system message using `customParameters` of the QBChatMessageInstance).
3. When occupant gets this message you can do pop up and remove this dialog from storage and UI. 

Could you expand a little bit on what difficulties do you have with this workflow?

**Comment by Pro100Andrey** [comment]
Hi @ajay2c9, any updates?
