### ISSUE TITLE
Adding WebRTCv2.4.1 in Private Pod is Giving Error

### ISSUE THREAD

**Issue by adil-appifytech** [QuickBlox/quickblox-ios-sdk#764]
**Environment details**
*iOS version, Quickblox iOS SDK version, QuickbloxWebRTC SDK version (optional)*
WebRTCv2.4
QuickBloxv2.9.2

**Did this work before?**
N/A

**Expected behavior**
I should be able to add this dynamic framework in our own private/public pod

**Actual behavior**
Getting this error

```
ld: warning: ignoring file /var/folders/5m/nfjphp9d7xd44_hr5j410vm80000gp/T/CocoaPods/Lint/Pods/Quickblox-WebRTC/QuickbloxWebRTC.framework/QuickbloxWebRTC, missing required architecture i386 in file /var/folders/5m/nfjphp9d7xd44_hr5j410vm80000gp/T/CocoaPods/Lint/Pods/Quickblox-WebRTC/QuickbloxWebRTC.framework/QuickbloxWebRTC (3 slices)
Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_QBRTCSession", referenced from:
      objc-class-ref in CallServiceManager.o
  "_OBJC_CLASS_$_QBRTCAudioSession", referenced from:
      objc-class-ref in CallServiceManager.o
  "_OBJC_CLASS_$_QBRTCClient", referenced from:
      objc-class-ref in CallServiceManager.o
  "_OBJC_CLASS_$_QBRTCICEServer", referenced from:
      objc-class-ref in CallServiceManager.o
  "_OBJC_CLASS_$_QBRTCConfig", referenced from:
      objc-class-ref in CallServiceManager.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **

```

**Logs**
N/A

**Steps to reproduce the behavior**
N/A

**Any others comments?**
 
 Attached are helpful screenshots

<img width="1425" alt="screen shot 2017-03-08 at 11 02 02 am" src="https://cloud.githubusercontent.com/assets/10629648/23694233/77fca09a-03fa-11e7-8980-de56d89b6ea5.png">

<img width="1599" alt="screen shot 2017-03-08 at 12 23 31 pm" src="https://cloud.githubusercontent.com/assets/10629648/23694239/842fc7a2-03fa-11e7-9f4d-afaa2636103d.png">

**Comment by Raikerian** [comment]
Hi,

i386 is not supported within QuickbloxWebRTC framework, it is 32 bit old simulator architecture.

**Comment by adil-appifytech** [comment]
@Raikerian - What's the fix then?

**Comment by Raikerian** [comment]
Need to remove i386 architecture as active build one.

**Comment by VitaliyGuru** [comment]
Closed as fixed.
