### ISSUE TITLE
leaveWithCompletionBlock and QBChatDelegate

### ISSUE THREAD

**Issue by odemolliens** [QuickBlox/quickblox-ios-sdk#766]
**Environment details**
*iOS 10, Quickblox iOS SDK 2.9.2,*

Hi,

I'm trying to implement the leave chat feature.

To ensure the fact that user really leave the chat, I need a callback.
`[chatRoom leaveWithCompletionBlock:^(NSError * _Nullable error) {
   //This case is only for error 
  }];  `

In previous SDK version, QBChatDelegate expose these callback methods

`- (void)chatRoomDidLeave:(NSString *)roomName;
`

But in recent version, I don't find anything about this delegate and **how get a success callback** **when user leave the room**.

Maybe I need to use ?
`- (void)deleteDialogWithID:(NSString *)dialogId completion:(void (^)(QBResponse *))completion`

Any idea?

**Comment by VitaliyGuru** [comment]
@odemolliens, Hello. Yes, you're right. You should use the method:
```objective-c
+ (QBRequest *)deleteDialogsWithIDs:(NSSet<NSString *> *)dialogIDs
                        forAllUsers:(BOOL)forAllUsers
                       successBlock:(nullable void(^)(QBResponse *response, NSArray<NSString *> * _Nullable deletedObjectsIDs, NSArray<NSString *> * _Nullable notFoundObjectsIDs, NSArray<NSString *> * _Nullable wrongPermissionsObjectsIDs))successBlock
                         errorBlock:(nullable QBRequestErrorBlock)errorBlock;
```

**Comment by VitaliyGuru** [comment]
If you are using QMServices you should choose this method:
```objective-c
- (void)deleteDialogWithID:(NSString *)dialogId completion:(void (^)(QBResponse *))completion 
```
