### ISSUE TITLE
Remote Video Frame stopped when capturing Local Frame using AVCaptureVideoDataOutput

### ISSUE THREAD

**Issue by haifizarshad** [QuickBlox/quickblox-ios-sdk#768]
"QB-OS" = "iOS 10.1.1"
"QB-SDK" = "iOS 2.9"
QuickbloxWebRTC version = 2.3 

I needed to capture some frames during video chat, but when i try to capture frame of local camera stream using iOS AVCaptureVideoDataOutput like this,

`AVCaptureSession *session = self.cameraCapture.captureSession;
    session.sessionPreset = AVCaptureSessionPresetMedium;    
    AVCaptureVideoDataOutput *output = session.outputs[0];
    dispatch_queue_t queue = self.cameraCapture.videoQueue;
    [output setSampleBufferDelegate:self queue:queue];
    output.videoSettings = [NSDictionary dictionaryWithObject:[NSNumber numberWithInt:kCVPixelFormatType_32BGRA] forKey:(id)kCVPixelBufferPixelFormatTypeKey];
    [session startRunning];`

When 'output.videoSettings' executed it create black frame like a camera flash on local side and then disappear, but stop sending frames on remote side, i guess what m i doing wrong?

**Comment by Raikerian** [comment]
Hi,

Currently supported video formats are kCVPixelFormatType_420YpCbCr8BiPlanarFullRange and kCVPixelFormatType_32ARGB.
See QBRTCPixelFormat in QBRTCTypes.h file for more information.

**Comment by haifizarshad** [comment]
Thanks for your quick response,but when i try to update 'videoSettings' dictionary with formate type, "kCVPixelFormatType_32ARGB" it get crashed with error,
**Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[AVCaptureVideoDataOutput setVideoSettings:] Unsupported pixel format type - use -availableVideoCVPixelFormatTypes'**

And in case of "kCVPixelFormatType_420YpCbCr8BiPlanarFullRange" it give error with bytes/row like this,

**<Error>: CGBitmapContextCreate: invalid data bytes/row: should be at least 1920 for 8 integer bits/component, 3 components, kCGImageAlphaPremultipliedFirst.
CGBitmapContextCreateImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
<Error>: CGBitmapContextCreateImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.**

**Comment by Raikerian** [comment]
Look at our screen sharing implementation, here we sending frames using separate capture: https://quickblox.com/developers/Sample-webrtc-ios#Custom_video_capture

Working implementation can be found in video chat sample in current repository.

**Comment by haifizarshad** [comment]
Actually my issue here is not to send frames via screen sharing, my code is working fine (both local and remote frames updates normally) until i start capturing local stream frames, local screen update with black frame (only first one) then came back to normal flow but after this process o can't see any update on remote just black image just like this,
![capture issue](https://cloud.githubusercontent.com/assets/2638131/23867642/66b73046-083e-11e7-8a72-0fcc5961d461.png)

**Comment by Raikerian** [comment]
Is that square a **part of the whole frame** which is fullscreen on your screenshot? Or us that black frame a separate view on top of the fullscreen frame with its own frame? If it's the part of the frame itself (and by frame I mean your whole entity, not just black square) then I don't really think there is an issue on our end here.

**Comment by haifizarshad** [comment]
Actually black image is just a UIView is container for 'QBRTCRemoteVideoView' with its custom frame size,
`QBRTCRemoteVideoView *opponentVideoView = (id)[self videoViewWithOpponentID:recepentId];
    opponentVideoView.frame = self.remoteVideoContainerView.bounds;
    [self.remoteVideoContainerView addSubview:opponentVideoView];`

it updated properly until i start capturing and sudenly frames captured and sent from this device goes black,
`AVCaptureSession *session = self.cameraCapture.captureSession; session.sessionPreset = AVCaptureSessionPresetMedium; AVCaptureVideoDataOutput *output = session.outputs[0]; dispatch_queue_t queue = self.cameraCapture.videoQueue; [output setSampleBufferDelegate:self queue:queue]; output.videoSettings = [NSDictionary dictionaryWithObject:[NSNumber numberWithInt:kCVPixelFormatType_32BGRA] forKey:(id)kCVPixelBufferPixelFormatTypeKey]; [session startRunning];`

**Comment by haifizarshad** [comment]
I rather prefer to capture local stream via,
`[AVCaptureStillImageOutputObj captureStillImageAsynchronouslyFromConnection:AVCaptureConnection completionHandler:^(CMSampleBufferRef imageDataSampleBuffer, NSError *error) {
            NSData *imageData = [AVCaptureStillImageOutput jpegStillImageNSDataRepresentation:imageDataSampleBuffer];
                                                              UIImage *capturedImage = [UIImage imageWithData:imageData];
//.... 
        }];`
its working fine now.
