### ISSUE TITLE
QBChatAbstractMessage in current sdk

### ISSUE THREAD

**Issue by cipherguy** [QuickBlox/quickblox-ios-sdk#771]
Hello , I just trying to upgrade quickblox to new version and the issue is it is missing . 
QBChatAbstractMessage class.

**Comment by VitaliyGuru** [comment]
@cipherguy, Hello? What was your previous version of QuickbloxSDK? This class was removed 2 years ago. You should use QBChatMessage instead.

**Comment by VitaliyGuru** [comment]
@cipherguy, Hello. Do you have any additional questions regarding this issue?

**Comment by VitaliyGuru** [comment]
@cipherguy, Closed due to no response.
