### ISSUE TITLE
 error when uploading archieve to appstore

### ISSUE THREAD

**Issue by godwincharan** [QuickBlox/quickblox-ios-sdk#772]
I get following errors while uploading the app to App Store using Xcode. I have Xcode  Version 8.2.1 (8C1002)

Following are the errors:
iTunes Store operation failed. Unsupported Architectures. The executable for Bachao.app/Frameworks/Quickblox.framework contains unsupported architectures '[x86_64, i386]'.

iTunes Store operation failed.
Invalid Segment Alignment. The app binary at 'Bachao.app/Frameworks/Quickblox.framework/Quickblox' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version.

iTunes Store operation failed.
The binary is invalid. The encryption info in the LC_ENCRYPTION_INFO load command is either missing or invalid, or the binary is already encrypted. This binary does not seem to have been built with Apple's linker.

**Comment by godwincharan** [comment]
@Pro100Andrey Can you please look this as highest priority. I am not able share my app with client using apple's Test flight.

**Comment by Pro100Andrey** [comment]
Hi @godwincharan , please check [Run Script Phase for Dynamic framework](https://quickblox.com/developers/IOS-how-to-connect-Quickblox-framework#Run_Script_Phase_for_Dynamic_framework)

**Comment by godwincharan** [comment]
@Pro100Andrey
bash "${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}/Quickblox.framework/strip-framework.sh"

Do we need to manually fill BUILT_PRODUCTS_DIR and FRAMEWORKS_FOLDER_PATH. Or it will understand automatically?

**Comment by Pro100Andrey** [comment]
@godwincharan, automatically 
<img width="1168" alt="2017-03-19 12 36 29" src="https://cloud.githubusercontent.com/assets/1109916/24080112/cb14ae54-0ca0-11e7-9cf7-3ec9098260eb.png">

**Comment by Pro100Andrey** [comment]
@godwincharan  any updates ?

**Comment by godwincharan** [comment]
@Pro100Andrey  Thanks for your support. It worked. Really appreciate your support on weekend.
