### ISSUE TITLE
The user doesn't receives the messages that were sent to the group chat  by others when he was offline. 

### ISSUE THREAD

**Issue by basantsa** [QuickBlox/quickblox-ios-sdk#773]
The user doesn't receives the messages that were sent to the group chat by others when he was offline. 

Am not using push notifications here. Also, when the app is put in the background, i disconnect from the chat, and when the app comes to foreground i connect to the chat and makes the user join the group again.

My assumption is as soon as the user comes online, he should receive the group messages that were sent to him when he was disconnected from chat.

**Comment by VitaliyGuru** [comment]
@basantsa , Hello. For group dialogs you should receive messages using REST API. 
In order to save 'em to history (to be able to receve 'em fron the REST) you should send messages with custom parameter.

```objective-c
QBChatMessage *message = [QBChatMessage message];
...
NSMutableDictionary *params = [NSMutableDictionary dictionary];
params[@"save_to_history"] = @YES;
[message setCustomParameters:params];
```
Take a look at our [documentation](https://quickblox.com/developers/SimpleSample-chat_users-ios#Chat_history).

**Comment by basantsa** [comment]
Yes am setting the params[@"save_to_history"] = @YES;

So in order to fetch the messages which were sent in a room when the user was offline, i would be need to call a REST api ? And that REST api give me **only** the messages which weren't delivered because the user was offline. Right ?

**Comment by basantsa** [comment]
@VitaliyGuru This is the code am using. 
let message: QBChatMessage = QBChatMessage()
            message.text = messageTxt
            let params = NSMutableDictionary()
            params["save_to_history"] = true
            message.customParameters = params
            message.dialogID = group.groupId
            message.dateSent = Date()
        
        
            groupChatDialog.send(message, completionBlock: { (error) in
                if error == nil {
                    print("Message sent successfully.")
                } else {
                    print(error!)
                }
            })


My assumption is whenever the user connects to that chat, he would receive all the offline messages sent to that group and the delegate would be called:

func chatRoomDidReceive(_ message: QBChatMessage, fromDialogID dialogID: String) {
}

Also, if this is not the case, then which REST api should i call to fetch the offline messages ? I didn't find any in the Docs.

**Comment by VitaliyGuru** [comment]
No, in this situation you should use [extendedRequest](https://quickblox.com/developers/SimpleSample-chat_users-ios#List_chat_messages):

```objective-c
+ (QBRequest *)messagesWithDialogID:(NSString *)dialogID
                    extendedRequest:(nullable NSDictionary<NSString *, NSString *> *) extendedParameters
                            forPage:(nullable QBResponsePage *)page
                       successBlock:(nullable void (^)(QBResponse *response, NSArray<QBChatMessage *> * _Nullable messages, QBResponsePage * _Nullable page))successBlock
                         errorBlock:(nullable QBRequestErrorBlock)errorBlock;
```

Example for extendedParametrs from our [QMChatServises](https://github.com/QuickBlox/q-municate-services-ios):
```objective-c
- (NSDictionary *)parametersForMessagesUsingDialogID:(NSString *)chatDialogID {
    //1
    NSMutableDictionary *parameters = [@{@"sort_desc" : @"date_sent"} mutableCopy];
    //2
    NSDate *lastMessagesLoadDate = self.lastMessagesLoadDate[chatDialogID];
    //3
    QBChatMessage *lastMessage = [self.messagesMemoryStorage lastMessageFromDialogID:chatDialogID];
    
    if (lastMessagesLoadDate == nil && lastMessage != nil) {
        //4
        lastMessagesLoadDate = lastMessage.dateSent;
    }
    //5
    parameters[@"date_sent[gte]"] = @([lastMessagesLoadDate timeIntervalSince1970]);
    
    return [parameters copy];
}
```

1. Using operator `sort_desc` for field `date_sent`  to receive sorted messages. 
2. Getting cached `lastMessagesLoadDate` from the previous request for the dialog.  
3. In QMServices messages are stored in memory and persistent storages, so looking for last cached message.
4. Getting `lastMessagesLoadDate` from the cached message.
5.  Adding new operator  `date_sent` with filter `gte`(Greater Than or Equal) which means that the server should return messages sent later cached one.

**Comment by basantsa** [comment]
@VitaliyGuru you sir are brilliant ! It worked. Thanks.
