### ISSUE TITLE
Getting last message when user was block with using Privacy list

### ISSUE THREAD

**Issue by vikrantrajput** [QuickBlox/quickblox-ios-sdk#776]
Hello everyone, I am working on Block  functionalities. If user A blocks user B, ideally, user A should not receive any message from B, which is working fine. The issue is, when B is blocked by A and B sends a message to A, message is still being stored on the backend and is considered as last message from B to A. But this is not supposed to be last message as it was sent after getting blocked. 
When I try to get all dialogs for A, I get dialog from B and last message is what B sent after getting blocked. 

I am using following code to get dialog which having last message and more details
```objc
 NSString *token = [QBSession currentSession].sessionDetails.token;
[[ConnectionManager sharedManager] retrieveDialogsWthToken:token success:^(id responseObject) {} failure:^(NSError *error) {}];
```
and this is my response of this method
```logos
{
    items =     (
                {
            "_id" = 58cd03dfa0eb47865a00000d;
            "created_at" = "2017-03-18T09:54:39Z";
            "last_message" = Ijkjkjkl;
            "last_message_date_sent" = 1490078617;
            "last_message_user_id" = 22145264;
            name = "chat_for_product_277_with_22143612";
            "occupants_ids" =             (
                22143612,
                22145264
            );
            photo = "<null>";
            type = 2;
            "unread_messages_count" = 0;
            "updated_at" = "2017-03-21T06:43:39Z";
            "user_id" = 22145264;
            "xmpp_room_jid" = "51509_58cd03dfa0eb47865a00000d@muc.chat.quickblox.com";
        }
    );
    limit = 100;
    skip = 0;
    "total_entries" = 1;
}
```
please give me solution asap. 
Thanks

**Comment by vikrantrajput** [comment]
@Raikerian @Pro100Andrey please give me response and guide me for this issue.
Thanks

**Comment by Raikerian** [comment]
Hi,

I'm not really sure what is the issue here. Are you not receiving last message text or something?

**Comment by vikrantrajput** [comment]
@Raikerian  Thanks for reply, A user getting last message sending by B user but that time B user blocked by A user. So I want that A get last message which only when B user not block. IF B blocked than don't get any last message during block.

**Comment by vikrantrajput** [comment]
@Raikerian  did you get my problem ?

**Comment by vikrantrajput** [comment]
@soulfly @Raikerian How I can solve this issue ?

**Comment by vikrantrajput** [comment]
@soulfly @VitaliyGuru @Raikerian I am rephrasing the issue to make it easy to understand. 
If user A blocks user B, ideally, user A should not receive any message from B, which is working fine. The issue is, when B is blocked by A and B sends a message to A, message is still being stored on the backend and is considered as last message from B to A. But this is not supposed to be last message as it was sent after getting blocked.
When I try to get all dialogs for A, I get dialog from B and last message is what B sent after getting blocked.

**Comment by VitaliyGuru** [comment]
@vikrantrajput, Hello. We've understood you. It's a server-side issue.

**Comment by vikrantrajput** [comment]
Hello @VitaliyGuru thanks. 
Do you have any idea by when can this issue be fixed?

**Comment by VitaliyGuru** [comment]
@vikrantrajput, It will be fixed in next releases. No any ETA  for now.

**Comment by vikrantrajput** [comment]
Hello @VitaliyGuru, any updates on this issue?
Is this fixed in any of the recent updates?

**Comment by keeblebogdan** [comment]
Any new updates? Blocked user can still send messages.

**Comment by ZalakSA** [comment]
How to prevent block users from sending message notification ? Please help me

**Comment by QB-vladyslav-vyshniak** [comment]
Hello, dear users. 

Thank you for contacting QuickBlox support.
Currently, our developers are testing new updates for PrivacyLists feature where this issue will be fixed.
Also, we will release documentation about how to use PrivacyLists feature.
