### ISSUE TITLE
Not able to add new class in Pod Project

### ISSUE THREAD

**Issue by SagarNandha1** [QuickBlox/quickblox-ios-sdk#778]
Hello,
I have created a project & included pods for chat and video calling as well. I am using Quickblox iOS Chat SDK 2.9. 

Now, I want to send audio files in chat and for that I am adding a new "CustomClass.h" & "CustomClass.m" & "CustomClass.xib" for the same in Pod project. It is the same file as it is created for displaying image in chat screen. The path of this class & xib is configured perfectly as well it is set as public.

But When I am importing this file in "QBChatCell" file, I am seeing an error that "CustomClass.h" file is not found. So, Please assist that How can I add .xib file and .h & .m files in existing pod project of Quick blox SDK.

Awaiting for reply.

Regards,
Sagar

**Comment by VitaliyGuru** [comment]
@SagarNandha1, Hello. QMChatCell is not part of QuickbloxSDK. It's part of QMChatViewController.

**Comment by VitaliyGuru** [comment]
@SagarNandha1, Hello
Any updates?
