### ISSUE TITLE
How to add a new field to Chat table in Quickblox ?

### ISSUE THREAD

**Issue by basantsa** [QuickBlox/quickblox-ios-sdk#779]
Quickblox gives us some default fields for QBChatDialog like ID, type, name, photo etc. Can we add some extra fields to it ? For example if I want to add another column called groupDelete time which would be a date, how would i do that ?

**Comment by VitaliyGuru** [comment]
@basantsam, Hello. Yes, you can.
There is `@property (nonatomic, copy, nullable) NSDictionary<NSString *, id> *data;` of `QBChatDialog`.
 Please take a look at [our documentation](https://quickblox.com/developers/SimpleSample-chat_users-ios#Custom_parameters).

**Comment by VitaliyGuru** [comment]
@basantsa, Hello. Do you have any issue-related questions or concerns you would like to share?

**Comment by basantsa** [comment]
Hi, 
Am going to integrate this over the weekend and get back. Thanks.

**Comment by basantsa** [comment]
Works. Thanks.
