### ISSUE TITLE
Unable to get the sample user list.

### ISSUE THREAD

**Issue by Gurmeetkaur5949** [QuickBlox/quickblox-ios-sdk#780]
Hello Team,
 i'm using this demo app but the list of sample user is not displayed. I'm always getting this error request  failed : client error(422). one more question if i have list of users and i'm choose one like sampleuserone then how can i create new opponent for one to one chat. I have seen the tutorial site but never understand that how can implement chat between one to one user.

**Comment by Pro100Andrey** [comment]
@Gurmeetkaur5949 , Hello. Could you please provide full logs?

[QBSettings setLogLevel:QBLogLevelDebug];

**Comment by Gurmeetkaur5949** [comment]
Hello sir
I'm getting the error when i logged in as an existing user.
The error log is

*ChatApp[814:428472] [QBCore] Response error reasons: {*

*    errors =     {*

*        base =         (*

*            "Bad timestamp"*

*        );*

*    };*

*}*

*2017-03-28 14:46:20.646543 ChatApp[814:428472] [QBAuth] Create Session
request error: {"errors":{"base":["Bad timestamp"]}}*

Printing description of response:

(QBResponse *) response = 0x0056296f

Printing description of response:

[QBResponse], status: 422




*ChatApp[814:428109] [QBAuth] Create Session request error:
{"errors":{"base":["Bad timestamp"]}}*

*2017-03-28 14:47:15.633329 ChatApp[814:428109] [QBCore] Response error:
Error Domain=com.alamofire.error.serialization.response Code=-1011 "Request
failed: client error (422)"
UserInfo={com.alamofire.serialization.response.error.response=<NSHTTPURLResponse:
0x14d40f00> { URL: https://api.quickblox.com/session.json
<https://api.quickblox.com/session.json> } { status code: 422, headers {*

*    "Access-Control-Allow-Origin" = "*";*

*    "Cache-Control" = "no-cache";*

*    Connection = "keep-alive";*

*    "Content-Length" = 37;*

*    "Content-Type" = "application/json; charset=utf-8";*

*    Date = "Wed, 29 Mar 2017 09:17:43 GMT";*

*    "QuickBlox-REST-API-Version" = "0.1.1";*

*    Server = "openresty/1.9.15.1 <http://1.9.15.1>";*

*    Status = "422 Unprocessable Entity";*

*    "X-Rack-Cache" = "invalidate, pass";*

*    "X-Request-Id" = 61f4f6e05ee977625ab09c855ed36dd9;*

*    "X-Runtime" = "0.006789";*

*    "X-UA-Compatible" = "IE=Edge,chrome=1";*

*} }, NSLocalizedRecoverySuggestion={"errors":{"base":["Bad timestamp"]}},
NSErrorFailingURLKey=https://api.quickblox.com/session.json
<https://api.quickblox.com/session.json>, NSLocalizedDescription=Request
failed: client error (422),
com.alamofire.serialization.response.error.data=<7b226572 726f7273 223a7b22
62617365 223a5b22 42616420 74696d65 7374616d 70225d7d 7d>}*

*2017-03-28 14:47:15.633727 ChatApp[814:428109] [QBCore] Response error
reasons: {*

*    errors =     {*

*        base =         (*

*            "Bad timestamp"*

*        );*

*    };*

*}*


*Thanks and Regards*

*GURMEET KAUR*

**Comment by Gurmeetkaur5949** [comment]
One more question if i try to test app on simulator then it works good but
if i run the app on device then i'm getting error in video/audio calling as
well as in chat also. I think this issue is raise because i'm changing the
some code. Please have a look at this code.

#pragma mark - Helpers

- (NSString *)currentEnvironment {

    NSString* environment = @"dev";

#if DEV

    environment = @"dev";

#endif

#if QA

    environment = @"qbqa";

#endif

    return environment;
}

In this i'm always getting a empty string. so i change the environment
string with static value just for testing purpose. Now the app is working
good on simulator but always give me error on a real device.
Please help me , Tell me what can i do to run the app on real device??

**Comment by VitaliyGuru** [comment]
@Gurmeetkaur5949, Hello. 

With regard to the first question:

Bad timestamp means that you send invalid `timestamp` value on session creation, **which is based on your phone time**. Your device time shouldn't differ from server more than 2 hours.
We suggest you synchronize time on your devices with NTP service or just set tick 2 checkboxes in Settings in your device: Automatic date & time and Automatic time zone.
Hope this help.

On the second issue, `QA`, `DEV` - preprocessor macros.
![3f133a81bf](https://cloud.githubusercontent.com/assets/4947664/24646748/a9a8a838-1925-11e7-805f-1d2c5d4874f4.png).

**Comment by Gurmeetkaur5949** [comment]
​Thanks sir , this answer solve my problem. ​Thanks for your reply.

**Comment by primeappsin** [comment]
![screen shot 2017-06-07 at 10 23 39 pm](https://user-images.githubusercontent.com/29257950/26890681-052f4194-4bd0-11e7-9dab-18b55b9977e4.png)

**Comment by primeappsin** [comment]
Still facing same issue

**Comment by primeappsin** [comment]
@VitaliyGuru can u plz help me y I am getting error 404 its working in demo
 project but not in my project

**Comment by primeappsin** [comment]
![screen shot 2017-06-07 at 10 25 53 pm](https://user-images.githubusercontent.com/29257950/26890768-57735b34-4bd0-11e7-92a2-c456c30e9501.png)
Getting sender id not sender name

**Comment by primeappsin** [comment]
While calling downloadCurrentEnvironmentUsers this method it gives 404 error, to get users list.
Please help me out to get it done soon,
Thanks in advance
