### ISSUE TITLE
Push notifications cant upload production certificate

### ISSUE THREAD

**Issue by rcorin** [QuickBlox/quickblox-ios-sdk#782]
*Help avoid duplicate issue reports, check [existing issues](https://github.com/QuickBlox/quickblox-ios-sdk/issues)*
 
**Environment details**
*iOS version, Quickblox iOS SDK version, QuickbloxWebRTC SDK version (optional)*

**Did this work before?**

**Expected behavior**

**Actual behavior**

**Logs**
*Attach full logs that will describe your problem (please, use github [gist](https://gist.github.com/))*

**Steps to reproduce the behavior**

**Any others comments?**

**Comment by rcorin** [comment]
In the admin console for uploading Apns certificate i cannot choose the environment. Then when I export the certificate from Apple (Apple push service sandbox & production) its detected as sandbox development not production.

**Comment by rcorin** [comment]
This is my app id: 54363

**Comment by AlexJakeGreen** [comment]
@rcorin Hi,
Could you test your PEM key using the following command, which should hang if successful until you press Ctrl-C:
``` bash
openssl s_client -connect gateway.push.apple.com:2195 -cert cert.pem -key cert.pem
```

The above tests the PEM Key in production mode. For sandbox mode, use the following command:
``` bash
openssl s_client -connect gateway.sandbox.push.apple.com:2195 -cert cert.pem -key cert.pem
```

**Comment by rcorin** [comment]
Thanks for answering! I was using the tutorial for exporting the keys from Keychain, and it's exporting a .p12 file not a .pem. 
When calling your command it gives:
unable to load client certificate private key file
87398:error:0906D06C:PEM routines:PEM_read_bio:no start line:/BuildRoot/Library/Caches/com.apple.xbs/Sources/OpenSSL098/OpenSSL098-64.50.5/src/crypto/pem/pem_lib.c:648:Expecting: ANY PRIVATE KEY

**Comment by Raikerian** [comment]
Please send production certificate (p12) which you are trying to upload to this.andrey@gmail.com

**Comment by rcorin** [comment]
Thanks, just did.

**Comment by AlexJakeGreen** [comment]
Hi @rcorin 
I just checked the certificate.
gateway.push.apple.com closes the connection, and it means the certificate is not for production.
```
$ openssl pkcs12 -info -in CertificadosProd.p12 -out cert.pem -nodes
$ openssl s_client -connect gateway.sandbox.push.apple.com:2195 -cert cert.pem
***
    Verify return code: 0 (ok)
---
(hangs here)

$ openssl s_client -connect gateway.push.apple.com:2195 -cert cert.pem 
***
    Verify return code: 0 (ok)
---
closed
(connection closed)
```
Our system detects certificate type automatically, that's why where's no button for choosing the environment.

**Comment by rcorin** [comment]
Hello,
Thanks for the message. I just made another certificate that works ok now
with the openssl test, but still cannot upload to the admin console. I
think the problem is that now in the Apple console you can only generate a
certificate valid for both development and production, and not just
production. I've sent you the new certificate.
thanks
Ricardo

On Mon, Apr 3, 2017 at 6:23 AM, Oleksandr Litvinov <notifications@github.com

**Comment by rcorin** [comment]
I just tried uploading the certificate .pem and it worked! You may want to
update the documentation...
thanks!

**Comment by soulfly** [comment]
@rcorin how you generate Production-only certificate?
I do not see a way to do it, only Universal or Development.

**Comment by rcorin** [comment]
Yes, you can only generate Universal, and I thought that that was a problem. 

If you upload the .p12 certificate to the QB admin console then it detects only for development. If you convert the .p12 to .pem using:

openssl pkcs12 -info -in CertificadosProd2.p12 -out cert.pem -nodes

and upload the .pem file then it's detected as Universal. 
regards!

**Comment by soulfly** [comment]
@rcorin strange... that should not be like that. p12 also should work, let us double check.

**Comment by soulfly** [comment]
@rcorin we have checked your latest certificate you sent ~30 mins ago. We see something strange - your file actually contains 2 certs inside: Dev + Universal.
I see 2 rows in a Keychain app:
https://www.evernote.com/l/ANgWIuSsm35KOrZCdInglYjRaYsNJ_1_BGIB/image.png

that's why QuickBlox dashboard detects it as Development becaue it parses only 1 thing. 
I do not know a way how you did it, but could you create p12 certificate with only Universal part?

**Comment by rcorin** [comment]
I created the certificate from developer.apple.com, I think they changed and now create the certificates with both dev and production option. There is no "just production" option anymore:

Apple Push Notification service SSL (Sandbox & Production)
Establish connectivity between your notification server, the Apple Push Notification service sandbox, and production environments to deliver remote notifications to your app. When utilizing HTTP/2, the same certificate can be used to deliver app notifications, update ClockKit complication data, and alert background VoIP apps of incoming activity. A separate certificate is required for each app you distribute.


![applepush](https://cloud.githubusercontent.com/assets/1315480/24608386/b48b4eb0-184c-11e7-822c-6b8da7524cc1.jpeg)

**Comment by soulfly** [comment]
Did the same, but got only 1 cert inside: Universal

https://www.evernote.com/l/ANhUlUSZXhhBq7uFjy5FtS4uSOwxcnI6GSQB/image.png

How do you actually create this .p12 file? Could you provide us your steps, please

**Comment by soulfly** [comment]
We use this guide to create and upload p12 certificate:
https://quickblox.com/developers/How_to_create_APNS_certificates

you can go through 1 to 4 sections

**Comment by rcorin** [comment]
Hello,

yes, I used the same guide, not sure how I ended up with two certificates
in the same .pem, I did it again and there's only one.
In any case it's working now so thanks a lot!

Ricardo

**Comment by soulfly** [comment]
@rcorin great, thanks for keeping us updated!
