### ISSUE TITLE
AudioTrack 

### ISSUE THREAD

**Issue by moarzumanov** [QuickBlox/quickblox-ios-sdk#785]
Is there any way to get AVAssetTrack from QBRTCAudioTrack?

**Comment by VitaliyGuru** [comment]
@moarzumanov, Hello. 
Could you please explain in more detail why do you need AVAssetTrack?

**Comment by moarzumanov** [comment]
@VitaliyGuru, Hi

I want to implement speech recognition in my app to make subtitles. I need AVAudioPCMBuffer for SFSpeechAudioBufferRecognitionRequest.

**Comment by Raikerian** [comment]
Hi @moarzumanov 

There will be a remote audio track sink interface added in the next update. You will be able to receive this values from remote audio track: AudioBufferList, AudioStreamBasicDescription, number of frames and timestamp (CMTime).
Release approx. end of this week or start of the next one.

**Comment by Raikerian** [comment]
Accessing remote audio data was added in QuickbloxWebRTC SDK v2.6:
https://quickblox.com/developers/Sample-webrtc-ios#Framework_changelog

Check usage guide here: https://quickblox.com/developers/Sample-webrtc-ios#Accessing_remote_audio_data

**Comment by maughray** [comment]
Hi,

I am currently using last version of QuickBlox and I also want to recognize voice from remote audio track, but I can not find how to convert received variable of type "UnsafePointer<AudioBufferList>" to "AVAudioPCMBuffer" that uses SFSpeechAudioBufferRecognitionRequest. Could you please let me know how you do that?

```
class RemoteAudioTrackManager: NSObject, QBRTCAudioTrackSinkInterface
{
    func audioTrack(_ audioTrack: QBRTCAudioTrack,
                    didSinkAudioBufferList audioBufferList: UnsafePointer<AudioBufferList>,
                    audioStreamDescription: AudioStreamBasicDescription,
                    numberOfFrames: Int,
                    time: CMTime)
    {
        let bufferList = audioBufferList.pointee
        
        var recognitionRequest = SFSpeechAudioBufferRecognitionRequest()
        
        recognitionRequest.append(bufferList)
        /*
            ERROR: Cannot convert value of type 'AudioBufferList' to expected argument type 'AVAudioPCMBuffer'
         */
    }
}
```

Thanks.
