### ISSUE TITLE
BlobID

### ISSUE THREAD

**Issue by Fedenieto90** [QuickBlox/quickblox-ios-sdk#786]
Hi! I'm trying to show the opponents user avatar in iOS but I cant. The user avatar is uploaded to the content module. But, when I try to fetch that file with a QBUUser `blobID` I can't. Apparently the blobID is not present. I tried setting the blobID in the signUp but I can't. What should I do?

**Comment by VitaliyGuru** [comment]
@Fedenieto90, Hello. Could you please provide a code snippet for setting and fetching blobID?
Also, full logs will be helpful. 

```
[QBSettings setLogLevel:QBLogLevelDebug];
```

**Comment by Fedenieto90** [comment]
I used the example code snippet. After registering a user, I uploaded the file to the content module:

`// Upload new avatar to Content module
NSData *avatar = [NSData dataWithContentsOfFile:[[NSBundle mainBundle] pathForResource:@"myAvatar" ofType:@"png"]];
//
[QBRequest TUploadFile:avatar fileName:@"MyAvatar" contentType:@"image/png" isPublic:NO successBlock:nil statusBlock:nil errorBlock:nil];`

That works ok, and the file is uploaded. But it fails when I try to fetch the avatar from the opponent with this example:

`NSUInteger userProfilePictureID = user.blobID; // user - an instance of QBUUser class
 
// download user profile picture
[QBRequest downloadFileWithUID:userProfilePictureID successBlock:nil statusBlock:nil errorBlock:nil];`

**Comment by VitaliyGuru** [comment]
@Fedenieto90, You should use method
```objective-c
+ (QBRequest *)downloadFileWithID:(NSUInteger)fileID
                     successBlock:(nullable void(^)(QBResponse *response, NSData *fileData))successBlock
                      statusBlock:(nullable QBRequestStatusUpdateBlock)statusBlock
                       errorBlock:(nullable void(^)(QBResponse *response))errorBlock;
```

**Comment by Fedenieto90** [comment]
Thanks @VitaliyGuru , the `fileID` parameter is taken from the `user.blobID` field?

**Comment by VitaliyGuru** [comment]
@Fedenieto90, Yes.

**Comment by Fedenieto90** [comment]
Ok! @VitaliyGuru , that `blobID` is created when I upload the avatar? Or do I have to set it for each user?

**Comment by VitaliyGuru** [comment]
@Fedenieto90, In success block of method `TUploadFile` you will receive an instance of `QBCBlob` class. This instance has a property named ID. You should use this property.

```objective-c
   QBUUser *user = //;
   user.blobID = blob.ID;
```

**Comment by Fedenieto90** [comment]
@VitaliyGuru So after uploading the image, I have to update the user in the database by setting the blobID from the response of `TUploadFile`?

**Comment by VitaliyGuru** [comment]
@Fedenieto90, Also you should update user using method:

```objective-c
+ (QBRequest *)updateCurrentUser:(QBUpdateUserParameters *)parameters
                    successBlock:(nullable void (^)(QBResponse *response, QBUUser * _Nullable user))successBlock
                      errorBlock:(nullable QBRequestErrorBlock)errorBlock;
```

**Comment by Fedenieto90** [comment]
Ok! @VitaliyGuru Thanks for the info!

**Comment by VitaliyGuru** [comment]
@Fedenieto90, The second approach is to use `customData` parameter of QBUUser instance. 
You can serialize any data in this parameter.

**Comment by Fedenieto90** [comment]
Ok! Thanks!

**Comment by VitaliyGuru** [comment]
@Fedenieto90, Do you have any additional issue-related questions?
