### ISSUE TITLE
Typo in Dialog Model field name

### ISSUE THREAD

**Issue by madsonic** [QuickBlox/quickblox-ios-sdk#787]
*Help avoid duplicate issue reports, check [existing issues](https://github.com/QuickBlox/quickblox-ios-sdk/issues)*
 No existing issues

**Environment details**
*iOS version, Quickblox iOS SDK version, QuickbloxWebRTC SDK version (optional)*
iOS Version: >= 8, Quickblox iOS SDK version

**Did this work before?**
not relevant

**Expected behavior**
return results with only 1 chat dialog

**Actual behavior**
return results with 0 chat dialog

**Logs**
*Attach full logs that will describe your problem (please, use github [gist](https://gist.github.com/))*

**Steps to reproduce the behavior**
https://quickblox.com/developers/Chat#Dialog_model
    
    let page = QBResponsePage(limit: 100)
    let extendedRequest = ["occupant_ids": "[25976759, 26025952]"]
        
    QBRequest.dialogs(for: page, extendedRequest: extendedRequest, successBlock: { (response: QBResponse, dialogs: [QBChatDialog]?, dialogsUsersIDs: Set<NSNumber>?, page: QBResponsePage?) -> Void in
        print(dialogsUsersIDs)
    }) { (errResponse: QBResponse) -> Void in
        print("error")
        print(errResponse)
    }
I used the gist to filter dialogs by occupants. Following the dialog model in the documentation, I searched with `extendedRequest = ["occupants_ids": "[XXXXXXXX, YYYYYYYY]"` using the key `occupant_ids` gave the correct result. The only difference is the plurality of `occupant`.

The field name in the above documentation should be corrected

**Comment by VitaliyGuru** [comment]
@madsonic, The documentation is OK. Checked with server-team. 
You have sent the link to the **model** of the dialog.
You should use **filters**( allowed parameters) for the extended request. Take a look at [this documentation](https://quickblox.com/developers/Chat#Parameters). 
BTW: even if filter `occupants_ids` works well this is an undocumented feature=). It will be tested, and if it pass all tests will be released in near future.

**Comment by madsonic** [comment]
How is the documentation OK if the keys that worked and the ones in the model documentation are different? This is **obviously** a typo. 

It is hard to tell whether a feature is documented if the documentations are inconsistent. The link you gave differs from what is mention in the [get started guide](https://quickblox.com/developers/SimpleSample-chat_users-ios#Guide:_Getting_Started_with_Chat_API)

> here are some filters to get only chat dialogs you need, _not just all_

This would imply that I should use the model for the fields I want to search or at least that is how I interpreted 'not just all'. So the documentation actually suggested that this is a documented feature.
