### ISSUE TITLE
How can I set Unique Key in Custom Table

### ISSUE THREAD

**Issue by unoiatech** [QuickBlox/quickblox-ios-sdk#789]
I am creating a custom table in quickblox ? I want to set unique key on some of the fields of table. I am not able to find anything about unique key in documentation. How can I set unique key ? Do we have this feature in quickblox ? If not, is there any other option which have same behaviour as unique key ? 
 
Thanks

**Comment by VitaliyGuru** [comment]
@unoiatech, 
Could you expand a little bit on what you said about the unique key?
Are you sure that your question refers to Quickblox SDK?
Also could you please describe workflow in details?

**Comment by Pro100Andrey** [comment]
HI @unoiatech, Any updates?

**Comment by unoiatech** [comment]
I hope now I explained better.
