### ISSUE TITLE
how to resolve this issue "base Bad timestamp"?

### ISSUE THREAD

**Issue by Muhammad-Arslan-Qamar** [QuickBlox/quickblox-ios-sdk#790]
I am new on android, while after importing this code i opened the module **sample-chat**  and it is showing this statement **Can't obtain users errors: base Bad timestamp**.

**Comment by Pro100Andrey** [comment]
Hi @Muhammad-Arslan-Qamar, please provide full logs, for enable logs use code bellow:

```objc
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    ...
    [QBSettings setLogLevel:QBLogLevelDebug];
```

**Comment by Pro100Andrey** [comment]
Hi @Muhammad-Arslan-Qamar, Any updates ?

**Comment by VitaliyGuru** [comment]
@Muhammad-Arslan-Qamar

**Comment by Muhammad-Arslan-Qamar** [comment]
sorry don't understand what did meant by logs??

**Comment by Pro100Andrey** [comment]
Hi @Muhammad-Arslan-Qamar, i mean Xcode console output 

View->Debug Area->Activate Console

shift + cmd + c

**Comment by Muhammad-Arslan-Qamar** [comment]
I am having this issue on android. The problem is when is try get users
from by making this method call

QBUsers.getUsersByTags (tag,null).performAsync()

I am getting exception having. message  "Bad Time Stamp"

I have already check my time on device. also checked by turning on
automatic time zone and time.

If you need more info . i will share the stacktrace. I think the in making
in request.

**Comment by VitaliyGuru** [comment]
@Muhammad-Arslan-Qamar, As for users retrieving:
1.  You should go to the admin.quickblox.com.
2.  Then select your app and go to the settings. http://joxi.ru/p27bp9dt8adxm7
3.  Then you should select checkmark "Allow to retrieve a list of users". http://joxi.ru/VrwbG80tk9GMAX

It will allow you to retrieve a list of users. Waiting for your feedback.

**Comment by VitaliyGuru** [comment]
@Muhammad-Arslan-Qamar, 

> I am having this issue on android.

Please create an issue in [Android Repo](https://github.com/QuickBlox/quickblox-android-sdk/issues) and add all information from this issue.

**Comment by theappslabb** [comment]
I have same issue but  I resolved it. The reason behind this is the wrong date and time on my phone.
