### ISSUE TITLE
Undefined symbols for architecture i386 for _OBJC_CLASS_$_QBRTCClient

### ISSUE THREAD

**Issue by NelepovDmitry** [QuickBlox/quickblox-ios-sdk#793]
Hi, i have problem with adding WebRTC library to my project. Here description of problem:

I create empty project.
Create pod file
```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target :'TestQuickBlox' do
pod 'Quickblox-WebRTC', '~> 2.4.1'
pod 'QuickBlox'
end
```
After that, i open workspace and add code in app delegate
```
#import "AppDelegate.h"

#import <SystemConfiguration/SystemConfiguration.h>
#import <MobileCoreServices/MobileCoreServices.h>
#import <Quickblox/Quickblox.h>
#import <QuickbloxWebRTC/QuickbloxWebRTC.h>

@interface AppDelegate ()

@end

@implementation AppDelegate


- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    // Override point for customization after application launch.
    [QBSettings setAccountKey:@"dBvfn72y1NaQBhhb6f2s"];
    [QBSettings setApplicationID:48324];
    [QBSettings setAuthKey:@"2wV9z25P5stJ4WF"];
    [QBSettings setAuthSecret:@"jshyVqQcFYjY6OX"];
    [QBSettings setLogLevel:QBLogLevelDebug];
    [QBSettings enableXMPPLogging];
    
    [QBRTCClient initializeRTC];
    
    return YES;
}
```

Then i try run on simulator and i got error:
```
ld: warning: ignoring file /Users/nelepovds/Dev/Tests/TestQuickBlox/Pods/Quickblox-WebRTC/QuickbloxWebRTC.framework/QuickbloxWebRTC, missing required architecture i386 in file /Users/nelepovds/Dev/Tests/TestQuickBlox/Pods/Quickblox-WebRTC/QuickbloxWebRTC.framework/QuickbloxWebRTC (3 slices)
Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_QBRTCClient", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
iOS SDK 8.0

**Comment by VitaliyGuru** [comment]
@NelepovDmitry,
Please take a look at [this issue](https://github.com/QuickBlox/quickblox-ios-sdk/issues/764).

**Comment by NelepovDmitry** [comment]
Please give a description how to remove i386 when run on simulator, please.

**Comment by Raikerian** [comment]
@NelepovDmitry just don't use old iPhone 4 simulator, and unless you have i386 arch in your project settings you should be fine.

**Comment by NelepovDmitry** [comment]
@Raikerian i don't use old iphone 4 simulator.
i use 
XCode 8.3.2
Simulator 5S 10.3 
MacOS Sierra
And CPU Core i5
Also i check project build settings and not found any words with i386. 
Valid architectures: arm64 armv7 armv7s

**Comment by VitaliyGuru** [comment]
@NelepovDmitry Coul you please attach a sample project with the reproducible issue.

**Comment by NelepovDmitry** [comment]
@VitaliyGuru yes, here link
[TestQuickBlox](https://drive.google.com/open?id=0B86RD0dcHe5hc1ZxeUhrcTZIcWM)

It's full source with pods.

**Comment by Pro100Andrey** [comment]
Hi @NelepovDmitry

1.  Could you please add `use_frameworks!` in your `Podfile`

```ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target :'TestQuickBlox' do
pod 'Quickblox-WebRTC', '~> 2.4.1'
pod 'QuickBlox'
end
```
2. run pod update
3. clean the build folder for `TestQuickBlox`. `Shift+Alt+Command+K`

**Comment by Pro100Andrey** [comment]
Result:
<img width="1084" alt="screenshot 2017-04-28 14 36 26" src="https://cloud.githubusercontent.com/assets/1109916/25527164/2953f10c-2c20-11e7-84ee-fcf7c92dd1f7.png">

**Comment by NelepovDmitry** [comment]
@Pro100Andrey thank you all work fine.
