### ISSUE TITLE
Download file from custom table issue

### ISSUE THREAD

**Issue by kuangzq** [QuickBlox/quickblox-ios-sdk#795]
I was using

+ (QBRequest *)downloadFileFromClassName:(NSString *)className
                                objectID:(NSString *)objectID
                           fileFieldName:(NSString *)fileFieldName
                            successBlock:(nullable void (^)(QBResponse *response, NSData * _Nullable loadedData))successBlock
                             statusBlock:(nullable QBRequestStatusUpdateBlock)statusBlock
                              errorBlock:(nullable QBRequestErrorBlock)errorBlock;

to download image file (uploaded before as NSData). When massive (70 or so) requests were sent out in a for loop, most responses succeeded while quite a few callbacks returned in ~~~ successBlock ~~~ with nil loadedData or a loadedData with only 30 bytes (definitely wrong for an image data). I need to retry several times before achieving a final actual success.

**Environment details**
iOS version 10.2.1(14D27), Quickblox iOS SDK version 2.9.2

**Did this work before?**
N/A

**Expected behavior**
(As described above.)

**Actual behavior**
(As described above.)

**Logs**
*Attach full logs that will describe your problem (please, use github [gist](https://gist.github.com/))*
(No valuable log for this issue because they are abnormals in successBlock.)

**Steps to reproduce the behavior**
(As described above.)

**Any others comments?**
I understand this may be a performance limitation, but the nil data or truncated data should happen only in errorBlock, not successBlock.

**Comment by Pro100Andrey** [comment]
Hi @kuangzq, anyway could you please provide full logs?

**Comment by Pro100Andrey** [comment]
Hi @kuangzq, any updates ?
