### ISSUE TITLE
QBRequest usersWithLogins retrieve contacts which are not in my contacts list

### ISSUE THREAD

**Issue by marshad13** [QuickBlox/quickblox-ios-sdk#798]
iOS = 10.1.1
QuickbloxWebRTC =  2.5
Quickblox = 2.9.2

I have authenticated my users with twitter digits, everything is working fine, but when i retrieve all of my contacts that are available on my app, it retrieve contacts that are not in my phone contact list, but all contacts registered in my app, what m i doing wrong?

Here is the method i m using,

`+ (QBRequest *)usersWithLogins:(NSArray<NSString *> *)logins
                          page:(nullable QBGeneralResponsePage *)page
                  successBlock:(nullable void (^)(QBResponse *response, QBGeneralResponsePage * _Nullable page, NSArray<QBUUser *> * _Nullable users))successBlock
                    errorBlock:(nullable QBRequestErrorBlock)errorBlock;`

**Comment by marshad13** [comment]
Is there anyone to explain what m i doing wrong?

**Comment by VitaliyGuru** [comment]
@marshad13, 

> I have authenticated my users with twitter digits, everything is working fine, but when i retrieve all of my contacts that are available on my app, it retrieve contacts that are not in my phone contact list, but all contacts registered in my app, what m i doing wrong?

It's a conventional workflow. This method returns users with provided logins in completion block.

Quickblox isn't associated with phone contact list. This feature should be implemented by you.

You mentioned that all users are authenticated with twitter digits thus their models have filled `phone` field with. To get users by their phone numbers you should use the method below:
```objective-c
/**
 Retrieve users with phone numbers (with extended set of pagination parameters)
 
 @param phoneNumbers Phone numbers of users which you want to retrieve
 @param page Pagination parameters
 @param successBlock Block with response, page, and users instances if request succeeded
 @param errorBlock Block with response instance if request failed
 
 @return An instance of QBRequest for cancel operation mainly.
 */
+ (QBRequest *)usersWithPhoneNumbers:(NSArray<NSString *> *)phoneNumbers
                                page:(nullable QBGeneralResponsePage *)page
                        successBlock:(nullable void (^)(QBResponse *response, QBGeneralResponsePage * _Nullable page, NSArray<QBUUser *> * _Nullable users))successBlock
                          errorBlock:(nullable QBRequestErrorBlock)errorBlock;
```

**Comment by marshad13** [comment]
Thanks for your response, let me check it first!

**Comment by marshad13** [comment]
It still returns all contacts added in app including ones that are not in my contacts list

**Comment by marshad13** [comment]
I have 100 contacts in my phone and no one is available on QB users dashboard(from my contacts), I added a user on dashboard with email and some basic info, when i call this method,
`+ (QBRequest *)usersWithPhoneNumbers:(NSArray<NSString *> *)phoneNumbers
                                page:(nullable QBGeneralResponsePage *)page
                        successBlock:(nullable void (^)(QBResponse *response, QBGeneralResponsePage * _Nullable page, NSArray<QBUUser *> * _Nullable users))successBlock
                          errorBlock:(nullable QBRequestErrorBlock)errorBlock;`
It still retrieve user with email that is not in my contacts, is there any other way to check my available contacts? I am totally stuck here.

**Comment by Pro100Andrey** [comment]
Hi @marshad13,
We have released new [Address book](https://quickblox.com/developers/SimpleSample-users-ios#Address_Book) functionality, please check it.

Thanks!
