### ISSUE TITLE
Video chat: viewToRenderOwnVideoStream don't rotate image in landscape orientation

### ISSUE THREAD

**Issue by DrMoriarty** [QuickBlox/quickblox-ios-sdk#8]
I've tested the Sample-VideoChat-ios example (I just moved "my own" view a little bit up in order to see it in landscape).

The screenshot of device:
![screenshot 2013 09 18 17 01 59](https://f.cloud.github.com/assets/1177068/1164971/4e6d252a-2063-11e3-8209-84c79f485722.png)

The screenshot of simulator:
![18 09 2013 17 02 05 ios](https://f.cloud.github.com/assets/1177068/1164976/65d9cb5a-2063-11e3-87f1-5ed87eac8c5e.png)

As you can see viewToRenderOpponentVideoStream correctly rotated image in portrait and landscape mode, but viewToRenderOwnVideoStream didn't.

**Comment by shalem93** [comment]
Is there a way to get rid of the landscape camera in the new WebRTC 2.1.1 version?
