### ISSUE TITLE
Not able to hear the audio via Speaker

### ISSUE THREAD

**Issue by rajanshahsa** [QuickBlox/quickblox-ios-sdk#800]
Hello,
I want to hear the audio via speaker in my video call. I had write following code. it gives error every time.

  let audioSession = QBRTCAudioSession.instance()
            audioSession.initialize()
            audioSession.addDelegate(self)
            if (audioSession.isInitialized && audioSession.currentAudioDevice != QBRTCAudioDevice.speaker){
                audioSession.currentAudioDevice = QBRTCAudioDevice.speaker
            }
            audioSession.deinitialize()

The error is "The operation couldn’t be completed. (OSStatus error -50.)". It indeed give response in
"didChangeCurrentAudioDevice" which indicates the "updatedAudioDevice" value is "speaker". but immediately after "didChangeCurrentAudioDevice" call it throw error in "didFailToChangeAudioDeviceWithError".

Can you please help me out in this?

**Comment by rajanshahsa** [comment]
I write this code in didReceiveNewSession now before accepting the call. Still it give me error. and then I hangup the call and call again than it works fine. And I am able to hear the audio via Speaker.

**Comment by Raikerian** [comment]
Hi,

Why do you deinitialize audio session right after initializing it? Makes no sense, check https://quickblox.com/developers/Sample-webrtc-ios#Audio_Session_.28Previously_Sound_Router.29

Initialize before call start, deinitialize after call end.

**Comment by rajanshahsa** [comment]
@Raikerian Thank you for answer. I had remove that line and it works fine. Sorry I forgot to close the ticket.
