### ISSUE TITLE
How to record and Save Video call in iOS ?? 

### ISSUE THREAD

**Issue by DhiruServer** [QuickBlox/quickblox-ios-sdk#801]
i have integrated my project with **QuickBlox** Video calling . that is working fine 
but my requirement  to record the Video whole video conversations  ie .  **OpponentVideo**  and **LocalVideo** , how can i do this using QuickBlox ios SDK .

please help me out ,,,, thanks !

**Comment by Raikerian** [comment]
Hi,

We are currently working on this and will provide solution soon.

**Comment by DhiruServer** [comment]
ok ,

**Comment by Raikerian** [comment]
The recorder is now available in QuickbloxWebRTC SDK v2.6:
https://quickblox.com/developers/Sample-webrtc-ios#Framework_changelog

Check short usage guideline and requirements here: https://quickblox.com/developers/Sample-webrtc-ios#Recording_audio_and_video_calls
