### ISSUE TITLE
Blocked User still can send message and other user is receiving.

### ISSUE THREAD

**Issue by unoiatech** [QuickBlox/quickblox-ios-sdk#802]
I am working with the block functionality using quickblox. I am able to block user.  Here are logs of privacyList:
```
[PrivacyList name: public]
	 privacyItems: (
    "
   type: GROUP_USER_ID
    userID: 26886220
    action: deny
    mutualBlock: NO",
    "
   type: GROUP_USER_ID
    userID: 27143502
    action: deny
    mutualBlock: NO",
    "
   type: GROUP_USER_ID
    userID: 26977459
    action: deny
    mutualBlock: NO"
)
```
For some reason, I am using groupChat for 2 users. 

**Expected behavior**
The blocked should not be aware that he has been blocked and should be able to send message. But the other user (who blocked the user) should not receive any message from blocked user.

**Actual behavior**
User is getting blocked . But blocked user is able to send message and receiver is receiving and getting notified about the message.

**Any others comments?**

 I tried the block functionality in other apps e.g Whatsapp. They just block user from 1-1 chats but blocked user can send messages in group and other user receives the messages. 
Is it possible to block user in group chat ? If yes, please correct me if I am doing something wrong.

**Comment by VitaliyGuru** [comment]
@unoiatech, Our QA team has tested privacy list workflow and confirmed that user doesn't receive the message from the blocked user in group chat.
Could you please provide code snippet and logs?
