### ISSUE TITLE
How to send video file as attachment in quickblox iOS?

### ISSUE THREAD

**Issue by akashthakkar09** [QuickBlox/quickblox-ios-sdk#807]
iOS version : 10.3
Quickblox iOS SDK version : 2.9.2

Quickblox iOS Video Attachments

I have integrated Quickblox iOS (Objc) Library into my app for chat module.

Images as an attachment under QBRequest TUploadFile method is possible. But I can't find any working solution to make a video attachment file under the same request.

I have confirmed by reading a document from Quickblog which says - Video attachment possible under Quickblox chat SDK.

Do anyone has any working solution to make video file attachment with this?

Below code is written to upload a video under QBRequest TUploadFile.

Thanks in advance!

**Image Attachment code**

```
NSString *filePath1 = [[NSBundle mainBundle] pathForResource:@"small" ofType:@"mp4"];
    NSError *error = nil;
    NSData *videoData = [NSData dataWithContentsOfFile:filePath1 options:nil error:&error];
     __weak __typeof(self)weakSelf = self;

- (void)uploadAndSendAttachmentMessage:(QBChatMessage*)message toDialog:(QBChatDialog*)dialog withChatService:(QMChatService*)chatService withAttachedVideo:(NSData*)videoData completion:(QBChatCompletionBlock)completion {
    [self changeMessageAttachmentStatus:QMMessageAttachmentStatusLoading forMessage:message];

    [QBRequest TUploadFile:videoData fileName:@"attachment video" contentType:@"video/mp4" isPublic:YES successBlock:^(QBResponse* response, QBCBlob* blob) {
        QBChatAttachment* attachment = [QBChatAttachment new];
        attachment.type = @"video";
        attachment.ID = blob.UID;
        attachment.url = [blob publicUrl];

        message.attachments = @[attachment];
        message.text = @"Attachment video";

        [self saveData:videoData chatAttachment:attachment error:nil];
        [self.attachmentsStorage setObject:videoData forKey:attachment.ID];

        [self changeMessageAttachmentStatus:QMMessageAttachmentStatusLoaded forMessage:message];

        [chatService sendMessage:message type:QMMessageTypeText toDialog:dialog saveToHistory:YES saveToStorage:YES completion:completion];
    } statusBlock:^(QBRequest* request, QBRequestStatus* status) {
        if ([self.delegate respondsToSelector:@selector(chatAttachmentService:didChangeUploadingProgress:forMessage:)]) {
            [self.delegate chatAttachmentService:self didChangeUploadingProgress:status.percentOfCompletion forMessage:message];
        }
    } errorBlock:^(QBResponse* response) {
        [self changeMessageAttachmentStatus:QMMessageAttachmentStatusNotLoaded forMessage:message];

        if (completion) {
            completion(response.error.error);
        }
    }];
}

```

**Logs**

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSConcreteData size]: unrecognized selector sent to instance 0x61000046da80'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010c2cfb0b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000010bd34141 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010c33f134 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x000000010c256840 ___forwarding___ + 1024
	4   CoreFoundation                      0x000000010c2563b8 _CF_forwarding_prep_0 + 120
	5   UIKit                               0x000000010812ecdc -[UIImageView _updateImageViewForOldImage:newImage:] + 731
	6   UIKit                               0x000000010812a43e -[UIImageView setImage:] + 387
	7   QMCVDevelopment                     0x0000000107af0298 -[QMChatAttachmentOutgoingCell setAttachmentImage:] + 152
	8   samplechat                          0x0000000107846603 __64-[ChatViewController collectionView:configureCell:forIndexPath:]_block_invoke + 499
	9   QMServicesDevelopment               0x0000000107b9efd6 -[QMChatAttachmentService imageForAttachmentMessage:completion:] + 614
	10  samplechat                          0x0000000107846248 -[ChatViewController collectionView:configureCell:forIndexPath:] + 4024
	11  QMCVDevelopment                     0x0000000107b0632f -[QMChatViewController collectionView:cellForItemAtIndexPath:] + 591
	12  UIKit                               0x000000010884c9b1 -[UICollectionView _createPreparedCellForItemAtIndexPath:withLayoutAttributes:applyAttributes:isFocused:notify:] + 446
	13  UIKit                               0x000000010884c7ed -[UICollectionView _createPreparedCellForItemAtIndexPath:withLayoutAttributes:applyAttributes:] + 35
	14  UIKit                               0x000000010886b220 __51-[UICollectionView _viewAnimationsForCurrentUpdate]_block_invoke.1941 + 564
	15  UIKit                               0x0000000108868647 -[UICollectionView _viewAnimationsForCurrentUpdate] + 5141
	16  UIKit                               0x000000010886dc7f __71-[UICollectionView _updateWithItems:tentativelyForReordering:animator:]_block_invoke.2012 + 197
	17  UIKit                               0x0000000107fd2d3e +[UIView(Animation) performWithoutAnimation:] + 90
	18  UIKit                               0x000000010886c8b9 -[UICollectionView _updateWithItems:tentativelyForReordering:animator:] + 3856
	19  UIKit                               0x0000000108866bbf -[UICollectionView _endItemAnimationsWithInvalidationContext:tentativelyForReordering:animator:] + 17030
	20  UIKit                               0x000000010886f259 -[UICollectionView _endUpdatesWithInvalidationContext:tentativelyForReordering:animator:] + 71
	21  UIKit                               0x000000010886f5a0 -[UICollectionView _performBatchUpdates:completion:invalidationContext:tentativelyForReordering:animator:] + 437
	22  UIKit                               0x000000010886f3c8 -[UICollectionView _performBatchUpdates:completion:invalidationContext:tentativelyForReordering:] + 91
	23  UIKit                               0x000000010886f34a -[UICollectionView _performBatchUpdates:completion:invalidationContext:] + 74
	24  UIKit                               0x000000010886f29f -[UICollectionView performBatchUpdates:completion:] + 53
	25  QMCVDevelopment                     0x0000000107b01445 -[QMChatViewController changeDataSource:withMessages:updateType:] + 485
	26  QMCVDevelopment                     0x0000000107af9710 __63-[QMChatDataSource changeDataSourceWithMessages:forUpdateType:]_block_invoke_2 + 272
	27  libdispatch.dylib                   0x000000010c95905c _dispatch_client_callout + 8
	28  libdispatch.dylib                   0x000000010c93c0f8 _dispatch_barrier_sync_f_slow_invoke + 579
	29  libdispatch.dylib                   0x000000010c95905c _dispatch_client_callout + 8
	30  libdispatch.dylib                   0x000000010c93a40b _dispatch_main_queue_callback_4CF + 411
	31  CoreFoundation                      0x000000010c294909 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	32  CoreFoundation                      0x000000010c25aae4 __CFRunLoopRun + 2164
	33  CoreFoundation                      0x000000010c25a016 CFRunLoopRunSpecific + 406
	34  GraphicsServices                    0x000000010ed86a24 GSEventRunModal + 62
	35  UIKit                               0x0000000107f1b0d4 UIApplicationMain + 159
	36  samplechat                          0x000000010784c41f main + 111
	37  libdyld.dylib                       0x000000010c9a565d start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by VitaliyGuru** [comment]
@akashthakkar09, From your stack trace:
```
5 UIKit 0x000000010812ecdc -[UIImageView _updateImageViewForOldImage:newImage:] + 731
6 UIKit 0x000000010812a43e -[UIImageView setImage:] 
```
Looks like you're trying to set incorrect object type for UIImageView. 
Could you please enable breakpoints for all exceptions and show me the line, where the crash appeared?

**Comment by Pro100Andrey** [comment]
Hi @akashthakkar09, Any updates ?

**Comment by arpitjain03** [comment]
Firstly get the local video URL using Photo Library or Camera. Then proceed as follows:

```
let message = QBChatMessage()
message.senderID = (self.senderID)
message.dialogID = self.chatDialogModel.id
message.dateSent = Date()

let attachment = QBChatAttachment.videoAttachment(withFileURL: url)        
self.chatDataSource.add(message)

ServicesManager.instance().chatService.sendAttachmentMessage(message, to: self.chatDialogModel, with: attachment, completion: { (error) in
        
        self.attachmentCellsMap.removeObject(forKey: message.id as AnyObject?)
        guard error != nil else { return }
        self.chatDataSource.delete(message)
})

```
