### ISSUE TITLE
How to Processing GPUImageVideoCamera as CMSampleBufferRef for QuickBlox SDK 

### ISSUE THREAD

**Issue by bianchenglongRC** [QuickBlox/quickblox-ios-sdk#808]
**Environment details**
*iOS version : 10.3,Quickblox iOS SDK version : 2.9.2

Add GPUImage to QuickBlox

I add GPUimage to quickblox
This is my code:
 __weak GPUImageRawDataOutput *weakOutput = _rawDataOutput;

    [_rawDataOutput setNewFrameAvailableBlock:^{
        @autoreleasepool {
            NSLog(@"=============================================");
            [weakOutput lockFramebufferForReading];

            GLubyte *outputBytes = [weakOutput rawBytesForImage];

            NSInteger bytesPerRow = [weakOutput bytesPerRowInOutput];

            CVPixelBufferRef pixelBuffer = NULL;

            OSStatus result = CVPixelBufferCreateWithBytes(kCFAllocatorDefault, 240, 320, kCVPixelFormatType_32BGRA, outputBytes, bytesPerRow, nil, nil, nil, &pixelBuffer);

            CMVideoFormatDescriptionRef videoInfo = NULL;

            result = CMVideoFormatDescriptionCreateForImageBuffer(NULL, pixelBuffer, &videoInfo);

            CMSampleTimingInfo sampleTimimgInfo;

            CMSampleBufferRef sampleBuffer = NULL;

            result = CMSampleBufferCreateForImageBuffer(kCFAllocatorDefault, pixelBuffer, true, NULL, NULL, videoInfo, &sampleTimimgInfo, &sampleBuffer);

            [weakSelf processVideoSampleBuffer:sampleBuffer];

            [weakOutput unlockFramebufferAfterReading];

            CFRelease(pixelBuffer);
        }
    }];

-(void) processVideoSampleBuffer:(CMSampleBufferRef)sampleBuffer

{
    
    CVPixelBufferRef pixelBuffer = CMSampleBufferGetImageBuffer(sampleBuffer);
    
    CVPixelBufferLockBaseAddress(pixelBuffer, kCVPixelBufferLock_ReadOnly);
    
    QBRTCVideoFrame *videoFrame = [[QBRTCVideoFrame alloc] initWithPixelBuffer:pixelBuffer videoRotation:QBRTCVideoRotation_0];
    [super sendVideoFrame:videoFrame];

    CVPixelBufferUnlockBaseAddress(pixelBuffer, kCVPixelBufferLock_ReadOnly);

}

but it's does not work, please help me.

**Logs**
 2017-05-22 15:55:30.727 rtc::Video capturer received unsupported non-planar frame format.

**Comment by Raikerian** [comment]
Hi,

Use either kCVPixelFormatType_420YpCbCr8BiPlanarFullRange or kCVPixelFormatType_32ARGB as they are the only ones that currently supported by our WebRTC SDK.

**Comment by bianchenglongRC** [comment]
so I should fix it like this: 
     OSStatus result = CVPixelBufferCreateWithBytes(kCFAllocatorDefault, 240, 320, kCVPixelFormatType_420YpCbCr8BiPlanarFullRange, outputBytes, bytesPerRow, nil, nil, nil, &pixelBuffer); or kCVPixelFormatType_32ARGB

**Comment by bianchenglongRC** [comment]
@Raikerian I try it(use kCVPixelFormatType_420YpCbCr8BiPlanarFullRange),but it put same logs.

**Comment by Raikerian** [comment]
You need to convert your image data from kCVPixelFormatType_32BGRA to one of our supported formats.

**Comment by bianchenglongRC** [comment]
Could this be a wrong method?
CVPixelBufferCreateWithBytes(kCFAllocatorDefault, 240, 320, kCVPixelFormatType_420YpCbCr8BiPlanarFullRange, outputBytes, bytesPerRow, nil, nil, nil, &pixelBuffer);

**Comment by bianchenglongRC** [comment]
@Raikerian  Could this be a wrong method?
CVPixelBufferCreateWithBytes(kCFAllocatorDefault，240,320，kCVPixelFormatType_420YpCbCr8BiPlanarFullRange，outputBytes，bytesPerRow，nil，nil，nil，＆pixelBuffer); thanks

**Comment by Raikerian** [comment]
I suspect your raw data (bytes) are in kCVPixelFormatType_32BGRA format. You cannot just create it with any format you want. Need to convert them.

**Comment by bianchenglongRC** [comment]
- (void)p_initGPUImageFilters {
    
    self.videoCamera = [[GPUImageVideoCamera alloc] initWithSessionPreset:AVCaptureSessionPresetHigh cameraPosition:AVCaptureDevicePositionFront];
    self.videoCamera.outputImageOrientation = UIInterfaceOrientationPortrait;
    self.videoCamera.horizontallyMirrorFrontFacingCamera = YES;
    self.videoCamera.delegate = self;
    self.filterView = [[GPUImageView alloc] initWithFrame:_showFrame];
    self.filterView.fillMode = kGPUImageFillModePreserveAspectRatioAndFill;
    self.spafilter = [[GPUImageSmoothToonFilter alloc] init];
    self.rawDataOutput = [[GPUImageRawDataOutput alloc] initWithImageSize:CGSizeMake(240, 320) resultsInBGRAFormat:NO];
    
    [self.videoCamera addTarget:self.filterView];
    [self.filterView addTarget:self.filterView];
    [self.filterView addTarget:self.rawDataOutput];
    __weak typeof(self) weakSelf = self;
    __weak GPUImageRawDataOutput *weakOutput = self.rawDataOutput;
    [self.rawDataOutput setNewFrameAvailableBlock:^{
        @autoreleasepool {
            [weakOutput lockFramebufferForReading];
            GLubyte *outputBytes = [weakOutput rawBytesForImage];
            NSInteger bytesPerRow = [weakOutput bytesPerRowInOutput];
            CVPixelBufferRef pixelBuffer = NULL;
            CVPixelBufferCreateWithBytes(kCFAllocatorDefault, 240, 320, kCVPixelFormatType_420YpCbCr8BiPlanarFullRange, outputBytes, bytesPerRow, nil, nil, nil, &pixelBuffer);
            [weakSelf processVideoSampleBuffers:pixelBuffer];
            [weakOutput unlockFramebufferAfterReading];
        }
    }];
}

-(void) processVideoSampleBuffers:(CVPixelBufferRef)sampleBuffer
{
    QBRTCVideoFrame *videoFrame = [[QBRTCVideoFrame alloc] initWithPixelBuffer:sampleBuffer videoRotation:QBRTCVideoRotation_0];
    [super sendVideoFrame:videoFrame];
}

That is my whole code,I can't find where is wrong.please help me. Thanks @Raikerian !

**Comment by Pro100Andrey** [comment]
Hi @bianchenglongRC, you can use vImage within the Accelerate framework to do a NEON-optimized color component swap using code:

```objc
vImage_Buffer src;
src.height = height;
src.width = width;
src.rowBytes = srcBytesPerRow;
src.data = srcRows;

vImage_Buffer dest;
dest.height = height;
dest.width = width;
dest.rowBytes = destBytesPerRow;
dest.data = destRows;

/*
The map describing the permutation of the 4 color channels.
 Each value in the map must be 0,1,2, or 3.  A map of 0,1,2,3
 is a copy from src->dest while a map of 3,2,1,0 is permutes
 ARGB -> BGRA.  Providing a map value greater than 3 will
 result in the return of error kvImageInvalidParameter.
*/
// Swap pixel channels from BGRA to ARGB.
const uint8_t map[4] = { 3,2,1,0 };
vImagePermuteChannels_ARGB8888(&src, &dest, map, kvImageNoFlags);
```

**Comment by bianchenglongRC** [comment]
Hello @Pro100Andrey ,I will try it. Thanks!

**Comment by Pro100Andrey** [comment]
Hi @bianchenglongRC, any updates ?

**Comment by bianchenglongRC** [comment]
Yeah,after i tried it, it crashed. But i found i would not transform it.Because someone sdk i had sovled it.And your solution i would try again. So thank you very much! @Pro100Andrey

**Comment by Pro100Andrey** [comment]
Hi @bianchenglongRC, any updates ?

**Comment by bianchenglongRC** [comment]
My boss said  we won't use Gpuimage for the time being,So I haven't time for try it.So sorry. @Pro100Andrey

**Comment by Raikerian** [comment]
Any updates on this? Can we close this issue?
