### ISSUE TITLE
Difficulty to retrieve typing status of opponent in private dialog.

### ISSUE THREAD

**Issue by anismansuri** [QuickBlox/quickblox-ios-sdk#810]
*Help avoid duplicate issue reports, check [existing issues](https://github.com/QuickBlox/quickblox-ios-sdk/issues)*
 
**Environment details**
*iOS version, Quickblox iOS SDK version, QuickbloxWebRTC SDK version (optional)*
'QuickBlox', '> 2.9'
'QMServices', '> 0.4'

**Did this work before?**
No

**Expected behavior**
In private dialog both user can see typing status of one another.
After sending image.

**Actual behavior**
After sending image from user 1 to user 2. User 1 can't see the status of user 2 typing.
    And if user 1 goes to chatlist and come back user 2 dialog then it start working again.

**Steps to reproduce the behavior**
send image to user 2 from user 1.
and start typing in user 2.
User 1 will not be able to detect if user is typing.

**Any others comments?**

**Comment by anismansuri** [comment]
Has anyone idea regarding this issue?

**Comment by Raikerian** [comment]
Hi,

Have you followed the documentation? https://quickblox.com/developers/SimpleSample-chat_users-ios#Typing_status

**Comment by Pro100Andrey** [comment]
hi @anismansuri, Any updates?
