### ISSUE TITLE
Add new user in group audio call and cancel calls between users group

### ISSUE THREAD

**Issue by hirents** [QuickBlox/quickblox-ios-sdk#811]
Hello,
I'm trying to implement audio calls between the groups in iOS,
1.)Suppose UserA and UserB is connected with each other now add new userC can we add?
if i add so again session created but my old session for userA and userB this is already connected ago.
2.)for some reason I'm not able to clear session with all connected users group.
for example userA is host and userB, userC is receivers. after accepting call all connected to each other.
now question is host UserA cancel call he is left from userB and userC but did not cancel from userB and userC they are connected untill. while host cancel call should be cancel from all group users.

**Comment by Raikerian** [comment]
Hi,

Adding users to current call are not supported for now as group call is a part of p2p call.
There is Enterprise-only solution for now, where you can join and leave group video chats at any time, read more here: https://quickblox.com/developers/EnterpriseFeatures#Conference_video_calls

**Comment by hirents** [comment]
Hello Raikerian,
Understand your first answer but what about second point.

**Comment by Raikerian** [comment]
All users in regular calls are connected to each other. That means that there is no host. If you want to implement such feature, you need to check who is hanging up current call. If the user who did hang up is the initiator, then just leave the call for everyone else.
