### ISSUE TITLE
apple mach-o linker error group while integrate quickblox in ios

### ISSUE THREAD

**Issue by NaveenChatla** [QuickBlox/quickblox-ios-sdk#813]
*Help avoid duplicate issue reports, check [existing issues](https://github.com/QuickBlox/quickblox-ios-sdk/issues)*
 
**Environment details**
*iOS version, Quickblox iOS SDK version, QuickbloxWebRTC SDK version (optional)*

**Did this work before?**

**Expected behavior**

**Actual behavior**

**Logs**
*Attach full logs that will describe your problem (please, use github [gist](https://gist.github.com/))*

**Steps to reproduce the behavior**

**Any others comments?**

**Comment by VitaliyGuru** [comment]
@NaveenChatla, Could you please attach test project with this issue being reproducible?
