### ISSUE TITLE
Check for opponent's busyness before starting call

### ISSUE THREAD

**Issue by Shamsiddin** [QuickBlox/quickblox-ios-sdk#814]
**Environment details**
iOS version: 9.3.2
Quickblox iOS SDK version: 2.7.6
QuickbloxWebRTC SDK version: 2.2
Language: Objective-C
XCode version: 8.1

**Did this work before?**
I don't know if this functionality is implemented. At least I couldn't find anything about it from actual documentations.

**Any others comments?**
My question is that how can I check if the user (opponent) is busy before starting my audio/video call? That way I would prevent sending unnecessary calling push notification to the user.
My actual calling code is like below:

```
NSArray *opponentsIDs = @[@(5130147)];
QBRTCSession *newSession = [QBRTCClient.instance createNewSessionWithOpponents:opponentsIDs withConferenceType:QBRTCConferenceTypeVideo];
[newSession startCall:nil];

// here's code for sending push notification with the text: "Incoming video call from Teshavoy"
```

As you can see, I don't know if opponent busy or not, but sending calling push notification.
So please help me how can I check user's busyness.

**Comment by Shamsiddin** [comment]
**Will I get an answer from support team side?**

**Comment by Shamsiddin** [comment]
Anybody from support team?

**Comment by Raikerian** [comment]
Hi,

You cannot know for sure that your opponent is in call, unless you store some kind of status when you are accepting call. You can also hangup new session on receiver side if you already have one.

**Comment by Shamsiddin** [comment]
Yes, I definitely hang up new received session if I already have one, but it doesn't prevent caller side from sending unnecessary calling notification like `"Incoming video call from ..."`.
Your suggestion can't help to stop caller user from sending a notification.

**Comment by Raikerian** [comment]
Just don't show the incoming video call when hanging up a new session. I don't really see any issues here. You cannot forbid some one to call you, unless that person will know for sure that you are busy (hold a status somewhere if you really need this).

**Comment by Pro100Andrey** [comment]
Hi @Shamsiddin, any updates ?

**Comment by Shamsiddin** [comment]
Hi @Pro100Andrey 

@Raikerian offered that I need to store this status somewhere on my server and check for this status if my opponent is in call at the moment or not. Of course I can do this, but I want that Quickblox gave me this opportunity. It would be great if I can get this status from Quickblox.
I don't want to send push notification to opponent if it's in call, before sending push-notification, or calling I need to know status of the User.

**Comment by Raikerian** [comment]
@Shamsiddin you can use Quickblox of course. Take a look at our custom objects module https://quickblox.com/developers/SimpleSample-customObjects-ios
You can store information there.

**Comment by Shamsiddin** [comment]
Hi @Raikerian thanks for your quick response.

Why QuickbloxWebRTC itself doesn't have this functionality? Storing statuses on custom objects module means responsibility for controlling this status value is on my responsibility. I want that QuickbloxWebRTC gave this status like a checking for opponents online/offline status

**Comment by Raikerian** [comment]
All calls are made with peer to peer technology. There is no server involved technically, therefore there is nowhere to store your call status. Only the user himself can answer whether he is in call or not.
