### ISSUE TITLE
Quiclblox User fetch 404 error Swift 3

### ISSUE THREAD

**Issue by primeappsin** [QuickBlox/quickblox-ios-sdk#815]
Getting error 404 always

ServicesManager.instance().downloadCurrentEnvironmentUsers(successBlock: { (users) -> Void in
                        
                        guard let unwrappedUsers = users else {
                            
                            SVProgressHUD.showError(withStatus: "No users downloaded")
                            return
                        }
                        
                        SVProgressHUD.showSuccess(withStatus: "SA_STR_COMPLETED".localized())
                        
                        
                    }, errorBlock: { (error) -> Void in
                        
                        SVProgressHUD.showError(withStatus: error.localizedDescription)
                    })

**Comment by VitaliyGuru** [comment]
@primeappsin, Look's like you have a [similar issue](https://github.com/QuickBlox/quickblox-ios-sdk/issues/382#issuecomment-205324585).

**Comment by primeappsin** [comment]
I have check Allow to retrieve a list of users and add tags the also getting 404 error

**Comment by VitaliyGuru** [comment]
@primeappsin  Is this issue reproducible in our sample?
Please take a look at [this comment](https://github.com/QuickBlox/quickblox-ios-sdk/issues/780#issuecomment-291423846)(Second answer)

**Comment by primeappsin** [comment]
![screen shot 2017-06-07 at 10 23 39 pm](https://user-images.githubusercontent.com/29257950/26891042-42c168e2-4bd1-11e7-9234-1544f30869bf.png)
![screen shot 2017-06-07 at 10 25 53 pm](https://user-images.githubusercontent.com/29257950/26891043-43055c8c-4bd1-11e7-8092-4281ab0ded5b.png)
Not getting sender name chat display sender id ,

**Comment by VitaliyGuru** [comment]
@primeappsin, You should add `DEV=1` for debug Preprocessor Macros.

**Comment by primeappsin** [comment]
![screen shot 2017-06-08 at 2 32 21 pm](https://user-images.githubusercontent.com/29257950/26920752-a224eb52-4c57-11e7-8828-7a71b659a9bd.png)

Getting same issue error 404........ ;(

**Comment by primeappsin** [comment]
Can u plz let us know any other solution @VitaliyGuru

**Comment by VitaliyGuru** [comment]
@primeappsin, Could you please enable full logs and send us this information?

```
[QBSettings setLogLevel:QBLogLevelDebug];
[QBSettings enableXMPPLogging];
```

**Comment by primeappsin** [comment]
Sure...Below is the log for that:

2017-06-08 16:22:05.052 FNTSYRadioApp[6541:128977] [QBCore] Request URL:https://api.quickblox.com/users/by_tags.json?page=1&per_page=100&tags=
2017-06-08 16:22:05.052 FNTSYRadioApp[6541:128977] [QBCore] Request method: GET
2017-06-08 16:22:05.052 FNTSYRadioApp[6541:128977] [QBCore] Request parameters:{
    page = 1;
    "per_page" = 100;
    tags = "";
}
2017-06-08 16:22:05.052 FNTSYRadioApp[6541:128977] [QBCore] Request headers: {
    "Accept-Language" = "en;q=1";
    "QB-OS" = "iOS 10.3";
    "QB-SDK" = "iOS 2.9.2";
    "QB-Token" = d2ea5c3154fc4a1a15b758ec22ce06f7ed00e496;
    "QuickBlox-REST-API-Version" = "0.1.1";
    "User-Agent" = "FNTSYRadioApp/2.5 (iPhone; iOS 10.3; Scale/2.00)";
}
2017-06-08 16:22:05.057 FNTSYRadioApp[6541:129303] [Core] Set default chat endpoint for QBConnectionZoneTypeAutomatic
2017-06-08 16:22:05.075 FNTSYRadioApp[6541:128977] [QMChatCache] Dialogs to insert 0, update 0
2017-06-08 16:22:05.964 FNTSYRadioApp[6541:128977] [QBCore] Response error: Error Domain=com.alamofire.error.serialization.response Code=-1011 "Request failed: not found (404)" UserInfo={com.alamofire.serialization.response.error.response=<NSHTTPURLResponse: 0x6000000393c0> { URL: https://api.quickblox.com/users/by_tags.json?page=1&per_page=100&tags= } { status code: 404, headers {
    "Access-Control-Allow-Origin" = "*";
    "Cache-Control" = "no-cache";
    Connection = "keep-alive";
    "Content-Length" = 44;
    "Content-Type" = "application/json; charset=utf-8";
    Date = "Thu, 08 Jun 2017 10:52:17 GMT";
    "QB-Token-ExpirationDate" = "2017-06-08 12:39:05 +0000";
    "QuickBlox-REST-API-Version" = "0.1.1";
    Server = "openresty/1.9.15.1";
    Status = "404 Not Found";
    "Strict-Transport-Security" = "max-age=31536000";
    "X-Content-Type-Options" = nosniff;
    "X-Frame-Options" = SAMEORIGIN;
    "X-Request-Id" = "a36952d0-0dce-4925-a0d5-d4dc53ae6ade";
    "X-Runtime" = "0.014243";
    "X-XSS-Protection" = "1; mode=block";
} }, NSErrorFailingURLKey=https://api.quickblox.com/users/by_tags.json?page=1&per_page=100&tags=, com.alamofire.serialization.response.error.data=<7b22636f 6465223a 6e756c6c 2c226d65 73736167 65223a22 436f756c 646e2774 2066696e 64207573 6572227d>, NSLocalizedDescription=Request failed: not found (404)}





*************************************************
Please take a look and let us know for it.
Thanks

**Comment by VitaliyGuru** [comment]
@primeappsin, from logs I've noticed that you're setting empty string for tags.
The method `downloadCurrentEnvironmentUsers` takes tags from the method:
```objective-c
- (NSString *)currentEnvironment {
    NSString* environment = nil;
#if DEV
    environment = @"dev";
#endif
    
#if QA
    environment = @"qbqa";
#endif
    
    return environment;
}
```
DEV and QA are proprocessor macroses. Please recheck.

**Comment by VitaliyGuru** [comment]
@primeappsin, BTW, getting users by tags is not the only one way for users retrieving.
Please take a look at [users doumentation].

**Comment by primeappsin** [comment]
Hi VitaliyGuru,
Yes I have also noticed the same thing,
and found that there is Not supported build configuration that is why it goes blank in TAG field.
So I need to check that now.
Thanks for the great support.
:)

**Comment by VitaliyGuru** [comment]
@primeappsin, Any updates?
