### ISSUE TITLE
Sender ID Not displayi

### ISSUE THREAD

**Issue by primeappsin** [QuickBlox/quickblox-ios-sdk#816]
![screen shot 2017-06-07 at 9 51 04 pm](https://user-images.githubusercontent.com/29257950/26889373-a4605d16-4bcb-11e7-9a0b-e1b8f445f037.png)

**Comment by primeappsin** [comment]
Not getting send name in iOS sdk get sender id

**Comment by VitaliyGuru** [comment]
@primeappsin, You should get user by id.
```objective-c
        QBUUser *user;
        [QBRequest userWithID:user.ID
                 successBlock:^(QBResponse * _Nonnull response, QBUUser * _Nullable user) {
                    
                 }
                   errorBlock:^(QBResponse * _Nonnull response) {
                       
                   }];
```

And then get his full name or login in success block.

To avoid performance issues you should cache retrieved user.

Take a look at [QMServices](https://github.com/QuickBlox/q-municate-services-ios). Their main feature is inbox persistent and memory storage for messages, dialogs, and users.

**Comment by VitaliyGuru** [comment]
@primeappsin, Any updates?
