### ISSUE TITLE
[Question] Is 1-to-many broadcast available in QuickbloxWebRTC yet? 

### ISSUE THREAD

**Issue by hoangelec** [QuickBlox/quickblox-ios-sdk#819]
Hello team, 
I have a plan to develop and iOS app in which a user can broadcast a live stream video room, and then others can join in and then cumulatively share their stream others within the same room. 

However from what I read in your sample (https://quickblox.com/developers/Sample-webrtc-ios), a call session can only be established when a user accepts a call from another. 

I just want to ask if there is a workaround that I can use to implement my idea with Quickblox ?
Thanks in advance

**Comment by Raikerian** [comment]
Hi,

The case you have described is possible to do by using our Enterprise-only feature: https://quickblox.com/developers/EnterpriseFeatures#Conference_video_calls

It's not really possible with just p2p calls without the server (at least for now).
