### ISSUE TITLE
Call drops after random time interval

### ISSUE THREAD

**Issue by hiteshagja** [QuickBlox/quickblox-ios-sdk#821]
I have integrated quickblox refering your webrtc javascript example and I am facing call disconnection issue. Call is getting disconnect between 20-28 seconds. Why is this happening? Is there any API limitation for starter plan? Help me solve this issue.

**Comment by VitaliyGuru** [comment]
@hiteshagja, Your issue should be referred to [JS SDK](https://github.com/QuickBlox/quickblox-javascript-sdk). Closed as invalid.
