### ISSUE TITLE
didReceiveNewSession method is not running.

### ISSUE THREAD

**Issue by syedqamara** [QuickBlox/quickblox-ios-sdk#825]
I am trying to make an Audio Call but on the receiver end i am unable get didReceiveNewSession method trigger. 

> > 2017-06-23 01:55:03.970 rtc::Initializing QBRTCAudioSession using configuration: <QBRTCAudioSessionConfiguration: 0x17265300, Category: AVAudioSessionCategoryPlayAndRecord, Category options: 2, Mode: AVAudioSessionModeVoiceChat>
> 2017-06-23 01:55:04.174 rtc::Current audio device was updated to Receiver
> 2017-06-23 01:55:04.175 rtc::Trying to initialize QBRTCAudioSession while it's already has been initialized. Deinitialize instance first.
> 2017-06-23 01:55:04.183 rtc::Trying to initialize QBRTCAudioSession while it's already has been initialized. Deinitialize instance first.
> 2017-06-23 01:55:04.185 rtc::Trying to initialize QBRTCAudioSession while it's already has been initialized. Deinitialize instance first.
> 2017-06-23 01:55:04.245 rtc::QBRTCAudioSession switched from Speaker to Receiver port. Reason: The category of the session object changed or session was just activated.
> 2017-06-23 01:55:04.300 rtc::[RTCClient] Initializing SSL...
> 2017-06-23 01:55:04.322 rtc::Create audio track: RTCMediaStreamTrack: kind:audio, id:audioTrack, enabled, state:Live
> 2017-06-23 01:55:04.325 rtc::[SESS]<44E49375-5574-47C2-9284-FB9616647BF3, I:28786800, O:[28841924], T:A> Init.
> 2017-06-23 01:55:04.326 rtc::[RTCClient] <QBRTCClient: 0x15f34430> created new [SESS]<44E49375-5574-47C2-9284-FB9616647BF3, I:28786800, O:[28841924], T:A>
> 2017-06-23 01:55:04.327 rtc::[SESS]<44E49375-5574-47C2-9284-FB9616647BF3, I:28786800, O:[28841924], T:A> Start call
> Optional(28786800)
> 2017-06-23 01:55:04.335 rtc::Created local media stream Media stream: ID=com.quickblox.mediastream.device-iphone4,1_ios-9.3.5_userid-28786800] A=1 V=0
> 2017-06-23 01:55:04.382 rtc::[PCON]<28841924, R:Offer> Negotiation
> 2017-06-23 01:55:04.383 rtc::[PCON]<28841924, R:Offer> Create offer
> 2017-06-23 01:55:04.445 rtc::[PCON]<28841924, R:Offer> Signaling state HAVE_LOCAL_OFFER
> 2017-06-23 01:55:04.465 rtc::[PCON]<28841924, R:Offer> Did change ice gethering state to GATHERING
> 2017-06-23 01:55:04.466 rtc::[PCON]<28841924, R:Offer> SND offer SDP
> 2017-06-23 01:55:04.480 rtc::[TASK]<ID:3, l:com.quickblox.connection.dialing.timer> Start.
> 2017-06-23 01:55:04.485 TwinkleApp[1573:223483] [ChatService] Message SNT: <message id="282475249" type="headline" to="28841924-59014@chat.quickblox.com"><extraParams xmlns="jabber:client"><callType>2</callType><sdkVersion>2.6.0.1</sdkVersion><sdp>v=0
> o=- 4738691159933465069 2 IN IP4 127.0.0.1
> s=-
> t=0 0
> a=group:BUNDLE audio
> a=msid-semantic: WMS com.quickblox.mediastream.device-iphone4,1_ios-9.3.5_userid-28786800]
> m=audio 9 UDP/TLS/RTP/SAVPF 102 111 103 9 0 8 105 13 110 113 126
> c=IN IP4 0.0.0.0
> a=rtcp:9 IN IP4 0.0.0.0
> a=ice-ufrag:/Ww7
> a=ice-pwd:zudKcVybWFFDUTXNwhPIj+ze
> a=ice-options:trickle renomination
> a=fingerprint:sha-256 BB:F8:BA:05:ED:21:EF:F5:61:53:27:B6:94:BA:9B:09:DB:93:49:4C:E8:04:45:DD:45:11:48:A2:6D:80:F6:6D
> a=setup:actpass
> a=mid:audio
> a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
> a=sendrecv
> a=rtcp-mux
> a=rtpmap:111 opus/48000/2
> a=rtcp-fb:111 transport-cc
> a=fmtp:111 minptime=10;useinbandfec=1
> a=rtpmap:103 ISAC/16000
> a=rtpmap:9 G722/8000
> a=rtpmap:102 ILBC/8000
> a=rtpmap:0 PCMU/8000
> a=rtpmap:8 PCMA/8000
> a=rtpmap:105 CN/16000
> a=rtpmap:13 CN/8000
> a=rtpmap:110 telephone-event/48000
> a=rtpmap:113 telephone-event/16000
> a=rtpmap:126 telephone-event/8000
> a=ssrc:725945092 cname:rAFk36c/UJPTL58s
> a=ssrc:725945092 msid:com.quickblox.mediastream.device-iphone4,1_ios-9.3.5_userid-28786800] audioTrack
> a=ssrc:725945092 mslabel:com.quickblox.mediastream.device-iphone4,1_ios-9.3.5_userid-28786800]
> a=ssrc:725945092 label:audioTrack
> </sdp><moduleIdentifier>WebRTCVideoChat</moduleIdentifier><sessionID>44E49375-5574-47C2-9284-FB9616647BF3</sessionID><callerID>28786800</callerID><platform>ios</platform><signalType>call</signalType><userInfo><id>28841924</id></userInfo><opponentsIDs><opponentID>28841924</opponentID></opponentsIDs></extraParams></message>
> 2017-06-23 01:55:05.670 rtc::[PCON]<28841924, R:Offer> Did change ice gethering state to COMPLETE
> 2017-06-23 01:55:09.545 rtc::[PCON]<28841924, R:Offer> SND offer SDP
> 2017-06-23 01:55:09.551 TwinkleApp[1573:223483] [ChatService] Message SNT: <message id="1622650073" type="headline" to="28841924-59014@chat.quickblox.com"><extraParams xmlns="jabber:client"><callType>2</callType><sdkVersion>2.6.0.1</sdkVersion><sdp>v=0
> o=- 4738691159933465069 2 IN IP4 127.0.0.1
> s=-
> t=0 0
> a=group:BUNDLE audio
> a=msid-semantic: WMS com.quickblox.mediastream.device-iphone4,1_ios-9.3.5_userid-28786800]
> m=audio 9 UDP/TLS/RTP/SAVPF 102 111 103 9 0 8 105 13 110 113 126
> c=IN IP4 0.0.0.0
> a=rtcp:9 IN IP4 0.0.0.0
> a=ice-ufrag:/Ww7
> a=ice-pwd:zudKcVybWFFDUTXNwhPIj+ze
> a=ice-options:trickle renomination
> a=fingerprint:sha-256 BB:F8:BA:05:ED:21:EF:F5:61:53:27:B6:94:BA:9B:09:DB:93:49:4C:E8:04:45:DD:45:11:48:A2:6D:80:F6:6D
> a=setup:actpass
> a=mid:audio
> a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
> a=sendrecv
> a=rtcp-mux
> a=rtpmap:111 opus/48000/2
> a=rtcp-fb:111 transport-cc
> a=fmtp:111 minptime=10;useinbandfec=1
> a=rtpmap:103 ISAC/16000
> a=rtpmap:9 G722/8000
> a=rtpmap:102 ILBC/8000
> a=rtpmap:0 PCMU/8000
> a=rtpmap:8 PCMA/8000
> a=rtpmap:105 CN/16000
> a=rtpmap:13 CN/8000
> a=rtpmap:110 telephone-event/48000
> a=rtpmap:113 telephone-event/16000
> a=rtpmap:126 telephone-event/8000
> a=ssrc:725945092 cname:rAFk36c/UJPTL58s
> a=ssrc:725945092 msid:com.quickblox.mediastream.device-iphone4,1_ios-9.3.5_userid-28786800] audioTrack
> a=ssrc:725945092 mslabel:com.quickblox.mediastream.device-iphone4,1_ios-9.3.5_userid-28786800]
> a=ssrc:725945092 label:audioTrack
> </sdp><moduleIdentifier>WebRTCVideoChat</moduleIdentifier><sessionID>44E49375-5574-47C2-9284-FB9616647BF3</sessionID><callerID>28786800</callerID><platform>ios</platform><signalType>call</signalType><userInfo><id>28841924</id></userInfo><opponentsIDs><opponentID>28841924</opponentID></opponentsIDs></extraParams></message>

My Chat is Working perfectly so after login i set QBRTCClient delegate and when Application open i am calling QBRTCClient.initialize method but still i am not getting any single log on receiver side when i make a call.

Below is my Call Manager Class..
```
enum CallStates {
    case incomming
    case rejected
    case accepted
    case connected
    case connecting
    case disconnected
    case failed
    case end
    case notRespond
}

class CallManager: NSObject, QBRTCClientDelegate {
    static var shared = CallManager()
    var instance = QBRTCClient.instance()
    var currentSession: QBRTCSession?
    var callStatesHandler: ((CallStates, Int)->Void)?
    var videoTrackHandler: ((QBRTCVideoTrack)->Void)?
    var audioTrackHandler: ((QBRTCAudioTrack)->Void)?
    
    override init() {
        super.init()
        
    }
    func addDelegate() {
        QBRTCClient.instance().add(self)
        QBRTCSession.initialize()
        setBasicRTCConfiguration()
    }
    
    
    func makeAVideoCall(toUserID: Int) {
        let newSession = QBRTCClient.instance().createNewSession(withOpponents: [NSNumber.init(value: toUserID)], with: QBRTCConferenceType.video)
        // userInfo - the custom user information dictionary for the call. May be nil.
        let userInfo :[String:String] = ["id":"\(toUserID)"]
        newSession.startCall(userInfo)
        
    }
    
    func makeAudioCall(toUserID: Int) {
        self.initiateAudioSetting()
        var userID = AppManager.shared.currentUser?.id
        let newSession = QBRTCClient.instance().createNewSession(withOpponents: [NSNumber.init(value: toUserID)], with: QBRTCConferenceType.audio)
        // userInfo - the custom user information dictionary for the call. May be nil.
        let userInfo :[String:String] = ["id":"\(toUserID)"]
        newSession.startCall(userInfo)
        print(userID)
    }
    
    func setBasicRTCConfiguration() {
        let conf = QBRTCMediaStreamConfiguration.default()
        conf.audioCodec = QBRTCAudioCodec.codeciLBC
        QBRTCConfig.setMediaStreamConfiguration(conf)
        
    }
    
    func initiateAudioSetting() {
        QBRTCAudioSession.instance().initialize()
        //OR you can initialize audio session with a specific configuration
        QBRTCAudioSession.instance().initialize { (configuration) -> () in
            // adding blutetooth support
            configuration.categoryOptions = AVAudioSessionCategoryOptions.allowBluetooth
            if #available(iOS 10.0, *) {
                configuration.categoryOptions = AVAudioSessionCategoryOptions.allowBluetoothA2DP
            } else {
                // Fallback on earlier versions
            }
            if #available(iOS 10.0, *) {
                configuration.categoryOptions = AVAudioSessionCategoryOptions.allowAirPlay
            } else {
                // Fallback on earlier versions
            }
            
            if (self.currentSession?.conferenceType == QBRTCConferenceType.video) {
                // setting mode to video chat to enable airplay audio and speaker only for video call
                configuration.mode = AVAudioSessionModeVideoChat
            }
        }
        //Set headphone or phone receiver
        QBRTCAudioSession.instance().currentAudioDevice = QBRTCAudioDevice.receiver
    }
    func deinitializeAudio() {
        QBRTCAudioSession.instance().deinitialize()
    }
    
    func acceptCall() {
        let id = AppManager.shared.currentUser?.id
        let userInfo = ["id": "\(id!)"]
        self.currentSession?.acceptCall(userInfo)
    }
    func rejectCall() {
        let userInfo = ["reason": "Call Rejected"]
        self.currentSession?.rejectCall(userInfo)
        self.currentSession = nil
    }
    func watchForCallState(completion: @escaping (CallStates, Int)->Void) {
        self.callStatesHandler = completion
    }
    func watchForVideo(completion: @escaping (QBRTCVideoTrack)->Void) {
        self.videoTrackHandler = completion
    }
    func watchForAudio(completion: @escaping (QBRTCAudioTrack)->Void) {
        self.audioTrackHandler = completion
    }
    
    
    //Mark: - Delegates
    func session(_ session: QBRTCSession, acceptedByUser userID: NSNumber, userInfo: [String : String]? = nil) {
        guard let completion = self.callStatesHandler else {return}
        completion(.accepted,userID.intValue)
    }
    
    func didReceiveNewSession(_ session: QBRTCSession, userInfo: [String : String]? = nil) {
        if self.currentSession != nil {
            let userInfo = ["reason": "User Busy"]
            session.rejectCall(userInfo)
            return
        }
        self.currentSession = session
        let id = userInfo?["id"] as! Int
        guard let completion = self.callStatesHandler else {return}
        completion(.incomming, id)
    }
    func session(_ session: QBRTCSession, rejectedByUser userID: NSNumber, userInfo: [String : String]? = nil) {
        guard let completion = self.callStatesHandler else {return}
        completion(.rejected,userID.intValue)
        self.deinitializeAudio()
    }
    func session(_ session: QBRTCBaseSession, connectedToUser userID: NSNumber) {
        guard let completion = self.callStatesHandler else {return}
        completion(.connected, userID.intValue)
    }
    func session(_ session: QBRTCBaseSession, connectionClosedForUser userID: NSNumber) {
        guard let completion = self.callStatesHandler else {return}
        completion(.end,userID.intValue)
        self.deinitializeAudio()
    }
    func sessionDidClose(_ session: QBRTCSession) {
        guard let completion = self.callStatesHandler else {return}
        completion(.end,(session.opponentsIDs.first?.intValue)!)
        self.deinitializeAudio()
    }
    func session(_ session: QBRTCBaseSession, startedConnectingToUser userID: NSNumber) {
        guard let completion = self.callStatesHandler else {return}
        completion(.connecting,userID.intValue)
    }
    func session(_ session: QBRTCBaseSession, disconnectedFromUser userID: NSNumber) {
        guard let completion = self.callStatesHandler else {return}
        completion(.disconnected,userID.intValue)
        self.deinitializeAudio()
    }
    func session(_ session: QBRTCSession, userDidNotRespond userID: NSNumber) {
        guard let completion = self.callStatesHandler else {return}
        completion(.notRespond,userID.intValue)
        self.deinitializeAudio()
    }
    func session(_ session: QBRTCBaseSession, connectionFailedForUser userID: NSNumber) {
        guard let completion = self.callStatesHandler else {return}
        completion(.failed,userID.intValue)
        self.deinitializeAudio()
    }
    func session(_ session: QBRTCBaseSession, receivedRemoteVideoTrack videoTrack: QBRTCVideoTrack, fromUser userID: NSNumber) {
        guard let video = self.videoTrackHandler else {return}
        video(videoTrack)
    }
    func session(_ session: QBRTCBaseSession, receivedRemoteAudioTrack audioTrack: QBRTCAudioTrack, fromUser userID: NSNumber) {
        guard let audio = self.audioTrackHandler else {return}
        audio(audioTrack)
    }
    
}
```

**Comment by v-anh** [comment]
How about try "QBRTCSession.initializeRTC()" instead of QBRTCSession.initialize()

**Comment by syedqamara** [comment]
Well i have found the solution. My RTC delegates were set but chat
delegates weren't set at that time and while debugging when i chat delegate
is set it automatically connect the RTC as well.

**Comment by v-anh** [comment]
Hi @syedqamara ,

Did you add "QBChat.initialize()" in your "func addDelegate()" and solved your problem? I have the same issue with you and still not be resolved.

**Comment by Raikerian** [comment]
Hi,

For regular calls, QBChat is the signaling processor. So of course, you need to connect to chat first. Also, don't hesitate to check our video sample in the current repository.

**Comment by v-anh** [comment]
Hi @Raikerian ,

Thanks for your answer, 

I do have connected to QBChat. I have completed make an audio and video call.
 My case is when I'm waking app from VOIP notification for catching the call I always get : 
"[ChatService] Did disconnect with error: Error Domain=QBGCDAsyncSocketErrorDomain Code=7 "Socket closed by remote peer" UserInfo={NSLocalizedDescription=Socket closed by remote peer}"

Maybe that why "didReceiveNewSession" never be call? Could you give me some advice for this?

**Comment by Raikerian** [comment]
Do you perform disconnect from QBChat when going background?

**Comment by Raikerian** [comment]
Let's move to your own issue as this one seems resolved for creator.
