### ISSUE TITLE
Failed to Authorize while SignUp and Login.

### ISSUE THREAD

**Issue by syedqamara** [QuickBlox/quickblox-ios-sdk#828]
I am getting the following response when ever i perform SignUp/Login from my Enterprise account.
I haven't created a single account yet from app but have tried to create manually an account from admin panel and try to login but still get this error. Before this i was successfully running this code on free account but when i change the credentials it stopped working.
I have checked my credentials but they are all perfect.

> 2017-06-30 06:29:59.004 TwinkleApp[3680:615617] [QBCore] Response error: Error Domain=com.alamofire.error.serialization.response Code=-1011 "Request failed: unauthorized (401)" UserInfo={com.alamofire.serialization.response.error.response=<NSHTTPURLResponse: 0x15aa0b50> { URL: https://apiuffbook.quickblox.com/login.json } { status code: 401, headers {
>     "Access-Control-Allow-Origin" = "*";
>     "Cache-Control" = "no-cache";
>     Connection = "keep-alive";
>     "Content-Type" = "application/json; charset=utf-8";
>     Date = "Fri, 30 Jun 2017 01:30:19 GMT";
>     "QB-Token-ExpirationDate" = "2017-06-30 03:29:23 +0000";
>     "QuickBlox-REST-API-Version" = "0.1.1";
>     Server = "nginx/1.10.1";
>     Status = "401 Unauthorized";
>     "Transfer-Encoding" = Identity;
>     "Www-Authenticate" = "OAuth realm=users";
>     "X-Rack-Cache" = "invalidate, pass";
>     "X-Request-Id" = ae1211e53e941a1d207a2e6c9a955ea6;
>     "X-Runtime" = "0.011611";
>     "X-UA-Compatible" = "IE=Edge,chrome=1";
> } }, NSErrorFailingURLKey=https://apiuffbook.quickblox.com/login.json, NSLocalizedDescription=Request failed: unauthorized (401), com.alamofire.serialization.response.error.data=<7b226572 726f7273 223a5b22 556e6175 74686f72 697a6564 225d7d>}

Here is my Framework initialization code and Login/SignUp Code.

```
    static func quickBloxActivationSettings() {
        QBSettings.setApplicationID(UInt(Constants.kQBAppID))
        QBSettings.setAuthKey(Constants.kQBAppKey)
        QBSettings.setAuthSecret(Constants.kQBSecretKey)
        QBSettings.setAccountKey(Constants.kQBAccountID)
        QBSettings.setApiEndpoint(Constants.kAPIDomain, chatEndpoint: Constants.kChatDomain, forServiceZone: QBConnectionZoneType.production)
        QBSettings.setServiceZone(.production)
        QBSettings.setAutoReconnectEnabled(true)
        QBSettings.setCarbonsEnabled(true)
        QBSettings.setLogLevel(QBLogLevel.debug)
        QBSettings.enableXMPPLogging()
        
    }
    
    static func signUpUser(with number: String, completion: @escaping (Void)->Void, failure: @escaping (String)->Void) {
        let newUser = QBUUser()
        newUser.login = number
        newUser.password = Constants.defaultPassword
        newUser.phone = number
        QBRequest.signUp(newUser, successBlock: {response, user in
            AppManager.shared.currentUser = user
            Contacts.shared.fetchAllUser()
            AppDelegate.shared.watchForCalls()
            AppDelegate.shared.registerDeviceForPush()
            completion()
//            print("Response: \(response)\n\nUser: \(user)\n\n")
        }, errorBlock: {error in
            
            if let reason = error.error?.reasons {
                if AppManager.shared.isAlreadyAUser(json: reason) {
                    loginUser(with: number, completion: completion, failure: failure)
                }else {
                    failure(AppManager.shared.getSignUpErrorReason(json: (error.error?.reasons)!))
                }
            }else {
                failure("")
            }
            
        })
    }
    static func loginUser(with number: String, completion: @escaping (Void)->Void, failure: @escaping (String)->Void) {
        let newUser = QBUUser()
        newUser.login = number
        newUser.password = Constants.defaultPassword
        QBRequest.logIn(withUserLogin: number, password: Constants.defaultPassword, successBlock: {response, user in
            AppManager.shared.currentUser = user
            Contacts.shared.fetchAllUser()
            AppDelegate.shared.watchForCalls()
            AppDelegate.shared.registerDeviceForPush()
            completion()
            //Invoke CallBack Method for Loggin Success
        }, errorBlock: { error in
            if let errorString = error.error?.reasons {
                failure(AppManager.shared.getSignUpErrorReason(json: errorString))
            }
            
        })
    }
```

**Comment by VitaliyGuru** [comment]
@syedqamara 

Could you please enable full logs and send us this information?

```
[QBSettings setLogLevel:QBLogLevelDebug];
[QBSettings enableXMPPLogging];
```

Also, recheck your credentials.

**Comment by Raikerian** [comment]
Any update on this?
