### ISSUE TITLE
QBPushNotificationsHeader.h:17:9: 'QuickBlox/QBRequest+QBPushNotifications.h' file not found

### ISSUE THREAD

**Issue by keithslater** [QuickBlox/quickblox-ios-sdk#830]
**Environment details**
QuickBlox version 2.9.2
iOS 10

**Did this work before?**
Not sure, we inherited this project.

**Expected behavior**

**Actual behavior**
I get this error - 

Lexical or Preprocessor Issue Group
QBPushNotificationsHeader.h:17:9: 'QuickBlox/QBRequest+QBPushNotifications.h' file not found

I've tried to uninstall and reinstall. It was running an older version of QuickBlox and I updated to 2.9.2 but still get the same error.

**Comment by keithslater** [comment]
It looks like it's because of this line QuickBlox vs Quickblox

https://github.com/QuickBlox/push-sender-tools/blob/master/ios/Quickblox.framework/Headers/QBPushNotificationsHeader.h#L17

**Comment by Raikerian** [comment]
Hi,

Seems like that line indeed has B as an upper case. But for some reason, it is working in our projects. It will be fixed in our next release, for now, can you fix 1 letter on your own, will it work for you?

**Comment by keithslater** [comment]
Yes, I fixed it for myself. Just wanted to let you guys know so you can fix it in the project. I believe the reason it doesn't work for me is because my code is on a case sensitive partition.

**Comment by Raikerian** [comment]
Glad to hear it worked, thank you for your report, will be available public next release.

**Comment by Pro100Andrey** [comment]
Fixed in 2.10
