### ISSUE TITLE
Forcing Portrait Mode for QBRTCRemoteVideoView

### ISSUE THREAD

**Issue by shalem93** [QuickBlox/quickblox-ios-sdk#831]
*Help avoid duplicate issue reports, check [existing issues](https://github.com/QuickBlox/quickblox-ios-sdk/issues)*
 
**Environment details**
*iOS version, Quickblox iOS SDK version, QuickbloxWebRTC SDK version (optional)*
iOS 10+ QB RTC 2.4+

**Did this work before?**
In reference to #262 , subclassing works for QBRTCCameraCapture but Remote View is not working. Im assuming I still will have to sub-class but I'm having trouble making this work. Any help?

**Expected behavior**
When i turn my phone to landscape, I do not want the camera to try and adjust the orientation.

**Actual behavior**
The camera adjusts to a poor user experience of orientation.

**Logs**
*Attach full logs that will describe your problem (please, use github [gist](https://gist.github.com/))*

**Steps to reproduce the behavior**
Get in a video chat with updated WebRtc on iPhone and turn your phone

**Any others comments?**

**Comment by Raikerian** [comment]
Hi,

Referenced issue was fixed long ago (just update your framework). I don't really understand this part:

> The camera adjusts to a poor user experience of orientation.

Perhaps any screenshots? Also, checkout our video sample in current repository, is the issue persistent there?

**Comment by shalem93** [comment]
Hi I'm using RTC 2.6.1 . It's not fixed, when I rotate the camera rotates. I want it to hold still on the remote view when user rotates the camera. How do I do this?

**Comment by Raikerian** [comment]
Do you mean you want to block orientation change? Then you should look into this https://stackoverflow.com/questions/11785565/how-can-i-disable-landscape-orientation

Camera will be always rotated if application supports such orientation.

**Comment by Pro100Andrey** [comment]
Hi @shalem93, Any updates ?

**Comment by shalem93** [comment]
Hi @Pro100Andrey @Raikerian I am still having this problem. Sorry for the delayed response!

The QBRTCRemoteView is still changing when I rotate my phone despite locking landscape. How do I fix this? The solution in #262 is only for QBRTCVideoView which is my local video stream...
