### ISSUE TITLE
Push Notifications being Backlogged

### ISSUE THREAD

**Issue by shalem93** [QuickBlox/quickblox-ios-sdk#833]
*Help avoid duplicate issue reports, check [existing issues](https://github.com/QuickBlox/quickblox-ios-sdk/issues)*
 
**Environment details**
*iOS version, Quickblox iOS SDK version, QuickbloxWebRTC SDK version (optional)*
iOS 10, Qb 2.9.2, RTC 2.6.1

**Did this work before?**
No

**Expected behavior**
Push notifications fire at time of event

**Actual behavior**
Push notifications getting caught in queue on admin dashboard and sending hours later. It is less than 20/s . It seems very vague. I had updated to your Pro Tier and still had same issues. My push notifications need to be more reliable to my users. Any input?

**Logs**
*Attach full logs that will describe your problem (please, use github [gist](https://gist.github.com/))*

**Steps to reproduce the behavior**

**Any others comments?**

**Comment by Raikerian** [comment]
Hi,

It might be a server-side issue or any other. This is iOS repository. Please contact our support as you are pro-tier user: https://assist.quickblox.com/index.php?/Tickets/Submit
