### ISSUE TITLE
Error: Success or Failure block is not called

### ISSUE THREAD

**Issue by Nik20112** [QuickBlox/quickblox-ios-sdk#835]
*Help avoid duplicate issue reports, check [existing issues](https://github.com/QuickBlox/quickblox-ios-sdk/issues)*
 
**Environment details**
*iOS version, Quickblox iOS SDK version, QuickbloxWebRTC SDK version (optional)*
iOS Version: 10.3
pod 'Quickblox-WebRTC', '~> 2.6'
pod 'QuickBlox'

**Did this work before?**
No. I m working swift 3 and calling the below methods but can't go inside success or error block " debugPrint("Success",response)". But When I enable debug mode its give me the response in log.
    //MARK: - Get Users by RoomName from QuickBlox

    func loadQuickBloxUsersByRoomName()  {
        let page:QBGeneralResponsePage = QBGeneralResponsePage.init(currentPage: 1, perPage: 50, totalEntries: 1000)
        QBRequest.users(withTags: currentUser?.qbuser.tags as! [String], page:page, successBlock: { (response:QBResponse, responsePage:QBGeneralResponsePage,qbuserdata:[QBUUser]) in
            debugPrint("Success",response)
            debugPrint(responsePage)
            debugPrint(qbuserdata)

            if response.isSuccess{
            }
            else{
                messageBox(message: response.error?.description)
            }
            
        } as? (QBResponse, QBGeneralResponsePage?, [QBUUser]?) -> Void) { (response:QBResponse) in
            messageBox(message: response.error?.description)
        }
    }
**Expected behavior**
Its should be working fine because I have  integrated the code in proper way

**Actual behavior**
Success or Failure block is not called

**Logs**
*Attach full logs that will describe your problem (please, use github [gist](https://gist.github.com/))*
https://gist.github.com/Nik20112/f4180debbed4a0c1e550fe04d98cfe5f

**Steps to reproduce the behavior**

**Any others comments?**
 Please resolve it asap

**Comment by Raikerian** [comment]
Hi,

Please attach full logs from app start till problem occurs.

**Comment by Pro100Andrey** [comment]
Hi @Nik20112, Any updates?
