### ISSUE TITLE
Using Quickblox-> Video Not Received!

### ISSUE THREAD

**Issue by sv-dev2** [QuickBlox/quickblox-ios-sdk#837]
Hi

I am using quickblox (iOS Objective-C) to make video calls. I stuck in an issue, the issue is that - when i call the other user sound is coming perfectly but video is not coming. The delegate or function (receivedRemoteVideoTrack) is calling and i set the video track on my view but nothing is happend and video is not coming. I do the all stuff and make all possible changes but i cant solved my problem. i am attaching my class for furthur details, so you can check this, and please tell me where i was wrong or missing somthing.
[SpecialistCallingVC.m.zip](https://github.com/QuickBlox/quickblox-ios-sdk/files/1162213/SpecialistCallingVC.m.zip)

Thanx in advance :)

**Comment by Raikerian** [comment]
Hi,

You can check our video sample in current repository, it is written in objc and it should give you the right idea of what's wrong with your code.

**Comment by Pro100Andrey** [comment]
Hi @sv-dev2, could you please provide logs + stat report.

**Comment by Pro100Andrey** [comment]
@sv-dev2 

- (IBAction)answervideoCall:(id)sender
{
//    // 2123, 2123, 3122 - opponent's
    NSArray *opponentsIDs = @[@29774029];
    QBRTCSession *newSession = [[QBRTCClient instance] createNewSessionWithOpponents:opponentsIDs
                                                                  withConferenceType:QBRTCConferenceTypeVideo];

    self.session = newSession;
   //Set self.videoCapture here
    self.session.localMediaStream.videoTrack.videoCapture = self.videoCapture;
    [self.session startCall:nil];
}

**Comment by sv-dev2** [comment]
Thanx A Lot Guys........ Its Working! ..............Thank You all.....:)
