### ISSUE TITLE
can't remove privacy list

### ISSUE THREAD

**Issue by chaymaeBZ** [QuickBlox/quickblox-ios-sdk#839]
I am trying to build the block users feature using privacy lists.
I already created a privacy list with name “public”. When I try to remove it I get an error that says ‘Can not modify list while being in use by other session’ . I tried to create another temporary list named “tmp” and set it to default so that the “public” list can be removed. here is the code that I used :
```swift
 let user = QBUUser()
        user.id = 29777896
        user.password = "03121995"
        
        QBChat.instance().addDelegate(self)
      
        QBChat.instance().connect(with: user) {
            (error) in
                if error != nil {
                    print("error")
                    return
                } else {
                    print("\n success connecting to QB chat \n")
                    
                    QBRequest.logIn(withUserLogin: "chem", password: "03121995", successBlock: { (response: QBResponse, user: QBUUser?) in
                        print("\n ---------------> connected \n")
                        
                        // here goes code
                        
                        self.createNewListAndSetDefault()
                        
                    })
            }
        }

````

```swift
 func createNewListAndSetDefault() {
        let item: QBPrivacyItem = QBPrivacyItem(privacyType: QBPrivacyType.groupUserID , userID: 29782373, allow: false)!
      
        let privacyList = QBPrivacyList(name: "tmp", items: [item])
        QBChat.instance().setPrivacyList(privacyList)
        QBChat.instance().setActivePrivacyListWithName("tmp")
        QBChat.instance().setDefaultPrivacyListWithName("tmp")
        
        print("\n -- Done setting a new list as default -- \n")
    }
````

Then I have a button that when you click on it, it removes the “public” list :
```swift
QBChat.instance().removePrivacyList(withName: "public")
```
but still I am getting the error : 
 ‘Can not modify list while being in use by other session’
Did I miss something ?

**Comment by chaymaeBZ** [comment]
@Raikerian please can you check this ? I've been trying with this for a very long time ...

**Comment by Raikerian** [comment]
Hi,

Make sure that you have logged in with that user on 1 device. If you have multiple active sessions with 1 user, you should deactivate privacy list that you want to delete in every active session.
Otherwise, if this is not the case, please provide full logs where we can see creating the list, activating and attempt of deleting it (user gist.github.com for attaching logs).

**Comment by chaymaeBZ** [comment]
@Raikerian here are the full logs ( link to gist file ) : 

https://gist.github.com/chaymaeBZ/768878edc749775f7d222fec1b4c483a

**Comment by Raikerian** [comment]
According to log:
```
2017-07-24 12:03:50.190 chattt-app[62020:36019763] [ChatService] IQ SNT: <iq type="set" id="6B31ECEE-E069-41FA-BE4C-AE268C3C7C56"><query xmlns="jabber:iq:privacy"><list name="tmp"><item type="jid" value="muc.chat.quickblox.com/29782373" action="deny" order="1"/></list></query></iq>
2017-07-24 12:03:50.190 chattt-app[62020:36019763] [ChatService] IQ SNT: <iq type="set" id="E5390F56-6740-4CA8-A398-4734F8236F1F"><query xmlns="jabber:iq:privacy"><default name="tmp"/></query></iq>
2017-07-24 12:03:50.190 chattt-app[62020:36019763] [ChatService] IQ SNT: <iq type="set" id="6A1D00FE-404C-4F88-9FCF-D6B30C566D2F"><query xmlns="jabber:iq:privacy"><active name="tmp"/></query></iq>
2017-07-24 12:03:51.975 chattt-app[62020:36020897] [ChatService] IQ RCV: <iq xmlns="jabber:client" id="6B31ECEE-E069-41FA-BE4C-AE268C3C7C56" type="result" to="29777896-60054@chat.quickblox.com/AE014784-9758-484F-94A9-E5D8FBDEFAF0"/>
2017-07-24 12:03:58.897 chattt-app[62020:36019763] [ChatService] IQ SNT: <iq type="set" id="AAB402A4-5EB0-4631-B945-F5D8085A51B8"><query xmlns="jabber:iq:privacy"><list name="public"/></query></iq>
```

Line = action:
1. You did set "tmp" list.
2. You did set "tmp" as default.
3. You did set "tmp" as active.
4. Received success result.
5. You did set "public" list.

The issue is in the action 5, you are setting "public" list and then trying to remove it. Check your code.
You can see our guidelines here: https://quickblox.com/developers/SimpleSample-chat_users-ios#Privacy_lists

Also, your log is heavy modified, I've asked for a full one if that is possible.

**Comment by chaymaeBZ** [comment]
@Raikerian Thank you for pointing this. I don't really know what's wrong I m sure I didn't set "public" list after setting "tmp" and here is the full code : 
(It's just a small code to test features individually)
https://gist.github.com/chaymaeBZ/f2e9c97138ed78377a118773361f0ed4

can you please do a quick review !

**Comment by chaymaeBZ** [comment]
It looks like `QBChat.instance().removePrivacyList(withName: "public")` is implicitly calling set privacy list ...

**Comment by Pro100Andrey** [comment]
Hi @chaymaeBZ, you right `QBChat.instance().removePrivacyList(withName: "public")` is implicitly calling set privacy list, without <QBPrivacyItem *> items 

> When a client adds or updates a privacy list, the <list/> element SHOULD contain at least one <item/> child element; when a client removes a privacy list, the <list/> element MUST NOT contain any <item/> child elements.

[xmpp spec](https://xmpp.org/extensions/xep-0016.html)

**Comment by Pro100Andrey** [comment]
@chaymaeBZ could you please remove `QBChat.instance().setActivePrivacyListWithName("tmp")` from your code and check again

**Comment by chaymaeBZ** [comment]
Hi @Pro100Andrey , I just removed `QBChat.instance().setActivePrivacyListWithName("tmp")` from code but it still doesn't work. I tried also to remove items of "public" one by one. In fact it deleted all items except the first item in the list, because if all items were deleted the list will be deleted and that's what it fails exactly to do : removing a list . I think there is an internal problem . Please can you check this and update the label of this issue if it's a real bug or am I just wrong ?

**Comment by Raikerian** [comment]
Can you replicate this by adding code to our sample chat? If yes attach that modified version and we will check it one more time. I didn't find much success replicating that.

**Comment by Pro100Andrey** [comment]
Hi @chaymaeBZ, any updates ??

**Comment by chaymaeBZ** [comment]
@Pro100Andrey Sorry I am very busy these days, I'll get back to this really soon and add code to sample chat as @Raikerian requested.
