### ISSUE TITLE
iOS Swift group message is not sent live. Group chat not working

### ISSUE THREAD

**Issue by ZeshanIlyas** [QuickBlox/quickblox-ios-sdk#840]
*1 to 1 chat is working but group chat is not working *

created a group dialogue 

```
let chatDialog = QBChatDialog(dialogID: nil, type: QBChatDialogType.group)
        let currentUserId  = UserDefaults.standard.integer(forKey: "CurrentUserID")
        let groupName = "\(groupUsers[0].fullName ?? "" ), \(groupUsers[1].fullName ?? "" )..."
        chatDialog.name = groupName
        var ids = groupUsers.map { (user2) -> UInt in
            return user2.id
        }
        chatDialog.occupantIDs = ids as [NSNumber]
        QBRequest.createDialog(chatDialog, successBlock: { (response: QBResponse?, createdDialog : QBChatDialog?) -> Void in
            print(response ?? "", createdDialog ?? "")
            print("dialog created")
            self.dialogUpdateBlock!()
            SVProgressHUD.dismiss()
            self.navigationController?.popViewController(animated: true)
        }) { (responce : QBResponse!) -> Void in
            print(responce, "error")
            SVProgressHUD.dismiss()
        }

```

But when I send the chat message it does not received live for any occupants in either of these methods

```
func chatDidReceive(_ message: QBChatMessage) {
      print(message) //This is working in one-to-one chat but not working in group chat.
    }
    func chatRoomDidReceive(_ message: QBChatMessage, fromDialogID dialogID: String) {
        print(message)
    }
```

**Comment by ZeshanIlyas** [comment]
@Raikerian Please check this

**Comment by aliasad106** [comment]
No reply on this from anyone ?

**Comment by Raikerian** [comment]
Hi @ZeshanIlyas , @aliasad106 

Not really sure what do you want us to check here. I have just tested our swift sample in current repository and everything is working fine in both group and 1on1 chats.
Please check that sample and if you are still having issues attach full logs (use gist.github.com to post logs).

**Comment by aliasad106** [comment]
@Raikerian for me the group dialog is being created perfectly and it's also available with all occupants in the admin panel on the QB admin panel. But I'm not receiving message. It seems I'm missing some configuration for group chat in the Admin panel. could this be the reason apart from that I've followed the tutorial and sample chat for making this.

**Comment by aliasad106** [comment]
@Raikerian As far as I know This method should be called Since I'm an occupant in that dialgue. 
**- (void)chatRoomDidReceiveMessage:(QBChatMessage *)message fromDialogID:(NSString *)dialogID**
_** But it is not called at all**_
Event the messages do load when I go back and come back to that dialogue. But the messages do not get received live.

**Comment by Raikerian** [comment]
Check whether you are joined to that dialog by calling `isJoined` method:
```swift
chatDialog.isJoined
```

**Comment by aliasad106** [comment]
isJoined() is returning false.

**Comment by Raikerian** [comment]
That's the issue, you need to join to group dialog first. Are you using our sample or any other custom implementation?
Use this method to join group dialogs:
https://github.com/QuickBlox/quickblox-ios-sdk/blob/master/Framework/Quickblox.framework/Headers/QBChatDialog.h#L220-L225

**Comment by aliasad106** [comment]
@Raikerian the sample chat does not call this method anywhere but the groups is joined already. This group is not a public group in fact it's just a group created with predefined occupants.

**Comment by Raikerian** [comment]
You need to join any chat dialog that is a group (both group and public group). And sample chat calling this method for every group chat (the actual code is in QMServices): https://github.com/QuickBlox/q-municate-services-ios/blob/master/QMManagers/QMServicesManager.m#L178-L219

**Comment by aliasad106** [comment]
This is crazy. It's missing in the documentation. It took plenty of hours. Anyways thanks

**Comment by Raikerian** [comment]
It's in the documentation, please take a read here: https://quickblox.com/developers/SimpleSample-chat_users-ios#Chat_in_group_dialog
:)

**Comment by aliasad106** [comment]
Wow. Sorry :( My Bad. I was searching the group creation code. I thought that should be in that. But also the messages were being retrieved except the live one this also made me confused that it could be internal issue.

**Comment by Raikerian** [comment]
Messages retrieval functions are REST-based. They are performed using QBRequest class. QBChat is the whole different thing and is responsible for live-time chat updates. You can read more if you want on how this is working here (not required obviously, just additional information on system): https://quickblox.com/developers/Overview

If you will still have any questions hit us up with a new issue here.
