### ISSUE TITLE
Push notifications stop working

### ISSUE THREAD

**Issue by dungnc** [QuickBlox/quickblox-ios-sdk#842]
Hi, my app is working well until 07/28/2017
I'm check in "Queue" at Admin page and it's show me:
https://gyazo.com/0f1e37f0d461eb2c54ee4c3966cd9529
My app id is: 49976

Please help me, thanks for your supporting

**Comment by tom-falcore** [comment]
Doesn't work for me as well from that Date.
We are getting the exact same error:

"There were no recipients for this scheduled event. You may need to check 'Subscriber filtering' settings for your event. For example: there are no users with specified tags."

My app id is: 59533

**Comment by RishabhParashar** [comment]
facing the same exact issue since that 28/07/2017.... app #id : 59032

**Comment by Raikerian** [comment]
Hi, everyone.

As this is probably a server-side issue, I have addressed it to them currently. Thanks for your report, we will post updates as soon as I will get them.

**Comment by Raikerian** [comment]
It should be fixed now, can you guys check it?

**Comment by mrikh** [comment]
I am facing the same exact issue as above and the push aren't still working. All of them are currently in the active status (even though they were working until a few days ago) and showing :

"There were no recipients for this scheduled event. You may need to check 'Subscriber filtering' settings for your event. For example: there are no users with specified tags."

@Raikerian I tried sending a push like 1-3 minutes ago.

**Comment by Raikerian** [comment]
@mrikh are you sure that there are users with those tags that have push subscriptions?

**Comment by mrikh** [comment]
I'm not sure what you mean by tags as i'm not using that property at all.
This is how i'm creating my push event object:

            let data = try JSONSerialization.data(withJSONObject: payload, options: .prettyPrinted)
            
            let message = String(data: data, encoding: .utf8)
            
            let event = QBMEvent()
            
            event.notificationType = .push
            
            event.usersIDs = opponentsIDs
            
            event.type = .oneShot
            
            event.message = message
            
            QBRequest.createEvent(event, successBlock: { (response, event) in
                
                print("success")
                
            }, errorBlock: nil)


And i'm sure i'm sending the push to the correct quickblox_id who has succesfully subscribed to the push.

**Comment by mrikh** [comment]
@Raikerian The push have started to appear now :)

**Comment by stdiohue** [comment]
It's working, thanks Team

**Comment by tom-falcore** [comment]
Seems to be working now.
