### ISSUE TITLE
How to identify if new user sign up for chat in may app? 

### ISSUE THREAD

**Issue by sunilju** [QuickBlox/quickblox-ios-sdk#843]
*Help avoid duplicate issue reports, check [existing issues](https://github.com/QuickBlox/quickblox-ios-sdk/issues)*
 
**Environment details**
*iOS version, Quickblox iOS SDK version, QuickbloxWebRTC SDK version (optional)*

**Did this work before?**

**Expected behavior**

**Actual behavior**

**Logs**
*Attach full logs that will describe your problem (please, use github [gist](https://gist.github.com/))*

**Steps to reproduce the behavior**

**Any others comments?**

**Comment by Pro100Andrey** [comment]
Hi @sunilju, What did you mean "new user sign up for chat in my app" ?
