### ISSUE TITLE
Push notification not able to receive and it's status is active in queue.

### ISSUE THREAD

**Issue by akhil1103** [QuickBlox/quickblox-ios-sdk#844]
*Help avoid duplicate issue reports, check [existing issues](https://github.com/QuickBlox/quickblox-ios-sdk/issues)*
 
**Environment details**
Ios 10.3.1
Quickblox version 3.3

**Did this work before?**
I am able to receive notification but from last 2 days, all notification are just added into the queue with status as active.

**Expected behavior**
Push notification should reaches to the device

**Actual behavior**
Notification is not being sent to device

**Logs**
*Attach full logs that will describe your problem (please, use github [gist](https://gist.github.com/))*

User exist in subscription list and push certificate is also verified it's working well with other servers. All the notification created from dashboard and using API are just added in the queue with active status but user is not able to receive any notification.
**Steps to reproduce the behavior**

**Any others comments?**

**Comment by Raikerian** [comment]
Hi,

There were some issues server-side that were fixed today: https://github.com/QuickBlox/quickblox-ios-sdk/issues/842

Can you check sending pushes one more time?

**Comment by akhil1103** [comment]
Thanks for the support,

Its working well now

On Mon, Jul 31, 2017 at 9:06 PM, Vitaliy Gorbachov <notifications@github.com
