### ISSUE TITLE
Retrieve all chat rooms from Quickblox Database

### ISSUE THREAD

**Issue by unoiatech** [QuickBlox/quickblox-ios-sdk#846]
**Did this work before?**
No

**Expected behavior**
I want to retrieve all the chat dialogs (User associated and without ) from database. 

**Actual behavior**
Currently I am able to retrieve only dialogs with which the user is associated.

**Any others comments?**
 
  I want to retrieve total chat dialogs from Database. Even if the current user is not part of that chat. Is it possible ?

**Comment by Pro100Andrey** [comment]
Hi @unoiatech, No, only user associated
