### ISSUE TITLE
QMSoundManager doesn't play properly sound on speaker

### ISSUE THREAD

**Issue by YroJlbok** [QuickBlox/quickblox-ios-sdk#847]
*Help avoid duplicate issue reports, check [existing issues](https://github.com/QuickBlox/quickblox-ios-sdk/issues)*
 
**Environment details**
*iOS version, Quickblox iOS SDK version, QuickbloxWebRTC SDK version (optional)*
ios - 10.3.2, Quickblox - 2.9.2, QuickbloxWebRTC -2.6.0.1

**Did this work before?**
no

**Expected behavior**
When I am changing QBRTCAudioSession.instance().currentAudioDevice = .speaker, the dialing sound should play on speaker.

**Actual behavior**
Now it's working with bug, when phone ringer level more than 60 -70 % then all works fine, but in case when it's lower dialing sound plays only through receiver. You can find same behavior in your test app sample-videochat-webrtc. 

**Logs**
*Attach full logs that will describe your problem (please, use github [gist](https://gist.github.com/))*

**Steps to reproduce the behavior**
Before cal set your ringer level to 60 or less, and start audio call with default QBRTCAudioSession.
After that try to change QBRTCAudioSession.instance().currentAudioDevice to speaker and after that dialing sound will not play on speaker.

**Any others comments?**

**Comment by Raikerian** [comment]
Hi,

I have just tested our video sample in the master branch of the current repository with the steps you have provided and wasn't able to reproduce it. Also ringer level has nothing to do with QBRTCAudioSession before the call. Please make sure that you are not using modified version of the sample. And if not, please update your steps for the actual ones.
