### ISSUE TITLE
QBRTCSession.h errors on pod installation

### ISSUE THREAD

**Issue by hellc** [QuickBlox/quickblox-ios-sdk#85]
Можно как нибудь на досуге добавить #import <AVFoundation/AVFoundation.h> в файл QBRTCSession.h? Приходится это каждый раз делать при установке библиотеки через CocoaPods.

Спасибо

**Comment by Pro100Andrey** [comment]
@hellc  >> Можно как нибудь на досуге добавить #import в файл QBRTCSession.h? 
Импорт AVCaptureSession ?

**Comment by Pro100Andrey** [comment]
@hellc  если да то скоро в новой версии

**Comment by hellc** [comment]
Спасибо. Ждём апдейтов!
