### ISSUE TITLE
The operation couldn’t be completed. (com.quickblox.chat error -1004.)

### ISSUE THREAD

**Issue by unoiatech** [QuickBlox/quickblox-ios-sdk#850]
**Environment details**
QuickbloxFramework Version : 2.9.2

**Did this work before?**
Yes, it was working a few hours before. I was able to join the public chat group.

**Logs**
The operation couldn’t be completed. (com.quickblox.chat error -1004.)

**Steps to reproduce the behavior**
```swift
singleDialog.join(completionBlock: { (joiningError) in
    print("error joining dialog",joiningError!.localizedDescription)                    
})
```

**Comment by VitaliyGuru** [comment]
@unoiatech, Hello 
Could you please enable full logs and send us this information?

```
[QBSettings setLogLevel:QBLogLevelDebug];
[QBSettings enableXMPPLogging];
```

**Comment by Pro100Andrey** [comment]
@unoiatech hi, any updates?

**Comment by unoiatech** [comment]
Hello, I tried with debug Log. But it does not log any error. But I looks like it has something with the Connection. I tried to reconnect the chat, and it works. It happens, when I join one public chat group after another.

**Comment by unoiatech** [comment]
Also, I am getting error
com.quickblox.chat error -1002.
while sending message to a private chat

**Comment by Pro100Andrey** [comment]
Hi @unoiatech, error code -1002  mens that you are not connected to the chat.

**Comment by Pro100Andrey** [comment]
All errors:

```objc
typedef NS_ENUM(NSInteger, QBChatErrorCode) {
    
    QBChatErrorCodeDidNotAuthenticate = 401,
    QBChatErrorCodeOperationCouldNotBeCompleted = 404,
    QBChatErrorCodeUnderlying = 503,
    
    QBChatErrorCodeAlreadyConnected = -1000,
    QBChatErrorCodeNotJoinedToRoom = -1001,
    QBChatErrorCodeNotConnected = -1002,
    QBChatErrorCodeAlreadyDisconnected = -1003,
    QBChatErrorCodeYouHaveToBeConnected = -1004,
    QBChatErrorCodeYouHaveToJoinRoom = -1005,
    QBChatErrorCodeAlreadyJoined = -1006,
    QBChatErrorCodeNoOccupants = -1007,
    QBChatErrorCodePrivateDialog = -1008,
    QBChatErrorCodeNotInTheContactList = -1009,
    QBChatErrorCodeTimeout = -1010,
    QBChatErrorInvalidUserID = -1011
};
```

**Comment by Pro100Andrey** [comment]
Hi @unoiatech, Any updates ?

**Comment by unoiatech** [comment]
Hello @Pro100Andrey , Thanks for your help. I got it worked. The issue was with chat Connection. Thank you.
