### ISSUE TITLE
internal server error (500) on QBRequest createEvent (Fixed Date)

### ISSUE THREAD

**Issue by syrotynin** [QuickBlox/quickblox-ios-sdk#851]
**"QB-OS" = "iOS 10.3.2";
"QB-SDK" = "iOS 2.9.2";
"QuickBlox-REST-API-Version" = "0.1.1";**

*This feature worked before. Are you going to support it in the future?*

**Expected: scheduled notification with fire date**
**Actual: Request failed: internal server error (500)**

**Response error: Error Domain=com.alamofire.error.serialization.response Code=-1011 "Request failed: internal server error (500)" UserInfo={com.alamofire.serialization.response.error.response=<NSHTTPURLResponse: 0x17422dfc0> { URL: https://api.quickblox.com/events.json } { status code: 500, headers {
    Connection = "keep-alive";
    "Content-Length" = 48;
    "Content-Type" = "application/json; charset=utf-8";
    Date = "Mon, 07 Aug 2017 15:55:38 GMT";
    Server = "openresty/1.9.15.1";
    Status = "500 Internal Server Error";
    "Strict-Transport-Security" = "max-age=31536000";
    "X-Request-Id" = "fc167721-51ad-41be-94c4-4f910537a298";
    "X-Runtime" = "0.037284";
} }, NSErrorFailingURLKey=https://api.quickblox.com/events.json, com.alamofire.serialization.response.error.data=<7b227374 61747573 223a2235 3030222c 22657272 6f72223a 22496e74 65726e61 6c205365 72766572 20457272 6f72227d>, NSLocalizedDescription=Request failed: internal server error**

*Precondition: user is logged in, fireDate set*

          
`QBMEvent *event = [QBMEvent event];
            event.notificationType = QBMNotificationTypePush;
            event.type = QBMEventTypeFixedDate;
            event.date = fireDate;
            
            NSMutableDictionary  *dictPush = [NSMutableDictionary  dictionary];
            [dictPush setObject:text forKey:@"message"];
            NSError *error = nil;
            NSData *sendData = [NSJSONSerialization dataWithJSONObject:dictPush options:NSJSONWritingPrettyPrinted error:&error];
            NSString *jsonString = [[NSString alloc] initWithData:sendData encoding:NSUTF8StringEncoding];
            
            event.message = jsonString;
            event.usersIDs = [NSString stringWithFormat:@"%lu", (unsigned long)user.ID];

            [QBRequest createEvent:event successBlock:^(QBResponse *response, NSArray *events) {
               /*some processing*/
            }errorBlock:^(QBResponse *response) {
                if (errorBlock){
                 // *Have an error(500) here*
                    errorBlock(response.error);
                }
            }];`

**Comment by Pro100Andrey** [comment]
Hi @syrotynin, could you please provide Request / Response logs?

**Comment by syrotynin** [comment]
`Request URL:https://api.quickblox.com/events.json
2017-08-07 19:14:02.314722+0300 ClipOn[1071:383575] [QBCore] Request method: POST
2017-08-07 19:14:02.314935+0300 ClipOn[1071:383575] [QBCore] Request parameters:{
    event =     {
        date = 1502123014;
        environment = development;
        "event_type" = "fixed_date";
        message = ewogICJtZXNzYWdlIiA6ICJZb3UgaGF2ZSBhIG5ldyBDbGlwT24hIgp9;
        "notification_type" = push;
        user =         {
            ids = 16893531;
        };
    };
}
2017-08-07 19:14:02.315159+0300 ClipOn[1071:383575] [QBCore] Request headers: {
    "Accept-Language" = "en-UA;q=1, ru-UA;q=0.9, uk-UA;q=0.8, ar-UA;q=0.7, ru-RU;q=0.6";
    "Content-Type" = "application/x-www-form-urlencoded";
    "QB-OS" = "iOS 10.3.2";
    "QB-SDK" = "iOS 2.9.2";
    "QB-Token" = 81669b4040288808a75ba9c80c467f200700a1e3;
    "QuickBlox-REST-API-Version" = "0.1.1";
    "User-Agent" = "ClipOn/1.06 (iPod touch; iOS 10.3.2; Scale/2.00)";
}
2017-08-07 19:14:02.562001+0300 ClipOn[1071:383225] [QBCore] Response error: Error Domain=com.alamofire.error.serialization.response Code=-1011 "Request failed: internal server error (500)" UserInfo={com.alamofire.serialization.response.error.response=<NSHTTPURLResponse: 0x174225b20> { URL: https://api.quickblox.com/events.json } { status code: 500, headers {
    Connection = "keep-alive";
    "Content-Length" = 48;
    "Content-Type" = "application/json; charset=utf-8";
    Date = "Mon, 07 Aug 2017 16:14:02 GMT";
    Server = "openresty/1.9.15.1";
    Status = "500 Internal Server Error";
    "Strict-Transport-Security" = "max-age=31536000";
    "X-Request-Id" = "4d400ea7-5998-4ea3-849b-d0406eb6843f";
    "X-Runtime" = "0.038773";
} }, NSErrorFailingURLKey=https://api.quickblox.com/events.json, com.alamofire.serialization.response.error.data=<7b227374 61747573 223a2235 3030222c 22657272 6f72223a 22496e74 65726e61 6c205365 72766572 20457272 6f72227d>, NSLocalizedDescription=Request failed: internal server error (500)}`

**Comment by syrotynin** [comment]
@Pro100Andrey 
Request URL:https://api.quickblox.com/events.json
2017-08-07 19:14:02.314722+0300 ClipOn[1071:383575] [QBCore] Request method: POST
2017-08-07 19:14:02.314935+0300 ClipOn[1071:383575] [QBCore] Request parameters:{
    event =     {
        date = 1502123014;
        environment = development;
        "event_type" = "fixed_date";
        message = ewogICJtZXNzYWdlIiA6ICJZb3UgaGF2ZSBhIG5ldyBDbGlwT24hIgp9;
        "notification_type" = push;
        user =         {
            ids = 16893531;
        };
    };
}
2017-08-07 19:14:02.315159+0300 ClipOn[1071:383575] [QBCore] Request headers: {
    "Accept-Language" = "en-UA;q=1, ru-UA;q=0.9, uk-UA;q=0.8, ar-UA;q=0.7, ru-RU;q=0.6";
    "Content-Type" = "application/x-www-form-urlencoded";
    "QB-OS" = "iOS 10.3.2";
    "QB-SDK" = "iOS 2.9.2";
    "QB-Token" = 81669b4040288808a75ba9c80c467f200700a1e3;
    "QuickBlox-REST-API-Version" = "0.1.1";
    "User-Agent" = "ClipOn/1.06 (iPod touch; iOS 10.3.2; Scale/2.00)";
}

Response error: Error Domain=com.alamofire.error.serialization.response Code=-1011 "Request failed: internal server error (500)" UserInfo={com.alamofire.serialization.response.error.response=<NSHTTPURLResponse: 0x174225b20> { URL: https://api.quickblox.com/events.json } { status code: 500, headers {
    Connection = "keep-alive";
    "Content-Length" = 48;
    "Content-Type" = "application/json; charset=utf-8";
    Date = "Mon, 07 Aug 2017 16:14:02 GMT";
    Server = "openresty/1.9.15.1";
    Status = "500 Internal Server Error";
    "Strict-Transport-Security" = "max-age=31536000";
    "X-Request-Id" = "4d400ea7-5998-4ea3-849b-d0406eb6843f";
    "X-Runtime" = "0.038773";
} }, NSErrorFailingURLKey=https://api.quickblox.com/events.json, com.alamofire.serialization.response.error.data=<7b227374 61747573 223a2235 3030222c 22657272 6f72223a 22496e74 65726e61 6c205365 72766572 20457272 6f72227

**Comment by syrotynin** [comment]
Also, this feature doesn't seem to be working from Dashboard.
Scheduled notifications don't come and the status is always "active".
Please check the screenshot
![screen shot 2017-08-10 at 12 09 50 pm](https://user-images.githubusercontent.com/6272133/29163484-51e94a30-7dc5-11e7-8c07-f541a63aa247.png)

**Comment by Mani101991** [comment]
Hi syrotynin. This issues if fixed or not

**Comment by Mani101991** [comment]
Hi @syrotynin and @Pro100Andrey. This issues is fixed or not. Not working for me in iOS App and Dashboard also. Please fix this

**Comment by Pro100Andrey** [comment]
Hi @syrotynin, @Mani101991, the new version of application server will be deployed on Thursday

**Comment by Mani101991** [comment]
Hi @Pro100Andrey , this issues is fixed or not in latest version.

**Comment by Pro100Andrey** [comment]
fixed

**Comment by Mani101991** [comment]
@Pro100Andrey ok Thanks.
