### ISSUE TITLE
Remote Video Stretching - QBRTCRemoteVideoView

### ISSUE THREAD

**Issue by iosgnanavel** [QuickBlox/quickblox-ios-sdk#852]
**Video Stretching**
Hi,  We had faced an issue in video call screen. While in call ,the opponent video view was filled to the entire view as per our need but the view was stretched. 

The video displaying was not accurately aspect fill to the view. we need your guidance to prevent the video from being stretched.The video was perfectly fitted for local video view but not for remote video view. 

**Version**
*XCode 8.3.2*
*IOS SDK 10*
*QuickBlox 2.9.3*
*QuickBlox WebRTC 2.6.1*

**In Our Code**
*QBRTCClientDelegate*

                func session(_ session: QBRTCBaseSession, receivedRemoteVideoTrack videoTrack: QBRTCVideoTrack, fromUser userID: NSNumber) {
        self.performUpdateUserID(userID, block: {(_ cell: CellVideoCall) -> Void in

                        if let opponentVideoView: QBRTCRemoteVideoView = self.videoView(opponentID: userID) as? QBRTCRemoteVideoView {

                            opponentVideoView.videoGravity = AVVideoScalingModeResizeAspectFill

                            cell.videoView = opponentVideoView

                        }

                    })

                }

*Set VideoviewWithOppententID*

                let remoteVideoTrack:QBRTCVideoTrack? = QBCoreInstance.currentSession?.remoteVideoTrack(withUserID: opponentID)

                if (result == nil) && (remoteVideoTrack != nil) {

                                remoteVideoView = QBRTCRemoteVideoView(frame: CGRect(x: 2, y: 2, width: 2, height: 2))

                                remoteVideoView?.videoGravity = AVVideoScalingModeResizeAspectFill

                                dictVideoViews[opponentID] = remoteVideoView

                                result = remoteVideoView

                            }

                        remoteVideoView?.setVideoTrack(remoteVideoTrack!)

![img_0684](https://user-images.githubusercontent.com/22077394/29277555-97ae3702-812f-11e7-9e35-dad42b2d8585.PNG)

Thanks in advance !

**Comment by Pro100Andrey** [comment]
Hi @iosgnanavel, Use AVLayerVideoGravityResizeAspectFill. From inline documentation:
```objc
@interface QBRTCRemoteVideoView : UIView <RTCVideoRenderer>
....
/**
 *	Options are AVLayerVideoGravityResizeAspect, AVLayerVideoGravityResizeAspectFill
 *  and AVLayerVideoGravityResize. AVLayerVideoGravityResizeAspect is default.
 *  See <AVFoundation/AVAnimation.h> for a description of these options.
 *
 *  Default value: AVLayerVideoGravityResize
 */
@property (nonatomic, copy) NSString *videoGravity;
```

**Comment by Pro100Andrey** [comment]
@iosgnanavel Any updates ?

**Comment by Pro100Andrey** [comment]
@iosgnanavel ?

**Comment by iosgnanavel** [comment]
**Hi andrey**, Thanks for your reply! , we tried with your answer but its not working.
The  following line which u suggested ,
"Use AVLayerVideoGravityResizeAspectFill. From inline documentation " is working like this. pls follow the screenshot:
![img_0685](https://user-images.githubusercontent.com/22077394/29352126-3f31a3fc-8283-11e7-8ae2-e80bb3b9092f.PNG)

we expected to be like, the remote video view should be filled to the entire view as like local video view without stretching.
Thanks.

**Comment by Pro100Andrey** [comment]
Hi @iosgnanavel, Use `AVLayerVideoGravityResizeAspect` for filled to the entire view all like local video view without scratching

**Comment by iosgnanavel** [comment]
Hi @Pro100Andrey  Thanks for reply, its working fine. thanks a lot.

**Comment by DhananjayAwasthisyscraft** [comment]
@iosgnanavel  Can you please share this demo with me. I have urgently required.

**Comment by manishbd** [comment]
please check out this link- useful link for video  Stretching

https://github.com/Mahabali/Apprtc-swift/blob/master/Apprtc/RTCVideoChatViewController.swift
