### ISSUE TITLE
mutualBlock doesn't work in private chat

### ISSUE THREAD

**Issue by maodd** [QuickBlox/quickblox-ios-sdk#854]
**New Issue Checklist**

 - [Y] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [N] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    | 10.3                                    |                                          
Quickblox iOS SDK version      | 2.9.3                                  |
QuickbloxWebRTC SDK version    | 2.6.1                                  |                               
Xcode Version                  | Xcode 8.3.3                              |
Repro with our demo sample     | n/a  |

**Did this work before?**
No

**Expected behavior**
mutualBlock: By default user, who is blocking, can send messages and presences to
 *  the one he blocked without any errors. To achieve a two-way block set this
 *  property to YES. After that the user, who is blocking, will receive errors
 *  when will try to communicate with blocked user.

So by setting mutualBlock = YES, blocking use should receive errors when try to communicate with blocked user.

**Actual behavior**
No errors when blocking user try to communicate with blocked user.

Blocked user does receive this though, which is expected behavior.

Further debug turns out that mutualBlock flag reset to 'NO' even when code set it to 'YES' before adding to privacy list.

**Logs**

*Please use the following template for logs:*

```
<details>
<summary>Title for logs </summary>
// Your logs here
2017-08-17 10:11:06.416 UNI[10924:93723] [ChatService] IQ SNT: <iq type="set" id="035C0E02-D0C1-4A6A-829B-A4E9830F339A"><query xmlns="jabber:iq:privacy"><list name="public"><item type="jid" value="29968309-59915@chat.quickblox.com" action="deny" order="1"/></list></query></iq>
2017-08-17 10:11:06.416 UNI[10924:93723] [ChatService] IQ SNT: <iq type="set" id="52E3DC40-3A7A-4CD3-804B-FE04B1ED6F0C"><query xmlns="jabber:iq:privacy"><default name="public"/></query></iq>
</details>
```

To enable full logs use the following code:
```
[QBSettings setLogLevel:QBLogLevelDebug];
[QBSettings enableXMPPLogging];
```

**Steps to reproduce the behavior**
 QBPrivacyItem *item = [[QBPrivacyItem alloc] initWithPrivacyType:QBPrivacyTypeUserID userID:self.userInfo.qbID.integerValue allow:NO];

    item.mutualBlock = YES;
  if (_privacyList) {
       
        NSMutableArray<QBPrivacyItem *> *mutableItems = [_privacyList.privacyItems mutableCopy];
        
        for (QBPrivacyItem * item in _privacyList.privacyItems) {
            if ( item.userID == self.userInfo.qbID.integerValue) {
                [mutableItems removeObject:item];
            }
        }
        
        [mutableItems addObject:item];
        
        _privacyList.privacyItems = mutableItems;
    }else{
        _privacyList = [[QBPrivacyList alloc] initWithName:@"public" items:@[item]];
    }
    
    [[QBChat instance] setPrivacyList:_privacyList];

    [[QBChat instance] setDefaultPrivacyListWithName:@"public"];

// after this, recheck privacylist, privacy item mutualBlock: NO. expect: YES

**Any others comments**

**Comment by Raikerian** [comment]
Hi,

I have checked this in the latest iOS SDK and everything is fine in my case. I did the check 5 seconds after the last line of code in your snippet. Maybe there is a specific way to check it?

**Comment by Pro100Andrey** [comment]
Hi @maodd, any updates ?
