### ISSUE TITLE
What is best practice of handling dev and production environment for Quickblox? Should I create 2 apps in admin panel?

### ISSUE THREAD

**Issue by EugeneGoloboyar** [QuickBlox/quickblox-ios-sdk#855]
**New Issue Checklist**

 - [+] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [+] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

Should I create two apps (dev and prod) to handle environments properly?
In order not to mix dev and prod users/chats.

And I'm not sure is this method related to my question.
```objc
(void)setServiceZone:(QBConnectionZoneType)serviceZone; 
```
How does quickblox handle dev and prod for the same one app? Will it create separate database for dev and prod for one app?

Thanks.

**Comment by Pro100Andrey** [comment]
Hi @EugeneGoloboyar,

>Should I create two apps (dev and prod) to handle environments properly?
How does quickblox handle dev and prod for the same one app?

Yes, for example we use the some logic in  [Q-municate](https://github.com/QuickBlox/q-municate-ios/blob/master/Q-municate/QMAppDelegate.m#L67)

>Will it create separate database for dev and prod for one app?

Yes you are right.
