### ISSUE TITLE
Dialog messages loading.

### ISSUE THREAD

**Issue by ndemenko** [QuickBlox/quickblox-ios-sdk#857]
Use ChatViewController and DialogsViewController from swift example (but logic fixed for my requirements). It work perfect until today. Run app, go to dialogs try open one -> chat screen is empty. Go back and try to open same dialog -> now it show messages.

If need I can provide needed parts of code.

**Comment by ndemenko** [comment]
It was my bad, solved.

**Comment by Ashu** [comment]
How did you solved it? I am having the similar issue in example project.
