### ISSUE TITLE
TIC TCP Conn Failed on iOS 11

### ISSUE THREAD

**Issue by svtechnology** [QuickBlox/quickblox-ios-sdk#858]
**New Issue Checklist**

 - [x] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [x] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    | iOS 11                                    |      iOS 11                                    
Quickblox iOS SDK version      | 2.1.0                                  | 2.1.0
QuickbloxWebRTC SDK version    | x                                 |                               
Xcode Version                  | Xcode 9 beta                              | Xcode 9.0
Repro with our demo sample     | yes   |

**Did this work before?**
Yes, it works flawless on iOS 10 devices

**Expected behavior**
Joining a valid group dialog on iOS 11 should not return a error message and successfully join the dialog.

**Actual behavior**
Every time I try to join a Dialog on device running iOS 11, it results in the below log.

**Logs**

*Please use the following template for logs:*

```
<details>
<summary>Error while connecting </summary>
2017-08-23 20:17:09.787178+0200 [1158:459260] TIC TCP Conn Failed [9:0x1c0363c00]: 1:61 Err(61)
2017-08-23 20:17:09.787378+0200 [1158:459260] Task <67F237F3-312C-413B-B031-6E926CE4CA5A>.<1> HTTP load failed (error code: -1004 [1:61])
2017-08-23 20:17:09.788255+0200 [1158:459253] Task <67F237F3-312C-413B-B031-6E926CE4CA5A>.<1> finished with error - code: -1004
</details>
```

To enable full logs use the following code:
```
[QBSettings setLogLevel:QBLogLevelDebug];
[QBSettings enableXMPPLogging];
```

**Steps to reproduce the behavior**
Device should be running the latest beta of iOS 11 (beta 7 as on 23/08/2017)
Build and run the app on Xcode 9.

**Any others comments**
The same code works as expected on my iPhone 7 running iOS 10 but the above error is thrown on my iPhone 7 Plus running iOS 11

**Comment by svtechnology** [comment]
Apologies for the false flag. It was a configuration issue. Closing it as non-issue.

**Comment by zhugongyuan** [comment]
How to resolve the configuration issue?i hava this issue.thanks
