### ISSUE TITLE
Last message in dialog mismatch history and wrong send date

### ISSUE THREAD

**Issue by EugeneGoloboyar** [QuickBlox/quickblox-ios-sdk#859]
**New Issue Checklist**

 - [x] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [X] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    | 10.0                                    |                                          
Quickblox iOS SDK version      | 2.10                                  |                           
Xcode Version                  | Xcode 8.3                             |

I got an issue when date of last message in dialog doesn't correspond to real last message in history. It is obvious in admin panel. screenshots are provided.

Chat history:
the last message is "Should be possible"

![ScreenShot](http://s018.radikal.ru/i506/1708/64/ab1eb60cb179.png)

Dialog view:
the last message is incorrect as the date is incorrect - "Should be" is the last with 15:06

![ScreenShot](http://s011.radikal.ru/i315/1708/cc/50d2b3194a18.png)

**Comment by soulfly** [comment]
Did you remove any messages via API?

**Comment by EugeneGoloboyar** [comment]
No, I didn't remove any messages on this stage. On that stage we only had sending messages.
Neither via API, nor in any other way we remove messages etc.
And encountered with this strange issue.

**Comment by Pro100Andrey** [comment]
Hi @EugeneGoloboyar, 

Could you please confirm that the issue is still reproducible?

Thanks.

**Comment by VitaliyGuru** [comment]
This issue is being closed due to no response from our previous requests for information or action. We are assuming that this issue no longer exists. If this is still an issue, please open a new one.
