### ISSUE TITLE
Quickblox chat error 60

### ISSUE THREAD

**Issue by gask** [QuickBlox/quickblox-ios-sdk#86]
Hi there, it's been a while now that Quickblox chat is not connecting, everytime I try to connect in the chat, the QBChatDelegate throws me the error number 60.
What is happening? Did something change lately?

I'm using iOS SDK 2.2.3 btw.
Thanks in advance.
Gio

**Comment by soulfly** [comment]
Hi there, 

please post QB SDK log to this thread, will analise
