### ISSUE TITLE
Getting previous login user dailouge

### ISSUE THREAD

**Issue by Rameshwar48** [QuickBlox/quickblox-ios-sdk#862]
There is two user A and B

First login with user A and making request to get dialogue of user A, dialogue getting correct
Than logout using user A, and login to user B and make request for dialogue of user B
than dialogue getting wrong(getting dialogue of user A) 

I check current user after login again , user getting correct

**Comment by VitaliyGuru** [comment]
@Rameshwar48, Please provide full logs for user A and user B.

**Comment by Pro100Andrey** [comment]
Hi @Rameshwar48, Any updates ?
