### ISSUE TITLE
How to identify opponent user enable or disable video in quickblox iOS

### ISSUE THREAD

**Issue by Mani101991** [QuickBlox/quickblox-ios-sdk#863]
Hello Guys,

How to identify opponent user enable or disable video or audio in quickblox. Please tell me the solution

**Comment by Mani101991** [comment]
Hi @VitaliyGuru I Was Calling one to one video call. Quickblox already provided Video enable/disable Stream. UserA is Calling to UserB(Video Call). if UserB disables the video that time shows the UserA Screen is black. So I am asking if UserB disable the video any identify the (disable video for UserB) methods to UserA

**Comment by Raikerian** [comment]
Hi @Mani101991 

When disabling/enabling video, send a system message to your opponents about such update:
https://quickblox.com/developers/SimpleSample-chat_users-ios#System_notifications

**Comment by Mani101991** [comment]
Hi @Raikerian 

Thanks. One more question @Raikerian . If userA is Callling to userB(Video Call). userB is attend the call. if userB press Home button(Background Mode) that case also working ha system message?. In quickblox Document saying only online users to get the system message. Please tell me the solution @Raikerian

**Comment by Raikerian** [comment]
Just do not logout from QBChat when you have an active call while going in the background. Then if call ended in background perform chat log out, otherwise, you will be good.
