### ISSUE TITLE
code signing issue when installed Quickblox through cocoapods

### ISSUE THREAD

**Issue by PriyeshRanjan7** [QuickBlox/quickblox-ios-sdk#864]
**New Issue Checklist**

 - [x] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [x] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    | 10.3                                    |                                          
Quickblox iOS SDK version      | 2.10                                 |
QuickbloxWebRTC SDK version    | 2.6.1                                  |                               
Xcode Version                  | Xcode 8.3.3                              |
Repro with our demo sample     | e.g. does it happen with our demo sample?   |

**Did this work before?**

**Expected behavior**

**Actual behavior**

**Logs**

*Please use the following template for logs:*

```
<details>
<summary>Title for logs </summary>
// Your logs here
</details>
```

To enable full logs use the following code:
```
[QBSettings setLogLevel:QBLogLevelDebug];
[QBSettings enableXMPPLogging];
```

**Steps to reproduce the behavior**

**Any others comments**

**Comment by VitaliyGuru** [comment]
I would be grateful if you could send the details.

**Comment by PriyeshRanjan7** [comment]
I installed Quickblox through cocoapods. Added run-script also. But when trying to distribute using crashlytics Beta app, I am unable to install. In the device log I can see "Failed to verify code signature of QuickbloxWebRTC.framework". Please let me know if I am doing anything incorrectly?

**Comment by VitaliyGuru** [comment]
@PriyeshRanjan7, Let me just make sure - you have added [this script](https://quickblox.com/developers/Sample-webrtc-ios#Run_Script_Phase_for_Dynamic_framework), haven't you?

**Comment by PriyeshRanjan7** [comment]
@VitaliyGuru : yes.. I have added the same script and followed the same link.

**Comment by Raikerian** [comment]
Is "Failed to verify code signature of QuickbloxWebRTC.framework" the only error you see? Any other lines that hint us about the problem?
What is QuickbloxWebRTC framework version? You didn't fill that in your initial post. Also, make sure those scripts are at the bottom of the build phases and validate the script itself once again.

**Comment by PriyeshRanjan7** [comment]
@Raikerian : update it with the version.
Xcode 8.3.3, quickblox: 2.10, webrtc:2.6.1, ios: 10.3.

run script is in the bottom of the build phases.

Also, able to create ipa manually. This problem is when I am trying to distribute using Crashlytics Beta app.

**Comment by Pro100Andrey** [comment]
Hi @PriyeshRanjan7, could you please provide error log?

**Comment by PriyeshRanjan7** [comment]
@Pro100Andrey : please find attached log.`Sep 15 20:21:09 iPhone installd(MobileSystemServices)[413] <Notice>: 0x16e0db000 +[MICodeSigningVerifier _validateSignatureAndCopyInfoForURL:withOptions:error:]: 147: Failed to verify code signature of /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.g7WQTD/extracted/Payload/ServiceLive.app/Frameworks/QuickbloxWebRTC.framework : 0xe8008017 (A signed resource has been added, modified, or deleted.)
Sep 15 20:21:09 iPhone installd(MobileSystemServices)[413] <Notice>: 0x16e0db000 -[MIInstaller performInstallationWithError:]: Verification stage failed
Sep 15 20:21:09 iPhone installd(MobileInstallation)[413] <Notice>: <private>:Install (New):0:Fail:End`

**Comment by PriyeshRanjan7** [comment]
@Pro100Andrey : bash "${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}/QuickbloxWebRTC.framework/strip-framework.sh"

while debugging I found that when adding above script.. m unable to find Quickblox folder in BUILT_PRODUCTS_DIR... **I am adding  this quickblox frameworks using cocoapods**.

please let me know if anything wrong here.

**Comment by Pro100Andrey** [comment]
@PriyeshRanjan7, Could you confirm if this issue is still reproducible?

**Comment by PriyeshRanjan7** [comment]
@Pro100Andrey : Got the issue. It was happening due to static framework of WebRTC and in the cocoapods I was using use_framework!. May be because of that it was throwing error.
