### ISSUE TITLE
User is logged in but can't connect to QBChat

### ISSUE THREAD

**Issue by shalem93** [QuickBlox/quickblox-ios-sdk#866]
**New Issue Checklist**

 - [x ] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [x ] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    |                   10.3.3                  |                                          
Quickblox iOS SDK version      |                  2.9.2               |
QuickbloxWebRTC SDK version    |        2.6.1                        |                               
Xcode Version                  |                 8.3            |
Repro with our demo sample     | e.g. does it happen with our demo sample?   |

**Did this work before?**
In reference to #305 , Im having similar issues and no this hasn't worked for a long time.

My users upon logging back in don't get remembered by QBChat and I get this password error. My users are logging in through Facebook so we use the token as the password like the QBDocs say but I am still having this issue.

**Expected behavior**
Users can log in freely and chat with other users

**Actual behavior**
Users can't connect to QBChat and therefore can't chat with other users.

**Logs**
2017-09-07 15:18:18.484 XpandU[35531:39591813] QBCHAT error: <failure xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><not-authorized/><text lang="en">Password not verified</text></failure>

*Please use the following template for logs:*

```
<details>
<summary>Title for logs </summary>
// Your logs here
</details>
```

To enable full logs use the following code:
```
[QBSettings setLogLevel:QBLogLevelDebug];
[QBSettings enableXMPPLogging];
```

**Steps to reproduce the behavior**

**Any others comments**

**Comment by Pro100Andrey** [comment]
Hi @shalem93, could you please provide full logs (REST & xmpp), for enable use code bellow
```objc
[QBSettings setLogLevel:QBLogLevelDebug];
[QBSettings enableXMPPLogging];
```

**Comment by Pro100Andrey** [comment]
Hi @shalem93, any updates ?
