### ISSUE TITLE
Need Callkit With Quickblox SDK Demo App

### ISSUE THREAD

**Issue by Mani101991** [QuickBlox/quickblox-ios-sdk#867]
Hi Guys,

Anyone having or implemented the callkit in quickblox SDK. Please provide the demo app for Quickblox with Callkit.

**Comment by Raikerian** [comment]
Hi,

We are currently working on it. Updated SDK, as well as the example in sample will be released soon.

**Comment by Raikerian** [comment]
Check out our latest QuickbloxWebRTC framework version 2.6.3: https://quickblox.com/developers/Sample-webrtc-ios#Framework_changelog
CallKit walkthrough: https://quickblox.com/developers/Sample-webrtc-ios#Apple_CallKit

Also check our updated sample: https://github.com/QuickBlox/quickblox-ios-sdk/tree/master/sample-videochat-webrtc
