### ISSUE TITLE
Can the owner of the chat delete all the messages for a particular chat?

### ISSUE THREAD

**Issue by RamandeepGosal** [QuickBlox/quickblox-ios-sdk#868]
**New Issue Checklist**

 -  I have read the [Documentation](https://quickblox.com/developers/IOS)
 -  I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    |  10.3                                    |                                          
Quickblox iOS SDK version      |  2.9.2                                  |
QuickbloxWebRTC SDK version    |  2.4.2                                  |                               
Xcode Version                  |  Xcode 8.3.1                              |
Repro with our demo sample     |  No   |

I want to delete the messages for all users in the group chat. I am the owner of the group. 
Can the owner delete all the group messages, even the ones not sent by him?

I have used this code to delete the messages - 
```
+(void)DeleteAllChatMessages : (NSMutableArray*)arrSelectedMessages successBlock:(void(^)(id responseObject))sucess failureBlock:(void(^)(id errorResponse))fail
{
  NSMutableArray *arrIds = [[NSMutableArray alloc]init];
  for (int i=0; i<arrSelectedMessages.count; i++)
  {
    QBChatMessage *msg = [arrSelectedMessages objectAtIndex:i];
    [arrIds addObject:msg.ID];
  }
  NSSet *setIfIds = [NSSet setWithArray:arrIds];
  
  [QBRequest deleteMessagesWithIDs:setIfIds forAllUsers:YES successBlock:^(QBResponse * _Nonnull response) {
    
    sucess(response);
    
  } errorBlock:^(QBResponse * _Nonnull response) {
    fail(response);
  }];
}
```
I get this response - 
```
{
    NotFound =     {
        ids =         (
        );
    };
    SuccessfullyDeleted =     {
        ids =         (
            59b7bd265b6c5dc402004202,
            59b7bd285b6c5dc402004204
        );
    };
    WrongPermissions =     {
        ids =         (
            59b76434f3042bc5010041be,
            59b7643df3042bc5010041c1,
            59b76844f3042be4010041ab,
            59b76854f3042be4010041ae,
            59b769bef3042be5010041af,
            59b776e6f3042bf2010041be,
            59b778b5f3042bf6010041cc,
            59b778bdf3042bf6010041ce,
            59b778c1f3042bf6010041d0,
            59b778f6f3042bf60100420a,
            59b77933f3042bf601004221,
            59b77935f3042bf601004223,
            59b77996f3042bf601004256,
            59b77b35f3042bf60100428c,
            59b7b9c0f3042b1a02004232
        );
    };
}

```
I can understand creator can not delete the messages of other users. 
But is there any way by which I can delete those messages for all the users of that Chat ?

**Comment by VitaliyGuru** [comment]
@RamandeepGosal, There is no such possibility.

**Comment by VitaliyGuru** [comment]
@RamandeepGosal, Please describe in details the workflow you need.

**Comment by RamandeepGosal** [comment]
Hi, 
Thanks for the reply.
I want to provide the delete all messages privilege to the owner of the chat. Only the owner of the chat will have this functionality.

**Comment by RamandeepGosal** [comment]
Hi there @VitaliyGuru 
Can you please provide me a response whether it is possible or not? 
I would be thankful.

**Comment by VitaliyGuru** [comment]
@RamandeepGosal, You can use the following approach:
1. When the owner deletes chat message he can send the notification message with custom parameter, e.g. 

```objective-c
    QBChatMessage *messageYouWantToDelete = [QBChatMessage new];
    //Let's assume you have removed message and in completion block:

    QBChatMessage *notificationMessage = [QBChatMessage new];
     //Other message configuration, e.g adding occuppants' IDs
    //...
    if (!notificationMessage.customParameters) {
        notificationMessage.customParameters = [[NSMutableDictionary alloc] init];
    }
   
    notificationMessage.customParameters[@"message_to_delete"] = messageYouWantToDelete.ID;
```
2. All occupants will receive this message and they should check for the parameter `@"message_to_delete"` and remove message on theirs side if the parameter  exists.
```objective-c
    QBChatMessage *receivedMessage;
    if (receivedMessage.customParameters[@"message_to_delete"]) {
        NSSet *messageIDs = [NSSet setWithObject:receivedMessage.customParameters[@"message_to_delete"]];
        [QBRequest deleteMessagesWithIDs:messageIDs
                             forAllUsers:YES
                            successBlock:^(QBResponse * _Nonnull response) {
                                
                            } errorBlock:^(QBResponse * _Nonnull response) {
                                
                            }];
    }
```

**Comment by RamandeepGosal** [comment]
@VitaliyGuru 
Thanks for giving me this idea, but recievedmessage will be in chatdidrecievemessage right?
Then it will make all the messages vanish when the chat gets connected, if I am not wrong. 
I think it will be a bit strange (all messages getting deleted after chat gets connected) with respect to user experience. 
I will give it a try. 
Thank you very much!!!

**Comment by VitaliyGuru** [comment]
@RamandeepGosal, Also you can send system message with the approach described above for online users.
https://quickblox.com/developers/SimpleSample-chat_users-ios#System_notifications

**Comment by VitaliyGuru** [comment]
@RamandeepGosal, My bet, I forgot, that you also should check for the owner of the message.
You should add:
```objective-c
notificationMessage.customParameters[@"message_to_delete_owner"] = [NSString stringWithFormat:@"%ld",messageYouWantToDelete.senderID];
```
And the final method:
```objective-c
 QBChatMessage *receivedMessage;
    if (receivedMessage.customParameters[@"message_to_delete"]) {
        NSSet *messageIDs = [NSSet setWithObject:receivedMessage.customParameters[@"message_to_delete"]];
        BOOL isOwner =
        receivedMessage.customParameters[@"message_to_delete_owner"].integerValue == QBSession.currentSession.currentUser.ID;
        [QBRequest deleteMessagesWithIDs:messageIDs
                             forAllUsers:isOwner
                            successBlock:^(QBResponse * _Nonnull response) {
                                
                            } errorBlock:^(QBResponse * _Nonnull response) {
                                
                            }];
    }
```

**Comment by RamandeepGosal** [comment]
Hi thanks for the efforts, 
My client said deleting the messages from the personal chat would be enough.
No need to delete for all.
I ll stick to that .
Thank you very much!!!
