### ISSUE TITLE
Unable to connect to chat server .

### ISSUE THREAD

**Issue by nitinsindhubt** [QuickBlox/quickblox-ios-sdk#869]
For Receiving  video call i need to do following things 
**1.** I need to login to quick . blox 
**2**. i should connect to the chat server 

i am doing this using below code

I am trying to login on QuickBlox , after login Success and trying to connect user to Quickblox chat server .
   
```objc
 NSString *strQBLogin= @"SomeUserID"
    NSString *strQBPassword= @"Some_Password"
    
    [QBRequest logInWithUserLogin:strQBLogin   password:strQBPassword successBlock:^(QBResponse *response, QBUUser *user) {
        
        
        NSLog(@"Loggin to Quick Blox Server");
        
        
        user.password=strQBPassword;
        
        // connect to Chat
        
        
        NSLog(@"Connecting to user did start");

        [[QBChat instance] connectWithUser:user completion:^(NSError * _Nullable error) {
            
             NSLog(@"Connecting to user did Finish");
            
            if (error) {
                NSLog(@"Error in Conneting to Quick Blox ");
                
            }
            else
            {
             NSLog(@" Conneted to Quick Blox ");
               
            }
            
        }];
        
        
    } errorBlock:^(QBResponse *response) {
        
        
        
        // error handling
        NSLog(@"error: %@", response.error);
    }];

```

but when call 

   ```
 [[QBChat instance] connectWithUser:user completion:^(NSError * _Nullable error) {
    }];
```

i get the following error message in the log :

  `  rtc::<QBRTCClient 0x6000002459a0, delegates[2]> did accidentally disconnect.
`
please help me ..

![screen shot 2017-09-13 at 2 24 19 pm](https://user-images.githubusercontent.com/30141402/30368684-90f2d90a-988f-11e7-920a-05742fa9a30b.png)

After Enabling Debug Level Log
  ```
  [QBSettings setLogLevel:QBLogLevelDebug];
    [QBSettings enableXMPPLogging];
```

![screen shot 2017-09-13 at 2 39 11 pm](https://user-images.githubusercontent.com/30141402/30369413-0d74af4c-9892-11e7-9e51-f1c3bf0f19f0.png)

**Comment by nitinsindhubt** [comment]
Abe bhai koi batayega ? kyun ho raha hai aisa ??

**Comment by Pro100Andrey** [comment]
Hi @nitinsindhubt, could you please check the port 5223 access in your firewall settings ?

**Comment by nitinsindhubt** [comment]
Thank you soo much ,,,,, Live long bro ,,,, you are real life saver :) . 👍 

This is a issue of my office network , working fine on personal hotspot .

**Comment by nitinsindhubt** [comment]
But how can i know if firwall is blocking , i need to show error message to user , when some user connect to such network 


Thanks in advacne

**Comment by Pro100Andrey** [comment]
@nitinsindhubt, could you please update the issue on stackowerflow ?

**Comment by nitinsindhubt** [comment]
Ok, I'll remove the issue from stackoverflow  .

but i have question 

```
[[QBChat instance] connectWithUser:user completion:^(NSError * _Nullable error) {

 }];
```

the above block doesn't call , when i am getting such problem , if firewall is blocking you should  return in the block with `Error` and `error.localizedDescription`
