### ISSUE TITLE
Adding Custom Field in QBChatAttachment

### ISSUE THREAD

**Issue by unoiatech** [QuickBlox/quickblox-ios-sdk#871]
This is actually not an issue. But I need help in customizing QBChatAttachment. If its possible to customize this header class. 
I need to attach a thumbnail with the image. The thumbnail will be display while the original image is downloading. 
How can I do that? I am trying to add custom field "thumbnailData" in QBChatAttachment class. But getting this error:

`Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[QBChatAttachment setThumbnailData:]: unrecognized selector sent to instance`

Can I customize it in some way? Or can you please suggest me some way around to attach thumbnail ?

**Comment by Pro100Andrey** [comment]
HI @unoiatech, use code bellow:

```objc
QBChatAttachment *attachment = [QBChatAttachment new];
attachment[@"thumbnail"] = @"thumbnail_url";
```

**Comment by unoiatech** [comment]
Hey , I tried the above code  . It is giving me below error : 

Expected method to write dictionary element not found on object of type 'QBChatAttachment *'

**Comment by VitaliyGuru** [comment]
@unoiatech, Please provide Quickblox SDK version.

**Comment by unoiatech** [comment]
I am using Quickblox 2.9.2 Version.

**Comment by Pro100Andrey** [comment]
Hi @unoiatech, please update to the last versions of SDK

**Comment by Pro100Andrey** [comment]
Hi @unoiatech, any updates ?
