### ISSUE TITLE
How to share a video as attachment

### ISSUE THREAD

**Issue by shahkevin23** [QuickBlox/quickblox-ios-sdk#872]
func didPickAttactmentVideoUrl(_ url: URL) {
        let message = QBChatMessage()
        message.senderID =  self.senderID
        message.dialogID = self.dialog.id
//        message.text = "\(url)"
        message.dateSent = Date()
        
        DispatchQueue.global().async {
            [weak self] () -> Void in
            // Sending attachment.
            DispatchQueue.main.async(execute: {
                self?.chatDataSource.add(message)
                // sendAttachmentMessage method always firstly adds message to memory storage
                do {
                    let data = try Data(contentsOf: url)
                     QBRequest.tUploadFile(data, fileName: "Kevinshah", contentType: "video/mp4", isPublic: true, successBlock: { (success, blob) in
                        let att = QBChatAttachment()
                        att.type = "video"
                        att.localFileURL = url
                        att.id = blob.uid
                        message.attachments = [att]
                        print("success \(success.debugDescription as Any)")
                        ServicesManager.instance().chatService.sendAttachmentMessage(message, to: self!.dialog, with: att, completion: { (error) in
                            print(error.debugDescription as Any)
                        })
                    }, statusBlock: { (request, status) in
                        _ = ValidationToast.showStatusMessage(message: "\(status.percentOfCompletion)")
                    }, errorBlock: { (errResponse) in
                        print(errResponse.error?.error?.localizedDescription as Any)
                    })
                 } catch {
                    print("error")
                }
            })
        }
    }
![screen shot 2017-09-21 at 2 55 20 pm](https://user-images.githubusercontent.com/24786934/30688871-f0f2c510-9edc-11e7-92ea-825d3f035082.png)

**Comment by shahkevin23** [comment]
func didPickAttactmentVideoUrl(_ url: URL) {
        let message = QBChatMessage()
        message.senderID =  self.senderID
        message.dialogID = self.dialog.id
//        message.text = "\(url)"
        message.dateSent = Date()
        
        DispatchQueue.global().async {
            [weak self] () -> Void in
            // Sending attachment.
            DispatchQueue.main.async(execute: {
                self?.chatDataSource.add(message)
                // sendAttachmentMessage method always firstly adds message to memory storage
                do {
                    let data = try Data(contentsOf: url)
                     QBRequest.tUploadFile(data, fileName: "Kevinshah", contentType: "video/mp4", isPublic: true, successBlock: { (success, blob) in
                        let att = QBChatAttachment()
                        att.type = "video"
                        att.localFileURL = url
                        att.id = blob.uid
                        message.attachments = [att]
                        print("success \(success.debugDescription as Any)")
                        ServicesManager.instance().chatService.sendAttachmentMessage(message, to: self!.dialog, with: att, completion: { (error) in
                            print(error.debugDescription as Any)
                        })
                    }, statusBlock: { (request, status) in
                        _ = ValidationToast.showStatusMessage(message: "\(status.percentOfCompletion)")
                    }, errorBlock: { (errResponse) in
                        print(errResponse.error?.error?.localizedDescription as Any)
                    })
                 } catch {
                    print("error")
                }
            })
        }
    }

**Comment by shahkevin23** [comment]
Can you please provide a sample for video sharing as attachment

**Comment by VitaliyGuru** [comment]
@shahkevin23,
You should use the latest version of QMServices.
```objective-c
    QBChatAttachment *attachment = [QBChatAttachment videoAttachmentWithFileURL:videoUrl];
//or you can use designated initializer of  QBChatAttachment.

+ (instancetype)initWithName:(nullable NSString *)name
                     fileURL:(nullable NSURL *)fileURL
                 contentType:(NSString *)contentType
              attachmentType:(NSString *)type;

```

For attachment send you can use the following method of QMChatService instance:
```objective-c
- (void)sendAttachmentMessage:(QBChatMessage *)attachmentMessage
                     toDialog:(QBChatDialog *)dialog
               withAttachment:(QBChatAttachment *)attachment
                   completion:(nullable QBChatCompletionBlock)completion;
```

**Comment by Pro100Andrey** [comment]
Hi @shahkevin23, Any updates ?

**Comment by SalmanGhumsani** [comment]
@Pro100Andrey Yeah It's awesome I have just followed the step and I am able to send the video can you please clarify How to represent it from both ends? is there any hack?

**Comment by arpitjain03** [comment]
Firstly get the local video URL using Photo Library or Camera. Then proceed as follows:

    let message = QBChatMessage()
    message.senderID = (self.senderID)
    message.dialogID = self.chatDialogModel.id
    message.dateSent = Date()
   
    let attachment = QBChatAttachment.videoAttachment(withFileURL: url)        
    self.chatDataSource.add(message)
    
    ServicesManager.instance().chatService.sendAttachmentMessage(message, to: self.chatDialogModel, with: attachment, completion: { (error) in
            
            self.attachmentCellsMap.removeObject(forKey: message.id as AnyObject?)
            guard error != nil else { return }
            self.chatDataSource.delete(message)
    })

This will send video as attachment.
