### ISSUE TITLE
Expected a Type 

### ISSUE THREAD

**Issue by shashankel** [QuickBlox/quickblox-ios-sdk#874]
When I try to compile the code for sample-videochat-webrtc the below lines in QBcore.m throw the error Expected a Type. I am using Xcode 9.

(void)chatDidNotConnectWithError:(QB_NULLABLE NSError *)error {
    
}

- (void)chatDidFailWithStreamError:(QB_NULLABLE NSError *)error {
    
}

**Comment by Raikerian** [comment]
Hi,

Just remove QB_NULLABLE from there and it should work.

**Comment by shashankel** [comment]
Working now. Thanks
