### ISSUE TITLE
Red Banner

### ISSUE THREAD

**Issue by vivek5586** [QuickBlox/quickblox-ios-sdk#875]
When two users connect online in Ios and then if the receiver put the app in the background mode and after speaking if the dialer disconnects the call there is a red banner that appears on the top and it is not disappearing for at least 30 seconds.

**New Issue Checklist**

 - [x] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [x] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    | e.g. 8.0                                    |                                          
Quickblox iOS SDK version      | e.g. 2.7.6                                  |
QuickbloxWebRTC SDK version    | e.g. 2.2.1                                  |                               
Xcode Version                  | e.g. Xcode 8.1                              |
Repro with our demo sample     | e.g. does it happen with our demo sample?   |

**Did this work before?**

**Expected behavior**

**Actual behavior**

**Logs**

*Please use the following template for logs:*

```
<details>
<summary>Title for logs </summary>
// Your logs here
</details>
```

To enable full logs use the following code:
```
[QBSettings setLogLevel:QBLogLevelDebug];
[QBSettings enableXMPPLogging];
```

**Steps to reproduce the behavior**

**Any others comments**

**Comment by Raikerian** [comment]
Hi,

Red banner is a result of activating webrtc audio session. After call end you need to deinitialize audio session:

```
//deinitialize after session close 
[[QBRTCAudioSession instance] deinitialize];
```

**Comment by vivek5586** [comment]
Thanks for the reply and Including my developer on this ,we are already
doing the deinitialise but the red banner disappears and reappears again
,please help us on this as this is the only issue stopping us from going
live.

**Comment by vivek5586** [comment]
Will send u video ,code and debug logs in couple of hours.

**Comment by Raikerian** [comment]
Just let me know if the issue exists in our sample.

**Comment by vivek5586** [comment]
Can u refer me wat sample you are asking about pleasw.

On Sep 28, 2017 9:39 AM, "Vitaliy Gorbachov" <notifications@github.com>
wrote:

Just let me know if the issue exists in our sample.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/QuickBlox/quickblox-ios-sdk/issues/875#issuecomment-332839229>,
or mute the thread

**Comment by Raikerian** [comment]
https://github.com/QuickBlox/quickblox-ios-sdk/tree/master/sample-videochat-webrtc

**Comment by vivek5586** [comment]
The sample does not have background mode and call kit integration ,so there is no red banner there

**Comment by Raikerian** [comment]
It does have background mode though: http://take.ms/YxL5W
And it does have a red banner when you are going background (I have just checked it)

And call kit has nothing to do with in-call (red banner) notification on iOS.

**Comment by vivek5586** [comment]
Ok will check and let u know in couple of hours ,Thank u

**Comment by vivek5586** [comment]
one quick question do we have to put the voip flag to true or false when we integrate with call kit as i am confused with the documentation provided by quickblox.

**Comment by Raikerian** [comment]
You don't need VoIP flag for our functionality. You can use it of course if you need it (VoIP push notifications for example).
Here is background documentation https://quickblox.com/developers/Sample-webrtc-ios#Background_mode
Please tell us what exactly confusing there so we can improve that.

**Comment by vivek5586** [comment]
It's confusing because apple doc says we have to enable voip if we use call
kit.

**Comment by Raikerian** [comment]
When I said that you don't need that flag for our functionality, I meant SDK. Call Kit is not a part of our SDK, and if Apple says so then you definitely need to enable that flag.

**Comment by vivek5586** [comment]
ok thank you and we did take the background audio off as call kit has its
own audio, is that fine?

**Comment by Raikerian** [comment]
Where did you take background audio off again?

**Comment by Pro100Andrey** [comment]
Hi @vivek5586, 
Thanks for notify us!

**Comment by VishalSharma91** [comment]
Currently I am not allowing record support in my app but when I make calls it shows red banner like a recorder if I go in background, unlike Green banner which is case with most of apps like WhatsApp, Skype, etc, let me know how to achieve that.
Even I turned the audio capability off and I made a call but still it shows red.
