### ISSUE TITLE
Signup filing with error **Failed to save the record** if the username already exists.

### ISSUE THREAD

**Issue by jkmathew** [QuickBlox/quickblox-ios-sdk#876]
Signup filing with error **Failed to save the record** if the username already exists.

 - [x] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [x] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    | 10.3                                    |                                          
Quickblox iOS SDK version      | 2.11                                  |
QuickbloxWebRTC SDK version    |-            |                               
Xcode Version                  |  Xcode 8.3                              |
Repro with our demo sample     | -   |

**Did this work before?**
Yes

**Expected behavior**
Signup should work

**Actual behavior**
Signup filing with error **Failed to save the record** if the username already exists.

**Logs**
```
POST URL:https://api.quickblox.com/users.json
headers: {
    "Accept-Language" = "en-US;q=1, ar-US;q=0.9, fr-US;q=0.8, en;q=0.7";
    "Content-Type" = "application/x-www-form-urlencoded";
    "QB-OS" = "iOS 10.3";
    "QB-SDK" = "iOS 2.11";
    "QB-Token" = 12857bcccedd162b5ee7f299625009778100efca;
    "QuickBlox-REST-API-Version" = "0.1.1";
    "User-Agent" = "NJOUD/1.0 (iPhone; iOS 10.3; Scale/3.00)";
}
parameters: {
    user =     {
        login = johny;
        password = <#mypassword#>>;
    };
}
2017-09-27 16:21:21.440 NJOUD[20043:241295] [QBCore]: Response[2]
headers: {
    "Access-Control-Allow-Origin" = "*";
    "Cache-Control" = "no-cache";
    Connection = "keep-alive";
    "Content-Length" = 51;
    "Content-Type" = "application/json; charset=utf-8";
    Date = "Wed, 27 Sep 2017 10:51:21 GMT";
    Duration = "0.311859";
    "QB-Token-ExpirationDate" = "2017-09-27 12:49:11 +0000";
    "QuickBlox-REST-API-Version" = "0.1.1";
    Server = "openresty/1.9.15.1";
    "Set-Cookie" = "_mkra_ctxt=0652b76990e93962362c49d008befa8d--422; path=/; max-age=5; HttpOnly; secure";
    Status = "422 Unprocessable Entity";
    "Strict-Transport-Security" = "max-age=31536000";
    "X-Content-Type-Options" = nosniff;
    "X-Frame-Options" = SAMEORIGIN;
    "X-Request-Id" = "c5f2dafc-324a-4b4c-8684-e5247feebdde";
    "X-Runtime" = "0.042932";
    "X-XSS-Protection" = "1; mode=block";
}
error: Request failed: client error (422)
reasons: {
    code = "<null>";
    message = "Failed to save the record";
}
```

**Comment by soulfly** [comment]
Hi @jkmathew
we are checking this now

**Comment by soulfly** [comment]
This is fixed now, you can check

**Comment by VitaliyGuru** [comment]
@jkmathew  Could you please confirm this issue has been fixed?

**Comment by jkmathew** [comment]
@soulfly , should I update pod/framework or its fixed from server side?
