### ISSUE TITLE
Calls take too long to connect

### ISSUE THREAD

**Issue by deadjdona** [QuickBlox/quickblox-ios-sdk#878]
**New Issue Checklist**

 - [+] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [+] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    | 11.0.1                                    |                                          
Quickblox iOS SDK version      | e.g. 2.12                                  |
QuickbloxWebRTC SDK version    | e.g. 2.12                                  |                               
Xcode Version                  | e.g. Xcode 8.1                              |
Repro with our demo sample     | e.g. does it happen with our demo sample?   |

**Did this work before?**
Not sure.

**Expected behavior**
Fast connection times.

**Actual behavior**
Calls are slow. It takes too long to answer call and actually hear other person.

**Steps to reproduce the behavior**
Calls from one account and answer from other.

**Any others comments**

**Comment by Pro100Andrey** [comment]
Hi @deadjdona, 
Could you please provide full logs?

```objc
For enable logging use code bellow:
 [QBSettings setLogLevel:QBLogLevelDebug];
 [QBSettings enableXMPPLogging];
```
Thanks.

**Comment by Pro100Andrey** [comment]
Hi @deadjdona, Any updates ?

**Comment by IntellectSoftDeveloper** [comment]
Look on debug log, with enabled xmpp logging. 
[log.txt](https://github.com/QuickBlox/quickblox-ios-sdk/files/1513204/log.txt)

**Comment by Raikerian** [comment]
@IntellectSoftDeveloper are you connected to the original issue creator? If not, then please create a separate issue.

**Comment by IntellectSoftDeveloper** [comment]
Yes, I provide full logs instead @deadjdona, we on same project)

**Comment by deadjdona** [comment]
that's on dedicated quickblox server, not even on shared server.

**Comment by Raikerian** [comment]
Please attach logs from both devices where we can see slow connections. Also please check this issue in our sample in current repository (sample-videochat).

**Comment by VitaliyGuru** [comment]
@deadjdona, @IntellectSoftDeveloper ,
Any updates?
