### ISSUE TITLE
Search the dialogs on bases on names not working

### ISSUE THREAD

**Issue by RamandeepGosal** [QuickBlox/quickblox-ios-sdk#880]
**New Issue Checklist**

 -  I have read the [Documentation](https://quickblox.com/developers/IOS)
 -  I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    |  10.3                                    |                                          
Quickblox iOS SDK version      |  2.9.2                                  |
QuickbloxWebRTC SDK version    |  2.4.2                                  |                               
Xcode Version                  |  Xcode 8.3.1                              |
Repro with our demo sample     |  No   |

I am trying to retrieve the dialogs on the bases on the names and according to the examples given by quickblox developers for filters while retrieving dialogs, I used this 

```objc
{field_name}[{search_operator}]
//Example was provided as - 
extendedRequest[@"type[in]"] = @"1,2"; 

```

So I used 'name' and 'ctn' as extendedRequest parameters - 

```objc
extendedRequest[@"name[ctn]"] = @"ram"; 
```
The code for the same is given below:

```objc
NSMutableDictionary<NSString*,NSString*> *abc = [[NSMutableDictionary alloc]initWithObjectsAndKeys:@"3",@"type", nil];
  if(![individualSearchBar.text isEqualToString:@""]){
    [abc setObject:individualSearchBar.text forKey:@"name[ctn]"];
  }
```
But it gives me correct response sometimes and other times It just returns 0 rows

<details>
<summary>These are the log deatils </summary>

``` logos
2017-10-03 15:28:52.803649+0530 Panda[396:58571] [QBCore] Request URL:https://api.quickblox.com/chat/Dialog.json?limit=1000&name%5Bctn%5D=ram&type=3
2017-10-03 15:28:52.803789+0530 Panda[396:58571] [QBCore] Request method: GET
2017-10-03 15:28:52.803863+0530 Panda[396:58571] [QBCore] Request parameters:{
    limit = 1000;
    "name[ctn]" = ram;
    type = 3;
}
2017-10-03 15:28:52.803935+0530 Panda[396:58571] [QBCore] Request headers: {
    "Accept-Language" = "en-IN;q=1";
    "QB-OS" = "iOS 10.3.3";
    "QB-SDK" = "iOS 2.9.2";
    "QB-Token" = 23286a5cda6bd2a79615e26d3fcd74610700efbf;
    "QuickBlox-REST-API-Version" = "0.1.1";
    "User-Agent" = "Panda/1.1 (iPhone; iOS 10.3.3; Scale/2.00)";
}
2017-10-03 15:28:53.241520+0530 Panda[396:58572] [QBCore] Response headers: {
    "Access-Control-Allow-Origin" = "*";
    "Cache-Control" = "max-age=0, private, must-revalidate";
    Connection = "keep-alive";
    "Content-Length" = 51;
    "Content-Type" = "application/json; charset=utf-8";
    Date = "Tue, 03 Oct 2017 09:58:53 GMT";
    Etag = "W/\"f6359bf753fc5213460f8a6eaa9234b6\"";
    "QB-Token-ExpirationDate" = "2017-10-03 11:49:27 +0000";
    "QuickBlox-REST-API-Version" = "0.1.1";
    Server = "openresty/1.9.15.1";
    "Set-Cookie" = "_mkra_ctxt=c01d9eb52430ae65ef6fd0809279ca89--200; path=/; max-age=5; HttpOnly; secure";
    Status = "304 Not Modified";
    "Strict-Transport-Security" = "max-age=31536000, max-age=15768000;";
    "X-Content-Type-Options" = nosniff;
    "X-Frame-Options" = SAMEORIGIN;
    "X-Request-Id" = "f16b7380-658a-465e-abf6-f74c8ffce6c5";
    "X-Runtime" = "0.028350";
    "X-XSS-Protection" = "1; mode=block";
}
2017-10-03 15:28:53.242181+0530 Panda[396:58571] [QBCore] Response object: {
    items =     (
    );
    limit = 100;
    skip = 0;
    "total_entries" = 0;
}
2017-10-03 15:28:53.244023+0530 Panda[396:58571] [QBCore] Response object: {
    items =     (
    );
    limit = 100;
    skip = 0;
    "total_entries" = 0;
}
```
</details>

Here I have a dialog with name ramandeep singh but it is not returned.

**Comment by Pro100Andrey** [comment]
Hi @RamandeepGosal, type=3 don't have the `name` field. From [documentation](https://quickblox.com/developers/Chat#Create_dialog):

Parameter `name` Required - YES (except when type=3 (PRIVATE). Ignored when type=3(PRIVATE)

**Comment by RamandeepGosal** [comment]
Hi @Pro100Andrey,
Thanks for a quick reply, 
But I am working on an application which is having group messages and private messages listing on two different controllers. 
And I want to add search functionality in the listing. Can you please suggest me what to use to implement searching on the bases on name in private chat which is of type 3.

**Comment by Pro100Andrey** [comment]
Hi @RamandeepGosal, Did you have contact list functionality in your app?

**Comment by RamandeepGosal** [comment]
Hi @Pro100Andrey, Yes I have taken the users phone numbers from the contacts of the phone and once the message is sent to the user, the app shows them in the private chat listing screen,

**Comment by RamandeepGosal** [comment]
I apologies if I am doing something wrong but the application was already built and was sent for improvements to me and I have checked and rectified most of the functionality, but I am stuch at this issue.

**Comment by Pro100Andrey** [comment]
Hi @RamandeepGosal,
1) You can use Group Dialog with 2 occupants instead of Private, then you will be able to search by name

2) You can load own dialogs and search locally . (Same functionality : https://github.com/QuickBlox/q-municate-ios)

**Comment by RamandeepGosal** [comment]
I will load them all and then search locally, 
Thanks for your time.
