### ISSUE TITLE
hungUpByUser not called

### ISSUE THREAD

**Issue by hcrgithub** [QuickBlox/quickblox-ios-sdk#884]
**New Issue Checklist**

 - [x] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [x] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

**Environment details**

iOS Version    : 11.0
Quickblox iOS SDK version  : 2.12
QuickbloxWebRTC SDK version  :  2.6.1                      
Xcode Version  : Xcode 9 
Repro with our demo sample  : No

**Did this work before?**
No

**Expected behavior**
delegate hungUpByUser should be called (Do note that didReceiveNewSession gets called on receiver side)

**Actual behavior**
Did receive signal in log : hangUp from: 34297938

**Steps to reproduce the behavior**
Call from device A to device B, and device B should hung up the call.

**Comments**

Call type : Audio

Sender : Simulator
Receiver : iPad mini 2 

Sender log : https://www.dropbox.com/s/gerphd3mn2q2w0y/SenderLog.rtf?dl=0 (It can be observed that the receiver has hung up the call and in log I get a signal Did receive signal: hangUp from: 34297938, but the respective delegate hungUpByUser is not called.
 
Receiver log : https://www.dropbox.com/s/5zg81exsmcq40cs/ReceiverLog.rtf?dl=0

Signal gets received in log for all the cases, but few delegates for QBRTCClientDelegate are not getting called.

didReceiveNewSession,connectionClosedForUser,sessionDidClose gets called, but few other delegates are not called
like hungUpByUser,didChangeState,connectedToUser,acceptedByUser are not called.

Source file which handles call : https://www.dropbox.com/s/bvvsw3tudc5fam1/TempVC.swift?dl=0

I have already connected to chat and few delegate methods are called too as mentioned above.

**Comment by hcrgithub** [comment]
Here is the complete project : https://www.dropbox.com/s/pd3hx8qteed7kv2/CallAudioVideo.zip?dl=0

**Comment by hcrgithub** [comment]
Finally I got the solution. 

I followed the tutorial at https://quickblox.com/developers/Sample-webrtc-ios to create a video calling app, but there are many important issues in the tutorial for Swift which was creating an issue.

The issue was mainly in method definition. For an example,

In tutorial, the hungUpByUser method shown for Swift is 

Wrong :
func session(_ session: QBRTCSession, hungUpByUser userID: NSNumber, userInfo: [NSObject : AnyObject]) {
      
}

**Correct** :
func session(_ session: QBRTCSession, hungUpByUser userID: NSNumber, userInfo: [String : String]? = nil) {
    
}

So due to incorrect method implementation of the code at the tutorial, the delegates were not getting called.

Regards
Hooda

**Comment by Raikerian** [comment]
Thank you for pointing that out, fixed that part of the doc on the website

**Comment by hcrgithub** [comment]
Hi Raikerian, this was just one of the method I pointed out, but there might be other method signature not confirming to the syntax it should be.

Example at tutorial: 
Wrong : 

func session(session: QBRTCSession!, acceptedByUser userID: NSNumber!, userInfo: [NSObject : AnyObject]!) {
 
}

Correct : 

func session(_ session: QBRTCSession, acceptedByUser userID: NSNumber, userInfo: [String : String]? = nil) {

 }

I hope the tutorial will be updated, so no one else in the future gets an issue in delegate calls by following the tutorial.

**Comment by Raikerian** [comment]
Fixed that one too. Unfortunately, we don't have swift video sample now, so some of the swift code can use old syntax.
