### ISSUE TITLE
Group Created After Join Immediately the user Not working in Android.

### ISSUE THREAD

**Issue by Mani101991** [QuickBlox/quickblox-ios-sdk#885]
Hi Team,

Hello i am using quickblox SDK in Android. UserA Group is created after join immediately 
 in group. That user cannot be joined. once UserA is Background to enter foreground working fine. Please look on this issue and fix this ASAP.

**Comment by Pro100Andrey** [comment]
Hi @Mani101991, 

Could you please provide full logs? For enable logging use code bellow:

```objc
 [QBSettings setLogLevel:QBLogLevelDebug];
 [QBSettings enableXMPPLogging];
```

**Comment by Mani101991** [comment]
Hello @Pro100Andrey 
This is the log. Please look on this below

> org.jivesoftware.smack.SmackException$NoResponseException: No response received within reply timeout. Timeout was 5000ms (~5s). Used filter: AndFilter: (FromMatchesFilter (full): 61104_59ca4568a0eb472e0b3a79d1@muc.chat.quickblox.com/33382641, StanzaTypeFilter: Presence).
09-26 17:47:59.201 5227-7502/com.chat W/System.err: at org.jivesoftware.smack.PacketCollector.nextResultOrThrow(Unknown Source)
09-26 17:47:59.202 5227-7502/com.chat W/System.err: at org.jivesoftware.smackx.muc.MultiUserChat.enter(Unknown Source)
09-26 17:47:59.203 5227-7502/com.chat W/System.err: at org.jivesoftware.smackx.muc.MultiUserChat.join(Unknown Source)
09-26 17:47:59.204 5227-7502/com.chat W/System.err: at com.quickblox.chat.QBGroupChat.join(Unknown Source)
09-26 17:47:59.205 5227-7502/com.chat W/System.err: at com.quickblox.chat.model.QBChatDialog.join(Unknown Source)
09-26 17:47:59.207 5227-7502/com.chat W/System.err: at com.chat.quickblox.quickblox_core.qb.helpers.QBChatHelper.joinRoomChat(QBChatHelper.java:687)
09-26 17:47:59.208 5227-7502/com.chat W/System.err: at com.chat.quickblox.quickblox_core.qb.helpers.QBChatHelper.createGroupChat(QBChatHelper.java:769)
09-26 17:47:59.210 5227-7502/com.chat W/System.err: at com.chat.activity.NewGroup$1.run(NewGroup.java:172)
09-26 17:47:59.211 5227-7502/com.chat W/System.err: at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
09-26 17:47:59.212 5227-7502/com.chat W/System.err: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
09-26 17:47:59.214 5227-7502/com.chat W/System.err: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
09-26 17:47:59.215 5227-7502/com.chat W/System.err: at java.lang.Thread.run(Thread.java:761)

**Comment by VitaliyGuru** [comment]
@Mani101991, You have provided logs from the android device.
Please provide logs from the iOS device or create an issue in [android repo](https://github.com/QuickBlox/quickblox-android-sdk) and close this one.

**Comment by Mani101991** [comment]
Hello @Pro100Andrey  & @VitaliyGuru. Sorry. The above issues not working in only Android. Now working on Fine in iOS. Please check the issues and fix the ASAP

**Comment by Pro100Andrey** [comment]
Hi @Mani101991, 
Please create an issue in [android repo](https://github.com/QuickBlox/quickblox-android-sdk)
