### ISSUE TITLE
Quickblox Server not working properly

### ISSUE THREAD

**Issue by Mani101991** [QuickBlox/quickblox-ios-sdk#886]
Hello @Pro100Andrey 

You have mentioned that server is under maintenance today. After your server maintenance the call, chat,online,offline and everything are not working properly and its dosent showing any error too.  Before that everything are worked well. Kindly fix this issue.

**Comment by Mani101991** [comment]
Hello @VitaliyGuru 

This Error came in chat logs

> Did disconnect with error: Error Domain=QBGCDAsyncSocketErrorDomain Code=7 "Socket closed by remote peer" UserInfo={NSLocalizedDescription=Socket closed by remote peer}
> ERROR MESSAGE : Optional(Error Domain=NSCocoaErrorDomain Code=503 "Service unavailable" UserInfo={NSLocalizedDescription=Service unavailable, NSLocalizedRecoverySuggestion=Try to perform this operation again})

**Comment by Mani101991** [comment]
Hi @VitaliyGuru and @soulfly 

It is a serious issues. Please fix this ASAP

**Comment by Pro100Andrey** [comment]
Hi @Mani101991, Fixed. Thanks!

**Comment by Mani101991** [comment]
Hello @Pro100Andrey, 

Thanks. i will check and let you know.

**Comment by Mani101991** [comment]
Hello @Pro100Andrey 

System Message not working. i will trying to send system message

But that error came

Error Domain=libxmlErrorDomain Code=68 "StartTag: invalid element name
" UserInfo={NSLocalizedDescription=StartTag: invalid element name
}

Please check and fix this ASAP

**Comment by Pro100Andrey** [comment]
Hi @Mani101991 Please provide full logs

**Comment by Mani101991** [comment]
Hi @Pro100Andrey,

Thank you so much for your quick response and work. Well done, And I am using your SDK for both android and ios. In iOS, every problem is solved and everything is working perfect and nice. But In Android, issues are there and I already locked the issues in the GitHub for Android SDK  and no response is arrived from your side as like ios kindly fix that issues too.

**Comment by Pro100Andrey** [comment]
@Mani101991,
Could you please close the issue if problem has been resolved?

Thanks.

**Comment by Mani101991** [comment]
Hello @Pro100Andrey 

I will close this issue. Please see it Android SDK issues in github and fix this ASAP
