### ISSUE TITLE
Can we get others users privacy lists data in quickblox?

### ISSUE THREAD

**Issue by githubmss** [QuickBlox/quickblox-ios-sdk#888]
Please help to get all users privacy list through quickblox.

**Comment by Pro100Andrey** [comment]
Hi @githubmss,
Could you please check and fill issue template ?

**Comment by Pro100Andrey** [comment]
Hi @githubmss,

Please check [Retrieve a privacy list](https://quickblox.com/developers/SimpleSample-chat_users-ios#Retrieve_a_privacy_list)

```objc
[[QBChat instance] addDelegate:self];
[[QBChat instance] retrievePrivacyListWithName:@"public"];

#pragma mark -
#pragma mark QBChatDelegate
 
- (void)chatDidReceivePrivacyList:(QBPrivacyList *)privacyList {
    NSLog(@"Privacy items: %@", privacyList.privacyItems);
}
```
Thanks.

**Comment by VitaliyGuru** [comment]
@githubmss,  Closed due to template absence. Please create an issue again and fill template.
