### ISSUE TITLE
Chat without Request Invitation :  

### ISSUE THREAD

**Issue by Mani101991** [QuickBlox/quickblox-ios-sdk#889]
Hi Quickblox Team and @Pro100Andrey ,

Chat without Request Invitation :  
For example :  Consider A and B is a app user and A need to chat with B and A has a contact info of B, But B doesn’t have a contact info of A. So at this time A and B are not able to chat with each other. Is there any way to chat between them without sending any invitation to B user ?

**Comment by Pro100Andrey** [comment]
Hi @Mani101991, could you please check and fill issue template ?

**Comment by Mani101991** [comment]
Hi @Pro100Andrey 

Like WhatsApp

**Comment by Pro100Andrey** [comment]
i mean 

**New Issue Checklist**

 - [ ] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [ ] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none


**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    | e.g. 8.0                                    |                                          
Quickblox iOS SDK version      | e.g. 2.7.6                                  |
QuickbloxWebRTC SDK version    | e.g. 2.2.1                                  |                               
Xcode Version                  | e.g. Xcode 8.1                              |
Repro with our demo sample     | e.g. does it happen with our demo sample?   |

**Did this work before?**


**Expected behavior**


**Actual behavior**


**Logs**

*Please use the following template for logs:*

```
<details>
<summary>Title for logs </summary>
// Your logs here
</details>
```

To enable full logs use the following code:
```
[QBSettings setLogLevel:QBLogLevelDebug];
[QBSettings enableXMPPLogging];
```

**Steps to reproduce the behavior**


**Any others comments**

**Comment by Mani101991** [comment]
Hi @Pro100Andrey 

It is not a issue and its is question i am asking.

**Comment by Pro100Andrey** [comment]
> Chat without Request Invitation :

According to REST API, [Create a dialog](https://quickblox.com/developers/SimpleSample-chat_users-ios#Create_new_dialog) query, you don't need to create a dialog for 1-1(private) chat - it will be created automatically with 1st chat message. But you can create it anyway if you need this for your application.

**Comment by Pro100Andrey** [comment]
@Mani101991, Any updates ?

**Comment by Mani101991** [comment]
Ok. i Will check and let you know. Without Request Invitation whether call will also work?

**Comment by Pro100Andrey** [comment]
@Mani101991 

>Without Request Invitation whether call will also work?

Yes

**Comment by Pro100Andrey** [comment]
Hi @Mani101991, Any updates ?

**Comment by Mani101991** [comment]
hi @Pro100Andrey 

Already we are working like this only, But without adding in contact its not showing that particular user inside the app.

**Comment by Pro100Andrey** [comment]
@Mani101991, 
You can display the dialog as a user.

To notify particular user(online) that you created a private chat you should use chat notifications - it's simple chat message with extra parameters inside. These parameters used to separate chat notifications from regular text chat messages:
```objc
// create message:
 QBChatMessage *inviteMessage = [QBChatMessage message];
 
NSMutableDictionary *customParams = [NSMutableDictionary new];
customParams[@"name"] = dialog.name;
customParams[@"_id"] = dialog.ID;
customParams[@"type"] = @(dialog.type);
customParams[@"occupants_ids"] = [dialog.occupantIDs componentsJoinedByString:@","];
 //Add notification_type=1 to extra params when you created a private chat 
customParams[@"notification_type"] = @"1";
inviteMessage.customParameters = customParams;

[[QBChat instance] sendSystemMessage:inviteMessage completion:^(NSError * _Nullable error) {
 
}];
```
Particular user will receive this in delegate:
```objc
- (void)chatDidReceiveSystemMessage:(QBChatMessage *)message
{
}
```
if particular user offline - use  [Request Dialogs each time user logins to app](https://quickblox.com/developers/SimpleSample-chat_users-ios#Retrieve_list_of_dialogs)

**Comment by Pro100Andrey** [comment]
@Mani101991 , Or use Chat with auto Request Invitation )

**Comment by Pro100Andrey** [comment]
@Mani101991, 

[Please check documentation](https://quickblox.com/developers/SimpleSample-chat_users-ios#Add.2FRemove_users)

To add users to the contact list just use the method below:
```objc
[[QBChat instance] addUserToContactListRequest:24123 completion:^(NSError * _Nullable error) {
 
}];
```

This user will receive the request to be added to the contact list:
```objc
#pragma mark -
#pragma mark QBChatDelegate
 
- (void)chatDidReceiveContactAddRequestFromUser:(NSUInteger)userID{
    //Auto confirm the request:
   [[QBChat instance] confirmAddContactRequest: userID completion:^(NSError * _Nullable error) {
 
  }];
}
```

**Comment by Mani101991** [comment]
Hi @Pro100Andrey 

Already Implemented for this method. But working on sometime and not working sometime. 

I was trying to send a message to another user via Android

For This issue came below
 

>    === REQUEST ==== d72def66-8966-4675-8db7-8d9563bff77c 
>                                                      REQUEST
>                                                          POST https://api.quickblox.com/chat/Dialog.json
>                                                      HEADERS
>                                                          QuickBlox-REST-API-Version=0.1.1
>                                                          QB-SDK=Android 3.4
>                                                          QB-Token=83e5f623d5a285c3b64f606ef0ff84623900eeb0
>                                                      PARAMETERS
>                                                          type=3
>                                                          occupants_ids=35210286
>                                                      INLINE
>                                                          POST https://api.quickblox.com/chat/Dialog.json?type=3&occupants_ids=35210286
> 
> 
>                                                      *** RESPONSE *** d72def66-8966-4675-8db7-8d9563bff77c 
>                                                      STATUS : 422 
>                                                      HEADERS
>                                                          X-Runtime=0.007880
>                                                          Cache-Control=no-cache
>                                                          QuickBlox-REST-API-Version=0.1.1
>                                                          X-Android-Selected-Protocol=http/1.1
>                                                          Set-Cookie=_mkra_ctxt=5d430d1b1db1b502d5ac9c87545cca8b--422; path=/; max-age=5; HttpOnly; secure
>                                                          QB-Token-ExpirationDate=2017-10-16 12:12:27 +0000
>                                                          Status=422 Unprocessable Entity
>                                                          X-Request-Id=bf669ee4-0f98-43f2-bfce-351880a87b95
>                                                          X-Android-Response-Source=NETWORK 422
>                                                          Connection=Close
>                                                          X-Android-Sent-Millis=1508149409763
>                                                          Content-Type=application/json; charset=utf-8
>                                                          Date=Mon, 16 Oct 2017 10:23:31 GMT
>                                                          X-Content-Type-Options=nosniff
>                                                          Content-Length=45
>                                                          Server=openresty/1.9.15.1
>                                                          Strict-Transport-Security=max-age=31536000
>                                                          X-XSS-Protection=1; mode=block
>                                                          X-Frame-Options=SAMEORIGIN
>                                                          X-Android-Received-Millis=1508149410418
>                                                          Access-Control-Allow-Origin=*
>                                                      BODY
>                                                          '{"errors":{"base":["Forbidden. Need user."]}}'
> 
> 
> 
> 
>

**Comment by Pro100Andrey** [comment]
@Mani101991, you should login to user before create / get dialogs

**Comment by Pro100Andrey** [comment]
@Mani101991,

When someone connects with an app using QuickBlox, the app will be able to obtain an access token which provides temporary, secure access to QuickBlox APIs.

Expiration time for session token is 2 hours after last request to REST API.

**Comment by Pro100Andrey** [comment]
@Mani101991 Any updates ?

**Comment by Mani101991** [comment]
Hi @Pro100Andrey 

Dialog Cannot created

**Comment by Pro100Andrey** [comment]
@Mani101991, Could you please provide iOS logs ?

**Comment by Mani101991** [comment]
Hi @Pro100Andrey 

iOS Working fine. But Android not working.

> REQUEST
> POST https://api.quickblox.com/chat/Dialog.json
> HEADERS
> QuickBlox-REST-API-Version=0.1.1
> QB-SDK=Android 3.4
> QB-Token=83e5f623d5a285c3b64f606ef0ff84623900eeb0
> PARAMETERS
> type=3
> occupants_ids=35210286
> INLINE
> POST https://api.quickblox.com/chat/Dialog.json?type=3&occupants_ids=35210286

> *** RESPONSE *** d72def66-8966-4675-8db7-8d9563bff77c ***
                                                     STATUS : 422 
                                                     HEADERS
                                                         X-Runtime=0.007880
                                                         Cache-Control=no-cache
                                                         QuickBlox-REST-API-Version=0.1.1
                                                         X-Android-Selected-Protocol=http/1.1
                                                         Set-Cookie=_mkra_ctxt=5d430d1b1db1b502d5ac9c87545cca8b--422; path=/; max-age=5; HttpOnly; secure
                                                         QB-Token-ExpirationDate=2017-10-16 12:12:27 +0000
                                                         Status=422 Unprocessable Entity
                                                         X-Request-Id=bf669ee4-0f98-43f2-bfce-351880a87b95
                                                         X-Android-Response-Source=NETWORK 422
                                                         Connection=Close
                                                         X-Android-Sent-Millis=1508149409763
                                                         Content-Type=application/json; charset=utf-8
                                                         Date=Mon, 16 Oct 2017 10:23:31 GMT
                                                         X-Content-Type-Options=nosniff
                                                         Content-Length=45
                                                         Server=openresty/1.9.15.1
                                                         Strict-Transport-Security=max-age=31536000
                                                         X-XSS-Protection=1; mode=block
                                                         X-Frame-Options=SAMEORIGIN
                                                         X-Android-Received-Millis=1508149410418
                                                         Access-Control-Allow-Origin=*
                                                     BODY
                                                         '{"errors":{"base":["Forbidden. Need user."]}}'

**Comment by Pro100Andrey** [comment]
@Mani101991 

>You should login to user before create / get dialogs (likely QB session expired )

>When someone connects with an app using QuickBlox, the app will be able to obtain an access token which provides temporary, secure access to QuickBlox APIs.
Expiration time for session token is 2 hours after last request to REST API.

**Comment by Pro100Andrey** [comment]
@Mani101991,[please check it](https://quickblox.com/developers/SimpleSample-users-android#Sign_In_with_login_.26_password)

**Comment by Pro100Andrey** [comment]
or provide the issue in [android team](https://github.com/QuickBlox/quickblox-android-sdk)

**Comment by Pro100Andrey** [comment]
@Mani101991, any updates ?

**Comment by Mani101991** [comment]
Hi @Pro100Andrey 

Thanks for your response. Please provide the issue to android Team

**Comment by VitaliyGuru** [comment]
@Mani101991, you can create an issue in [android repo](https://github.com/QuickBlox/quickblox-android-sdk).

**Comment by VitaliyGuru** [comment]
@Mani101991, please close this issue if it has been resolved.

**Comment by Pro100Andrey** [comment]
Hi @Mani101991, 
You can create an issue in [android repo](https://github.com/QuickBlox/quickblox-android-sdk).
