### ISSUE TITLE
ChatDataSource not add messages

### ISSUE THREAD

**Issue by maulik6994** [QuickBlox/quickblox-ios-sdk#890]
**New Issue Checklist**

 - [ ] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [ ] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    | e.g. 8.0                                    |                                          
Quickblox iOS SDK version      | e.g. 2.7.6                                  |
QuickbloxWebRTC SDK version    | e.g. 2.2.1                                  |                               
Xcode Version                  | e.g. Xcode 8.1                              |
Repro with our demo sample     | e.g. does it happen with our demo sample?   |

**Did this work before?**

**Expected behavior**

**Actual behavior**

**Logs**

*Please use the following template for logs:*

```
<details>
<summary>Title for logs </summary>
// Your logs here
</details>
```

To enable full logs use the following code:
```
[QBSettings setLogLevel:QBLogLevelDebug];
[QBSettings enableXMPPLogging];
```

**Steps to reproduce the behavior**

**Any others comments**

**Comment by Raikerian** [comment]
Hi,

Can you add more information on what problem do you have? We are not able to help you just by reading a title of the issue.

**Comment by maulik6994** [comment]
i am using with swift but addMessage method not adding messages

**Comment by Pro100Andrey** [comment]
Hi @maulik6994, where is it not working ?

**Comment by Pro100Andrey** [comment]
@maulik6994, Could you please provide more details ?

**Comment by maulik6994** [comment]
implement custom UI, in that 
[changeDataSource:self withMessages:messagesArray updateType:updateType];

Not getting call.
Delegate perfectly..

**Comment by VitaliyGuru** [comment]
@maulik6994, You should the following methods for data source:
```objective-c
- (void)addMessage:(QBChatMessage *)message;
- (void)addMessages:(NSArray<QBChatMessage *> *)messages;

- (void)deleteMessage:(QBChatMessage *)message;
- (void)deleteMessages:(NSArray <QBChatMessage *> *)messages;

- (void)updateMessage:(QBChatMessage *)message;
- (void)updateMessages:(NSArray <QBChatMessage *> *)messages;
```

**Comment by maulik6994** [comment]
- (void)addMessage:(QBChatMessage *)message;
- (void)addMessages:(NSArray<QBChatMessage *> *)messages;


we have used both of this methods.

Issue in QMChatDataSource object in to that not getting stored messages.

**Comment by VitaliyGuru** [comment]
@maulik6994, Could you please provide a sample project with this issue?

**Comment by maulik6994** [comment]
Ok 
here I attaching the demo.
please check it in xcode 9.0

[QuickBloxDemo.zip](https://github.com/QuickBlox/quickblox-ios-sdk/files/1394685/QuickBloxDemo.zip)

Thank you.

**Comment by VitaliyGuru** [comment]
@maulik6994, Please provide login and password for testing.

**Comment by VitaliyGuru** [comment]
[QuickBloxDemo 2.zip](https://github.com/QuickBlox/quickblox-ios-sdk/files/1398237/QuickBloxDemo.2.zip)

I have updated your project with our data source.
Just tap login button - the user is hardcoded.

One thing you should know is that our collection view is flipped upside down and that's why our data source is reversed.  So in this example new messages are added at the top of your table view.
There are two approaches:
1. use our collection view and base collection view cells.
2. flip your table view upside down.

**Comment by Pro100Andrey** [comment]
Hi @maulik6994, 

Any updates ?

Thanks

**Comment by maulik6994** [comment]
Hey, We have Holidays this week.

I will update you by Monday..

Thanking you...

**Comment by Pro100Andrey** [comment]
Hi @maulik6994,
Any updates ?

Thanks

**Comment by maulik6994** [comment]
Thanks thats Done..

one more help please.
Do you have demo of videochat in swift?

**Comment by VitaliyGuru** [comment]
@maulik6994, No, but we have planned it for the future releases. 
You can follow our [blog](https://quickblox.com/blog/) to keep track of updates.

**Comment by maulik6994** [comment]
Ok Thanks @VitaliyGuru
