### ISSUE TITLE
Can not get total number of messages for a particular dialog.

### ISSUE THREAD

**Issue by RamandeepGosal** [QuickBlox/quickblox-ios-sdk#892]
**New Issue Checklist**

 -  I have read the [Documentation](https://quickblox.com/developers/IOS)
 -  I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    | 10.3                                    |                                          
Quickblox iOS SDK version      | 2.12                                  |
QuickbloxWebRTC SDK version    | 2.6.2                                  |                               
Xcode Version                  | Xcode 8.3.1                             |
Repro with our demo sample     | N/A   |

Hi, 

I want to get total number of messages for a particular dialog as I want to apply pagination in the application. 

I am trying this - 

```
  [QBRequest countOfMessagesForDialogID:_dialog.ID extendedRequest:nil successBlock:^(QBResponse * _Nonnull response, NSUInteger count) {
    NSLog(@" TOTAL NUMBER OF MESSAGES ----> %lu", (unsigned long)count);
  } errorBlock:^(QBResponse * _Nonnull response) {
    //Error
  }];
``` 
But I am getting an error which says:
```
The resource wasn't found
```
Can you please help me with this? 
Where am I going wrong?

**Logs**

*Please use the following template for logs:*

```
<details>
<summary>Log Details </summary>
2017-10-24 10:40:16.410265+0530 Panda[265:11995] [QBCore]: Request[3]:
GET URL:https://api.quickblox.com/chat/Message.json?chat_dialog_id=59cc7f1ca0eb476423ae9ef0&limit=100
headers: {
    "Accept-Language" = "en-IN;q=1";
    "QB-OS" = "iOS 10.3.3";
    "QB-SDK" = "iOS 2.12";
    "QB-Token" = a01b7ec37b84f150857ebc32bc1c18e68f00efbf;
    "QuickBlox-REST-API-Version" = "0.1.1";
    "User-Agent" = "Panda/1.1 (iPhone; iOS 10.3.3; Scale/2.00)";
}
parameters: {
    "chat_dialog_id" = 59cc7f1ca0eb476423ae9ef0;
    limit = 100;
}
2017-10-24 10:40:16.753600+0530 Panda[265:11976] [QBCore]: Response[2]
headers: {
    "Access-Control-Allow-Origin" = "*";
    "Cache-Control" = "no-cache";
    Connection = "keep-alive";
    "Content-Length" = 40;
    "Content-Type" = "application/json; charset=utf-8";
    Date = "Tue, 24 Oct 2017 05:10:16 GMT";
    Duration = "0.351024";
    "QB-Token-ExpirationDate" = "2017-10-24 07:07:30 +0000";
    "QuickBlox-REST-API-Version" = "0.1.1";
    Server = "openresty/1.9.15.1";
    "Set-Cookie" = "_mkra_ctxt=4161c8dab7c73bd7021b00f19f6ee330--404; path=/; max-age=5; HttpOnly; secure";
    Status = "404 Not Found";
    "Strict-Transport-Security" = "max-age=31536000";
    "X-Content-Type-Options" = nosniff;
    "X-Frame-Options" = SAMEORIGIN;
    "X-Request-Id" = "aa4a1396-8475-42ce-b78c-ab6aaeda7d49";
    "X-Runtime" = "0.020773";
    "X-XSS-Protection" = "1; mode=block";
}
error: Request failed: not found (404)
reasons: {
    errors =     (
        "The resource wasn't found"
    );
}
</details>
```

**Comment by Pro100Andrey** [comment]
Hi @RamandeepGosal, 
Thanks for reporting this, we are releasing new version of SDK witch will include this fix.

Thanks

**Comment by Pro100Andrey** [comment]
https://github.com/QuickBlox/quickblox-ios-sdk/issues/892
