### ISSUE TITLE
voice issue when receiving video call to ios device 

### ISSUE THREAD

**Issue by aslam969** [QuickBlox/quickblox-ios-sdk#893]
**New Issue Checklist**

 - [ ] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [ ] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    | ios 10                               |                                          
Quickblox iOS SDK version      |2.11                              |
QuickbloxWebRTC SDK version    | 2.6                                  |                               
Xcode Version                  | xcode 9                           |
Repro with our demo sample     | e.g. does it happen with our demo sample?   |

**Did this work before?**
yes

**Expected behavior**
voice should be come with video when receving call in ios device

**Actual behavior**
only video received

**Logs**

*Please use the following template for logs:*

```
<details>
<summary>Title for logs </summary>
// Your logs here
</details>
```

To enable full logs use the following code:
```
[QBSettings setLogLevel:QBLogLevelDebug];
[QBSettings enableXMPPLogging];
```

**Steps to reproduce the behavior**

**Any others comments**

**Comment by Raikerian** [comment]
Hi,

Please attach full logs to this issue.

**Comment by Pro100Andrey** [comment]
Hi @aslam969, Any updates ?
