### ISSUE TITLE
deprecated method QBCBlob.privateUrlForID(imageID).

### ISSUE THREAD

**Issue by prographo** [QuickBlox/quickblox-ios-sdk#894]
QB: You must NEVER discontinue the functionality of QBCBlob.privateUrlForID(imageID)

Images have already been uploaded, we only store the imageID

**Comment by Pro100Andrey** [comment]
Hi @prographo,  You should NEVER use this method for security reasons. Because `privateUrlForID` can be brute-forced. You need to migrate to uid download based API.

**Comment by Pro100Andrey** [comment]
Hi @prographo, use this helper method instead:

```objc 
+ (NSString *)privateUrlForID:(NSUInteger)ID {
    
    NSString *token = QBSession.currentSession.sessionDetails.token;
    if (token == nil) {
        
        return nil;
    }
    
    return [NSString stringWithFormat:@"%@/blobs/%tu/download?token=%@", QBSettings.apiEndpoint, ID, token];
}
```

**Comment by prographo** [comment]
thx
