### ISSUE TITLE
QBChatDelegate didReceiveMessage not called for group chat when app enter foreground

### ISSUE THREAD

**Issue by fans3210** [QuickBlox/quickblox-ios-sdk#897]
**Did this work before?**
No

**Expected behavior**
For private chat message, when app enters foreground, the 'didReceiveMessage' method is triggered and all the messages that the user didn't receive will be pushed to him via this method. 

Group chat should have similar behavior since I guess it's the feature of XMPP

**Actual behavior**

As mentioned in the title, the didReceiveMessage is not triggered. The only way to get those messages is by using RESTful api like the sample chat app did - which is not what I want.

Is there any way to enable this? Is this feature available for Enterprise account?

**Comment by fans3210** [comment]
By the way, I also checked the issue #773 . It mentioned that we have to use restful api, but does enterprise account have such feature?

**Comment by Raikerian** [comment]
Hi,

There is no feature to get missed messages through xmpp for group chats. Please use REST api to gather what you have missed: https://quickblox.com/developers/SimpleSample-chat_users-ios#List_chat_messages
