### ISSUE TITLE
Android to ios Video call not working. ios app crashes when call receives.

### ISSUE THREAD

**Issue by sharmashivanu** [QuickBlox/quickblox-ios-sdk#90]
Whenever I call from Android to ios, ios app crashes.I have attached the screen shot also.I am using the SDK version 2.3. Please note ios to ios calling is working.
![ioserror](https://cloud.githubusercontent.com/assets/5424990/8251848/a440ddca-169d-11e5-81b9-a61cd512695d.jpg)

**Comment by soulfly** [comment]
Please use the latest Android WebRTC sample, we have just released it today

http://quickblox.com/developers/Sample-webrtc-android

Android SDK 2.2.5 http://quickblox.com/developers/Android#Download_Android_SDK

**Comment by mgiraldo** [comment]
Have you made all current video chat apps useless with this change? I have an iOS app that uses the non-WebRTC SDK and it stopped working.

**Comment by NirmitDagly** [comment]
@sharmashivanu Hello, I am facing the same issue and cannot figure it out that It is an issue from iOS side or from android side? Also, If you have got a proper solution then please share with me so that I can solve it. Thanks in advance.

**Comment by iSevenDays** [comment]
Hello. We are developing a new QuickbloxWebRTC SDK with many hotfixes, improvements and with a support for the latest webrtc revision, please wait.

**Comment by rajanshahsa** [comment]
@sharmashivanu Hello, I am facing the same issue with Quickblox SDK version greater than 2.2. But if I used v2.2 It wont crash. Can you please help me out?? Actually I want sound to be hear from speaker, I had written following line but didn't get any success.

 QBRTCSoundRouter.instance().initialize() 
 QBRTCSoundRouter.instance().setCurrentSoundRoute(QBRTCSoundRoute.speaker)
 QBRTCSoundRouter.instance().deinitialize()

Can you please let me know what should I do in both cases? 
1. App crash with version greater than 2.2 
2.  Transferring sound to speaker.

Thank in advance.
