### ISSUE TITLE
Endpoint detection broken

### ISSUE THREAD

**Issue by sin2** [QuickBlox/quickblox-ios-sdk#900]
When updating app using QB SDK 2.12 => QB SDK 2.14, endpoints are not automatically detected and set for enterprise solution.

However, it works when the app has a clean install.

Workaround for now is setting the endpoints manually.

**Comment by Pro100Andrey** [comment]
Hi @sin2, Could you please provide code snippet and step's for reproduce ?

Thanks!

**Comment by sin2** [comment]
Well, we setup QB the following way:
`    
    // QuickBlox
    [QBSettings setApplicationID:kQuickBloxAppID];
    [QBSettings setAuthKey:kQuickBloxAuthKey];
    [QBSettings setAuthSecret:kQuickBloxAuthSecret];
    [QBSettings setAutoReconnectEnabled:YES];
    [QBSettings setAccountKey:kQuickBloxAccountKey];
`

Prior to the update on version 2.12, this worked fine and connected to our custom endpoint automatically.

After the updating to SDK 2.14, and updating the existing app on device (without uninstalling), it failed to connect to the custom endpoint, and was instead connecting to the shared instance endpoint we first used (api.quickblox.com). We believe this is the case because we were seeing old dialogs and history from that point.

As a workaround for 2.14 we have added the following and it is working for now:
`
    QBSettings.apiEndpoint = @"https://apicustom.quickblox.com";
    QBSettings.chatEndpoint = @"chatcustom.quickblox.com";
`

**Comment by Pro100Andrey** [comment]
Hi @sin2,
Thanks for reporting this, we are releasing the new version of SDK which will include this fix.

Thanks.

**Comment by Pro100Andrey** [comment]
fixed
