### ISSUE TITLE
Push notifications (version 2.13): Can't create subscription from iOS device - "unknown attribute: bundle_identifier"

### ISSUE THREAD

**Issue by jlubeck** [QuickBlox/quickblox-ios-sdk#901]
**New Issue Checklist**

 - [x] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [x] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

Same as ticket #759 but that one is closed already and it's happening for me on version 2.13.

here is the request being sent:

```
Request[2]:
POST URL:https://domain.quickblox.com/subscriptions.json
headers: {
    "Accept-Language" = "en-AR;q=1, es-AR;q=0.9, pt-BR;q=0.8";
    "Content-Type" = "application/x-www-form-urlencoded";
    "QB-OS" = "iOS 11.0.3";
    "QB-SDK" = "iOS 2.13";
    "QB-Token" = token;
    "QuickBlox-REST-API-Version" = "0.1.1";
    "User-Agent" = "name/1.2.8 (iPhone; iOS 11.0.3; Scale/3.00)";
}
parameters: {
    device =     {
        platform = ios;
        udid = "some udid";
    };
    "notification_channels" = apns;
    "push_token" =     {
        "bundle_identifier" = "com.bundle.app";
        "client_identification_sequence" = some_identifier;
        environment = development;
    };
}
```

**Comment by Raikerian** [comment]
Hi,

If you use Enterprise plan, please submit a ticket at https://assist.quickblox.com to Enterprise department to ensure your request will be processed in shortest time. Seems like you need to update server to the newest version.

**Comment by Pro100Andrey** [comment]
Hi @jlubeck, any updates?

Thanks!

**Comment by jlubeck** [comment]
Not yet, I'm not the owner of the account, so I can't submit the ticket myself. I already told the owner so hopefully he'll do it soon.
Thanks! I'll let you know

**Comment by Pro100Andrey** [comment]
Hi @jlubeck, Any updates ?
