### ISSUE TITLE
Still seeing previous caller's video track in a new video call

### ISSUE THREAD

**Issue by shalem93** [QuickBlox/quickblox-ios-sdk#902]
**New Issue Checklist**

 - [x] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [x] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    |  11.0                                    |                                          
Quickblox iOS SDK version      |  2.9.2                                  |
QuickbloxWebRTC SDK version    |  2.6.1                                  |                               
Xcode Version                   Xcode 9                             |
Repro with our demo sample     | e.g. does it happen with our demo sample?   |

**Did this work before?**
no

**Expected behavior**
The video panel gets cleared out once I receive a remote video track.

**Actual behavior**
I can still see the face of the person I called before.

**Logs**

[quickbloxLogs.txt](https://github.com/QuickBlox/quickblox-ios-sdk/files/1464481/quickbloxLogs.txt)

**Steps to reproduce the behavior**
Jump on a call with somebody, then leave and jump with someone else this time.

**Any others comments**

Is there a way for me to clear the video buffer or to detect when the video panel is populated with the new data?

**Comment by Raikerian** [comment]
Hi,

Have you removed old video track from QBRTCRemoteVideoView by calling `-[QBRTCRemoteVideoView setVideoTrack:]` and passing nil there?
