### ISSUE TITLE
Swift Chat does not load dialog for first time

### ISSUE THREAD

**Issue by manishverma30** [QuickBlox/quickblox-ios-sdk#903]
**New Issue Checklist**

 - [x] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [x] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    | e.g. 8.0                                    |                                          
Quickblox iOS SDK version      | e.g. 2.7.6                                  |
QuickbloxWebRTC SDK version    | e.g. 2.2.1                                  |                               
Xcode Version                  | e.g. Xcode 8.1                              |
Repro with our demo sample     | e.g. does it happen with our demo sample?   |

**Did this work before?**
Yes I saw this woking before. Now in my project and sample-chat-swift this is not working. I can reproduce the issue. 

**Expected behavior**
In ChatViewController.swift this condition should get executed when we are entering with valid dialog from other Viewcontroller.
print("Dialog= \(dialog)")
// Retrieving messages
            if (self.storedMessages()?.count ?? 0 > 0 && self.chatDataSource.messagesCount() == 0) {
   self.chatDataSource.add(self.storedMessages()!)
 }

**Actual behavior**
   self.storedMessages()?.count returns with zero value.

**Logs**
Attached.

<summary>Title for logs </summary>
I have printed dialog also just before problem code area.
// Your logs here

Attached Sample-Chat-Swift-Logs

</details>
I have enabled both debug and XMPP for logging.

**Steps to reproduce the behavior**
1. Get Sample-Chat-Swift project from QuickBlox.
2. Open in Xcode and I have selected Test account swift2dev10 user.
3. you get empty screen for Select a Dialog to Chat for the first time. if you come back empty chat screen and again select any Dialog then this time it loads.
4. This is reproducible in both sample-chat-swift project and mine own project too.
Thanks.
Manish 

[Sample-Chat-Swift-Logs.docx](https://github.com/QuickBlox/quickblox-ios-sdk/files/1469926/Sample-Chat-Swift-Logs.docx)
![img_2493](https://user-images.githubusercontent.com/3597303/32768741-1e8c5f0e-c93f-11e7-996a-06211498b739.PNG)

**Comment by manishverma30** [comment]
Swift Chat issue. reproduced in sample chat swift project.

**Comment by VitaliyGuru** [comment]
@manishverma30,  Please use the Sample-Chat-Swift project from the latest release.
This issue was fixed.

**Comment by Pro100Andrey** [comment]
Hi @manishverma30, any updates ?

**Comment by manishverma30** [comment]
Hi Anndrey,
I have these lines on my project Pod file
pod 'QMServicesDevelopment', :git => 'https://github.com/QuickBlox/q-municate-services-ios.git', :branch => 'development'
pod 'QMCVDevelopment' , :git => 'https://github.com/QuickBlox/QMChatViewController-ios', :branch => 'development'
pod 'SearchEmojiOnString'


and now I should replace these with ?? please suggest 
Thanks.
Manish

**Comment by Pro100Andrey** [comment]
Hi @manishverma30, Could you provide you ChatViewController.swift?

**Comment by manishverma30** [comment]
[ChatViewController.swift.zip](https://github.com/QuickBlox/quickblox-ios-sdk/files/1508687/ChatViewController.swift.zip)
Hi Andrey,
Please find my ChatViewController.swift attached here.
Thanks.
Manish

**Comment by Pro100Andrey** [comment]
Hi @manishverma30, [Please check latest release](https://github.com/QuickBlox/quickblox-ios-sdk/blob/b5abd41b582bac44f10985f541b1614f354dc700/sample-chat-swift/sample-chat-swift/Classes/ViewControllers/ChatViewController.swift#L62)

For fix your issue, please remove 2 lines from:

```swift
override func viewWillAppear(_ animated: Bool) {
....
 -    ServicesManager.instance().chatService.addDelegate(self) // remove this line		
 -    ServicesManager.instance().chatService.chatAttachmentService.delegate = self // remove this line		
....
}
```

and from:

```swift
 override func viewDidDisappear(_ animated: Bool) {
....
 -        ServicesManager.instance().chatService.removeDelegate(self)	// remove this line			
 -        ServicesManager.instance().chatService.chatAttachmentService.delegate = nil // remove this line		
....
}
```

and add 2 lines into:
```swift
override func viewDidLoad() {
+            ServicesManager.instance().chatService.addDelegate(self) //add this line
+            ServicesManager.instance().chatService.chatAttachmentService.delegate = self add this line
}
```

**Comment by manishverma30** [comment]
Thanks you so much Andrey. issue got resolved.
Thanks.
Manish
