### ISSUE TITLE
chat notification not show.

### ISSUE THREAD

**Issue by riteshpatel0** [QuickBlox/quickblox-ios-sdk#904]
sometime foreground chat notification not fire.

**Comment by Pro100Andrey** [comment]
Hi @riteshpatel0, Could you provide Full logs, from Xcode and `QuickBlox Dashboard` -> `Push Notifications` ->  `Queue`.

Thanks!

**Comment by Pro100Andrey** [comment]
Hi @riteshpatel0, Any updates?

Thanks!

**Comment by riteshpatel0** [comment]
hi @Pro100Andrey ,
 
What should I provide from the "QuickBlox Dashboard -> Push Notifications -> Queue"? and Notification was dismiss from the this method "[self showNotification:notification usingOneByOneMode:self.isOneByOneMode];". sometime work perfectly and sometime not. I don't no where I was wrong.

**Comment by VitaliyGuru** [comment]
@riteshpatel0, Do you have any additional information we should know?

**Comment by VitaliyGuru** [comment]
@riteshpatel0, 
> What should I provide from the "QuickBlox Dashboard -> Push Notifications -> Queue"?
Sorry for the confusion. It appears that we do not need this information.

**Comment by riteshpatel0** [comment]
hi @Pro100Andrey ,

Notification was dismiss in this method [self showNotification:notification usingOneByOneMode:self.isOneByOneMode]. and I was not getting any log related to notification.

**Comment by VitaliyGuru** [comment]
@riteshpatel0, We have tested our latest samples. Notifications work as expected. Please provide some additional information.

**Comment by riteshpatel0** [comment]
hi @VitaliyGuru ,

I am not getting error in sample demo. I was getting error in my project. and I was check my project but I am not getting any error related to notification. if you want to check my notification related code. so can I send you.

**Comment by Pro100Andrey** [comment]
Hi @riteshpatel0, Could you provide your sample project with this issue?

Thanks!

**Comment by Pro100Andrey** [comment]
Hi @riteshpatel0, any updates?

**Comment by riteshpatel0** [comment]
Hi @Pro100Andrey ,

I am not working in sample project. If you need code of notification so can I give you?

**Comment by riteshpatel0** [comment]
Hi @Pro100Andrey ,

I am attach my notification code as below. please check it.

[ChatNotification.zip](https://github.com/QuickBlox/quickblox-ios-sdk/files/1588743/ChatNotification.zip)


Thanks!

**Comment by Pro100Andrey** [comment]
Hi @riteshpatel0, Provided [ChatNotification.zip](https://github.com/QuickBlox/quickblox-ios-sdk/files/1588743/ChatNotification.zip) is not a sample project (only files). Please attach project which can be run on xcode.
