### ISSUE TITLE
Problem getting total unread messages count

### ISSUE THREAD

**Issue by UtkuDalmaz** [QuickBlox/quickblox-ios-sdk#906]
Hello,

I used to be able to get total unread message count with this code successfully but now it doesn't work.

```
let dialogsIDs: NSSet = NSSet(array: [""])
            QBRequest.totalUnreadMessageCountForDialogs(withIDs: dialogsIDs as! Set<String>, successBlock: { (response, count, dialogs) -> Void in
                if (count > 0) {
                    let tabArray = self.tabBarController?.tabBar.items as NSArray!
                    let tabItem = tabArray?.object(at: 3) as! UITabBarItem
                    tabItem.badgeValue = String(count)
                }
            }) { (response: QBResponse) -> Void in

            } 
```

Cannot find a proper documentation or assistance on this topic.
Any help is appreciated. Thanks

**Comment by VitaliyGuru** [comment]
@UtkuDalmaz, Please describe your problem in details by adding actual behavior.

**Comment by VitaliyGuru** [comment]
@UtkuDalmaz, FYI,  issue without template has the lowest priority.

**Comment by UtkuDalmaz** [comment]
What template guys come on. I am just looking for a way to get total unread messages count that's all and cannot find a proper documentation. Anyone can help me or you will just ignore?

**Comment by Pro100Andrey** [comment]
Hi @UtkuDalmaz,
>  Cannot find a proper documentation or assistance on this topic.

[Unread messages count](https://quickblox.com/developers/SimpleSample-chat_users-ios#Unread_messages_count)

**Comment by UtkuDalmaz** [comment]
The problem is that when using that exact same code I get

`Cannot convert value of type '(QBResponse, UInt, [String : AnyObject]?) -> Void' to expected argument type 'qb_response_unread_messages_block_t?' (aka 'Optional<(QBResponse, UInt, Dictionary<String, Any>) -> ()>')`

**Comment by Pro100Andrey** [comment]
@UtkuDalmaz try this for swift 4

```swift
let dialogsIDs: Set<String> = ["dialogID"]

QBRequest.totalUnreadMessageCountForDialogs(withIDs: dialogsIDs, successBlock: { (response, count, dialogs) in
    
}) { (response) in
    
}
```

**Comment by Pro100Andrey** [comment]
@UtkuDalmaz, any updates?

**Comment by UtkuDalmaz** [comment]
Testing the code now.

**Comment by UtkuDalmaz** [comment]
let dialogsIDs: Set<String> = [""]
            QBRequest.totalUnreadMessageCountForDialogs(withIDs: dialogsIDs, successBlock: { (response, count, dialogs) in
       
            }) { (response) in
                print(response)
            }

I tried the code like this without any DialogID to get the total unread count but I get this response
`[QBResponse], status: 404`

**Comment by Pro100Andrey** [comment]
@UtkuDalmaz   `let dialogsIDs: Set<String> = [""]` is not empty set.
You should use   `let dialogsIDs: Set<String> = []`.

**Comment by UtkuDalmaz** [comment]
Thank you so much, man. You saved my life. By the way, try to update documentation for Swift 4. Cheers

**Comment by Pro100Andrey** [comment]
Your issue:

Hello,

> 
> I used to be able to get total unread message count with this code successfully but now it doesn't work.
> 
> let dialogsIDs: NSSet = NSSet(array: [""])
>             QBRequest.totalUnreadMessageCountForDialogs(withIDs: dialogsIDs as! Set<String>, successBlock: { (response, count, dialogs) -> Void in
>                 if (count > 0) {
>                     let tabArray = self.tabBarController?.tabBar.items as NSArray!
>                     let tabItem = tabArray?.object(at: 3) as! UITabBarItem
>                     tabItem.badgeValue = String(count)
>                 }
>             }) { (response: QBResponse) -> Void in
> 
>             } 
> Cannot find a proper documentation or assistance on this topic.
> Any help is appreciated. Thanks

doesn't contain any helpful information, please follow our advice for a quick and useful response.

Thanks.

**Comment by Pro100Andrey** [comment]
@UtkuDalmaz, as for:
 > By the way, try to update documentation for Swift 4. 

it is in progress.

Thanks!
