### ISSUE TITLE
Other Audio sound is low when playing them in video chat

### ISSUE THREAD

**Issue by sathisndot** [QuickBlox/quickblox-ios-sdk#907]
I are working on Game Application.I have a few option on WIN/LOSE the Game that are on our video chat screen and I want to add sound effects for these process like Start,Win,Lose in this game.
I've face problem that when I call these methods to play sounds outside of the video chat the volume on them sounds fine but in video chat the volume of other sound is very low. I have Explain my code below 

Version
XCode 9.0
IOS SDK 11
QuickBlox 2.9.3
QuickBlox WebRTC 2.6.1

## 
In Our Code
QBRTCClientDelegate

 QBRTCAudioSession.instance().initialize { (configuration) in
            if #available(iOS 10.0, *) {
                configuration.categoryOptions =
                    [.allowBluetooth, .allowBluetoothA2DP, .allowAirPlay, .duckOthers, .mixWithOthers, .interruptSpokenAudioAndMixWithOthers]
            } else {
                configuration.categoryOptions = [.allowBluetooth, .duckOthers,.mixWithOthers, .interruptSpokenAudioAndMixWithOthers]
            }
            configuration.mode = AVAudioSessionModeVideoChat
        }
        //Set headphone or phone receiver
        QBRTCAudioSession.instance().currentAudioDevice = QBRTCAudioDevice.receiver
        //or set speaker
        QBRTCAudioSession.instance().currentAudioDevice = QBRTCAudioDevice.speaker

**Comment by Raikerian** [comment]
Hi,

Please look into categoryOptions when initializing the audio session. Apple has different ones, you need to select which one you personally need: https://developer.apple.com/documentation/avfoundation/avaudiosessioncategoryoptions

You are currently using duckOthers and mixWithOthers, which are working exactly how you described in the post.

**Comment by Pro100Andrey** [comment]
Hi @sathisndot, Any updates?
