### ISSUE TITLE
I am trying to call video call on QuickBlox-iOS. But I am not getting continuous call

### ISSUE THREAD

**Issue by anil03** [QuickBlox/quickblox-ios-sdk#908]
Hi There,

I implement the video chat feature in iOS application, When user call through video chat to another user then I only get simple notification.
 I need to get continuous call alert when user call me. It is not happening. for example whatsapp 

Please do let me know if any code implementation or flag.

**Comment by Raikerian** [comment]
Hi,

It is done by using Apple CallKit framework. We are currently working on making SDK to work with it. It will be released with the example in our sample soon.

**Comment by Raikerian** [comment]
Check out our latest QuickbloxWebRTC framework version 2.6.3: https://quickblox.com/developers/Sample-webrtc-ios#Framework_changelog
CallKit walkthrough: https://quickblox.com/developers/Sample-webrtc-ios#Apple_CallKit

Also check our updated sample: https://github.com/QuickBlox/quickblox-ios-sdk/tree/master/sample-videochat-webrtc
