### ISSUE TITLE
How group call initiator can stop audio/video call for selected opponent?

### ISSUE THREAD

**Issue by YroJlbok** [QuickBlox/quickblox-ios-sdk#909]
**New Issue Checklist**

 - [+] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [+] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    | 11.0.3                                    |                                          
Quickblox iOS SDK version      | 2.14                                  |
QuickbloxWebRTC SDK version    | 2.6.2                                  |                               
Xcode Version                  | 9.1                              |
Repro with our demo sample     | no   |

**Did this work before?**
no

**Expected behavior**
Is there some possibility to stop audio/video call for selected opponent in group call, when I call initiator?

**Actual behavior**
Current QBRTCSession has method hungUp, but I cant use this method to stop call for some user, maybe parameter userInfo can help me, but I can't find any description about it. 

<details>
<summary>Title for logs </summary>

```logos

// Your logs here

```

</details>

**Steps to reproduce the behavior**

**Any others comments**

**Comment by Raikerian** [comment]
Hi,

You can do it by sending a system message using system message module (https://quickblox.com/developers/SimpleSample-chat_users-ios#System_notifications), on which you can just hang up call. So for example, you as an initiator, sending this message to the user in the call, and he just performs hangup.

**Comment by YroJlbok** [comment]
hi Raikerian, 
thanks for answer.
