### ISSUE TITLE
Need quickblox audio call in swift.

### ISSUE THREAD

**Issue by SagarDabhi** [QuickBlox/quickblox-ios-sdk#910]
hello, there is any video/audio calling exapmle on swift ?

**Comment by Raikerian** [comment]
Hi,

The example is only available in objc, but framework is working fully with swift.

**Comment by SagarDabhi** [comment]
Thanks for reply, already code for that but I really don't know how its work

**Comment by Raikerian** [comment]
Check out this guide to understand whats going on, there are some swift examples, but overall logic is same for both: https://quickblox.com/developers/Sample-webrtc-ios

**Comment by SagarDabhi** [comment]
Ok Thanks
