### ISSUE TITLE
User data not updating

### ISSUE THREAD

**Issue by aly-irshad** [QuickBlox/quickblox-ios-sdk#912]
I have designed the following code to check that a user exists or not.

 //checking if user exists with this email
    func quickbloxUserExistence(phone:String, callback: @escaping (Bool)->(Void)) {
        
        let arrr = QMServicesManager.instance().usersService.getUsersWithLogins([phone])
        if let arr = arrr.result as? [QBUUser], arr.count > 0{
            //user found
            callback(true)
        }
        else{
            //user not found
            callback(false)
        }
    }

It gives me right answer for the first time if the user does not exist and then I proceed to user registration in my code and everything goes well. but if the user gets deleted from QuickBlox console it always says that the user exists until I delete the app from the Phone. What's wrong I am doing. Please suggest.

**Comment by VitaliyGuru** [comment]
The user is still cached in the QMServices. QMServices aren't bonded to the console.

**Comment by aly-irshad** [comment]
So what should I do to solve this. please suggest.
