### ISSUE TITLE
Not able to fetch value from the usersMemoryStorage.

### ISSUE THREAD

**Issue by riteshpatel0** [QuickBlox/quickblox-ios-sdk#917]
I am store value in usersMemoryStorage but I am getting nil when I fetch value from the cache.

**Comment by VitaliyGuru** [comment]
@riteshpatel0, Please send us a code snippet for getting and retrieving users. Also, print 'usersMemoryStorage' array before getting.

**Comment by riteshpatel0** [comment]
hi @VitaliyGuru ,

I am using below snippet for storing user into 'usersMemoryStorage' cache.

 func storeUserToDB()
    {

        for user in arrayFriends
        {
           let userDB = QBUUser()
            userDB.id = UInt(user.chatid)!
            userDB.fullName = user.firstname
            userDB.avatarUrl = user.profileImg
            ServicesManager.instance().usersService.usersMemoryStorage.add(userDB)
        }
    }

and I am using below snippet for fetching users from the 'usersMemoryStorage' cache.

let userDB = ServicesManager.instance().usersService.usersMemoryStorage.user(withID: self.oppoid)
print(userDB)

I am getting value nil when i fetch users from the usermemory storage as above snippet.

**Comment by kalyan9691** [comment]
I am facing same issue but only in iOS 11.2.1
