### ISSUE TITLE
pod install not working sample-videochat-webrtc

### ISSUE THREAD

**Issue by Alkalouti** [QuickBlox/quickblox-ios-sdk#92]
Hi,

I try to video chat tutorial and there the error inside the application .

diff: /../Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods 
installation.

and when i try to pod install i got this error:
[!] Unable to find a target named `sample-videochat-webrtcTests`

Please advice.

**Comment by soulfly** [comment]
Please try the latest SDK version
