### ISSUE TITLE
 group video call

### ISSUE THREAD

**Issue by mohanrajmca** [QuickBlox/quickblox-ios-sdk#921]
how many member join at the same time in group video call ? . And how much internet speed need connect 4 member video call , because my group video call more then 2 member not connecting at the time , so kindly explain me how to solve the problem quickly ASOP.

**Comment by Raikerian** [comment]
> how many member join at the same time in group video call
Highly depends on the device you are using. Usually we do not recommend more than 5 users in 1 call if you are using p2p calls. Things are different if there is a serverside implemented (enterprise only): https://quickblox.com/developers/EnterpriseFeatures#Conference_video_calls

> And how much internet speed need connect 4 member video call
Prettu much any internet speed can be used. Webrtc will adapt quality to your internet speed, so you don't have much lag (unless connection is really bad).

If you are experiencing any problems, please check them in our video sample first (in the current repository) and attach full logs from two devices.
