### ISSUE TITLE
push[fieldName] array

### ISSUE THREAD

**Issue by Aragunz** [QuickBlox/quickblox-ios-sdk#922]
**New Issue Checklist**

let currentUserCustomObject = QBCOCustomObject()
        currentUserCustomObject.id  =  currentUser.userCustomId
        currentUserCustomObject.fields[push"friends"] = comUserId

        //currentUserCustomObject.fields.setValue(comUserId, forKey: "push[friends]")
        
        let communicatingUserObject = QBCOCustomObject()
        communicatingUserObject.id = customComUserId
        communicatingUserObject.fields["push[friends"] = currentUser.userId
       // communicatingUserObject.fields.setValue(currentUser.userId, forKey: "push[friends]")

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    | 11.2                                    |                                          
Quickblox iOS SDK version      | Latest                          |
QuickbloxWebRTC SDK version    | Latest                                 |                               
Xcode Version                  | e.g. Xcode 9.2                              |
Repro with our demo sample     | e.g. does it happen with our demo sample?   |

**Did this work before?**
Not sure

**Expected behavior**
 To append an integer into field with array type integer.

**Actual behavior**
Doesnt do anything
 
**Logs**

*Please use the following template for logs:*

To enable full logs use the following code:
```objc
[QBSettings setLogLevel:QBLogLevelDebug];
[QBSettings enableXMPPLogging];
```

<details>
<summary>Title for logs </summary>

```logos

// Your logs here


     
Here is the code

</details>
 All objects have read/update/delete access to open

**Steps to reproduce the behavior**


**Any others comments**

**Comment by Pro100Andrey** [comment]
Hi @Aragunz, could you provide full logs? Thanks!

**Comment by Aragunz** [comment]
It was a mistake on my part, i thought push works when creating QBCustomObject  ... customObjects.fields["push[friends]"] but that is user as special operatior when updating custom object. Thank you. i will close issue.
