### ISSUE TITLE
Set environment manually in push subscription iOS sdk

### ISSUE THREAD

**Issue by jsaadk** [QuickBlox/quickblox-ios-sdk#923]
I need to set production environment in push notification subscription without needing to archive for TestFlight or AppStore; and setting service zone in "production" does not work. Is there a way to achieve it manually.

**Comment by VitaliyGuru** [comment]
@jsaadk,
The environment is taken from the certificate your application subscribed for.
You can test APNS production environment archiving an AdHoc version of your App. The app will be using the production certificates and servers.
