### ISSUE TITLE
Video quality is very poor and volume is too slow during video call in swift.

### ISSUE THREAD

**Issue by DhananjayAwasthisyscraft** [QuickBlox/quickblox-ios-sdk#924]
I am using pod 'Quickblox-WebRTC', '~> 2.6' for video calling in ios swift and xcode 8.3.2. I am facing two problem the first one is, during video call volume is too slow an i am using this code
QBRTCAudioSession.instance().initialize()
QBRTCAudioSession.instance().currentAudioDevice = QBRTCAudioDevice.speaker
the second one is that, during video calling video quality is poor and video is stretched also, for prevent to stretching i am using this line of code 
remoteView.videoGravity = AVLayerVideoGravityResizeAspect.

**Comment by Raikerian** [comment]
> the second one is that, during video calling video quality is poor and video is stretched also, for prevent to stretching i am using this line of code
> remoteView.videoGravity = AVLayerVideoGravityResizeAspect.

This is the right solution and you are doing it right.
Regarding volume and quality issues, please attach call logs. Enable full logs by setting
`[QBRTCConfig setLogLevel:QBRTCLogLevelVerbose];`

Also, enable stat reports. To do that first enable them by setting:
`[QBRTCConfig setStatsReportTimeInterval:1.0f];`

And then print them in QBRTCClientDelegate:
```objc
- (void)session:(QBRTCSession *)__unused session updatedStatsReport:(QBRTCStatsReport *)report forUserID:(NSNumber *)userID {
    
    NSLog(@"Stats report for userID: %@\n%@", userID, [report statsString]);
}
```

**Comment by DhananjayAwasthisyscraft** [comment]
Hello Raikerian,
I am sending call logs to you, for call logs i am using this line of codes.
QBRTCConfig.setStatsReportTimeInterval(5)
QBRTCConfig.setLogLevel(QBRTCLogLevel.verbose)

func session(_ session: QBRTCBaseSession, updatedStatsReport report: QBRTCStatsReport, forUserID userID: NSNumber) {
 print("\(report.statsString())")
}
This is statsString.
(cpu)60%
CN 273ms | stun->stun/udp | (s)0bps | (r)0bps
VS (input) 640x480@10fps | (sent) 640x480@10fps
VS (enc) 280Kbps/309Kbps | (sent) 0bps/309Kbps | 15ms | H264
AvgQP (past 31 encoded frames) = 26
VR (recv) 640x480@10fps | (decoded)18 | (output)18fps | 0bps/0bps | 8ms
AS 0bps | opus
AR 0bps | opus | 126ms | (expandrate)0.342651
Packets lost: VS 0 | VR 10 | AS 0 | AR 0
(cpu)60%
CN 273ms | stun->stun/udp | (s)0bps | (r)0bps
VS (input) 640x480@10fps | (sent) 640x480@10fps
VS (enc) 280Kbps/309Kbps | (sent) 0bps/309Kbps | 15ms | H264
AvgQP (past 31 encoded frames) = 26
VR (recv) 640x480@10fps | (decoded)18 | (output)18fps | 0bps/0bps | 8ms
AS 0bps | opus
AR 0bps | opus | 126ms | (expandrate)0.342651
Packets lost: VS 0 | VR 10 | AS 0 | AR 0
(cpu)60%
CN 273ms | stun->stun/udp | (s)0bps | (r)0bps
VS (input) 640x480@10fps | (sent) 640x480@10fps
VS (enc) 280Kbps/309Kbps | (sent) 0bps/309Kbps | 15ms | H264
AvgQP (past 31 encoded frames) = 26
VR (recv) 640x480@10fps | (decoded)18 | (output)18fps | 0bps/0bps | 8ms
AS 0bps | opus
AR 0bps | opus | 126ms | (expandrate)0.342651
Packets lost: VS 0 | VR 10 | AS 0 | AR 0
(cpu)59%
CN 258ms | stun->stun/udp | (s)205Kbps | (r)169Kbps
VS (input) 640x480@9fps | (sent) 640x480@10fps
VS (enc) 84Kbps/93Kbps | (sent) 158Kbps/93Kbps | 16ms | H264
AvgQP (past 50 encoded frames) = 31
VR (recv) 640x480@13fps | (decoded)12 | (output)12fps | 123Kbps/0bps | 5ms
AS 40Kbps | opus
AR 39Kbps | opus | 285ms | (expandrate)0.0679932
Packets lost: VS 0 | VR 10 | AS 2 | AR 50
(cpu)59%
CN 258ms | stun->stun/udp | (s)205Kbps | (r)169Kbps
VS (input) 640x480@9fps | (sent) 640x480@10fps
VS (enc) 84Kbps/93Kbps | (sent) 158Kbps/93Kbps | 16ms | H264
AvgQP (past 50 encoded frames) = 31
VR (recv) 640x480@13fps | (decoded)12 | (output)12fps | 123Kbps/0bps | 5ms
AS 40Kbps | opus
AR 39Kbps | opus | 285ms | (expandrate)0.0679932
Packets lost: VS 0 | VR 10 | AS 2 | AR 50
(cpu)59%
CN 258ms | stun->stun/udp | (s)205Kbps | (r)169Kbps
VS (input) 640x480@9fps | (sent) 640x480@10fps
VS (enc) 84Kbps/93Kbps | (sent) 158Kbps/93Kbps | 16ms | H264
AvgQP (past 50 encoded frames) = 31
VR (recv) 640x480@13fps | (decoded)12 | (output)12fps | 123Kbps/0bps | 5ms
AS 40Kbps | opus
AR 39Kbps | opus | 285ms | (expandrate)0.0679932
Packets lost: VS 0 | VR 10 | AS 2 | AR 50
(cpu)55%
CN 266ms | stun->stun/udp | (s)134Kbps | (r)113Kbps
VS (input) 640x480@10fps | (sent) 640x480@10fps
VS (enc) 92Kbps/131Kbps | (sent) 88Kbps/131Kbps | 17ms | H264
AvgQP (past 50 encoded frames) = 40
VR (recv) 640x480@6fps | (decoded)7 | (output)7fps | 70Kbps/0bps | 9ms
AS 40Kbps | opus
AR 38Kbps | opus | 176ms | (expandrate)0.00872803
Packets lost: VS 0 | VR 10 | AS 2 | AR 50
(cpu)55%
CN 266ms | stun->stun/udp | (s)134Kbps | (r)113Kbps
VS (input) 640x480@10fps | (sent) 640x480@10fps
VS (enc) 92Kbps/131Kbps | (sent) 88Kbps/131Kbps | 17ms | H264
AvgQP (past 50 encoded frames) = 40
VR (recv) 640x480@6fps | (decoded)7 | (output)7fps | 70Kbps/0bps | 9ms
AS 40Kbps | opus
AR 38Kbps | opus | 176ms | (expandrate)0.00872803
Packets lost: VS 0 | VR 10 | AS 2 | AR 50
(cpu)55%
CN 266ms | stun->stun/udp | (s)134Kbps | (r)113Kbps
VS (input) 640x480@10fps | (sent) 640x480@10fps
VS (enc) 92Kbps/131Kbps | (sent) 88Kbps/131Kbps | 17ms | H264
AvgQP (past 50 encoded frames) = 40
VR (recv) 640x480@6fps | (decoded)7 | (output)7fps | 70Kbps/0bps | 9ms
AS 40Kbps | opus
AR 38Kbps | opus | 176ms | (expandrate)0.00872803
Packets lost: VS 0 | VR 10 | AS 2 | AR 50
2018-01-02 14:12:41.222 rtc::[PCON]<39861714, R:Offer> Did change ice connection state to COMPLETED
connectedToUser
connectedToUser
connectedToUser
(cpu)52%
CN 280ms | stun->stun/udp | (s)113Kbps | (r)70Kbps
VS (input) 640x480@9fps | (sent) 640x480@10fps
VS (enc) 60Kbps/74Kbps | (sent) 68Kbps/74Kbps | 15ms | H264
AvgQP (past 50 encoded frames) = 38
VR (recv) 480x360@4fps | (decoded)5 | (output)5fps | 30Kbps/0bps | 9ms
AS 39Kbps | opus
AR 36Kbps | opus | 197ms | (expandrate)0.041748
Packets lost: VS 0 | VR 10 | AS 2 | AR 50
(cpu)52%
CN 280ms | stun->stun/udp | (s)113Kbps | (r)70Kbps
VS (input) 640x480@9fps | (sent) 640x480@10fps
VS (enc) 60Kbps/74Kbps | (sent) 68Kbps/74Kbps | 15ms | H264
AvgQP (past 50 encoded frames) = 38
VR (recv) 480x360@4fps | (decoded)5 | (output)5fps | 30Kbps/0bps | 9ms
AS 39Kbps | opus
AR 36Kbps | opus | 197ms | (expandrate)0.041748
Packets lost: VS 0 | VR 10 | AS 2 | AR 50
(cpu)54%
CN 280ms | stun->stun/udp | (s)113Kbps | (r)70Kbps
VS (input) 640x480@9fps | (sent) 640x480@10fps
VS (enc) 60Kbps/74Kbps | (sent) 68Kbps/74Kbps | 15ms | H264
AvgQP (past 50 encoded frames) = 38
VR (recv) 480x360@4fps | (decoded)5 | (output)5fps | 30Kbps/0bps | 9ms
AS 39Kbps | opus
AR 36Kbps | opus | 197ms | (expandrate)0.041748
Packets lost: VS 0 | VR 10 | AS 2 | AR 50
(cpu)59%
CN 920ms | stun->stun/udp | (s)103Kbps | (r)77Kbps
VS (input) 640x480@10fps | (sent) 640x480@10fps
VS (enc) 52Kbps/49Kbps | (sent) 59Kbps/49Kbps | 14ms | H264
AvgQP (past 50 encoded frames) = 38
VR (recv) 480x360@7fps | (decoded)11 | (output)11fps | 30Kbps/0bps | 6ms
AS 39Kbps | opus
AR 42Kbps | opus | 505ms | (expandrate)0.142151
Packets lost: VS 0 | VR 10 | AS 2 | AR 50
(cpu)59%
CN 920ms | stun->stun/udp | (s)103Kbps | (r)77Kbps
VS (input) 640x480@10fps | (sent) 640x480@10fps
VS (enc) 52Kbps/49Kbps | (sent) 59Kbps/49Kbps | 14ms | H264
AvgQP (past 50 encoded frames) = 38
VR (recv) 480x360@7fps | (decoded)11 | (output)11fps | 30Kbps/0bps | 6ms
AS 39Kbps | opus
AR 42Kbps | opus | 505ms | (expandrate)0.142151
Packets lost: VS 0 | VR 10 | AS 2 | AR 50
(cpu)59%
CN 920ms | stun->stun/udp | (s)103Kbps | (r)77Kbps
VS (input) 640x480@10fps | (sent) 640x480@10fps
VS (enc) 52Kbps/49Kbps | (sent) 59Kbps/49Kbps | 14ms | H264
AvgQP (past 50 encoded frames) = 38
VR (recv) 480x360@7fps | (decoded)11 | (output)11fps | 30Kbps/0bps | 6ms
AS 39Kbps | opus
AR 42Kbps | opus | 505ms | (expandrate)0.142151
Packets lost: VS 0 | VR 10 | AS 2 | AR 50
(cpu)59%
CN 628ms | stun->stun/udp | (s)84Kbps | (r)68Kbps
VS (input) 640x480@9fps | (sent) 640x480@10fps
VS (enc) 42Kbps/53Kbps | (sent) 40Kbps/53Kbps | 16ms | H264
AvgQP (past 50 encoded frames) = 40
VR (recv) 320x240@7fps | (decoded)10 | (output)10fps | 24Kbps/0bps | 5ms
AS 40Kbps | opus
AR 40Kbps | opus | 210ms | (expandrate)0.0103149
Packets lost: VS 0 | VR 10 | AS 4 | AR 50
(cpu)59%
CN 628ms | stun->stun/udp | (s)84Kbps | (r)68Kbps
VS (input) 640x480@9fps | (sent) 640x480@10fps
VS (enc) 42Kbps/53Kbps | (sent) 40Kbps/53Kbps | 16ms | H264
AvgQP (past 50 encoded frames) = 40
VR (recv) 320x240@7fps | (decoded)10 | (output)10fps | 24Kbps/0bps | 5ms
AS 40Kbps | opus
AR 40Kbps | opus | 210ms | (expandrate)0.0103149
Packets lost: VS 0 | VR 10 | AS 4 | AR 50
(cpu)59%
CN 628ms | stun->stun/udp | (s)84Kbps | (r)68Kbps
VS (input) 640x480@9fps | (sent) 640x480@10fps
VS (enc) 42Kbps/53Kbps | (sent) 40Kbps/53Kbps | 16ms | H264
AvgQP (past 50 encoded frames) = 40
VR (recv) 320x240@7fps | (decoded)10 | (output)10fps | 24Kbps/0bps | 5ms
AS 40Kbps | opus
AR 40Kbps | opus | 210ms | (expandrate)0.0103149
Packets lost: VS 0 | VR 10 | AS 4 | AR 50
(cpu)57%
CN 471ms | stun->stun/udp | (s)90Kbps | (r)62Kbps
VS (input) 640x480@10fps | (sent) 640x480@10fps
VS (enc) 46Kbps/60Kbps | (sent) 45Kbps/60Kbps | 16ms | H264
AvgQP (past 50 encoded frames) = 34
VR (recv) 320x240@12fps | (decoded)12 | (output)12fps | 21Kbps/0bps | 4ms
AS 40Kbps | opus
AR 36Kbps | opus | 244ms | (expandrate)0.0463257
Packets lost: VS 0 | VR 13 | AS 4 | AR 56
(cpu)57%
CN 471ms | stun->stun/udp | (s)90Kbps | (r)62Kbps
VS (input) 640x480@10fps | (sent) 640x480@10fps
VS (enc) 46Kbps/60Kbps | (sent) 45Kbps/60Kbps | 16ms | H264
AvgQP (past 50 encoded frames) = 34
VR (recv) 320x240@12fps | (decoded)12 | (output)12fps | 21Kbps/0bps | 4ms
AS 40Kbps | opus
AR 36Kbps | opus | 244ms | (expandrate)0.0463257
Packets lost: VS 0 | VR 13 | AS 4 | AR 56
(cpu)57%
CN 471ms | stun->stun/udp | (s)90Kbps | (r)62Kbps
VS (input) 640x480@10fps | (sent) 640x480@10fps
VS (enc) 46Kbps/60Kbps | (sent) 45Kbps/60Kbps | 16ms | H264
AvgQP (past 50 encoded frames) = 34
VR (recv) 320x240@12fps | (decoded)12 | (output)12fps | 21Kbps/0bps | 4ms
AS 40Kbps | opus
AR 36Kbps | opus | 244ms | (expandrate)0.0463257
Packets lost: VS 0 | VR 13 | AS 4 | AR 56
(cpu)60%
CN 423ms | stun->stun/udp | (s)94Kbps | (r)68Kbps
VS (input) 640x480@10fps | (sent) 640x480@10fps
VS (enc) 55Kbps/70Kbps | (sent) 48Kbps/70Kbps | 15ms | H264
AvgQP (past 50 encoded frames) = 32
VR (recv) 320x240@4fps | (decoded)10 | (output)10fps | 23Kbps/0bps | 8ms
AS 40Kbps | opus
AR 39Kbps | opus | 235ms | (expandrate)0.0557861
Packets lost: VS 0 | VR 16 | AS 7 | AR 75
(cpu)60%
CN 423ms | stun->stun/udp | (s)94Kbps | (r)68Kbps
VS (input) 640x480@10fps | (sent) 640x480@10fps
VS (enc) 55Kbps/70Kbps | (sent) 48Kbps/70Kbps | 15ms | H264
AvgQP (past 50 encoded frames) = 32
VR (recv) 320x240@4fps | (decoded)10 | (output)10fps | 23Kbps/0bps | 8ms
AS 40Kbps | opus
AR 39Kbps | opus | 235ms | (expandrate)0.0557861
Packets lost: VS 0 | VR 16 | AS 7 | AR 75
(cpu)60%
CN 423ms | stun->stun/udp | (s)94Kbps | (r)68Kbps
VS (input) 640x480@10fps | (sent) 640x480@10fps
VS (enc) 55Kbps/70Kbps | (sent) 48Kbps/70Kbps | 15ms | H264
AvgQP (past 50 encoded frames) = 32
VR (recv) 320x240@4fps | (decoded)10 | (output)10fps | 23Kbps/0bps | 8ms
AS 40Kbps | opus
AR 39Kbps | opus | 235ms | (expandrate)0.0557861
Packets lost: VS 0 | VR 16 | AS 7 | AR 75
(cpu)61%
CN 392ms | stun->stun/udp | (s)106Kbps | (r)61Kbps
VS (input) 640x480@9fps | (sent) 640x480@10fps
VS (enc) 59Kbps/79Kbps | (sent) 61Kbps/79Kbps | 17ms | H264
AvgQP (past 50 encoded frames) = 38
VR (recv) 320x240@2fps | (decoded)21 | (output)21fps | 19Kbps/0bps | 5ms
AS 39Kbps | opus
AR 33Kbps | opus | 189ms | (expandrate)0.0997314
Packets lost: VS 0 | VR 24 | AS 8 | AR 80
(cpu)61%
CN 392ms | stun->stun/udp | (s)106Kbps | (r)61Kbps
VS (input) 640x480@9fps | (sent) 640x480@10fps
VS (enc) 59Kbps/79Kbps | (sent) 61Kbps/79Kbps | 17ms | H264
AvgQP (past 50 encoded frames) = 38
VR (recv) 320x240@2fps | (decoded)21 | (output)21fps | 19Kbps/0bps | 5ms
AS 39Kbps | opus
AR 33Kbps | opus | 189ms | (expandrate)0.0997314
Packets lost: VS 0 | VR 24 | AS 8 | AR 80
(cpu)61%
CN 392ms | stun->stun/udp | (s)106Kbps | (r)61Kbps
VS (input) 640x480@9fps | (sent) 640x480@10fps
VS (enc) 59Kbps/79Kbps | (sent) 61Kbps/79Kbps | 17ms | H264
AvgQP (past 50 encoded frames) = 38
VR (recv) 320x240@2fps | (decoded)21 | (output)21fps | 19Kbps/0bps | 5ms
AS 39Kbps | opus
AR 33Kbps | opus | 189ms | (expandrate)0.0997314
Packets lost: VS 0 | VR 24 | AS 8 | AR 80
(cpu)57%
CN 440ms | stun->stun/udp | (s)107Kbps | (r)66Kbps
VS (input) 640x480@10fps | (sent) 640x480@10fps
VS (enc) 57Kbps/90Kbps | (sent) 62Kbps/90Kbps | 16ms | H264
AvgQP (past 50 encoded frames) = 40
VR (recv) 320x240@11fps | (decoded)10 | (output)10fps | 23Kbps/0bps | 11ms
AS 40Kbps | opus
AR 38Kbps | opus | 651ms | (expandrate)0.0715332
Packets lost: VS 0 | VR 27 | AS 8 | AR 119
(cpu)57%
CN 440ms | stun->stun/udp | (s)107Kbps | (r)66Kbps
VS (input) 640x480@10fps | (sent) 640x480@10fps
VS (enc) 57Kbps/90Kbps | (sent) 62Kbps/90Kbps | 16ms | H264
AvgQP (past 50 encoded frames) = 40
VR (recv) 320x240@11fps | (decoded)10 | (output)10fps | 23Kbps/0bps | 11ms
AS 40Kbps | opus
AR 38Kbps | opus | 651ms | (expandrate)0.0715332
Packets lost: VS 0 | VR 27 | AS 8 | AR 119
(cpu)57%
CN 440ms | stun->stun/udp | (s)107Kbps | (r)66Kbps
VS (input) 640x480@10fps | (sent) 640x480@10fps
VS (enc) 57Kbps/90Kbps | (sent) 62Kbps/90Kbps | 16ms | H264
AvgQP (past 50 encoded frames) = 40
VR (recv) 320x240@11fps | (decoded)10 | (output)10fps | 23Kbps/0bps | 11ms
AS 40Kbps | opus
AR 38Kbps | opus | 651ms | (expandrate)0.0715332
Packets lost: VS 0 | VR 27 | AS 8 | AR 119
(cpu)56%
CN 645ms | stun->stun/udp | (s)120Kbps | (r)51Kbps
VS (input) 640x480@9fps | (sent) 640x480@10fps
VS (enc) 92Kbps/109Kbps | (sent) 75Kbps/109Kbps | 17ms | H264
AvgQP (past 50 encoded frames) = 27
VR (recv) 320x240@7fps | (decoded)7 | (output)7fps | 18Kbps/0bps | 9ms
AS 39Kbps | opus
AR 30Kbps | opus | 243ms | (expandrate)0.0686035
Packets lost: VS 0 | VR 27 | AS 8 | AR 124
(cpu)56%
CN 645ms | stun->stun/udp | (s)120Kbps | (r)51Kbps
VS (input) 640x480@9fps | (sent) 640x480@10fps
VS (enc) 92Kbps/109Kbps | (sent) 75Kbps/109Kbps | 17ms | H264
AvgQP (past 50 encoded frames) = 27
VR (recv) 320x240@7fps | (decoded)7 | (output)7fps | 18Kbps/0bps | 9ms
AS 39Kbps | opus
AR 30Kbps | opus | 243ms | (expandrate)0.0686035
Packets lost: VS 0 | VR 27 | AS 8 | AR 124
(cpu)56%
CN 645ms | stun->stun/udp | (s)120Kbps | (r)51Kbps
VS (input) 640x480@9fps | (sent) 640x480@10fps
VS (enc) 92Kbps/109Kbps | (sent) 75Kbps/109Kbps | 17ms | H264
AvgQP (past 50 encoded frames) = 27
VR (recv) 320x240@7fps | (decoded)7 | (output)7fps | 18Kbps/0bps | 9ms
AS 39Kbps | opus
AR 30Kbps | opus | 243ms | (expandrate)0.0686035
Packets lost: VS 0 | VR 27 | AS 8 | AR 124
(cpu)57%
CN 846ms | stun->stun/udp | (s)113Kbps | (r)86Kbps
VS (input) 640x480@10fps | (sent) 640x480@10fps
VS (enc) 53Kbps/55Kbps | (sent) 70Kbps/55Kbps | 16ms | H264
AvgQP (past 50 encoded frames) = 23
VR (recv) 320x240@10fps | (decoded)11 | (output)11fps | 33Kbps/0bps | 5ms
AS 39Kbps | opus
AR 47Kbps | opus | 217ms | (expandrate)0.423096
Packets lost: VS 1 | VR 27 | AS 17 | AR 125
(cpu)57%
CN 846ms | stun->stun/udp | (s)113Kbps | (r)86Kbps
VS (input) 640x480@10fps | (sent) 640x480@10fps
VS (enc) 53Kbps/55Kbps | (sent) 70Kbps/55Kbps | 16ms | H264
AvgQP (past 50 encoded frames) = 23
VR (recv) 320x240@10fps | (decoded)11 | (output)11fps | 33Kbps/0bps | 5ms
AS 39Kbps | opus
AR 47Kbps | opus | 217ms | (expandrate)0.423096
Packets lost: VS 1 | VR 27 | AS 17 | AR 125
(cpu)57%
CN 846ms | stun->stun/udp | (s)113Kbps | (r)86Kbps
VS (input) 640x480@10fps | (sent) 640x480@10fps
VS (enc) 53Kbps/55Kbps | (sent) 70Kbps/55Kbps | 16ms | H264
AvgQP (past 50 encoded frames) = 23
VR (recv) 320x240@10fps | (decoded)11 | (output)11fps | 33Kbps/0bps | 5ms
AS 39Kbps | opus
AR 47Kbps | opus | 217ms | (expandrate)0.423096
Packets lost: VS 1 | VR 27 | AS 17 | AR 125
(cpu)60%
CN 623ms | stun->stun/udp | (s)101Kbps | (r)59Kbps
VS (input) 640x480@9fps | (sent) 640x480@10fps
VS (enc) 63Kbps/75Kbps | (sent) 56Kbps/75Kbps | 15ms | H264
AvgQP (past 50 encoded frames) = 24
VR (recv) 480x360@5fps | (decoded)11 | (output)11fps | 17Kbps/0bps | 5ms
AS 39Kbps | opus
AR 36Kbps | opus | 143ms | (expandrate)0.107483
Packets lost: VS 1 | VR 31 | AS 17 | AR 129
(cpu)60%
CN 623ms | stun->stun/udp | (s)101Kbps | (r)59Kbps
VS (input) 640x480@9fps | (sent) 640x480@10fps
VS (enc) 63Kbps/75Kbps | (sent) 56Kbps/75Kbps | 15ms | H264
AvgQP (past 50 encoded frames) = 24
VR (recv) 480x360@5fps | (decoded)11 | (output)11fps | 17Kbps/0bps | 5ms
AS 39Kbps | opus
AR 36Kbps | opus | 143ms | (expandrate)0.107483
Packets lost: VS 1 | VR 31 | AS 17 | AR 129
(cpu)60%
CN 623ms | stun->stun/udp | (s)101Kbps | (r)59Kbps
VS (input) 640x480@9fps | (sent) 640x480@10fps
VS (enc) 63Kbps/75Kbps | (sent) 56Kbps/75Kbps | 15ms | H264
AvgQP (past 50 encoded frames) = 24
VR (recv) 480x360@5fps | (decoded)11 | (output)11fps | 17Kbps/0bps | 5ms
AS 39Kbps | opus
AR 36Kbps | opus | 143ms | (expandrate)0.107483
Packets lost: VS 1 | VR 31 | AS 17 | AR 129
(cpu)54%
CN 630ms | stun->stun/udp | (s)114Kbps | (r)64Kbps
VS (input) 640x480@10fps | (sent) 640x480@10fps
VS (enc) 81Kbps/83Kbps | (sent) 72Kbps/83Kbps | 17ms | H264
AvgQP (past 50 encoded frames) = 22
VR (recv) 480x360@10fps | (decoded)10 | (output)10fps | 21Kbps/0bps | 7ms
AS 39Kbps | opus
AR 39Kbps | opus | 129ms | (expandrate)0.20343
Packets lost: VS 1 | VR 32 | AS 17 | AR 129
(cpu)54%
CN 630ms | stun->stun/udp | (s)114Kbps | (r)64Kbps
VS (input) 640x480@10fps | (sent) 640x480@10fps
VS (enc) 81Kbps/83Kbps | (sent) 72Kbps/83Kbps | 17ms | H264
AvgQP (past 50 encoded frames) = 22
VR (recv) 480x360@10fps | (decoded)10 | (output)10fps | 21Kbps/0bps | 7ms
AS 39Kbps | opus
AR 39Kbps | opus | 129ms | (expandrate)0.20343
Packets lost: VS 1 | VR 32 | AS 17 | AR 129
(cpu)54%
CN 630ms | stun->stun/udp | (s)114Kbps | (r)64Kbps
VS (input) 640x480@10fps | (sent) 640x480@10fps
VS (enc) 81Kbps/83Kbps | (sent) 72Kbps/83Kbps | 17ms | H264
AvgQP (past 50 encoded frames) = 22
VR (recv) 480x360@10fps | (decoded)10 | (output)10fps | 21Kbps/0bps | 7ms
AS 39Kbps | opus
AR 39Kbps | opus | 129ms | (expandrate)0.20343
Packets lost: VS 1 | VR 32 | AS 17 | AR 129

**Comment by Raikerian** [comment]
You can set up video quality on a sender side: https://quickblox.com/developers/Sample-webrtc-ios#Switch_camera
As for audio, there should not be any problems if you have correctly activated audio session: https://quickblox.com/developers/Sample-webrtc-ios#Audio_Session_.28Previously_Sound_Router.29

Check out our video sample in the current repository to see if the problem is persistent there, and compare it to your implementation.
