### ISSUE TITLE
Display video attachment with thumbnail

### ISSUE THREAD

**Issue by SalmanGhumsani** [QuickBlox/quickblox-ios-sdk#925]
Hi Team,

I am implementing send and receive the video attachment with the help of **QMChatViewController** I am able to get the video from the user and also able to send it to another person and this is works perfectly but there is a problem to show it and download it.
Can you please explain if you have any method to download the video or thumbnail?

I am using for sending the video:
```

            let message = QBChatMessage()
            message.senderID = self.senderID
            message.dialogID = self.dialog.id
            message.dateSent = Date()
            let videoAttachment = QBChatAttachment.videoAttachment(withFileURL: videoUrl)
             ServicesManager.instance().chatService.sendAttachmentMessage(message, to: self.dialog, with: videoAttachment, completion: { (error) in
                if error == nil {
                    print("Success")
                }
                print(error)
             }) 
```

**Comment by VitaliyGuru** [comment]
@SalmanGhumsani, Hello.
Please take a look at [this method implementation of QMAttachmentAssetService](https://github.com/QuickBlox/q-municate-services-ios/blob/master/QMChatService/QMChatService/QMAttachmentService/QMAttachmentAssetService/QMAttachmentAssetService.m#L40-L87).

QMAttachmentAssetService is part of [QMServices](https://github.com/QuickBlox/q-municate-services-ios) with high-level API for Chat features.

**Comment by jasminpethani** [comment]
@SalmanGhumsani 

How did you show video option because i am not able to find any options which provides selecting video from attachments option on screen ??
