### ISSUE TITLE
CustomObject creation error

### ISSUE THREAD

**Issue by manishverma30** [QuickBlox/quickblox-ios-sdk#927]
Hi ,
I am having issue with creation of custom Object. I am using both Objective C and Swift code to create custom object but I am getting error " Error reasons:{
    errors =     (
        "Undefined class"
    );
and
[QBResponse], status: 403
This code use to work before and I have created many custom object but now I am getting error as above all the time for both Objective C and Swift code.
My Objective C code is something like this for creation of Custom Object which use to work not not anymore.
 QBCOCustomObject *object = [QBCOCustomObject customObject];
        object.className = @"doctor_schedulesmytest"; // object Class name
        object.ID = [NSString stringWithFormat:@"%li", (unsigned long)dataPointer.theUser.ID];
        // Object fields
        [object.fields setObject:scheduleArray[0] forKey:@"Monday"];
        [object.fields setObject:scheduleArray[1] forKey:@"Tuesday"];
        [object.fields setObject:scheduleArray[2] forKey:@"Wednesday"];
        
        [QBRequest createObject:object successBlock:^(QBResponse *response, QBCOCustomObject *object) {
            // object updated
            NSLog(@" Create CustomObject successfully for USERID: %lu", (unsigned long)dataPointer.theUser.ID);
            if ( ![userDefaults valueForKey:@"docscheduleID"] )
            {
                //[userDefaults SetObject:[[[[NSBundle mainBundle] infoDictionary] objectForKey:object.ID] stringValue] forKey:@"docscheduleID"];
                [[NSUserDefaults standardUserDefaults] setObject:object.ID forKey:@"docscheduleID"];
                [[NSUserDefaults standardUserDefaults] synchronize];
                NSLog(@" Saved for docscheduleID: %@", [[NSUserDefaults standardUserDefaults]
                                                                                                 stringForKey:@"docscheduleID"]);
            }
            
        } errorBlock:^(QBResponse *response) {
            // error handling
            NSLog(@" Response CustomObject error: %@", [response.error description]);
        }];

Thanks.
Manish

**Comment by VitaliyGuru** [comment]
The error tells that you don't have the custom data structure for the class named `doctor_schedulesmytest`. [Documentation related to this issue](https://quickblox.com/developers/SimpleSample-customObjects-ios#Adding_a_Custom_Data_structure_to_your_application).
Could you please check it?

**Comment by manishverma30** [comment]
HI, I have question here, I was having this impression that I should able to create new Custom Object using IOS code that means I should be able to create new class named "doctor_schedulesmytest" using IOS code but not from Admin Panel. ??
Thanks.
Manish

**Comment by VitaliyGuru** [comment]
A custom data structure for the class in admin panel is mandatory.

**Comment by manishverma30** [comment]
Thanks got the point. so data structure has to be created first from Admin panel and then IOS code can add records in that. Its clear now. We can close this issue.
Thanks.
Manish
