### ISSUE TITLE
Incomplete chat history in a private group dialog

### ISSUE THREAD

**Issue by AsceticKumar** [QuickBlox/quickblox-ios-sdk#928]
**Scenario**: I have added a participant in a private group dialog then i removed that participant, after few conversations i added that participant again to the dialog. In that case added participant can see the list of chat messages from the time it was removed from the group. 

**Expected behavior**: Either it can see all chat messages history or from the moment it was added to the group.

Platform: android and ios
Quickblox sdk version: android(3.3.3) and ios(2.10)

**Comment by VitaliyGuru** [comment]
@YatinKwikard, This behavior can't be changed. It's Quickblox workflow.
