### ISSUE TITLE
Last message From QbChatDialog is not complete

### ISSUE THREAD

**Issue by AsceticKumar** [QuickBlox/quickblox-ios-sdk#929]
Hi,
   We are using JSON String as body for QbChatMessage . When getting the dialog list the `lastMessage` returned was incomplete . So its not a valid JSON and can not be parsed.

Could you please look into this issue ?

**Comment by VitaliyGuru** [comment]
@YatinKwikard, Hello. 

Could you please enable full logs, perform all steps to reproduce this issue and send us this information?

```
[QBSettings setLogLevel:QBLogLevelDebug];
[QBSettings enableXMPPLogging];
```
