### ISSUE TITLE
Need Push Notification Delivered Acknlowledgment.

### ISSUE THREAD

**Issue by Mani101991** [QuickBlox/quickblox-ios-sdk#932]
Hi Team,

Currently, i’m facing a problem to identify whether the message is delivered to the receiver when he killed the app and received the notification. We need to get delivered response from the quick blox. 

For Example : 
Consider User A & User B,
User A is in Online.
User B is Offline(Internet is on) and the app is in the killed state(quit).
User A is sending a message to User B.
User B receives a push notification. At this moment, User B receives the message so we need to notify User A an acknowledgment that message is delivered. But, we didn’t have any option to identify whether the User B received the sent message from User A. 
Please have a look at this comment. Let me know your solution for this.

Thanks in Advance.

**Comment by pro100andrey** [comment]
fixed
