### ISSUE TITLE
Receiving all user dialogs from the server

### ISSUE THREAD

**Issue by Amekill** [QuickBlox/quickblox-ios-sdk#934]
**New Issue Checklist**

 - [+] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [+] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    | 11.2                                    |                                          
Quickblox iOS SDK version      | 2.14                                  |
QuickbloxWebRTC SDK version    | -                                  |                               
Xcode Version                  | 9.1                              |
Repro with our demo sample     | -   |

Hello. When I get all the user's dialogs from the server, I get all private user chats + ALL public chats. How do I filter public chats that only a user is subscribed to?

Sorry for my english 😊

**Comment by VitaliyGuru** [comment]
@Amekill, Hello. 

Could you please enable full logs, perform the request and send us this information?

```
[QBSettings setLogLevel:QBLogLevelDebug];
[QBSettings enableXMPPLogging];
```

**Comment by Amekill** [comment]
@VitaliyGuru Hello. Thanks for response. Logs:

2018-01-12 15:10:23.074137+0300 Amefee[7783:955184] [QBCore]: Request[1]:
GET URL:https://api.quickblox.com/chat/Dialog.json?limit=20&sender_id%5Bin%5D=39258716&type%5Bin%5D=1
headers: {
    "Accept-Language" = "en-RU;q=1, ru-RU;q=0.9";
    "QB-OS" = "iOS 11.2.2";
    "QB-SDK" = "iOS 2.14";
    "QB-Token" = 0411f895582559bff3ce7d64596c43d5bb010074;
    "QuickBlox-REST-API-Version" = "0.1.1";
    "User-Agent" = "Amefee/1.0 (iPhone; iOS 11.2.2; Scale/2.00)";
}
parameters: {
    limit = 20;
    "sender_id[in]" = 39258716;
    "type[in]" = 1;
}
2018-01-12 15:10:24.039228+0300 Amefee[7783:955182] [QBCore]: Response[1]:
headers: {
    "Access-Control-Allow-Origin" = "*";
    "Cache-Control" = "max-age=0, private, must-revalidate";
    Connection = "keep-alive";
    "Content-Length" = 3791;
    "Content-Type" = "application/json; charset=utf-8";
    Date = "Fri, 12 Jan 2018 12:10:23 GMT";
    Duration = "0.956111";
    Etag = "W/\"f4e596eec6222b314dfdf833714a8b5d\"";
    "QB-Token-ExpirationDate" = "2018-01-12 14:01:32 +0000";
    "QuickBlox-REST-API-Version" = "0.1.1";
    Server = "openresty/1.9.15.1";
    "Set-Cookie" = "_mkra_ctxt=9eaef32f05b4302c9d6247cd7a3de8cf--200; path=/; max-age=5; HttpOnly; secure";
    Status = "304 Not Modified";
    "Strict-Transport-Security" = "max-age=31536000, max-age=15768000;";
    "X-Content-Type-Options" = nosniff;
    "X-Frame-Options" = SAMEORIGIN;
    "X-Request-Id" = "1a169828-c303-47f9-b6db-03282fa8fd18";
    "X-Runtime" = "0.019721";
    "X-XSS-Protection" = "1; mode=block";
}
object: {
    items =     (
                {
            "_id" = 5a53bc2ca0eb4709922eda19;
            "created_at" = "2018-01-08T18:45:00Z";
            "last_message" = " \U0414\U043c\U043e\U0434\U0438";
            "last_message_date_sent" = 1515486583;
            "last_message_user_id" = 39434882;
            name = testuser1;
            "occupants_ids" =             (
            );
            photo = "<null>";
            type = 1;
            "unread_messages_count" = 0;
            "updated_at" = "2018-01-09T08:29:43Z";
            "user_id" = 40487725;
            "xmpp_room_jid" = "65652_5a53bc2ca0eb4709922eda19@muc.chat.quickblox.com";
        },
                {
            "_id" = 5a41258ea28f9a156e3fb0d1;
            "created_at" = "2017-12-25T16:21:34Z";
            "last_message" = "Type a message..";
            "last_message_date_sent" = 1515418418;
            "last_message_user_id" = 40415040;
            name = "FISST PUBLIC CHAT";
            "occupants_ids" =             (
            );
            photo = "https://www.apple.com/ac/structured-data/images/knowledge_graph_logo.png";
            type = 1;
            "unread_messages_count" = 0;
            "updated_at" = "2018-01-08T13:33:38Z";
            "user_id" = 39258716;
            "xmpp_room_jid" = "65652_5a41258ea28f9a156e3fb0d1@muc.chat.quickblox.com";
        },
                {
            "_id" = 5a54b03fa28f9a0c66f1fd1c;
            "created_at" = "2018-01-09T12:06:23Z";
            "last_message" = "<null>";
            "last_message_date_sent" = "<null>";
            "last_message_user_id" = "<null>";
            name = testuser2;
            "occupants_ids" =             (
            );
            photo = "<null>";
            type = 1;
            "unread_messages_count" = 0;
            "updated_at" = "2018-01-09T12:06:23Z";
            "user_id" = 40523656;
            "xmpp_room_jid" = "65652_5a54b03fa28f9a0c66f1fd1c@muc.chat.quickblox.com";
        },
                {

            "_id" = 5a54b1e9a28f9a21f8f1fd50;
            "created_at" = "2018-01-09T12:13:29Z";
            "last_message" = "<null>";
            "last_message_date_sent" = "<null>";
            "last_message_user_id" = "<null>";
            name = testuser3;
            "occupants_ids" =             (
            );
            photo = "<null>";
            type = 1;
            "unread_messages_count" = 0;
            "updated_at" = "2018-01-09T12:13:29Z";
            "user_id" = 40523961;
            "xmpp_room_jid" = "65652_5a54b1e9a28f9a21f8f1fd50@muc.chat.quickblox.com";
        },
                {
            "_id" = 5a54b33da28f9a2631f1fd2f;
            "created_at" = "2018-01-09T12:19:09Z";
            "last_message" = "<null>";
            "last_message_date_sent" = "<null>";
            "last_message_user_id" = "<null>";
            name = testuser4;
            "occupants_ids" =             (
            );
            photo = "<null>";
            type = 1;
            "unread_messages_count" = 0;
            "updated_at" = "2018-01-09T12:19:09Z";
            "user_id" = 40524175;
            "xmpp_room_jid" = "65652_5a54b33da28f9a2631f1fd2f@muc.chat.quickblox.com";
        },
                {
            "_id" = 5a54b6f9a28f9a2284f1fd22;
            "created_at" = "2018-01-09T12:35:05Z";
            "last_message" = "<null>";
            "last_message_date_sent" = "<null>";
            "last_message_user_id" = "<null>";
            name = testuser5;
            "occupants_ids" =             (
            );
            photo = "<null>";
            type = 1;
            "unread_messages_count" = 0;
            "updated_at" = "2018-01-09T12:35:05Z";
            "user_id" = 40524818;
            "xmpp_room_jid" = "65652_5a54b6f9a28f9a2284f1fd22@muc.chat.quickblox.com";
        },
                {
            "_id" = 5a54b7e2a0eb4730272ed9ce;
            "created_at" = "2018-01-09T12:38:58Z";
            "last_message" = "<null>";
            "last_message_date_sent" = "<null>";
            "last_message_user_id" = "<null>";
            name = testuser6;
            "occupants_ids" =             (
            );
            photo = "<null>";
            type = 1;
            "unread_messages_count" = 0;
            "updated_at" = "2018-01-09T12:38:58Z";
            "user_id" = 40524946;
            "xmpp_room_jid" = "65652_5a54b7e2a0eb4730272ed9ce@muc.chat.quickblox.com";
        },
                {
            "_id" = 5a54b885a28f9a2242f1fd49;
            "created_at" = "2018-01-09T12:41:41Z";
            "last_message" = "<null>";
            "last_message_date_sent" = "<null>";
            "last_message_user_id" = "<null>";
            name = testuser7;
            "occupants_ids" =             (
            );
            photo = "<null>";
            type = 1;
            "unread_messages_count" = 0;
            "updated_at" = "2018-01-09T12:41:41Z";
            "user_id" = 40525038;
            "xmpp_room_jid" = "65652_5a54b885a28f9a2242f1fd49@muc.chat.quickblox.com";
        },
                {
            "_id" = 5a54c3efa0eb473eac2eda03;
            "created_at" = "2018-01-09T13:30:23Z";
            "last_message" = "<null>";
            "last_message_date_sent" = "<null>";
            "last_message_user_id" = "<null>";
            name = testuser8;
            "occupants_ids" =             (
            );
            photo = "<null>";
            type = 1;
            "unread_messages_count" = 0;
            "updated_at" = "2018-01-09T13:30:23Z";
            "user_id" = 40526974;
            "xmpp_room_jid" = "65652_5a54c3efa0eb473eac2eda03@muc.chat.quickblox.com";
        },
                {
            "_id" = 5a54c593a28f9a1b3bf1fd6f;
            "created_at" = "2018-01-09T13:37:23Z";
            "last_message" = "<null>";
            "last_message_date_sent" = "<null>";
            "last_message_user_id" = "<null>";
            name = testuser9;
            "occupants_ids" =             (
            );
            photo = "<null>";
            type = 1;
            "unread_messages_count" = 0;
            "updated_at" = "2018-01-09T13:37:23Z";
            "user_id" = 40527200;
            "xmpp_room_jid" = "65652_5a54c593a28f9a1b3bf1fd6f@muc.chat.quickblox.com";
        }
    );
    limit = 20;
    skip = 0;
    "total_entries" = 10;
}
[]

**Comment by VitaliyGuru** [comment]
@Amekill, Hello. You should use custom data and extended request for public dialogs in order to keep subscribed users and retrieve only needed dialogs because there is no occupants list for this type of dialog. 
[Filters documentation](https://quickblox.com/developers/SimpleSample-chat_users-ios#Filters)
[Custom data documentation](https://quickblox.com/developers/SimpleSample-chat_users-ios#Custom_parameters).
