### ISSUE TITLE
Audio call: No sound listen due to play calling sound even I stop using [QMSoundManager stopAllSounds].   

### ISSUE THREAD

**Issue by iOSMahesh** [QuickBlox/quickblox-ios-sdk#936]
I am facing audio issue from iOS to android call or iOS to iOS call.
Device A: iPhone
Device B: Android phone
Step:
1. Press call button from the iOS device. & audio initialize & play calling sound using
        QMSoundManager.playCallingSound()
 2. Call received from android phone then our delegate called So I remove calling sound.
- delegate method; session(_ session: QBRTCBaseSession, connectedToUser userID: NSNumber)
            VBQuickBloxSingleTon.shared.beepTimer?.invalidate()
            VBQuickBloxSingleTon.shared.beepTimer = nil
            QMSoundManager.instance().stopAllSounds()

Then I can't able to hear a sound until I manually switch to the current audio device to the speaker then I work fine.

**Comment by iOSMahesh** [comment]
Hi @Raikerian,

I'm using latest version 2.6.3 webRTC with swift 4.0.
I had update lib using pod but no luck to fix issue!!

**Comment by Raikerian** [comment]
1. Is it possible for you to reproduce this issue using our sample? If yes, did you make any changes (which ones). sample-videochat in current repository.
2. If 1 is not true for you, please attach full logs with stat reports from the device with the problem.

To achieve full logs in console, first turn on them before using anything webrtc related in the app by using this code:
```objc
[QBRTCConfig setLogLevel:QBRTCLogLevelVerboseWithWebRTC];
[QBRTCConfig setStatsReportTimeInterval:1.0f];
```

Then in the class, where you did subscribe to QBRTCClientDelegate, implement stat reports delegat and print them like this:
```objc
- (void)session:(QBRTCSession *)__unused session updatedStatsReport:(QBRTCStatsReport *)report forUserID:(NSNumber *)userID {
    
    NSLog(@"Stats report for userID: %@\n%@", userID, [report statsString]);
}
```

Send us full log using gist.github.com or similar services.

**Comment by iOSMahesh** [comment]
Thanks for quick response.

Let me try with #2. If it helps to find the issue otherwise I will do work on #1.

**Comment by iOSMahesh** [comment]
Hi @Raikerian 

Please check below URL contain WebRTC logs.
https://gist.github.com/iOSMahesh/031fe8698cbeff0a8b3c1ea319468587

**Comment by iOSMahesh** [comment]
Hi @Raikerian ,
Did you able to get any hint from error logs?

**Comment by iOSMahesh** [comment]
Hi @Raikerian 
Can I have more suggestion from you to fix the issue?

**Comment by Raikerian** [comment]
Main error is:
```
(RTCLogging.mm:31): (audio_device_ios.mm:372 OnDeliverRecordedData): Session:
 RTCAudioSession: {
  category: AVAudioSessionCategoryPlayAndRecord
  categoryOptions: 64
  mode: AVAudioSessionModeVoiceChat
  isActive: 1
  sampleRate: 44100.00
  IOBufferDuration: 0.011610
  outputNumberOfChannels: 2
  inputNumberOfChannels: 3
  outputLatency: 0.000771
  inputLatency: 0.000408
  outputVolume: 1.000000
}
```

Which means your audio session using incorrect settings.
Please make sure that you are correctly activating audio session before the call:
https://quickblox.com/developers/Sample-webrtc-ios#Audio_Session_.28Previously_Sound_Router.29

You can check our sample to see the correct usage.

**Comment by iOSMahesh** [comment]
Thanks @Raikerian 
Issue fixed. it's due to _AVAudioSessionCategoryOptionAllowBluetoothA2DP_ missing in my code

**Comment by iOSMahesh** [comment]
@Raikerian 
I know this issue closed but I want your helo for another issue. please check issue: https://github.com/QuickBlox/quickblox-ios-sdk/issues/1060

**Comment by Raikerian** [comment]
Hey @iOSMahesh 
Sorry, but I'm no longer working in Quickblox.

**Comment by iOSMahesh** [comment]
@Raikerian 
Thanks for quick updates. Do you know other contributor who help me. Its urgent. I'm trapped with push issue. We are going to release our app.
