### ISSUE TITLE
Sample chat swift build failure - <Quickblox/Quickblox.h> not found

### ISSUE THREAD

**Issue by StrobeGB** [QuickBlox/quickblox-ios-sdk#937]
Downloaded sample chat swift from Github, opened in Xcode 8.3.3, replaced IDs, secret and key in AppDelegate.sift then build and run (as per 5 minute install)

Build failed with <Quickblox/Quickblox.h> file not found in QBChatMessage+QBDateDivider.h.

![screen shot 2018-01-21 at 12 05 47](https://user-images.githubusercontent.com/23457270/35194040-2ed35012-fea4-11e7-8c4d-d75234d45181.png)
![screen shot 2018-01-21 at 12 06 54](https://user-images.githubusercontent.com/23457270/35194041-2f40039c-fea4-11e7-812f-0feebf5efddb.png)
![screen shot 2018-01-21 at 12 12 44](https://user-images.githubusercontent.com/23457270/35194046-7153cdae-fea4-11e7-8d0f-d72c02384fdd.png)

Where to start?

**Comment by Pro100Andrey** [comment]
Hi @StrobeGB , please check latest release https://github.com/QuickBlox/quickblox-ios-sdk/releases

**Comment by Pro100Andrey** [comment]
hi @StrobeGB, any updates?

**Comment by StrobeGB** [comment]
I didn't see the requirement for XCode 9. I've reverted from XCode 9 back to 8 due to performance issues with Swift. Could I proceed using Quickblox downloads prior to Swift 4 support, or should I abandon?

**Comment by Raikerian** [comment]
You can definitely use our sdk with any version of swift.
