### ISSUE TITLE
has the service stopped working for older apps?

### ISSUE THREAD

**Issue by mgiraldo** [QuickBlox/quickblox-ios-sdk#94]
has the service stopped working for apps that do not implement the new web-rtc sdk? video in my app suddenly stopped working and i can only imagine this is the explanation.

**Comment by soulfly** [comment]
Our TURN server is under high load, scaling it now...

**Comment by soulfly** [comment]
Now should work

**Comment by mgiraldo** [comment]
is it down again?

**Comment by soulfly** [comment]
what do you see now?

**Comment by mgiraldo** [comment]
working. but this is very unreliable :/

**Comment by mgiraldo** [comment]
is this supposed to be working?

**Comment by soulfly** [comment]
Do you still have any issues here?

**Comment by mgiraldo** [comment]
it started working again. namely video stopped working around the time of this first issue. was temporarily resolved in jun 23. but had not really worked since.

until right now.

sigh.

thanks
