### ISSUE TITLE
send message issue

### ISSUE THREAD

**Issue by sandeep102** [QuickBlox/quickblox-ios-sdk#940]
Message send successfully but.  the message go up first and then it show to bottom as last message. why this happening?. is it animation issue. this thing is happening in Demo also.

**Comment by VitaliyGuru** [comment]
Please provide screenshots or video.

**Comment by sandeep102** [comment]
![simulator screen shot - iphone 8 plus - 2018-02-01 at 05 30 55](https://user-images.githubusercontent.com/30519234/35674041-6322d9c6-0711-11e8-8bfd-f5bda9933e36.png)

screenshot just after sending message you can see the "Dad" is not at last

![simulator screen shot - iphone 8 plus - 2018-02-01 at 05 32 11](https://user-images.githubusercontent.com/30519234/35674095-93161a44-0711-11e8-90d5-82ee501394ed.png)


after 1 second it come to buttom as send message.

why this is happening?
I think this is solution is it??

https://stackoverflow.com/questions/36720985/quickblox-message-sort-on-date-sent-datesent

**Comment by sandeep102** [comment]
this is also happening in ios

**Comment by Pro100Andrey** [comment]
Hi @sandeep102 swift or objective-c?

**Comment by VitaliyGuru** [comment]
@sandeep102, You're using the latest version of the sample, aren't you?

**Comment by Pro100Andrey** [comment]
Hi @sandeep102, any updates?
