### ISSUE TITLE
Rate limit for your current plan Starter has been exceeded

### ISSUE THREAD

**Issue by MrProject13** [QuickBlox/quickblox-ios-sdk#941]
**Limit exceeded notification**

I received notification from quickblox that :
**Rate limit for your current plan Starter has been exceeded, please consider to upgrade you plan in QuickBlox dashboard to avoid any potential issues in your application. You can check available QuickBlox plans on Plans page.**

I am sure that I have not sent that much messages that starter plan exceeded. I want to know how this Starter plan limit exceeded works. 

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    | 11                                    |                                          
Quickblox iOS SDK version      | 1                                  |                       
Xcode Version                  | Xcode 8.3.2                              |

**Did this work before?**
Initially it was working smooth. But after received this notification quick blox behave like It is not connecting to server and fails the request.

**Message like**
Client error 429

**Comment by VitaliyGuru** [comment]
Hello, @MrProject13 
You can check all statistic for API Calls in your admin panel. 
http://joxi.ru/EA4K8gGCDB7eP2

I hope that helps! If you have any further questions, please [contact our support team](https://assist.quickblox.com/index.php?/Tickets/Submit).
