### ISSUE TITLE
Audio recording Button is not appeared.

### ISSUE THREAD

**Issue by mobile3000** [QuickBlox/quickblox-ios-sdk#946]
I  added  "self.inputToolBar.audioRecordingEnabled = true" in viewdidload function.
But audio recording Button is not appeared.

**Comment by Pro100Andrey** [comment]
Hi @mobile3000, any updates  ?

**Comment by mobile3000** [comment]
I have no any update.

**Comment by Pro100Andrey** [comment]
Hi @mobile3000, fixed in development branch [See](https://github.com/QuickBlox/QMChatViewController-ios/commit/30263b6314d40975a1c1dba89ef8d6576897da0e)

**Comment by mobile3000** [comment]
Thanks , I will check.

**Comment by Pro100Andrey** [comment]
Hi @mobile3000, any udpates ?

**Comment by mobile3000** [comment]
How can I use this branch?

**Comment by Pro100Andrey** [comment]
pod 'QMChatViewController', :git => 'git@github.com:QuickBlox/QMChatViewController-ios.git', :branch => 'development' ??

**Comment by mobile3000** [comment]
Thank you.
But When I install pod, I get the error.
http://prntscr.com/itemuu

**Comment by Pro100Andrey** [comment]
remove ?? )

sould be `pod 'QMChatViewController', :git => 'git@github.com:QuickBlox/QMChatViewController-ios.git', :branch => 'development'`

**Comment by mobile3000** [comment]
yes. but it is not.
http://prntscr.com/iteo2g

**Comment by Pro100Andrey** [comment]
`pod 'QMChatViewController', :git => 'https://github.com/QuickBlox/QMChatViewController-ios.git', :branch => 'development'`

**Comment by mobile3000** [comment]
Thank you.
I have installed pod file.
Then I get the error from pod file.
http://prntscr.com/itezg1

**Comment by Pro100Andrey** [comment]
@mobile3000, could you please provide your Podfile

**Comment by mobile3000** [comment]
If you can't help, sorry.

**Comment by Pro100Andrey** [comment]
Hi @mobile3000, 
🚀  QMChatViewController (0.6.1) successfully published [Changelog](https://github.com/QuickBlox/QMChatViewController-ios/releases/tag/0.6.1)

Podfile:
`pod 'QMChatViewController'`

How to update:
```bash
 pod update
```

Thanks!

**Comment by mobile3000** [comment]
Thank you.
