### ISSUE TITLE
Push Error

### ISSUE THREAD

**Issue by manojkraftly** [QuickBlox/quickblox-ios-sdk#947]
**New Issue Checklist**

 - [x] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [x] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    | e.g. 8.0                                    |                                          
Quickblox iOS SDK version      | e.g. 2.7.6                                  |
QuickbloxWebRTC SDK version    | e.g. 2.2.1                                  |                               
Xcode Version                  | e.g. Xcode 8.1                              |
Repro with our demo sample     | e.g. does it happen with our demo sample?   |

**Did this work before?**

**Expected behavior**

**Actual behavior**

**Logs**

*Please use the following template for logs:*

To enable full logs use the following code:
```objc
[QBSettings setLogLevel:QBLogLevelDebug];
[QBSettings enableXMPPLogging];
```

<details>
<summary>Title for logs </summary>

```logos

// Your logs here

```

</details>

**Steps to reproduce the behavior**

**Any others comments**

chatDialog.send(message, completionBlock:
                    {
                        (error) -> Void in
                        if error == nil
                        {
                            let push = QBMPushMessage()
                            push.alertBody = "You have a new message"
                            push.soundFile = "default"
                            QBRequest.sendPush(withText: textMessage, toUsers: "\(self.otherUserId)", successBlock: { (response, events) in
                                print(events ?? "")
                            }, errorBlock: { (error) in
                                print(error)
                            })
                        
                            
                        }
                })

**Comment by VitaliyGuru** [comment]
@manojkraftly, Hello. 


Could you please enable full logs and send us this information?
```
[QBSettings setLogLevel:QBLogLevelDebug];
[QBSettings enableXMPPLogging];
```

**Comment by Pro100Andrey** [comment]
Hi @manojkraftly, Any updates ?
