### ISSUE TITLE
Issue while sending sticker

### ISSUE THREAD

**Issue by dipendrapulse** [QuickBlox/quickblox-ios-sdk#949]
**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                     11.0                                    |                                          
Quickblox iOS SDK version      iOS 2.9.2                                  |
QuickbloxWebRTC SDK version    | e.g. 2.2.1                                  |                               
Xcode Version                  | e.g. Xcode 9.1                              |

I am finding issue while adding sticker, I am trying to use ChatViewController class as integrated into sample chat.
I followed below steps to integrate sticker
1)Created QMChatStickerOutGoingCell : QMChatCell<QMChatAttachmentCell> 
2)Added method in QMChatStickerOutGoingCell
- (void)fillWithStickerMessage: (NSString*)message downloaded: (BOOL)downloaded {
    if ([STKStickersManager isStickerMessage: message]) {
        [self.stickerImageView stk_setStickerWithMessage: message placeholder: nil placeholderColor: nil progress: nil completion: nil];
    }
3)In configureCell method added condition to download sticker
if ([cell isKindOfClass:[QMChatStickerOutGoingCell class]]){
        [(QMChatStickerOutGoingCell *)chatCell fillWithStickerMessage: message.text downloaded: [self.stickerController isStickerPackDownloaded: message.text]];
}

I also have attached screenshot how the screen looks some of the stickers are not downloaded.

![img-0831 1](https://user-images.githubusercontent.com/18593012/36601915-782e13c6-18dc-11e8-8512-8ec64a305551.PNG)

**Comment by VitaliyGuru** [comment]
@dipendrapulse, Hello.
 [http://stickerpipe.com](StickerPipe) is a third party component, so Quicbklox is not responsible for it stability. 
Try checking for an error in the method below:
```
		[self.stickerImageView stk_setStickerWithMessage:message
                                             placeholder:nil
                                        placeholderColor:nil
                                                progress:nil
                                              completion:^(NSError *error, UIImage *stickerImage) {
                                                  //Check here for error
                                              }];
```
