### ISSUE TITLE
Push Notification not working in production app

### ISSUE THREAD

**Issue by manojkraftly** [QuickBlox/quickblox-ios-sdk#952]
**New Issue Checklist**

 - [x] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [x] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    | e.g. 8.0                                    |                                          
Quickblox iOS SDK version      | e.g. 2.7.6                                  |
QuickbloxWebRTC SDK version    | e.g. 2.2.1                                  |                               
Xcode Version                  | e.g. Xcode 8.1                              |
Repro with our demo sample     | e.g. does it happen with our demo sample?   |

**Did this work before?**

**Expected behavior**

**Actual behavior**

**Logs**

*Please use the following template for logs:*

To enable full logs use the following code:
```objc
[QBSettings setLogLevel:QBLogLevelDebug];
[QBSettings enableXMPPLogging];
```

<details>
<summary>Title for logs </summary>

```logos

// Your logs here

```

</details>

**Steps to reproduce the behavior**

**Any others comments**

**Comment by VitaliyGuru** [comment]
@manojkraftly, Please add details to your issue. 

For now, we can only provide the list of well-known issues:
1. The certificate is invalid. To test your push certificate, we recommend using a third-party tool like Houston or APNS Tester to send pushes to the device. If the pushes don't work with the third party then you'll need to re-create your certs. 
2. Your device is not registered for push notifications or hasn’t subscriptions.
3. There's a problem with your provisioning profile or your XCode project is using the wrong profile/certificate.
4. You haven't uploaded Production Push Certs.

**Comment by manojkraftly** [comment]
I have checked these all points & push working fine iOS-iOS & iOS-web but getting issue with iOS-Android, Even android device already subscribed there.

**Comment by VitaliyGuru** [comment]
@manojkraftly, Could you please create an issue in [Android Repo](https://github.com/QuickBlox/quickblox-android-sdk)? 
Because as you said there are no problems on the iOS side.

**Comment by manojkraftly** [comment]
There are problems in iOS side because push not working iOS-Android

**Comment by VitaliyGuru** [comment]
@manojkraftly, What were you trying to imply with "...push not working iOS-Android"?
Please send logs with the error or any other additional information.

**Comment by VitaliyGuru** [comment]
> There are problems in iOS side

But you said before:
> I have checked these all points & push working fine iOS-iOS & iOS-web but getting issue with iOS-Android, Even android device already subscribed there.

Could you please create an issue in [Android Repo](https://github.com/QuickBlox/quickblox-android-sdk)?
