### ISSUE TITLE
how can get video/audio call history

### ISSUE THREAD

**Issue by senjaliya1989** [QuickBlox/quickblox-ios-sdk#953]
i have use quickblox. every think working fine but i can't understand how to get video/audio call history like whatsapp

**Comment by VitaliyGuru** [comment]
@senjaliya1989, Hello.
The call history can be implemented by dint of notification messages as in Q-municate.
Please take a look at [this category](https://github.com/QuickBlox/q-municate-ios/blob/d43696b18c9c73fe22a64a81360c8d554e2734ba/Q-municate/Categories/QBChatMessage/QBChatMessage%2BQMCallNotifications.h) which can be used as an example for implementation on your side.

**Comment by Pro100Andrey** [comment]
Hi @senjaliya1989, any updates ?
