### ISSUE TITLE
Custom Chat Engine

### ISSUE THREAD

**Issue by VishalWaman** [QuickBlox/quickblox-ios-sdk#954]
We are looking for a Custom Chat Engine that should have below capability
1.	IOS SDK
2.	Android SDK
3.	Chat + Voice + Video Feature
4.	Custom message that should trigger a event, e.g. when user types “#” we should list an options (like dropdown) and event should trigger on user selection

**Comment by VitaliyGuru** [comment]
@VishalWaman, Hello
QuickBlox works cross-platform and we offer native SDKs for Web/iOS/Android as well as Rest APIs. You may check variety of features we offer as well as our documentation and code sample here: https://quickblox.com/developers/QuickBlox_Developers

We would love to find out more about your project and be able to advise of the best practices in similar use cases tapping into our experience of helping thousands of customers add communication and data into their apps. To get in touch and discuss your requirement please submit enterprise request on our website: https://quickblox.com/enterprise/

**Comment by VitaliyGuru** [comment]
@VishalWaman, Should you need any further information, please do not hesitate to contact us.
