### ISSUE TITLE
QuickBlox In Swift, iOS When My App in Foreground & Background then didReceiveNewSession method is called. but when in "lock-Mode" then it's not work.

### ISSUE THREAD

**Issue by Jaimin2208** [QuickBlox/quickblox-ios-sdk#956]
**New Issue Checklist**

 - [x] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [x] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    | e.g. 8.0                                    |                                          
Quickblox iOS SDK version      | e.g. 2.7.6                                  |
QuickbloxWebRTC SDK version    | e.g. 2.2.1                                  |                               
Xcode Version                  | e.g. Xcode 8.1                              |
Repro with our demo sample     | e.g. does it happen with our demo sample?   |

**Did this work before?**

**Expected behavior**

**Actual behavior**

**Logs**

*Please use the following template for logs:*

To enable full logs use the following code:
```objc
[QBSettings setLogLevel:QBLogLevelDebug];
[QBSettings enableXMPPLogging];
```

<details>
<summary>Title for logs </summary>

```logos

// Your logs here

```

</details>

**Steps to reproduce the behavior**

**Any others comments**

**Comment by Jaimin2208** [comment]
Hello Raikerian,

When My App in Foreground & Background then didReceiveNewSession method is called.
but when in "lock-Mode" then it's not work.

**Comment by VitaliyGuru** [comment]
@Jaimin2208, Please provide full logs.

**Comment by Pro100Andrey** [comment]
Hi @Jaimin2208, any updates ?

**Comment by Raikerian** [comment]
Hi,

This might be because you are disconnecting from the QBChat, whenever app goes in inactive state. Locking your phone does make it inactive.

**Comment by Pro100Andrey** [comment]
Hi @Jaimin2208, any updates ?
