### ISSUE TITLE
response Code=-1011 "Request failed: not found (404)"

### ISSUE THREAD

**Issue by siddharth3322** [QuickBlox/quickblox-ios-sdk#958]
When QMChatViewController loaded at time, I was getting this kind of error log.
Though if you test within devices then you don't feel any problem is running but xCode log showing this kind of error messages.

![exnext_chat_error](https://user-images.githubusercontent.com/3082151/37242063-f649f790-2488-11e8-839b-225f32072c83.png)

I hope above log has given you all required details. Please reply me regarding this.

**Comment by Pro100Andrey** [comment]
Hi @siddharth3322, Could you provide full logs (not screenshot)? 

Thanks!

**Comment by siddharth3322** [comment]
yes I can provide you full log now but which component, should I use? If I paste directly log over here then it will create complete mess up and all data get jumbled.

**Comment by Pro100Andrey** [comment]
@siddharth3322 use gist - https://gist.github.com

**Comment by siddharth3322** [comment]
Here is the uploaded log details:
[https://gist.github.com/siddharth3322/c1cff8b0578dba4a8af85494450b27fb](url)

**Comment by Pro100Andrey** [comment]
@siddharth3322  from your log:
- "date_sent[gte]" = 0; - **invalid field**.
and you set **nil** for dialog id in:

```objc

+ (QBRequest *)messagesWithDialogID:(NSString *)dialogID
                    extendedRequest:(NSDictionary *) extendedParameters
                            forPage:(QBResponsePage *)page
                       successBlock:(qb_response_messages_block_t)successBlock
                         errorBlock:(qb_response_block_t)errorBlock
```

**Comment by siddharth3322** [comment]
now what should I require to do for solution?

**Comment by Pro100Andrey** [comment]
@siddharth3322 
my suggestion -  update SDK to lates version [2.16](https://github.com/QuickBlox/quickblox-ios-sdk/releases)

Thanks!

**Comment by siddharth3322** [comment]
If I just update the framework file then will it work for me?

**Comment by Pro100Andrey** [comment]
Check documentation - [HOWTO Retrive chat history](https://quickblox.com/developers/SimpleSample-chat_users-ios#List_chat_messages)

**Comment by siddharth3322** [comment]
At these two places, I am assigning dialogID 
```
- (void)didPickAttachmentImage:(UIImage *)image {
    
    if (_chatUser.my_state == connection_state_completed_by_subscribed_user) {
        NSString *strHeOrShe = [_chatUser.gender  isEqual: @"M"] ? @"He" : @"She";
        [self showAlertWithTitle:@"Wait for a reply" withMessage:[NSString stringWithFormat:@"You can't send any more messages to %@ untill %@ replies.",_chatUser.name, strHeOrShe]];
        return;
    }

    QBChatMessage *message = [QBChatMessage new];
    message.senderID = self.senderID;
    message.dialogID = self.dialog.ID;
    message.dateSent = [NSDate date];
```
    
Here is another place:

```
 if (attachment.image) {
        
//         NSLog(@"-----> didPressSendButton - First - userInitiatedConnection - IF");
        [self userInitiatedConnection];

        
        QBChatMessage *message = [QBChatMessage new];
        message.senderID = self.senderID;
        message.dateSent = [NSDate date];

        if (self.dialog.ID) {
            message.dialogID = self.dialog.ID;
            
            [self.chatDataSource addMessage:message];
            
            [[QMServicesManager instance].chatService sendAttachmentMessage:message
                                                                   toDialog:self.dialog
                                                        withAttachmentImage:attachment.image
                                                                 completion:^(NSError *error) {
                                                                     
                                                                     [self.attachmentCells removeObjectForKey:message.ID];
                                                                     
                                                                     if (error != nil) {
                                                                         // perform local attachment deleting
                                                                         [self.chatDataSource deleteMessage:message];
                                                                         [self showAlertWithTitle:@"Failed" withMessage:error.localizedDescription];
                                                                         // [SVProgressHUD showErrorWithStatus:error.localizedDescription];
                                                                     }
                                                                 }];
        }
```

This is last way:

```
- (void)chatService:(QMChatService *)chatService didUpdateChatDialogInMemoryStorage:(QBChatDialog *)chatDialog {
    if (self.dialog.type != QBChatDialogTypePrivate && [self.dialog.ID isEqualToString:chatDialog.ID]) {
        self.dialog  = chatDialog;
        self.title = self.dialog.name;
    }
}
```

So at which place my ID going wrong for dialog?

**Comment by Pro100Andrey** [comment]
@siddharth3322 check  this mehtod:
```objc
+ (QBRequest *)messagesWithDialogID:(NSString *)dialogID
                    extendedRequest:(NSDictionary *) extendedParameters
                            forPage:(QBResponsePage *)page
                       successBlock:(qb_response_messages_block_t)successBlock
                         errorBlock:(qb_response_block_t)errorBlock
```

**Comment by siddharth3322** [comment]
can you tell me exactly in which class this method exist?

Within my code I can't able to find this one...

**Comment by siddharth3322** [comment]
I have not written this method any where in my code:
![messageswithdialogid_method_call](https://user-images.githubusercontent.com/3082151/37255790-6c6babe6-2577-11e8-9e76-37b6287c3998.png)

**Comment by Pro100Andrey** [comment]
https://github.com/QuickBlox/q-municate-services-ios/blob/3370000d584c46051077b99f81bf603bf8fe7682/QMChatService/QMChatService/QMChatService.m#L995

**Comment by Pro100Andrey** [comment]
yes but you call this method

**Comment by Pro100Andrey** [comment]
and you shuld check why dialogID == nil

**Comment by Pro100Andrey** [comment]
For example check our chat sample - https://github.com/QuickBlox/quickblox-ios-sdk/tree/master/sample-chat. Works fine.

**Comment by siddharth3322** [comment]
Okay I will do this 👍 

Now help me in my another posted issue.

**Comment by VitaliyGuru** [comment]
From [Quicblox "Response codes and errors" documentation](https://quickblox.com/developers/Errors):
The requested resource could not be found:
- a user tries to retrieve chat messages for invalid chat dialog id.

**Comment by Pro100Andrey** [comment]
Hi @siddharth3322, any updates ?

**Comment by sagarmseven** [comment]
how to solve issue
error: Request failed: not found (404)
reasons: {
    code = "<null>";
    message = "Couldn't find user";
}
