### ISSUE TITLE
unrecognized selector sent to instance 0x16a92400

### ISSUE THREAD

**Issue by siddharth3322** [QuickBlox/quickblox-ios-sdk#959]
When I try to close QMChatViewController at that time my application get crashed with following log details.

![exnext_app_crash](https://user-images.githubusercontent.com/3082151/37242258-50ca7b10-248c-11e8-83f2-33f49bba91c0.png)

Then I press back button of chat view dialog, list of chat users page get loaded. So I can't able to figure out whether its problem of chat view dialog or chat user list page!!
Only in iPad storyboard this kind of problem happening, iPhone storyboard not get crashed in this stage.

Please give me some suggestion into this - over all end to end chatting started working properly for me so its a good news.

From my other issue, you can get my SDK and OS related information that I just created few mins ago.
[https://github.com/QuickBlox/quickblox-ios-sdk/issues/958](url)

**Comment by siddharth3322** [comment]
Also this is more important for me to solve - because this one crashing the application.
Other one is only showing error code.

**Comment by Pro100Andrey** [comment]
@siddharth3322 , Colud you check this issue https://github.com/QuickBlox/QMChatViewController-ios/issues/133

**Comment by siddharth3322** [comment]
Yes this problem get solve if you rename following delegate:
`@property (weak, nonatomic, nullable) id<QMPlaceHolderTextViewPasteDelegate> pasteQMDelegate;`

That you found within this file:
**QMChatViewController-ios/QMChatViewController/QMChatViewController.m**
