### ISSUE TITLE
keep login session active and automatically logged in when already login to app

### ISSUE THREAD

**Issue by mayur9333** [QuickBlox/quickblox-ios-sdk#962]
**New Issue Checklist**

 - [ ] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [ ] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found non

Hey there, i am new to quickblox an trying to make an simple chat app. Here i am facing issue with session. 

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    | e.g. 8.0                                    |                                          
Quickblox iOS SDK version      | e.g. 2.7.6                                  |
QuickbloxWebRTC SDK version    | e.g. 2.2.1                                  |                               
Xcode Version                  | e.g. Xcode 8.1                              |
Repro with our demo sample     | e.g. does it happen with our demo sample?   |

**Expected behavior**
I need to app directly login if it previously opened and not logged out.

**Actual behavior**

but with my code every time i need to put email and password.please help

**Comment by VitaliyGuru** [comment]
@mayur9333, Hello
 Any questions or issues?

**Comment by mayur9333** [comment]
please check above updated block and help @VitaliyGuru

**Comment by shaharukhs** [comment]
I have same question.

**Comment by VitaliyGuru** [comment]
@mayur9333, @shaharukhs  Hello.
For this purpose, you should use [keychain](https://medium.com/ios-os-x-development/securing-user-data-with-keychain-for-ios-e720e0f9a8e2).
The same approach is used in Q-municate. You can look at [this class](https://github.com/QuickBlox/q-municate-ios/blob/17f5b930b0391fea144b46f5a082acbf8b2ca90c/Q-municate/Classes/QMProfile/QMProfile.h). We're using wrapper for the keychain named [SAMKeychain](https://github.com/soffes/SAMKeychain).

**Comment by Pro100Andrey** [comment]
hi @mayur9333 and @shaharukhs any updates?

Thanks!

**Comment by shaharukhs** [comment]
I want solution just for login session active for Text chat and Video chat

this is my current scenario when app launch then user is logged in and session is created.
but this session I want to keep alive till user did not logged out from app.
As currently I need to logged in user each time when they open apps after terminated.

for login I am using swift demo provided by you.

```
ServicesManager.instance().authService.logIn(with: self.user, completion: { (response, qbUser) in
            if qbUser != nil {
                ServicesManager.instance().chatService.connect { (error) in
                    if error != nil {
                        print("user not connected error: ",error as Any)
                    }
                }
                print(qbUser as Any)
                print("successfully logged in chat user.")
            } else {
                print(response.error?.description as Any)
            }
        })
```

**Comment by VitaliyGuru** [comment]
@shaharukhs, The solution will be the same. You should use the keychain.

**Comment by Pro100Andrey** [comment]
Hi @mayur9333 and @shaharukhs any updates?

**Comment by mayur9333** [comment]
don't have an any idea about how to use keychain. please suggest. @Pro100Andrey  @VitaliyGuru

**Comment by Pro100Andrey** [comment]
For example check [QMSplashViewController](https://github.com/QuickBlox/q-municate-ios/blob/master/Q-municate/Scenes/Start/QMSplashViewController/QMSplashViewController.m#L22) from Q-municate app 

```objc
[self performSegueWithIdentifier:QMCore.instance.currentProfile.userData != nil ? kQMSceneSegueMain : kQMSceneSegueAuth sender:nil];
```

**Comment by Pro100Andrey** [comment]
When [QMProfile](https://github.com/QuickBlox/q-municate-ios/blob/17f5b930b0391fea144b46f5a082acbf8b2ca90c/Q-municate/Classes/QMProfile/QMProfile.h)  (QMCore.instance.currentProfile) - wrapper for the keychain named [SAMKeychain](https://github.com/soffes/SAMKeychain).

**Comment by Pro100Andrey** [comment]
Hi @mayur9333 any updates?
