### ISSUE TITLE
How to ring the receiver end phone when sender call the receiver.

### ISSUE THREAD

**Issue by mayur9333** [QuickBlox/quickblox-ios-sdk#963]
Hello,
 i am working with quickblox audio call and in my app i want to play ringtone. and for that i dont have an any idea how to do same. please suggest..thanks in advance.

**Comment by Raikerian** [comment]
Hi,

Please check [QMSoundManager](https://github.com/QuickBlox/quickblox-ios-sdk/blob/master/sample-videochat-webrtc/sample-videochat-webrtc/Classes/QMSoundManager/QMSoundManager.m). We are using that class to make sounds in our video sample.

**Comment by mayur9333** [comment]
for that should i have to install pod or it comes with quickblox pod. @Raikerian

**Comment by Raikerian** [comment]
No, you have to copy that class in your project.

**Comment by Pro100Andrey** [comment]
Hi @mayur9333, any updates?
