### ISSUE TITLE
Getting extra space at bottom in QMChatViewController ?

### ISSUE THREAD

**Issue by testingmyaccount** [QuickBlox/quickblox-ios-sdk#965]
![simulator screen shot - iphone 7 - 2018-03-15 at 12 01 12](https://user-images.githubusercontent.com/36070930/37447544-96fc03b4-2848-11e8-8d23-dbdff511cad4.png)

**Comment by VitaliyGuru** [comment]
@testingmyaccount, Hello.

You should override "inputToolBarStartPos" method which is used in the QMChatViewController.

-(NSUInteger)inputToolBarStartPos {
return 0;
}

**Comment by Pro100Andrey** [comment]
Hi @testingmyaccount, any updates ?
