### ISSUE TITLE
How to maintain record button icon show/hide in QMchatViewController ?

### ISSUE THREAD

**Issue by testingmyaccount** [QuickBlox/quickblox-ios-sdk#967]
I am trying to set record button at same place of send button. The issue is for first time when i open chat screen at that time record button is there and after then when i start typing then send button is appear, but if i remove all text then again it should show record button but unfortunately it is not showing.
For showing record button in controller i did like this.

        microButton.setImage(#imageLiteral(resourceName: "mic_gray"), for: .normal)
        microButton.frame = CGRect(x: 0.0, y: 0.0, width: 44, height: 44)
        self.inputToolbar?.contentView?.rightBarButtonItem = microButton
        self.inputToolbar.contentView.rightBarButtonItem.isEnabled = false
        self.inputToolbar.contentView.rightBarButtonItem.isHidden = false

Please let me know if i am doing something wrong or is there any default method available to manage(hide/show) this two buttons(send/record).

**Comment by Pro100Andrey** [comment]
Hi @testingmyaccount use  the method bellow:
objc:
```objc
    [self.inputToolbar toggleSendButtonEnabled]; 
```
swift

objc:
```swift
    self.inputToolbar.toggleSendButtonEnabled(); 
```

**Comment by Pro100Andrey** [comment]
hi @testingmyaccount, Any updates ?

Thanks!
