### ISSUE TITLE
-(void)didReceiveNewSession:(QBRTCSession *)session userInfo:(NSDictionary<NSString *,NSString *> *)userInfo

### ISSUE THREAD

**Issue by mayur9333** [QuickBlox/quickblox-ios-sdk#968]
**New Issue Checklist**

 - [ ] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [ ] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    | e.g. 8.0                                    |                                          
Quickblox iOS SDK version      | e.g. 2.7.6                                  |
QuickbloxWebRTC SDK version    | e.g. 2.2.1                                  |                               
Xcode Version                  | e.g. Xcode 8.1                              |
Repro with our demo sample     | e.g. does it happen with our demo sample?   |

**Did this work before?**

**Expected behavior**

i need to call -(void)didReceiveNewSession:(QBRTCSession *)session userInfo:(NSDictionary<NSString *,NSString *> *)userInfo method from every view controller.

for that where should i write the same so that whenever call comes this from should run from any view controller.

**Actual behavior**
i write the method on my listview controller an when i am on same page at that time only i able to call same

**Logs**

**Comment by Raikerian** [comment]
Hi,

Ideally, you need to have this method only in 1 place. It can be either singleton class object (as we are doing it in [Q-municate here)](https://github.com/QuickBlox/q-municate-ios/blob/master/Q-municate/Classes/Core/QMCallManager/QMCallManager.m#L307-L355) or single view controller which is always sitting in your memory, like some kind of root view controller/main view controller for your app (as we are doing it in our [video sample here](https://github.com/QuickBlox/quickblox-ios-sdk/blob/master/sample-videochat-webrtc/sample-videochat-webrtc/Components/Users/ViewControllers/UsersViewController/UsersViewController.m#L411-L457)).

Either way, I'm highly recommending you to check our [video sample here](https://github.com/QuickBlox/quickblox-ios-sdk/tree/master/sample-videochat-webrtc) and see what you can take from it.

**Comment by Pro100Andrey** [comment]
Hi @mayur9333 any updates?

Thanks!
