### ISSUE TITLE
How to Handle Session

### ISSUE THREAD

**Issue by mayur9333** [QuickBlox/quickblox-ios-sdk#969]
i am integrating quickblox in my chat app. Here my requirement is maintain Session after force quiet the App. If i open again by clicking App should revert me in user list rather login page.
 please suggest how to do same.

**Comment by Pro100Andrey** [comment]
Hi @mayur9333 

For this purpose, you should use [keychain](https://medium.com/ios-os-x-development/securing-user-data-with-keychain-for-ios-e720e0f9a8e2).
The same approach is used in Q-municate. You can look at [this class](https://github.com/QuickBlox/q-municate-ios/blob/17f5b930b0391fea144b46f5a082acbf8b2ca90c/Q-municate/Classes/QMProfile/QMProfile.h). We're using wrapper for the keychain named [SAMKeychain](https://github.com/soffes/SAMKeychain).

**Comment by Pro100Andrey** [comment]
For example check [QMSplashViewController](https://github.com/QuickBlox/q-municate-ios/blob/master/Q-municate/Scenes/Start/QMSplashViewController/QMSplashViewController.m#L22)  

```objc
[self performSegueWithIdentifier:QMCore.instance.currentProfile.userData != nil ? kQMSceneSegueMain : kQMSceneSegueAuth
                              sender:nil];
```

**Comment by Pro100Andrey** [comment]
dublicat https://github.com/QuickBlox/quickblox-ios-sdk/issues/962
