### ISSUE TITLE
How to implement CallKit while app is in Background or Kill ?

### ISSUE THREAD

**Issue by testingmyaccount** [QuickBlox/quickblox-ios-sdk#970]
In demo code i found that CallKit incoming call screen is appear when app is active, but nothing happen except notification while doing call when recipient app is in background or kill. Can you please help me on this how can i achieve this. I am familiar with Twilio and Sinch and i know they provides methods which works at the time of call when app is in background or kill.
Is there any extra set up i need to do i.e VOIP or anything else ?
Please help me on this as soon as possible.

**Comment by Raikerian** [comment]
Hi,

In order to receive calls in background please setup VOIP push certificate in your admin panel first: https://quickblox.com/developers/SimpleSample-messages_users-ios

**Comment by testingmyaccount** [comment]
i have already uploaded the VOIP certificates, but how i can get that which method has been call when get the incoming call & receive the call

**Comment by Raikerian** [comment]
Are you using our video sample in the current repository? If so, here are Apple Push Kit methods that you need to know about: https://github.com/QuickBlox/quickblox-ios-sdk/blob/master/sample-videochat-webrtc/sample-videochat-webrtc/Components/Users/ViewControllers/UsersViewController/UsersViewController.m#L539-L555
That method gets triggered every time you receive VOIP push, and if it's not, then it means that there is no push to receive. You will need to check push queue in admin panel for that. Also please attach logs so we can check whether the subscription is there.

**Comment by testingmyaccount** [comment]
Still i didn't receive any VOIP notification when app is in Background Or Kill in this example. Also none of PKPushRegistryDelegate methods called when app is in background/kill. It is only working when app is in active mode and methods under this QBWebRTCChatDelegate getting called.
 
We are working with Swift as our development language. And i did VOIP related set up but still very confused on which methods i need to use when i get VOIP notification. Also i tried with information which i am getting in VOIP notification but the information i am getting is not sufficient. 
So please let me know what will be my VOIP notification PAYLOAD or it will be maintain by QuickBlox itself ?
Also in our app we are getting called above mention method but what will be next which is required to start call. 

Can you please provide any example on this, if it is then it will be very helpful. Let me know if you need more information.

**Comment by Raikerian** [comment]
Please take a look at the sample-videochat in the current repository. Apple PushKit related stuff is in UsersViewController class, and CallKit related stuff is in CallKitManager class.

**Comment by Pro100Andrey** [comment]
Hi @testingmyaccount, any updates?

**Comment by raheeshishan** [comment]
call kit with distribution certificate backgroud not working

**Comment by vineeshLee** [comment]
hi iam not getting call when the Android App app is closed quickblox onReceiveNewSession not getting invoked,is there any option to add callKit like IOS in android to solve this problem,please help.
