### ISSUE TITLE
QBCore currentUser object is nil

### ISSUE THREAD

**Issue by vineeshtp** [QuickBlox/quickblox-ios-sdk#972]
Have an issue while integrating Videochat with existing project.

In the Existing project already implemented text chat.
Now I need to integrate Video and Audio with the same.
I seen that in the Video and Audio integration throughout the sample code, It uses **QBCore** class but, in the chat doesn't contains the same.
By using QBCore there is no API to login with QuickBlox  account, it have signup option and login with currentUser so it always creating new users.

If we sign in using  QBRequest in chat application, 
**QBCore** currentuser object is nil,  QBCore is used in Video/Audio call sample application, which is used throughout used for the same.

So, Couldn't access the same in Chat application

**New Issue Checklist**

 - [ ] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [ ] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    | e.g. 8.0                                    |                                          
Quickblox iOS SDK version      | e.g. 2.7.6                                  |
QuickbloxWebRTC SDK version    | e.g. 2.2.1                                  |                               
Xcode Version                  | e.g. Xcode 8.1                              |
Repro with our demo sample     | e.g. does it happen with our demo sample?   |

**Did this work before?**

**Expected behavior**

**Actual behavior**

**Logs**

*Please use the following template for logs:*

To enable full logs use the following code:
```objc
[QBSettings setLogLevel:QBLogLevelDebug];
[QBSettings enableXMPPLogging];
```

<details>
<summary>Title for logs </summary>

```logos

// Your logs here

```

</details>

**Steps to reproduce the behavior**

**Any others comments**

**Comment by Pro100Andrey** [comment]
Hi @vineeshtp Could you provide full logs ?

To enable full logs use the following code:

```objc
[QBSettings setLogLevel:QBLogLevelDebug];
[QBSettings enableXMPPLogging];
```

Use gist.github.com to deliver logs.

Thanks

**Comment by Pro100Andrey** [comment]
https://github.com/QuickBlox/quickblox-ios-sdk/blob/0cc178065f25dc3d7680a4a762c8fcda158cb7c8/sample-videochat-webrtc/sample-videochat-webrtc/Components/Core/QBCore.m#L99

**Comment by vineeshtp** [comment]
Sorry,

Now it is working.
I hope missed some thing earlier.


Thanks & Regards,

 Vineesh TP

**Comment by Pro100Andrey** [comment]
Hi @vineeshtp, Check Q-municate for login, signiup logic:

-  `login` view controller 
https://github.com/QuickBlox/quickblox-ios-sdk/blob/0cc178065f25dc3d7680a4a762c8fcda158cb7c8/sample-videochat-webrtc/sample-videochat-webrtc/Components/Core/QBCore.m#L99

- `signup`  with facebook view controller 

https://github.com/QuickBlox/q-municate-ios/blob/master/Q-municate/Scenes/Auth/Welcome%20screen/QMWelcomeScreenViewController.m

**Comment by vineeshtp** [comment]
Some times I got the same issue.

Here is the scenario :
1. loggedout by call

QBCore.instance().logout()


2. Login Again by using QBRequest using email Id


Please find the below log:-

*2018-03-23 22:17:39.665362+0530 VideoChat[1062:404526] [DYMTLInitPlatform]
platform initialization successful*

*2018-03-23 22:17:39.906 rtc::[RTCClient] iPhone6,2, 11.2.5, SDK: 2.6.3,
webrtc: 18213*

*2018-03-23 22:17:39.909 rtc::[RTCClient] Waiting for QBChat to connect*

*2018-03-23 22:17:39.972166+0530 VideoChat[1062:404373] [MC] Lazy loading
NSBundle MobileCoreServices.framework*

*2018-03-23 22:17:39.974095+0530 VideoChat[1062:404373] [MC] Loaded
MobileCoreServices.framework*

*2018-03-23 22:17:42.260443+0530 VideoChat[1062:404536] [QBCore]:
Request[1]:*

*POST URL:https://api.quickblox.com/login.json
<https://api.quickblox.com/login.json>*

*headers: {*

*    "Accept-Language" = "en-IN;q=1";*

*    "Content-Type" = "application/x-www-form-urlencoded";*

*    "QB-OS" = "iOS 11.2.5";*

*    "QB-SDK" = "iOS 2.14";*

*    "QB-Token" = 49e1a46a4f86761c71ba056315f0629fb0010e59;*

*    "QuickBlox-REST-API-Version" = "0.1.1";*

*    "User-Agent" = "VideoChat/1.0 (iPhone; iOS 11.2.5; Scale/2.00)";*

*}*

*parameters: {*

*    email = "v@v.com <v@v.com>";*

*    password = 12345678;*

*}*

*2018-03-23 22:17:45.375479+0530 VideoChat[1062:404514] [QBCore]:
Response[1]:*

*headers: {*

*    "Access-Control-Allow-Origin" = "*";*

*    "Cache-Control" = "no-cache";*

*    Connection = "keep-alive";*

*    "Content-Length" = 371;*

*    "Content-Type" = "application/json; charset=utf-8";*

*    Date = "Fri, 23 Mar 2018 16:47:45 GMT";*

*    Duration = "3.112023";*

*    "QB-Token-ExpirationDate" = "2018-03-23 18:47:45 UTC";*

*    "QuickBlox-REST-API-Version" = "0.1.1";*

*    Server = "openresty/1.9.15.1 <http://1.9.15.1>";*

*    "Set-Cookie" = "_mkra_ctxt=a885362e1d16e44f2712b35a7e9e0956--202;
path=/; max-age=5; HttpOnly; secure";*

*    Status = "202 Accepted";*

*    "Strict-Transport-Security" = "max-age=31536000";*

*    "X-Content-Type-Options" = nosniff;*

*    "X-Frame-Options" = SAMEORIGIN;*

*    "X-Request-Id" = "7358a176-a611-4cbc-bdd3-569127310006";*

*    "X-Runtime" = "0.034368";*

*    "X-XSS-Protection" = "1; mode=block";*

*}*

*object: {*

*    user =     {*

*        "blob_id" = "<null>";*

*        "created_at" = "2018-03-23T16:06:30Z";*

*        "custom_data" = "";*

*        email = "v@v.com <v@v.com>";*

*        "external_user_id" = "<null>";*

*        "facebook_id" = "<null>";*

*        "full_name" = Vineesh;*

*        id = 45731476;*

*        "last_request_at" = "2018-03-23T16:47:45Z";*

*        login = "v@v.com <v@v.com>";*

*        "owner_id" = 636;*

*        phone = "";*

*        "twitter_digits_id" = "<null>";*

*        "twitter_id" = "<null>";*

*        "updated_at" = "2018-03-23T16:47:45Z";*

*        "user_tags" = "<null>";*

*        website = "<null>";*

*    };*

*}*

*2018-03-23 22:17:45.597 rtc::[RTCClient] Waiting for QBChat to connect*

*2018-03-23 22:17:45.626 rtc::[QBRTCAudioSession] Initializing
QBRTCAudioSession using configuration: <QBRTCAudioSessionConfiguration:
0x107e495d0, Category: AVAudioSessionCategoryPlayAndRecord, Category
options: 2, Mode: AVAudioSessionModeVoiceChat>*

*2018-03-23 22:17:45.945 rtc::[QBRTCAudioSession] Current audio device was
updated to Receiver*

*2018-03-23 22:17:45.946 rtc::[QBRTCAudioSession] Trying to initialize
QBRTCAudioSession while it's already has been initialized. Deinitialize
instance first.*

*2018-03-23 22:17:45.947 rtc::[CAMC] Initializing QBRTCCameraCapture with
video format: <QBRTCVideoFormat:0x107e50220, dimensions: 640x480, frame
rate: 21, pixel format: 420f>*

*2018-03-23 22:17:45.962 rtc::[CAMC] Starting QBRTCCameraCapture capture
session.*

*nil*

*QBCore- Current user :*

*2018-03-23 22:17:45.996335+0530 VideoChat[1062:404540] [QBCore]:
Request[2]:*

*GET URL:https://api.quickblox.com/users/by_tags.json?tags=doctor
<https://api.quickblox.com/users/by_tags.json?tags=doctor>*

*headers: {*

*    "Accept-Language" = "en-IN;q=1";*

*    "QB-OS" = "iOS 11.2.5";*

*    "QB-SDK" = "iOS 2.14";*

*    "QB-Token" = 49e1a46a4f86761c71ba056315f0629fb0010e59;*

*    "QuickBlox-REST-API-Version" = "0.1.1";*

*    "User-Agent" = "VideoChat/1.0 (iPhone; iOS 11.2.5; Scale/2.00)";*

*}*

*parameters: {*

*    tags = doctor;*

*}*

*2018-03-23 22:17:46.013742+0530 VideoChat[1062:404536] [MC] System group
container for systemgroup.com.apple.configurationprofiles path is
/private/var/containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles*

*2018-03-23 22:17:46.191545+0530 VideoChat[1062:404536] [MC] Reading from
public effective user settings.*

*2018-03-23 22:17:46.241 rtc::[QBRTCAudioSession] Switched from Speaker to
Speaker port. Reason: The category of the session object changed or session
was just activated.*

*2018-03-23 22:17:46.251 rtc::Updating device: <AVCaptureFigVideoDevice:
0x107e92060 [Front
Camera][com.apple.avfoundation.avcapturedevice.built-in_video:1]> with
video format: <AVCaptureDeviceFormat: 0x1049d8b60 'vide'/'420f'  640x 480,
{ 1- 30 fps}, fov:55.200, max zoom:60.00 (upscales @2.00), ISO:47.0-1504.0,
SS:0.000031-1.000000>*

*2018-03-23 22:17:46.256 rtc::[QBRTCAudioSession] Switched from Receiver to
Speaker port. Reason: The output route was overridden by the app.*

*2018-03-23 22:17:46.472 rtc::[CAMC] Capture session started.*

*2018-03-23 22:17:46.697360+0530 VideoChat[1062:404540] [QBCore]:
Response[2]:*

*headers: {*

*    "Access-Control-Allow-Origin" = "*";*

*    "Cache-Control" = "max-age=0, private, must-revalidate";*

*    Connection = "keep-alive";*

*    "Content-Length" = 415;*

*    "Content-Type" = "application/json; charset=utf-8";*

*    Date = "Fri, 23 Mar 2018 16:47:46 GMT";*

*    Duration = "0.706793";*

*    Etag = "W/\"74f1dbff5e5f1556440db7d660a168ce\"";*

*    "QB-Token-ExpirationDate" = "2018-03-23 18:47:45 +0000";*

*    "QuickBlox-REST-API-Version" = "0.1.1";*

*    Server = "openresty/1.9.15.1 <http://1.9.15.1>";*

*    "Set-Cookie" = "_mkra_ctxt=24c19cabbeb239b256ea77264bf924bd--200;
path=/; max-age=5; HttpOnly; secure";*

*    Status = "304 Not Modified";*

*    "Strict-Transport-Security" = "max-age=31536000, max-age=15768000;";*

*    "X-Content-Type-Options" = nosniff;*

*    "X-Frame-Options" = SAMEORIGIN;*

*    "X-Request-Id" = "b541a7e1-0115-4a80-bba1-49c627daf8d4";*

*    "X-Runtime" = "0.129697";*

*    "X-XSS-Protection" = "1; mode=block";*

*}*

*object: {*

*    "current_page" = 1;*

*    items =     (*

*                {*

*            user =             {*

*                "blob_id" = "<null>";*

*                "created_at" = "2018-03-22T16:40:49Z";*

*                "custom_data" = "";*

*                email = "s@s.com <s@s.com>";*

*                "external_user_id" = "<null>";*

*                "facebook_id" = "<null>";*

*                "full_name" = Saam;*

*                id = 45669013;*

*                "last_request_at" = "<null>";*

*                login = "s@s.com <s@s.com>";*

*                "owner_id" = 636;*

*                phone = "";*

*                "twitter_digits_id" = "<null>";*

*                "twitter_id" = "<null>";*

*                "updated_at" = "2018-03-23T01:09:21Z";*

*                "user_tags" = doctor;*

*                website = "<null>";*

*            };*

*        }*

*    );*

*    "per_page" = 10;*

*    "total_entries" = 1;*

*}*

*0*

*nil*

*Id: 45669013*



Thanks & Regards,

 Vineesh TP

**Comment by vineeshtp** [comment]
Still the issue open.


Thanks & Regards,

 Vineesh TP
