### ISSUE TITLE
'Quickblox-WebRTC' uses the unencrypted http protocol to transfer the Pod.

### ISSUE THREAD

**Issue by truemetal** [QuickBlox/quickblox-ios-sdk#974]
Quickblox-WebRTC (2.6.3)

`[!] 'Quickblox-WebRTC' uses the unencrypted http protocol to transfer the Pod. Please be sure you're in a safe network with only trusted hosts in there. Please reach out to the library author to notify them of this security issue.
`

![screen shot 2018-03-24 at 21 20 27](https://user-images.githubusercontent.com/2472186/37868056-7d862992-2fa9-11e8-9023-2f76475debcb.png)

**Comment by Pro100Andrey** [comment]
Hi @truemetal, thank you for informing us!

**Comment by Pro100Andrey** [comment]
Hi @truemetal, fixed (v2.7 - Mar 28, 2018)

[Changelog](https://quickblox.com/developers/Sample-webrtc-ios#Framework_changelog)

Thanks!
