### ISSUE TITLE
CallKit is not working when I call from other device, but it works in sample project

### ISSUE THREAD

**Issue by hassan31** [QuickBlox/quickblox-ios-sdk#975]
Hello Dear,

I've been facing a serious issue on video calling. When I run your sample project on both devices, then it works really fine, whenever I receive video call with native CallKit UI on receiver side.

But When I implemented the same behaviour same code in my project, then I don't receive Native CallKit UI on receiver end, However I tried to show Custom Incoming call UI on behalf of CallKit UI, then that works... 

Can you please guide me on this what I'm missing in my project. I can send you my project if you want.

Look forward to hear from you.
Thanks,

**Comment by Raikerian** [comment]
Hi,

Please check that you have correctly setup Apple CallKit and VOIP push notifications for that, use our [quick guide](https://quickblox.com/developers/Sample-webrtc-ios#Apple_CallKit) to check things up.
Basically, whenever you are receiving VOIP push notification with a specific key, that identifies that that VOIP push notification is about a call, you need to login into chat to then receive QBRTCSession, and after that show Apple CallKit UI with their API.

**Comment by hassan31** [comment]
Thanks a lot for your help. Now its working. :)

**Comment by Raikerian** [comment]
Great to hear that you've managed to fix it. If you will have any other problems please let us know by creating a separate issue.
