### ISSUE TITLE
Is it Possible to make a successfull call when receiver app is terminated or in background

### ISSUE THREAD

**Issue by mayur9333** [QuickBlox/quickblox-ios-sdk#976]
Hi, i need to call user when receiver end App is in background or terminated. please suggest
thank you,

**Comment by Raikerian** [comment]
Hi,

Yes, it is possible, for that you will need to use Apple CallKit, with VOIP push notifications. You can check [quick guide here](https://quickblox.com/developers/Sample-webrtc-ios#Apple_CallKit), as well as an example within our sample-videochat in the current repository.

**Comment by Pro100Andrey** [comment]
Hi @mayur9333, any updates?

**Comment by mayur9333** [comment]
Not check yet @Pro100Andrey  and you @Raikerian

**Comment by Pro100Andrey** [comment]
@mayur9333, ок
