### ISSUE TITLE
UIKit thread sanitizer issue - RTC

### ISSUE THREAD

**Issue by truemetal** [QuickBlox/quickblox-ios-sdk#977]
JFYI - this happens if current session is receiving remote video track
Cheers

<img width="1405" alt="item-0_and_airportextra_and_item-0_and_item-0_and_item-0_and_item-0_and_applebluetoothextra" src="https://user-images.githubusercontent.com/2472186/37915397-1a2c87b8-3122-11e8-9796-4475fbb22351.png">

**Comment by Pro100Andrey** [comment]
Hi @truemetal, fixed (v2.7 - Mar 28, 2018)

[Changelog](https://quickblox.com/developers/Sample-webrtc-ios#Framework_changelog)

Thanks!
