### ISSUE TITLE
Problem sending frames from ReplayKit via QBRTCVideoCapture

### ISSUE THREAD

**Issue by truemetal** [QuickBlox/quickblox-ios-sdk#978]
I have a subclass of `QBRTCVideoCapture` that sends frames like this:

```swift
   func sendBuffer(buffer: CMSampleBuffer) {
        videoQueue.async {
            guard let buffer = CMSampleBufferGetImageBuffer(buffer) else { abort() }
            let frame = QBRTCVideoFrame(pixelBuffer: buffer, videoRotation: ._0)
            self.send(frame)
        }
    }
```

The frames appear on the other side's `QBRTCRemoteVideoView` for several seconds, then on sender's side I see multitude of these errors in terminal: 
```logos
[carc] CAReportingClient.mm:320:-[CAReportingClient sendMessage:category:type:reporters:]_block_invoke: The operation couldn’t be completed. No valid RTCReporting and the session was started
2018-03-27 15:12:51.976283+0300 sender[551:55992] [carc] CAReportingClient.mm:320:-[CAReportingClient sendMessage:category:type:reporters:]_block_invoke: The operation couldn’t be completed. No valid RTCReporting and the session was started
2018-03-27 15:13:01.966826+0300 sender[551:55992] [carc] CAReportingClient.mm:320:-[CAReportingClient sendMessage:category:type:reporters:]_block_invoke: The operation couldn’t be completed. No valid RTCReporting and the session was started
2018-03-27 15:13:11.976554+0300 sender[551:56902] [carc] CAReportingClient.mm:320:-[CAReportingClient sendMessage:category:type:reporters:]_block_invoke: The operation couldn’t be completed. No valid RTCReporting and the session was started
```

PODS:
  - QuickBlox (2.16)
  - Quickblox-WebRTC (2.6.3)

**Comment by Pro100Andrey** [comment]
Hi @truemetal, Could you provide more info about CMSampleBuffer:

- width, height
- pixel format (for example kCVPixelFormatType_420YpCbCr8Planar or other)

Thanks!

**Comment by Pro100Andrey** [comment]
@truemetal ,

Please capture logs in the call. To enable them and this to your config:
```swift
QBRTCConfig.setLogLevel(.verboseWithWebRTC)
```
Also enable stats reports:
To enable stats report first enable them by setting config:
```swift
QBRTCConfig.setStatsReportTimeInterval(1.0)
```
And then print them in QBRTCClientDelegate:
```swift
func session(_ session: QBRTCBaseSession, updatedStatsReport report: QBRTCStatsReport, forUserID userID: NSNumber) {
    let sess = session as! QBRTCSession
    print("UserID:\(userID)\nSessionID:\(sess.id)\n\(report.statsString())")
}
```

Thanks!

**Comment by truemetal** [comment]
@Pro100Andrey here's info about buffer

> <CVPixelBuffer 0x10b5468f0 width=1080 height=1920 pixelFormat=420f iosurface=0x10b524d30 planes=2>
> <Plane 0 width=1080 height=1920 bytesPerRow=1088>
> <Plane 1 width=540 height=960 bytesPerRow=1088>
> <attributes=<CFBasicHash 0x10b546c30 [0x1b79a4310]>{type = immutable dict, count = 1,
> entries =>
> 	0 : <CFString 0x1b06fd758 [0x1b79a4310]>{contents = "PixelFormatDescription"} = <CFBasicHash 0x10b5363d0 [0x1b79a4310]>{type = immutable dict, count = 12,
> entries =>
> 	1 : <CFString 0x1b06fdd58 [0x1b79a4310]>{contents = "FillExtendedPixelsCallback"} = <CFData 0x104595fc0 [0x1b79a4310]>{length = 24, capacity = 24, bytes = 0x000000000000000048c46f89010000000000000000000000}
> 	5 : <CFString 0x1b06fda18 [0x1b79a4310]>{contents = "ContainsAlpha"} = <CFBoolean 0x1b79a4878 [0x1b79a4310]>{value = false}
> 	6 : <CFString 0x1b06fdbf8 [0x1b79a4310]>{contents = "ContainsYCbCr"} = <CFBoolean 0x1b79a4868 [0x1b79a4310]>{value = true}
> 	7 : <CFString 0x1b06fd6d8 [0x1b79a4310]>{contents = "OpenGLESCompatibility"} = <CFBoolean 0x1b79a4868 [0x1b79a4310]>{value = true}
> 	9 : <CFString 0x1b06fd698 [0x1b79a4310]>{contents = "IOSurfaceOpenGLESTextureCompatibility"} = <CFBoolean 0x1b79a4868 [0x1b79a4310]>{value = true}
> 	10 : <CFString 0x1b06fdc58 [0x1b79a4310]>{contents = "ComponentRange"} = <CFString 0x1b06fdc98 [0x1b79a4310]>{contents = "FullRange"}
> 	12 : <CFString 0x1b06fd678 [0x1b79a4310]>{contents = "IOSurfaceCoreAnimationCompatibility"} = <CFBoolean 0x1b79a4868 [0x1b79a4310]>{value = true}
> 	13 : <CFString 0x1b06fd6b8 [0x1b79a4310]>{contents = "IOSurfaceOpenGLESFBOCompatibility"} = <CFBoolean 0x1b79a4868 [0x1b79a4310]>{value = true}
> 	15 : <CFString 0x1b06fd9b8 [0x1b79a4310]>{contents = "PixelFormat"} = <CFNumber 0xb000000343230662 [0x1b79a4310]>{value = +875704422, type = kCFNumberSInt32Type}
> 	18 : <CFString 0x1b06fdbd8 [0x1b79a4310]>{contents = "BitsPerComponent"} = <CFNumber 0xb000000000000082 [0x1b79a4310]>{value = +8, type = kCFNumberSInt32Type}
> 	21 : <CFString 0x1b06fdc18 [0x1b79a4310]>{contents = "ContainsRGB"} = <CFBoolean 0x1b79a4878 [0x1b79a4310]>{value = false}
> 	22 : <CFString 0x1b06fda38 [0x1b79a4310]>{contents = "Planes"} = (
>         {
>         BitsPerBlock = 8;
>         BlackBlock = <00>;
>     },
>         {
>         BitsPerBlock = 16;
>         BlackBlock = <8080>;
>         HorizontalSubsampling = 2;
>         VerticalSubsampling = 2;
>     }
> )
> }
> 
> }
>  propagatedAttachments=<CFBasicHash 0x10b546e20 [0x1b79a4310]>{type = mutable dict, count = 0,
> entries =>
> }
>  nonPropagatedAttachments=<CFBasicHash 0x10b546cb0 [0x1b79a4310]>{type = mutable dict, count = 0,
> entries =>
> }
> >
>

**Comment by truemetal** [comment]
@Pro100Andrey here's the logs: https://pastebin.com/V3MdLK1R

**Comment by Pro100Andrey** [comment]
@truemetal, from your logs:
> VS (input) 1080x1920@59fps | (sent) 540x960@57fps

webrtc is currently supporting only 30 fps

**Comment by truemetal** [comment]
@Pro100Andrey after throttling to 30fps, the problem unfortunately, persists
Here're the logs: https://pastebin.com/AjCLuYcg

**Comment by Pro100Andrey** [comment]
@truemetal, from your logs:

```logs
(vie_encoder.cc:673): Video frame parameters changed: dimensions=810x1440, texture=1.
(video_sender.cc:129):  max bitrate 2500 start bitrate 650 max frame rate 60 max payload size 1200
(h264_video_toolbox_encoder.mm:491): Failed to encode frame with code: -12902
(video_sender.cc:348): Failed to encode frame. Error code: -1
(vie_encoder.cc:785): OnBitrateUpdated, bitrate 652526 packet loss 0 rtt 14
(vie_encoder.cc:785): OnBitrateUpdated, bitrate 652526 packet loss 0 rtt 14
(h264_video_toolbox_encoder.mm:681): H264 encode failed.
```

-> H264 encode failed after change dimensions in to 810x1440

check demention <   `810x1440` for example `540x960`

Thanks!

**Comment by truemetal** [comment]
@Pro100Andrey do you mean like downsample the buffer before sending it?

**Comment by Pro100Andrey** [comment]
@truemetal yes

**Comment by Pro100Andrey** [comment]
@truemetal without downsample should work in vp8 codec

**Comment by Pro100Andrey** [comment]
Hi @truemetal, Check code bellow:
```swift
import UIKit
import QuickbloxWebRTC
import ReplayKit
import Accelerate

class YourGameViewController: UIViewController {

    override func viewDidLoad() {
        super.viewDidLoad()
        RPScreenRecorder.shared()
        RPScreenRecorder.shared().startCapture(handler: { (buffer, type, err) in
            let source = CMSampleBufferGetImageBuffer(buffer)
            if (source != nil) {
                
                let pixelBuff = self.resizePixelBuffer(source!, width: 540, height: 960)
                print(pixelBuff)
            }
            
        }) { (err) in
            
        }
    }
    
    /**
     Resizes a CVPixelBuffer to a new width and height.
     */
    public func resizePixelBuffer(_ pixelBuffer: CVPixelBuffer,
                                  width: Int, height: Int) -> CVPixelBuffer? {
        
        return resizePixelBuffer(pixelBuffer, cropX: 0, cropY: 0,
                                 cropWidth: CVPixelBufferGetWidth(pixelBuffer),
                                 cropHeight: CVPixelBufferGetHeight(pixelBuffer),
                                 scaleWidth: width, scaleHeight: height)
    }


    public func resizePixelBuffer(_ srcPixelBuffer: CVPixelBuffer,
                                  cropX: Int,
                                  cropY: Int,
                                  cropWidth: Int,
                                  cropHeight: Int,
                                  scaleWidth: Int,
                                  scaleHeight: Int) -> CVPixelBuffer? {
        
        CVPixelBufferLockBaseAddress(srcPixelBuffer, CVPixelBufferLockFlags(rawValue: 0))
        guard let srcData = CVPixelBufferGetBaseAddress(srcPixelBuffer) else {
            print("->>Error: could not get pixel buffer base address")
            return nil
        }
        let srcBytesPerRow = CVPixelBufferGetBytesPerRow(srcPixelBuffer)
        let offset = cropY*srcBytesPerRow + cropX*4
        var srcBuffer = vImage_Buffer(data: srcData.advanced(by: offset),
                                      height: vImagePixelCount(cropHeight),
                                      width: vImagePixelCount(cropWidth),
                                      rowBytes: srcBytesPerRow)
        
        let destBytesPerRow = scaleWidth*4
        guard let destData = malloc(scaleHeight*destBytesPerRow) else {
            print("->>Error: out of memory")
            return nil
        }
        var destBuffer = vImage_Buffer(data: destData,
                                       height: vImagePixelCount(scaleHeight),
                                       width: vImagePixelCount(scaleWidth),
                                       rowBytes: destBytesPerRow)
        
        let error = vImageScale_ARGB8888(&srcBuffer, &destBuffer, nil, vImage_Flags(0))
        CVPixelBufferUnlockBaseAddress(srcPixelBuffer, CVPixelBufferLockFlags(rawValue: 0))
        if error != kvImageNoError {
            print("->>Error:", error)
            free(destData)
            return nil
        }
        
        let releaseCallback: CVPixelBufferReleaseBytesCallback = { _, ptr in
            if let ptr = ptr {
                free(UnsafeMutableRawPointer(mutating: ptr))
            }
        }
        
        let pixelFormat = CVPixelBufferGetPixelFormatType(srcPixelBuffer)
        var dstPixelBuffer: CVPixelBuffer?
        let status = CVPixelBufferCreateWithBytes(nil, scaleWidth, scaleHeight,
                                                  pixelFormat, destData,
                                                  destBytesPerRow, releaseCallback,
                                                  nil, nil, &dstPixelBuffer)
        if status != kCVReturnSuccess {
            print("->>Error: could not create new pixel buffer")
            free(destData)
            return nil
        }
        return dstPixelBuffer
    }
}
```

**Comment by Pro100Andrey** [comment]
@truemetal, any updates?

**Comment by truemetal** [comment]
@Pro100Andrey thanks for the code! Looks like something wrong is now with pixel format after using that function: 

I get a lot of these: 
> 2018-03-27 19:18:31.922 rtc::Video capturer received unsupported non-planar frame format.

**Comment by Pro100Andrey** [comment]
@truemetal, Sorry my mistake. Should be:

```swift
class ScreenCapture: QBRTCCameraCapture {
    
    open func startCapture() {
        
        self.adaptOutputFormat(toWidth: 340, height: 420, fps: 3)
        RPScreenRecorder.shared().startCapture(handler: { (smapleBuffer, bufferType, error) in
            let source = CMSampleBufferGetImageBuffer(smapleBuffer)
            let frame = QBRTCVideoFrame(pixelBuffer: source, videoRotation: ._0)
            self.send(frame)
        }) { (err) in
        }
    }
}
```

**Comment by Pro100Andrey** [comment]
@truemetal Use AdaptOutputFormat(....) method after setting the capture to localmediasteam videotrack:

self.session.localMediaStream.videoTrack.videoCapture = self.cameraCapture;

**Comment by Pro100Andrey** [comment]
Hi @truemetal, any updates?

**Comment by truemetal** [comment]
@Pro100Andrey thanks for the quick responses, `adaptOutputFormat` actually works!

I've also tried setting vp8 codec, just to try it out, like so: 

```swift
let c = QBRTCConfig.mediaStreamConfiguration()
        c.videoCodec = .VP8
        QBRTCConfig.setMediaStreamConfiguration(c)
```

I still get these errors, which hints that setting vp8 was not successful: 

> (h264_video_toolbox_encoder.mm:681): H264 encode failed.

I've tried setting media stream config both in app delegate (after and before initializing RTCClient), and also after assigning screen vide capture.

**Comment by Pro100Andrey** [comment]
@truemetal Use  QBRTCConfig.mediaStreamConfiguration().videoCodec = .VP8 before start/accept call

**Comment by truemetal** [comment]
If I'm setting it like this in AppDelegate, I still get h264 errors
```swift
        QBRTCClient.initializeRTC()
        QBRTCConfig.mediaStreamConfiguration().videoCodec = .VP8
```

Here's a log: https://pastebin.com/QZUi0C5V

**Comment by Pro100Andrey** [comment]
@truemetal my skype this.andrey

**Comment by truemetal** [comment]
Thanks @Pro100Andrey ! 

<img width="909" alt="problem_sending_frames_from_replaykit_via_qbrtcvideocapture_ _issue__978_ _quickblox_quickblox-ios-sdk" src="https://user-images.githubusercontent.com/2472186/38028248-0a918234-329b-11e8-91dd-a517b181082e.png">

Missed this part, after setting that to vp8 on both devices (not only the sender) I see different log messages: 

> (vie_encoder.cc:142): Incoming frame dropped due to that the encoder is blocked.

But that I guess is expected.

**Comment by Pro100Andrey** [comment]
> Due to the fact that encoding has to be set on both devices before call starts, I understand, I can't specify codec per video capture? 

No.

My suggestion -  use h264 for camera without self.adaptOutputFormat  and  h264  for screen with self.adaptOutputFormat.

Because VP8 - software codec for iOS, h264 - hardware

**Comment by Pro100Andrey** [comment]
If you will have any other problems please let us know by creating a separate issue.

**Comment by truemetal** [comment]
Thanks
