### ISSUE TITLE
VideoCaptureSession's sampleBufferDelegate returning nil

### ISSUE THREAD

**Issue by RubenBenBen** [QuickBlox/quickblox-ios-sdk#982]
**New Issue Checklist**

 - [X] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [X] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    |  9.3                                   |                                          
Quickblox iOS SDK version      |  latest                               |
QuickbloxWebRTC SDK version    | latest                                  |                               
Xcode Version                  | Xcode 9.2                             |
Repro with our demo sample     | yes   |

In the ```sample-videochat-webrtc``` project when making a video call, in ```CallViewController``` class I am trying to access the ```sampleBufferDelegate``` of the session's videoOutput:
```
        NSArray <AVCaptureVideoDataOutput *>*outPuts = self.cameraCapture.captureSession.outputs;
        if (outPuts.count) {
            NSLog(@"%@", outPuts[0].sampleBufferDelegate);
        }
```
I want to override the ```sampleBufferDelegate``` to another object to be able listen to ``` AVCaptureVideoDataOutputSampleBufferDelegate``` 's  ``` -(void)captureOutput:(AVCaptureOutput *)output didOutputSampleBuffer:(CMSampleBufferRef)sampleBuffer fromConnection:(AVCaptureConnection *)connection ```   method, and then call the original ```sampleBufferDelegate```'s same method. 1 times out of 10 I get the object and can override it. But most of the time the original ```sampleBufferDelegate``` is ```nil``` when I try to get it, so it is being set some time later and I can't find the place where it is done. Can you please help me with that? Or is there maybe another way to get the ```CMSampleBufferRef``` object after ```didOutputSampleBuffer``` is being called?

P.S. I am using ```kCVPixelFormatType_32ARGB``` format type

**Comment by pro100andrey** [comment]
Hi @RubenBenBen,

> I want to override the sampleBufferDelegate to another object to be able listen to AVCaptureVideoDataOutputSampleBufferDelegate 's -(void)captureOutput:(AVCaptureOutput *)output didOutputSampleBuffer:(CMSampleBufferRef)sampleBuffer fromConnection:(AVCaptureConnection *)connection method, and then call the original sampleBufferDelegate's same method. 1 times out of 10 I get the object and can override it. But most of the time the original sampleBufferDelegate is nil when I try to get it, so it is being set some time later and I can't find the place where it is done. Can you please help me with that? Or is there maybe another way to get the CMSampleBufferRef object after didOutputSampleBuffer is being called?

QBRTCCameraCapture is the final object. But you can implement a subclass of the QBRTCVideoCapture and use camera your way.

You can see our screen sharing example on how we are using ARGB format here: https://github.com/QuickBlox/quickblox-ios-sdk/blob/master/sample-videochat-webrtc/sample-videochat-webrtc/ViewControllers/SharingViewController/QBRTCScreenCapture.m

**Comment by pro100andrey** [comment]
@RubenBenBen, If you will have any other problems or questions please let us know by creating a separate issue.

Thanks!
