### ISSUE TITLE
can't keep videoFormat to kCVPixelFormatType_32ARGB

### ISSUE THREAD

**Issue by RubenBenBen** [QuickBlox/quickblox-ios-sdk#983]
**New Issue Checklist**

 - [X] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [X] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    |  9.3                                   |                                          
Quickblox iOS SDK version      |  latest                               |
QuickbloxWebRTC SDK version    | latest                                  |                               
Xcode Version                  | Xcode 9.2                             |
Repro with our demo sample     | yes   |

In the ```sample-videochat-webrtc``` project when making a video call, in ```CallViewController```, when initializing ```cameraCapture```, I set the video format to ```kCVPixelFormatType_32ARGB```. I even get the log:
```
rtc::[CAMC] Initializing QBRTCCameraCapture with video format: <QBRTCVideoFormat:0x15e94cb0, dimensions: 640x480, frame rate: 30, pixel format: ARGB>
```

But then when I am logging ```videoSettings``` of the session's videoOutput:
```
        NSArray <AVCaptureVideoDataOutput *>*outPuts = self.cameraCapture.captureSession.outputs;
        if (outPuts.count) {
            NSLog(@"%@", outPuts[0].videoSettings);
        }
```
it outputs the following:
```
{
    Height = 480;
    PixelFormatType = 875704422;
    Width = 640;
}
```
where 875704422 is ```420f```, not ```ARGB```. I also noticed that somewhere in the middle of the logs I get the following log:
```
rtc::Updating device: <AVCaptureFigVideoDevice: 0x15e40a00 [Front Camera][com.apple.avfoundation.avcapturedevice.built-in_video:1]> with video format: <AVCaptureDeviceFormat: 0x15e38950 'vide'/'420f'  640x 480, { 2- 30 fps}, fov:54.910, ISO:135.0-2160.0, SS:0.000063-0.500000>
```
So I guess it updates the format from ```ARGB``` to ```420f```. How can I stop it from updating it? I really need the ```ARGB``` format, so I can convert it to ```BGRA``` to do some rendering on the frames.

**Comment by Raikerian** [comment]
Hi,

kCVPixelFormatType_32ARGB is among supported formats. Please show us some code how you are trying to use it.

**Comment by RubenBenBen** [comment]
Hi, I just override the ```videoFormat``` in ```Settings.m```:

```
- (void)load {
    
    NSUserDefaults *defaults = [NSUserDefaults standardUserDefaults];
    
    AVCaptureDevicePosition postion = [defaults integerForKey:kPreferredCameraPosition];
    
    if (postion == AVCaptureDevicePositionUnspecified) {
        //First launch
        postion = AVCaptureDevicePositionFront;
    }
    
    self.preferredCameraPostion = postion;
    
    NSData *videoFormatData = [defaults objectForKey:kVideoFormatKey];
    if (videoFormatData) {
        
        self.videoFormat = [NSKeyedUnarchiver unarchiveObjectWithData:videoFormatData];
        
    }
    else {

        self.videoFormat = [QBRTCVideoFormat defaultFormat];
    }
    
    self.videoFormat = [QBRTCVideoFormat videoFormatWithWidth:self.videoFormat.width height:self.videoFormat.height frameRate:self.videoFormat.frameRate pixelFormat:QBRTCPixelFormatARGB];
    
. . .
}
```

**Comment by Raikerian** [comment]
I have checked it and yeah, as of now `QBRTCCameraCapture` working only with `kCVPixelFormatType_420YpCbCr8BiPlanarFullRange`.
You can, however, subclass of `QBRTCVideoCapture` and use camera your way.

**Comment by Raikerian** [comment]
We will try to fix it in `QBRTCCameraCapture` for the next version of our framework. As of now use suggestion above.

**Comment by RubenBenBen** [comment]
Not sure how can I implement a subclass of ```QBRTCVideoCapture``` having only headers. Can you please provide the ```QBRTCVideoCapture.m``` and ```QBRTCCameraCapture.m``` to see how it should work?
Can you give an approximate time when to anticipate your next version of the framework?
Thanks

**Comment by Raikerian** [comment]
I have just tested it, and AVCaptureVideoDataOutput (which is used by camera capture) does not support `kCVPixelFormatType_32ARGB`.

> Unsupported pixel format type - use -availableVideoCVPixelFormatTypes'

`kCVPixelFormatType_420YpCbCr8BiPlanarFullRange` is the only one for use here. You can see our screen sharing example on how we are using ARGB format here: https://github.com/QuickBlox/quickblox-ios-sdk/blob/master/sample-videochat-webrtc/sample-videochat-webrtc/ViewControllers/SharingViewController/QBRTCScreenCapture.m

**Comment by pro100andrey** [comment]
Hi @RubenBenBen what was the reason behind using kCVPixelFormatType_32BGRA?

**Comment by RubenBenBen** [comment]
@Raikerian thanks for sharing. Yeah, sadly ```kCVPixelFormatType_32ARGB``` is not supported in ```AVCaptureVideoDataOutput```.
@pro100andrey Hi, I want to do some openCV rendering during the video stream, which needs r, g, b components of pixels, that's why I want to use ```ARGB``` or ```BGRA``` format.

**Comment by pro100andrey** [comment]
@RubenBenBen You can use vImage within the `Accelerate.framework` for convert BGRA to ARGB

For swap pixel channels from `BGRA` to `ARGB` use code bellow:

```c
const uint8_t map[4] = { 3, 2, 1, 0};
vImagePermuteChannels_ARGB8888(&src, &dest, map, kvImageNoFlags);
```

**Comment by pro100andrey** [comment]
@RubenBenBen, if you will have any other problems or questions please let us know by creating a separate issue.

Thanks!

**Comment by RubenBenBen** [comment]
Thanks, I've seen that suggestion already in your previous issues. The problem is that if only ```kCVPixelFormatType_420YpCbCr8BiPlanarFullRange``` is supported, I don't have the ```BGRA``` format and that's what I'm trying to deal with: get b, g, r from ```kCVPixelFormatType_420YpCbCr8BiPlanarFullRange``` pixelBuffer.
