### ISSUE TITLE
How do I show Quickblox incoming call if app in background/terminated

### ISSUE THREAD

**Issue by vineeshtp** [QuickBlox/quickblox-ios-sdk#986]
I have implemented quickblox chat,voice and video call.
I could make the call even if app in background.

How can show Quickblox incoming call if app in background or terminated.

If app in background I  am receiving the  **PKPushRegistry** delegate methog.

`func pushRegistry(_ registry: PKPushRegistry, didReceiveIncomingPushWith payload: PKPushPayload, for type: PKPushType) {
        if type == .voIP {
        }   
    }`

To report the incoming call to CallKitManager, the session shall be nil, so can not call this function.

`CallKitManager.instance.reportIncomingCall(withUserIDs: opponentIDs, session: session, uuid: self.callUUID!, onAcceptAction: { 
            }, completion: nil)`

 - [ ] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [ ] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    | e.g. 8.0                                    |                                          
Quickblox iOS SDK version      | e.g. 2.7.6                                  |
QuickbloxWebRTC SDK version    | e.g. 2.2.1                                  |                               
Xcode Version                  | e.g. Xcode 8.1                              |
Repro with our demo sample     | e.g. does it happen with our demo sample?   |

**Did this work before?**

**Expected behavior**

**Actual behavior**

**Logs**

*Please use the following template for logs:*

To enable full logs use the following code:
```objc
[QBSettings setLogLevel:QBLogLevelDebug];
[QBSettings enableXMPPLogging];
```

<details>
<summary>Title for logs </summary>

```logos

// Your logs here

```

</details>

**Steps to reproduce the behavior**

**Any others comments**

**Comment by Pro100Andrey** [comment]
Duplicate with https://github.com/QuickBlox/quickblox-ios-sdk/issues/981
