### ISSUE TITLE
Getting r, g, b values from kCVPixelFormatType_420YpCbCr8BiPlanarFullRange pixel buffer

### ISSUE THREAD

**Issue by RubenBenBen** [QuickBlox/quickblox-ios-sdk#990]
**New Issue Checklist**

 - [X] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [X] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    |  9.3                                   |                                          
Quickblox iOS SDK version      |  latest                               |
QuickbloxWebRTC SDK version    | latest                                  |                               
Xcode Version                  | Xcode 9.2                             |
Repro with our demo sample     | yes   |

Hi again, as we figured out earlier in this issue https://github.com/QuickBlox/quickblox-ios-sdk/issues/983 , ```kCVPixelFormatType_32ARGB``` format is not supported for the videoCapture, so the only option is to use ```kCVPixelFormatType_420YpCbCr8BiPlanarFullRange```. I'm trying to figure out how to get r, g, b components out of 420f format to do some rendering with openCV. Is there a way to do so?

**Comment by pro100andrey** [comment]
@RubenBenBen, https://stackoverflow.com/questions/24090122/converting-a-kcvpixelformattype-420ypcbcr8biplanarfullrange-buffer-to-a-rgb-buff ?

**Comment by pro100andrey** [comment]
@RubenBenBen, But best way implement subclass of QBRTCVideoCapture

**Comment by pro100andrey** [comment]
@RubenBenBen, any updates?

**Comment by RubenBenBen** [comment]
@pro100andrey It works! thanks very much
