### ISSUE TITLE
Missing required architecture i386 when build for profiling

### ISSUE THREAD

**Issue by Serproger** [QuickBlox/quickblox-ios-sdk#993]
**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    | 11.3                                   |                                          
Quickblox iOS SDK version      | 2.1.6                                 |
QuickbloxWebRTC SDK version    | 2.7                            |                               
Xcode Version                  | 9.3                    |

**Expected behavior**

Application that uses quickblox webrtc can be built for profiling.

**Actual behavior**

When building I have this error:

```
ld: warning: ignoring file _/Pods/Quickblox-WebRTC/QuickbloxWebRTC.framework/QuickbloxWebRTC, missing required architecture i386 in file _/Pods/Quickblox-WebRTC/QuickbloxWebRTC.framework/QuickbloxWebRTC (3 slices)
Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_QBRTCVideoFormat", referenced from:
      objc-class-ref in VideoController.o
  "_OBJC_CLASS_$_QBRTCClient", referenced from:
      objc-class-ref in VideoController.o
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_QBRTCAudioSession", referenced from:
      objc-class-ref in VideoController.o
  "_OBJC_CLASS_$_QBRTCConfig", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_QBRTCSession", referenced from:
      objc-class-ref in VideoController.o
  "_OBJC_CLASS_$_QBRTCCameraCapture", referenced from:
      objc-class-ref in VideoController.o
  "_OBJC_CLASS_$_QBRTCRemoteVideoView", referenced from:
      objc-class-ref in VideoController.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

```

**Comment by pro100andrey** [comment]
https://github.com/QuickBlox/quickblox-ios-sdk/issues/793

**Comment by Serproger** [comment]
It's not a duplicate. I've followed all the instructions in your issue, but nothing works. And this error can be observed ONLY when build for profiling (for simulator and for physical device).

**Comment by pro100andrey** [comment]
@Serproger Could you please provide sample project with this issue?

**Comment by pro100andrey** [comment]
<img width="847" alt="screenshot 2018-04-09 10 12 36" src="https://user-images.githubusercontent.com/1109916/38484242-989e69e2-3bde-11e8-94a3-0db6bae55f25.png">

**Comment by pro100andrey** [comment]
@Serproger any updates?

**Comment by Serproger** [comment]
For which project I should set this property? Pods?

**Comment by Serproger** [comment]
Besides that, valid architectures for CocaPods project are i386, x86_x64. Is it valid to update them in the way mentioned in issue 783?

**Comment by pro100andrey** [comment]
For which project I should set this property? Pods?

For your project. For example : Targets - "<Your project name>" -" Build Settings"

**Comment by pro100andrey** [comment]
> Is it valid to update them in the way mentioned in issue 783?

https://github.com/QuickBlox/quickblox-ios-sdk/issues/783


?????

**Comment by Serproger** [comment]
sorry, 793 :)

**Comment by pro100andrey** [comment]
We don't support i386

Besides that, valid architectures for CocaPods project are i386, x86_x64. Is it valid to update them in the way mentioned in issue 793?

Only:
``` logos
(for architecture x86_64):	Mach-O 64-bit dynamically linked shared library x86_64
(for architecture armv7):	Mach-O dynamically linked shared library arm_v7
(for architecture arm64):	Mach-O 64-bit dynamically linked shared library arm64
```

For Profiling, you should set "Build Active Architecture Only" to `yes` for "Debug & Release".

**Comment by pro100andrey** [comment]
@Serproger, any updates?

**Comment by Serproger** [comment]
Yes, setting of "Build Active Architecture Only" works, thanks.

**Comment by pro100andrey** [comment]
@Serproger if you will have any other problems or questions please let us know by creating a separate issue.

Thanks!
